"""Français — détails, beginner_1 (50 questions)."""

D = {
"prophets_251": "Le Coran lui-même donne le nom du Prophète ﷺ : « Muhammad est le Messager d'Allah » (48:29), et encore : « Muhammad n'est le père d'aucun de vos hommes, mais il est le Messager d'Allah et le sceau des prophètes » (33:40). Son nom et sa lignée ouvrent toute biographie classique, et chaque musulman prononce son nom chaque jour dans le témoignage de foi. Le musulman apprend le nom de l'homme qui lui a apporté le Coran, et il l'honore chaque fois qu'il est prononcé.",

"prophets_252": "Ces mots terminent une longue prière qu'Ibrâhîm fait vers la fin de la sourate Ibrâhîm, après avoir installé sa famille dans une vallée sans cultures, près de la Maison sacrée (14:37). Il dit : « Louange à Allah, qui m'a donné, malgré ma vieillesse, Ismâ'îl et Ishâq. Vraiment, mon Seigneur entend bien la prière » (14:39), puis il demande que lui et ses descendants accomplissent la prière (14:40). Les deux fils sont nommés comme des dons reçus tard dans la vie. Le musulman apprend à remercier Allah pour ses enfants comme pour un don, et non comme pour une chose due.",

"prophets_253": "Le verset répond à une fausse affirmation rapportée juste avant lui. La sourate An-Nisâ' rapporte la vantardise de ceux qui disaient avoir tué le Messie, 'Îsâ fils de Maryam, et elle répond : « Ils ne l'ont ni tué ni crucifié, mais cela leur est apparu ainsi » (4:157). Puis vient la vérité : « Allah l'a plutôt élevé vers Lui. Et Allah est Puissant et Sage » (4:158). Le musulman apprend que 'Îsâ n'a pas été tué, qu'Allah a protégé Son messager, et qu'aucun complot ne peut vaincre Son plan.",

"prophets_254": "La sourate Maryam raconte son histoire : « Et mentionne dans le Livre Maryam, quand elle se retira de sa famille vers un lieu situé à l'est » (19:16). Allah lui envoya Son Esprit sous la forme d'un homme ; elle chercha refuge contre lui auprès du Tout Miséricordieux, et il dit qu'il n'était qu'un messager de son Seigneur, venu lui donner un garçon pur (19:17-19). Quand elle demanda comment, il répondit : « Ton Seigneur dit : cela M'est facile » (19:21). Le musulman apprend que 'Îsâ est né par le seul ordre d'Allah, et il honore Maryam comme sa mère.",

"prophets_255": "Avant de créer Âdam, Allah dit aux anges : « Je vais placer sur la terre un successeur » (2:30). Puis « Il apprit à Âdam les noms, tous les noms » (2:31), Il montra aux anges que cette nouvelle créature savait ce qu'eux ne savaient pas, et Il leur ordonna de se prosterner devant lui (2:34). Plus loin, le Coran s'adresse à tous les hommes en les appelant « enfants d'Âdam » (7:26), et il leur rappelle qu'Allah « vous a créés d'un seul être » (4:1). Le musulman apprend que chaque être humain sur terre descend de ce premier homme, honoré par son Créateur avec le savoir.",

"prophets_256": "La sourate Al-Anbiyâ' raconte comment le jeune Ibrâhîm brisa les idoles de son peuple, laissa debout la plus grande, et leur dit de lui demander si elle pouvait parler (21:58-63). Leur réponse fut le feu : « Brûlez-le et secourez vos dieux, si vous voulez agir » (21:68). Allah ordonna alors : « Ô feu, sois fraîcheur et paix pour Ibrâhîm » (21:69), et le verset suivant dit qu'ils voulurent lui nuire, mais qu'Allah fit d'eux les perdants (21:70). Le musulman apprend que le feu ne brûle que par la permission d'Allah, et qu'Il protège celui qui se tient du côté de la vérité.",

"prophets_257": "Allah posa cette question à Mûsâ dans la vallée sacrée de Tuwâ, là où Il lui parla pour la première fois (20:12-13) : « Et qu'y a-t-il dans ta main droite, ô Mûsâ ? » (20:17). Mûsâ répondit : « C'est mon bâton ; je m'appuie dessus, et avec lui je fais tomber des feuilles pour mes moutons » (20:18). Allah dit : « Jette-le », et il devint un serpent qui rampait vite ; puis Il lui dit de le prendre sans peur, et il redevint comme avant (20:19-21). Le musulman apprend qu'Allah peut faire du bâton d'un berger un signe pour un prophète.",

"prophets_258": "La sourate Yûsuf s'ouvre sur le garçon qui dit à son père : « Ô mon père, j'ai vu onze étoiles, le soleil et la lune ; je les ai vus se prosterner devant moi » (12:4). Son père Ya'qûb lui dit de ne pas le raconter à ses frères, de peur qu'ils ne complotent contre lui, car Satan est pour l'homme un ennemi déclaré (12:5). Bien plus tard, quand ses parents et ses frères se prosternèrent devant lui en Égypte, Yûsuf dit : « Voilà l'explication de mon rêve d'autrefois ; mon Seigneur l'a rendu vrai » (12:100). Le musulman apprend que ce qu'Allah montre peut demander de longues années et de dures épreuves avant de se réaliser.",

"prophets_259": "Sulaymân avait passé les oiseaux en revue et demandé pourquoi la huppe manquait, en menaçant de la punir si elle n'apportait pas une excuse claire (27:20-21). Elle revint avec une nouvelle : « J'ai appris une chose que tu ne sais pas, et je t'apporte de Saba' une nouvelle sûre » (27:22). Elle y avait trouvé une femme qui régnait avec un grand trône, et son peuple qui se prosternait devant le soleil au lieu d'Allah (27:23-24). Sulaymân dit qu'il vérifierait si elle avait dit la vérité, et il la renvoya avec une lettre (27:27-28). Le musulman apprend qu'une nouvelle se vérifie avant qu'on agisse.",

"prophets_260": "Le verset dit : « Et rappelle-toi Notre serviteur Ayyûb, quand il appela son Seigneur : Satan m'a touché par la peine et la souffrance » (38:41). Allah lui répondit aussitôt : « Frappe le sol de ton pied ; voici une source fraîche pour te laver et pour boire » (38:42), et Il lui rendit sa famille, et autant encore avec eux (38:43). Puis le Coran donne son jugement : « Vraiment, Nous l'avons trouvé patient. Quel excellent serviteur ; il revenait sans cesse vers Allah » (38:44). Le musulman apprend que la patience ne veut pas dire se taire devant Allah : Ayyûb a enduré, et il a aussi demandé.",

"prophets_261": "Le verset compare deux prophètes : « Vraiment, 'Îsâ est, devant Allah, comme Âdam. Il le créa de poussière, puis Il lui dit : Sois, et il fut » (3:59). Il termine le récit de la naissance de 'Îsâ dans la sourate Âl 'Imrân, et le verset suivant ajoute : « La vérité vient de ton Seigneur, ne sois donc pas parmi ceux qui doutent » (3:60). Ailleurs, le Coran dit de tous les hommes : « Il vous a créés de poussière, et voilà que vous êtes des êtres humains qui se répandent » (30:20). Le musulman apprend que la poussière a pris vie par un seul mot d'Allah, et que personne n'a donc de raison d'être fier.",

"prophets_262": "Le verset se trouve dans une liste de messagers : « Il y a des messagers dont Nous t'avons déjà parlé, et des messagers dont Nous ne t'avons pas parlé. Et Allah a parlé à Mûsâ de vive voix » (4:164). La sourate Tâ-Hâ rapporte cette parole dans la vallée sacrée : « Vraiment, Je suis ton Seigneur, enlève donc tes sandales ; tu es dans la vallée sacrée de Tuwâ ; et Je t'ai choisi, écoute donc ce qui est révélé » (20:12-13). Plus tard, Allah lui dit qu'Il l'avait choisi parmi les hommes par Ses messages et Sa parole (7:144). Le musulman apprend que Mûsâ a reçu un honneur particulier parmi les messagers.",

"prophets_263": "Le Coran énonce cet article de foi en un seul verset : « Muhammad n'est le père d'aucun de vos hommes, mais il est le Messager d'Allah et le sceau des prophètes » (33:40). Un sceau est ce qui ferme une lettre ; rien ne s'ajoute après lui. Il a aussi été envoyé non pas à une seule ville, mais à tout le monde : « Dis : Ô hommes, je suis le Messager d'Allah vers vous tous » (7:158). Toute biographie classique et toute profession de foi musulmane enseignent cette clôture de la prophétie. Le musulman apprend que la guidée dont il a besoin a été complétée avec ce dernier prophète, et que nul ne viendra après lui.",

"prophets_264": "Le verset qui donne ce titre est dans la sourate An-Nisâ' : « Qui est meilleur en religion que celui qui soumet son visage à Allah, fait le bien, et suit la voie d'Ibrâhîm, tourné vers la vérité ? Et Allah a pris Ibrâhîm pour ami intime » (4:125). La sourate Al-Baqara montre ensuite ce que les musulmans disent de lui : « Nous croyons en Allah et en ce qui nous a été révélé, et en ce qui a été révélé à Ibrâhîm, Ismâ'îl, Ishâq, Ya'qûb et aux Tribus » (2:136). Ibrâhîm est en tête de cette lignée de prophètes. Le musulman apprend que la proximité d'Allah vient de la soumission à Lui et du bien que l'on fait, comme l'a fait Ibrâhîm.",

"prophets_265": "Le verset fait partie d'un discours qu'Allah tiendra au Jour du Jugement, en énumérant Ses bienfaits : « Ô 'Îsâ, fils de Maryam, rappelle-toi Mon bienfait sur toi et sur ta mère, quand Je t'ai soutenu par l'Esprit pur, et que tu parlais aux gens au berceau et à l'âge mûr » (5:110). Il continue : il façonna un oiseau avec de l'argile et cela devint un oiseau par la permission d'Allah, il guérit l'aveugle-né et le lépreux par Sa permission, et il fit sortir les morts par Sa permission (5:110). Le musulman apprend que les miracles de 'Îsâ étaient vrais et qu'ils étaient ceux d'Allah, accomplis par Son serviteur.",

"prophets_266": "Le verset dit : « Nous avons donné à Dâwûd une faveur de Notre part : Ô montagnes, redites les louanges avec lui, et vous aussi, les oiseaux. Et Nous avons rendu le fer mou pour lui » (34:10). Le verset suivant lui dit quoi faire de ce fer : fabriquer de larges cottes de mailles, bien mesurer les mailles, et faire le bien, car Allah voit ce qu'il fait (34:11). La sourate Sâd ajoute que les montagnes glorifiaient avec lui le soir et après le lever du soleil, et que les oiseaux se rassemblaient autour de lui (38:18-19). Le musulman apprend que louer Allah unit une personne à toute la création, qui Le loue aussi.",

"prophets_267": "Le roi d'Égypte avait vu sept vaches grasses mangées par sept vaches maigres, et sept épis verts avec d'autres secs, et sa cour appela cela un fouillis de rêves (12:43-44). L'homme sorti de prison se souvint de Yûsuf et alla le voir : « Yûsuf, ô homme de vérité, explique-nous » (12:46). Yûsuf répondit : sept années à semer sans relâche, en laissant le grain dans ses épis ; puis sept années dures qui mangeraient ce qui avait été mis de côté ; puis une année de pluie et d'abondance (12:47-49). Le musulman apprend que le savoir venu d'Allah sert à aider les gens, même ceux qui l'ont oublié en prison.",

"prophets_268": "Les paroles des frères ouvrent l'épreuve : « Yûsuf et son frère sont plus chers à notre père que nous, alors que nous sommes un groupe. Vraiment, notre père est dans une erreur évidente » (12:8). La sourate Yûsuf nomme ce père un peu avant, quand il promet au garçon qu'Allah achèvera Son bienfait « sur toi et sur la famille de Ya'qûb, comme Il l'a achevé auparavant sur tes deux ancêtres, Ibrâhîm et Ishâq » (12:6). Quand ses fils lui apportèrent la tunique de Yûsuf avec du faux sang, il répondit : « Belle patience » (12:18). Le musulman apprend de ce père que c'est la patience, et non la colère, qui répond à une grande perte.",

"prophets_269": "Le verset est l'un des bienfaits qu'Allah rappelle aux Enfants d'Israël : « Et quand Nous avons fendu la mer pour vous, Nous vous avons sauvés et Nous avons noyé les gens de Pharaon sous vos yeux » (2:50). La sourate Ash-Shu'arâ' raconte le moment lui-même : avec l'armée de Pharaon derrière eux, les compagnons de Mûsâ crièrent qu'ils étaient pris, et il répondit : « Non ! Mon Seigneur est avec moi ; Il va me guider » (26:61-62). Alors Allah ordonna : « Frappe la mer de ton bâton », et elle se fendit, chaque côté comme une grande montagne (26:63). Le musulman apprend que, quand tout chemin semble fermé, Allah peut en ouvrir un.",

"prophets_270": "Cette pratique vient d'un verset de la sourate Al-Ahzâb : « Vraiment, Allah et Ses anges prient sur le Prophète. Ô vous qui croyez, priez sur lui et saluez-le par la paix » (33:56). Ainsi, quand un musulman dit sallâ-Llâhu 'alayhi wa sallam, il fait exactement ce que ce verset demande : il se joint à Allah et à Ses anges pour honorer le Prophète ﷺ. Les musulmans prient aussi sur lui dans la position assise, à la fin de chaque prière. Le musulman apprend à répondre au nom du Prophète ﷺ par une prière pour lui, en remerciement pour la guidée qu'il a apportée.",

"prophets_271": "La sourate qui porte son nom commence ainsi : « Nous avons envoyé Nûh vers son peuple : avertis ton peuple avant qu'un châtiment douloureux ne l'atteigne » (71:1). Il leur dit clairement : adorez Allah, craignez-Le, et obéissez-moi (71:3). Puis il se plaignit à son Seigneur : « Mon Seigneur, j'ai appelé mon peuple nuit et jour, mais mon appel n'a fait que les éloigner davantage » (71:5-6) ; ils mettaient leurs doigts dans leurs oreilles et s'enveloppaient dans leurs vêtements (71:7). La sourate Al-'Ankabût donne la durée : mille ans moins cinquante (29:14). Le musulman apprend que celui qui appelle vers Allah continue, et laisse le résultat à Allah.",

"prophets_272": "La sourate Sâd nomme le père et le fils en une seule ligne : « Et à Dâwûd Nous avons donné Sulaymân. Quel excellent serviteur ; vraiment, il revenait sans cesse vers Allah » (38:30). Remarquons ce qui est loué : non pas le trône qu'il allait avoir, mais son caractère de serviteur qui revenait toujours vers son Seigneur. La sourate An-Naml dit qu'il hérita de Dâwûd et qu'il dit aux gens : « On nous a appris le langage des oiseaux, et on nous a donné de toute chose » (27:16). Le musulman apprend que la plus belle louange d'un roi est d'avoir été un bon serviteur d'Allah.",

"prophets_273": "Le verset termine l'histoire de l'armée de Tâlût : « Ils les vainquirent donc par la permission d'Allah, et Dâwûd tua Jâlût, et Allah lui donna la royauté et la sagesse et lui apprit ce qu'Il voulut » (2:251). Juste avant, les quelques hommes restés fermes avaient dit : « Combien de fois une petite troupe a vaincu une grande troupe par la permission d'Allah ; et Allah est avec les patients » (2:249), et ils avaient demandé la patience, des pas fermes et la victoire (2:250). Dâwûd, l'un de cette petite troupe, devint roi et prophète. Le musulman apprend que la victoire vient d'Allah aux patients, et non du nombre.",

"prophets_274": "Le Coran met cette croyance dans la bouche de chaque croyant : « Le Messager a cru en ce qui lui a été descendu de son Seigneur, et les croyants aussi. Tous ont cru en Allah, en Ses anges, en Ses livres et en Ses messagers : Nous ne faisons aucune différence entre Ses messagers » (2:285). Il dit aussi que tous ne sont pas nommés : « des messagers dont Nous t'avons parlé, et des messagers dont Nous ne t'avons pas parlé » (40:78). Le musulman apprend à honorer les prophètes qu'il connaît par leur nom et ceux qu'il ne connaît pas, comme une seule famille envoyée par un seul Seigneur.",

"prophets_275": "Le verset dit : « Vraiment, Allah a élu Âdam, Nûh, la famille d'Ibrâhîm et la famille de 'Imrân au-dessus des mondes, descendants les uns des autres » (3:33-34). Le verset suivant montre pourquoi la famille de 'Imrân est nommée : la femme de 'Imrân pria : « Mon Seigneur, je T'ai consacré ce qui est dans mon ventre » (3:35), et l'enfant fut Maryam, la mère de 'Îsâ (3:36). Ainsi le verset nomme le premier homme, le prophète du déluge, le père de nombreux prophètes et la famille du Messie. Le musulman apprend que les prophètes viennent d'une seule lignée choisie.",

"prophets_276": "Le nom du pays est prononcé par Yûsuf lui-même quand sa famille arrive : « Entrez en Égypte, si Allah le veut, en toute sécurité » (12:99). Il avait demandé au roi : « Confie-moi les réserves du pays ; je suis un gardien qui sait » (12:55), et le Coran dit : « Ainsi Nous avons établi Yûsuf dans le pays » (12:56). Aux retrouvailles, il fit monter ses parents sur le trône et dit qu'Allah avait été bon envers lui quand Il l'avait fait sortir de prison (12:100). Le musulman apprend que le garçon jeté dans un puits a été élevé par Allah jusqu'aux honneurs, dans un pays étranger.",

"prophets_277": "La sourate Al-Isrâ' s'ouvre sur ce voyage : « Gloire à Celui qui fit voyager de nuit Son serviteur, de la Mosquée sacrée à la Mosquée la plus lointaine, dont Nous avons béni les alentours, pour lui montrer certains de Nos signes » (17:1). La Mosquée sacrée est à La Mecque, où vivait le Prophète ﷺ, et la Mosquée la plus lointaine est al-Aqsâ. Au moment de son plus grand honneur, le Coran l'appelle simplement « Son serviteur ». Le verset suivant passe à Mûsâ et au Livre qui lui fut donné (17:2). Le musulman apprend qu'al-Aqsâ est un lieu béni lié à son Prophète ﷺ, et que le plus haut titre est celui de serviteur d'Allah.",

"prophets_278": "Le verset dit : « Et Nous avons donné à Mûsâ le Livre, et Nous avons envoyé après lui des messagers, les uns à la suite des autres » (2:87), et il continue en nommant 'Îsâ, fils de Maryam, qui reçut des preuves claires et fut soutenu par l'Esprit pur. Le Livre donné à Mûsâ est nommé ailleurs : « Vraiment, Nous avons fait descendre la Torah, où il y a guidée et lumière » (5:44), et la sourate Âl 'Imrân dit qu'Allah « a fait descendre auparavant la Torah et l'Évangile, comme guidée pour les gens » (3:3-4). Le musulman apprend que la Torah était une vraie révélation faite à Mûsâ, et que croire aux livres d'avant fait partie de sa foi.",

"prophets_279": "Le verset dit : « Et Nous avons envoyé, sur leurs traces, 'Îsâ fils de Maryam, pour confirmer la Torah venue avant lui ; et Nous lui avons donné l'Évangile, où il y a guidée et lumière » (5:46). Deux versets plus tôt, la Torah est décrite avec les mêmes mots, guidée et lumière (5:44), et deux versets plus loin Allah dit au Prophète ﷺ que le Coran a été envoyé « pour confirmer le Livre venu avant lui » (5:48). Torah, Évangile et Coran forment ainsi une seule chaîne venue d'un seul Envoyeur. Le musulman apprend que 'Îsâ est venu avec un vrai livre, et il y croit tel qu'Allah l'a révélé.",

"prophets_280": "Le verset est une longue liste de ceux à qui Allah a envoyé la révélation : « Nous t'avons révélé comme Nous avons révélé à Nûh et aux prophètes après lui ; et Nous avons révélé à Ibrâhîm, Ismâ'îl, Ishâq, Ya'qûb et aux Tribus, à 'Îsâ, Ayyûb, Yûnus, Hârûn et Sulaymân ; et à Dâwûd Nous avons donné le Zabûr » (4:163). La sourate Al-Isrâ' répète ce don avec les mêmes mots (17:55), et la sourate Al-Anbiyâ' en cite une ligne : « la terre sera héritée par Mes serviteurs vertueux » (21:105). Le musulman apprend que Dâwûd était à la fois un roi et un prophète, avec un livre nommé dans le Coran.",

"prophets_281": "Ibrâhîm avait prié pour avoir un enfant vertueux, et on lui annonça un garçon plein de douceur (37:100-101). Puis : « Quand le garçon fut en âge de travailler avec lui, il dit : Ô mon fils, j'ai vu en rêve que je te sacrifie, vois donc ce que tu en penses. Il dit : Ô mon père, fais ce qui t'est ordonné ; tu me trouveras, si Allah le veut, parmi les patients » (37:102). Quand tous deux se furent soumis, Allah appela : « Ô Ibrâhîm, tu as réalisé la vision » (37:104-105), et Il racheta le garçon par un grand sacrifice (37:107). Le musulman apprend du fils à dire « si Allah le veut », et que l'obéissance est accueillie par la miséricorde.",

"prophets_282": "Le verset dit : « Et Nous avons inspiré à la mère de Mûsâ : allaite-le, et quand tu auras peur pour lui, jette-le dans le fleuve, et n'aie pas peur et ne t'attriste pas. Vraiment, Nous te le rendrons et Nous ferons de lui un des messagers » (28:7). Pharaon tuait les fils de son peuple (28:4). La propre famille de Pharaon recueillit le bébé, et il refusa toutes les nourrices jusqu'à ce que sa sœur les conduise à sa mère, « ainsi Nous l'avons rendu à sa mère, pour que son œil soit consolé » (28:8-13). Le musulman apprend qu'Allah tient Sa promesse, même en passant par la maison d'un ennemi.",

"prophets_283": "Le Coran cite l'appel lui-même : « Et il appela dans les ténèbres : Il n'est de dieu que Toi ; gloire à Toi ; vraiment, j'ai été parmi les injustes » (21:87). Le verset dit qu'il était parti en colère, pensant qu'Allah ne lui imposerait pas d'épreuve. La réponse suit : « Nous lui avons donc répondu et Nous l'avons sauvé de l'angoisse ; et c'est ainsi que Nous sauvons les croyants » (21:88). La sourate As-Sâffât raconte que le poisson avala Yûnus, et que s'il n'avait pas glorifié Allah, il serait resté dans son ventre (37:142-144). Le musulman apprend que cette même prière est une porte de secours pour tout croyant en détresse.",

"prophets_284": "Son nom complet est Muhammad ibn 'Abdullâh ibn 'Abd al-Muttalib ibn Hâshim, de la tribu de Quraysh, à La Mecque ; toute biographie classique s'ouvre sur cette ligne. Toutes s'accordent à dire que 'Abdullâh mourut avant la naissance de son fils, si bien que le Prophète ﷺ n'a jamais connu son père. Le Coran lui parle de cette enfance : « Ne t'a-t-Il pas trouvé orphelin, et Il t'a donné un abri ? » (93:6). Son grand-père 'Abd al-Muttalib prit soin de lui, puis son oncle Abû Tâlib. Le musulman apprend que le dernier messager d'Allah a commencé sa vie orphelin, avec Allah Lui-même pour protecteur.",

"prophets_285": "Âmina bint Wahb était de Quraysh, la tribu de La Mecque, et toute biographie classique la présente comme la mère du Prophète ﷺ. Toutes s'accordent à dire qu'elle mourut alors qu'il était encore un petit garçon, après que son père fut mort avant sa naissance, si bien qu'il grandit sous la garde de son grand-père 'Abd al-Muttalib, puis de son oncle Abû Tâlib. Le Coran le lui rappelle : « Ne t'a-t-Il pas trouvé orphelin, et Il t'a donné un abri ? Et Il t'a trouvé égaré, et Il t'a guidé » (93:6-7). Le musulman apprend qu'Allah a veillé sur Son Prophète ﷺ dès le berceau, et il honore la mère qui l'a porté.",

"prophets_286": "Maryam apporta son bébé à son peuple, qui l'accusa ; elle montra seulement l'enfant du doigt, et ils demandèrent comment ils pourraient parler à un bébé au berceau (19:27-29). Alors il parla : « Vraiment, je suis le serviteur d'Allah. Il m'a donné le Livre et Il a fait de moi un prophète, Il m'a rendu béni où que je sois, et Il m'a prescrit la prière et la zakât tant que je vivrai, et d'être bon envers ma mère » (19:30-32). Le Coran dit ensuite : « Tel est 'Îsâ, fils de Maryam, la parole de vérité » (19:34). Le musulman apprend que les premiers mots de 'Îsâ l'ont appelé serviteur d'Allah, et il tient cela pour la vérité à son sujet.",

"prophets_287": "Le verset dit : « Et aux 'Âd, Nous avons envoyé leur frère Hûd. Il dit : Ô mon peuple, adorez Allah ; vous n'avez pas d'autre dieu que Lui. Ne Le craindrez-vous donc pas ? » (7:65). Les chefs de son peuple le traitèrent de sot et de menteur, et il répondit qu'il était un messager du Seigneur des mondes, qui leur donnait un conseil sincère (7:66-68). Il leur rappela qu'Allah avait fait d'eux les successeurs du peuple de Nûh (7:69) ; ils refusèrent, alors Allah sauva Hûd et ceux qui étaient avec lui, et Il fit périr ceux qui niaient (7:72). Le musulman apprend que Hûd a apporté le même appel que chaque prophète.",

"prophets_288": "Le verset dit : « Et aux Thamûd, Nous avons envoyé leur frère Sâlih. Il dit : Ô mon peuple, adorez Allah ; vous n'avez pas d'autre dieu que Lui. Une preuve claire vous est venue de votre Seigneur : voici la chamelle d'Allah, un signe pour vous. Laissez-la donc manger sur la terre d'Allah et ne lui faites aucun mal, sinon un châtiment douloureux vous saisira » (7:73). Les Thamûd taillaient leurs maisons dans les montagnes (7:74), pourtant ils coupèrent les jarrets de la chamelle et défièrent l'ordre de leur Seigneur, et un tremblement de terre les emporta (7:77-78). Le musulman apprend que faire du mal à ce qu'Allah protège mène à la ruine.",

"prophets_289": "Mûsâ venait d'être envoyé à Pharaon, et il pria : « Mon Seigneur, ouvre-moi ma poitrine, rends ma tâche facile, et dénoue le nœud de ma langue, pour qu'ils comprennent mes paroles » (20:25-28). Puis il demanda un aide : « Et donne-moi un assistant de ma famille, Hârûn, mon frère ; fortifie-moi par lui et fais-le participer à ma tâche » (20:29-32). Allah répondit : « Ta demande t'est accordée, ô Mûsâ » (20:36), et plus tard Il leur dit : « Allez, tous les deux, vers Pharaon » (20:43). Le musulman apprend que demander l'aide d'Allah, et un bon compagnon pour une tâche difficile, fait partie de la voie d'un prophète.",

"prophets_290": "Le verset dit : « Muhammad n'est le père d'aucun de vos hommes, mais il est le Messager d'Allah et le sceau des prophètes ; et Allah sait toute chose » (33:40). Il vient après le récit de Zayd (33:37), dans une sourate qui avait déjà dit que les fils adoptifs doivent être appelés du nom de leurs vrais pères (33:5). Un sceau ferme une lettre pour que rien ne s'y ajoute. Quelques versets plus loin, Allah l'appelle « une lampe qui éclaire » (33:46). Le musulman apprend que la prophétie a été complétée et fermée avec Muhammad ﷺ, et que son message est le dernier.",

"prophets_291": "Les paroles des anges sont : « Ô Maryam, vraiment Allah t'a élue et purifiée, et Il t'a élue au-dessus des femmes des mondes. Ô Maryam, sois dévouée à ton Seigneur, prosterne-toi, et incline-toi avec ceux qui s'inclinent » (3:42-43). Plus tôt, la sourate montre pourquoi : chaque fois que Zakariyyâ entrait dans son lieu de prière, il trouvait auprès d'elle de la nourriture et lui demandait d'où elle venait, et elle répondait : « Elle vient d'Allah » (3:37). Peu après, les anges lui annoncent un fils, le Messie, 'Îsâ (3:45). Le musulman apprend que Maryam a été élue pour sa dévotion, et qu'être élue l'a appelée à plus d'adoration encore.",

"prophets_292": "Le verset donne toute la prière : « Et Ayyûb, quand il appela son Seigneur : Vraiment, le mal m'a touché, et Tu es le plus miséricordieux des miséricordieux » (21:83). Il ne fit pas une liste de demandes ; il nomma sa peine et il nomma la miséricorde d'Allah. La réponse vint aussitôt : « Nous lui avons donc répondu et Nous avons enlevé le mal qui le touchait, et Nous lui avons donné sa famille et autant encore avec eux, par une miséricorde de Notre part » (21:84). Le verset suivant compte avec lui Ismâ'îl, Idrîs et Dhul-Kifl parmi les patients (21:85). Le musulman apprend à porter sa douleur à Allah en quelques mots humbles.",

"prophets_293": "Le verset dit : « Et Il apprit à Âdam les noms, tous les noms ; puis Il les présenta aux anges et dit : Dites-Moi les noms de ceux-ci, si vous êtes véridiques » (2:31). Les anges répondirent : « Gloire à Toi ! Nous n'avons de savoir que ce que Tu nous as appris » (2:32). Puis Allah dit : « Ô Âdam, dis-leur leurs noms », et quand il le fit, Il rappela aux anges qu'Il connaît ce qui est caché dans les cieux et sur la terre (2:33), et Il leur ordonna de se prosterner devant Âdam (2:34). Le musulman apprend que le savoir est un don d'Allah, et qu'il a élevé le premier homme en honneur.",

"prophets_294": "La prière dit : « Mon Seigneur, pardonne-moi, et donne-moi un royaume tel que nul après moi n'en aura de semblable. Vraiment, Tu es le Grand Donateur » (38:35). Remarquons qu'il demande d'abord le pardon. Allah répondit : « Nous lui avons donc soumis le vent, qui soufflait doucement sur son ordre là où il voulait » (38:36), ainsi que les démons, tout bâtisseur et tout plongeur (38:37). Puis Il dit : « Voilà Notre don, donne ou retiens, sans avoir de compte à rendre » (38:39), et Il lui promit la proximité et un beau retour (38:40). Le musulman apprend que le pouvoir sans égal de Sulaymân est venu comme un don après une prière de pardon, joint à une promesse pour l'au-delà.",

"prophets_295": "Les anges venus chez Lût dirent : « Ô Lût, nous sommes les messagers de ton Seigneur ; ils ne t'atteindront jamais. Pars donc avec ta famille pendant une partie de la nuit, et qu'aucun de vous ne se retourne, sauf ta femme ; ce qui les frappera la frappera aussi. Leur rendez-vous est le matin » (11:81). À l'aube, Allah renversa la ville sens dessus dessous et fit pleuvoir sur elle des pierres d'argile dure (11:82). La sourate At-Tahrîm explique le sort de cette femme : les femmes de Nûh et de Lût vivaient auprès de deux serviteurs vertueux, mais elles les trahirent, et cela ne leur servit à rien devant Allah (66:10). Le musulman apprend que chacun répond de sa propre foi.",

"prophets_296": "Le verset dit : « Et quand Ibrâhîm dit à son père : Prends-tu des idoles pour dieux ? Vraiment, je vous vois, toi et ton peuple, dans une erreur évidente » (6:74). Les versets suivants racontent comment Allah lui montra le royaume des cieux et de la terre (6:75) : il vit une étoile, puis la lune, puis le soleil, et chaque fois qu'ils se couchaient, il disait : « Je n'aime pas ce qui disparaît » (6:76-78). Puis il déclara : « J'ai tourné mon visage vers Celui qui a créé les cieux et la terre, tourné vers la vérité » (6:79). Le musulman apprend que l'avertissement d'Ibrâhîm a commencé à la maison, et que seul le Créateur, qui ne se couche jamais, mérite d'être adoré.",

"prophets_297": "Le mot rasûl traverse tout le Coran. C'est le titre du témoignage de foi : « Muhammad est le Messager d'Allah » (48:29). Le Coran dit qu'aucun peuple n'a été laissé sans messager : « À chaque communauté un messager » (10:47), et « il n'est pas de communauté où un avertisseur ne soit passé » (35:24). Il dit aussi quelle est la tâche d'un messager : « Le Messager n'est chargé que de transmettre clairement » (24:54) ; il n'invente pas le message, il le porte fidèlement de la part d'Allah. Le musulman apprend à voir chaque messager, de Nûh à Muhammad ﷺ, comme le porteur fidèle d'un seul message : adorez Allah seul.",

"prophets_298": "Les deux versets disent : « Ô Prophète, Nous t'avons envoyé témoin, annonciateur de bonne nouvelle et avertisseur, et comme celui qui appelle vers Allah par Sa permission, et comme une lampe qui éclaire » (33:45-46). Le verset suivant dit quelle est cette bonne nouvelle : « Annonce aux croyants la bonne nouvelle qu'ils auront d'Allah une grande faveur » (33:47). La sourate Al-Baqara explique le témoin : la communauté musulmane a été faite communauté du juste milieu « pour que le Messager soit témoin sur vous » (2:143). Le musulman apprend que son Prophète ﷺ veille sur sa communauté, lui apporte l'espoir, l'avertit du danger et éclaire son chemin.",

"prophets_299": "Le verset vient vers la fin de la sourate Al-Anbiyâ', après une longue suite de prophètes : « Et Nous ne t'avons envoyé qu'en miséricorde pour les mondes » (21:107). Le verset suivant donne le cœur de cette miséricorde : « Dis : il m'est seulement révélé que votre Dieu est un Dieu unique ; allez-vous donc vous soumettre ? » (21:108). La sourate At-Tawba montre la miséricorde dans sa personne : « Il vous est venu un Messager pris parmi vous ; ce que vous souffrez lui pèse ; envers les croyants, il est bon et miséricordieux » (9:128). Le musulman apprend que le Prophète ﷺ a été envoyé pour tous les mondes, et il essaie de porter cette même miséricorde aux autres.",

"prophets_300": "Le verset dit : « Ô descendants de ceux que Nous avons portés avec Nûh ; vraiment, il était un serviteur très reconnaissant » (17:3). Il s'adresse aux Enfants d'Israël, juste après le Livre donné à Mûsâ (17:2), et il leur rappelle que leurs ancêtres ont été sauvés sur l'Arche. La reconnaissance de Nûh se voit dans la sourate Al-Mu'minûn, où Allah lui dit quoi dire une fois à bord : « Louange à Allah, qui nous a sauvés du peuple injuste » (23:28). Après toute une vie à appeler son peuple (29:14) et un déluge qui noya ceux qui niaient, il répondit par la louange. Le musulman apprend de Nûh que remercier Allah est la bonne réponse au secours reçu.",
}
