"""Français — détails, beginner_3 (50 questions)."""

D = {
"sira_291": "Tous les récits classiques de l'histoire du Coran, et les paroles de Zayd ibn Thâbit rapportées dans Sahîh al-Bukhârî, racontent qu'après la mort de nombreux récitateurs à Yamâma, 'Umar pressa Abû Bakr de rassembler le Coran, et Abû Bakr confia la tâche à Zayd, qui le recueillit à partir de ce qui était écrit et de la mémoire des récitateurs. Les feuillets furent gardés chez Abû Bakr, puis chez 'Umar. Allah avait promis : « Vraiment, c'est Nous qui avons fait descendre le Rappel, et c'est Nous qui en sommes le gardien » (15:9). Le musulman voit dans ce soin une des façons dont cette promesse a été tenue.",

"sira_292": "Toute biographie classique rapporte que le père du Prophète ﷺ, 'Abdullâh, mourut avant sa naissance, et sa mère Âmina alors qu'il était encore un petit garçon ; alors son grand-père 'Abd al-Muttalib, un ancien respecté de Quraysh, le prit sous sa garde et le garda près de lui. Quand le grand-père mourut, le garçon passa à son oncle Abû Tâlib, qui le protégea toute sa vie. Le Coran rappelle ces années : « Ne t'a-t-Il pas trouvé orphelin, et Il t'a donné un abri ? » (93:6). Le musulman apprend qu'Allah a pris soin de Son Prophète ﷺ à travers sa propre famille.",

"sira_293": "Le verset se trouve dans la sourate Ad-Duhâ, où Allah jure par la clarté du matin et par la nuit calme, et dit à Son Prophète ﷺ : « Ton Seigneur ne t'a pas abandonné, et Il ne te déteste pas » (93:3). Puis Il compte trois bienfaits : « Ne t'a-t-Il pas trouvé orphelin, et Il t'a donné un abri ? Et Il t'a trouvé égaré, et Il t'a guidé ? Et Il t'a trouvé pauvre, et Il t'a enrichi ? » (93:6-8). La sourate se termine en lui demandant de transmettre cette bonté : n'opprime pas l'orphelin, ne repousse pas celui qui demande (93:9-10). Le musulman apprend que se souvenir de l'aide d'Allah nous rend doux avec les autres.",

"sira_294": "Le Coran parle d'Uhud dans la sourate Âl 'Imrân, juste après avoir nommé Badr : « Allah vous a déjà donné la victoire à Badr, alors que vous étiez peu nombreux » (3:123). Il se tourne ensuite vers le matin où le Prophète ﷺ sortit pour placer les croyants à leurs postes de combat (3:121), près de la montagne d'Uhud, à l'extérieur de Médine. Toute biographie classique raconte que les archers quittèrent la colline qu'ils devaient tenir, que le Prophète ﷺ fut blessé et que son oncle Hamza fut tué ; le Coran ajoute qu'Allah leur pardonna (3:152). Le musulman apprend que la difficulté après la victoire est aussi une épreuve.",

"sira_295": "La sourate Al-Ahzâb, les Coalisés, garde le souvenir de cette bataille : « Rappelez-vous le bienfait d'Allah sur vous, quand des armées sont venues à vous et que Nous avons envoyé contre elles un vent et des armées que vous ne voyiez pas » (33:9). Les tribus ennemies s'étaient unies contre Médine, et toute biographie classique rapporte que les musulmans, avec le Prophète ﷺ qui portait la terre à leurs côtés, creusèrent un large fossé sur le côté ouvert de la ville, pour que les cavaliers ne puissent pas passer. Le Coran rappelle la peur de ces jours, quand « les cœurs montèrent jusqu'aux gorges » (33:10). Le musulman apprend que le travail dur va avec la confiance en l'aide d'Allah.",

"sira_296": "'Â'isha était la fille d'Abû Bakr as-Siddîq, l'ami le plus proche du Prophète ﷺ et le premier calife après lui. Le Coran parle de son père comme du compagnon de la grotte pendant l'émigration : « le second des deux, quand ils étaient dans la grotte, quand il dit à son compagnon : ne t'attriste pas, vraiment Allah est avec nous » (9:40). Toute biographie classique rapporte que le Prophète ﷺ mourut dans la chambre de 'Â'isha et y fut enterré, et qu'elle enseigna aux compagnons et transmit un grand nombre de ses paroles. Le musulman apprend son nom comme celui d'une mère des croyants et d'une enseignante.",

"sira_297": "Le verset complet dit : « Le Prophète est plus proche des croyants qu'eux-mêmes, et ses épouses sont leurs mères » (33:6). Il se trouve près du début de la sourate Al-Ahzâb, après qu'Allah a dit qu'appeler un garçon adopté le fils de quelqu'un n'en fait pas un vrai fils (33:4-5) ; ici, au contraire, Allah Lui-même donne aux épouses du Prophète ﷺ le titre de mères. Plus loin dans la sourate, Il dit que personne ne peut les épouser après lui (33:53). Le musulman honore Khadîja, 'Â'isha et les autres épouses du Prophète ﷺ avec le respect dû à une mère.",

"sira_298": "Toute biographie classique rapporte que 'Alî était le fils d'Abû Tâlib, l'oncle qui éleva le Prophète ﷺ, qu'il grandit dans la maison même du Prophète ﷺ, et qu'il accepta l'islam enfant, parmi les tout premiers. La nuit de l'émigration, il dormit dans le lit du Prophète ﷺ pour que les guetteurs dehors pensent qu'il était encore là. À Médine, il épousa Fâtima, la fille du Prophète ﷺ ; leurs fils furent al-Hasan et al-Husayn, et des années plus tard 'Alî devint le quatrième calife. Le musulman se souvient de lui comme lié au Prophète ﷺ par le sang, par le mariage et par la foi.",

"sira_299": "Toute biographie classique rapporte que, quand le Prophète ﷺ arriva à Médine après l'émigration, l'une des premières choses qu'il fit fut de bâtir une mosquée, en travaillant à côté de ses compagnons. De là, il dirigea les cinq prières, enseigna le Coran et reçut les délégations, et quand il mourut, il fut enterré dans la chambre de 'Â'isha, qui donnait sur elle. Sahîh al-Bukhârî et Sahîh Muslim rapportent ses paroles : une prière dans sa mosquée vaut mieux que mille prières partout ailleurs, sauf à al-Masjid al-Harâm. Le musulman qui visite Médine y prie et adresse au Prophète ﷺ son salut de paix.",

"sira_300": "Le Coran raconte le voyage : « Gloire à Celui qui fit voyager de nuit Son serviteur, d'al-Masjid al-Harâm à al-Masjid al-Aqsâ, dont Nous avons béni les alentours » (17:1). Le récit du voyage nocturne dans Sahîh Muslim, avec les mots d'Anas ibn Mâlik, donne son nom à la monture : le Prophète ﷺ dit qu'on lui amena al-Burâq, un animal blanc plus grand qu'un âne et plus petit qu'un mulet, qui posait son sabot aussi loin que portait son regard. Le nom vient du mot arabe qui veut dire l'éclair. Le musulman apprend que le voyage nocturne fut un vrai voyage, avec une vraie monture, accordé par Allah.",

"faith_151": "Ibn 'Umar rapporte dans Sahîh al-Bukhârî 8 que le Prophète ﷺ nomma les cinq : le témoignage qu'il n'est de dieu qu'Allah et que Muhammad est le Messager d'Allah, accomplir la prière, donner la zakât, le pèlerinage, et jeûner le Ramadan. Le Coran parle de chacun : « accomplissez la prière et donnez la zakât » (2:43), « le jeûne vous est prescrit » (2:183), et le pèlerinage dû à Allah par quiconque peut faire le voyage (3:97). Le mot pilier est employé parce qu'une maison ne peut pas tenir s'il manque un support. Le musulman apprend les cinq comme un seul tout, et non comme une liste où l'on choisit.",

"faith_152": "La shahâda se dit en arabe : lâ ilâha illa Allah, Muhammadun rasûl Allah. Ses deux moitiés sont toutes deux dans le Coran : « Sache donc qu'il n'est de dieu qu'Allah » (47:19) et « Muhammad est le Messager d'Allah » (48:29). Dans Sahîh al-Bukhârî 8, le Prophète ﷺ la nomme en premier parmi les cinq piliers, et chaque musulman la répète dans la position assise de chaque prière, dans l'appel à la prière, et comme les mots que dit une personne pour entrer en islam. Le musulman apprend que toute la religion commence par ces deux phrases : un seul Seigneur à adorer, un seul messager à suivre.",

"faith_153": "Chaque musulman accomplit les mêmes cinq : Fajr avant le lever du soleil, Dhuhr après midi, 'Asr l'après-midi, Maghrib juste après le coucher du soleil et 'Ishâ' la nuit. Le Coran dit : « Vraiment, la prière a été prescrite aux croyants à des heures fixées » (4:103), et : « Accomplis la prière du déclin du soleil jusqu'à l'obscurité de la nuit, et la récitation de l'aube » (17:78). Sahîh al-Bukhârî et Sahîh Muslim rapportent, dans le hadith du voyage nocturne, que les prières furent d'abord cinquante et furent réduites à cinq, en gardant la récompense de cinquante. Le musulman apprend que sa journée est organisée autour de cinq rendez-vous avec son Seigneur.",

"faith_154": "Le verset continue : « Le mois de Ramadan, durant lequel le Coran a été descendu comme guidée pour les gens, et preuves claires de la guidée et du discernement. Que celui d'entre vous qui voit le mois le jeûne ; et celui qui est malade ou en voyage, un nombre égal d'autres jours. Allah veut pour vous la facilité, et Il ne veut pas pour vous la difficulté » (2:185). Deux versets plus tôt, le jeûne est rendu obligatoire, comme il l'était pour les peuples d'avant (2:183). Le musulman apprend que le Ramadan est le mois du Livre autant que le mois du jeûne, et que la règle d'Allah fait place au malade et au voyageur.",

"faith_155": "Le mot zakât veut dire purification et croissance, et le Coran la joint à la prière encore et encore : « Accomplissez la prière et donnez la zakât » (2:43). Il dit aussi qui la reçoit : « L'aumône est seulement pour les pauvres et les nécessiteux » et les autres groupes que le verset nomme (9:60), et il fut dit au Prophète ﷺ : « Prends de leurs biens une aumône par laquelle tu les purifies » (9:103). Dans Sahîh al-Bukhârî 8, elle est comptée parmi les cinq piliers de l'islam. Le musulman apprend que donner une part de ce qu'il possède rend le reste pur, et que les pauvres ont un droit sur ses biens.",

"faith_156": "Le Coran rend le devoir clair : « Et c'est un devoir envers Allah pour les gens d'aller en pèlerinage à la Maison, pour quiconque peut y trouver un chemin » (3:97). Il raconte aussi comment l'appel a commencé, quand Ibrâhîm reçut l'ordre : « Annonce aux gens le pèlerinage ; ils viendront à toi à pied et sur tout chameau maigre, de tout passage lointain » (22:27). Les pèlerins portent un simple vêtement blanc, tournent autour de la Ka'ba, marchent entre Safâ et Marwa, que le Coran compte parmi les signes d'Allah (2:158), et se tiennent à 'Arafa (2:198). Le musulman qui peut voyager fait le voyage une fois, en répondant à l'appel d'Ibrâhîm.",

"faith_157": "Les six sont nommés par le Prophète ﷺ lui-même dans le hadith de Jibrîl, rapporté par 'Umar dans Sahîh Muslim 8 : quand Jibrîl vint sous la forme d'un homme et l'interrogea sur l'îmân, il répondit que c'est croire en Allah, en Ses anges, en Ses livres, en Ses messagers, au Jour dernier, et au destin, son bien et son mal. Le Coran en cite la plupart en un seul verset : « tous ont cru en Allah, en Ses anges, en Ses livres et en Ses messagers » (2:285). Le musulman apprend les six comme les croyances qui se tiennent derrière les cinq piliers.",

"faith_158": "La sourate n'a que quatre versets : « Dis : Il est Allah, Unique. Allah, le Seul à être imploré pour ce que nous désirons. Il n'a jamais engendré, n'a pas été engendré non plus, et nul n'est égal à Lui » (112:1-4). Elle est appelée Al-Ikhlâs, la sincérité, parce qu'elle ne parle de rien d'autre qu'Allah seul, et Sahîh al-Bukhârî rapporte que le Prophète ﷺ a dit qu'elle vaut un tiers du Coran. Tout autre verset qui parle d'Allah s'accorde avec elle : « Votre Dieu est un Dieu unique ; il n'est de dieu que Lui » (2:163). Le musulman apprend la sourate par cœur tout petit, et avec elle toute sa croyance au sujet d'Allah.",

"faith_159": "Le nom apparaît dès la toute première ligne du Coran, « Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux » (1:1), et Allah l'emploie pour Lui-même quand Il parle à Mûsâ : « Vraiment, Je suis Allah ; il n'est de dieu que Moi, adore-Moi donc » (20:14). Le Coran demande aussi : « Connais-tu quelqu'un qui porte le même nom que Lui ? » (19:65), car personne d'autre n'a jamais été appelé Allah. Ses autres noms Lui appartiennent aussi : « À Allah appartiennent les plus beaux noms » (7:180). Le musulman apprend qu'Allah n'est pas un titre mais Son propre nom, dans toutes les langues que parlent les musulmans.",

"faith_160": "Le Coran parle de lui-même : « Voici le Livre au sujet duquel il n'y a aucun doute, une guidée pour ceux qui craignent Allah » (2:2), et il raconte comment il est venu : « L'Esprit fidèle l'a fait descendre sur ton cœur, en une langue arabe claire » (26:193-195). Son nom veut dire la récitation, et son premier mot révélé fut un ordre de lire (96:1). Il est descendu au long des années de la mission du Prophète ﷺ, et Allah a promis de le garder : « Vraiment, c'est Nous qui avons fait descendre le Rappel, et c'est Nous qui en sommes le gardien » (15:9). Le musulman apprend le Coran comme la parole d'Allah, gardée sans changement depuis qu'elle a été révélée.",

"faith_161": "Le verset continue : « la première Maison établie pour les gens est celle de Bakka, bénie et guidée pour les mondes ; il s'y trouve des signes clairs, la station d'Ibrâhîm » (3:96-97). Bakka, c'est La Mecque, et le Coran dit qui en éleva les murs : « Quand Ibrâhîm élevait les fondations de la Maison, avec Ismâ'îl : notre Seigneur, accepte cela de nous » (2:127). Les musulmans du monde entier se tournent vers elle pour prier, comme il leur a été dit : « Tourne ton visage vers al-Masjid al-Harâm » (2:144). Le musulman apprend que la Ka'ba n'est pas adorée ; elle est la direction de l'adoration et la Maison qu'Ibrâhîm a bâtie pour Allah seul.",

"faith_162": "'Umar ibn Abî Salama raconte lui-même l'histoire dans Sahîh al-Bukhârî 5376 : il était un garçon qui vivait dans la maison du Prophète ﷺ, et aux repas sa main allait partout dans le plat, alors le Prophète ﷺ lui dit : « Garçon, dis le nom d'Allah, mange de ta main droite, et mange de ce qui est le plus près de toi. » Il ajoute que cela resta sa façon de manger pour toujours. Le Coran dit aux croyants : « mangez des bonnes choses que Nous vous avons données et soyez reconnaissants envers Allah » (2:172). Le musulman apprend les bonnes manières à table des mots mêmes du Prophète ﷺ : le nom d'Allah d'abord, la main droite, la nourriture devant soi.",

"faith_163": "La salutation est en arabe, as-salâmu 'alaykum, et c'est ce que disent les anges aux gens du Paradis : « Paix sur vous, pour ce que vous avez enduré avec patience » (13:24). Le Coran dit aux croyants : « Quand vous entrez dans des maisons, saluez-vous les uns les autres d'une salutation venant d'Allah, bénie et bonne » (24:61). Sahîh Muslim rapporte que le Prophète ﷺ a dit que les croyants n'entreront pas au Paradis avant de croire, ni ne croiront avant de s'aimer les uns les autres, et que répandre le salâm entre eux apporte cet amour. Le musulman apprend que sa salutation est une prière pour la sécurité de l'autre.",

"faith_164": "Le Coran fixe la règle pour toute salutation : « Quand on vous salue d'une salutation, saluez d'une meilleure, ou rendez-la » (4:86). Ainsi la réponse à as-salâmu 'alaykum est wa 'alaykum as-salâm, et la meilleure réponse ajoute wa rahmatullâhi wa barakâtuh, et la miséricorde d'Allah et Ses bénédictions. Le verset se termine : « Vraiment, Allah tient compte de toute chose » (4:86), ainsi même une salutation est comptée. Le musulman apprend à répondre à chaque salâm qu'il entend, et à y ajouter quand il le peut.",

"faith_165": "Le nom de la fête veut dire la rupture du jeûne, et elle tombe le premier jour de Shawwâl, le mois qui suit le Ramadan. Le Coran, après avoir ordonné le jeûne, dit pourquoi le mois se termine par des remerciements : « pour que vous complétiez le nombre et que vous glorifiiez Allah de vous avoir guidés, et afin que vous soyez reconnaissants » (2:185). Le matin de l'Aïd, les musulmans donnent une aumône de nourriture aux pauvres avant la prière, puis se rassemblent pour la prière de l'Aïd et se rendent visite les uns aux autres. Sahîh al-Bukhârî rapporte que le Prophète ﷺ a dit que chaque peuple a sa fête et que celle-ci est la nôtre. Le musulman apprend qu'un mois difficile se termine par la reconnaissance et le partage.",

"faith_166": "Le nom de la fête veut dire le sacrifice, et elle tombe le dixième jour de Dhû-l-Hijja, quand les pèlerins à Minâ offrent leurs bêtes et que les musulmans du monde entier font de même. Elle rappelle Ibrâhîm, prêt à sacrifier son fils quand Allah le lui ordonna en rêve, jusqu'à ce qu'Allah appelle : « Ô Ibrâhîm, tu as réalisé la vision », et « Nous l'avons racheté par un grand sacrifice » (37:104-107). Le Coran dit à quoi sert l'offrande : « Ni leur chair ni leur sang n'atteindront Allah, mais ce qui L'atteint, c'est votre piété » (22:37). Le musulman apprend que la viande est partagée avec la famille et les pauvres, et que le vrai don est l'obéissance.",

"faith_167": "Le Coran décrit les anges avec ces mots : « Ils ne désobéissent pas à Allah dans ce qu'Il leur ordonne, et ils font ce qui leur est ordonné » (66:6), et encore : « Ceux qui sont auprès de Lui ne sont pas trop fiers pour L'adorer, et ils ne se lassent pas ; ils Le glorifient nuit et jour et ne faiblissent jamais » (21:19-20). Ils sont créés par Allah et envoyés comme Ses messagers, avec des ailes, deux, trois et quatre (35:1) ; Jibrîl a fait descendre le Coran sur le cœur du Prophète ﷺ (2:97). Le musulman apprend à croire en des êtres qu'il ne peut pas voir, dont toute la vie est obéissance à Allah.",

"faith_168": "Le Coran l'appelle un jardin parce qu'il est plein d'arbres et d'eau : « des jardins sous lesquels coulent les ruisseaux » (2:25) est sa description la plus fréquente. Il est « large comme les cieux et la terre, préparé pour ceux qui craignent Allah » (3:133), et ceux qui y entrent entendent : « Entrez-y en paix, en sécurité » (15:46). Sahîh al-Bukhârî et Sahîh Muslim rapportent que le Prophète ﷺ a dit qu'Allah a préparé pour Ses serviteurs vertueux ce qu'aucun œil n'a vu, ce qu'aucune oreille n'a entendu, et ce qu'aucun cœur humain n'a imaginé. Le musulman apprend à travailler pour une demeure plus belle que tout ce qui est en ce monde.",

"faith_169": "Le Coran lui-même donne les étapes : « Ô vous qui croyez, quand vous vous levez pour la prière, lavez vos visages et vos mains jusqu'aux coudes, passez les mains mouillées sur vos têtes, et lavez vos pieds jusqu'aux chevilles » (5:6). Le même verset dit qu'Allah ne veut pas vous rendre les choses difficiles, mais qu'Il veut vous purifier et achever Son bienfait sur vous. Sahîh al-Bukhârî rapporte que le Prophète ﷺ a dit que la prière de celui qui a perdu sa pureté n'est pas acceptée tant qu'il n'a pas fait le wudû'. Le musulman apprend qu'il vient parler à son Seigneur en étant propre, et que le wudû' est la première partie de la prière.",

"faith_170": "Le mot rak'a vient de rukû', l'inclinaison, et le Coran appelle les croyants « ceux qui s'inclinent et ceux qui se prosternent » (9:112) et ordonne : « Ô vous qui croyez, inclinez-vous, prosternez-vous et adorez votre Seigneur » (22:77). Une rak'a se déroule dans cet ordre : debout avec la récitation d'al-Fâtiha, inclinaison, debout de nouveau, prosternation, position assise, prosternation de nouveau. Chaque musulman compte les prières par leurs rak'as : Fajr en a deux, Maghrib trois, et Dhuhr, 'Asr et 'Ishâ' quatre chacune. Le musulman apprend la rak'a comme la brique de toute la prière.",

"faith_171": "'Ubâda ibn as-Sâmit rapporte dans Sahîh al-Bukhârî que le Prophète ﷺ a dit qu'il n'y a pas de prière pour celui qui ne récite pas l'Ouverture du Livre. Le Prophète ﷺ l'a aussi appelée, dans Sahîh al-Bukhârî, les « sept répétés » dont parle le Coran (15:87), et elle est répétée au moins dix-sept fois par jour au long des cinq prières. Ses sept versets louent Allah, Seigneur des mondes, puis Lui demandent : « C'est Toi seul que nous adorons et c'est Toi seul dont nous implorons l'aide ; guide-nous sur le droit chemin » (1:5-6). Le musulman apprend al-Fâtiha avant toutes les autres sourates, parce que sans elle la prière ne peut pas se faire.",

"faith_172": "Le Coran emploie le mot dans ses ordres sur la nourriture : « Ô hommes, mangez de ce qui est sur la terre, licite et bon » (2:168), et : « Mangez de ce qu'Allah vous a donné, licite et bon, et soyez reconnaissants pour le bienfait d'Allah » (16:114). Il décrit le Prophète ﷺ comme celui qui « leur rend licites les bonnes choses et leur interdit les mauvaises » (7:157). Sahîh al-Bukhârî et Sahîh Muslim rapportent qu'il a dit que le halâl est clair et que le harâm est clair. Le musulman apprend que ce qu'Allah a permis est vaste et bon, et que le manger en remerciant est déjà une adoration.",

"faith_173": "La même racine donne al-Masjid al-Harâm, la mosquée sacrée, car harâm veut d'abord dire ce qui est mis à part et ne doit pas être touché. Le Coran dit au Prophète ﷺ : « Dis : mon Seigneur a seulement interdit les actes honteux, visibles et cachés, le péché, l'oppression injuste, et que vous associez à Allah ce pour quoi Il n'a fait descendre aucune preuve » (7:33). Il avertit aussi : « Ne dites pas, d'après ce que vos langues décrivent faussement : ceci est licite et ceci est illicite » (16:116). Le musulman apprend que seul Allah décide de ce qui est harâm, et que la liste est courte à côté de tout ce qu'Il permet.",

"faith_174": "Le verset dit en entier : « Il vous a seulement interdit la bête morte, le sang, la chair de porc, et ce qui a été offert à un autre qu'Allah ; mais celui qui y est forcé par le besoin, sans le désirer et sans aller trop loin, il n'y a pas de péché sur lui ; vraiment Allah est Pardonneur et Miséricordieux » (2:173). Le verset d'avant s'ouvre sur la large permission : « mangez des bonnes choses que Nous vous avons données et soyez reconnaissants envers Allah » (2:172). Les mêmes quatre choses sont interdites encore en 6:145 et 16:115. Le musulman apprend que la règle est claire et petite, et qu'Allah la lève pour celui qui n'a rien d'autre à manger.",

"faith_175": "Le verset donne une liste et une raison : « Ô vous qui croyez, le vin, le jeu de hasard, les autels de sacrifice et les flèches de divination ne sont qu'une souillure de l'œuvre de Satan ; écartez-vous-en, afin que vous réussissiez » (5:90). Le verset suivant explique ce que fait le vin : Satan s'en sert « pour semer entre vous l'hostilité et la haine, et pour vous détourner du rappel d'Allah et de la prière » (5:91). Le mot arabe khamr couvre toute boisson qui trouble l'esprit, et Sahîh Muslim rapporte que le Prophète ﷺ a dit que tout enivrant est khamr et que tout enivrant est interdit. Le musulman apprend que l'esprit est un dépôt, gardé clair pour se souvenir d'Allah.",

"faith_176": "Abû Hurayra rapporte dans Sahîh al-Bukhârî 6224 tout l'échange : quand l'un de vous éternue, qu'il dise al-hamdu lillâh ; que son frère ou son compagnon réponde yarhamuk Allah, qu'Allah te fasse miséricorde ; et que celui qui a éternué réponde yahdîkum Allah wa yuslih bâlakum, qu'Allah vous guide et arrange vos affaires. Ainsi un éternuement devient trois courtes prières échangées entre deux personnes. Les mots al-hamdu lillâh sont les mêmes qui ouvrent al-Fâtiha : « Louange à Allah, Seigneur des mondes » (1:2). Le musulman apprend à remercier Allah même pour un éternuement, et à répondre par une prière pour celui qui est à côté de lui.",

"faith_177": "Le mot salât est le mot du Coran lui-même pour la prière ; Allah dit à Mûsâ : « Accomplis la prière pour te souvenir de Moi » (20:14). Le Coran dit ce qu'elle fait pour celui qui prie : « Vraiment, la prière éloigne des actes honteux et mauvais, et le rappel d'Allah est plus grand » (29:45), et il la nomme à côté de la patience comme l'aide du croyant : « Cherchez de l'aide dans la patience et la prière » (2:45). L'appel à la prière emploie aussi ce mot : hayya 'ala as-salât, venez à la prière. Le musulman apprend que as-salât a des mots et des mouvements fixés, différents de la demande libre du du'â'.",

"faith_178": "Le Coran dit que l'invitation vient d'Allah Lui-même : « Votre Seigneur dit : appelez-Moi, Je vous répondrai » (40:60), et : « Quand Mes serviteurs t'interrogent sur Moi, vraiment Je suis proche ; Je réponds à l'appel de celui qui appelle quand il M'appelle » (2:186). Les prophètes priaient ainsi : Ibrâhîm demanda : « Mon Seigneur, fais de moi quelqu'un qui accomplit la prière, et de mes descendants aussi » (14:40), et Zakariyyâ appela son Seigneur à voix basse pour avoir un fils (19:3-4). Le du'â' n'a besoin ni de mots fixés, ni d'heure, ni de lieu, seulement d'un cœur tourné vers Allah. Le musulman apprend à parler à son Seigneur avec ses propres mots, sûr d'être entendu.",

"faith_179": "Al-Fâtiha s'ouvre ainsi : « Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux. Louange à Allah, Seigneur des mondes » (1:1-2). Le hamd est une louange donnée avec amour et remerciement, et le verset 1:2 la donne à Allah parce qu'Il est le Seigneur de tous les mondes qui existent. Les mêmes mots ouvrent quatre autres sourates, Al-An'âm, Al-Kahf, Saba' et Fâtir, et le Coran dit qu'ils sont les derniers mots des gens du Paradis : « la fin de leur appel est : louange à Allah, Seigneur des mondes » (10:10). Le musulman dit al-hamdu lillâh après avoir mangé, après avoir éternué et quand une bonne nouvelle arrive, et il l'entend dans chaque rak'a.",

"faith_180": "La racine du mot donne salâm, la paix, et aslama, se remettre entre les mains de quelqu'un. Le Coran montre Ibrâhîm faisant exactement cela : « Quand son Seigneur lui dit : soumets-toi, il dit : je me soumets au Seigneur des mondes » (2:131). Allah nomme la religion avec ce mot, « Vraiment, la religion auprès d'Allah, c'est l'islam » (3:19), et pendant le pèlerinage du Prophète ﷺ ce verset descendit : « Aujourd'hui, J'ai parachevé pour vous votre religion, et J'ai choisi pour vous l'islam comme religion » (5:3). Le musulman apprend qu'islam est le mot qu'Allah a choisi, qui veut dire se donner à Lui et y trouver la paix.",

"faith_181": "Le Coran dit qui a donné le nom : « C'est Lui qui vous a nommés musulmans, avant et en ceci » (22:78). Ibrâhîm et Ismâ'îl priaient avec ce mot en bâtissant la Ka'ba : « Notre Seigneur, fais de nous deux Tes soumis, et de nos descendants une communauté soumise à Toi » (2:128), et Ya'qûb dit à ses fils : « ne mourez qu'en musulmans » (2:132). Le Coran dit d'Ibrâhîm qu'« il n'était ni juif ni chrétien, mais il était droit, musulman » (3:67). Le musulman apprend que son nom le lie à chaque prophète qui s'est donné à Allah, bien avant la naissance du Prophète ﷺ.",

"faith_182": "La sourate s'ouvre sur la louange et sa raison : « Louange à Allah, qui a créé les cieux et la terre, et qui a fait les ténèbres et la lumière ; pourtant ceux qui ne croient pas donnent des égaux à leur Seigneur » (6:1). Le verset suivant se tourne vers l'être humain : « C'est Lui qui vous a créés d'argile, puis a fixé un terme » (6:2). Ailleurs, le Coran dit qu'Il a créé les cieux et la terre en six jours, puis s'est établi sur le Trône (7:54), et qu'Il n'a pas d'associé dans Son royaume (25:2). Le musulman apprend à regarder le ciel et la terre et à répondre par les mots qui ouvrent la sourate Al-An'âm.",

"faith_183": "Abû Hurayra rapporte dans Sahîh al-Bukhârî 2736 que le Prophète ﷺ a dit qu'Allah a quatre-vingt-dix-neuf noms, cent moins un, et que celui qui les apprend tous par cœur entrera au Paradis. C'est dans le Coran que l'on trouve les noms : « À Allah appartiennent les plus beaux noms, appelez-Le donc par eux » (7:180), et un passage en rassemble beaucoup : le Roi, le Saint, la Paix, le Créateur, Celui qui donne un commencement, Celui qui donne la forme (59:23-24). Le musulman apprend les noms dans le Coran et appelle Allah par celui qui convient à son besoin : le Pardonneur quand il a fauté, le Pourvoyeur quand il est dans le manque.",

"faith_184": "Le verset appelle les anges « nobles et scribes » (82:11), et les versets autour complètent l'image : « Vraiment, il y a sur vous des gardiens » (82:10), « ils savent ce que vous faites » (82:12). Ils viennent dans la sourate Al-Infitâr, juste après qu'Allah a demandé : « Ô homme, qu'est-ce qui t'a trompé au sujet de ton Seigneur généreux ? » (82:6), et juste avant que la sourate dise que les bons seront dans le bonheur et les mauvais dans le Feu (82:13-14). La sourate Qâf ajoute que les deux anges sont assis à droite et à gauche, et qu'aucune parole n'est dite sans un observateur prêt à côté de lui (50:17-18). Le musulman apprend que rien de ce qu'il fait n'est perdu, et que son propre registre lui sera montré.",

"faith_185": "La sourate n'a que cinq versets : « Vraiment, Nous l'avons fait descendre pendant la Nuit du Destin. Et qui te dira ce qu'est la Nuit du Destin ? La Nuit du Destin est meilleure que mille mois » (97:1-3). Les versets suivants disent que les anges et l'Esprit y descendent pour tout ordre, et qu'elle est paix jusqu'à l'aube (97:4-5). Ce qui a été descendu est le Coran, et la sourate Al-Baqara place cette descente en Ramadan (2:185). Sahîh al-Bukhârî rapporte que le Prophète ﷺ a dit aux croyants de la chercher dans les nuits impaires des dix dernières de Ramadan. Le musulman passe ces nuits en prière, en espérant rencontrer la nuit nommée en 97:3.",

"faith_186": "Le mot vient de wâhid, un, et veut dire reconnaître Allah comme unique : L'adorer seul, sans associé. Le Coran dit que chaque messager a été envoyé avec cela : « Nous n'avons envoyé avant toi aucun messager sans lui révéler : il n'est de dieu que Moi, adorez-Moi donc » (21:25), et : « Nous avons envoyé à chaque communauté un messager, disant : adorez Allah et écartez-vous des fausses divinités » (16:36). Sa formule la plus courte est la sourate Al-Ikhlâs, « Dis : Il est Allah, Unique » (112:1), et sa formule de chaque jour est la première moitié de la shahâda. Le musulman apprend que le tawhîd est le seul message que Nûh, Ibrâhîm, Mûsâ, 'Îsâ et Muhammad ﷺ ont tous partagé.",

"faith_187": "Le mot veut dire donner un associé, et le Coran le traite comme la seule faute qu'Allah dit ne pas pardonner : « Vraiment, Allah ne pardonne pas qu'on Lui donne des associés, mais Il pardonne ce qui est moins que cela à qui Il veut » (4:48). Le sage Luqmân donna cela à son fils comme première leçon : « Ô mon fils, n'associe rien à Allah ; vraiment, l'association est une grande injustice » (31:13). L'ordre est dit simplement ailleurs : « Adorez Allah et ne Lui associez rien » (4:36). Le musulman apprend à garder chaque acte d'adoration pour Allah seul.",

"faith_188": "Le Coran jure par ce Jour : « Je jure par le Jour de la Résurrection » (75:1), et il lui donne aussi d'autres noms : le Jour du Jugement, l'Heure, le Jour des Comptes. Il dit ce qui arrive : « Ce Jour-là, les gens s'avanceront en groupes séparés pour qu'on leur montre leurs actes. Celui qui fait le poids d'un atome de bien le verra, et celui qui fait le poids d'un atome de mal le verra » (99:6-8). Les balances seront dressées pour qu'aucune âme ne soit lésée (21:47), et chaque musulman nomme ce Jour dans chaque rak'a, quand al-Fâtiha appelle Allah « Maître du Jour du Jugement » (1:4). Le musulman apprend à vivre comme quelqu'un à qui l'on montrera ses actes.",

"faith_189": "Le verset dit : « Vraiment, le nombre de mois auprès d'Allah est de douze mois, dans le décret d'Allah depuis le jour où Il a créé les cieux et la terre ; parmi eux, quatre sont sacrés » (9:36). Les mois musulmans suivent la lune : le Coran dit que les croissants sont « des mesures du temps pour les gens et pour le pèlerinage » (2:189), et qu'Allah a fait les phases de la lune « pour que vous connaissiez le nombre des années et le calcul » (10:5). Le Ramadan est le neuvième des douze, et Dhû-l-Hijja, le mois du pèlerinage, le dernier. Le musulman apprend que son calendrier se compte par la nouvelle lune, et que quatre de ses mois sont sacrés.",

"faith_190": "Chaque musulman prie de la même façon : après s'être incliné et redressé, il descend au sol, se rassoit, et descend une seconde fois avant de se relever ou de s'asseoir pour le tashahhud. Sahîh al-Bukhârî rapporte que le Prophète ﷺ a dit qu'il avait reçu l'ordre de se prosterner sur sept os : le front avec le nez, les deux mains, les deux genoux et les orteils des deux pieds. Le Coran termine la sourate Al-'Alaq par l'ordre « Prosterne-toi et rapproche-toi » (96:19), et Sahîh Muslim rapporte que le Prophète ﷺ a dit que le serviteur est le plus proche de son Seigneur quand il se prosterne. Le musulman apprend que les deux prosternations sont les moments les plus proches de la prière.",
}
