"""Français — détails, prophets_c_1 (50 questions)."""

D = {
"prophets_151": "L'ordre est donné dans la sourate Al-Baqara : « Ô Adam, habite le Paradis, toi et ton épouse, et mangez-en librement où vous voudrez, mais n'approchez pas de cet arbre, sinon vous seriez du nombre des injustes » (2:35). Il vient juste après que les anges se sont prosternés devant Adam et qu'Iblîs a refusé (2:34), et juste avant que Satan ne les fasse glisser tous deux (2:36). Un musulman apprend que l'obéissance se prouve à la seule limite qu'Allah fixe, non dans l'abondance qu'Il permet.",

"prophets_152": "Le verset dit : « Puis Adam reçut de son Seigneur des paroles, et Il agréa son repentir. Il est Celui qui accueille le repentir, le Miséricordieux » (2:37). La sourate Al-Aʿrâf rapporte la prière d'Adam et de son épouse : « Notre Seigneur, nous nous sommes fait du tort à nous-mêmes, et si Tu ne nous pardonnes pas et ne nous fais pas miséricorde, nous serons du nombre des perdants » (7:23). Un musulman apprend que le chemin du retour vers Allah fut ouvert pour le premier être humain.",

"prophets_153": "Le verset dit : « ʿÎsâ est auprès d'Allah comme Adam : Il le créa de terre, puis lui dit “Sois”, et il fut » (3:59). La sourate Âl ʿImrân vient de raconter la naissance de ʿÎsâ, et le verset suivant clôt l'argument : « La vérité vient de ton Seigneur, ne sois donc pas du nombre de ceux qui doutent » (3:60). Un musulman en retient que ʿÎsâ est un serviteur et un messager créé, et qu'un prodige dans la naissance renvoie au Créateur.",

"prophets_154": "La sourate Maryam dit : « Mentionne dans le Livre Idrîs. C'était un véridique, un prophète. Et Nous l'élevâmes à un rang élevé » (19:56-57). Il clôt une série de prophètes que la sourate demande au Prophète ﷺ de mentionner : Ibrâhîm (19:41), Mûsâ (19:51), Ismâʿîl (19:54), puis Idrîs. La sourate les rassemble ensuite tous comme ceux qu'Allah a comblés de Ses faveurs, qui tombaient prosternés et en pleurs quand Ses versets leur étaient récités (19:58). Un musulman apprend qu'Idrîs est honoré pour deux choses nommées ensemble, la véracité et la prophétie.",

"prophets_155": "Les paroles de Nûh sont dans la sourate Hûd : « Montez dedans : au nom d'Allah seront sa course et son mouillage. Mon Seigneur est Pardonneur et Miséricordieux » (11:41). Le verset précédent montre le four qui déborde, signe que le déluge avait commencé, avec l'ordre d'embarquer un couple de chaque espèce et le petit nombre de ceux qui avaient cru (11:40). Un musulman apprend de Nûh à commencer tout voyage par le nom d'Allah, en s'en remettant à Lui pour le départ et pour l'arrivée.",

"prophets_156": "La prière clôt la sourate Nûh : « Mon Seigneur, ne laisse sur la terre aucun habitant parmi les mécréants. Si Tu les laisses, ils égareront Tes serviteurs et n'engendreront que des pervers mécréants » (71:26-27). Elle vient après que Nûh a dit à son Seigneur qu'il avait appelé son peuple nuit et jour, et que son appel n'avait fait qu'accroître leur fuite (71:5-6) ; le Coran compte son séjour parmi eux à mille ans moins cinquante (29:14). Un musulman apprend que Nûh ne demanda cela qu'après toute une vie d'appel patient.",

"prophets_157": "L'ordre est dans la sourate Al-Mu'minûn : « Construis le vaisseau sous Nos yeux et selon Notre révélation, et quand Notre ordre viendra et que le four débordera, fais-y monter un couple de chaque espèce, ainsi que ta famille, sauf ceux contre qui la parole a déjà été prononcée » (23:27). Juste avant, son peuple l'avait traité de simple homme comme eux, et il avait prié : « Mon Seigneur, secours-moi, car ils m'ont traité de menteur » (23:26). Un musulman apprend que le secours d'Allah vint avec des instructions précises, et que Nûh y répondit par la louange (23:28).",

"prophets_158": "Hûd dit aux ʿÂd dans la sourate Al-Aʿrâf : « Rappelez-vous : Il vous a faits successeurs après le peuple de Nûh et Il vous a largement accrus en stature. Rappelez-vous donc les bienfaits d'Allah, afin que vous réussissiez » (7:69). Il avait commencé comme tout prophète, « Ô mon peuple, adorez Allah ; vous n'avez pas d'autre dieu que Lui » (7:65), et les notables répondirent qu'ils le voyaient dans la sottise (7:66). Un musulman apprend que la force d'un peuple est un bienfait à se rappeler, et que s'en souvenir est le chemin de la réussite.",

"prophets_159": "La sourate Al-Hâqqa dit : « Quant aux ʿÂd, ils furent détruits par un vent glacial, impétueux, qu'Il déchaîna contre eux sept nuits et huit jours consécutifs, de sorte que tu aurais vu les gens là, renversés, comme des troncs creux de palmiers » (69:6-7). La sourate les associe aux Thamûd, qui « furent détruits par le cataclysme foudroyant » (69:5). Un musulman apprend que le vent qui nous sert chaque jour est un soldat d'Allah, et qu'aucune force ne tient devant Lui.",

"prophets_160": "Hûd demande dans la sourate Ash-Shuʿarâ : « Bâtissez-vous sur chaque hauteur un monument, par vanité, et prenez-vous des forteresses comme si vous deviez vivre éternellement ? » (26:128-129). Il avait ouvert par l'appel que la sourate donne à chaque messager, « Ne craindrez-vous pas Allah ? » (26:124), et il continue en nommant Celui qui leur a accordé bétail, enfants, jardins et sources (26:132-134). Un musulman apprend à employer la richesse pour le besoin et la gratitude plutôt que pour le paraître, en se rappelant que la terre n'est pas une demeure permanente.",

"prophets_161": "Sâlih dit aux Thamûd dans la sourate Al-Aʿrâf : « Rappelez-vous : Il vous a faits successeurs après les ʿÂd et vous a établis sur la terre : vous prenez des châteaux dans ses plaines et vous taillez des demeures dans les montagnes. Rappelez-vous donc les bienfaits d'Allah, et ne parcourez pas la terre en y semant la corruption » (7:74). Juste avant, il leur avait montré la chamelle d'Allah comme un signe, en leur disant de ne pas lui faire de mal (7:73). Un musulman apprend que le savoir-faire d'un peuple vient d'Allah, et que la juste réponse est la gratitude.",

"prophets_162": "Allah dit à Sâlih dans la sourate Al-Qamar : « Nous leur envoyons la chamelle comme épreuve. Surveille-les donc et sois patient. Et informe-les que l'eau doit être partagée entre eux : chaque tour de boisson sera respecté » (54:27-28). Les Thamûd avaient refusé de suivre « un seul être humain d'entre nous » et avaient traité Sâlih de menteur insolent (54:24-25). Ils échouèrent à l'épreuve : leur compagnon coupa les jarrets de la chamelle (54:29). Un musulman apprend qu'un signe d'Allah est aussi une épreuve sur la manière dont on le traite.",

"prophets_163": "La sourate Al-Aʿrâf raconte la fin : « Le tremblement les saisit, et au matin ils gisaient dans leurs demeures » (7:78). Le verset précédent en donne la cause : ils coupèrent les jarrets de la chamelle, méprisèrent l'ordre de leur Seigneur et défièrent Sâlih : « Apporte-nous ce que tu nous promets, si tu es du nombre des messagers » (7:77). Un musulman apprend qu'un châtiment réclamé par moquerie peut venir, et que le conseil du prophète était la vraie protection.",

"prophets_164": "La sourate Ash-Shuʿarâ rapporte : « Quand leur frère Lût leur dit : Ne craindrez-vous pas Allah ? Je suis pour vous un messager digne de confiance ; craignez donc Allah et obéissez-moi. Je ne vous demande pour cela aucun salaire ; mon salaire n'incombe qu'au Seigneur des mondes » (26:161-164). La sourate donne les mêmes paroles d'ouverture à Nûh, Hûd, Sâlih et Shuʿayb, chacun appelé « leur frère ». Un musulman apprend que Lût vint à son peuple en frère, avec l'appel que tout messager apporta.",

"prophets_165": "Les anges disent à Lût dans la sourate Hûd : « Nous sommes les messagers de ton Seigneur ; ils ne t'atteindront jamais. Pars donc avec ta famille dans une partie de la nuit, et que nul d'entre vous ne se retourne, sauf ta femme : elle sera frappée par ce qui les frappera. Leur rendez-vous est le matin » (11:81). À l'aube, la cité fut renversée sens dessus dessous et couverte d'une pluie de pierres d'argile cuite (11:82). Un musulman apprend qu'obéir aux instructions d'Allah sans se retourner était la voie du salut.",

"prophets_166": "La sourate Hûd dit : « Et aux Madyan, leur frère Shuʿayb. Il dit : Ô mon peuple, adorez Allah ; vous n'avez pas d'autre dieu que Lui. Et ne diminuez pas la mesure et le poids. Je vous vois dans la prospérité, et je crains pour vous le châtiment d'un Jour qui enveloppera tout » (11:84). Il poursuit : « Donnez la pleine mesure et le plein poids avec justice, et ne privez pas les gens de leur dû » (11:85). L'adoration d'Allah seul et l'honnêteté de la balance tiennent dans un même souffle. Un musulman apprend que la loyauté dans le commerce fait partie de la foi.",

"prophets_167": "Shuʿayb dit dans la sourate Hûd : « Je ne veux pas faire, en votre absence, ce que je vous interdis. Je ne veux que la réforme, autant que je le puis. Ma réussite ne dépend que d'Allah ; en Lui je place ma confiance, et vers Lui je reviens » (11:88). Son peuple venait de se moquer de lui : « Est-ce ta prière qui te commande que nous abandonnions ce qu'adoraient nos pères ? » (11:87). Un musulman apprend que celui qui appelle au bien doit d'abord le vivre lui-même, et compter sur Allah pour le résultat.",

"prophets_168": "La sourate Al-Baqara dit : « Quand Ibrâhîm fut éprouvé par son Seigneur par des paroles et qu'il les accomplit, Il dit : Je vais faire de toi un guide pour les gens. Il dit : Et parmi ma descendance ? Il dit : Mon engagement ne s'étend pas aux injustes » (2:124). Les versets suivants montrent ce que ce rôle de guide signifiait : la Maison faite lieu de retour et de sécurité, et Ibrâhîm et Ismâʿîl élevant ses fondations en priant « Notre Seigneur, accepte de nous » (2:125-127). Un musulman apprend que la direction en religion est donnée pour une obéissance accomplie, non héritée par le sang.",

"prophets_169": "La sourate Al-Baqara le raconte : « Quand Ibrâhîm dit : Mon Seigneur est Celui qui donne la vie et donne la mort, il dit : Moi, je donne la vie et je donne la mort. Ibrâhîm dit : Allah fait venir le soleil du Levant, fais-le donc venir du Couchant. Et celui qui avait mécru resta confondu » (2:258). Le verset dit que l'homme disputa « parce qu'Allah lui avait donné la royauté » et le laisse sans nom. Un musulman apprend à répondre à une prétention fausse par une preuve claire qu'aucune puissance sur terre ne peut imiter.",

"prophets_170": "L'ordre dit : « Et appelle les gens au pèlerinage : ils viendront vers toi à pied et sur toute monture élancée, venant de tout chemin éloigné » (22:27). Le verset précédent plante le décor : Allah installa Ibrâhîm à l'emplacement de la Maison, avec l'ordre de ne rien Lui associer et de la purifier pour ceux qui tournent autour, se tiennent debout, s'inclinent et se prosternent (22:26). Un musulman apprend que le Hajj est une invitation lancée d'abord par Ibrâhîm, et que chaque pèlerin d'aujourd'hui y répond.",

"prophets_171": "La sourate Adh-Dhâriyât le raconte : « Quand ils entrèrent chez lui et dirent : Paix. Il dit : Paix, gens inconnus. Puis il s'éclipsa vers sa famille et apporta un veau gras, le plaça devant eux et dit : Ne mangerez-vous pas ? » (51:24-27). Quand leurs mains ne se tendirent pas vers lui, il prit peur ; ils dirent : « Ne crains rien », et lui annoncèrent la bonne nouvelle d'un garçon plein de savoir (51:28). Un musulman apprend l'hospitalité d'Ibrâhîm : rendre le salut, s'éclipser discrètement, apporter le meilleur, le placer tout près et inviter avec douceur.",

"prophets_172": "La sourate Al-Mumtahana dit : « Vous avez eu un bel exemple en Ibrâhîm et en ceux qui étaient avec lui, quand ils dirent à leur peuple : Nous nous désolidarisons de vous et de ce que vous adorez en dehors d'Allah. Nous vous renions, et entre nous et vous sont apparues l'inimitié et la haine pour toujours, jusqu'à ce que vous croyiez en Allah seul » (60:4). Le même verset se termine par leur prière : « Notre Seigneur, en Toi nous plaçons notre confiance, vers Toi nous revenons » (60:4). Un musulman apprend que la loyauté appartient d'abord à Allah.",

"prophets_173": "La prière commence ainsi : « Mon Seigneur, fais de cette cité un lieu sûr, et préserve-moi ainsi que mes fils de l'adoration des idoles. Mon Seigneur, elles ont égaré beaucoup de gens » (14:35-36). Ibrâhîm dit ensuite qu'il a installé une partie de sa descendance dans une vallée sans culture, près de la Maison sacrée d'Allah, et demande que des cœurs s'inclinent vers eux et qu'ils soient pourvus de fruits (14:37). Un musulman apprend d'Ibrâhîm ce qu'il faut demander pour ses enfants avant la nourriture ou le confort : qu'ils adorent Allah seul.",

"prophets_174": "La sourate As-Sâffât rapporte : « Il dit : Je pars vers mon Seigneur ; Il me guidera. Mon Seigneur, accorde-moi un enfant d'entre les vertueux. Nous lui annonçâmes alors la bonne nouvelle d'un garçon longanime » (37:99-101). Ces paroles viennent juste après que son peuple, vaincu dans la dispute sur les idoles qu'il avait brisées, tenta de le brûler : « ils complotèrent contre lui, mais Nous les rendîmes les plus bas » (37:98). Un musulman apprend que quitter son peuple pour Allah est un voyage vers la guidance, et que son premier fruit fut un fils vertueux.",

"prophets_175": "La sourate Maryam dit : « Mentionne dans le Livre Ismâʿîl. Il était fidèle à sa promesse, et c'était un messager et un prophète. Il commandait à sa famille la prière et la zakât, et il était agréé auprès de son Seigneur » (19:54-55). Il apparaît dans la série de prophètes de la sourate, après Mûsâ et Hârûn (19:51-53) et avant Idrîs (19:56). Un musulman apprend que tenir sa parole est une marque de la prophétie, et que la prière et la zakât commencent à la maison.",

"prophets_176": "Yaʿqûb dit dans la sourate Yûsuf : « Ô mon fils, ne raconte pas ta vision à tes frères, car ils trameraient une ruse contre toi. Satan est pour l'homme un ennemi déclaré » (12:5). Yûsuf venait de lui dire : « Ô mon père, j'ai vu onze étoiles, le soleil et la lune ; je les ai vus se prosterner devant moi » (12:4). À la fin de la sourate, la famille de Yûsuf se prosterne devant lui (12:100). Un musulman apprend à protéger un bienfait de l'envie et à faire confiance à Allah pour l'accomplir.",

"prophets_177": "La sourate Yûsuf rapporte : « Un témoin de la famille de celle-ci témoigna : si sa tunique est déchirée par devant, elle a dit la vérité et lui est un menteur ; mais si sa tunique est déchirée par derrière, elle a menti et il est parmi les véridiques » (12:26-27). Le verset suivant tranche : « Quand il vit sa tunique déchirée par derrière, il dit : Voilà une de vos ruses de femmes » (12:28). Un musulman apprend qu'Allah mit au jour l'innocence de Yûsuf par un signe évident.",

"prophets_178": "La sourate Yûsuf le raconte : « Elle les fit venir et leur prépara un festin, remit à chacune un couteau, et dit : Sors devant elles. Quand elles le virent, elles furent saisies d'admiration et se coupèrent les mains, et dirent : À Allah ne plaise ! Ce n'est pas un être humain ; ce n'est qu'un ange noble » (12:31). Elle le menaça de prison, et Yûsuf pria : « Mon Seigneur, la prison m'est plus chère que ce à quoi elles m'appellent » (12:33). Un musulman apprend que Yûsuf choisit la prison plutôt que de désobéir à Allah.",

"prophets_179": "Yûsuf dit : « Ô mes deux compagnons de prison, des seigneurs séparés valent-ils mieux qu'Allah, l'Unique, le Dominateur ? Vous n'adorez en dehors de Lui que des noms que vous et vos pères avez inventés, et pour lesquels Allah n'a fait descendre aucune preuve. Le jugement n'appartient qu'à Allah » (12:39-40). Deux jeunes gens lui avaient demandé d'interpréter leurs rêves, voyant en lui un homme de bien (12:36). Un musulman apprend à placer l'appel à l'unicité d'Allah avant tout autre service.",

"prophets_180": "La sourate Yûsuf rapporte : « Le roi dit : Amenez-le-moi ; je le prendrai pour moi-même. Et quand il lui eut parlé, il dit : Tu es dès aujourd'hui près de nous en une position d'autorité, digne de confiance » (12:54). Yûsuf avait refusé de quitter la prison tant que l'affaire des femmes ne serait pas éclaircie (12:50). Il répondit à l'offre du roi par une demande : « Confie-moi les greniers du pays » (12:55). Un musulman apprend que le rang de Yûsuf vint après que son honneur fut lavé, et qu'il s'en servit pour assumer une charge.",

"prophets_181": "La sourate Yûsuf dit : « Il commença par leurs sacs avant le sac de son frère, puis il la sortit du sac de son frère. Ainsi suggérâmes-Nous cette ruse à Yûsuf ; il ne pouvait retenir son frère selon la loi du roi, à moins qu'Allah ne le voulût. Nous élevons en degrés qui Nous voulons, et au-dessus de tout homme de savoir il en est un plus savant » (12:76). Les frères eux-mêmes avaient fixé la peine : celui dans le sac duquel elle serait trouvée serait retenu (12:75). Un musulman apprend qu'Allah arrange les événements au-delà du regard des hommes.",

"prophets_182": "Les paroles de Yûsuf sont dans la sourate Yûsuf : « Pas de reproche contre vous aujourd'hui. Allah vous pardonnera, et Il est le plus Miséricordieux des miséricordieux » (12:92). Il leur avait demandé s'ils se souvenaient de ce qu'ils avaient fait à Yûsuf et à son frère dans leur ignorance (12:89), puis leur avait dit : « Je suis Yûsuf, et voici mon frère » (12:90) ; ils reconnurent : « Allah t'a préféré à nous, et nous étions des pécheurs » (12:91). Un musulman apprend que pardonner à ceux qui nous ont fait du tort, quand on a pouvoir sur eux, est la voie des prophètes.",

"prophets_183": "Yaʿqûb dit dans la sourate Yûsuf : « Ô mes fils, partez et enquérez-vous de Yûsuf et de son frère, et ne désespérez pas de la miséricorde d'Allah. Seuls les mécréants désespèrent de la miséricorde d'Allah » (12:87). À ce moment, ses yeux étaient devenus blancs de chagrin (12:84), et ses fils lui avaient dit qu'il ne cesserait de se rappeler Yûsuf jusqu'à en dépérir (12:85). Un musulman apprend que le chagrin se porte à Allah, et que l'espoir en Sa miséricorde fait partie de la foi elle-même.",

"prophets_184": "La prière dit : « Mon Seigneur, Tu m'as donné une part de souveraineté et Tu m'as appris l'interprétation des événements. Créateur des cieux et de la terre, Tu es mon protecteur en ce monde et dans l'au-delà. Fais-moi mourir soumis et fais-moi rejoindre les vertueux » (12:101). Yûsuf la prononce au sommet de son histoire, quand ses parents sont venus en Égypte et que sa famille s'est prosternée devant lui (12:100). Un musulman apprend de Yûsuf à demander une bonne fin par-dessus tout gain de ce monde.",

"prophets_185": "La sourate Sâd dit : « Rappelle-toi Notre serviteur Ayyûb, quand il appela son Seigneur : Le Diable m'a infligé détresse et souffrance » (38:41). La sourate Al-Anbiyâ donne son appel en ces mots : « Le mal m'a touché, et Tu es le plus Miséricordieux des miséricordieux » (21:83). La réponse vint aussitôt : « Frappe du pied ; voici une source fraîche pour te laver et pour boire » (38:42). Un musulman apprend d'Ayyûb comment se plaindre à Allah seul, sans un mot contre Lui.",

"prophets_186": "La sourate Sâd dit : « Nous lui rendîmes sa famille et autant qu'eux avec eux, par miséricorde de Notre part et comme rappel pour les doués d'intelligence » (38:43). Le verset suivant ajoute le témoignage d'Allah : « Nous l'avons trouvé patient. Quel excellent serviteur » (38:44). La sourate Al-Anbiyâ dit la même chose : « Nous l'exauçâmes, enlevâmes le mal qui le touchait, et lui rendîmes sa famille et autant qu'eux avec eux » (21:84). Un musulman apprend que le soulagement d'Allah après la patience vient plus grand que la perte : ce qui avait été perdu fut doublé.",

"prophets_187": "La sourate As-Sâffât dit : « S'il n'avait pas été de ceux qui glorifient Allah, il serait resté dans son ventre jusqu'au Jour où ils seront ressuscités » (37:143-144). Yûnus s'était enfui vers le navire chargé, avait tiré au sort et avait perdu (37:140-141). La sourate Al-Anbiyâ donne ses paroles dans les ténèbres : « Il n'y a de dieu que Toi ; gloire à Toi ; j'ai été du nombre des injustes » (21:87). Un musulman apprend que glorifier Allah dans les temps faciles porte un serviteur à travers les plus durs.",

"prophets_188": "La sourate Yûnus dit : « Si seulement il y avait eu une cité qui ait cru et à qui sa foi ait profité, hormis le peuple de Yûnus. Quand ils crurent, Nous écartâmes d'eux le châtiment d'ignominie dans la vie de ce monde, et Nous les laissâmes jouir pour un temps » (10:98). La sourate As-Sâffât donne leur nombre : cent mille ou davantage, « et ils crurent » (37:147-148). Un musulman apprend que le repentir avant l'arrivée du châtiment est accepté, et qu'une cité entière fut épargnée grâce à lui.",

"prophets_189": "La sourate Al-Qalam dit : « Sois patient pour le jugement de ton Seigneur, et ne sois pas comme l'homme au poisson, quand il appela, plein d'angoisse. Si une faveur de son Seigneur ne l'avait pas atteint, il aurait été rejeté sur le rivage nu, blâmé. Mais son Seigneur l'a choisi et l'a mis au nombre des vertueux » (68:48-50). La sourate s'adresse au Prophète ﷺ (68:2). Un musulman apprend que la patience est demandée à celui qui appelle à Allah.",

"prophets_190": "La sourate As-Sâffât dit : « Ilyâs était du nombre des messagers, quand il dit à son peuple : Ne craindrez-vous pas Allah ? Invoquez-vous Baʿl et délaissez-vous le meilleur des créateurs, Allah, votre Seigneur et le Seigneur de vos premiers ancêtres ? » (37:123-126). Son peuple le traita de menteur (37:127) ; puis Allah laissa pour lui une salutation parmi les générations suivantes, « Paix sur Ilyâs » (37:129-130). Un musulman apprend qu'Ilyâs appela à l'adoration du seul Créateur, et que la paix envoyée sur lui est récitée aujourd'hui.",

"prophets_191": "La sourate Al-Anbiyâ dit : « Et Ismâʿîl, Idrîs et Dhû-l-Kifl : tous étaient du nombre des endurants. Et Nous les fîmes entrer en Notre miséricorde ; ils étaient parmi les vertueux » (21:85-86). Ils sont nommés juste après Ayyûb, dont la patience dans l'affliction vient d'être racontée (21:83-84). Dhû-l-Kifl est nommé une fois encore dans la sourate Sâd, de nouveau aux côtés d'Ismâʿîl : « Rappelle-toi Ismâʿîl, Al-Yasaʿ et Dhû-l-Kifl ; tous sont parmi les meilleurs » (38:48). Un musulman apprend que le Coran ne raconte aucune histoire de lui, et que la patience seule lui valut une place dans la miséricorde d'Allah.",

"prophets_192": "La sourate Al-Baqara dit : « Et quand Nous avons fendu la mer pour vous, Nous vous avons sauvés et noyé les gens de Pharaon, tandis que vous regardiez » (2:50). Le verset appartient à un passage qui commence par « Ô Enfants d'Israël, rappelez-vous Mon bienfait dont Je vous ai comblés » (2:40). La sourate Ash-Shuʿarâ montre l'instant : « Frappe la mer de ton bâton. Elle se fendit, et chaque partie fut comme une immense montagne » (26:63). Un musulman apprend qu'Allah sauve et juge en un seul acte, et que Ses bienfaits sont à se rappeler.",

"prophets_193": "Mûsâ dit dans la sourate Al-Qasas : « Mon frère Hârûn est plus éloquent que moi en parole ; envoie-le donc avec moi comme soutien pour me confirmer ; je crains qu'ils ne me traitent de menteur » (28:34). Allah répondit : « Nous allons fortifier ton bras par ton frère et vous donner à tous deux une autorité » (28:35). Un musulman apprend que demander un aide n'est pas une faiblesse, et qu'Allah accorda à Hârûn la prophétie en réponse à la prière de son frère.",

"prophets_194": "Allah dit à Mûsâ et Hârûn dans la sourate Tâ-Hâ : « Parlez-lui avec des paroles douces, afin qu'il se rappelle ou qu'il craigne » (20:44), juste après « Allez, tous deux, vers Pharaon ; il a dépassé les limites » (20:43). Les deux répondirent : « Notre Seigneur, nous craignons qu'il ne se hâte contre nous ou qu'il ne dépasse les limites », et il leur fut dit : « Ne craignez rien ; Je suis avec vous deux, J'entends et Je vois » (20:45-46). Un musulman apprend que la douceur dans l'appel à Allah est commandée même envers l'auditeur le plus dur.",

"prophets_195": "La sourate Ghâfir dit : « Un homme croyant de la famille de Pharaon, qui cachait sa foi, dit : Tuerez-vous un homme parce qu'il dit : Mon Seigneur est Allah, alors qu'il vous a apporté des preuves claires de votre Seigneur ? » (40:28). Il parle juste après que Pharaon a dit « Laissez-moi tuer Mûsâ » (40:26), et la sourate achève son histoire : « Allah le protégea des méfaits qu'ils tramaient » (40:45). Un musulman apprend qu'un seul croyant qui dit la vérité devant un tyran est rappelé par Allah.",

"prophets_196": "La sourate Tâ-Hâ dit : « Hârûn leur avait dit auparavant : Ô mon peuple, vous n'êtes qu'éprouvés par lui. Votre Seigneur est le Tout Miséricordieux : suivez-moi donc et obéissez à mon ordre » (20:90). Le Sâmirî leur avait fait un veau, un corps qui mugissait, et ils avaient dit : « Voici votre dieu et le dieu de Mûsâ » (20:88). Un musulman apprend qu'une épreuve peut se présenter sous l'aspect d'un prodige, et que suivre le messager d'Allah, comme Hârûn le demanda, est le moyen de la traverser.",

"prophets_197": "La sourate Al-Qasas dit : « La femme de Pharaon dit : Il sera la joie de mon œil et du tien ; ne le tuez pas. Il se peut qu'il nous soit utile, ou que nous le prenions pour fils. Et ils ne se doutaient de rien » (28:9). La mère de Mûsâ avait reçu l'inspiration de le jeter dans le fleuve (28:7). Dans la sourate At-Tahrîm, la même femme prie : « Mon Seigneur, construis-moi auprès de Toi une maison au Paradis » (66:11). Un musulman apprend qu'un cœur croyant vivait dans le palais même de Pharaon.",

"prophets_198": "La sourate Al-Kahf rapporte : « Mûsâ lui dit : Puis-je te suivre, à la condition que tu m'apprennes de ce qu'on t'a appris concernant une bonne direction ? » (18:66). L'homme n'est décrit que comme « un serviteur d'entre Nos serviteurs, à qui Nous avions donné une miséricorde de Notre part et enseigné une science de Notre part » (18:65). Mûsâ promit : « Tu me trouveras, si Allah le veut, patient » (18:69). Un musulman apprend de Mûsâ, le prophète qui parla avec Allah, les bonnes manières de la quête du savoir : demander la permission, promettre la patience et se placer sous l'autorité du maître.",

"prophets_199": "La sourate Al-Aʿrâf dit : « Lorsque Mûsâ revint à son peuple, courroucé et affligé, il dit : Comme est mauvais ce que vous avez fait à ma place après moi ! Il jeta les Tables et saisit son frère par la tête » (7:150). Hârûn répondit : « Fils de ma mère, le peuple m'a dominé et a failli me tuer » (7:150), et Mûsâ pria : « Mon Seigneur, pardonne-moi ainsi qu'à mon frère » (7:151). Un musulman apprend que la colère pour Allah est réelle même chez un prophète, et qu'elle s'achève en prière.",

"prophets_200": "La sourate An-Nâziʿât dit : « Va vers Pharaon ; il a dépassé les limites. Et dis : Voudrais-tu te purifier, et que je te guide vers ton Seigneur, afin que tu Le craignes ? » (79:17-19). La sourate vient de rappeler l'appel de Mûsâ dans la vallée sacrée de Tuwâ (79:15-16). Pharaon répondit en proclamant « Je suis votre seigneur suprême » (79:24), et Allah le saisit pour en faire un exemple (79:25). Un musulman apprend que même un tyran se vit d'abord offrir purification et guidance, par une question plutôt que par une menace.",
}
