"""Français — détails, prophets_b (60 questions)."""

D = {
"prophets_091": "Le verset ouvre le récit des faveurs accordées à Dâwûd dans la sourate Saba : « Nous avons certes donné à Dâwûd une grâce venant de Nous : ô montagnes, répétez les louanges avec lui, et vous aussi les oiseaux. Et Nous lui rendîmes le fer malléable » (34:10). Le verset suivant lui dit à quoi sert ce don : « Fabrique des cottes de mailles complètes et mesure les mailles avec précision, et faites le bien ; Je vois ce que vous faites » (34:11). Un musulman apprend qu'un savoir-faire est une faveur d'Allah, à employer pour le bien et sous Son regard.",

"prophets_092": "La sourate Al-Anbiyâ' dit : « Nous lui apprîmes la fabrication des cottes de mailles pour vous, afin de vous protéger dans vos combats. Serez-vous donc reconnaissants ? » (21:80). Il suit le verset où les montagnes et les oiseaux glorifient Allah avec Dâwûd (21:79), et mène au vent soumis à Sulaymân (21:81). L'armure est un don fait au peuple qu'elle protège autant qu'à Dâwûd, et le verset se termine en leur demandant de la gratitude. Un musulman apprend à voir un savoir utile comme une faveur qui appelle la reconnaissance.",

"prophets_093": "Le verset clôt l'histoire de l'armée de Tâlût : « Ils les mirent en déroute par la permission d'Allah, et Dâwûd tua Jâlût, et Allah lui donna la royauté et la sagesse et lui enseigna ce qu'Il voulut » (2:251). Juste avant, la petite troupe avait prié : « Seigneur, déverse sur nous l'endurance, affermis nos pas et donne-nous la victoire sur le peuple mécréant » (2:250). La victoire est attribuée à la permission d'Allah, et le jeune Dâwûd reçoit à la fois le pouvoir et le savoir. Un musulman apprend que le succès vient par la permission d'Allah, non par le nombre.",

"prophets_094": "Tâlût dit en partant avec l'armée : « Allah va vous éprouver par une rivière : celui qui en boit n'est pas des miens, sauf celui qui en prend une gorgée dans le creux de la main. Mais ils en burent, sauf un petit nombre » (2:249). Il était le roi que les Enfants d'Israël avaient demandé (2:247). Le petit nombre qui tint ferme dit : « Combien de fois une petite troupe a vaincu une troupe nombreuse par la permission d'Allah » (2:249). Un musulman apprend qu'un petit acte d'obéissance montre qui tiendra ferme plus tard.",

"prophets_095": "Le verset dit : « Nous soumîmes les montagnes à glorifier avec Dâwûd, ainsi que les oiseaux ; et c'est Nous qui agissions » (21:79). Il suit le jugement de Dâwûd et de Sulaymân au sujet du champ (21:78). La sourate Sâd montre la même scène : les montagnes glorifiant avec lui le soir et au lever du soleil, et les oiseaux rassemblés, tous tournés vers lui (38:18-19). Un musulman apprend que toute la création loue Allah, et qu'un serviteur qui Le loue rejoint un chœur bien plus vaste que lui.",

"prophets_096": "Le verset dit : « Et à Sulaymân Nous soumîmes le vent impétueux, courant sur son ordre vers la terre que Nous avions bénie ; et Nous savons toute chose » (21:81). La sourate Saba en donne la mesure : « son parcours du matin était d'un mois et son parcours du soir d'un mois » (34:12), et la sourate Sâd dit que le vent soufflait doucement sur son ordre là où il le dirigeait (38:36). Un musulman apprend que même le plus grand pouvoir d'un roi est un prêt d'Allah, accordé pour un temps et sous Sa science.",

"prophets_097": "Sulaymân passa les oiseaux en revue et demanda : « Pourquoi ne vois-je pas la huppe, ou est-elle parmi les absents ? », promettant de la punir à moins qu'elle n'apporte une excuse claire (27:20-21). La huppe revint et dit : « J'ai appris une chose que tu ne sais pas, et je t'apporte de Saba une nouvelle sûre » (27:22). Elle rapporta l'existence d'une reine au trône immense, et d'un peuple qui se prosternait devant le soleil (27:23-24). Un musulman apprend que Sulaymân écouta un petit oiseau, car une nouvelle vraie compte, quel que soit celui qui la porte.",

"prophets_098": "Le verset dit : « Quand ils arrivèrent à la vallée des fourmis, une fourmi dit : Ô fourmis, entrez dans vos demeures, que Sulaymân et ses troupes ne vous écrasent pas sans s'en apercevoir » (27:18). Sulaymân la comprit : « Il sourit, riant de ses paroles, et dit : Seigneur, permets-moi d'être reconnaissant pour Ta faveur envers moi et envers mes parents, et de faire le bien que Tu agrées » (27:19). Un musulman apprend qu'un moment d'émerveillement devant la création d'Allah doit se changer aussitôt en gratitude.",

"prophets_099": "Sulaymân demanda à son assemblée : « Lequel de vous m'apportera son trône avant qu'ils ne viennent à moi soumis ? » (27:38). Alors « celui qui avait une science du Livre dit : Je te l'apporterai avant que ton regard ne revienne à toi. Quand il le vit placé devant lui, il dit : Ceci est une faveur de mon Seigneur, pour m'éprouver : serai-je reconnaissant ou ingrat » (27:40). Un musulman apprend qu'un grand don est une épreuve à laquelle on répond par la gratitude.",

"prophets_100": "Les djinns travaillaient pour Sulaymân par la permission de son Seigneur (34:12) : « Ils lui faisaient ce qu'il voulait : sanctuaires, statues, bassins comme des réservoirs et marmites fixes. Œuvrez, famille de Dâwûd, en gratitude ; et peu de Mes serviteurs sont reconnaissants » (34:13). Le même passage avertit que tout djinn qui se détournerait de l'ordre d'Allah goûterait au châtiment de la Fournaise (34:12). Un musulman apprend que l'abondance est un appel à la gratitude, et que peu y répondent.",

"prophets_101": "Le verset dit : « Quand Nous décrétâmes sa mort, rien ne leur indiqua sa mort, sinon une bête de la terre qui rongeait son bâton. Quand il tomba, il devint clair pour les djinns que s'ils avaient connu l'invisible, ils ne seraient pas restés dans un châtiment humiliant » (34:14). Les djinns bâtissaient et plongeaient pour lui sous ses ordres (34:12-13), et ils continuèrent à travailler tant qu'il resta debout. Un musulman apprend que l'invisible appartient à Allah seul, et que nul autre, djinn ou humain, ne peut le voir.",

"prophets_102": "La prière dit : « Il dit : Seigneur, pardonne-moi et accorde-moi un royaume tel que nul après moi n'en aura de pareil ; c'est Toi le Grand Donateur » (38:35). Le verset vient juste après que le Coran dit que Sulaymân fut éprouvé puis revint à son Seigneur (38:34). Allah répondit en lui soumettant le vent et les démons, bâtisseurs et plongeurs (38:36-37), et dit : « Voilà Notre don, accorde ou retiens sans avoir à rendre compte » (38:39). Un musulman remarque que Sulaymân demanda le pardon avant toute autre chose.",

"prophets_103": "Ayyûb appela son Seigneur : « Satan m'a touché par la peine et le tourment » (38:41). La réponse vint : « Frappe le sol de ton pied : voici une eau fraîche pour te laver et pour boire » (38:42). Allah lui rendit ensuite sa famille et autant avec elle, comme miséricorde et rappel (38:43), et dit : « Nous l'avons trouvé endurant ; quel excellent serviteur, toujours tourné vers Nous » (38:44). Un musulman apprend qu'Ayyûb se tourna vers Allah seul dans sa maladie, et que le soulagement vint par un acte d'obéissance.",

"prophets_104": "Le verset dit : « Et l'homme au poisson, quand il partit en colère ; puis il appela dans les ténèbres : Nulle divinité à part Toi, gloire à Toi, j'ai été du nombre des injustes » (21:87). Le verset suivant répond : « Nous l'exauçâmes et le sauvâmes de l'angoisse ; et c'est ainsi que Nous sauvons les croyants » (21:88). Un musulman apprend cet appel pour sa propre détresse, car le Coran promet que c'est ainsi qu'Allah sauve les croyants.",

"prophets_105": "La sourate As-Sâffât raconte l'histoire : Yûnus s'enfuit vers le navire chargé, tira au sort et perdit, et le poisson l'avala alors qu'il était blâmable (37:140-142). « S'il n'avait pas été de ceux qui glorifient Allah, il serait resté dans son ventre jusqu'au Jour où ils seront ressuscités » (37:143-144). « Nous le rejetâmes sur le rivage nu, alors qu'il était malade » (37:145), « et Nous fîmes pousser au-dessus de lui un plant de courge » (37:146). Un musulman apprend que la sollicitude d'Allah continue après le pardon, jusqu'à l'ombre au-dessus de la tête d'un homme malade.",

"prophets_106": "Le verset dit : « Nous l'envoyâmes vers cent mille, ou davantage, et ils crurent ; Nous leur accordâmes donc la jouissance pour un temps » (37:147-148). Il clôt l'histoire de Yûnus (37:139-146). La sourate Yûnus les rappelle : la foi d'aucune cité ne lui profita quand vint le châtiment, sauf le peuple de Yûnus, dont Allah écarta le châtiment de l'ignominie quand ils crurent (10:98). Un musulman apprend qu'un peuple entier peut revenir ensemble à Allah, et que Sa miséricorde les accueille quand ils le font.",

"prophets_107": "Zakariyyâ avait demandé comment il pouvait avoir un fils dans sa vieillesse, et il lui fut dit : « Cela M'est facile » (19:8-9). Il demanda alors un signe : « Ton signe sera que tu ne parleras pas aux gens pendant trois nuits, tout en étant sain » (19:10). Il sortit ensuite vers son peuple et leur fit signe de glorifier Allah matin et soir (19:11). Un musulman apprend que son signe fut le silence, et que même sans parole il continua d'appeler les autres à la louange.",

"prophets_108": "La bonne nouvelle dit : « Ô Zakariyyâ, Nous t'annonçons un garçon dont le nom sera Yahyâ ; Nous n'avons donné ce nom à personne auparavant » (19:7). Elle répond à la prière discrète du début de la sourate, où Zakariyyâ dit que ses os s'étaient affaiblis et que sa tête avait blanchi de vieillesse, et demanda un héritier qui plaise à Allah (19:3-6). Allah choisit le nom avant que l'enfant ne soit né. Un musulman apprend qu'Allah répond à une prière secrète plus complètement que ce qui fut demandé.",

"prophets_109": "Le verset dit : « Ô Yahyâ, prends le Livre avec force. Et Nous lui donnâmes la sagesse dès l'enfance » (19:12). Les versets suivants le décrivent : tendresse venue d'Allah et pureté, crainte d'Allah, bonté envers ses parents, ni tyran ni désobéissant, et « paix sur lui le jour où il naquit, le jour où il mourra et le jour où il sera ressuscité vivant » (19:13-15). La sagesse dans l'enfance vint avec la bonté envers les parents. Un musulman apprend que la vraie compréhension se montre dans le bon caractère, quel que soit l'âge.",

"prophets_110": "Le verset dit : « Quand la femme de 'Imrân dit : Seigneur, je T'ai voué ce qui est dans mon ventre, consacré à Ton service, accepte-le donc de moi ; Tu es Celui qui entend, Celui qui sait » (3:35). Quand elle accoucha, elle dit : « Seigneur, j'ai mis au monde une fille », la nomma Maryam, et demanda à Allah de la protéger, elle et sa descendance, contre Satan (3:36). Un musulman apprend de cette mère qu'un enfant peut être offert à Allah avant sa naissance, et qu'Allah accepte.",

"prophets_111": "« Son Seigneur l'accueillit d'un bel accueil et la confia à Zakariyyâ. Chaque fois que Zakariyyâ entrait auprès d'elle dans le sanctuaire, il trouvait auprès d'elle une subsistance. Il dit : Ô Maryam, d'où cela te vient-il ? Elle dit : Cela vient d'Allah ; Allah pourvoit à qui Il veut sans compter » (3:37). Le verset suivant dit que Zakariyyâ appela alors son Seigneur pour une bonne descendance (3:38). Un musulman apprend que voir la subsistance qu'Allah accorde à un autre poussa un prophète à demander, avec espoir, la sienne.",

"prophets_112": "Le verset dit : « Quand les anges dirent : Ô Maryam, Allah t'a élue et purifiée, et Il t'a choisie au-dessus des femmes des mondes » (3:42). Les anges lui dirent ensuite quoi faire de ce rang : « Ô Maryam, sois dévouée à ton Seigneur, prosterne-toi et incline-toi avec ceux qui s'inclinent » (3:43). Le Coran appelle cela des nouvelles de l'invisible révélées au Prophète ﷺ (3:44). Un musulman apprend qu'être choisi par Allah conduit à plus d'adoration, non à moins.",

"prophets_113": "« Les douleurs de l'enfantement la poussèrent vers le tronc d'un palmier ; elle dit : Que ne suis-je morte avant cela, et tombée dans l'oubli » (19:23). Une voix l'appela d'en dessous d'elle : « Ne t'attriste pas ; ton Seigneur a placé sous toi un ruisseau » (19:24), « et secoue vers toi le tronc du palmier : il fera tomber sur toi des dattes fraîches et mûres » (19:25). Un musulman apprend que la subsistance d'Allah demande souvent un petit effort, et que le réconfort vient à l'heure la plus dure.",

"prophets_114": "Le verset dit : « Le Messie, fils de Maryam, n'était qu'un messager ; des messagers sont passés avant lui. Sa mère était une véridique. Tous deux mangeaient de la nourriture » (5:75). Il répond à ceux qui, dans le même passage, disaient qu'Allah est le Messie, ou l'un de trois (5:72-73). Le même mot de véridique est donné à Yûsuf, appelé en prison « Ô Yûsuf, le véridique » (12:46). Un musulman apprend à honorer Maryam hautement et à n'adorer qu'Allah seul.",

"prophets_115": "Les anges dirent : « Ô Maryam, Allah t'annonce une parole venant de Lui, dont le nom sera le Messie, Îsâ fils de Maryam, illustre ici-bas et dans l'au-delà » (3:45). Quand elle demanda comment elle pourrait avoir un enfant sans qu'aucun homme ne l'ait touchée, il lui fut dit : « Ainsi Allah crée ce qu'Il veut ; quand Il décrète une chose, Il lui dit seulement : Sois, et elle est » (3:47). Un musulman apprend les noms et le rang d'Îsâ par les paroles mêmes des anges.",

"prophets_116": "Îsâ dit aux Enfants d'Israël : « Je viens à vous avec un signe de votre Seigneur : je façonne pour vous, avec de l'argile, la forme d'un oiseau, puis je souffle dedans et il devient oiseau par la permission d'Allah ; je rends la vie aux morts par la permission d'Allah » (3:49). Deux fois dans un seul verset apparaissent les mots « par la permission d'Allah », et la sourate Al-Mâ'ida les répète (5:110). Un musulman apprend que chaque miracle d'un prophète est l'acte d'Allah, et que le prophète est Son serviteur.",

"prophets_117": "Le verset dit : « Quand Îsâ sentit leur mécréance, il dit : Qui sont mes soutiens pour Allah ? Les apôtres dirent : Nous sommes les soutiens d'Allah ; nous croyons en Allah, et sois témoin que nous sommes musulmans » (3:52). Ils demandèrent à être inscrits parmi les témoins (3:53). La sourate As-Saff appelle les croyants à être les soutiens d'Allah comme le furent les apôtres quand Îsâ le leur demanda (61:14). Un musulman apprend que répondre à l'appel d'un prophète, c'est se tenir à ses côtés quand les autres se détournent.",

"prophets_118": "Les apôtres demandèrent à Îsâ si son Seigneur pouvait faire descendre sur eux une table servie venue du ciel, et il répondit : « Craignez Allah, si vous êtes croyants » (5:112). Îsâ pria : « Ô Allah, notre Seigneur, fais descendre sur nous une table du ciel, qui soit une fête pour le premier d'entre nous et le dernier, et un signe de Ta part » (5:114). Allah promit de la faire descendre, en avertissant quiconque mécroirait après cela (5:115). Un musulman apprend qu'un signe accordé est un dépôt, non un spectacle.",

"prophets_119": "Les versets répondent à une prétention : « Et à cause de leur parole : Nous avons tué le Messie, Îsâ fils de Maryam, le messager d'Allah. Ils ne l'ont pas tué, ni crucifié, mais cela leur est apparu ainsi. Ils ne l'ont certainement pas tué. Allah l'a plutôt élevé vers Lui » (4:157-158). Le passage énumère des torts antérieurs du même peuple, dont une grave calomnie contre Maryam (4:156). Un musulman apprend à dire de la fin d'Îsâ ce que dit le Coran : ni tué, ni crucifié, élevé par Allah.",

"prophets_120": "Îsâ dit : « Ô Enfants d'Israël, je suis le messager d'Allah envoyé vers vous, confirmant la Torah venue avant moi et annonçant un messager à venir après moi, dont le nom sera Ahmad » (61:6). Le verset précédent rapporte Mûsâ demandant à son peuple pourquoi ils lui faisaient du mal alors qu'ils savaient qu'il était le messager d'Allah (61:5). Chaque messager confirme celui d'avant et annonce celui d'après. Un musulman apprend qu'Ahmad est un nom du Prophète ﷺ, annoncé par Îsâ bien avant sa naissance.",

"prophets_121": "La sourate As-Sâffât dit : « Ilyâs était parmi les messagers. Quand il dit à son peuple : Ne craindrez-vous pas Allah ? » (37:123-124), « Invoquez-vous Ba'l, et délaissez-vous le Meilleur des créateurs, Allah, votre Seigneur et le Seigneur de vos premiers ancêtres ? » (37:125-126). Ils le traitèrent de menteur, et seront amenés pour le jugement, sauf les serviteurs élus d'Allah (37:127-128). Allah lui laissa un bon renom parmi les générations suivantes : « Paix sur Ilyâsîn » (37:129-130). Un musulman apprend que tout l'argument d'un prophète est que seul le Créateur mérite d'être invoqué.",

"prophets_122": "Le verset dit : « Et Ismâ'îl, Idrîs et Dhul-Kifl : tous étaient parmi les endurants. Nous les fîmes entrer dans Notre miséricorde ; ils étaient parmi les vertueux » (21:85-86). La sourate Al-Anbiyâ' passe d'un prophète au suivant : juste avant vient Ayyûb, dont Allah écarta le mal (21:83-84), et juste après vient Yûnus appelant dans les ténèbres (21:87). Un musulman apprend que l'endurance est le trait par lequel le Coran choisit de se souvenir de ces trois prophètes, et que l'endurance mène à la miséricorde d'Allah.",

"prophets_123": "Le verset dit : « Et rappelle-toi Ismâ'îl, Al-Yasa' et Dhul-Kifl : tous parmi les meilleurs » (38:48). Il suit la mention d'Ibrâhîm, d'Ishâq et de Ya'qûb, hommes de force et de clairvoyance qu'Allah choisit pour une qualité particulière, le rappel de l'au-delà (38:45-47). Al-Yasa' est nommé une fois encore dans la sourate Al-An'âm, aux côtés d'Ismâ'îl, de Yûnus et de Lût, parmi ceux qu'Allah a préférés aux mondes (6:86). Le Coran ne lui donne aucune histoire, seulement un rang. Un musulman apprend à honorer chaque prophète que le Coran nomme, même sans histoire.",

"prophets_124": "Le verset dit : « Muhammad n'est le père d'aucun de vos hommes, mais il est le Messager d'Allah et le Sceau des prophètes ; et Allah sait toute chose » (33:40). Il clôt le passage sur Zayd, que le Prophète ﷺ avait élevé comme un fils (33:37), après que la sourate a établi que les fils adoptifs ne sont pas de vrais fils (33:4-5). Un sceau vient en dernier et clôt ce qui précède. Un musulman apprend de ce verset qu'aucun prophète ne vient après Muhammad ﷺ, et que son message est le dernier.",

"prophets_125": "Le verset dit : « Nous ne t'avons envoyé qu'en miséricorde pour les mondes » (21:107). Il se trouve vers la fin de la sourate Al-Anbiyâ', qui a raconté de nombreux prophètes, et le verset suivant donne le cœur de son message : « Dis : Il m'est seulement révélé que votre Dieu est un Dieu unique ; vous soumettrez-vous donc ? » (21:108). La miséricorde n'est pas pour un seul peuple ni un seul temps, mais pour les mondes. Un musulman apprend que le suivre ﷺ est destiné à porter la miséricorde à tous ceux que son message atteint.",

"prophets_126": "Le verset dit : « Allah et Ses anges prient sur le Prophète. Ô vous qui croyez, priez sur lui et saluez-le d'un salut de paix » (33:56). Il suit une description du Prophète ﷺ comme témoin, annonciateur de bonne nouvelle, avertisseur, appelant vers Allah et lampe éclairante (33:45-46). Il est demandé aux croyants de faire sur terre ce qu'Allah et Ses anges font au-dessus. Un musulman en tire l'habitude d'appeler la bénédiction sur lui chaque fois que son nom est mentionné.",

"prophets_127": "Le verset dit : « Et tu es certes d'une moralité éminente » (68:4). Il vient à l'ouverture de la sourate Al-Qalam, après qu'Allah a juré par la plume et par ce qu'ils écrivent que le Prophète ﷺ n'est pas fou, par la grâce de son Seigneur, et que sa récompense est sans fin (68:1-3). La sourate Al-Ahzâb ajoute que dans le Messager d'Allah il y a un excellent modèle pour ceux qui espèrent en Allah (33:21). Un musulman apprend que la conduite du Prophète ﷺ est elle-même une preuve de sa véracité, et un modèle à suivre.",

"prophets_128": "Le verset dit : « Muhammad n'est qu'un messager ; des messagers sont passés avant lui. S'il meurt ou s'il est tué, retournerez-vous sur vos talons ? Quiconque retourne en arrière ne nuira en rien à Allah, et Allah récompensera les reconnaissants » (3:144). Il appartient aux versets sur la bataille dans laquelle les croyants furent blessés (3:140). Un musulman apprend que la foi repose sur Allah, qui ne meurt jamais, et qu'aimer le Prophète ﷺ, c'est tenir à son message.",

"prophets_129": "Le verset dit : « Quand Nous prîmes des prophètes leur engagement, ainsi que de toi, de Nûh, d'Ibrâhîm, de Mûsâ et d'Îsâ fils de Maryam ; et Nous prîmes d'eux un engagement solennel » (33:7). Son but suit : « afin qu'Il interroge les véridiques sur leur véracité » (33:8). La sourate Ash-Shûrâ nomme les mêmes cinq : la religion prescrite à Nûh, Ibrâhîm, Mûsâ et Îsâ est celle révélée au Prophète ﷺ (42:13). Un musulman apprend que ces messagers ont porté un seul engagement et une seule religion.",

"prophets_130": "Abû Hurayra rapporte dans Sahîh al-Bukhârî 2262 que le Prophète ﷺ dit qu'Allah n'a envoyé aucun prophète qui n'ait gardé les moutons ; quand on lui demanda si lui aussi l'avait fait, il dit qu'il les avait gardés pour les Mecquois contre un petit salaire. Le Coran montre Mûsâ dans le même travail : son bâton abattait des feuilles pour ses moutons (20:18), et il abreuva le troupeau des deux femmes de Madyan (28:23-24). Un musulman apprend que les prophètes gagnaient leur vie de leurs mains, et qu'aucun travail honnête n'est indigne de personne.",

"prophets_131": "Le hadith est rapporté par Abû Hurayra dans Sahîh Muslim 2379 : le Messager d'Allah ﷺ dit que Zakariyyâ était charpentier. Le Coran montre le même prophète dans le sanctuaire, prenant soin de Maryam et demandant d'où venait sa subsistance (3:37), et appelant son Seigneur pour un fils dans sa vieillesse (19:3-6). Le hadith ajoute qu'entre ces moments il travaillait le bois pour gagner son pain. Un musulman apprend que la prophétie et un humble métier allaient de pair, et que travailler de ses mains ne porte aucune honte.",

"prophets_132": "Le hadith est rapporté par Abû Hurayra dans Sahîh al-Bukhârî 3442. Le Prophète ﷺ dit qu'ici-bas et dans l'au-delà il est le plus proche de tous les gens d'Îsâ fils de Maryam, que les prophètes sont des frères d'un même père, que leurs mères diffèrent, et que leur religion est une. Le Coran rapporte Îsâ annonçant après lui un messager nommé Ahmad (61:6), et il ne nomme aucun prophète entre eux. Un musulman apprend à aimer Îsâ comme le Prophète ﷺ l'aimait, et à voir tous les prophètes comme une seule famille.",

"prophets_133": "Six sourates portent le nom d'un prophète, comme le montre la liste des noms des sourates : Yûnus (10), Hûd (11), Yûsuf (12), Ibrâhîm (14), Muhammad (47) et Nûh (71). La sourate Yûsuf raconte son histoire et l'appelle le meilleur des récits (12:3) ; la sourate Nûh est entièrement consacrée à son appel à son peuple ; la sourate Ibrâhîm contient sa prière pour La Mecque et sa descendance (14:35-41) ; la sourate Muhammad le nomme dans son deuxième verset (47:2). La sourate Al-Anbiyâ' porte le nom de tous les prophètes ensemble. Un musulman apprend à se repérer dans le Coran grâce à ces noms.",

"prophets_134": "Le verset dit : « Ibrâhîm était certes indulgent, plein de compassion et sans cesse tourné vers Allah » (11:75). Quand la crainte eut quitté Ibrâhîm et que la bonne nouvelle lui fut parvenue, il se mit à plaider auprès d'Allah pour le peuple de Lût (11:74), jusqu'à ce qu'il lui soit dit : « Ô Ibrâhîm, laisse cela ; l'ordre de ton Seigneur est venu, et un châtiment qui ne peut être repoussé va les atteindre » (11:76). Un musulman apprend qu'un cœur tendre plaide même pour les égarés, tout en s'inclinant devant le décret d'Allah.",

"prophets_135": "Shu'ayb dit au peuple de Madyan : « Ô mon peuple, adorez Allah ; vous n'avez d'autre divinité que Lui. Une preuve claire vous est venue de votre Seigneur ; donnez donc la pleine mesure et le poids exact, ne lésez pas les gens dans leurs biens, et ne semez pas la corruption sur la terre après qu'elle a été réformée » (7:85). La sourate Ash-Shu'arâ' rapporte le même appel à peser avec une balance droite (26:181-182). Un musulman apprend que l'honnêteté dans le commerce fait partie de l'adoration, et n'en est pas séparée.",

"prophets_136": "Le verset dit : « Le tremblement de terre les saisit, et ils gisaient sans vie dans leurs demeures. Ceux qui avaient traité Shu'ayb de menteur furent comme s'ils n'y avaient jamais vécu » (7:91-92). Les chefs avaient menacé de l'expulser, lui et les croyants (7:88). Shu'ayb se détourna alors : « Ô mon peuple, je vous ai transmis les messages de mon Seigneur et je vous ai conseillés ; comment m'affligerais-je pour un peuple mécréant ? » (7:93). Un musulman apprend qu'un avertisseur qui a transmis son message est dégagé de ce qui suit.",

"prophets_137": "Des hôtes vinrent à Ibrâhîm avec une bonne nouvelle et le saluèrent de paix, et il apporta un veau rôti (11:69). « Quand il vit que leurs mains ne s'en approchaient pas, il les trouva étranges et ressentit de la crainte à leur égard. Ils dirent : N'aie pas peur ; nous sommes envoyés vers le peuple de Lût » (11:70). Sa femme rit, et reçut la bonne nouvelle d'Ishâq et, après Ishâq, de Ya'qûb (11:71). Un musulman apprend que la mission des anges portait à la fois la miséricorde pour une maison et la justice pour une autre.",

"prophets_138": "Le verset dit : « Seigneur, fais de moi quelqu'un qui accomplit la prière, ainsi que de ma descendance ; notre Seigneur, et accepte mon invocation » (14:40). Il appartient à la longue prière qu'Ibrâhîm fit après avoir installé sa famille près de la Maison sacrée : il demanda une cité sûre et la protection contre les idoles (14:35), et dit qu'il avait placé sa descendance dans une vallée sans cultures afin qu'ils accomplissent la prière (14:37). Un musulman apprend à demander la prière non seulement pour lui-même, mais pour ses enfants après lui.",

"prophets_139": "Le verset dit : « Il éleva ses parents sur le trône, et ils tombèrent prosternés devant lui. Il dit : Ô mon père, voilà l'interprétation de mon rêve d'autrefois ; mon Seigneur l'a réalisé. Il a été bon envers moi quand Il m'a fait sortir de prison » (12:100). Le rêve était celui des onze étoiles, du soleil et de la lune que Yûsuf, enfant, avait vus se prosterner devant lui (12:4). Un musulman apprend que Yûsuf, au sommet de son honneur, en attribua le mérite à Allah.",

"prophets_140": "Les frères dirent : « Yûsuf et son frère sont plus chers à notre père que nous, alors que nous sommes un groupe ; notre père est dans un égarement évident. Tuez Yûsuf ou jetez-le dans quelque terre lointaine, pour que le visage de votre père soit à vous seuls, et qu'après cela vous soyez des gens vertueux » (12:8-9). L'un d'eux dit : « Ne tuez pas Yûsuf, mais jetez-le au fond du puits ; des voyageurs le recueilleront » (12:10). Un musulman apprend comment la jalousie se persuade du mal en promettant le repentir pour plus tard.",

"prophets_141": "Les frères vinrent à leur père le soir en pleurant, disant qu'un loup avait dévoré Yûsuf pendant qu'ils faisaient la course (12:16-17). « Ils apportèrent sa chemise tachée d'un faux sang. Il dit : Vos âmes vous ont plutôt suggéré quelque chose ; patience, belle patience, et c'est Allah dont on implore le secours » (12:18). La chemise revient deux fois : déchirée par-derrière, prouvant l'innocence de Yûsuf (12:26-28), et posée sur le visage de Ya'qûb, lui rendant la vue (12:93, 12:96). Un musulman apprend de Ya'qûb à répondre au mensonge par la patience et à chercher le secours d'Allah.",

"prophets_142": "« Nous inspirâmes à la mère de Mûsâ : quand tu craindras pour lui, jette-le dans le fleuve, et ne crains pas et ne t'attriste pas ; Nous te le rendrons et ferons de lui un messager » (28:7). La famille de Pharaon le recueillit (28:8). Allah lui fit refuser toute nourrice jusqu'à ce que sa sœur les conduise à sa mère, « afin qu'elle sache que la promesse d'Allah est vraie » (28:12-13). Un musulman apprend que la promesse d'Allah est tenue, même à travers un fleuve et un palais.",

"prophets_143": "Le verset dit : « Nous inspirâmes à Mûsâ : Frappe la mer de ton bâton. Elle se fendit, et chaque pan fut comme une immense montagne » (26:63). Juste avant, quand les deux groupes se virent, les compagnons de Mûsâ s'écrièrent qu'ils allaient être rejoints, et il répondit : « Non ; mon Seigneur est avec moi, Il me guidera » (26:62). Allah sauva ensuite Mûsâ et tous ceux qui étaient avec lui, et noya les autres (26:65-66). Un musulman apprend que la certitude de Mûsâ vint avant que la mer ne s'ouvre, non après.",

"prophets_144": "Mûsâ s'était dirigé vers un feu et avait entendu un appel : ôte tes sandales, tu es dans la vallée sacrée de Tuwâ, écoute ce qui est révélé (20:11-13). Ce qui fut révélé vint aussitôt : « Je suis Allah ; il n'y a de divinité que Moi, adore-Moi donc et accomplis la prière pour te souvenir de Moi » (20:14). Le verset suivant lui dit que l'Heure vient sûrement (20:15). Un musulman apprend que le premier message d'Allah à un prophète fut Son unicité, l'adoration et la prière.",

"prophets_145": "L'ordre dit : « Allez tous deux vers Pharaon ; il a dépassé les limites. Parlez-lui avec douceur, afin qu'il se rappelle ou qu'il craigne » (20:43-44). Les deux dirent qu'ils craignaient que Pharaon ne se hâte de leur faire du mal, et Allah répondit : « Ne craignez pas ; Je suis avec vous deux, J'entends et Je vois » (20:45-46). La douceur fut ordonnée envers l'homme que le Coran appelle un transgresseur. Un musulman apprend qu'un message ferme doit être transmis d'une voix douce.",

"prophets_146": "Le verset dit : « Quand Mûsâ dit à son jeune serviteur : Je ne cesserai pas avant d'atteindre le confluent des deux mers, dussé-je marcher pendant des années » (18:60). Quand ils y parvinrent, ils oublièrent leur poisson (18:61) ; quand Mûsâ demanda plus tard leur repas, le jeune homme s'en souvint, et Mûsâ dit : « C'est ce que nous cherchions », et ils revinrent sur leurs pas (18:62-64). Là ils trouvèrent un serviteur à qui Allah avait donné miséricorde et science (18:65). Un musulman apprend que chercher la science vaut un long voyage fatigant.",

"prophets_147": "Le serviteur perça le bateau sur lequel ils étaient montés, et Mûsâ demanda : « L'as-tu percé pour noyer ses passagers ? » (18:71). Puis il tua un jeune garçon (18:74). Puis il redressa un mur qui menaçait de s'écrouler, et Mûsâ dit qu'il aurait pu en demander un salaire (18:77). Le serviteur expliqua chaque acte : un roi s'emparait de tout bateau en bon état, les parents du garçon étaient croyants, et le mur cachait un trésor pour deux orphelins ; « je ne l'ai pas fait de mon propre chef » (18:82). Un musulman apprend que ce qui ressemble à un mal peut cacher la miséricorde d'Allah.",

"prophets_148": "Maryam apporta l'enfant à son peuple, qui lui fit des reproches (19:27-28). Elle désigna le bébé, et ils demandèrent comment ils pouvaient parler à un enfant au berceau (19:29). « Il dit : Je suis le serviteur d'Allah ; Il m'a donné le Livre et a fait de moi un prophète » (19:30). Il poursuivit : Allah l'avait rendu béni où qu'il soit, lui avait prescrit la prière et la zakât, et l'avait rendu bon envers sa mère (19:31-32). Un musulman apprend que le premier mot d'Îsâ sur lui-même fut « serviteur ».",

"prophets_149": "Allah avait interdit à Âdam et à son épouse un seul arbre, et Satan leur chuchota (7:19-21). Quand ils en goûtèrent, leur nudité leur apparut, et leur Seigneur demanda : « Ne vous avais-Je pas interdit cet arbre et dit que Satan est pour vous un ennemi déclaré ? » (7:22). Ils répondirent : « Seigneur, nous nous sommes fait du tort à nous-mêmes ; si Tu ne nous pardonnes pas et ne nous fais pas miséricorde, nous serons certainement du nombre des perdants » (7:23). Un musulman apprend les mots à dire après une faute.",

"prophets_150": "La sourate s'ouvre ainsi : « Nous avons envoyé Nûh vers son peuple : avertis ton peuple avant que ne leur vienne un châtiment douloureux » (71:1). Nûh leur dit qu'il était un avertisseur clair et les appela à adorer Allah, à Le craindre et à lui obéir (71:2-3). Il dit à son Seigneur qu'il les avait appelés nuit et jour et qu'ils n'avaient fait que fuir, mettant leurs doigts dans leurs oreilles (71:5-7). Il leur promit la pluie, les biens et les enfants s'ils demandaient pardon (71:10-12). Un musulman apprend qu'un avertissement est un acte de miséricorde, donné avant le châtiment.",
}
