"""Français — détails, sira_a (60 questions)."""

D = {
"sira_031": "La sourate s'ouvre ainsi : « Pour le pacte de Quraysh, leur pacte concernant le voyage d'hiver et d'été » (106:1-2), puis elle appelle la tribu : « Qu'ils adorent donc le Seigneur de cette Maison, qui les a nourris contre la faim et mis à l'abri de la peur » (106:3-4). Quraysh vivait auprès de la Ka'ba et commerçait en deux voyages annuels, et le Coran lui rappelle que les deux viennent d'Allah. Un musulman apprend que le Prophète ﷺ fut envoyé d'abord à sa propre tribu, et que l'honneur s'accompagne d'un devoir d'adoration.",

"sira_032": "Toute biographie classique rapporte la généalogie ainsi : Muhammad, fils de 'Abdullâh, fils de 'Abd al-Muttalib, fils de Hâshim, et le clan tire son nom de Hâshim. Les Banû Hâshim étaient l'un des clans de Quraysh établis autour de la Ka'ba, et leur chef, Abû Tâlib, protégea son neveu pendant les années mecquoises. Lorsque Quraysh boycotta les musulmans, tous les Banû Hâshim furent exclus avec lui. Un musulman apprend que le Prophète ﷺ grandit au sein d'un clan qui le protégea avant de croire en lui.",

"sira_033": "Halîma venait des Banû Sa'd, et toute biographie classique rapporte comment elle arriva à La Mecque avec les femmes de sa tribu en quête de nourrissons à allaiter, prit l'orphelin dont le père était mort et l'emmena au désert, où les familles mecquoises envoyaient leurs enfants pour l'air pur et l'arabe sans mélange. Les biographies rapportent que les troupeaux de sa maison prospérèrent tant qu'il fut chez eux, et qu'elle le garda au-delà du terme habituel avant de le rendre à sa mère Âmina. Un musulman apprend que les premières années du Prophète ﷺ se passèrent simplement, parmi des gens ordinaires.",

"sira_034": "Hamza était le fils de 'Abd al-Muttalib et donc l'oncle du Prophète ﷺ, bien que proche de lui par l'âge ; les biographies rapportent que tous deux furent allaités par la même femme, Thuwayba. Il embrassa l'islam à La Mecque après avoir tenu tête à Abû Jahl, qui avait insulté son neveu, et à Badr il combattit dans le duel qui ouvrit la bataille. À Uhud, il fut tué par Wahshî, un esclave abyssin qui embrassa plus tard l'islam et raconta lui-même l'histoire. Un musulman se souvient de Hamza comme d'un homme qui défendit le Prophète ﷺ avant de croire et donna sa vie après avoir cru.",

"sira_035": "Les biographies rapportent qu'Abû Tâlib avait beaucoup d'enfants et peu de moyens, si bien que le Prophète ﷺ prit son jeune cousin 'Alî dans sa propre maison pour alléger la charge de son oncle. 'Alî était un enfant quand vint la révélation et embrassa l'islam parmi les tout premiers ; il épousa Fâtima, dormit dans le lit du Prophète ﷺ la nuit de l'Hégire et porta l'étendard à Khaybar. Après 'Uthmân, il reçut le serment d'allégeance à Médine. Un musulman apprend que pour 'Alî, la proximité avec le Prophète ﷺ fut à la fois affaire d'éducation et de foi.",

"sira_036": "Toute biographie classique rapporte que le jour de la mort du Prophète ﷺ, les compagnons se réunirent au lieu de réunion des Banû Sâ'ida à Médine et prêtèrent serment d'allégeance à Abû Bakr, 'Umar étant le premier à lui prendre la main. Pendant sa dernière maladie, le Prophète ﷺ avait ordonné à Abû Bakr de diriger la prière à sa place, ce que les compagnons prirent comme un signe de son rang. Le Coran parle de lui, sans le nommer, comme du second de deux dans la grotte (9:40). Un musulman apprend que la direction de la communauté après le Prophète ﷺ revint à l'homme le plus proche de lui dans la foi et dans l'épreuve.",

"sira_037": "Les biographies lient ce titre au matin qui suivit le Voyage nocturne, quand le Prophète ﷺ dit aux Mecquois qu'il était allé à Jérusalem et revenu en une seule nuit. Quraysh courut chez Abû Bakr en s'attendant à le voir douter, et il répondit que si le Prophète ﷺ l'avait dit, c'était vrai, puisqu'il le croyait déjà chaque matin et chaque soir au sujet de nouvelles venues du ciel. Le Coran parle de lui comme du second de deux dans la grotte, à qui il fut dit de ne pas s'affliger (9:40). Un musulman apprend que croire le Prophète ﷺ sans hésiter est en soi une marque d'honneur.",

"sira_038": "Les biographies rapportent que lorsque 'Umar embrassa l'islam à La Mecque, les musulmans, qui priaient en se cachant, sortirent et prièrent ouvertement à la Ka'ba, et que de là vint son titre : par lui, la vérité fut séparée du mensonge au grand jour. Le Sahîh al-Bukhârî rapporte que les compagnons disaient être forts depuis que 'Umar avait embrassé l'islam. Il devint plus tard le deuxième calife, désigné par Abû Bakr avant sa mort. Un musulman apprend que le courage de montrer la vérité ouvertement est un don dont les autres tirent leur force.",

"sira_039": "Les biographies rapportent que 'Uthmân émigra avec Ruqayya en Abyssinie pendant la persécution de La Mecque, puis à Médine. Quand les musulmans marchèrent vers Badr, elle était malade, et le Prophète ﷺ lui dit de rester pour la soigner ; elle mourut pendant que l'armée était au loin, et le Prophète ﷺ le compta tout de même parmi les hommes de Badr. Il épousa ensuite sa sœur Umm Kulthûm, qui mourut elle aussi de son vivant. Un musulman apprend que l'honneur de 'Uthmân lui vint de sa proximité avec la maison du Prophète ﷺ.",

"sira_040": "Toute biographie classique rapporte comment chaque calife en vint à diriger. Abû Bakr reçut le serment d'allégeance le jour de la mort du Prophète ﷺ et, avant sa propre mort, désigna 'Umar pour lui succéder ; 'Umar, mortellement blessé, confia le choix à un conseil de six compagnons, qui choisirent 'Uthmân ; après que 'Uthmân fut tué à Médine, ses habitants prêtèrent serment à 'Alî. Les quatre sont dits bien guidés parce qu'ils gouvernèrent selon le Coran et l'exemple du Prophète ﷺ. Un musulman apprend leur ordre comme le premier chapitre de l'histoire de la communauté après son Prophète ﷺ.",

"sira_041": "Toute biographie classique rapporte que lorsque le Prophète ﷺ rentra tremblant de la grotte de Hirâ après la première révélation, Khadîja le couvrit et lui dit qu'Allah ne l'abandonnerait jamais à la honte, parce qu'il maintenait les liens avec ses proches, portait les fardeaux des faibles, donnait aux pauvres et honorait ses hôtes. Elle l'emmena ensuite chez son cousin Waraqa ibn Nawfal, qui connaissait les Écritures antérieures et lui dit que c'était l'ange venu à Mûsâ. Un musulman apprend que la première à dire oui au message fut celle qui connaissait le mieux le Messager ﷺ.",

"sira_042": "Les biographies rapportent que Bilâl était un esclave abyssin de La Mecque dont le maître, Umayya ibn Khalaf, l'étendait sur le sable brûlant en plein midi, une lourde pierre sur la poitrine, pour lui faire renier sa foi, et que Bilâl répondait seulement « Ahad, Ahad », Un, Un. Abû Bakr, qui tenait sa richesse du commerce, paya au maître son prix et l'affranchit pour Allah. Bilâl devint plus tard le muezzin du Prophète ﷺ à Médine. Un musulman apprend qu'Abû Bakr dépensa son argent pour libérer les opprimés.",

"sira_043": "Les biographies rapportent que Yâsir, sa femme Sumayya et leur fils 'Ammâr comptaient parmi les faibles de La Mecque, sans clan pour les protéger, et qu'Abû Jahl et d'autres torturaient la famille sous la chaleur pour lui faire abandonner l'islam. Le Prophète ﷺ passa près d'eux et dit : « Patience, famille de Yâsir, votre rendez-vous est le Paradis. » Abû Jahl tua Sumayya d'un coup de lance ; lui-même tomba à Badr, tandis que 'Ammâr vécut longtemps comme compagnon. Un musulman apprend que la première martyre de l'islam fut une femme qui choisit sa foi plutôt que sa vie.",

"sira_044": "Toute biographie classique rapporte que lorsque la persécution à La Mecque devint insupportable, le Prophète ﷺ dit à ses compagnons qu'il y avait en Abyssinie un roi chez qui personne n'était lésé, et les envoya chercher refuge auprès de lui. Ils traversèrent la mer Rouge en deux groupes ; parmi eux se trouvaient 'Uthmân et son épouse Ruqayya, fille du Prophète ﷺ. Quraysh envoya des émissaires chargés de cadeaux pour demander au roi de leur livrer les musulmans, et il refusa. Un musulman apprend que chercher la sécurité dans un pays juste, même pas encore musulman, fut le propre conseil du Prophète ﷺ.",

"sira_045": "Le hadith est rapporté par Abû Hurayra et consigné dans le Sahîh al-Bukhârî 1245 : le Messager d'Allah ﷺ annonça la mort du Négus le jour même où il mourut, sortit avec les compagnons vers le lieu de prière, les disposa en rangs et prononça quatre takbîr. Aucune nouvelle n'était parvenue d'Abyssinie à Médine, de sorte que l'annonce était elle-même un signe de prophétie. Le Négus avait abrité les musulmans qui avaient fui La Mecque et refusé de les livrer à Quraysh. Un musulman apprend que le Prophète ﷺ honora le roi qui protégea les faibles.",

"sira_046": "Les biographies conservent la scène telle que la rapporta Umm Salama, l'une des émigrées. Ja'far, frère aîné de 'Alî, dit au roi que son peuple avait vécu dans l'ignorance, adorant les idoles et lésant les faibles, jusqu'à ce qu'Allah leur envoie un messager qui les appela à adorer Allah seul, à dire la vérité, à maintenir les liens de parenté et à protéger leurs voisins. Quand le roi demanda à entendre la révélation, Ja'far récita la sourate Maryam, le Négus pleura et refusa de livrer les musulmans. Un musulman apprend que l'islam fut d'abord expliqué à l'étranger en mots simples et en versets du Coran.",

"sira_047": "La sourate dit : « Que périssent les deux mains d'Abû Lahab, et que lui-même périsse. Sa fortune ne lui servira à rien, ni ce qu'il a acquis. Il brûlera dans un Feu plein de flammes, et sa femme, la porteuse de bois, au cou une corde de fibres tordues » (111:1-5). Le Sahîh al-Bukhârî rapporte l'occasion : quand le Prophète ﷺ monta sur la colline de Safâ et appela Quraysh pour l'avertir, son oncle Abû Lahab répondit en lui souhaitant de périr, et la sourate descendit. Un musulman apprend que la parenté avec le Prophète ﷺ ne fut d'aucune protection pour un homme qui combattit son message.",

"sira_048": "Toute biographie classique rapporte qu'Abû Tâlib et Khadîja moururent à peu d'intervalle, la dixième année de la mission. Abû Tâlib, bien qu'il ne soit jamais entré dans l'islam, avait usé de son rang de chef des Banû Hâshim pour empêcher Quraysh de nuire à son neveu ; le Coran parle de lui quand il dit que le Prophète ﷺ ne peut guider qui il aime (28:56). Une fois les deux disparus, Quraysh le traita plus durement, et il partit à Tâ'if chercher un soutien. Un musulman apprend que même le Prophète ﷺ connut le chagrin, et que le chagrin n'est pas une faiblesse de la foi.",

"sira_049": "Le hadith est rapporté par 'Âisha et consigné dans le Sahîh al-Bukhârî 3231. Elle demanda au Prophète ﷺ si un jour avait été plus dur pour lui qu'Uhud, et il répondit que le plus dur fut celui où il se présenta aux chefs de Tâ'if et fut repoussé, puis s'éloigna dans le chagrin jusqu'à ce qu'un nuage l'ombrage et que Jibrîl l'appelle avec l'ange des montagnes, qui proposa d'écraser ces gens entre les deux montagnes de La Mecque. Le Prophète ﷺ répondit qu'il espérait qu'Allah ferait sortir de leur descendance des gens qui L'adoreraient seul. Un musulman apprend à répondre à la cruauté par l'espoir.",

"sira_050": "Le hadith est rapporté par Anas d'après Abû Dharr et consigné dans le Sahîh al-Bukhârî 349 : Jibrîl lava sa poitrine avec l'eau de Zamzam, la remplit d'un plateau d'or empli de sagesse et de foi, et l'emmena à travers les cieux, où il rencontra Âdam, Idrîs, Mûsâ, 'Îsâ et Ibrâhîm. Là, Allah rendit obligatoires cinquante prières par jour ; Mûsâ lui dit que sa communauté ne pourrait le supporter, et il revint encore et encore jusqu'à ce qu'elles soient cinq, comptées pour cinquante en récompense. Un musulman apprend que la prière quotidienne fut donnée au lieu le plus élevé et allégée par miséricorde.",

"sira_051": "La sourate An-Najm décrit la vision : « Il l'a vu, en vérité, une autre fois » (53:13), « près de Sidrat al-Muntahâ » (53:14), « près duquel se trouve le Jardin du Refuge, au moment où le lotus était couvert de ce qui le couvrait. Le regard n'a ni dévié ni dépassé » (53:15-17). La sourate s'ouvre en jurant par l'étoile que le Prophète ﷺ ne s'est pas égaré et ne dit que ce qui lui est révélé (53:1-4). Un musulman apprend que ce que le Prophète ﷺ rapporta de l'Ascension est confirmé par le Coran lui-même.",

"sira_052": "Toute biographie classique rapporte deux serments, prêtés lors de deux saisons de pèlerinage successives au défilé d'Al-'Aqaba, où le Prophète ﷺ rencontra de nuit les hommes de Yathrib, loin de Quraysh. Au premier, douze hommes s'engagèrent, comme le Sahîh al-Bukhârî le rapporte d'après 'Ubâda ibn as-Sâmit, à ne rien associer à Allah, à ne pas voler, à ne pas commettre l'adultère et à ne pas tuer leurs enfants. Au second, plus de soixante-dix hommes et deux femmes s'engagèrent à le défendre comme ils défendaient leurs propres familles. Un musulman apprend que la communauté de Médine commença par une promesse faite à voix basse dans l'obscurité.",

"sira_053": "Les biographies rapportent qu'après le premier serment d'Al-'Aqaba, les gens de Yathrib demandèrent un enseignant, et que le Prophète ﷺ envoya Mus'ab ibn 'Umayr, un jeune homme de Quraysh qui avait quitté une vie d'aisance pour l'islam. Il logea chez As'ad ibn Zurâra, récita le Coran à quiconque voulait l'écouter, et par lui les chefs Sa'd ibn Mu'âdh et Usayd ibn Hudayr entrèrent dans l'islam. Il fut tué à Uhud en portant l'étendard, avec un simple manteau pour linceul. Un musulman apprend que la foi atteignit Médine grâce à un seul enseignant patient.",

"sira_054": "Toute biographie classique rapporte que les clans de Quraysh convinrent d'envoyer un jeune homme de chacun d'eux pour frapper le Prophète ﷺ ensemble ; le Coran le rappelle : « quand les mécréants complotaient contre toi pour t'emprisonner, te tuer ou te chasser ; ils complotent, et Allah aussi complote » (8:30). Le Prophète ﷺ dit à 'Alî de se coucher dans son lit sous son manteau vert et partit sans être vu, chargeant 'Alî de rendre les dépôts que les Mecquois lui avaient confiés. Un musulman apprend que le Prophète ﷺ garda ses dépôts même envers ceux qui complotaient sa mort.",

"sira_055": "Thawr se trouve au sud de La Mecque alors que Médine est au nord ; les deux hommes prirent d'abord la direction opposée pour dérouter les recherches. Le Coran parle de ce moment : « le second de deux, quand ils étaient dans la grotte, quand il dit à son compagnon : “Ne t'afflige pas, Allah est avec nous” » (9:40). Le Sahîh al-Bukhârî rapporte la crainte d'Abû Bakr qu'un poursuivant regardant sous ses pieds ne les voie, et la réponse du Prophète ﷺ lui demandant ce qu'il pensait de deux dont le troisième était Allah. Un musulman apprend que la confiance en Allah reste calme même dans le danger.",

"sira_056": "Le long récit de l'Hégire rapporté par 'Âisha dans le Sahîh al-Bukhârî 3905 raconte comment les deux hommes se cachèrent trois nuits dans la grotte de Thawr, comment 'Abdullâh, le fils d'Abû Bakr, apportait les nouvelles chaque soir, et comment 'Âmir ibn Fuhayra amenait des brebis pour le lait. Asmâ prépara les provisions et, ne trouvant rien pour attacher le sac de nourriture, coupa sa ceinture en deux et en utilisa une moitié ; de là elle fut nommée Dhât an-Nitâqayn. Un musulman apprend que l'Hégire réussit grâce au service discret de toute une famille.",

"sira_057": "Surâqa ibn Mâlik raconte lui-même l'histoire dans le Sahîh al-Bukhârî 3906. Quand un homme mentionna avoir vu des cavaliers sur la côte, Surâqa, espérant la récompense offerte par Quraysh, partit à leur poursuite ; comme il approchait, les pattes avant de son cheval s'enfoncèrent dans le sol jusqu'aux genoux. Il cria pour demander la sauvegarde, et le Prophète ﷺ fit écrire par 'Âmir ibn Fuhayra une garantie sur un morceau de cuir. Un musulman apprend qu'Allah protégea Son Messager ﷺ sur la route ouverte comme Il l'avait fait dans la grotte.",

"sira_058": "Le verset rapporte les hypocrites pendant le siège de Médine : « Et quand un groupe d'entre eux dit : “Ô gens de Yathrib, il n'y a pas de place pour vous ici, retournez donc”, et qu'une partie d'entre eux demanda au Prophète la permission de partir en disant : “Nos maisons sont sans défense”, alors qu'elles ne l'étaient pas ; ils ne voulaient que fuir » (33:13). Le Sahîh al-Bukhârî rapporte que le Prophète ﷺ dit que les gens l'appelaient Yathrib mais qu'elle était Médine. Un musulman apprend que l'ancien nom survit dans le Coran dans la bouche de ceux qui voulaient abandonner la ville.",

"sira_059": "Le long hadith de Hudaybiyya dans le Sahîh al-Bukhârî 2731 raconte que le Prophète ﷺ partit avec plus de mille compagnons pour accomplir la 'umra, et qu'au défilé près de La Mecque, Al-Qaswâ s'agenouilla et refusa de se relever. Les gens dirent qu'elle était devenue rétive, et le Prophète ﷺ répondit que l'entêtement n'était pas dans sa nature, mais que Celui qui avait retenu l'éléphant loin de La Mecque l'avait retenue. Il jura ensuite d'accorder à Quraysh toute demande qui honorerait le caractère sacré de la Maison d'Allah. Un musulman apprend que le Prophète ﷺ lisait la volonté d'Allah jusque dans l'arrêt de sa chamelle.",

"sira_060": "Toute biographie classique rapporte que peu après son arrivée à Médine, le Prophète ﷺ réunit les émigrés et les auxiliaires dans la maison d'Anas ibn Mâlik et les unit comme frères deux par deux. Le Coran loue les Ansâr pour cela : « ceux qui, avant eux, se sont installés dans la demeure et dans la foi aiment ceux qui émigrent vers eux, ne ressentent dans leur poitrine aucune envie pour ce qui est donné aux émigrés, et les préfèrent à eux-mêmes, même s'ils sont dans le besoin » (59:9). Le Sahîh al-Bukhârî rapporte que Sa'd ibn ar-Rabî' offrit à son frère 'Abd ar-Rahmân ibn 'Awf la moitié de ses biens. Un musulman apprend que la fraternité dans la foi devint réelle par le partage.",

"sira_061": "Toute biographie classique conserve le texte du document que le Prophète ﷺ rédigea à son arrivée à Médine. Il déclare que les croyants de Quraysh et de Yathrib, et quiconque se joint à eux, forment une seule communauté distincte de tous les autres hommes ; que les tribus juives qui entrent dans le pacte forment une communauté aux côtés des croyants, les juifs ayant leur religion et les musulmans la leur ; que Yathrib est inviolable et sera défendue ensemble ; et que tout différend est renvoyé à Allah et à Muhammad ﷺ. Un musulman apprend que la première cité musulmane fut fondée sur des obligations écrites partagées avec ses voisins non musulmans.",

"sira_062": "Le Sahîh al-Bukhârî 6452 rapporte le récit d'Abû Hurayra sur sa faim : il s'attachait une pierre sur le ventre, et un jour il s'assit sur le chemin dans l'espoir d'être nourri ; Abû Bakr et 'Umar passèrent sans s'en apercevoir. Puis le Prophète ﷺ vint, sourit et l'emmena chez lui, où une coupe de lait avait été envoyée en cadeau. Il dit à Abû Hurayra d'appeler les gens de la Suffa, les hôtes de l'islam sans famille ni biens, et de servir chacun jusqu'à ce que tous aient bu à satiété, puis il but lui-même ce qui restait. Un musulman apprend que les compagnons les plus pauvres étaient les propres hôtes du Prophète ﷺ.",

"sira_063": "Toute biographie classique situe la bataille au Ramadan de la deuxième année après l'Hégire, quand le Prophète ﷺ partit avec un peu plus de trois cents hommes pour intercepter une caravane de Quraysh et rencontra à la place une armée d'environ mille hommes venue de La Mecque. Le Coran appelle ce jour le jour du discernement, le jour où les deux armées se rencontrèrent (8:41), et rappelle aux croyants : « Allah vous a déjà donné la victoire à Badr alors que vous étiez peu nombreux » (3:123). Un musulman apprend que Badr fut la première preuve que la petite communauté de Médine survivrait.",

"sira_064": "Le verset appartient au récit de Badr dans la sourate Al-Anfâl : « Quand vous imploriez le secours de votre Seigneur, et qu'Il vous exauça : “Je vous envoie en renfort mille anges, se suivant les uns les autres” » (8:9). Le verset suivant explique leur raison d'être : « Allah ne fit cela que comme bonne annonce et pour que vos cœurs s'en rassurent ; la victoire ne vient que d'Allah » (8:10). La sourate rappelle ensuite la somnolence qui apaisa les croyants et la pluie qui affermit leurs pas (8:11). Un musulman apprend que le secours d'Allah peut venir sans être vu, et que c'est Allah, non le nombre, qui donne la victoire.",

"sira_065": "Le hadith est rapporté par al-Barâ' ibn 'Âzib dans le Sahîh al-Bukhârî 3039. Le Prophète ﷺ plaça 'Abdullâh ibn Jubayr à la tête de cinquante archers et leur dit de ne pas quitter leur position, qu'ils voient les musulmans vaincus ou victorieux, tant qu'il ne les aurait pas fait appeler. Quand Quraysh se débanda et que ses femmes s'enfuirent sur le flanc de la colline, les archers dirent que le butin était à prendre ; Ibn Jubayr leur rappela l'ordre, mais ils descendirent quand même, et leurs visages furent alors retournés. Un musulman apprend qu'obéir à l'ordre du Prophète ﷺ comptait plus que tout gain de l'instant.",

"sira_066": "Toute biographie classique situe le mont Uhud à une courte chevauchée au nord de Médine, si bien que les musulmans sortirent de la ville et campèrent avec la montagne dans le dos. Le Coran parle de ce matin-là : « quand tu quittas ta famille pour placer les croyants à leurs postes de combat » (3:121). Le Sahîh al-Bukhârî rapporte que le Prophète ﷺ dit que c'est une montagne qui nous aime et que nous aimons, et Hamza et les autres martyrs furent enterrés à son pied. Un musulman apprend qu'une montagne de Médine est évoquée avec affection à cause de ceux qui moururent à son pied.",

"sira_067": "Toute biographie classique rapporte le long voyage de Salmân : né en Perse, il quitta le culte du feu de son père, servit des moines chrétiens dans plusieurs villes, apprit qu'un prophète paraîtrait dans une terre de palmiers-dattiers et atteignit Médine comme esclave, où le Prophète ﷺ l'aida à racheter sa liberté. Quand les coalisés marchèrent sur Médine, Salmân proposa de creuser une tranchée sur le côté ouvert de la ville, une défense qu'il avait vue en Perse, et le Prophète ﷺ porta la terre aux côtés des compagnons. Un musulman apprend qu'un bon conseil est bienvenu, de quelque pays qu'il vienne.",

"sira_068": "La sourate rappelle le siège : « Ô vous qui croyez, souvenez-vous du bienfait d'Allah envers vous quand des armées vinrent à vous et que Nous envoyâmes contre elles un vent et des armées que vous ne voyiez pas » (33:9), « quand ils vinrent à vous d'en haut et d'en bas, quand les regards se troublèrent et que les cœurs remontèrent jusqu'aux gorges » (33:10). Les croyants, voyant les coalisés, dirent que c'était ce qu'Allah et Son Messager leur avaient promis (33:22), et Allah renvoya les mécréants sans qu'ils aient rien obtenu (33:25). Un musulman apprend que le siège fut brisé par un vent et par la foi, non par une épée.",

"sira_069": "Le verset dit : « Allah a certes été satisfait des croyants quand ils te prêtaient serment sous l'arbre ; Il savait ce qu'il y avait dans leurs cœurs, alors Il fit descendre sur eux la sérénité et les récompensa par une victoire proche » (48:18). Le Sahîh al-Bukhârî rapporte l'occasion : le Prophète ﷺ avait envoyé 'Uthmân à La Mecque comme émissaire, et quand le bruit vint qu'il avait été tué, le Prophète ﷺ appela les compagnons à lui prêter serment sous un arbre à Hudaybiyya. Un musulman apprend qu'Allah Lui-même consigna Son agrément pour ceux qui se tinrent aux côtés de Son Messager ﷺ.",

"sira_070": "La sourate commence ainsi : « Nous t'avons accordé une victoire éclatante, afin qu'Allah te pardonne tes péchés passés et futurs » (48:1-2). Le Sahîh al-Bukhârî rapporte qu'elle descendit sur le chemin du retour de Hudaybiyya, et que le Prophète ﷺ dit qu'une sourate lui avait été révélée qui lui était plus chère que tout ce sur quoi le soleil se lève. Les compagnons avaient ressenti le traité comme un recul ; la révélation le nomma une victoire. Un musulman apprend que le jugement d'Allah sur un événement peut être l'inverse de ce qu'il paraît le jour même.",

"sira_071": "Toute biographie classique situe le traité en Dhû l-Qa'da de la sixième année après l'Hégire, quand le Prophète ﷺ était venu accomplir la 'umra et que Quraysh lui barra la route. Le Sahîh al-Bukhârî en conserve les termes : les musulmans repartiraient cette année-là et reviendraient l'année suivante pour trois jours ; il n'y aurait pas de combat pendant dix ans ; et quiconque viendrait de Quraysh au Prophète ﷺ sans permission serait renvoyé. L'année suivante, le Prophète ﷺ accomplit la 'umra comme convenu. Un musulman apprend qu'une paix difficile, fidèlement respectée, ouvrit le chemin de La Mecque.",

"sira_072": "Le Sahîh al-Bukhârî 7 rapporte, d'après Ibn 'Abbâs, comment Héraclius convoqua Abû Sufyân et les marchands mecquois présents en Syrie et l'interrogea sur l'homme qui se disait prophète : sa lignée, qui le suivait, s'il avait jamais menti ou rompu un pacte, et ce qu'il ordonnait. Abû Sufyân, encore ennemi, répondit avec sincérité, et Héraclius conclut que s'il en était ainsi, cet homme régnerait un jour sur le sol sous ses pieds. La lettre, lue ensuite, citait l'appel aux gens du Livre à une parole commune (3:64). Un musulman apprend que même le témoignage honnête d'un ennemi rendit témoignage au Prophète ﷺ.",

"sira_073": "Le hadith est rapporté par Sahl ibn Sa'd dans le Sahîh al-Bukhârî 3701. Les compagnons passèrent la nuit à se demander qui recevrait l'étendard, et au matin chacun l'espérait, mais le Prophète ﷺ demanda 'Alî, qui souffrait des yeux ; il y appliqua sa salive, pria pour lui, et 'Alî fut guéri comme s'il n'avait jamais eu mal. En lui remettant l'étendard, il lui dit d'avancer calmement et d'inviter d'abord les gens à l'islam, car qu'Allah guide un seul homme par lui valait mieux que des chameaux roux. Un musulman apprend que le but de l'étendard était la guidance avant la conquête.",

"sira_074": "Le hadith est rapporté par Anas dans le Sahîh al-Bukhârî 4262. Avant qu'aucun messager ne soit arrivé du champ de bataille, le Prophète ﷺ dit aux gens de Médine que Zayd avait pris l'étendard et était tombé, puis Ja'far, puis Ibn Rawâha, les yeux baignés de larmes tandis qu'il parlait, jusqu'à ce qu'un sabre parmi les sabres d'Allah le prenne et qu'Allah leur accorde la victoire. Zayd ibn Hâritha est le seul compagnon nommé dans le Coran (33:37). Un musulman apprend que le Prophète ﷺ pleura ses compagnons et les honora dans l'ordre où ils tombèrent.",

"sira_075": "Les mots viennent du hadith d'Anas dans le Sahîh al-Bukhârî 4262, où le Prophète ﷺ dit que l'étendard fut ensuite pris par un sabre parmi les sabres d'Allah, par qui Allah donna la victoire aux musulmans. Toute biographie classique l'identifie comme Khâlid ibn al-Walîd, qui avait mené la cavalerie de Quraysh contre les musulmans à Uhud et embrassé l'islam après le traité de Hudaybiyya ; à Mu'ta, il ramena l'armée en sécurité. Un musulman apprend qu'un titre donné par le Prophète ﷺ peut survivre à l'ancienne hostilité d'un homme.",

"sira_076": "Le hadith est rapporté par Ibn Mas'ûd dans le Sahîh al-Bukhârî 4287 : quand le Prophète ﷺ entra à La Mecque le jour de la conquête, il y avait trois cent soixante idoles autour de la Ka'ba, et il passa parmi elles en les frappant d'un bâton et en récitant : « La vérité est venue et le faux a disparu ; certes, le faux est voué à disparaître » (17:81), avec un verset de la sourate Saba (34:49). Le premier verset avait été révélé des années plus tôt à La Mecque, alors que les idoles étaient encore debout. Un musulman apprend que la Maison bâtie pour l'adoration d'Allah seul fut purifiée avec les mots mêmes du Coran.",

"sira_077": "Toute biographie classique rapporte que le jour de la conquête de La Mecque, une fois les idoles retirées de la Ka'ba, le Prophète ﷺ ordonna à Bilâl de monter sur son toit et de lancer l'appel à la prière, et la voix de l'ancien esclave retentit sur la ville où il avait été torturé pour avoir dit qu'Allah est Un. Bilâl était le muezzin du Prophète ﷺ depuis l'institution de l'adhân à Médine, comme le rapporte le Sahîh al-Bukhârî. Un musulman apprend qu'en islam, le rang vient de la foi et non de la naissance.",

"sira_078": "Toute biographie classique rapporte que le jour de la conquête, le Prophète ﷺ se tint à la porte de la Ka'ba devant les Quraysh assemblés, qui l'avaient combattu pendant des années, et leur demanda ce qu'ils pensaient qu'il ferait d'eux. Ils répondirent qu'il était un frère noble et le fils d'un frère noble. Il répondit par les mots de Yûsuf à ses frères : « Pas de reproche contre vous aujourd'hui ; Allah vous pardonnera » (12:92), puis leur dit de s'en aller, car ils étaient libres. Un musulman apprend que la plus grande victoire du Prophète ﷺ fut scellée par le pardon.",

"sira_079": "Les versets disent : « … et le jour de Hunayn, quand votre grand nombre vous plut mais ne vous servit à rien, et que la terre, malgré son étendue, vous devint étroite ; puis vous tournâtes le dos en fuyant. Puis Allah fit descendre Sa sérénité sur Son Messager et sur les croyants, et fit descendre des soldats que vous ne voyiez pas » (9:25-26). Toute biographie classique situe la bataille peu après la conquête de La Mecque, contre Hawâzin et Thaqîf ; le Prophète ﷺ tint bon sur sa mule jusqu'à ce que les compagnons se rallient. Un musulman apprend que compter sur le nombre est une faiblesse, et compter sur Allah une force.",

"sira_080": "Ka'b raconte lui-même son histoire dans le Sahîh al-Bukhârî 4418. Il remit sans cesse son départ pour Tabûk jusqu'à ce que l'armée soit partie. Quand le Prophète ﷺ revint, les hypocrites vinrent avec des excuses et des serments et furent laissés en paix, mais Ka'b dit qu'il n'avait aucune excuse ; le Prophète ﷺ répondit que cet homme avait dit la vérité, et ordonna aux musulmans de ne pas lui parler. Au cinquantième matin, le verset descendit : « Et sur les trois qui furent laissés en arrière » (9:118). Un musulman apprend qu'une vérité dure dite au Prophète ﷺ valait mieux que tout mensonge facile.",

"sira_081": "Toute biographie classique rapporte qu'une fois La Mecque entrée dans l'islam, les tribus d'Arabie envoyèrent des délégations à Médine pour déclarer leur islam devant le Prophète ﷺ ; parmi elles vint Thaqîf de Tâ'if, la ville qui l'avait chassé. Le Coran parle de cette saison : « Quand vient le secours d'Allah ainsi que la victoire, et que tu vois les gens entrer en foule dans la religion d'Allah, alors glorifie ton Seigneur par la louange et implore Son pardon » (110:1-3). Un musulman apprend que la réponse à un flot de nouveaux croyants fut la louange et l'humilité.",

"sira_082": "Toute biographie classique rapporte que pendant son unique pèlerinage, le Prophète ﷺ s'adressa aux pèlerins à Arafat, leur disant que leur sang et leurs biens étaient aussi sacrés les uns pour les autres que ce jour, ce mois et cette ville, et qu'il laissait parmi eux le Livre d'Allah, auquel quiconque s'attacherait ne s'égarerait jamais. Quand ils affirmèrent qu'il avait transmis le message, il prit Allah à témoin, trois fois. Le verset annonçant le parachèvement de la religion fut révélé à Arafat ce même jour (5:3). Un musulman apprend que les dernières paroles publiques du Prophète ﷺ portèrent sur le caractère sacré de la vie et la garde du Coran.",

"sira_083": "Le passage entier dit : « Aujourd'hui, les mécréants désespèrent de votre religion. Aujourd'hui, J'ai parachevé pour vous votre religion, et accompli sur vous Mon bienfait, et J'agrée pour vous l'islam comme religion » (5:3). Le Sahîh al-Bukhârî rapporte qu'un juif dit à 'Umar que si ce verset était venu aux juifs, ils auraient fait de ce jour une fête, et que 'Umar répondit qu'il était descendu alors que le Prophète ﷺ se tenait à Arafat, un vendredi. Un musulman apprend que la religion fut déclarée complète pendant le pèlerinage d'adieu, sans que rien reste à y ajouter.",

"sira_084": "Toute biographie classique rapporte qu'après le pèlerinage d'adieu, le Prophète ﷺ revint à Médine, tomba malade quelques mois plus tard, la onzième année après l'Hégire, et mourut un lundi dans la chambre de son épouse 'Âisha, à côté de sa mosquée. Le Sahîh al-Bukhârî rapporte que ses derniers mots furent une prière pour la plus haute compagnie. Il fut enterré dans la chambre où il mourut, et Abû Bakr et 'Umar furent plus tard déposés à ses côtés. Un musulman apprend que la ville qui accueillit le Prophète ﷺ lors de l'Hégire est la ville qui garde sa tombe.",

"sira_085": "Le Sahîh al-Bukhârî rapporte le récit de 'Âisha sur le dernier jour : le Prophète ﷺ mourut appuyé contre sa poitrine, et elle tint pour une faveur d'Allah que cela soit arrivé dans sa maison et le jour qui lui revenait. Il fut enterré dans cette chambre, et toute biographie classique rapporte qu'Abû Bakr, puis 'Umar, furent enterrés à ses côtés. Quand la mosquée fut plus tard agrandie, la chambre fut englobée en elle, de sorte que sa tombe se trouve aujourd'hui à l'intérieur de la Mosquée du Prophète. Un musulman apprend que le Prophète ﷺ mourut dans une petite chambre parmi les siens, sans rien du cérémonial d'un roi.",

"sira_086": "Le hadith est rapporté par 'Âisha et consigné dans le Sahîh al-Bukhârî 3667. Abû Bakr entra, découvrit le visage du Prophète ﷺ, l'embrassa et pleura. Il sortit ensuite vers la mosquée, où 'Umar disait aux gens que le Prophète ﷺ n'était pas mort, lui dit de s'asseoir, prononça les mots que cite la question et récita : « Muhammad n'est qu'un messager ; des messagers sont passés avant lui. S'il meurt ou s'il est tué, retournerez-vous sur vos talons ? » (3:144). Un musulman apprend que le chagrin pour le Prophète ﷺ est juste, mais que l'adoration n'appartient qu'à Allah.",

"sira_087": "Toute biographie classique rapporte qu'al-Hasan et al-Husayn naquirent à Médine de Fâtima, fille du Prophète ﷺ, et de 'Alî, et que leur grand-père les portait sur ses épaules, les asseyait sur ses genoux et les laissait grimper sur son dos. Le Sahîh al-Bukhârî rapporte qu'il dit d'al-Hasan : « Ô Allah, je l'aime, aime-le donc, et aime quiconque l'aime », et qu'il appela les deux ses deux fleurs odorantes en ce monde. Un musulman apprend que le Prophète ﷺ montra ouvertement sa tendresse pour les enfants et demanda aux autres de les aimer.",

"sira_088": "Toute biographie classique rapporte que le Prophète ﷺ épousa 'Âisha, fille de son plus proche compagnon Abû Bakr, après la mort de Khadîja, et qu'elle vécut avec lui dans la chambre attenante à la mosquée où il mourut plus tard. Le Sahîh al-Bukhârî rapporte que lorsqu'on lui demanda qui il aimait le plus, il répondit 'Âisha, et lorsqu'on lui demanda parmi les hommes, son père. Après sa mort, elle vécut encore de longues années à Médine, et les compagnons et leurs élèves venaient auprès d'elle pour apprendre. Un musulman apprend qu'une grande part de ce que l'on sait de la vie familiale du Prophète ﷺ vient de l'épouse qui s'en souvenait.",

"sira_089": "Toute biographie classique rapporte que le premier mari de Hafsa mourut après Badr, et que son père 'Umar la proposa en mariage à Abû Bakr et à 'Uthmân, qui déclinèrent tous deux, avant que le Prophète ﷺ ne la demande lui-même. Le Sahîh al-Bukhârî rapporte qu'après la mort de 'Umar, les feuillets sur lesquels le Coran avait été rassemblé au temps d'Abû Bakr furent gardés chez Hafsa, et que 'Uthmân les lui emprunta pour faire les copies qu'il envoya aux villes, avant de les lui rendre. Un musulman apprend que le texte du Coran passa par la garde d'une épouse du Prophète ﷺ.",

"sira_090": "Toute biographie classique rapporte qu'Abû Hurayra vint au Prophète ﷺ l'année de Khaybar, vécut parmi les pauvres de la Suffa et resta constamment à ses côtés. Le Sahîh al-Bukhârî rapporte sa propre explication : les Muhâjirûn étaient occupés aux marchés et les Ansâr à leurs terres, tandis que lui suivait le Prophète ﷺ le ventre vide ; et quand il se plaignit d'oublier, le Prophète ﷺ lui fit étendre son manteau et le serrer contre sa poitrine, après quoi il n'oublia plus rien. Un musulman apprend que la plus grande réserve de hadiths fut gardée par un homme qui choisit la compagnie plutôt que le commerce.",
}
