"""Français — détails, sira_b (60 questions)."""

D = {
"sira_091": "Anas ibn Mâlik rapporte dans Sahîh al-Bukhârî 6038 qu'en dix ans de service le Prophète ﷺ ne lui a jamais dit « ouf », ne lui a jamais demandé d'une chose faite « pourquoi l'as-tu faite ? », ni d'une chose laissée « pourquoi ne l'as-tu pas faite ? ». « Ouf » est le plus petit son d'impatience, le mot même que le Coran interdit à un enfant de dire à ses parents âgés (17:23). Un musulman en retient comment traiter ceux qui aident à la maison : avec patience, sans petits reproches.",

"sira_092": "Ibn 'Abbâs raconte le moment dans Sahîh al-Bukhârî 75 : le Prophète ﷺ le serra contre sa poitrine et dit : « Ô Allah, enseigne-lui le Livre. » Le Livre est le Coran, descendu « comme un exposé explicite de toute chose, ainsi qu'un guide, une miséricorde et une bonne annonce pour les musulmans » (16:89). Ibn 'Abbâs était un enfant, et la prière vint avec une étreinte. Un musulman apprend à joindre l'affection à la prière pour un enfant, et à demander d'abord à Allah la compréhension du Coran.",

"sira_093": "Ibn 'Abbâs relate dans Sahîh al-Bukhârî 1395 les instructions que le Prophète ﷺ donna à Mu'âdh ibn Jabal : il allait chez des gens du Livre et devait d'abord les appeler à témoigner qu'il n'y a de divinité qu'Allah et que Muhammad est Son Messager. S'ils acceptaient, il devait leur enseigner les cinq prières quotidiennes qu'Allah avait rendues obligatoires ; puis, qu'une aumône était due de leurs riches à leurs pauvres. Un musulman apprend que l'appel commence par l'unicité d'Allah et avance pas à pas.",

"sira_094": "Anas rapporte dans Sahîh al-Bukhârî 3744 que le Prophète ﷺ dit que chaque communauté a un homme de confiance, et que l'homme de confiance de cette communauté est Abû 'Ubayda ibn al-Jarrâh. Amîn était le titre que La Mecque avait donné au Prophète ﷺ avant sa mission, et ici il le donne publiquement à un compagnon. Le Coran compte parmi ceux qui réussissent « ceux qui gardent fidèlement leurs dépôts et leurs engagements » (23:8). Un musulman en retient qu'être digne de confiance est un rang, que le chef honore en public.",

"sira_095": "Zayd ibn Thâbit le raconte dans Sahîh al-Bukhârî 4986. Après les pertes parmi les récitateurs à al-Yamâma, 'Umar pressa Abû Bakr de rassembler le Coran avant que davantage ne soit perdu, et Abû Bakr, d'abord réticent à faire ce que le Prophète ﷺ n'avait pas fait, accepta. Il dit à Zayd qu'il était un jeune homme sage qui avait écrit la révélation. Zayd dit que déplacer une montagne aurait été plus léger, et rassembla le Coran à partir de parchemins, de pétioles de palmier et de la mémoire des hommes. Un musulman apprend avec quel soin son Livre a été préservé.",

"sira_096": "Anas ibn Mâlik relate dans Sahîh al-Bukhârî 4987 comment les copies officielles virent le jour. Hudhayfa, alarmé par des différences de récitation entre les musulmans de Syrie et d'Irak, demanda à 'Uthmân de sauver la communauté avant qu'elle ne diverge sur son Livre comme les communautés antérieures l'avaient fait. 'Uthmân emprunta à Hafsa les feuillets rassemblés sous Abû Bakr, les fit copier par Zayd ibn Thâbit et trois hommes de Quraysh, et envoya un exemplaire à chaque province. Un musulman apprend que l'unité du texte du Coran fut gardée par les compagnons eux-mêmes.",

"sira_097": "Toutes les biographies rapportent que Salmân naquit en Perse et quitta son pays à la recherche de la vraie religion, servant des moines chrétiens avant d'être vendu comme esclave et emmené à Yathrib. Là, après l'Hégire, il observa chez le Prophète ﷺ les signes qu'il attendait, embrassa l'islam et obtint sa liberté. Au siège de Médine, c'est Salmân qui proposa le fossé. Un musulman apprend que la vérité vaut un long voyage, et que l'islam fit du Persan, de l'Arabe et de l'Abyssin une seule famille.",

"sira_098": "Les biographies s'accordent sur le fait que Suhayb naquit arabe, fut capturé enfant et élevé chez les Byzantins, et vint à La Mecque, où il obtint sa liberté et embrassa l'islam. Quand il partit pour Médine, Quraysh le poursuivit, et il acheta son passage en cédant toute la richesse qu'il avait gagnée. Le Prophète ﷺ l'accueillit en disant que le commerce de Suhayb avait été profitable. Un musulman apprend qu'un croyant compte la foi et la compagnie du Prophète ﷺ pour plus que tout ce qu'il possède.",

"sira_099": "Al-Masjid an-Nabawî est la mosquée que le Prophète ﷺ fonda en arrivant à Médine ; toutes les biographies rapportent qu'il la construisit avec ses compagnons en briques de terre et en troncs de palmier, portant lui-même les briques. Les chambres de ses épouses donnaient sur elle, les pauvres de la Suffa s'y abritaient, et là il enseigna, jugea et dirigea la prière pendant dix ans. Il fut enterré dans la chambre de 'Âisha, à côté d'elle, aujourd'hui à l'intérieur de la mosquée. Un musulman y voit le cœur de la première communauté, où la prière et la vie quotidienne ne faisaient qu'un.",

"sira_100": "Le nom figure dans quatre versets : « Muhammad n'est qu'un messager ; des messagers sont passés avant lui » (3:144) ; « Muhammad n'est le père d'aucun de vos hommes, mais le Messager d'Allah et le Sceau des Prophètes » (33:40) ; la foi « en ce qui a été descendu sur Muhammad » (47:2) ; et « Muhammad est le Messager d'Allah » (48:29). En 61:6, 'Îsâ annonce un messager « dont le nom est Ahmad ». Un musulman apprend à trouver son Prophète ﷺ nommé dans le Livre qu'il récite.",

"sira_101": "Le verset dit : « Vous avez dans le Messager d'Allah un excellent modèle pour quiconque espère en Allah et au Jour dernier et invoque Allah souvent » (33:21). Il appartient au siège de Médine dans la sourate al-Ahzâb, quand l'ennemi vint « d'en haut et d'en bas de vous » (33:10), et que les croyants, voyant les armées, dirent que c'était ce qu'Allah avait promis (33:22). Un musulman en retient que suivre le Prophète ﷺ, c'est imiter sa conduite, surtout dans l'épreuve.",

"sira_102": "Toutes les biographies rapportent que le premier enfant du Prophète ﷺ avec Khadîja fut un fils, al-Qâsim, né avant la révélation, et que, selon la coutume arabe, le père fut dès lors appelé Abû al-Qâsim. Le garçon mourut encore petit, comme l'autre fils né de Khadîja, 'Abdullâh, mais la kunya resta au Prophète ﷺ toute sa vie. Une kunya, dans l'usage arabe, marque l'honneur et la proximité. Un musulman apprend que derrière ce titre familier se tient un père qui enterra ses enfants et le supporta avec patience.",

"sira_103": "Les biographies s'accordent sur le fait qu'Ibrâhîm naquit à Médine de Mâriya et fut allaité dans une maison que le Prophète ﷺ visitait souvent. L'enfant mourut en bas âge, et le Prophète ﷺ le tint dans ses bras pendant qu'il mourait et pleura. Ce jour-là, le soleil s'éclipsa, et les gens dirent que c'était pour Ibrâhîm ; le Prophète ﷺ leur dit que le soleil et la lune sont deux signes d'Allah, qui ne s'éclipsent pour la mort de personne. Un musulman apprend que les larmes sont permises, et que les signes de la nature ne sont liés à aucun homme.",

"sira_104": "Toutes les biographies rapportent que Khadîja était commerçante et qu'ayant entendu parler de l'honnêteté de Muhammad ﷺ, elle l'envoya avec sa caravane en Syrie avec son serviteur Maysara, qui revint en faisant son éloge. Le commerce prospéra, et elle lui fit proposer le mariage. Quand la première révélation vint, elle fut la première à croire et le rassura, disant qu'Allah ne couvrirait jamais de honte un homme qui maintenait les liens de parenté et aidait les faibles. Un musulman apprend que sa mission commença dans un mariage bâti sur la confiance.",

"sira_105": "Toutes les biographies rapportent la reconstruction de la Ka'ba. Quand les murs atteignirent la hauteur de la Pierre noire, chaque clan réclama de la poser, et la dispute frôla le sang jusqu'à ce qu'ils conviennent que le premier homme à franchir la porte déciderait. Ce fut Muhammad ﷺ, et ils acceptèrent le jugement d'al-Amîn. Il étendit son manteau, y posa la Pierre, fit soulever un bord par un chef de chaque clan, et la mit en place lui-même. Un musulman apprend qu'une solution juste qui donne à chacun sa part met fin à une querelle.",

"sira_106": "Les biographies s'accordent sur le fait que le Prophète ﷺ avait quarante ans quand la révélation commença, et qu'il avait pris l'habitude de se retirer dans la grotte de Hirâ pour adorer seul. Le Coran nomme le mois : « le mois de Ramadan, au cours duquel le Coran a été descendu » (2:185). Jibrîl vint à lui là-bas avec « Lis, au nom de ton Seigneur qui a créé » (96:1). Quarante ans est l'âge que le Coran décrit comme la pleine maturité (46:15). Un musulman apprend que la mission commença dans la solitude et la réflexion.",

"sira_107": "Sahîh al-Bukhârî 3 décrit Waraqa ibn Nawfal comme le cousin de Khadîja, chrétien avant l'islam, qui écrivait de l'Évangile en hébreu. Khadîja dit : « Écoute ton neveu », et après avoir entendu le récit de Hirâ, Waraqa dit que c'était le Nâmûs qu'Allah avait envoyé à Mûsâ, et souhaita être jeune pour le jour où son peuple le chasserait. Quand on lui demanda s'ils le feraient, Waraqa répondit qu'aucun homme n'avait jamais apporté ce qu'il apportait sans rencontrer l'hostilité. Un musulman apprend qu'un homme des Écritures antérieures reconnut sa mission.",

"sira_108": "Ibn 'Abbâs relate dans Sahîh al-Bukhârî 4770 que lorsque « Et avertis tes proches les plus proches » (26:214) fut révélé, le Prophète ﷺ monta sur as-Safâ et appela les clans de Quraysh. Il leur demanda s'ils le croiraient s'il disait que des cavaliers allaient les attaquer, et ils dirent n'avoir jamais connu de lui que la vérité. Il dit qu'il les avertissait d'un châtiment sévère. Abû Lahab lui souhaita la ruine, et « Que périssent les deux mains d'Abû Lahab » (111:1) descendit. Un musulman apprend que son message reposait sur une honnêteté éprouvée.",

"sira_109": "Tous les récits du califat de 'Umar rapportent que, lorsque les documents datés rendirent nécessaire un calendrier fixe, il réunit les compagnons pour décider à partir de quel événement compter les années. Ils choisirent l'Hégire plutôt que la naissance ou la mort du Prophète ﷺ, et firent commencer l'année par Muharram. Le Coran avait déjà fixé les mois : « Le nombre des mois, auprès d'Allah, est de douze mois, dans le registre d'Allah » (9:36). Un musulman apprend que son calendrier compte à partir de la fondation de la communauté.",

"sira_110": "Toutes les biographies s'accordent sur le fait que le Prophète ﷺ entra à Médine en Rabî' al-Awwal et mourut le même mois de la onzième année, à dix ans d'écart. Entre les deux se placent les grands événements : Badr la deuxième année, Uhud la troisième, le siège de Médine la cinquième, Hudaybiyya la sixième, la conquête de La Mecque la huitième et le pèlerinage d'adieu la dixième. Le Coran appelle la ville de son ancien nom, Yathrib (33:13). Un musulman apprend qu'une communauté entière fut bâtie en une décennie.",

"sira_111": "Les biographies s'accordent sur le fait que, de la première révélation à l'Hégire, le Prophète ﷺ prêcha à La Mecque pendant treize ans : trois à appeler les gens discrètement, le reste en public, à travers l'émigration en Abyssinie, le boycott de son clan, les morts de Khadîja et d'Abû Tâlib et les serments de 'Aqaba. Le Coran décrit sa révélation comme « un Coran que Nous avons fragmenté, pour que tu le récites aux gens lentement » (17:106). Un musulman apprend que l'enseignement du Coran fut donné en des années de patience.",

"sira_112": "Al-Barâ' rapporte dans Sahîh al-Bukhârî 3212 que le Prophète ﷺ dit à Hassân : « Satirise-les, et Jibrîl est avec toi. » Hassân ibn Thâbit était un poète des Ansâr, et les poètes de Quraysh attaquaient le Prophète ﷺ en vers. Le Coran condamne les poètes que suivent les égarés mais excepte « ceux qui croient, font de bonnes œuvres, invoquent Allah souvent et se défendent après avoir été lésés » (26:227). Un musulman apprend qu'un don pour les mots est honoré quand il est mis au service de la vérité.",

"sira_113": "Abû Mûsâ al-Ash'arî raconte dans Sahîh al-Bukhârî 5048 que le Prophète ﷺ lui dit : « Ô Abû Mûsâ, tu as reçu une des flûtes de la famille de Dâwûd. » Le Coran rapporte qu'Allah donna à Dâwûd le Zabûr (4:163) et fit que les montagnes et les oiseaux se joignent à lui dans la louange (21:79), le modèle d'une voix qui loue. Abû Mûsâ récitait le Coran quand le Prophète ﷺ l'entendit. Un musulman apprend qu'une belle récitation est un don que le Prophète ﷺ admirait.",

"sira_114": "'Abdullâh ibn 'Amr rapporte dans Sahîh al-Bukhârî 3758 qu'il entendit le Prophète ﷺ dire : « Prenez le Coran de quatre », en commençant par 'Abdullâh ibn Mas'ûd, puis Sâlim l'affranchi d'Abû Hudhayfa, Mu'âdh ibn Jabal et Ubayy ibn Ka'b. Ibn Mas'ûd et Sâlim étaient des émigrés de La Mecque, Mu'âdh et Ubayy étaient des Ansâr, de sorte que les maîtres du Coran venaient des deux moitiés de la communauté. Un musulman apprend que le Coran fut transmis par des maîtres nommés en qui le Prophète ﷺ avait confiance, dans une chaîne qui remonte jusqu'à lui.",

"sira_115": "Sahîh al-Bukhârî 4073 rapporte que le jour d'Uhud le visage du Prophète ﷺ fut blessé et une dent de devant brisée. Le Coran parle de ce jour, où les musulmans fuyaient « tandis que le Messager vous appelait par-derrière » (3:153), et console les blessés : « Si une blessure vous atteint, pareille blessure a déjà atteint le peuple adverse » (3:140). Il resta sur le champ de bataille avec ses compagnons. Un musulman apprend que le Prophète ﷺ partagea la douleur de sa communauté dans son propre corps.",

"sira_116": "'Alî rapporte dans Sahîh al-Bukhârî 4055 qu'il n'entendit jamais le Prophète ﷺ dire à quelqu'un « que mon père et ma mère te soient sacrifiés », sauf à Sa'd ibn Abî Waqqâs, le jour d'Uhud, quand il lui dit de tirer. Sa'd décochait des flèches pour tenir l'ennemi loin du Prophète ﷺ. Chez les Arabes, offrir ses parents en rançon était la plus forte expression de l'amour. Un musulman apprend que le courage à défendre le Prophète ﷺ valut des mots qu'il ne donna à personne d'autre.",

"sira_117": "Les biographies s'accordent sur le fait que les musulmans marchèrent à la rencontre d'une caravane de Quraysh menée par Abû Sufyân revenant de Syrie, mais qu'il obliqua le long de la côte et envoya chercher du secours à La Mecque, de sorte qu'une armée sortit à sa place. Le Coran le rappelle : « Et quand Allah vous promettait qu'un des deux groupes serait à vous, vous souhaitiez que ce soit celui qui n'était pas armé » (8:7). La bataille suivit à Badr. Un musulman apprend que ce qu'Allah choisit était plus dur que ce qu'ils voulaient, et plus grand.",

"sira_118": "Toutes les biographies rapportent qu'Abû Sufyân, le chef de Quraysh, sortit épier l'armée qui approchait de La Mecque, fut amené au Prophète ﷺ par son oncle al-'Abbâs, et embrassa l'islam la nuit précédant l'entrée. Le Prophète ﷺ l'honora alors en proclamant que quiconque entrait dans la maison d'Abû Sufyân était en sécurité, comme quiconque fermait sa porte ou entrait dans la mosquée. Un musulman apprend que le Prophète ﷺ accueillit son plus vieil ennemi avec sécurité et honneur.",

"sira_119": "Ibn 'Abbâs le raconte dans Sahîh al-Bukhârî 3364. Ibrâhîm laissa Hâjar et Ismâ'îl dans la vallée ; quand elle demanda si Allah avait ordonné cela et qu'il dit oui, elle répondit qu'Il ne les abandonnerait pas. L'eau vint à manquer, l'enfant pleura de soif, et elle vit un ange creuser du talon jusqu'à ce que l'eau jaillisse. Elle fit un bassin, et le Prophète ﷺ dit que si elle l'avait laissée, Zamzam aurait coulé librement. Un musulman apprend que Zamzam fut donnée à une mère qui avait confiance en Allah.",

"sira_120": "Anas rapporte dans Sahîh al-Bukhârî 5872 que le Prophète ﷺ fit faire une bague d'argent, gravée « Muhammad Rasûl Allah », dans le récit de ses lettres : quand il décida d'écrire aux souverains, on lui dit qu'une lettre sans sceau ne serait pas lue. Anas ajoute que la blancheur de la bague était encore devant ses yeux. Les trois mots sont la seconde moitié du témoignage de foi. Un musulman apprend que le Prophète ﷺ usa des moyens de son temps pour faire recevoir son message.",

"sira_121": "'Âisha rapporte dans Sahîh al-Bukhârî 5431 que le Messager d'Allah ﷺ aimait les sucreries et le miel. Sa courte phrase le montre prenant plaisir à une bonne nourriture sans excès. Le Coran parle du miel comme d'une guérison : des abeilles « sort de leur ventre une boisson aux couleurs variées, dans laquelle il y a une guérison pour les gens » (16:69). Son goût allait à une chose que le Coran nomme parmi les signes d'Allah. Un musulman apprend que jouir d'une nourriture licite avec gratitude fait partie de la voie du Prophète ﷺ.",

"sira_122": "Abû Qatâda rapporte dans Sahîh Muslim 1162 que le Prophète ﷺ fut interrogé sur le jeûne du lundi et répondit que c'était le jour où il était né et le jour où la révélation lui était descendue. Le même hadith rapporte que le jeûne du jour de 'Arafa expie l'année précédente et l'année suivante, et 'Âshûrâ' l'année précédente. Naissance et mission tombent le même jour de la semaine, et il l'honora non par une fête mais par un jeûne. Un musulman apprend que la gratitude pour un bienfait se montre par l'adoration.",

"sira_123": "As-Sâ'ib ibn Yazîd relate dans Sahîh al-Bukhârî 3541 qu'enfant il fut emmené par sa tante auprès du Prophète ﷺ ; le Prophète ﷺ lui caressa la tête, pria pour sa bénédiction et fit ses ablutions, et l'enfant but de l'eau. Puis il se tint derrière lui et vit le sceau de la prophétie entre ses épaules, comme le bouton d'une tente. Le Coran l'appelle « le Sceau des Prophètes » (33:40). Un musulman apprend que même les enfants qui rencontrèrent le Prophète ﷺ se souvenaient de lui de près.",

"sira_124": "Sahl ibn Sa'd relate dans Sahîh al-Bukhârî 917 que le Prophète ﷺ demanda à une femme de faire fabriquer par son esclave charpentier quelque chose en bois sur quoi s'asseoir pour s'adresser aux gens, fait du tamaris d'al-Ghâba. Une fois qu'il fut dressé dans la mosquée, le Prophète ﷺ y pria, en redescendit à reculons pour se prosterner à son pied, puis dit aux gens qu'il avait fait cela pour qu'ils apprennent sa prière. Un musulman apprend que le Prophète ﷺ montra la prière autant qu'il la décrivit.",

"sira_125": "Toutes les biographies rapportent que les Aws et les Khazraj s'étaient combattus pendant des générations, et que des hommes des Khazraj rencontrèrent le Prophète ﷺ à La Mecque, acceptèrent son appel et revinrent avec des hommes des Aws prêter serment d'allégeance à 'Aqaba. Le Coran le leur rappelle : « Rappelez-vous le bienfait d'Allah sur vous : lorsque vous étiez ennemis, Il a réconcilié vos cœurs et vous êtes devenus, par Son bienfait, des frères » (3:103). Un musulman apprend que la foi fit d'anciens ennemis un seul peuple.",

"sira_126": "Le verset dit : « Le Prophète a plus de droit sur les croyants qu'ils n'en ont sur eux-mêmes, et ses épouses sont leurs mères » (33:6). La sourate al-Ahzâb s'adresse à elles directement, « Ô femmes du Prophète, vous n'êtes pas comme les autres femmes » (33:32), et interdit aux croyants de jamais les épouser après lui, appelant cela « une énormité auprès d'Allah » (33:53). Un musulman apprend à parler de Khadîja et de 'Âisha comme de ses mères, et à recevoir ce qu'elles ont transmis de la maison du Prophète ﷺ comme l'enseignement d'une mère.",

"sira_127": "Toutes les biographies s'accordent sur le fait que le Prophète ﷺ quitta La Mecque avec Abû Bakr en l'année correspondant à 622, se cacha trois jours dans la grotte de Thawr pendant que Quraysh le cherchait, et atteignit Médine. Le Coran rappelle la grotte : « lorsque ceux qui avaient mécru l'avaient chassé, deuxième de deux, quand ils étaient dans la grotte et qu'il disait à son compagnon : “Ne t'afflige pas ; Allah est avec nous” » (9:40). Un musulman apprend que son calendrier commença par un voyage fait dans la confiance.",

"sira_128": "Anas le raconte dans Sahîh al-Bukhârî 2048. Quand 'Abd ar-Rahmân ibn 'Awf arriva, le Prophète ﷺ le fit frère de Sa'd ibn ar-Rabî', qui lui offrit la moitié de ses biens. 'Abd ar-Rahmân demanda seulement qu'on lui montre le marché, et commerça avec profit. Plus tard il vint avec une trace de parfum jaune, s'étant marié pour le poids d'un noyau de datte en or, et le Prophète ﷺ lui dit de donner un repas de noces, ne serait-ce qu'avec un mouton. Un musulman apprend à accepter l'aide sans en vivre.",

"sira_129": "Ubayy ibn Ka'b relate dans Sahîh Muslim 810 que le Prophète ﷺ lui demanda : « Ô Abû al-Mundhir, sais-tu quel verset du Livre d'Allah est le plus grand ? » Ubayy répondit par le Verset du Trône, « Allah, nulle divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même » (2:255), qui dit ensuite que Son Kursî s'étend sur les cieux et la terre. Le Prophète ﷺ le frappa sur la poitrine et dit : « Que la science te soit agréable, Abû al-Mundhir. » Un musulman apprend à connaître ce verset et sa place.",

"sira_130": "Toutes les biographies rapportent que lorsque le Prophète ﷺ entra à Médine, les Ansâr le supplièrent de loger chez eux, et qu'il leur dit de laisser aller sa chamelle, car elle recevait des ordres. Elle avança jusqu'à s'agenouiller sur une aire de séchage appartenant à deux orphelins des Banû an-Najjâr. Bien qu'ils l'offrissent en don, il insista pour payer, et là fut construite la mosquée. Un musulman apprend que le Prophète ﷺ ne favorisa aucun clan et paya un juste prix même à des orphelins qui voulaient donner.",

"sira_131": "Les biographies rapportent trois fils : al-Qâsim et 'Abdullâh, tous deux nés de Khadîja, et Ibrâhîm, né à Médine de Mâriya ; chacun mourut dans la petite enfance. Ses quatre filles, Zaynab, Ruqayya, Umm Kulthûm et Fâtima, grandirent. Le Coran énonce l'issue : « Muhammad n'est le père d'aucun de vos hommes, mais le Messager d'Allah et le Sceau des Prophètes » (33:40). Un musulman apprend que le Prophète ﷺ connut le chagrin d'enterrer des enfants, et que son message fut porté plus loin sans fils.",

"sira_132": "Toutes les biographies s'accordent sur le fait que Zayd ibn Hâritha fut capturé enfant, fut donné par Khadîja au Prophète ﷺ, et que lorsque son père vint le chercher, Zayd choisit de rester. Le Prophète ﷺ l'affranchit et l'adopta ; on l'appela Zayd ibn Muhammad jusqu'à ce que le Coran mette fin à cette appellation : « Appelez-les du nom de leurs pères » (33:5). Il est le seul compagnon nommé dans le Coran (33:37) et tomba en commandant à Mu'ta. Un musulman apprend ce que peut être l'amour entre un maître et un affranchi.",

"sira_133": "Ibn 'Umar rapporte dans Sahîh al-Bukhârî 4469 que le Prophète ﷺ envoya une troupe sous le commandement d'Usâma ibn Zayd, et que lorsque des gens critiquèrent son commandement, il dit que ceux qui critiquaient Usâma avaient critiqué avant lui le commandement de son père ; que son père en avait été digne et était parmi les plus chers à son cœur ; et que celui-ci était parmi les plus chers à son cœur après lui. Usâma était très jeune, et son père avait commandé à Mu'ta. Un musulman apprend que le commandement se donne au mérite plutôt qu'à l'âge.",

"sira_134": "Toutes les biographies rapportent que Zamzam avait été comblée longtemps auparavant, et que 'Abd al-Muttalib en vit l'emplacement en rêve et la dégagea avec son fils unique, al-Hârith ; il tint ensuite la charge d'abreuver les pèlerins. Elles rapportent aussi son vœu de sacrifier un fils si Allah lui en donnait dix, et que lorsque le sort tomba sur 'Abdullâh, futur père du Prophète ﷺ, il fut racheté par cent chameaux. Un musulman apprend que le grand-père du Prophète ﷺ servit les pèlerins.",

"sira_135": "Toutes les biographies situent les musulmans à Badr à un peu plus de trois cents hommes, face à une armée de Quraysh de près de mille. Le Coran rapporte le déséquilibre : « Allah vous a déjà donné la victoire à Badr alors que vous étiez peu nombreux » (3:123), et promet un secours du ciel : « Ne vous suffit-il pas que votre Seigneur vous renforce de trois mille anges descendus ? » (3:124). Ceux qui étaient à Badr furent honorés toute leur vie. Un musulman apprend que la victoire ne se décide pas par le nombre.",

"sira_136": "Toutes les biographies rapportent que le Prophète ﷺ naquit à La Mecque en Rabî' al-Awwal, l'année de l'Éléphant, l'année où Abraha marcha avec un éléphant pour détruire la Ka'ba. Le Coran le rappelle : « N'as-tu pas vu comment ton Seigneur a agi envers les gens de l'Éléphant ? » (105:1). Son père 'Abdullâh était mort avant sa naissance, sa mère était Amina, et il fut allaité par Halîma. Un musulman apprend qu'Allah protégea la Maison l'année même où naquit son dernier Prophète ﷺ.",

"sira_137": "Les biographies s'accordent sur le fait que le Prophète ﷺ atteignit Médine en Rabî' al-Awwal et s'arrêta d'abord à Qubâ, où il fonda une mosquée, et qu'il entra dans la ville un vendredi, priant en chemin la première prière du vendredi. Le Coran parle de Qubâ comme d'« une mosquée fondée sur la piété dès le premier jour » (9:108). Chaque foyer des Ansâr souhaitait l'héberger. Un musulman apprend que la première chose que le Prophète ﷺ bâtit dans sa nouvelle demeure, avant toute maison pour lui-même, fut un lieu de prière.",

"sira_138": "Toutes les biographies rapportent que Quraysh rédigea un document les engageant à ne pas commercer ni se marier avec les Banû Hâshim et les Banû al-Muttalib jusqu'à ce qu'ils livrent Muhammad ﷺ, et le suspendit à l'intérieur de la Ka'ba. Abû Tâlib se retira avec tout le clan dans sa vallée hors de La Mecque, où ils souffrirent de la faim pendant environ trois ans. Cela prit fin quand des hommes de Quraysh qui en avaient honte firent déchirer le document, et on le trouva rongé sauf le nom d'Allah. Un musulman apprend que la patience dura plus longtemps que le pacte.",

"sira_139": "Toutes les biographies s'accordent sur le fait qu'après la première révélation le Prophète ﷺ ne parla de son message qu'à ses plus proches, et que les premiers à croire furent Khadîja, Abû Bakr, 'Alî et Zayd ibn Hâritha. Pendant environ trois ans, les croyants se réunirent discrètement dans la maison d'al-Arqam. Puis le Coran ordonna : « Expose donc clairement ce qu'on t'a commandé » (15:94), et « Et avertis tes proches les plus proches » (26:214). Un musulman apprend que l'appel grandit pas à pas, d'un cercle de confiance à toute la ville.",

"sira_140": "Ibn 'Abbâs relate dans Sahîh al-Bukhârî 3364 que lorsque l'eau fut épuisée et qu'Ismâ'îl pleura de soif, Hâjar monta sur as-Safâ pour chercher quelqu'un, redescendit, et dans la vallée releva son vêtement et courut comme une personne en détresse, puis monta sur al-Marwa. Elle fit cela sept fois, et le Prophète ﷺ dit que c'est pour cela que les pèlerins vont entre les deux. Le Coran dit : « As-Safâ et al-Marwa sont vraiment parmi les rites d'Allah » (2:158). Un musulman apprend que le sa'y de chaque pèlerin retrace la recherche d'une mère.",

"sira_141": "Abû Bakra relate dans Sahîh al-Bukhârî 2704 qu'il vit le Prophète ﷺ sur le minbar avec al-Hasan à côté de lui, disant : « Ce fils que voici est un sayyid, et il se peut qu'Allah réconcilie par lui deux grands groupes de musulmans. » Al-Hasan était le fils de 'Alî et de Fâtima, et ces mots furent dits devant toute l'assemblée. Le Coran fait de la paix entre croyants le devoir de tous (49:10). Un musulman apprend que le Prophète ﷺ plaçait la paix entre musulmans au-dessus du pouvoir.",

"sira_142": "Toutes les biographies rapportent que Fâtima était la plus jeune des filles du Prophète ﷺ, qu'elle épousa 'Alî à Médine, et que de ce mariage vinrent al-Hasan et al-Husayn, les petits-fils qu'il portait et avec qui il jouait. Elles rapportent aussi ses mots que Fâtima était une partie de lui, et qu'elle fut la seule de ses enfants à lui survivre, mourant environ six mois après lui. Un musulman apprend que la vie de famille du Prophète ﷺ fut faite de tendresse, et que sa descendance vient par une fille.",

"sira_143": "Toutes les biographies s'accordent sur le fait que Zaynab était mariée à son cousin Abû al-'Âs ibn ar-Rabî' et resta avec lui à La Mecque après l'Hégire. Quand il fut capturé à Badr, elle envoya en rançon un collier que Khadîja lui avait donné ; le Prophète ﷺ le reconnut, en fut ému, et le rendit et libéra son mari à condition que Zaynab rejoigne son père. Elle émigra à Médine, et Abû al-'Âs embrassa plus tard l'islam. Un musulman apprend combien le Prophète ﷺ aimait sa fille et honorait la mémoire de Khadîja.",

"sira_144": "Toutes les biographies rapportent que Bilâl ibn Rabâh était un esclave de La Mecque torturé par son maître pour avoir embrassé l'islam, qui répétait sans cesse « Ahad, Ahad » jusqu'à ce qu'Abû Bakr l'achète et l'affranchisse. À Médine, le Prophète ﷺ le choisit pour lancer l'appel à la prière, et le jour de la conquête de La Mecque, Bilâl monta sur le toit de la Ka'ba et lança l'adhân de là. Un musulman apprend que l'ancien esclave s'éleva jusqu'à appeler la communauté à la prière, et que le rang se mesure à la foi.",

"sira_145": "Sahîh al-Bukhârî 3661 rapporte les mots du Prophète ﷺ : s'il avait pris un ami intime parmi les hommes, ç'aurait été Abû Bakr, son frère et son compagnon. Le Coran réserve le mot khalîl au lien entre Ibrâhîm et son Seigneur, « Et Allah a pris Ibrâhîm pour khalîl » (4:125), et rappelle Abû Bakr comme « le deuxième de deux, quand ils étaient dans la grotte » (9:40). Un musulman apprend que nul ne fut plus proche du Prophète ﷺ qu'Abû Bakr, et que le lien le plus profond du cœur est gardé pour Allah.",

"sira_146": "Toutes les biographies rapportent que, comme Ibrâhîm avait déclaré La Mecque sanctuaire, le Prophète ﷺ déclara Médine sanctuaire entre ses deux étendues de pierres noires, et pria pour sa bénédiction. Le Coran appelle La Mecque « un sanctuaire sûr » (28:57) et nomme Médine de son ancien nom, Yathrib (33:13) ; le Prophète ﷺ l'appela Tayba. La Mecque abrite la Ka'ba, Médine sa mosquée et sa tombe, et ensemble elles sont al-Haramayn. Un musulman apprend à vénérer les deux : là où le Coran commença et là où la communauté fut bâtie.",

"sira_147": "Toutes les biographies s'accordent sur le fait qu'après l'Hégire le Prophète ﷺ fit le pèlerinage une fois, la dixième année, et qu'on l'appela le pèlerinage d'adieu parce qu'il mourut quelques mois plus tard. À 'Arafat, il s'adressa aux gens, leur rappelant que leurs vies et leurs biens étaient sacrés, et là descendit le verset : « Aujourd'hui, J'ai parachevé pour vous votre religion et accompli sur vous Mon bienfait » (5:3). Un musulman apprend que le Hajj qu'il accomplit aujourd'hui suit l'unique Hajj que le Prophète ﷺ dirigea.",

"sira_148": "Anas relate dans Sahîh al-Bukhârî 3149 que, marchant avec le Prophète ﷺ, qui portait un manteau à la bordure rugueuse, un bédouin le saisit et tira si fort qu'il marqua l'épaule du Prophète ﷺ. L'homme dit : « Ô Muhammad, ordonne qu'on me donne des biens d'Allah. » Le Prophète ﷺ se tourna, rit, et ordonna qu'on lui fasse un don. Le Coran dit : « Et tu es certes d'un caractère immense » (68:4). Un musulman apprend que le Prophète ﷺ répondit à la grossièreté par un sourire et la générosité.",

"sira_149": "Le Coran ouvre la sourate al-Isrâ' par le voyage : « Gloire à Celui qui, de nuit, fit voyager Son serviteur d'al-Masjid al-Harâm à al-Masjid al-Aqsâ, dont Nous avons béni les alentours, afin de lui montrer certains de Nos signes » (17:1). Toutes les biographies rapportent que le Prophète ﷺ fut transporté cette nuit-là de La Mecque à Jérusalem et élevé à travers les cieux, où les cinq prières furent prescrites. Quraysh se moqua de lui, et Abû Bakr le crut aussitôt. Un musulman apprend que Jérusalem est liée à sa prière dès le commencement.",

"sira_150": "Toutes les biographies s'accordent sur le fait que le Prophète ﷺ mourut à soixante-trois ans : quarante avant la révélation, treize à La Mecque, dix à Médine. Il mourut en Rabî' al-Awwal dans la chambre de 'Âisha. Abû Bakr affermit la communauté en récitant : « Muhammad n'est qu'un messager ; des messagers sont passés avant lui. S'il mourait ou était tué, retourneriez-vous sur vos talons ? » (3:144). Un musulman apprend que son amour pour le Prophète ﷺ repose sur l'adoration d'Allah, qui ne meurt pas.",
}
