"""Français — détails, virtues_c (50 questions)."""

D = {
"virtues_051": "Le verset est le dernier des conseils que Luqmân donne à son fils dans la sourate Luqmân : « Sois modeste dans ta démarche et baisse ta voix ; la plus détestée des voix est bien la voix des ânes » (31:19). Juste avant, il lui a dit de ne pas détourner son visage des gens par mépris ni de marcher sur la terre avec insolence, « car Allah n'aime pas tout présomptueux plein de gloriole » (31:18). Ses conseils descendent de la foi en Allah seul (31:13) jusqu'aux habitudes de la marche et de la parole. Un musulman apprend qu'une voix posée et un pas mesuré font partie du bon caractère.",

"virtues_052": "Les conseils de Luqmân à son fils dans la sourate Luqmân se ferment sur un verdict qui porte sur l'ensemble : « Cela fait partie des bonnes résolutions » (31:17). Le verset juste avant a dit à l'enfant que même une œuvre du poids d'un grain de moutarde, cachée dans un rocher, dans les cieux ou dans la terre, Allah la fera venir (31:16). La prière, le commandement du convenable, l'interdiction du blâmable et la patience sont ainsi posés sur cette certitude : rien de ce qui est fait n'est perdu. Un musulman apprend que la prière vient d'abord, que le souci du bien des autres la suit, et que la patience fait tenir l'une et l'autre.",

"virtues_053": "Le verset décrit les gens pour qui le Paradis est préparé : celui qui le précède appelle les croyants à « courir vers le pardon de votre Seigneur et vers un jardin large comme les cieux et la terre, préparé pour les pieux » (3:133), et 3:134 les nomme par leurs actes. Le verset suivant ajoute un quatrième trait : quand ils se font du tort à eux-mêmes, ils se rappellent Allah, demandent pardon et ne persistent pas sciemment (3:135). La générosité, la colère contenue, le pardon et le repentir sont placés côte à côte comme un seul caractère. Un musulman apprend que retenir sa colère et pardonner aux gens sont de bonnes œuvres qu'Allah aime.",

"virtues_054": "Le verset se termine par deux noms d'Allah : « Une parole agréable et un pardon valent mieux qu'une aumône suivie d'un tort. Allah Se suffit à Lui-même et Il est Indulgent » (2:263). Il se trouve dans un passage de la sourate Al-Baqara sur la dépense : le verset précédent promet la récompense de ceux qui donnent puis ne font pas suivre leur don de rappels ni de tort (2:262), et le verset suivant dit aux croyants de ne pas annuler leurs aumônes par des rappels et des torts (2:264). Un musulman apprend qu'un don se mesure à la manière dont il est fait, et qu'un refus doux vaut plus qu'un don qui blesse.",

"virtues_055": "Le verset poursuit en disant ce que l'aumône secrète fait pour celui qui donne : « et Il effacera une partie de vos méfaits. Allah est bien informé de ce que vous faites » (2:271). Le verset précédent a dit que tout ce qu'une personne dépense ou voue, Allah le sait (2:270), et le verset suivant ajoute que tout bien dépensé l'est pour l'âme même de celui qui donne et lui sera rendu intégralement (2:272). Le don caché aux pauvres est déclaré meilleur et rattaché à l'effacement des péchés. Un musulman apprend à donner sans public, en se fiant à Celui qui voit.",

"virtues_056": "Le verset s'ouvre sur ce qu'il faut donner avant de nommer ce qu'il ne faut pas donner : « Ô les croyants ! Dépensez des meilleures choses que vous avez gagnées et de ce que Nous avons fait sortir de la terre pour vous » (2:267), et il se ferme sur « Et sachez qu'Allah Se suffit à Lui-même et qu'Il est digne de louange ». Le verset suivant nomme la peur qui se cache derrière un don mesquin : « Shaytân vous menace de pauvreté et vous commande la turpitude, mais Allah vous promet un pardon de Sa part et une grâce » (2:268). Un musulman apprend à donner de ce qui est bon entre ses mains, et à répondre à la peur de la pauvreté par la confiance en la promesse d'Allah.",

"virtues_057": "Le verset continue : « Et quoi que vous dépensiez, Allah le sait » (3:92). Il vient juste après un verset sur ceux qui meurent dans la mécréance, de qui une terre pleine d'or ne serait pas acceptée comme rançon (3:91) : l'or offert trop tard n'achète rien, tandis qu'une chose aimée, donnée maintenant pour Allah, atteint la piété elle-même. La sourate Al-Baqara compte le fait de donner ses biens, malgré l'amour qu'on leur porte, aux proches, aux orphelins et aux nécessiteux parmi les marques des vrais pieux (2:177). Un musulman apprend que donner ce qui ne lui coûte rien n'est pas encore le don que le Coran loue.",

"virtues_058": "L'image appartient à une suite de conseils de la sourate Al-Isrâ. Deux versets plus tôt, le croyant est invité à donner au proche, au pauvre et au voyageur leur dû et à ne pas gaspiller, « car les gaspilleurs sont les frères des diables » (17:27) ; le verset juste avant dit que si l'on n'a rien à donner, on doit au moins dire une parole douce (17:28). Viennent ensuite la main enchaînée au cou, la main ouverte tout entière, et la fin de l'une comme de l'autre : se retrouver « blâmé et dénué » (17:29). Un musulman apprend que la générosité a deux bords à éviter, l'avarice et le gaspillage.",

"virtues_059": "Le verset est une ligne du portrait des « serviteurs du Tout Miséricordieux » à la fin de la sourate Al-Furqân. Le portrait s'ouvre sur leur démarche et leur parole : ils « marchent humblement sur la terre, et quand les ignorants s'adressent à eux, ils disent des paroles de paix » (25:63) ; il se poursuit avec leurs nuits passées prosternés et debout (25:64). Puis leur dépense est décrite (25:67), et le verset suivant se tourne vers ce qu'ils ne font jamais : invoquer un autre dieu, ôter une vie injustement ou commettre la fornication (25:68). Un musulman apprend que sa manière de gérer l'argent appartient au même portrait que sa manière de prier et de parler.",

"virtues_060": "Le verset se termine par sa raison : « Cela est meilleur pour vous, afin que vous vous souveniez » (24:27). Il ouvre un court passage de la sourate An-Nûr sur la maison : le verset suivant dit que si l'on n'y trouve personne, on n'entre pas avant d'en avoir reçu la permission, et que si l'on vous dit de repartir, on repart, « cela est plus pur pour vous » (24:28) ; le verset d'après excuse l'entrée dans des bâtiments inhabités où l'on a quelque affaire (24:29). Un musulman apprend qu'une maison est un espace protégé, et que demander la permission et saluer au seuil font partie de la bonne manière d'y entrer.",

"virtues_061": "L'explication donne la seconde moitié du verset ; la première traite d'une maison où personne ne répond : « Et si vous n'y trouvez personne, n'y entrez pas avant qu'on ne vous en donne la permission » (24:28). Vient ensuite l'ordre de partir quand on le demande, et le verset se ferme : « Et Allah sait bien ce que vous faites ». Le verset précédent a posé la règle pour toute maison qui n'est pas la sienne : ne pas entrer avant de demander la permission et de saluer ses habitants (24:27). Un refus à la porte est un droit de la maisonnée, non un affront. Un musulman apprend à repartir sans se vexer quand il n'est pas reçu.",

"virtues_062": "Le verset se trouve dans la sourate Al-Hujurât, une sourate de bonnes manières pour la communauté des croyants, après des versets sur le fait de baisser la voix devant le Prophète ﷺ (49:2-5) et avant l'ordre de faire la paix entre des croyants qui se combattent (49:9). Le verset qui le suit rappelle aux croyants que le Messager d'Allah est parmi eux et que, s'il suivait leurs désirs en bien des affaires, ils tomberaient dans la difficulté (49:7). Le raisonnement de 49:6 est dans le verset lui-même : une nouvelle acceptée sans vérification peut nuire à des innocents, et le regret vient trop tard. Un musulman apprend à s'arrêter devant une rumeur et à peser celui qui l'apporte.",

"virtues_063": "Le verset poursuit en donnant une image à la médisance : « L'un de vous aimerait-il manger la chair de son frère mort ? Vous en auriez horreur. Et craignez Allah ; Allah accueille le repentir et Il est Miséricordieux » (49:12). Le verset précédent a interdit de se moquer des autres, de s'insulter les uns les autres et de donner aux gens des sobriquets offensants (49:11), et le verset suivant dit qu'Allah a fait des peuples et des tribus pour qu'ils se connaissent les uns les autres (49:13). Le soupçon, l'espionnage et la médisance sont trois pas d'un même chemin, chacun nourrissant le suivant. Un musulman apprend à garder l'honneur d'un frère absent comme il garderait son corps.",

"virtues_064": "Le verset comble ce que les points de suspension de l'explication laissent de côté : si l'un des deux groupes fait du tort à l'autre, les croyants prennent parti contre celui qui fait le tort « jusqu'à ce qu'il revienne à l'ordre d'Allah », et c'est alors seulement que la paix est faite « entre eux avec justice » (49:9). Le verset suivant donne la raison pour laquelle toute la communauté est concernée : « Les croyants ne sont que des frères ; faites donc la paix entre vos frères, et craignez Allah, afin qu'on vous fasse miséricorde » (49:10). La réconciliation n'est donc pas le silence sur le tort, mais un règlement qui le répare. Un musulman apprend que la paix entre croyants doit être juste pour durer.",

"virtues_065": "Le verset s'ouvre sur un ordre qui encadre celui qui est cité : « Ô les croyants ! Soyez fermes pour Allah, témoins en toute équité » (5:8), et il se ferme sur « Et craignez Allah ; Allah est bien informé de ce que vous faites ». Plus tôt dans la même sourate, les croyants sont invités à ne pas laisser leur haine pour un peuple qui les avait écartés de la Mosquée sacrée les pousser à transgresser (5:2), de sorte que la mise en garde contre la haine est donnée deux fois dans la sourate Al-Mâ'ida. Un musulman apprend que l'aversion pour une personne, si forte soit-elle, n'excuse jamais de la traiter injustement, et que l'équité envers un ennemi est proche de la crainte d'Allah.",

"virtues_066": "Le verset continue au-delà des noms qu'il énumère : « Qu'il s'agisse d'un riche ou d'un pauvre, Allah a plus de droit sur eux deux. Ne suivez donc pas la passion, de peur de dévier de la justice. Et si vous déformez votre témoignage ou refusez de le donner, Allah est bien informé de ce que vous faites » (4:135). Trois forces qui tirent sur un témoin sont nommées : l'amour de soi et des siens, la crainte ou la pitié devant la richesse et la pauvreté, et la passion tout court. La sourate Al-Mâ'ida donne le miroir de ce verset, où la force qui tire est la haine plutôt que l'amour (5:8). Un musulman apprend que le témoignage véridique est dû d'abord à Allah, et que la parenté ne peut le faire plier.",

"virtues_067": "Le verset se ferme sur l'éloge de sa propre instruction : « Qu'il est excellent, ce à quoi Allah vous exhorte. Allah est Celui qui entend et qui voit » (4:58). Le verset suivant se tourne vers l'autre côté de la relation, disant aux croyants d'obéir à Allah, au Messager et à ceux qui détiennent l'autorité parmi eux (4:59) : les dépôts sont restitués et le jugement rendu avec équité par ceux qui portent la responsabilité, et l'obéissance est due par ceux qui sont sous elle. La sourate Al-Mu'minûn compte la garde des dépôts parmi les marques des croyants qui réussissent (23:8). Un musulman apprend que tout ce qui est placé entre ses mains, un objet, un secret ou une charge, doit parvenir à son propriétaire.",

"virtues_068": "Le verset commence par l'adoration d'Allah seul et se termine par un avertissement : « Allah n'aime pas le présomptueux, l'arrogant » (4:36). Le verset suivant les décrit : ceux qui sont avares, qui commandent l'avarice aux autres et qui cachent ce qu'Allah leur a donné de Sa grâce (4:37). La longue liste des personnes à qui la bonté est due est ainsi bordée d'un côté par le tawhid et de l'autre par l'arrogance jointe à l'avarice. Un musulman apprend que la bienfaisance s'élargit en cercles, depuis la maison jusqu'à l'étranger sur la route.",

"virtues_069": "Le verset se termine par une formule que l'explication laisse de côté : « si vous saviez » (2:280). Il suit les versets qui interdisent l'usure et disent aux croyants d'abandonner ce qui en reste, en ne reprenant que leur capital, « ainsi vous ne léserez personne et vous ne serez pas lésés » (2:279) ; et il est suivi d'un appel à craindre le Jour où chaque âme sera payée intégralement (2:281). Le créancier apprend que son droit est réel et que sa miséricorde vaut mieux que son droit. Un musulman apprend à traiter un débiteur en difficulté avec patience, et à voir dans une dette remise un don placé auprès d'Allah.",

"virtues_070": "Le verset poursuit en disant comment l'écrit se fait : un scribe écrit « avec équité », celui qui doit la dette dicte et craint Allah, et deux témoins sont appelés (2:282). Il dit aux croyants de ne pas se lasser d'écrire une dette, « petite ou grande, jusqu'à son terme », et en donne la raison : « cela est plus équitable auprès d'Allah, plus droit pour le témoignage et plus à même d'écarter le doute entre vous » (2:282). Un musulman apprend que des écrits clairs protègent les deux parties et font partie de la crainte d'Allah dans les transactions.",

"virtues_071": "Le verset se termine sur des mots que l'explication omet : « alors que vous savez » (2:188), de sorte que le tort qu'il décrit est commis sciemment. Il se trouve juste après les versets de la sourate Al-Baqara sur le jeûne de Ramadan, qui se ferment sur « voilà les limites d'Allah, ne vous en approchez pas » (2:187), et avant un verset sur les nouvelles lunes comme repères du temps et du pèlerinage (2:189). La sourate An-Nisâ répète l'interdiction et donne à sa place la voie licite : le commerce par consentement mutuel (4:29). Un musulman apprend que le bien pris par fraude ou en achetant un juge n'est pas à lui, quelque légal qu'il paraisse.",

"virtues_072": "Le verset se ferme sur un jugement sans appel : « C'est vraiment un grand péché » (4:2). La sourate An-Nisâ revient sur la question quelques versets plus loin, disant aux tuteurs d'éprouver les orphelins jusqu'à ce qu'ils atteignent l'âge du mariage et, une fois qu'on voit en eux un jugement sain, de leur remettre leurs biens, sans les dilapider ni se hâter de les dépenser avant qu'ils ne grandissent (4:6). Elle donne ensuite l'image la plus dure : ceux qui dévorent injustement les biens des orphelins « ne font qu'avaler du feu dans leurs ventres » (4:10). Un musulman apprend que le bien d'un orphelin est un dépôt à garder intact et à rendre.",

"virtues_073": "L'ordre vient parmi les conseils de la sourate Al-Isrâ, juste après celui de ne toucher aux biens de l'orphelin que de la meilleure manière et de remplir tout engagement, « car on sera interrogé sur l'engagement » (17:34), et juste avant la mise en garde contre le fait de suivre ce dont on n'a pas connaissance (17:36). La sourate Al-Mutaffifîn montre la faute dont le verset protège : des gens qui exigent la pleine mesure quand ils achètent mais donnent moins quand ils vendent (83:1-3). Des balances honnêtes sont ce qu'il y a de « mieux, et le résultat en est meilleur » (17:35). Un musulman apprend que l'exactitude à donner aux autres leur dû est une forme d'adoration.",

"virtues_074": "Le verset suit l'ordre de donner la pleine mesure et de peser avec équité (17:35) et précède la mise en garde contre la marche orgueilleuse sur la terre (17:37), de sorte qu'il se tient entre l'honnêteté dans le commerce et l'humilité dans le maintien. Il compte trois facultés, l'ouïe, la vue et le cœur, et dit de chacune qu'elle sera interrogée (17:36) : ce qu'une personne écoute, regarde et croit relève entièrement de sa responsabilité. Le passage se ferme sur les mots « tout cela, son mal est détestable auprès de ton Seigneur » (17:38). Un musulman apprend à ne pas répéter ce qu'il n'a pas vérifié et à ne pas accuser sur une supposition.",

"virtues_075": "Le verset ramène l'orgueil à une simple question de taille : un homme qui se pavane ne peut fendre le sol sous ses pieds ni grandir jusqu'à la hauteur des montagnes qui l'entourent (17:37), et le passage se ferme ensuite : « Tout cela, son mal est détestable auprès de ton Seigneur » (17:38). Luqmân donne à son fils le même conseil : ne marche pas sur la terre avec insolence, « Allah n'aime pas tout présomptueux plein de gloriole » (31:18) ; et « les serviteurs du Tout Miséricordieux » sont d'abord décrits comme ceux qui « marchent humblement sur la terre » (25:63). Un musulman apprend à se tenir avec modestie, parce que son propre corps lui montre combien il est petit.",

"virtues_076": "La promesse se termine par son troisième don : « Et quiconque obéit à Allah et à Son Messager obtient certes un grand succès » (33:70-71). Les deux versets viennent juste après que les croyants ont été invités à ne pas être comme ceux qui ont offensé Mûsâ, qu'Allah a ensuite innocenté de ce qu'ils disaient (33:69), et juste avant le verset sur le Dépôt que les cieux, la terre et les montagnes ont refusé de porter et que l'homme a pris sur lui (33:72). La parole droite est ainsi placée entre le mal de la calomnie et le poids de la responsabilité. Un musulman apprend que choisir des mots droits et vrais est une porte par laquelle ses autres œuvres sont réformées.",

"virtues_077": "L'ordre est donné à Mûsâ et à son frère Hârûn quand ils sont envoyés à Pharaon : « Allez vers Pharaon, tous deux ; il s'est vraiment rebellé » (20:43), puis vient l'instruction d'employer des paroles douces, « afin qu'il se rappelle ou qu'il craigne » (20:44). Tous deux répondent qu'ils craignent qu'il ne s'emporte contre eux ou ne dépasse les bornes, et Allah répond : « Ne craignez rien. Je suis avec vous deux ; J'entends et Je vois » (20:46). La parole douce leur est demandée au moment même où ils se sentent le plus menacés. Un musulman apprend que la douceur dans les mots est une stratégie de la vérité, non un signe de faiblesse.",

"virtues_078": "Le verset réunit trois choses en une seule personne : un appel à Allah, une vie droite et une appartenance déclarée à l'islam (41:33). Les versets qui suivent montrent comment un tel prédicateur se comporte quand on s'oppose à lui : « Repousse le mal par ce qui est meilleur, et voilà que celui avec qui tu avais une inimitié devient comme un ami chaleureux » (41:34), et la sourate ajoute que cela n'est accordé qu'aux endurants, à « celui qui a une grande part » (41:35). Un musulman apprend qu'inviter les autres vers Allah se fait autant par le caractère que par les mots.",

"virtues_079": "Le verset est le troisième d'une liste qui ouvre la sourate Al-Mu'minûn : « Bienheureux sont certes les croyants, ceux qui sont humbles dans leur prière » (23:1-2), « et qui se détournent des futilités » (23:3). La liste continue avec le versement de la zakat (23:4), la garde de la chasteté (23:5), le respect des dépôts et des engagements (23:8) et la garde des prières (23:9), et se termine par la promesse que ceux-là hériteront du Firdaws pour toujours (23:10-11). Le détournement du laghw est placé entre l'humilité dans la prière et la générosité avec les biens. Un musulman apprend à dépenser sa langue et son temps pour ce qui a du poids.",

"virtues_080": "Le verset (23:8) appartient à la liste des traits qui ouvre la sourate Al-Mu'minûn, après l'humilité dans la prière (23:2), le détournement des futilités (23:3), le versement de la zakat (23:4) et la garde de la chasteté (23:5), et juste avant la garde des prières (23:9) ; la liste se termine par l'héritage du Firdaws (23:10-11). Les mêmes mots, « ceux qui veillent sur leurs dépôts et leur engagement », reviennent dans la sourate Al-Ma'ârij, dans une seconde liste de ceux qui seront honorés dans des jardins (70:32). La sourate An-Nisâ donne l'ordre qui se trouve derrière ce trait : restituer les dépôts à leurs ayants droit (4:58). Un musulman apprend qu'une promesse donnée et une chose confiée sont des dettes de la foi.",

"virtues_081": "Le verset se ferme sur des mots que l'explication omet : « Il n'aime pas les injustes » (42:40). Il se trouve dans un passage de la sourate Ash-Shûrâ qui décrit d'abord les croyants qui se défendent quand la tyrannie les frappe (42:39), puis autorise une riposte mesurée à l'identique, puis dit que celui qui reprend son dû après avoir été lésé n'encourt aucun blâme (42:41). Ayant accordé le droit, le passage se termine : « Et celui qui endure et pardonne, cela fait partie des bonnes résolutions » (42:43). Un musulman apprend qu'il peut répondre à un tort dans la mesure de ce tort, et que le laisser aller est la voie la plus haute.",

"virtues_082": "Le verset commence par les gens auxquels il s'adresse : « Que les détenteurs de grâce et d'aisance parmi vous ne jurent pas de ne plus donner à leurs proches, aux nécessiteux et à ceux qui ont émigré dans le sentier d'Allah » (24:22). Il vient à la fin du passage de la sourate An-Nûr sur la calomnie que le Coran appelle un mensonge et « une énorme calomnie », et dont il menace de châtiment ceux qui la propagent (24:11-16). L'argument en faveur du pardon est retourné vers ceux qui donnent eux-mêmes : leur propre espoir d'être pardonnés. Un musulman apprend à mesurer le pardon qu'il accorde aux autres au pardon qu'il demande à Allah.",

"virtues_083": "Le verset s'adresse au Prophète ﷺ vers la fin de la sourate Al-A'râf, après des versets sur ceux qu'on invoque en dehors d'Allah et qui ne peuvent ni secourir ni entendre (7:197-198). Sa troisième consigne, s'écarter des ignorants (7:199), est aussitôt suivie de ce qu'il faut faire quand la provocation vient de l'intérieur : « Et si une suggestion de Shaytân t'atteint, cherche refuge auprès d'Allah ; Il entend tout et sait tout » (7:200). Un musulman apprend à accepter ce que les gens parviennent à donner et à ne pas se quereller avec la sottise.",

"virtues_084": "Le verset s'ouvre sur une phrase que l'explication laisse de côté : « Vous serez certes éprouvés dans vos biens et dans vos personnes » (3:186), et il nomme deux sources de paroles blessantes, ceux qui ont reçu le Livre auparavant et ceux qui donnent des associés à Allah. Il suit le verset qui dit que toute âme goûtera la mort et que la vie de ce monde n'est que jouissance trompeuse (3:185). Une seule réponse est donnée pour les trois épreuves. Un musulman apprend à s'attendre à l'insulte quand il tient à sa foi, et à l'accueillir avec patience plutôt que de la rendre.",

"virtues_085": "Le verset ferme le passage de la sourate Ash-Shûrâ sur la réponse au tort. Le passage affirme d'abord que les croyants se défendent quand la tyrannie les frappe (42:39), fixe la limite d'un mal rendu seulement par son pareil, et promet que celui qui pardonne et réconcilie a sa récompense auprès d'Allah (42:40) ; il ajoute que celui qui reprend son dû après avoir été lésé n'est pas à blâmer (42:41). Vient alors 42:43, qui place la patience et le pardon au-dessus de ce qui est simplement permis. La même formule qualifie le conseil de patience que Luqmân donne à son fils (31:17). Un musulman apprend que pardonner n'est pas une faiblesse, mais le choix le plus dur et le plus résolu.",

"virtues_086": "Le verset suivant dit qui sont les humbles : « ceux qui sont certains de rencontrer leur Seigneur et de retourner à Lui » (2:46). L'ordre de 2:45 s'adresse, dans cette première partie de la sourate Al-Baqara, aux Enfants d'Israël, juste après qu'on leur a demandé comment ils peuvent commander la piété aux autres en s'oubliant eux-mêmes, alors qu'ils récitent le Livre (2:44). Le même couple est donné plus loin aux croyants : « Ô les croyants ! Cherchez secours dans l'endurance et la prière ; Allah est avec les endurants » (2:153). Un musulman apprend que ce qui rend la prière légère, c'est la certitude de rencontrer son Seigneur.",

"virtues_087": "Le verset commence par la chose difficile dont il parle : « Le combat vous a été prescrit alors qu'il vous est désagréable » (2:216). Le verset ne prétend pas que le fardeau soit agréable ; il dit seulement que l'aversion des croyants n'est pas la mesure de ce qui est bon pour eux, et il se termine en opposant la science d'Allah à la leur. La sourate An-Nisâ applique le même raisonnement à une épouse que l'on en est venu à ne plus aimer, en qui Allah peut placer un grand bien (4:19). Un musulman apprend à accepter ce qu'Allah a décrété ou ordonné sans supposer que ce qui pèse est nuisible.",

"virtues_088": "La promesse se poursuit au-delà des deux dons nommés : « Et quiconque place sa confiance en Allah, Il lui suffit. Allah atteint ce qu'Il Se propose ; Allah a assigné une mesure à toute chose » (65:2-3). Ces mots viennent au milieu des prescriptions de la sourate At-Talâq sur le divorce et le délai d'attente, un temps de tension dans un foyer, et la sourate répète le schéma : quiconque craint Allah, Il lui facilite son affaire (65:4), efface ses méfaits et lui agrandit sa récompense (65:5). L'issue est ainsi promise précisément là où la porte semble fermée. Un musulman apprend à s'en tenir à la taqwa et à la confiance dans les passages difficiles.",

"virtues_089": "Le verset donne sa raison avant l'ordre : « Nous avons commandé à l'homme la bonté envers ses père et mère ; sa mère l'a porté, faiblesse sur faiblesse, et son sevrage a lieu à deux ans » (31:14). Il est placé au sein des conseils de Luqmân à son fils, et le verset suivant en fixe la limite : si les parents pressent leur enfant d'associer à Allah ce dont il n'a aucune connaissance, il ne leur obéit pas, mais leur tient compagnie ici-bas avec bonté (31:15). Un musulman apprend que la reconnaissance envers Allah et la reconnaissance envers les parents se disent dans un même souffle parce que la seconde fait partie de la première.",

"virtues_090": "Le verset s'ouvre sur le devoir et se ferme sur le compte à rendre : « Nous avons commandé à l'homme la bonté envers ses père et mère » et, après la limite, « C'est vers Moi que sera votre retour, et Je vous informerai de ce que vous faisiez » (29:8). La sourate Luqmân énonce la même limite et ajoute comment l'enfant traite encore de tels parents : il ne leur obéit pas en cela, mais les accompagne ici-bas avec bonté (31:15). Un musulman apprend que l'autorité d'un parent est réelle et large, et qu'elle ne s'arrête que là où commence le droit d'Allah.",

"virtues_091": "La prière est mise dans la bouche d'un homme à un moment précis de la vie : quand il atteint sa pleine force et quarante ans, dit le verset, il la prononce (46:15), et elle se termine par des mots que l'explication laisse de côté : « Je me repens à Toi et je suis du nombre des soumis ». Avant la prière, le verset rappelle la mère qui l'a porté avec peine et mis au monde avec peine, trente mois de grossesse et de sevrage. Le verset suivant répond : de telles personnes, le meilleur de leurs œuvres est accepté et leurs méfaits sont passés sous silence (46:16). Un musulman apprend une prière qui lie trois générations : ses parents, lui-même et ses enfants.",

"virtues_092": "Cette prière est le dernier trait du portrait des « serviteurs du Tout Miséricordieux » dans la sourate Al-Furqân, et le verset suivant donne leur récompense : « Ceux-là auront pour récompense le lieu le plus élevé, pour ce qu'ils ont enduré, et ils y seront accueillis avec un salut et une paix » (25:75). Juste avant la prière, les serviteurs sont décrits comme ceux qui, lorsqu'on leur rappelle les versets de leur Seigneur, ne tombent pas dessus sourds et aveugles (25:73) ; leur demande de bonnes familles suit leur propre attention à la révélation (25:74). Un musulman apprend à prier pour sa maisonnée et à la vouloir pieuse, et pas seulement heureuse.",

"virtues_093": "Le verset suit les péchés les plus graves que les serviteurs du Tout Miséricordieux évitent, associer un autre dieu à Allah, tuer injustement et la fornication (25:68), et la promesse que pour ceux qui se repentent, croient et font le bien, Allah remplace leurs mauvaises actions par de bonnes (25:70). Puis deux choses plus petites sont nommées : ils ne portent pas de faux témoignage, et lorsqu'ils passent auprès d'une futilité, ils passent avec dignité (25:72). Un musulman apprend à passer devant ce qui ne mérite pas son attention sans mépris et sans s'y joindre.",

"virtues_094": "Le verset poursuit avec une seconde courtoisie et une promesse : « Et quand on vous dit de vous lever, levez-vous ; Allah élèvera en degrés ceux d'entre vous qui ont cru et ceux qui ont reçu le savoir. Et Allah est bien informé de ce que vous faites » (58:11). Les versets qui le précèdent traitent des entretiens privés dans une assemblée, disant aux croyants de ne pas se concerter en secret sur le péché et l'hostilité, mais sur la bonté et la taqwa (58:9). Faire de la place reçoit pour réponse qu'Allah fait de la place, et se lever quand on le demande, qu'Allah élève en rang. Un musulman apprend que les petites courtoisies d'une assemblée sont remarquées par Allah et récompensées en retour.",

"virtues_095": "L'ordre vient à la fin d'un récit de pardon dans la sourate At-Tawba : Allah a accueilli le repentir du Prophète ﷺ et de ceux qui l'ont suivi à l'heure de la difficulté (9:117), et celui de trois hommes qui avaient été laissés en arrière, jusqu'à ce que la terre, malgré son étendue, se resserre sur eux et qu'ils sachent qu'il n'y a de refuge contre Allah qu'auprès de Lui (9:118). Le verset suivant dit alors aux croyants de craindre Allah et d'être avec les véridiques (9:119). Un musulman apprend à choisir sa compagnie d'après l'honnêteté, et à être compté parmi ceux qui disent la vérité.",

"virtues_096": "Le verset continue avec ce que le Prophète ﷺ ne doit pas faire : laisser ses yeux se détacher de ces gens « en désirant la parure de la vie de ce monde », ou obéir à celui « dont Nous avons rendu le cœur inattentif à Notre rappel, qui suit sa passion et dont l'affaire est toute négligence » (18:28). Le verset suivant laisse à chacun son choix : « La vérité vient de votre Seigneur ; quiconque le veut, qu'il croie, et quiconque le veut, qu'il mécroie » (18:29). Un musulman apprend à rechercher ceux qui se rappellent Allah et à rester avec eux, quel que soit leur rang.",

"virtues_097": "L'ordre vient à la fin du deuxième verset de la sourate Al-Mâ'ida, juste après que les croyants ont été invités à ne pas laisser la haine pour un peuple qui les avait autrefois écartés de la Mosquée sacrée les pousser à la transgression, et juste avant sa mise en garde finale : « Et craignez Allah ; Allah est dur en punition » (5:2). Le verset s'ouvre sur le respect des rites d'Allah et des pèlerins qui se dirigent vers la Maison sacrée, de sorte que l'entraide est demandée à des gens à qui l'on vient de rappeler un vieux grief. Un musulman apprend à se demander, avant de se joindre à quelque effort, si c'est le bien ou le mal qu'il aide à bâtir.",

"virtues_098": "Le verset donne la raison pour laquelle ses serments engagent : « alors que vous avez pris Allah pour garant contre vous. Allah sait ce que vous faites » (16:91). Il suit le verset dans lequel Allah commande la justice, la bienfaisance et le don aux proches, et interdit la turpitude, le mal et l'oppression (16:90), et il est suivi de l'image de celui qui rompt son serment : une femme qui défait son fil après l'avoir solidement filé, en prenant les serments comme moyen de tromperie entre les gens (16:92). Un musulman apprend qu'une promesse jurée au nom d'Allah se tient parce qu'Allah a été appelé à en témoigner.",

"virtues_099": "Le hadith est rapporté par Anas ibn Mâlik et consigné dans Sahih al-Bukhari 13, dans le Livre de la foi, sous un titre de chapitre qui énonce qu'aimer pour son frère ce que l'on aime pour soi-même fait partie de la foi. La formulation est une négation : la foi n'est pas complète sans cela. Le Coran donne le fondement de cette fraternité, « les croyants ne sont que des frères » (49:10), et loue les Ansâr qui ont donné la préférence aux autres sur eux-mêmes même dans le besoin (59:9). Un musulman apprend à éprouver sa foi par une seule question : veut-il pour les autres le bien qu'il veut pour lui-même ?",

"virtues_100": "Le verset se termine par une condition et une promesse : « Et quiconque fait cela en recherchant l'agrément d'Allah, Nous lui donnerons une énorme récompense » (4:114). Il vient dans un passage de la sourate An-Nisâ sur des gens qui se cachent des autres mais non d'Allah, qui est avec eux quand ils passent la nuit en des propos qu'Il n'agrée pas (4:108), et il transforme leurs conversations secrètes en épreuve : le chuchotement ne vaut rien sauf lorsqu'il sert une aumône, une bonne action ou la paix entre les gens. Un musulman apprend à se demander à quoi sert une conversation privée, et à s'assurer qu'elle sert le bien des gens.",
}
