"""Prophets — part A (prophets_033 … prophets_090).

Every entry is a fact stated explicitly in the Qur'an (sūrah:āyah) or,
for a handful, in Ṣaḥīḥ al-Bukhārī / Ṣaḥīḥ Muslim. The correct answer is
always written first; the game shuffles the order at draw time.
"""


def register(add, L):
    Q = "Quran"

    add("prophets_033", "prophets", "easy", "quran", Q, "38:71", False,
        fr=L("De quoi Allah a-t-Il créé Âdam, selon le Coran ?",
             ["D'argile", "De lumière", "De feu", "D'eau"], 0,
             "Allah dit aux anges : « Je vais créer d'argile un être humain. »",
             "Coran — Sourate Sâd, 38:71"),
        en=L("According to the Quran, from what did Allah create Adam?",
             ["From clay", "From light", "From fire", "From water"], 0,
             "Allah told the angels: \"I am going to create a human being from clay.\"",
             "Quran — Surah Sad, 38:71"),
        ar=L("مِمَّ خلق الله آدم بحسب القرآن؟",
             ["من طين", "من نور", "من نار", "من ماء"], 0,
             "قال الله للملائكة: ﴿إني خالق بشرًا من طين﴾.",
             "القرآن — سورة ص، 38:71"))

    add("prophets_034", "prophets", "easy", "quran", Q, "7:20", False,
        fr=L("Qui a poussé Âdam et son épouse à manger de l'arbre interdit ?",
             ["Shaytân (Iblîs)", "Un ange", "Un oiseau", "Un roi"], 0,
             "Shaytân leur chuchota pour leur faire manger de l'arbre qu'Allah avait interdit.",
             "Coran — Sourate Al-A'râf, 7:20"),
        en=L("Who tempted Adam and his wife to eat from the forbidden tree?",
             ["Shaytan (Iblis)", "An angel", "A bird", "A king"], 0,
             "Shaytan whispered to them so that they would eat from the tree Allah had forbidden.",
             "Quran — Surah Al-A'raf, 7:20"),
        ar=L("من وسوس لآدم وزوجه ليأكلا من الشجرة المحرّمة؟",
             ["الشيطان (إبليس)", "ملك", "طائر", "ملك من الملوك"], 0,
             "وسوس لهما الشيطان ليأكلا من الشجرة التي نهاهما الله عنها.",
             "القرآن — سورة الأعراف، 7:20"))

    add("prophets_035", "prophets", "medium", "quran", Q, "7:12", False,
        fr=L("Quelle raison Iblîs donna-t-il pour refuser de se prosterner devant Âdam ?",
             ["« Je suis meilleur que lui : Tu m'as créé de feu et lui d'argile »",
              "Il ne savait pas qui était Âdam", "Il avait peur des anges", "Il était endormi"], 0,
             "Iblîs refusa par orgueil : « Tu m'as créé de feu, et lui, Tu l'as créé d'argile. »",
             "Coran — Sourate Al-A'râf, 7:12"),
        en=L("What reason did Iblis give for refusing to bow to Adam?",
             ["\"I am better than him: You created me from fire and him from clay\"",
              "He did not know who Adam was", "He was afraid of the angels", "He was asleep"], 0,
             "Iblis refused out of pride: \"You created me from fire, and him You created from clay.\"",
             "Quran — Surah Al-A'raf, 7:12"),
        ar=L("ما الحجة التي قدّمها إبليس لرفض السجود لآدم؟",
             ["«أنا خير منه: خلقتني من نار وخلقته من طين»",
              "لم يكن يعرف آدم", "كان يخاف من الملائكة", "كان نائمًا"], 0,
             "رفض إبليس كِبرًا: ﴿خلقتني من نار وخلقته من طين﴾.",
             "القرآن — سورة الأعراف، 7:12"))

    add("prophets_036", "prophets", "hard", "quran", Q, "5:31", False,
        fr=L("Après le meurtre entre les deux fils d'Âdam, quel animal Allah envoya-t-Il pour montrer comment enterrer le corps ?",
             ["Un corbeau", "Un chien", "Une colombe", "Un renard"], 0,
             "Allah envoya un corbeau qui gratta la terre pour montrer au meurtrier comment cacher le corps de son frère.",
             "Coran — Sourate Al-Mâ'ida, 5:31"),
        en=L("After the killing between the two sons of Adam, which animal did Allah send to show how to bury the body?",
             ["A crow", "A dog", "A dove", "A fox"], 0,
             "Allah sent a crow that scratched the ground to show the killer how to hide his brother's body.",
             "Quran — Surah Al-Ma'ida, 5:31"),
        ar=L("بعد قتل أحد ابنَي آدم أخاه، أيَّ حيوان بعث الله ليُريه كيف يواري الجثة؟",
             ["غرابًا", "كلبًا", "حمامة", "ثعلبًا"], 0,
             "بعث الله غرابًا يبحث في الأرض ليُري القاتلَ كيف يواري سوءة أخيه.",
             "القرآن — سورة المائدة، 5:31"))

    add("prophets_037", "prophets", "medium", "quran", Q, "19:57", False,
        fr=L("Que dit le Coran au sujet du prophète Idrîs ?",
             ["Allah l'éleva à un rang très haut", "Il construisit une arche", "Il fut avalé par un poisson", "Il parla aux fourmis"], 0,
             "« Et Nous l'élevâmes à un haut rang. »",
             "Coran — Sourate Maryam, 19:57"),
        en=L("What does the Quran say about the prophet Idris?",
             ["Allah raised him to a high station", "He built an ark", "He was swallowed by a fish", "He spoke to the ants"], 0,
             "\"And We raised him to a high station.\"",
             "Quran — Surah Maryam, 19:57"),
        ar=L("ماذا يقول القرآن عن النبي إدريس؟",
             ["رفعه الله مكانًا عليًّا", "بنى سفينة", "التقمه الحوت", "كلّم النمل"], 0,
             "﴿ورفعناه مكانًا عليًّا﴾.",
             "القرآن — سورة مريم، 19:57"))

    add("prophets_038", "prophets", "medium", "quran", Q, "11:42-43", False,
        fr=L("Que fit le fils de Nûh quand son père l'appela à monter dans l'arche ?",
             ["Il refusa et voulut se réfugier sur une montagne", "Il monta le premier", "Il construisit sa propre arche", "Il partit chercher des animaux"], 0,
             "Il dit : « Je vais me réfugier sur une montagne » ; les flots le submergèrent.",
             "Coran — Sourate Hûd, 11:42-43"),
        en=L("What did Nuh's son do when his father called him into the ark?",
             ["He refused and said he would shelter on a mountain", "He boarded first", "He built his own ark", "He went to gather animals"], 0,
             "He said: \"I will take refuge on a mountain\"; the waves overwhelmed him.",
             "Quran — Surah Hud, 11:42-43"),
        ar=L("ماذا فعل ابن نوح حين دعاه أبوه ليركب السفينة؟",
             ["رفض وقال إنه سيأوي إلى جبل", "ركب أولًا", "بنى سفينة خاصة", "ذهب يجمع الحيوانات"], 0,
             "قال: ﴿سآوي إلى جبل يعصمني من الماء﴾ فحال بينهما الموج.",
             "القرآن — سورة هود، 11:42-43"))

    add("prophets_039", "prophets", "hard", "quran", Q, "11:44", False,
        fr=L("Sur quel mont l'arche de Nûh s'est-elle posée, selon le Coran ?",
             ["Le mont Jûdî", "Le mont Sinaï", "Le mont Uhud", "Le mont Arafat"], 0,
             "« Et l'arche s'installa sur le Jûdî. »",
             "Coran — Sourate Hûd, 11:44"),
        en=L("On which mount did Nuh's ark come to rest, according to the Quran?",
             ["Mount Judi", "Mount Sinai", "Mount Uhud", "Mount Arafat"], 0,
             "\"And the ark came to rest on al-Judi.\"",
             "Quran — Surah Hud, 11:44"),
        ar=L("على أي جبل استوت سفينة نوح بحسب القرآن؟",
             ["الجودي", "سيناء", "أُحد", "عرفات"], 0,
             "﴿واستوت على الجودي﴾.",
             "القرآن — سورة هود، 11:44"))

    add("prophets_040", "prophets", "medium", "quran", Q, "11:40", False,
        fr=L("Qu'Allah ordonna-t-Il à Nûh de charger dans l'arche ?",
             ["Un couple de chaque espèce et les croyants", "Uniquement sa famille", "Uniquement des oiseaux", "De l'or et de l'argent"], 0,
             "« Charge dans l'arche un couple de chaque espèce, ta famille… et ceux qui croient. »",
             "Coran — Sourate Hûd, 11:40"),
        en=L("What did Allah command Nuh to load into the ark?",
             ["A pair of every kind, and the believers", "Only his family", "Only birds", "Gold and silver"], 0,
             "\"Load into it a pair of every kind, and your family… and whoever has believed.\"",
             "Quran — Surah Hud, 11:40"),
        ar=L("بماذا أمر الله نوحًا أن يحمل في السفينة؟",
             ["من كل زوجين اثنين والمؤمنين", "أهله فقط", "الطيور فقط", "الذهب والفضة"], 0,
             "﴿احمل فيها من كلٍّ زوجين اثنين وأهلك… ومن آمن﴾.",
             "القرآن — سورة هود، 11:40"))

    add("prophets_041", "prophets", "easy", "quran", Q, "11:38", False,
        fr=L("Que faisaient les notables du peuple de Nûh quand ils le voyaient construire l'arche ?",
             ["Ils se moquaient de lui", "Ils l'aidaient", "Ils lui apportaient du bois", "Ils priaient avec lui"], 0,
             "Chaque fois que des notables passaient, ils se moquaient de lui.",
             "Coran — Sourate Hûd, 11:38"),
        en=L("What did the chiefs of Nuh's people do when they saw him building the ark?",
             ["They mocked him", "They helped him", "They brought him wood", "They prayed with him"], 0,
             "Whenever chiefs of his people passed by, they ridiculed him.",
             "Quran — Surah Hud, 11:38"),
        ar=L("ماذا كان يفعل الملأ من قوم نوح حين يرونه يصنع السفينة؟",
             ["يسخرون منه", "يساعدونه", "يأتونه بالخشب", "يصلّون معه"], 0,
             "﴿وكلما مرّ عليه ملأ من قومه سخروا منه﴾.",
             "القرآن — سورة هود، 11:38"))

    add("prophets_042", "prophets", "hard", "quran", Q, "17:3", False,
        fr=L("Par quelle expression le Coran décrit-il Nûh dans la sourate Al-Isrâ ?",
             ["Un serviteur très reconnaissant", "Un roi puissant", "Un grand voyageur", "Un homme silencieux"], 0,
             "« Il était un serviteur très reconnaissant. »",
             "Coran — Sourate Al-Isrâ, 17:3"),
        en=L("How does the Quran describe Nuh in Surah Al-Isra?",
             ["A grateful servant", "A mighty king", "A great traveller", "A silent man"], 0,
             "\"Indeed, he was a grateful servant.\"",
             "Quran — Surah Al-Isra, 17:3"),
        ar=L("بأي وصف وصف القرآن نوحًا في سورة الإسراء؟",
             ["عبدًا شكورًا", "ملكًا قويًا", "رحّالة عظيمًا", "رجلًا صامتًا"], 0,
             "﴿إنه كان عبدًا شكورًا﴾.",
             "القرآن — سورة الإسراء، 17:3"))

    add("prophets_043", "prophets", "medium", "quran", Q, "69:6", False,
        fr=L("Par quoi le peuple de 'Âd, auquel Hûd fut envoyé, fut-il anéanti ?",
             ["Un vent violent et glacial", "Un déluge", "Une pluie de pierres", "Un tremblement de terre"], 0,
             "« Les 'Âd furent anéantis par un vent mugissant et furieux. »",
             "Coran — Sourate Al-Hâqqa, 69:6"),
        en=L("How were the people of 'Ad, to whom Hud was sent, destroyed?",
             ["By a violent, furious wind", "By a flood", "By a rain of stones", "By an earthquake"], 0,
             "\"As for 'Ad, they were destroyed by a screaming, violent wind.\"",
             "Quran — Surah Al-Haqqa, 69:6"),
        ar=L("بماذا أُهلك قوم عاد الذين أُرسل إليهم هود؟",
             ["بريح صرصر عاتية", "بالطوفان", "بحجارة من السماء", "بالزلزلة"], 0,
             "﴿وأما عاد فأُهلكوا بريح صرصر عاتية﴾.",
             "القرآن — سورة الحاقة، 69:6"))

    add("prophets_044", "prophets", "medium", "quran", Q, "11:67", False,
        fr=L("Par quoi les Thamûd, peuple de Sâlih, furent-ils saisis ?",
             ["Un cri terrible", "Un déluge", "La famine", "Une nuée de sauterelles"], 0,
             "« Le Cri saisit ceux qui avaient été injustes. »",
             "Coran — Sourate Hûd, 11:67"),
        en=L("What seized Thamud, the people of Salih?",
             ["A terrible blast (cry)", "A flood", "A famine", "A swarm of locusts"], 0,
             "\"And the blast seized those who had wronged.\"",
             "Quran — Surah Hud, 11:67"),
        ar=L("بماذا أُخذ ثمود قوم صالح؟",
             ["بالصيحة", "بالطوفان", "بالمجاعة", "بالجراد"], 0,
             "﴿وأخذ الذين ظلموا الصيحة﴾.",
             "القرآن — سورة هود، 11:67"))

    add("prophets_045", "prophets", "hard", "quran", Q, "6:74", False,
        fr=L("Quel est le nom du père d'Ibrâhîm cité dans le Coran ?",
             ["Âzar", "Târih", "Lût", "Kan'ân"], 0,
             "« Ibrâhîm dit à Âzar, son père : prends-tu des idoles pour divinités ? »",
             "Coran — Sourate Al-An'âm, 6:74"),
        en=L("What is the name of Ibrahim's father mentioned in the Quran?",
             ["Azar", "Tarih", "Lut", "Kan'an"], 0,
             "\"Ibrahim said to his father Azar: do you take idols as gods?\"",
             "Quran — Surah Al-An'am, 6:74"),
        ar=L("ما اسم أبي إبراهيم المذكور في القرآن؟",
             ["آزر", "تارح", "لوط", "كنعان"], 0,
             "﴿وإذ قال إبراهيم لأبيه آزر أتتخذ أصنامًا آلهة﴾.",
             "القرآن — سورة الأنعام، 6:74"))

    add("prophets_046", "prophets", "medium", "quran", Q, "21:58", False,
        fr=L("Après avoir brisé les idoles, laquelle Ibrâhîm laissa-t-il intacte ?",
             ["La plus grande", "La plus petite", "Celle en or", "Aucune, il les brisa toutes"], 0,
             "Il les mit en pièces, sauf la plus grande, pour que son peuple l'interroge.",
             "Coran — Sourate Al-Anbiyâ, 21:58"),
        en=L("After breaking the idols, which one did Ibrahim leave intact?",
             ["The biggest one", "The smallest one", "The golden one", "None, he broke them all"], 0,
             "He broke them to pieces, except the biggest, so that his people would question it.",
             "Quran — Surah Al-Anbiya, 21:58"),
        ar=L("بعد تحطيم الأصنام، أيَّها ترك إبراهيم سليمًا؟",
             ["كبيرها", "أصغرها", "الذهبي", "لم يترك شيئًا"], 0,
             "﴿فجعلهم جذاذًا إلا كبيرًا لهم لعلهم إليه يرجعون﴾.",
             "القرآن — سورة الأنبياء، 21:58"))

    add("prophets_047", "prophets", "hard", "quran", Q, "6:76-78", False,
        fr=L("Après avoir vu l'étoile, la lune puis le soleil se coucher, que déclara Ibrâhîm ?",
             ["« Je n'aime pas ce qui disparaît »", "« Le soleil est mon seigneur »", "« La lune est la plus belle »", "« Je vais dormir »"], 0,
             "À chaque astre qui se couchait, il dit : « Je n'aime pas ceux qui disparaissent », puis se tourna vers le Créateur.",
             "Coran — Sourate Al-An'âm, 6:76-78"),
        en=L("After watching the star, the moon and then the sun set, what did Ibrahim declare?",
             ["\"I do not love those that set\"", "\"The sun is my lord\"", "\"The moon is the most beautiful\"", "\"I will sleep\""], 0,
             "As each one set he said: \"I do not love those that set,\" then turned to the Creator.",
             "Quran — Surah Al-An'am, 6:76-78"),
        ar=L("بعد أن رأى إبراهيم الكوكب ثم القمر ثم الشمس تغيب، ماذا قال؟",
             ["«لا أحب الآفلين»", "«الشمس ربي»", "«القمر أجمل»", "«سأنام»"], 0,
             "كلما أفل واحد قال: ﴿لا أحب الآفلين﴾، ثم توجّه إلى فاطر السماوات والأرض.",
             "القرآن — سورة الأنعام، 6:76-78"))

    add("prophets_048", "prophets", "hard", "quran", Q, "2:260", False,
        fr=L("Combien d'oiseaux Allah dit-Il à Ibrâhîm de prendre pour lui montrer comment Il ressuscite les morts ?",
             ["Quatre", "Deux", "Sept", "Douze"], 0,
             "« Prends quatre oiseaux… puis appelle-les : ils viendront à toi en hâte. »",
             "Coran — Sourate Al-Baqara, 2:260"),
        en=L("How many birds did Allah tell Ibrahim to take, to show him how He brings the dead to life?",
             ["Four", "Two", "Seven", "Twelve"], 0,
             "\"Take four birds… then call them: they will come to you in haste.\"",
             "Quran — Surah Al-Baqara, 2:260"),
        ar=L("كم طائرًا أمر الله إبراهيم أن يأخذ ليُريه كيف يحيي الموتى؟",
             ["أربعة", "اثنين", "سبعة", "اثني عشر"], 0,
             "﴿فخذ أربعة من الطير… ثم ادعهن يأتينك سعيًا﴾.",
             "القرآن — سورة البقرة، 2:260"))

    add("prophets_049", "prophets", "hard", "quran", Q, "11:69", False,
        fr=L("Que servit Ibrâhîm à ses hôtes, les anges venus lui annoncer une bonne nouvelle ?",
             ["Un veau rôti", "Des dattes", "Du lait", "Du pain et du miel"], 0,
             "« Il ne tarda pas à apporter un veau rôti. »",
             "Coran — Sourate Hûd, 11:69"),
        en=L("What did Ibrahim serve his guests, the angels who came with good news?",
             ["A roasted calf", "Dates", "Milk", "Bread and honey"], 0,
             "\"He did not delay in bringing a roasted calf.\"",
             "Quran — Surah Hud, 11:69"),
        ar=L("ماذا قدّم إبراهيم لضيوفه من الملائكة الذين جاؤوا بالبشرى؟",
             ["عجلًا حنيذًا", "تمرًا", "لبنًا", "خبزًا وعسلًا"], 0,
             "﴿فما لبث أن جاء بعجل حنيذ﴾.",
             "القرآن — سورة هود، 11:69"))

    add("prophets_050", "prophets", "medium", "quran", Q, "11:71", False,
        fr=L("Quelle bonne nouvelle les anges annoncèrent-ils à l'épouse d'Ibrâhîm ?",
             ["La naissance d'Ishâq", "Un voyage", "Une grande richesse", "Une pluie abondante"], 0,
             "« Nous lui annonçâmes Ishâq, et après Ishâq, Ya'qûb. »",
             "Coran — Sourate Hûd, 11:71"),
        en=L("What good news did the angels bring to Ibrahim's wife?",
             ["The birth of Ishaq", "A journey", "Great wealth", "Abundant rain"], 0,
             "\"We gave her good tidings of Ishaq, and after Ishaq, Ya'qub.\"",
             "Quran — Surah Hud, 11:71"),
        ar=L("بماذا بشّرت الملائكة امرأة إبراهيم؟",
             ["بإسحاق", "بسفر", "بمال كثير", "بمطر غزير"], 0,
             "﴿فبشّرناها بإسحاق ومن وراء إسحاق يعقوب﴾.",
             "القرآن — سورة هود، 11:71"))

    add("prophets_051", "prophets", "easy", "quran", Q, "37:102-107", False,
        fr=L("Comment réagit le fils d'Ibrâhîm quand son père lui raconta le rêve où il le sacrifiait ?",
             ["Il accepta : « Fais ce qui t'est ordonné »", "Il s'enfuit", "Il pleura et refusa", "Il se cacha"], 0,
             "Il dit : « Ô mon père, fais ce qui t'est commandé. » Et Allah le racheta par un grand sacrifice.",
             "Coran — Sourate As-Sâffât, 37:102-107"),
        en=L("How did Ibrahim's son react when his father told him the dream of sacrificing him?",
             ["He accepted: \"Do what you are commanded\"", "He ran away", "He cried and refused", "He hid"], 0,
             "He said: \"O my father, do as you are commanded.\" And Allah ransomed him with a great sacrifice.",
             "Quran — Surah As-Saffat, 37:102-107"),
        ar=L("كيف استجاب ابن إبراهيم حين أخبره أبوه برؤيا ذبحه؟",
             ["قال: «يا أبتِ افعل ما تؤمر»", "هرب", "بكى ورفض", "اختبأ"], 0,
             "قال: ﴿يا أبتِ افعل ما تؤمر﴾، وفداه الله بذبح عظيم.",
             "القرآن — سورة الصافات، 37:102-107"))

    add("prophets_052", "prophets", "medium", "quran", Q, "14:37", False,
        fr=L("Dans sa prière, où Ibrâhîm dit-il avoir installé une partie de sa famille ?",
             ["Dans une vallée sans culture, près de la Maison sacrée", "Au bord du Nil", "Dans une forêt", "Sur une île"], 0,
             "« J'ai établi une partie de ma descendance dans une vallée sans agriculture, auprès de Ta Maison sacrée. »",
             "Coran — Sourate Ibrâhîm, 14:37"),
        en=L("In his prayer, where does Ibrahim say he settled some of his family?",
             ["In a valley without cultivation, near the Sacred House", "By the Nile", "In a forest", "On an island"], 0,
             "\"I have settled some of my descendants in an uncultivated valley near Your Sacred House.\"",
             "Quran — Surah Ibrahim, 14:37"),
        ar=L("في دعائه، أين قال إبراهيم إنه أسكن بعض ذريته؟",
             ["بوادٍ غير ذي زرع عند البيت المحرّم", "على ضفة النيل", "في غابة", "في جزيرة"], 0,
             "﴿ربنا إني أسكنت من ذريتي بوادٍ غير ذي زرع عند بيتك المحرّم﴾.",
             "القرآن — سورة إبراهيم، 14:37"))

    add("prophets_053", "prophets", "medium", "quran", Q, "2:126", False,
        fr=L("Que demanda Ibrâhîm pour la ville de La Mecque dans sa prière ?",
             ["Qu'elle soit une cité sûre et que ses habitants aient des fruits", "Qu'elle devienne un royaume", "Qu'il y pleuve toujours", "Qu'elle ait un fleuve"], 0,
             "« Seigneur, fais de cette cité un lieu sûr, et accorde des fruits à ses habitants. »",
             "Coran — Sourate Al-Baqara, 2:126"),
        en=L("What did Ibrahim ask for the city of Makkah in his prayer?",
             ["That it be a secure city and its people be given fruits", "That it become a kingdom", "That it always rain there", "That it have a river"], 0,
             "\"My Lord, make this a secure city and provide its people with fruits.\"",
             "Quran — Surah Al-Baqara, 2:126"),
        ar=L("ماذا طلب إبراهيم لمكة في دعائه؟",
             ["أن تكون بلدًا آمنًا وأن يُرزق أهلها من الثمرات", "أن تصير مملكة", "أن تُمطر دائمًا", "أن يكون فيها نهر"], 0,
             "﴿ربِّ اجعل هذا بلدًا آمنًا وارزق أهله من الثمرات﴾.",
             "القرآن — سورة البقرة، 2:126"))

    add("prophets_054", "prophets", "hard", "quran", Q, "2:129", False,
        fr=L("En élevant la Ka'ba, Ibrâhîm et Ismâ'îl demandèrent à Allah d'envoyer parmi leurs descendants… ?",
             ["Un messager issu d'eux, qui leur récite Ses versets", "Un roi", "Une armée", "Un trésor"], 0,
             "« Seigneur, envoie parmi eux un messager issu d'eux, qui leur récite Tes versets. »",
             "Coran — Sourate Al-Baqara, 2:129"),
        en=L("While raising the Ka'ba, Ibrahim and Isma'il asked Allah to send among their descendants… ?",
             ["A messenger from among them, reciting His verses", "A king", "An army", "A treasure"], 0,
             "\"Our Lord, send among them a messenger from themselves who will recite to them Your verses.\"",
             "Quran — Surah Al-Baqara, 2:129"),
        ar=L("عند رفع قواعد الكعبة، ماذا سأل إبراهيم وإسماعيل أن يبعث الله في ذريتهما؟",
             ["رسولًا منهم يتلو عليهم آياته", "ملكًا", "جيشًا", "كنزًا"], 0,
             "﴿ربنا وابعث فيهم رسولًا منهم يتلو عليهم آياتك﴾.",
             "القرآن — سورة البقرة، 2:129"))

    add("prophets_055", "prophets", "hard", "quran", Q, "16:120", False,
        fr=L("Le Coran dit d'un prophète qu'il était à lui seul « une communauté (umma) ». Lequel ?",
             ["Ibrâhîm", "Nûh", "Mûsâ", "Sulaymân"], 0,
             "« Ibrâhîm était une communauté à lui seul, dévoué à Allah, droit. »",
             "Coran — Sourate An-Nahl, 16:120"),
        en=L("The Quran says one prophet was, by himself, \"a nation (umma)\". Which one?",
             ["Ibrahim", "Nuh", "Musa", "Sulayman"], 0,
             "\"Indeed, Ibrahim was a nation, devoutly obedient to Allah, upright.\"",
             "Quran — Surah An-Nahl, 16:120"),
        ar=L("أي نبي وصفه القرآن بأنه كان «أمّة» وحده؟",
             ["إبراهيم", "نوح", "موسى", "سليمان"], 0,
             "﴿إن إبراهيم كان أمّةً قانتًا لله حنيفًا﴾.",
             "القرآن — سورة النحل، 16:120"))

    add("prophets_056", "prophets", "medium", "quran", Q, "19:54", False,
        fr=L("De quelle qualité le Coran loue-t-il Ismâ'îl dans la sourate Maryam ?",
             ["Il était fidèle à sa promesse", "Il était très riche", "Il était roi", "Il savait nager"], 0,
             "« Il était fidèle à ses promesses, et c'était un messager et un prophète. »",
             "Coran — Sourate Maryam, 19:54"),
        en=L("For which quality does the Quran praise Isma'il in Surah Maryam?",
             ["He was true to his promise", "He was very wealthy", "He was a king", "He could swim"], 0,
             "\"Indeed, he was true to his promise, and he was a messenger and a prophet.\"",
             "Quran — Surah Maryam, 19:54"),
        ar=L("بأي صفة أثنى القرآن على إسماعيل في سورة مريم؟",
             ["كان صادق الوعد", "كان غنيًا جدًا", "كان ملكًا", "كان سبّاحًا"], 0,
             "﴿إنه كان صادق الوعد وكان رسولًا نبيًا﴾.",
             "القرآن — سورة مريم، 19:54"))

    add("prophets_057", "prophets", "medium", "quran", Q, "11:82", False,
        fr=L("Quel châtiment frappa le peuple de Lût ?",
             ["Une pluie de pierres d'argile", "Un déluge", "Une nuée de moustiques", "Une sécheresse"], 0,
             "« Nous renversâmes la cité et fîmes pleuvoir sur elle des pierres d'argile. »",
             "Coran — Sourate Hûd, 11:82"),
        en=L("What punishment struck the people of Lut?",
             ["A rain of stones of baked clay", "A flood", "A swarm of insects", "A drought"], 0,
             "\"We turned the city upside down and rained upon it stones of baked clay.\"",
             "Quran — Surah Hud, 11:82"),
        ar=L("ما العقاب الذي نزل بقوم لوط؟",
             ["أُمطروا حجارة من سجّيل", "الطوفان", "سرب من الحشرات", "الجفاف"], 0,
             "﴿جعلنا عاليها سافلها وأمطرنا عليها حجارة من سجّيل﴾.",
             "القرآن — سورة هود، 11:82"))

    add("prophets_058", "prophets", "hard", "quran", Q, "66:10", False,
        fr=L("Les épouses de quels deux prophètes le Coran cite-t-il comme exemple de mécréance ?",
             ["Nûh et Lût", "Ibrâhîm et Mûsâ", "Dâwûd et Sulaymân", "Ayyûb et Yûnus"], 0,
             "« Allah propose en exemple, pour les mécréants, la femme de Nûh et la femme de Lût. »",
             "Coran — Sourate At-Tahrîm, 66:10"),
        en=L("The wives of which two prophets does the Quran give as an example of disbelief?",
             ["Nuh and Lut", "Ibrahim and Musa", "Dawud and Sulayman", "Ayyub and Yunus"], 0,
             "\"Allah presents an example of those who disbelieved: the wife of Nuh and the wife of Lut.\"",
             "Quran — Surah At-Tahrim, 66:10"),
        ar=L("امرأتا أي نبيَّين ضرب الله بهما مثلًا للذين كفروا؟",
             ["نوح ولوط", "إبراهيم وموسى", "داوود وسليمان", "أيوب ويونس"], 0,
             "﴿ضرب الله مثلًا للذين كفروا امرأة نوح وامرأة لوط﴾.",
             "القرآن — سورة التحريم، 66:10"))

    add("prophets_059", "prophets", "medium", "quran", Q, "11:71", False,
        fr=L("Qui était le père de Ya'qûb ?",
             ["Ishâq", "Ismâ'îl", "Ibrâhîm", "Yûsuf"], 0,
             "Les anges annoncèrent à l'épouse d'Ibrâhîm « Ishâq, et après Ishâq, Ya'qûb ».",
             "Coran — Sourate Hûd, 11:71"),
        en=L("Who was Ya'qub's father?",
             ["Ishaq", "Isma'il", "Ibrahim", "Yusuf"], 0,
             "The angels announced to Ibrahim's wife \"Ishaq, and after Ishaq, Ya'qub\".",
             "Quran — Surah Hud, 11:71"),
        ar=L("من هو أبو يعقوب؟",
             ["إسحاق", "إسماعيل", "إبراهيم", "يوسف"], 0,
             "بشّرت الملائكة امرأة إبراهيم ﴿بإسحاق ومن وراء إسحاق يعقوب﴾.",
             "القرآن — سورة هود، 11:71"))

    add("prophets_060", "prophets", "medium", "quran", Q, "12:84", False,
        fr=L("Que devint la vue de Ya'qûb à force de pleurer Yûsuf ?",
             ["Ses yeux blanchirent", "Il vit mieux la nuit", "Rien ne changea", "Il devint borgne"], 0,
             "« Ses yeux blanchirent de chagrin, et il en était accablé. »",
             "Coran — Sourate Yûsuf, 12:84"),
        en=L("What happened to Ya'qub's eyesight from weeping over Yusuf?",
             ["His eyes turned white", "He saw better at night", "Nothing changed", "He lost one eye"], 0,
             "\"His eyes became white from grief, and he was suppressing it.\"",
             "Quran — Surah Yusuf, 12:84"),
        ar=L("ماذا حدث لبصر يعقوب من كثرة البكاء على يوسف؟",
             ["ابيضّت عيناه", "صار يرى أفضل ليلًا", "لم يتغير شيء", "فقد عينًا واحدة"], 0,
             "﴿وابيضّت عيناه من الحزن فهو كظيم﴾.",
             "القرآن — سورة يوسف، 12:84"))

    add("prophets_061", "prophets", "medium", "quran", Q, "12:93-96", False,
        fr=L("Qu'est-ce qui rendit la vue à Ya'qûb ?",
             ["La chemise de Yûsuf jetée sur son visage", "Une plante", "De l'eau de Zamzam", "Un baume"], 0,
             "Yûsuf dit : « Jetez ma chemise sur le visage de mon père, il recouvrera la vue. »",
             "Coran — Sourate Yûsuf, 12:93-96"),
        en=L("What restored Ya'qub's sight?",
             ["Yusuf's shirt cast over his face", "A plant", "Zamzam water", "An ointment"], 0,
             "Yusuf said: \"Cast my shirt over my father's face; he will regain his sight.\"",
             "Quran — Surah Yusuf, 12:93-96"),
        ar=L("ما الذي أعاد البصر إلى يعقوب؟",
             ["قميص يوسف أُلقي على وجهه", "نبتة", "ماء زمزم", "مرهم"], 0,
             "قال يوسف: ﴿اذهبوا بقميصي هذا فألقوه على وجه أبي يأتِ بصيرًا﴾.",
             "القرآن — سورة يوسف، 12:93-96"))

    add("prophets_062", "prophets", "medium", "quran", Q, "12:33", False,
        fr=L("Que préféra Yûsuf plutôt que de céder à ce qu'on lui proposait de mal ?",
             ["La prison", "L'exil", "La richesse", "Le silence"], 0,
             "« Seigneur, la prison m'est préférable à ce à quoi elles m'invitent. »",
             "Coran — Sourate Yûsuf, 12:33"),
        en=L("What did Yusuf prefer rather than giving in to what he was wrongly invited to?",
             ["Prison", "Exile", "Wealth", "Silence"], 0,
             "\"My Lord, prison is dearer to me than what they invite me to.\"",
             "Quran — Surah Yusuf, 12:33"),
        ar=L("ماذا فضّل يوسف على الاستجابة لما دُعي إليه من المعصية؟",
             ["السجن", "المنفى", "المال", "الصمت"], 0,
             "﴿ربِّ السجن أحب إليّ مما يدعونني إليه﴾.",
             "القرآن — سورة يوسف، 12:33"))

    add("prophets_063", "prophets", "hard", "quran", Q, "12:36", False,
        fr=L("En prison, deux jeunes hommes racontèrent leurs rêves à Yûsuf. Que voyait l'un d'eux ?",
             ["Il pressait du raisin", "Il volait", "Il gardait des moutons", "Il creusait un puits"], 0,
             "L'un se voyait presser du vin, l'autre porter du pain sur sa tête que les oiseaux mangeaient.",
             "Coran — Sourate Yûsuf, 12:36"),
        en=L("In prison, two young men told Yusuf their dreams. What did one of them see?",
             ["He was pressing grapes", "He was flying", "He was herding sheep", "He was digging a well"], 0,
             "One saw himself pressing wine, the other carrying bread on his head that birds ate from.",
             "Quran — Surah Yusuf, 12:36"),
        ar=L("في السجن قصّ فتيان على يوسف رؤياهما. ماذا رأى أحدهما؟",
             ["أنه يعصر خمرًا", "أنه يطير", "أنه يرعى غنمًا", "أنه يحفر بئرًا"], 0,
             "رأى أحدهما أنه يعصر خمرًا، والآخر أنه يحمل فوق رأسه خبزًا تأكل الطير منه.",
             "القرآن — سورة يوسف، 12:36"))

    add("prophets_064", "prophets", "medium", "quran", Q, "12:47-48", False,
        fr=L("Combien d'années d'abondance puis de sécheresse Yûsuf annonça-t-il au roi ?",
             ["Sept et sept", "Trois et trois", "Dix et dix", "Un et un"], 0,
             "« Vous sèmerez sept années… puis viendront sept années difficiles. »",
             "Coran — Sourate Yûsuf, 12:47-48"),
        en=L("How many years of plenty and then of drought did Yusuf foretell to the king?",
             ["Seven and seven", "Three and three", "Ten and ten", "One and one"], 0,
             "\"You will sow for seven years… then will come seven difficult years.\"",
             "Quran — Surah Yusuf, 12:47-48"),
        ar=L("كم سنة من الخصب ثم من الجدب أخبر يوسف الملك بها؟",
             ["سبع وسبع", "ثلاث وثلاث", "عشر وعشر", "سنة وسنة"], 0,
             "﴿تزرعون سبع سنين دأبًا… ثم يأتي من بعد ذلك سبع شداد﴾.",
             "القرآن — سورة يوسف، 12:47-48"))

    add("prophets_065", "prophets", "medium", "quran", Q, "12:55", False,
        fr=L("Quelle charge Yûsuf demanda-t-il au roi d'Égypte ?",
             ["Les greniers (réserves) du pays", "Le commandement de l'armée", "Le trône", "Le trésor d'or"], 0,
             "« Confie-moi les réserves du pays : je suis bon gardien et connaisseur. »",
             "Coran — Sourate Yûsuf, 12:55"),
        en=L("Which office did Yusuf ask the king of Egypt for?",
             ["The storehouses of the land", "Command of the army", "The throne", "The gold treasury"], 0,
             "\"Appoint me over the storehouses of the land: I am a knowing guardian.\"",
             "Quran — Surah Yusuf, 12:55"),
        ar=L("أي منصب طلب يوسف من ملك مصر؟",
             ["خزائن الأرض", "قيادة الجيش", "العرش", "خزانة الذهب"], 0,
             "﴿اجعلني على خزائن الأرض إني حفيظ عليم﴾.",
             "القرآن — سورة يوسف، 12:55"))

    add("prophets_066", "prophets", "hard", "quran", Q, "12:70", False,
        fr=L("Qu'est-ce que Yûsuf fit placer dans les bagages de son jeune frère pour le garder auprès de lui ?",
             ["La coupe du roi", "Un sac d'or", "Une lettre", "Sa chemise"], 0,
             "« Il mit la coupe dans le chargement de son frère. »",
             "Coran — Sourate Yûsuf, 12:70"),
        en=L("What did Yusuf have placed in his younger brother's baggage to keep him by his side?",
             ["The king's drinking cup", "A bag of gold", "A letter", "His shirt"], 0,
             "\"He put the drinking cup into his brother's bag.\"",
             "Quran — Surah Yusuf, 12:70"),
        ar=L("ماذا جعل يوسف في رحل أخيه ليُبقيه عنده؟",
             ["صُواع الملك", "كيس ذهب", "رسالة", "قميصه"], 0,
             "﴿جعل السقاية في رحل أخيه﴾.",
             "القرآن — سورة يوسف، 12:70"))

    add("prophets_067", "prophets", "hard", "quran", Q, "12:67", False,
        fr=L("Quel conseil Ya'qûb donna-t-il à ses fils avant leur entrée en Égypte ?",
             ["Entrer par des portes différentes", "Voyager de nuit", "Se déguiser", "Emporter des cadeaux"], 0,
             "« N'entrez pas par une seule porte, mais par des portes séparées. »",
             "Coran — Sourate Yûsuf, 12:67"),
        en=L("What advice did Ya'qub give his sons before they entered Egypt?",
             ["Enter through different gates", "Travel by night", "Disguise themselves", "Bring gifts"], 0,
             "\"Do not enter through one gate, but enter through different gates.\"",
             "Quran — Surah Yusuf, 12:67"),
        ar=L("بماذا نصح يعقوب أبناءه قبل دخولهم مصر؟",
             ["أن يدخلوا من أبواب متفرقة", "أن يسافروا ليلًا", "أن يتنكّروا", "أن يحملوا هدايا"], 0,
             "﴿لا تدخلوا من باب واحد وادخلوا من أبواب متفرقة﴾.",
             "القرآن — سورة يوسف، 12:67"))

    add("prophets_068", "prophets", "medium", "quran", Q, "12:58", False,
        fr=L("Pourquoi les frères de Yûsuf vinrent-ils en Égypte alors qu'il y était devenu intendant ?",
             ["Pour obtenir des provisions pendant la famine", "Pour le retrouver", "Pour faire le pèlerinage", "Pour vendre des chameaux"], 0,
             "Ses frères vinrent chercher des vivres ; ils entrèrent chez lui sans le reconnaître.",
             "Coran — Sourate Yûsuf, 12:58"),
        en=L("Why did Yusuf's brothers come to Egypt when he was in charge there?",
             ["To get provisions during the famine", "To find him", "To make a pilgrimage", "To sell camels"], 0,
             "His brothers came for grain; they entered upon him and did not recognise him.",
             "Quran — Surah Yusuf, 12:58"),
        ar=L("لماذا جاء إخوة يوسف إلى مصر وقد صار على خزائنها؟",
             ["ليأخذوا الميرة في سنوات الجدب", "ليبحثوا عنه", "للحج", "لبيع الإبل"], 0,
             "جاء إخوته يطلبون الطعام، فدخلوا عليه فعرفهم وهم له منكرون.",
             "القرآن — سورة يوسف، 12:58"))

    add("prophets_069", "prophets", "easy", "quran", Q, "28:8", False,
        fr=L("Dans quelle maison le bébé Mûsâ fut-il recueilli après avoir été mis dans le fleuve ?",
             ["Celle de Pharaon", "Celle d'un berger", "Celle d'un pêcheur", "Celle d'un marchand"], 0,
             "La famille de Pharaon le recueillit, pour qu'il devienne un jour leur ennemi et leur cause de chagrin.",
             "Coran — Sourate Al-Qasas, 28:8"),
        en=L("In whose house was baby Musa taken in after being placed in the river?",
             ["Pharaoh's", "A shepherd's", "A fisherman's", "A merchant's"], 0,
             "Pharaoh's household picked him up, that he might one day be an enemy and a grief to them.",
             "Quran — Surah Al-Qasas, 28:8"),
        ar=L("في بيت من التُقط موسى الرضيع بعد إلقائه في النهر؟",
             ["بيت فرعون", "بيت راعٍ", "بيت صيّاد", "بيت تاجر"], 0,
             "﴿فالتقطه آل فرعون ليكون لهم عدوًا وحزنًا﴾.",
             "القرآن — سورة القصص، 28:8"))

    add("prophets_070", "prophets", "medium", "quran", Q, "28:12-13", False,
        fr=L("Comment Mûsâ bébé revint-il finalement auprès de sa mère ?",
             ["Il refusa toutes les nourrices, et sa sœur proposa sa mère", "Pharaon le lui rendit par pitié", "Sa mère le vola de nuit", "Un ange l'emporta"], 0,
             "Allah lui fit refuser les nourrices ; sa sœur proposa une famille : c'était sa mère, qui put l'allaiter.",
             "Coran — Sourate Al-Qasas, 28:12-13"),
        en=L("How did baby Musa finally return to his mother?",
             ["He refused every wet nurse, and his sister suggested his mother", "Pharaoh returned him out of pity", "His mother stole him by night", "An angel carried him"], 0,
             "Allah made him refuse the wet nurses; his sister suggested a household: it was his mother, who nursed him.",
             "Quran — Surah Al-Qasas, 28:12-13"),
        ar=L("كيف عاد موسى الرضيع إلى أمه في النهاية؟",
             ["حرّم الله عليه المراضع فدلّت أخته على أمه", "أعاده فرعون شفقة", "سرقته أمه ليلًا", "حمله ملك"], 0,
             "﴿وحرّمنا عليه المراضع من قبل﴾ فدلّتهم أخته على أهل بيت، فرددناه إلى أمه.",
             "القرآن — سورة القصص، 28:12-13"))

    add("prophets_071", "prophets", "medium", "quran", Q, "28:15", False,
        fr=L("Pourquoi Mûsâ dut-il quitter l'Égypte en hâte, avant sa mission ?",
             ["Il avait tué un homme par accident en le frappant", "Il avait volé au palais", "Il refusait de payer l'impôt", "Il avait insulté Pharaon"], 0,
             "Il frappa un Égyptien qui se battait avec un homme de son peuple et le tua ; il regretta aussitôt.",
             "Coran — Sourate Al-Qasas, 28:15"),
        en=L("Why did Musa have to leave Egypt in haste, before his mission?",
             ["He had killed a man unintentionally with a blow", "He had stolen from the palace", "He refused to pay tax", "He had insulted Pharaoh"], 0,
             "He struck an Egyptian who was fighting a man of his people and killed him; he regretted it at once.",
             "Quran — Surah Al-Qasas, 28:15"),
        ar=L("لماذا اضطر موسى إلى مغادرة مصر مسرعًا قبل بعثته؟",
             ["وكز رجلًا فقضى عليه دون قصد القتل", "سرق من القصر", "رفض دفع الضريبة", "أهان فرعون"], 0,
             "﴿فوكزه موسى فقضى عليه﴾ ثم ندم واستغفر.",
             "القرآن — سورة القصص، 28:15"))

    add("prophets_072", "prophets", "hard", "quran", Q, "28:20", False,
        fr=L("Qui avertit Mûsâ que les notables complotaient pour le tuer ?",
             ["Un homme venu en courant de l'extrémité de la ville", "Sa mère", "Hârûn", "Un soldat"], 0,
             "« Un homme vint en courant du bout de la ville : ils délibèrent pour te tuer, pars ! »",
             "Coran — Sourate Al-Qasas, 28:20"),
        en=L("Who warned Musa that the chiefs were plotting to kill him?",
             ["A man who came running from the far end of the city", "His mother", "Harun", "A soldier"], 0,
             "\"A man came running from the farthest part of the city: they are conspiring to kill you, so leave!\"",
             "Quran — Surah Al-Qasas, 28:20"),
        ar=L("من حذّر موسى بأن الملأ يأتمرون به ليقتلوه؟",
             ["رجل جاء يسعى من أقصى المدينة", "أمه", "هارون", "جندي"], 0,
             "﴿وجاء رجل من أقصى المدينة يسعى قال يا موسى إن الملأ يأتمرون بك ليقتلوك فاخرج﴾.",
             "القرآن — سورة القصص، 28:20"))

    add("prophets_073", "prophets", "medium", "quran", Q, "28:23-24", False,
        fr=L("En arrivant à Madyan, que fit Mûsâ pour deux femmes près du point d'eau ?",
             ["Il abreuva leur troupeau", "Il leur vendit un chameau", "Il leur construisit une maison", "Il leur apprit à lire"], 0,
             "Il abreuva leurs bêtes, puis se retira à l'ombre en invoquant Allah.",
             "Coran — Sourate Al-Qasas, 28:23-24"),
        en=L("Arriving at Madyan, what did Musa do for two women at the watering place?",
             ["He watered their flock", "He sold them a camel", "He built them a house", "He taught them to read"], 0,
             "He watered their flock, then withdrew to the shade calling on Allah.",
             "Quran — Surah Al-Qasas, 28:23-24"),
        ar=L("حين وصل موسى إلى مدين، ماذا فعل للمرأتين عند الماء؟",
             ["سقى لهما غنمهما", "باع لهما جملًا", "بنى لهما بيتًا", "علّمهما القراءة"], 0,
             "﴿فسقى لهما ثم تولّى إلى الظل﴾ داعيًا ربه.",
             "القرآن — سورة القصص، 28:23-24"))

    add("prophets_074", "prophets", "hard", "quran", Q, "28:27", False,
        fr=L("Combien d'années le vieil homme de Madyan demanda-t-il à Mûsâ de travailler pour épouser sa fille ?",
             ["Huit ans, et dix s'il le voulait", "Un an", "Quarante ans", "Trois ans"], 0,
             "« Tu travailleras pour moi huit années ; si tu vas jusqu'à dix, ce sera de ton plein gré. »",
             "Coran — Sourate Al-Qasas, 28:27"),
        en=L("How many years did the old man of Madyan ask Musa to work in order to marry his daughter?",
             ["Eight, and ten if he wished", "One", "Forty", "Three"], 0,
             "\"You will serve me for eight years; if you complete ten, it will be of your own accord.\"",
             "Quran — Surah Al-Qasas, 28:27"),
        ar=L("كم سنة طلب شيخ مدين من موسى أن يعمل عنده ليزوّجه ابنته؟",
             ["ثماني سنين، وعشرًا إن شاء", "سنة", "أربعين سنة", "ثلاث سنين"], 0,
             "﴿على أن تأجرني ثماني حجج فإن أتممت عشرًا فمن عندك﴾.",
             "القرآن — سورة القصص، 28:27"))

    add("prophets_075", "prophets", "medium", "quran", Q, "20:12", False,
        fr=L("Qu'Allah ordonna-t-Il à Mûsâ de retirer dans la vallée sacrée de Tuwâ ?",
             ["Ses sandales", "Son manteau", "Son bâton", "Son turban"], 0,
             "« Ôte tes sandales : tu es dans la vallée sacrée de Tuwâ. »",
             "Coran — Sourate Tâ-Hâ, 20:12"),
        en=L("What did Allah command Musa to remove in the sacred valley of Tuwa?",
             ["His sandals", "His cloak", "His staff", "His turban"], 0,
             "\"Remove your sandals: you are in the sacred valley of Tuwa.\"",
             "Quran — Surah Ta-Ha, 20:12"),
        ar=L("بماذا أمر الله موسى أن يخلعه في الوادي المقدس طوى؟",
             ["نعليه", "رداءه", "عصاه", "عمامته"], 0,
             "﴿فاخلع نعليك إنك بالواد المقدس طوى﴾.",
             "القرآن — سورة طه، 20:12"))

    add("prophets_076", "prophets", "medium", "quran", Q, "20:22", False,
        fr=L("Quel fut le second signe donné à Mûsâ, après le bâton ?",
             ["Sa main devint blanche, sans mal", "Il put voler", "Sa voix devint tonnerre", "Il vit la nuit"], 0,
             "« Serre ta main sous ton aisselle : elle sortira blanche, sans aucun mal. »",
             "Coran — Sourate Tâ-Hâ, 20:22"),
        en=L("What was the second sign given to Musa, after the staff?",
             ["His hand came out white, without harm", "He could fly", "His voice became thunder", "He saw at night"], 0,
             "\"Draw your hand to your side: it will come out white, without disease.\"",
             "Quran — Surah Ta-Ha, 20:22"),
        ar=L("ما الآية الثانية التي أُعطيها موسى بعد العصا؟",
             ["تخرج يده بيضاء من غير سوء", "صار يطير", "صار صوته كالرعد", "صار يرى في الليل"], 0,
             "﴿واضمم يدك إلى جناحك تخرج بيضاء من غير سوء﴾.",
             "القرآن — سورة طه، 20:22"))

    add("prophets_077", "prophets", "medium", "quran", Q, "20:25-28", False,
        fr=L("Que demanda Mûsâ à Allah avant d'aller voir Pharaon ?",
             ["D'ouvrir sa poitrine et de dénouer sa langue", "Une armée", "De l'or", "Un cheval rapide"], 0,
             "« Seigneur, ouvre-moi ma poitrine, facilite ma mission, et dénoue ma langue. »",
             "Coran — Sourate Tâ-Hâ, 20:25-28"),
        en=L("What did Musa ask Allah for before going to Pharaoh?",
             ["To expand his chest and loosen his tongue", "An army", "Gold", "A fast horse"], 0,
             "\"My Lord, expand for me my chest, ease my task, and untie the knot from my tongue.\"",
             "Quran — Surah Ta-Ha, 20:25-28"),
        ar=L("ماذا سأل موسى ربه قبل الذهاب إلى فرعون؟",
             ["أن يشرح صدره ويحلّ عقدة لسانه", "جيشًا", "ذهبًا", "فرسًا سريعًا"], 0,
             "﴿ربِّ اشرح لي صدري ويسّر لي أمري واحلل عقدة من لساني﴾.",
             "القرآن — سورة طه، 20:25-28"))

    add("prophets_078", "prophets", "easy", "quran", Q, "20:29-30", False,
        fr=L("Qui Mûsâ demanda-t-il à Allah comme assistant dans sa mission ?",
             ["Son frère Hârûn", "Son fils", "Son beau-père", "Un ange"], 0,
             "« Donne-moi un assistant de ma famille : Hârûn, mon frère. »",
             "Coran — Sourate Tâ-Hâ, 20:29-30"),
        en=L("Whom did Musa ask Allah to give him as a helper in his mission?",
             ["His brother Harun", "His son", "His father-in-law", "An angel"], 0,
             "\"Appoint for me a helper from my family: Harun, my brother.\"",
             "Quran — Surah Ta-Ha, 20:29-30"),
        ar=L("من طلب موسى من الله أن يجعله وزيرًا له في رسالته؟",
             ["أخاه هارون", "ابنه", "حماه", "ملكًا"], 0,
             "﴿واجعل لي وزيرًا من أهلي هارون أخي﴾.",
             "القرآن — سورة طه، 20:29-30"))

    add("prophets_079", "prophets", "medium", "quran", Q, "7:117-120", False,
        fr=L("Que firent les magiciens de Pharaon quand le bâton de Mûsâ engloutit leurs illusions ?",
             ["Ils se prosternèrent et crurent", "Ils s'enfuirent", "Ils rirent", "Ils attaquèrent Mûsâ"], 0,
             "Les magiciens tombèrent prosternés : « Nous croyons au Seigneur des mondes, le Seigneur de Mûsâ et Hârûn. »",
             "Coran — Sourate Al-A'râf, 7:117-120"),
        en=L("What did Pharaoh's magicians do when Musa's staff swallowed their illusions?",
             ["They fell in prostration and believed", "They fled", "They laughed", "They attacked Musa"], 0,
             "The magicians fell down in prostration: \"We believe in the Lord of the worlds, the Lord of Musa and Harun.\"",
             "Quran — Surah Al-A'raf, 7:117-120"),
        ar=L("ماذا فعل سحرة فرعون حين لقفت عصا موسى ما صنعوا؟",
             ["خرّوا ساجدين وآمنوا", "هربوا", "ضحكوا", "هاجموا موسى"], 0,
             "﴿وأُلقي السحرة ساجدين قالوا آمنا برب العالمين رب موسى وهارون﴾.",
             "القرآن — سورة الأعراف، 7:117-120"))

    add("prophets_080", "prophets", "hard", "quran", Q, "7:133", False,
        fr=L("Lequel de ces fléaux le Coran cite-t-il parmi ceux envoyés contre le peuple de Pharaon ?",
             ["Les sauterelles", "La neige", "Les loups", "Le feu"], 0,
             "« Nous envoyâmes contre eux l'inondation, les sauterelles, les poux, les grenouilles et le sang. »",
             "Coran — Sourate Al-A'râf, 7:133"),
        en=L("Which of these plagues does the Quran list among those sent against Pharaoh's people?",
             ["Locusts", "Snow", "Wolves", "Fire"], 0,
             "\"We sent upon them the flood, locusts, lice, frogs and blood.\"",
             "Quran — Surah Al-A'raf, 7:133"),
        ar=L("أيٌّ مما يلي ذكره القرآن من الآيات التي أُرسلت على قوم فرعون؟",
             ["الجراد", "الثلج", "الذئاب", "النار"], 0,
             "﴿فأرسلنا عليهم الطوفان والجراد والقمّل والضفادع والدم﴾.",
             "القرآن — سورة الأعراف، 7:133"))

    add("prophets_081", "prophets", "hard", "quran", Q, "10:92", False,
        fr=L("Selon le Coran, que fit Allah du corps de Pharaon après sa noyade ?",
             ["Il le sauva pour qu'il soit un signe", "Il le fit disparaître", "Il le brûla", "Il le rendit à son peuple"], 0,
             "« Aujourd'hui Nous sauvons ton corps, afin que tu sois un signe pour ceux qui viendront après toi. »",
             "Coran — Sourate Yûnus, 10:92"),
        en=L("According to the Quran, what did Allah do with Pharaoh's body after he drowned?",
             ["Preserved it as a sign", "Made it vanish", "Burned it", "Returned it to his people"], 0,
             "\"Today We will save your body, so that you may be a sign to those who come after you.\"",
             "Quran — Surah Yunus, 10:92"),
        ar=L("بحسب القرآن، ماذا فعل الله بجسد فرعون بعد غرقه؟",
             ["نجّاه ليكون آية", "أخفاه", "أحرقه", "أعاده إلى قومه"], 0,
             "﴿فاليوم ننجّيك ببدنك لتكون لمن خلفك آية﴾.",
             "القرآن — سورة يونس، 10:92"))

    add("prophets_082", "prophets", "hard", "quran", Q, "66:11", False,
        fr=L("Selon le Coran, que demanda à Allah l'épouse croyante de Pharaon ?",
             ["Une maison auprès de Lui au Paradis", "Un fils", "La mort de Pharaon", "Un royaume"], 0,
             "« Seigneur, construis-moi auprès de Toi une maison au Paradis, et sauve-moi de Pharaon. »",
             "Coran — Sourate At-Tahrîm, 66:11"),
        en=L("According to the Quran, what did Pharaoh's believing wife ask of Allah?",
             ["A house near Him in Paradise", "A son", "Pharaoh's death", "A kingdom"], 0,
             "\"My Lord, build for me near You a house in Paradise, and save me from Pharaoh.\"",
             "Quran — Surah At-Tahrim, 66:11"),
        ar=L("بحسب القرآن، ماذا سألت امرأة فرعون المؤمنة ربها؟",
             ["بيتًا عنده في الجنة", "ولدًا", "موت فرعون", "مملكة"], 0,
             "﴿ربِّ ابنِ لي عندك بيتًا في الجنة ونجّني من فرعون﴾.",
             "القرآن — سورة التحريم، 66:11"))

    add("prophets_083", "prophets", "hard", "quran", Q, "7:142", False,
        fr=L("Combien de nuits dura le rendez-vous d'Allah avec Mûsâ sur le mont ?",
             ["Quarante", "Sept", "Dix", "Cent"], 0,
             "« Nous donnâmes rendez-vous à Mûsâ pendant trente nuits, complétées par dix : quarante nuits. »",
             "Coran — Sourate Al-A'râf, 7:142"),
        en=L("How many nights did Allah's appointment with Musa on the mount last?",
             ["Forty", "Seven", "Ten", "One hundred"], 0,
             "\"We appointed for Musa thirty nights and completed them with ten: forty nights.\"",
             "Quran — Surah Al-A'raf, 7:142"),
        ar=L("كم ليلة استغرق ميقات موسى مع ربه على الجبل؟",
             ["أربعين", "سبعًا", "عشرًا", "مئة"], 0,
             "﴿وواعدنا موسى ثلاثين ليلة وأتممناها بعشر فتمّ ميقات ربه أربعين ليلة﴾.",
             "القرآن — سورة الأعراف، 7:142"))

    add("prophets_084", "prophets", "hard", "quran", Q, "7:143", False,
        fr=L("Que se passa-t-il quand Mûsâ demanda à voir Allah ?",
             ["Allah Se manifesta au mont, qui s'effondra, et Mûsâ tomba foudroyé", "Il vit Allah", "Rien ne se passa", "Le mont s'éleva dans le ciel"], 0,
             "« Regarde le mont : s'il reste en place, tu Me verras. » Le mont fut pulvérisé et Mûsâ tomba évanoui.",
             "Coran — Sourate Al-A'râf, 7:143"),
        en=L("What happened when Musa asked to see Allah?",
             ["Allah manifested to the mount, which crumbled, and Musa fell unconscious", "He saw Allah", "Nothing happened", "The mount rose into the sky"], 0,
             "\"Look at the mount: if it stays in place, you will see Me.\" The mount was levelled and Musa fell unconscious.",
             "Quran — Surah Al-A'raf, 7:143"),
        ar=L("ماذا حدث حين سأل موسى ربه أن يراه؟",
             ["تجلّى الله للجبل فجعله دكًّا وخرّ موسى صعقًا", "رأى الله", "لم يحدث شيء", "ارتفع الجبل إلى السماء"], 0,
             "﴿انظر إلى الجبل فإن استقر مكانه فسوف تراني﴾ فلما تجلّى ربه للجبل جعله دكًّا وخرّ موسى صعقًا.",
             "القرآن — سورة الأعراف، 7:143"))

    add("prophets_085", "prophets", "medium", "quran", Q, "7:145", False,
        fr=L("Sur quoi Allah écrivit-Il pour Mûsâ des exhortations et des explications ?",
             ["Sur des Tables", "Sur des feuilles de palmier", "Sur une pierre noire", "Sur du cuir"], 0,
             "« Nous écrivîmes pour lui sur les Tables une exhortation sur toute chose. »",
             "Coran — Sourate Al-A'râf, 7:145"),
        en=L("On what did Allah write admonitions and explanations for Musa?",
             ["On Tablets", "On palm leaves", "On a black stone", "On leather"], 0,
             "\"We wrote for him on the Tablets an admonition concerning all things.\"",
             "Quran — Surah Al-A'raf, 7:145"),
        ar=L("على ماذا كتب الله لموسى الموعظة والتفصيل؟",
             ["على الألواح", "على سعف النخل", "على حجر أسود", "على جلد"], 0,
             "﴿وكتبنا له في الألواح من كل شيء موعظة﴾.",
             "القرآن — سورة الأعراف، 7:145"))

    add("prophets_086", "prophets", "hard", "quran", Q, "20:85-88", False,
        fr=L("Qui fabriqua le veau d'or que les Enfants d'Israël adorèrent pendant l'absence de Mûsâ ?",
             ["As-Sâmirî", "Hârûn", "Pharaon", "Qârûn"], 0,
             "« As-Sâmirî les a égarés » : il fit sortir de leurs bijoux un veau qui mugissait.",
             "Coran — Sourate Tâ-Hâ, 20:85-88"),
        en=L("Who made the calf that the Children of Israel worshipped while Musa was away?",
             ["As-Samiri", "Harun", "Pharaoh", "Qarun"], 0,
             "\"As-Samiri has led them astray\": from their ornaments he produced a calf that made a lowing sound.",
             "Quran — Surah Ta-Ha, 20:85-88"),
        ar=L("من صنع العجل الذي عبده بنو إسرائيل في غياب موسى؟",
             ["السامري", "هارون", "فرعون", "قارون"], 0,
             "﴿وأضلّهم السامري﴾: أخرج لهم من حليّهم عجلًا جسدًا له خوار.",
             "القرآن — سورة طه، 20:85-88"))

    add("prophets_087", "prophets", "hard", "quran", Q, "2:60", False,
        fr=L("Combien de sources jaillirent du rocher que Mûsâ frappa de son bâton ?",
             ["Douze", "Sept", "Trois", "Quarante"], 0,
             "« Frappe le rocher de ton bâton » : douze sources en jaillirent, une pour chaque tribu.",
             "Coran — Sourate Al-Baqara, 2:60"),
        en=L("How many springs gushed from the rock Musa struck with his staff?",
             ["Twelve", "Seven", "Three", "Forty"], 0,
             "\"Strike the rock with your staff\": twelve springs gushed forth, one for each tribe.",
             "Quran — Surah Al-Baqara, 2:60"),
        ar=L("كم عينًا انفجرت من الحجر الذي ضربه موسى بعصاه؟",
             ["اثنتا عشرة", "سبع", "ثلاث", "أربعون"], 0,
             "﴿اضرب بعصاك الحجر فانفجرت منه اثنتا عشرة عينًا﴾.",
             "القرآن — سورة البقرة، 2:60"))

    add("prophets_088", "prophets", "medium", "quran", Q, "2:57", False,
        fr=L("Quelle nourriture Allah fit-Il descendre sur les Enfants d'Israël dans le désert ?",
             ["La manne et les cailles", "Du riz et du poisson", "Des dattes et du lait", "Du pain et des olives"], 0,
             "« Nous fîmes descendre sur vous la manne et les cailles. »",
             "Coran — Sourate Al-Baqara, 2:57"),
        en=L("What food did Allah send down to the Children of Israel in the desert?",
             ["Manna and quails", "Rice and fish", "Dates and milk", "Bread and olives"], 0,
             "\"We sent down upon you manna and quails.\"",
             "Quran — Surah Al-Baqara, 2:57"),
        ar=L("ما الطعام الذي أنزله الله على بني إسرائيل في الصحراء؟",
             ["المنّ والسلوى", "الأرز والسمك", "التمر واللبن", "الخبز والزيتون"], 0,
             "﴿وأنزلنا عليكم المنّ والسلوى﴾.",
             "القرآن — سورة البقرة، 2:57"))

    add("prophets_089", "prophets", "hard", "quran", Q, "2:69", False,
        fr=L("De quelle couleur devait être la vache que Mûsâ ordonna aux Enfants d'Israël d'immoler ?",
             ["Jaune vif", "Noire", "Blanche", "Rousse"], 0,
             "« C'est une vache jaune, d'une couleur vive, qui réjouit les regards. »",
             "Coran — Sourate Al-Baqara, 2:69"),
        en=L("What colour was the cow Musa told the Children of Israel to sacrifice?",
             ["Bright yellow", "Black", "White", "Red"], 0,
             "\"It is a yellow cow, bright in colour, pleasing to those who see.\"",
             "Quran — Surah Al-Baqara, 2:69"),
        ar=L("ما لون البقرة التي أمر موسى بني إسرائيل بذبحها؟",
             ["صفراء فاقع لونها", "سوداء", "بيضاء", "حمراء"], 0,
             "﴿بقرة صفراء فاقع لونها تسرّ الناظرين﴾.",
             "القرآن — سورة البقرة، 2:69"))

    add("prophets_090", "prophets", "medium", "quran", Q, "28:76-81", False,
        fr=L("Qui, du peuple de Mûsâ, fut englouti avec sa demeure pour son orgueil et ses richesses ?",
             ["Qârûn", "Hâmân", "As-Sâmirî", "Jâlût"], 0,
             "Qârûn possédait des trésors immenses ; « Nous l'engloutîmes, lui et sa demeure, dans la terre. »",
             "Coran — Sourate Al-Qasas, 28:76-81"),
        en=L("Who, from Musa's people, was swallowed by the earth with his house for his arrogance and wealth?",
             ["Qarun", "Haman", "As-Samiri", "Jalut"], 0,
             "Qarun owned vast treasures; \"We caused the earth to swallow him and his home.\"",
             "Quran — Surah Al-Qasas, 28:76-81"),
        ar=L("من من قوم موسى خُسف به وبداره لكبره وماله؟",
             ["قارون", "هامان", "السامري", "جالوت"], 0,
             "كان لقارون كنوز عظيمة، ﴿فخسفنا به وبداره الأرض﴾.",
             "القرآن — سورة القصص، 28:76-81"))
