"""Sīra — part B (sira_091 … sira_150)."""

WE = "well-established sira event, agreed across standard biographies"
WT = "well-established terminology"


def register(add, L):
    Q = "Quran"
    S = "Sira"
    B = "Sahih al-Bukhari"
    M = "Sahih Muslim"

    add("sira_091", "sira", "medium", "hadithBukhari", B, "6038", False,
        fr=L("Quel jeune compagnon servit le Prophète ﷺ pendant dix ans sans jamais entendre un reproche ?",
             ["Anas ibn Mâlik", "Usâma ibn Zayd", "Ibn 'Abbâs", "Zayd ibn Thâbit"], 0,
             "Anas dit : « J'ai servi le Prophète ﷺ dix ans ; jamais il ne m'a dit “ouf”, ni “pourquoi as-tu fait cela ?” »",
             "Sahîh al-Bukhârî, 6038"),
        en=L("Which young companion served the Prophet ﷺ for ten years without ever hearing a reproach?",
             ["Anas ibn Malik", "Usama ibn Zayd", "Ibn 'Abbas", "Zayd ibn Thabit"], 0,
             "Anas said: \"I served the Prophet ﷺ for ten years; he never said 'uff' to me, nor 'why did you do that?'\"",
             "Sahih al-Bukhari, 6038"),
        ar=L("أي صحابي صغير خدم النبي ﷺ عشر سنين فلم يسمع منه عتابًا قط؟",
             ["أنس بن مالك", "أسامة بن زيد", "ابن عباس", "زيد بن ثابت"], 0,
             "قال أنس: «خدمت النبي ﷺ عشر سنين، فما قال لي أفٍّ قط، ولا لِمَ صنعت».",
             "صحيح البخاري، 6038"))

    add("sira_092", "sira", "hard", "hadithBukhari", B, "75", False,
        fr=L("Pour quel jeune cousin le Prophète ﷺ fit-il l'invocation : « Ô Allah, enseigne-lui le Livre » ?",
             ["'Abdullâh ibn 'Abbâs", "'Alî", "Ja'far", "Usâma"], 0,
             "Le Prophète ﷺ serra Ibn 'Abbâs contre lui et dit : « Ô Allah, enseigne-lui le Livre. »",
             "Sahîh al-Bukhârî, 75"),
        en=L("For which young cousin did the Prophet ﷺ pray: \"O Allah, teach him the Book\"?",
             ["'Abdullah ibn 'Abbas", "'Ali", "Ja'far", "Usama"], 0,
             "The Prophet ﷺ embraced Ibn 'Abbas and said: \"O Allah, teach him the Book.\"",
             "Sahih al-Bukhari, 75"),
        ar=L("لأي ابن عمّ صغير دعا النبي ﷺ: «اللهم علّمه الكتاب»؟",
             ["عبد الله بن عباس", "علي", "جعفر", "أسامة"], 0,
             "ضمّ النبي ﷺ ابن عباس إلى صدره وقال: «اللهم علّمه الكتاب».",
             "صحيح البخاري، 75"))

    add("sira_093", "sira", "medium", "hadithBukhari", B, "1395", False,
        fr=L("Quel compagnon le Prophète ﷺ envoya-t-il au Yémen en lui disant d'appeler d'abord à l'unicité d'Allah ?",
             ["Mu'âdh ibn Jabal", "Bilâl", "Abû Mûsâ seul", "Zayd ibn Hâritha"], 0,
             "« Tu vas chez des gens du Livre : appelle-les d'abord à témoigner qu'il n'y a de divinité qu'Allah… »",
             "Sahîh al-Bukhârî, 1395"),
        en=L("Which companion did the Prophet ﷺ send to Yemen, telling him to call first to the oneness of Allah?",
             ["Mu'adh ibn Jabal", "Bilal", "Abu Musa alone", "Zayd ibn Haritha"], 0,
             "\"You are going to a people of the Book: first call them to testify that there is no god but Allah…\"",
             "Sahih al-Bukhari, 1395"),
        ar=L("أي صحابي بعثه النبي ﷺ إلى اليمن وأوصاه أن يدعوهم أولًا إلى توحيد الله؟",
             ["معاذ بن جبل", "بلال", "أبو موسى وحده", "زيد بن حارثة"], 0,
             "«إنك تأتي قومًا من أهل الكتاب، فادعهم إلى شهادة أن لا إله إلا الله…».",
             "صحيح البخاري، 1395"))

    add("sira_094", "sira", "hard", "hadithBukhari", B, "3744", False,
        fr=L("Quel compagnon le Prophète ﷺ appela-t-il « l'homme de confiance (amîn) de cette communauté » ?",
             ["Abû 'Ubayda ibn al-Jarrâh", "Abû Bakr", "'Uthmân", "Khâlid"], 0,
             "« Chaque communauté a un homme de confiance, et le nôtre est Abû 'Ubayda ibn al-Jarrâh. »",
             "Sahîh al-Bukhârî, 3744"),
        en=L("Which companion did the Prophet ﷺ call \"the trustworthy one (amin) of this nation\"?",
             ["Abu 'Ubayda ibn al-Jarrah", "Abu Bakr", "'Uthman", "Khalid"], 0,
             "\"Every nation has a trustworthy one, and the trustworthy one of this nation is Abu 'Ubayda ibn al-Jarrah.\"",
             "Sahih al-Bukhari, 3744"),
        ar=L("أي صحابي سمّاه النبي ﷺ «أمين هذه الأمة»؟",
             ["أبو عبيدة بن الجراح", "أبو بكر", "عثمان", "خالد"], 0,
             "«لكل أمة أمين، وأمين هذه الأمة أبو عبيدة بن الجراح».",
             "صحيح البخاري، 3744"))

    add("sira_095", "sira", "medium", "hadithBukhari", B, "4986", False,
        fr=L("Quel compagnon, scribe de la révélation, fut chargé par Abû Bakr de rassembler le Coran ?",
             ["Zayd ibn Thâbit", "Abû Hurayra", "Anas ibn Mâlik", "Salmân"], 0,
             "Après la bataille d'al-Yamâma, Abû Bakr chargea Zayd ibn Thâbit de réunir le Coran.",
             "Sahîh al-Bukhârî, 4986"),
        en=L("Which companion, a scribe of the revelation, was tasked by Abu Bakr with collecting the Quran?",
             ["Zayd ibn Thabit", "Abu Hurayra", "Anas ibn Malik", "Salman"], 0,
             "After the battle of al-Yamama, Abu Bakr tasked Zayd ibn Thabit with collecting the Quran.",
             "Sahih al-Bukhari, 4986"),
        ar=L("أي صحابي من كتّاب الوحي كلّفه أبو بكر بجمع القرآن؟",
             ["زيد بن ثابت", "أبو هريرة", "أنس بن مالك", "سلمان"], 0,
             "بعد معركة اليمامة كلّف أبو بكر زيدَ بن ثابت بجمع القرآن.",
             "صحيح البخاري، 4986"))

    add("sira_096", "sira", "hard", "hadithBukhari", B, "4987", False,
        fr=L("Sous quel calife des copies officielles du Coran furent-elles envoyées dans les provinces ?",
             ["'Uthmân ibn 'Affân", "Abû Bakr", "'Umar", "'Alî"], 0,
             "'Uthmân fit copier le mushaf et envoya un exemplaire à chaque province.",
             "Sahîh al-Bukhârî, 4987"),
        en=L("Under which caliph were official copies of the Quran sent to the provinces?",
             ["'Uthman ibn 'Affan", "Abu Bakr", "'Umar", "'Ali"], 0,
             "'Uthman had the mushaf copied and sent a copy to every province.",
             "Sahih al-Bukhari, 4987"),
        ar=L("في عهد أي خليفة أُرسلت مصاحف رسمية إلى الأمصار؟",
             ["عثمان بن عفان", "أبو بكر", "عمر", "علي"], 0,
             "أمر عثمان بنسخ المصحف وأرسل إلى كل أفق مصحفًا.",
             "صحيح البخاري، 4987"))

    add("sira_097", "sira", "easy", "sira", S, WE, False,
        fr=L("De quel pays venait le compagnon Salmân, surnommé « al-Fârisî » ?",
             ["La Perse", "L'Abyssinie", "Byzance", "Le Yémen"], 0,
             "Salmân al-Fârisî, « le Persan », vint de Perse à la recherche de la vérité.",
             "Sîra — fait établi"),
        en=L("From which land did the companion Salman, called \"al-Farisi\", come?",
             ["Persia", "Abyssinia", "Byzantium", "Yemen"], 0,
             "Salman al-Farisi, \"the Persian\", came from Persia in search of the truth.",
             "Sira — established fact"),
        ar=L("من أي بلد جاء الصحابي سلمان الملقّب بـ«الفارسي»؟",
             ["فارس", "الحبشة", "الروم", "اليمن"], 0,
             "جاء سلمان الفارسي من بلاد فارس باحثًا عن الحق.",
             "السيرة — حقيقة ثابتة"))

    add("sira_098", "sira", "hard", "sira", S, WE, False,
        fr=L("Quel compagnon, venu de Byzance, est surnommé « ar-Rûmî » ?",
             ["Suhayb", "Bilâl", "Salmân", "Abû Dharr"], 0,
             "Suhayb ar-Rûmî grandit chez les Byzantins avant d'embrasser l'islam à La Mecque.",
             "Sîra — fait établi"),
        en=L("Which companion, who came from the Byzantine lands, is called \"ar-Rumi\"?",
             ["Suhayb", "Bilal", "Salman", "Abu Dharr"], 0,
             "Suhayb ar-Rumi grew up among the Byzantines before embracing Islam in Makkah.",
             "Sira — established fact"),
        ar=L("أي صحابي جاء من بلاد الروم ولُقّب بـ«الرومي»؟",
             ["صهيب", "بلال", "سلمان", "أبو ذر"], 0,
             "نشأ صهيب الرومي في بلاد الروم قبل أن يُسلم في مكة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_099", "sira", "easy", "sira", S, WT, False,
        fr=L("Comment s'appelle la mosquée du Prophète ﷺ à Médine ?",
             ["Al-Masjid an-Nabawî", "Al-Masjid al-Harâm", "Al-Masjid al-Aqsâ", "Masjid Qubâ"], 0,
             "La mosquée qu'il fonda à Médine s'appelle la Mosquée du Prophète, al-Masjid an-Nabawî.",
             "Sîra — terminologie établie"),
        en=L("What is the Prophet's ﷺ mosque in Madinah called?",
             ["Al-Masjid an-Nabawi", "Al-Masjid al-Haram", "Al-Masjid al-Aqsa", "Masjid Quba"], 0,
             "The mosque he founded in Madinah is called the Prophet's Mosque, al-Masjid an-Nabawi.",
             "Sira — established terminology"),
        ar=L("ماذا يُسمّى مسجد النبي ﷺ في المدينة؟",
             ["المسجد النبوي", "المسجد الحرام", "المسجد الأقصى", "مسجد قباء"], 0,
             "المسجد الذي أسسه في المدينة هو المسجد النبوي.",
             "السيرة — مصطلح ثابت"))

    add("sira_100", "sira", "hard", "quran", Q, "well-established count (the name Muhammad appears four times: 3:144, 33:40, 47:2, 48:29)", False,
        fr=L("Combien de fois le nom « Muhammad » apparaît-il dans le Coran ?",
             ["Quatre", "Une", "Douze", "Cent"], 0,
             "Dans les versets 3:144, 33:40, 47:2 et 48:29 ; le nom « Ahmad » apparaît en 61:6.",
             "Coran — fait établi"),
        en=L("How many times does the name \"Muhammad\" appear in the Quran?",
             ["Four", "One", "Twelve", "A hundred"], 0,
             "In verses 3:144, 33:40, 47:2 and 48:29; the name \"Ahmad\" appears in 61:6.",
             "Quran — established fact"),
        ar=L("كم مرة ورد اسم «محمد» في القرآن؟",
             ["أربع", "واحدة", "اثنتا عشرة", "مئة"], 0,
             "في الآيات 3:144 و33:40 و47:2 و48:29، وورد اسم «أحمد» في 61:6.",
             "القرآن — حقيقة ثابتة"))

    add("sira_101", "sira", "easy", "quran", Q, "33:21", False,
        fr=L("Comment le Coran décrit-il le Prophète ﷺ pour les croyants, dans le verset 33:21 ?",
             ["Un excellent modèle", "Un juge sévère", "Un roi", "Un poète"], 0,
             "« Vous avez dans le Messager d'Allah un excellent modèle. »",
             "Coran — Sourate Al-Ahzâb, 33:21"),
        en=L("How does the Quran describe the Prophet ﷺ for the believers, in verse 33:21?",
             ["An excellent example", "A stern judge", "A king", "A poet"], 0,
             "\"There has certainly been for you in the Messenger of Allah an excellent example.\"",
             "Quran — Surah Al-Ahzab, 33:21"),
        ar=L("كيف وصف القرآن النبي ﷺ للمؤمنين في الآية 33:21؟",
             ["أسوة حسنة", "قاضيًا صارمًا", "ملكًا", "شاعرًا"], 0,
             "﴿لقد كان لكم في رسول الله أسوة حسنة﴾.",
             "القرآن — سورة الأحزاب، 33:21"))

    add("sira_102", "sira", "medium", "sira", S, WE, False,
        fr=L("Quelle était la kunya (surnom paternel) du Prophète ﷺ ?",
             ["Abû al-Qâsim", "Abû Bakr", "Abû 'Abdullâh", "Abû Tâlib"], 0,
             "Il était appelé Abû al-Qâsim, du nom de son fils aîné Al-Qâsim.",
             "Sîra — fait établi"),
        en=L("What was the Prophet's ﷺ kunya (paternal nickname)?",
             ["Abu al-Qasim", "Abu Bakr", "Abu 'Abdullah", "Abu Talib"], 0,
             "He was called Abu al-Qasim, after his eldest son Al-Qasim.",
             "Sira — established fact"),
        ar=L("ما كنية النبي ﷺ؟",
             ["أبو القاسم", "أبو بكر", "أبو عبد الله", "أبو طالب"], 0,
             "كان يُكنّى أبا القاسم باسم ابنه الأكبر القاسم.",
             "السيرة — حقيقة ثابتة"))

    add("sira_103", "sira", "hard", "sira", S, WE, False,
        fr=L("Comment s'appelait le fils du Prophète ﷺ né à Médine, mort en bas âge ?",
             ["Ibrâhîm", "Al-Qâsim", "'Abdullâh", "Al-Hasan"], 0,
             "Ibrâhîm, né à Médine, mourut enfant ; le Prophète ﷺ pleura et dit que le cœur s'attriste sans dire ce qui déplaît à Allah.",
             "Sîra — fait établi"),
        en=L("What was the name of the Prophet's ﷺ son born in Madinah, who died as a small child?",
             ["Ibrahim", "Al-Qasim", "'Abdullah", "Al-Hasan"], 0,
             "Ibrahim, born in Madinah, died as an infant; the Prophet ﷺ wept and said the heart grieves without saying what displeases Allah.",
             "Sira — established fact"),
        ar=L("ما اسم ابن النبي ﷺ الذي وُلد في المدينة ومات صغيرًا؟",
             ["إبراهيم", "القاسم", "عبد الله", "الحسن"], 0,
             "إبراهيم، وُلد في المدينة ومات رضيعًا، فبكى النبي ﷺ وقال إن القلب يحزن ولا نقول إلا ما يرضي ربنا.",
             "السيرة — حقيقة ثابتة"))

    add("sira_104", "sira", "medium", "sira", S, WE, False,
        fr=L("Pour qui le Prophète ﷺ mena-t-il une caravane commerciale vers la Syrie avant la révélation ?",
             ["Khadîja", "Abû Bakr", "Abû Sufyân", "Al-'Abbâs"], 0,
             "Khadîja, riche commerçante, lui confia sa caravane vers la Syrie, puis lui proposa le mariage.",
             "Sîra — fait établi"),
        en=L("For whom did the Prophet ﷺ lead a trade caravan to Syria before the revelation?",
             ["Khadija", "Abu Bakr", "Abu Sufyan", "Al-'Abbas"], 0,
             "Khadija, a wealthy merchant, entrusted him with her caravan to Syria, then proposed marriage.",
             "Sira — established fact"),
        ar=L("لمن قاد النبي ﷺ قافلة تجارية إلى الشام قبل البعثة؟",
             ["خديجة", "أبو بكر", "أبو سفيان", "العباس"], 0,
             "استأجرته خديجة التاجرة الغنية لتجارتها إلى الشام، ثم عرضت عليه الزواج.",
             "السيرة — حقيقة ثابتة"))

    add("sira_105", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment le jeune Muhammad ﷺ régla-t-il la dispute des clans sur la remise en place de la Pierre noire ?",
             ["Il la posa sur un tissu que chaque clan souleva, puis la plaça lui-même", "Il la porta seul", "Il tira au sort", "Il la confia à Abû Bakr"], 0,
             "Il étendit un manteau, y posa la Pierre, fit soulever le tissu par les chefs des clans, puis la mit en place de sa main.",
             "Sîra — fait établi"),
        en=L("How did the young Muhammad ﷺ settle the clans' dispute over replacing the Black Stone?",
             ["He laid it on a cloth that every clan lifted, then set it himself", "He carried it alone", "He drew lots", "He entrusted it to Abu Bakr"], 0,
             "He spread a cloak, placed the Stone on it, had the clan chiefs lift the cloth together, then set it in place with his own hand.",
             "Sira — established fact"),
        ar=L("كيف حسم محمد ﷺ الشاب نزاع القبائل على وضع الحجر الأسود؟",
             ["وضعه في ثوب رفعه كل القبائل ثم وضعه بيده", "حمله وحده", "أجرى القرعة", "أعطاه لأبي بكر"], 0,
             "بسط رداءً ووضع فيه الحجر، ورفعه رؤساء القبائل جميعًا، ثم وضعه بيده في مكانه.",
             "السيرة — حقيقة ثابتة"))

    add("sira_106", "sira", "easy", "sira", S, WE, False,
        fr=L("À quel âge le Prophète ﷺ reçut-il la première révélation ?",
             ["Quarante ans", "Vingt-cinq ans", "Cinquante ans", "Soixante ans"], 0,
             "La révélation commença alors qu'il avait quarante ans, dans la grotte de Hirâ.",
             "Sîra — fait établi"),
        en=L("At what age did the Prophet ﷺ receive the first revelation?",
             ["Forty", "Twenty-five", "Fifty", "Sixty"], 0,
             "The revelation began when he was forty years old, in the cave of Hira.",
             "Sira — established fact"),
        ar=L("في أي سن نزل الوحي الأول على النبي ﷺ؟",
             ["أربعين سنة", "خمس وعشرين", "خمسين", "ستين"], 0,
             "بدأ الوحي وهو ابن أربعين سنة، في غار حراء.",
             "السيرة — حقيقة ثابتة"))

    add("sira_107", "sira", "medium", "hadithBukhari", B, "3", False,
        fr=L("Chez quel cousin de Khadîja, connaisseur des Écritures, le Prophète ﷺ fut-il conduit après la première révélation ?",
             ["Waraqa ibn Nawfal", "Abû Tâlib", "Abû Lahab", "Al-Walîd"], 0,
             "Waraqa dit : « C'est le Nâmûs (l'ange) qu'Allah envoya à Mûsâ. »",
             "Sahîh al-Bukhârî, 3"),
        en=L("To which cousin of Khadija, learned in the Scriptures, was the Prophet ﷺ taken after the first revelation?",
             ["Waraqa ibn Nawfal", "Abu Talib", "Abu Lahab", "Al-Walid"], 0,
             "Waraqa said: \"This is the Namus (the angel) whom Allah sent to Musa.\"",
             "Sahih al-Bukhari, 3"),
        ar=L("إلى أي ابن عمّ لخديجة عالم بالكتب ذهبت به بعد الوحي الأول؟",
             ["ورقة بن نوفل", "أبو طالب", "أبو لهب", "الوليد"], 0,
             "قال ورقة: «هذا الناموس الذي نزّل الله على موسى».",
             "صحيح البخاري، 3"))

    add("sira_108", "sira", "hard", "hadithBukhari", B, "4770", False,
        fr=L("Sur quelle colline le Prophète ﷺ monta-t-il pour appeler publiquement Quraysh, après le verset « Avertis tes proches » ?",
             ["As-Safâ", "Uhud", "Arafat", "Hirâ"], 0,
             "Il monta sur as-Safâ, appela les clans de Quraysh et les avertit d'un châtiment sévère.",
             "Sahîh al-Bukhârî, 4770"),
        en=L("On which hill did the Prophet ﷺ climb to call Quraysh publicly, after the verse \"Warn your closest kin\"?",
             ["As-Safa", "Uhud", "Arafat", "Hira"], 0,
             "He climbed as-Safa, called the clans of Quraysh and warned them of a severe punishment.",
             "Sahih al-Bukhari, 4770"),
        ar=L("على أي جبل صعد النبي ﷺ ليدعو قريشًا جهرًا بعد نزول ﴿وأنذر عشيرتك الأقربين﴾؟",
             ["الصفا", "أُحد", "عرفات", "حراء"], 0,
             "صعد الصفا ونادى بطون قريش وأنذرهم عذابًا شديدًا.",
             "صحيح البخاري، 4770"))

    add("sira_109", "sira", "medium", "sira", S, WE, False,
        fr=L("Quel calife institua le calendrier musulman à partir de l'année de l'Hégire ?",
             ["'Umar ibn al-Khattâb", "Abû Bakr", "'Uthmân", "'Alî"], 0,
             "Sous 'Umar, l'Hégire fut choisie comme point de départ du calendrier.",
             "Sîra — fait établi"),
        en=L("Which caliph established the Muslim calendar starting from the year of the Hijra?",
             ["'Umar ibn al-Khattab", "Abu Bakr", "'Uthman", "'Ali"], 0,
             "Under 'Umar, the Hijra was chosen as the starting point of the calendar.",
             "Sira — established fact"),
        ar=L("أي خليفة جعل بداية التقويم الإسلامي من سنة الهجرة؟",
             ["عمر بن الخطاب", "أبو بكر", "عثمان", "علي"], 0,
             "في عهد عمر اتُّخذت الهجرة مبدأً للتاريخ.",
             "السيرة — حقيقة ثابتة"))

    add("sira_110", "sira", "medium", "sira", S, WE, False,
        fr=L("Combien d'années le Prophète ﷺ vécut-il à Médine après l'Hégire ?",
             ["Dix", "Trois", "Vingt", "Treize"], 0,
             "Il vécut dix ans à Médine, de l'Hégire à sa mort en l'an 11.",
             "Sîra — fait établi"),
        en=L("How many years did the Prophet ﷺ live in Madinah after the Hijra?",
             ["Ten", "Three", "Twenty", "Thirteen"], 0,
             "He lived ten years in Madinah, from the Hijra to his death in 11 AH.",
             "Sira — established fact"),
        ar=L("كم سنة عاش النبي ﷺ في المدينة بعد الهجرة؟",
             ["عشر", "ثلاث", "عشرين", "ثلاث عشرة"], 0,
             "عاش عشر سنين في المدينة، من الهجرة إلى وفاته سنة 11.",
             "السيرة — حقيقة ثابتة"))

    add("sira_111", "sira", "medium", "sira", S, WE, False,
        fr=L("Combien d'années le Prophète ﷺ prêcha-t-il à La Mecque avant l'Hégire ?",
             ["Treize", "Trois", "Dix", "Vingt-trois"], 0,
             "Treize années à La Mecque, puis dix à Médine : vingt-trois ans de mission.",
             "Sîra — fait établi"),
        en=L("For how many years did the Prophet ﷺ preach in Makkah before the Hijra?",
             ["Thirteen", "Three", "Ten", "Twenty-three"], 0,
             "Thirteen years in Makkah, then ten in Madinah: twenty-three years of mission.",
             "Sira — established fact"),
        ar=L("كم سنة دعا النبي ﷺ في مكة قبل الهجرة؟",
             ["ثلاث عشرة", "ثلاثًا", "عشرًا", "ثلاثًا وعشرين"], 0,
             "ثلاث عشرة سنة في مكة ثم عشر في المدينة: ثلاث وعشرون سنة من الرسالة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_112", "sira", "hard", "hadithBukhari", B, "3212", False,
        fr=L("Quel compagnon, poète, défendait le Prophète ﷺ par ses vers et pour qui il demanda l'aide de Jibrîl ?",
             ["Hassân ibn Thâbit", "Ka'b ibn Mâlik", "'Abdullâh ibn Rawâha", "Labîd"], 0,
             "Le Prophète ﷺ dit à Hassân : « Réponds-leur, et Jibrîl est avec toi. »",
             "Sahîh al-Bukhârî, 3212"),
        en=L("Which companion, a poet, defended the Prophet ﷺ with his verses and for whom he asked Jibril's support?",
             ["Hassan ibn Thabit", "Ka'b ibn Malik", "'Abdullah ibn Rawaha", "Labid"], 0,
             "The Prophet ﷺ told Hassan: \"Answer them, and Jibril is with you.\"",
             "Sahih al-Bukhari, 3212"),
        ar=L("أي صحابي شاعر دافع عن النبي ﷺ بشعره وقال له النبي إن جبريل معه؟",
             ["حسان بن ثابت", "كعب بن مالك", "عبد الله بن رواحة", "لبيد"], 0,
             "قال النبي ﷺ لحسان: «أجب عني، اللهم أيّده بروح القدس».",
             "صحيح البخاري، 3212"))

    add("sira_113", "sira", "hard", "hadithBukhari", B, "5048", False,
        fr=L("De quel compagnon le Prophète ﷺ dit-il qu'il avait reçu « une des flûtes de la famille de Dâwûd » pour sa belle récitation ?",
             ["Abû Mûsâ al-Ash'arî", "Bilâl", "Ubayy ibn Ka'b", "Ibn Mas'ûd"], 0,
             "En l'écoutant réciter, le Prophète ﷺ dit qu'Abû Mûsâ avait reçu une des flûtes de la famille de Dâwûd.",
             "Sahîh al-Bukhârî, 5048"),
        en=L("Of which companion did the Prophet ﷺ say he had been given \"one of the flutes of the family of Dawud\" for his beautiful recitation?",
             ["Abu Musa al-Ash'ari", "Bilal", "Ubayy ibn Ka'b", "Ibn Mas'ud"], 0,
             "Hearing him recite, the Prophet ﷺ said Abu Musa had been given one of the flutes of the family of Dawud.",
             "Sahih al-Bukhari, 5048"),
        ar=L("عن أي صحابي قال النبي ﷺ إنه أُعطي «مزمارًا من مزامير آل داوود» لحسن قراءته؟",
             ["أبو موسى الأشعري", "بلال", "أبيّ بن كعب", "ابن مسعود"], 0,
             "لما سمعه يقرأ قال النبي ﷺ: «لقد أوتي هذا مزمارًا من مزامير آل داوود».",
             "صحيح البخاري، 5048"))

    add("sira_114", "sira", "hard", "hadithBukhari", B, "3758", False,
        fr=L("Le Prophète ﷺ recommanda d'apprendre le Coran auprès de quatre compagnons. Lequel en faisait partie ?",
             ["'Abdullâh ibn Mas'ûd", "Abû Hurayra", "Anas ibn Mâlik", "Khâlid ibn al-Walîd"], 0,
             "« Apprenez le Coran de quatre : Ibn Mas'ûd, Sâlim, Mu'âdh ibn Jabal et Ubayy ibn Ka'b. »",
             "Sahîh al-Bukhârî, 3758"),
        en=L("The Prophet ﷺ recommended learning the Quran from four companions. Which of these was one of them?",
             ["'Abdullah ibn Mas'ud", "Abu Hurayra", "Anas ibn Malik", "Khalid ibn al-Walid"], 0,
             "\"Learn the Quran from four: Ibn Mas'ud, Salim, Mu'adh ibn Jabal and Ubayy ibn Ka'b.\"",
             "Sahih al-Bukhari, 3758"),
        ar=L("أوصى النبي ﷺ بأخذ القرآن من أربعة من الصحابة. من منهم؟",
             ["عبد الله بن مسعود", "أبو هريرة", "أنس بن مالك", "خالد بن الوليد"], 0,
             "«خذوا القرآن من أربعة: من ابن مسعود، وسالم، ومعاذ بن جبل، وأبيّ بن كعب».",
             "صحيح البخاري، 3758"))

    add("sira_115", "sira", "hard", "hadithBukhari", B, "4073", False,
        fr=L("Lors de quelle bataille le Prophète ﷺ fut-il blessé au visage et perdit-il une dent ?",
             ["Uhud", "Badr", "Hunayn", "Khaybar"], 0,
             "À Uhud, sa dent fut brisée et son visage blessé.",
             "Sahîh al-Bukhârî, 4073"),
        en=L("At which battle was the Prophet ﷺ wounded in the face and lost a tooth?",
             ["Uhud", "Badr", "Hunayn", "Khaybar"], 0,
             "At Uhud, his tooth was broken and his face wounded.",
             "Sahih al-Bukhari, 4073"),
        ar=L("في أي غزوة جُرح وجه النبي ﷺ وكُسرت رباعيته؟",
             ["أُحد", "بدر", "حنين", "خيبر"], 0,
             "في أُحد كُسرت رباعيته وشُجّ وجهه.",
             "صحيح البخاري، 4073"))

    add("sira_116", "sira", "hard", "hadithBukhari", B, "4055", False,
        fr=L("À quel compagnon, archer d'Uhud, le Prophète ﷺ dit-il : « Tire ! Que mon père et ma mère soient ta rançon » ?",
             ["Sa'd ibn Abî Waqqâs", "Talha", "Az-Zubayr", "'Alî"], 0,
             "Le Prophète ﷺ lui tendait les flèches en disant : « Tire, que mon père et ma mère te soient sacrifiés. »",
             "Sahîh al-Bukhârî, 4055"),
        en=L("To which companion, an archer at Uhud, did the Prophet ﷺ say: \"Shoot! May my father and mother be your ransom\"?",
             ["Sa'd ibn Abi Waqqas", "Talha", "Az-Zubayr", "'Ali"], 0,
             "The Prophet ﷺ handed him arrows saying: \"Shoot, may my father and mother be sacrificed for you.\"",
             "Sahih al-Bukhari, 4055"),
        ar=L("لأي صحابي رامٍ يوم أُحد قال النبي ﷺ: «ارمِ فداك أبي وأمي»؟",
             ["سعد بن أبي وقاص", "طلحة", "الزبير", "علي"], 0,
             "كان النبي ﷺ يناوله النبل ويقول: «ارمِ فداك أبي وأمي».",
             "صحيح البخاري، 4055"))

    add("sira_117", "sira", "medium", "sira", S, WE, False,
        fr=L("Quelle caravane les musulmans partirent-ils intercepter, ce qui mena à la bataille de Badr ?",
             ["Celle d'Abû Sufyân, revenant de Syrie", "Celle du Négus", "Celle des Perses", "Celle de Tâ'if"], 0,
             "La caravane de Quraysh menée par Abû Sufyân échappa, mais l'armée mecquoise vint à Badr.",
             "Sîra — fait établi"),
        en=L("Which caravan did the Muslims set out to intercept, which led to the battle of Badr?",
             ["Abu Sufyan's, returning from Syria", "The Negus's", "The Persians'", "Ta'if's"], 0,
             "The Quraysh caravan led by Abu Sufyan escaped, but the Makkan army came to Badr.",
             "Sira — established fact"),
        ar=L("أي قافلة خرج المسلمون لاعتراضها فكانت سببًا في غزوة بدر؟",
             ["قافلة أبي سفيان العائدة من الشام", "قافلة النجاشي", "قافلة الفرس", "قافلة الطائف"], 0,
             "نجت قافلة قريش بقيادة أبي سفيان، لكن جيش مكة قدم إلى بدر.",
             "السيرة — حقيقة ثابتة"))

    add("sira_118", "sira", "hard", "sira", S, WE, False,
        fr=L("Quand le chef mecquois Abû Sufyân embrassa-t-il l'islam ?",
             ["Lors de la conquête de La Mecque", "Avant l'Hégire", "À Badr", "Après la mort du Prophète ﷺ"], 0,
             "Abû Sufyân se convertit à la veille de l'entrée du Prophète ﷺ à La Mecque.",
             "Sîra — fait établi"),
        en=L("When did the Makkan chief Abu Sufyan embrace Islam?",
             ["At the conquest of Makkah", "Before the Hijra", "At Badr", "After the Prophet's ﷺ death"], 0,
             "Abu Sufyan converted on the eve of the Prophet's ﷺ entry into Makkah.",
             "Sira — established fact"),
        ar=L("متى أسلم زعيم مكة أبو سفيان؟",
             ["عند فتح مكة", "قبل الهجرة", "في بدر", "بعد وفاة النبي ﷺ"], 0,
             "أسلم أبو سفيان عشية دخول النبي ﷺ مكة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_119", "sira", "easy", "hadithBukhari", B, "3364", False,
        fr=L("Quelle source jaillit pour Hâjar et son fils Ismâ'îl dans la vallée de La Mecque ?",
             ["Zamzam", "Le Nil", "L'Euphrate", "Le Jourdain"], 0,
             "Un ange frappa le sol et l'eau de Zamzam jaillit ; Hâjar en fit un bassin.",
             "Sahîh al-Bukhârî, 3364"),
        en=L("Which spring gushed forth for Hajar and her son Isma'il in the valley of Makkah?",
             ["Zamzam", "The Nile", "The Euphrates", "The Jordan"], 0,
             "An angel struck the ground and the water of Zamzam gushed out; Hajar made a basin around it.",
             "Sahih al-Bukhari, 3364"),
        ar=L("أي عين تفجّرت لهاجر وابنها إسماعيل في وادي مكة؟",
             ["زمزم", "النيل", "الفرات", "الأردن"], 0,
             "ضرب الملك الأرض فنبع ماء زمزم، فجعلت هاجر حوله حوضًا.",
             "صحيح البخاري، 3364"))

    add("sira_120", "sira", "hard", "hadithBukhari", B, "5872", False,
        fr=L("Qu'était-il gravé sur la bague du Prophète ﷺ ?",
             ["« Muhammad Rasûl Allah »", "« Allahu Akbar »", "« Lâ ilâha illa Allah »", "Son nom seul"], 0,
             "Sa bague d'argent portait « Muhammad, Messager d'Allah » sur trois lignes.",
             "Sahîh al-Bukhârî, 5872"),
        en=L("What was engraved on the Prophet's ﷺ ring?",
             ["\"Muhammad Rasul Allah\"", "\"Allahu Akbar\"", "\"La ilaha illa Allah\"", "His name alone"], 0,
             "His silver ring bore \"Muhammad, Messenger of Allah\" in three lines.",
             "Sahih al-Bukhari, 5872"),
        ar=L("ماذا كان منقوشًا على خاتم النبي ﷺ؟",
             ["«محمد رسول الله»", "«الله أكبر»", "«لا إله إلا الله»", "اسمه فقط"], 0,
             "كان خاتمه من فضة نقشه «محمد رسول الله» في ثلاثة أسطر.",
             "صحيح البخاري، 5872"))

    add("sira_121", "sira", "hard", "hadithBukhari", B, "5431", False,
        fr=L("Quels aliments le Prophète ﷺ aimait-il, selon 'Âisha ?",
             ["Les douceurs et le miel", "Le poisson", "Les épices fortes", "Le vinaigre seulement"], 0,
             "'Âisha rapporte que le Prophète ﷺ aimait les sucreries et le miel.",
             "Sahîh al-Bukhârî, 5431"),
        en=L("Which foods did the Prophet ﷺ like, according to 'Aisha?",
             ["Sweets and honey", "Fish", "Strong spices", "Vinegar only"], 0,
             "'Aisha reports that the Prophet ﷺ loved sweet things and honey.",
             "Sahih al-Bukhari, 5431"),
        ar=L("أي الأطعمة كان النبي ﷺ يحب بحسب عائشة؟",
             ["الحلواء والعسل", "السمك", "التوابل الحارة", "الخل فقط"], 0,
             "روت عائشة أن النبي ﷺ كان يحب الحلواء والعسل.",
             "صحيح البخاري، 5431"))

    add("sira_122", "sira", "medium", "hadithMuslim", M, "1162", False,
        fr=L("Quel jour de la semaine le Prophète ﷺ est-il né, jour où il jeûnait aussi ?",
             ["Le lundi", "Le vendredi", "Le samedi", "Le mercredi"], 0,
             "Interrogé sur le jeûne du lundi, il dit : « C'est le jour où je suis né et où la révélation m'est parvenue. »",
             "Sahîh Muslim, 1162"),
        en=L("On which day of the week was the Prophet ﷺ born, a day on which he also fasted?",
             ["Monday", "Friday", "Saturday", "Wednesday"], 0,
             "Asked about fasting on Monday, he said: \"That is the day I was born and the day revelation came to me.\"",
             "Sahih Muslim, 1162"),
        ar=L("في أي يوم من الأسبوع وُلد النبي ﷺ، وكان يصومه؟",
             ["الاثنين", "الجمعة", "السبت", "الأربعاء"], 0,
             "سُئل عن صوم الاثنين فقال: «ذاك يوم وُلدت فيه، ويوم أُنزل عليّ فيه».",
             "صحيح مسلم، 1162"))

    add("sira_123", "sira", "hard", "hadithBukhari", B, "3541", False,
        fr=L("Où se trouvait le « sceau de la prophétie » sur le corps du Prophète ﷺ ?",
             ["Entre ses épaules", "Sur sa main", "Sur son front", "Sur sa poitrine"], 0,
             "Le sceau de la prophétie se trouvait entre ses épaules.",
             "Sahîh al-Bukhârî, 3541"),
        en=L("Where was the \"seal of prophethood\" on the Prophet's ﷺ body?",
             ["Between his shoulders", "On his hand", "On his forehead", "On his chest"], 0,
             "The seal of prophethood was between his shoulders.",
             "Sahih al-Bukhari, 3541"),
        ar=L("أين كان «خاتم النبوة» في جسد النبي ﷺ؟",
             ["بين كتفيه", "على يده", "على جبينه", "على صدره"], 0,
             "كان خاتم النبوة بين كتفيه.",
             "صحيح البخاري، 3541"))

    add("sira_124", "sira", "hard", "hadithBukhari", B, "917", False,
        fr=L("De quel bois fut fait le minbar (chaire) du Prophète ﷺ, fabriqué par un charpentier ?",
             ["Du tamaris (athl)", "Du cèdre", "De l'olivier", "Du palmier"], 0,
             "Le Prophète ﷺ fit faire un minbar en bois de tamaris pour s'adresser aux gens.",
             "Sahîh al-Bukhârî, 917"),
        en=L("From which wood was the Prophet's ﷺ minbar (pulpit) made, by a carpenter?",
             ["Tamarisk (athl)", "Cedar", "Olive", "Palm"], 0,
             "The Prophet ﷺ had a minbar made of tamarisk wood, from which he addressed the people.",
             "Sahih al-Bukhari, 917"),
        ar=L("من أي خشب صُنع منبر النبي ﷺ على يد نجّار؟",
             ["من الأثل (الطرفاء)", "من الأرز", "من الزيتون", "من النخل"], 0,
             "أمر النبي ﷺ بصنع منبر من طرفاء الغابة ليخاطب الناس عليه.",
             "صحيح البخاري، 917"))

    add("sira_125", "sira", "medium", "sira", S, WE, False,
        fr=L("Quelles étaient les deux grandes tribus de Médine qui formèrent les Ansâr ?",
             ["Les Aws et les Khazraj", "Quraysh et Thaqîf", "Tamîm et Hawâzin", "Kinda et Hamdân"], 0,
             "Les Aws et les Khazraj, longtemps rivales, s'unirent dans l'islam et devinrent les Ansâr.",
             "Sîra — fait établi"),
        en=L("Which two great tribes of Madinah formed the Ansar?",
             ["The Aws and the Khazraj", "Quraysh and Thaqif", "Tamim and Hawazin", "Kinda and Hamdan"], 0,
             "The Aws and the Khazraj, long-time rivals, united in Islam and became the Ansar.",
             "Sira — established fact"),
        ar=L("ما القبيلتان الكبيرتان في المدينة اللتان صارتا الأنصار؟",
             ["الأوس والخزرج", "قريش وثقيف", "تميم وهوازن", "كندة وهمدان"], 0,
             "اتحدت الأوس والخزرج بعد عداوة طويلة في الإسلام وصارتا الأنصار.",
             "السيرة — حقيقة ثابتة"))

    add("sira_126", "sira", "easy", "quran", Q, "33:6", False,
        fr=L("Quel titre le Coran donne-t-il aux épouses du Prophète ﷺ ?",
             ["Les Mères des croyants", "Les reines de Médine", "Les filles de Quraysh", "Les gardiennes du Livre"], 0,
             "« Ses épouses sont leurs mères » : les Mères des croyants.",
             "Coran — Sourate Al-Ahzâb, 33:6"),
        en=L("What title does the Quran give the wives of the Prophet ﷺ?",
             ["The Mothers of the Believers", "The queens of Madinah", "The daughters of Quraysh", "The keepers of the Book"], 0,
             "\"His wives are their mothers\": the Mothers of the Believers.",
             "Quran — Surah Al-Ahzab, 33:6"),
        ar=L("ما اللقب الذي أعطاه القرآن لزوجات النبي ﷺ؟",
             ["أمهات المؤمنين", "ملكات المدينة", "بنات قريش", "حافظات الكتاب"], 0,
             "﴿وأزواجه أمهاتهم﴾: أمهات المؤمنين.",
             "القرآن — سورة الأحزاب، 33:6"))

    add("sira_127", "sira", "medium", "sira", S, WE, False,
        fr=L("En quelle année du calendrier chrétien eut lieu l'Hégire ?",
             ["622", "570", "632", "610"], 0,
             "L'Hégire, en 622, marque le début du calendrier musulman.",
             "Sîra — fait établi"),
        en=L("In which year of the Christian calendar did the Hijra take place?",
             ["622", "570", "632", "610"], 0,
             "The Hijra, in 622, marks the start of the Muslim calendar.",
             "Sira — established fact"),
        ar=L("في أي سنة ميلادية كانت الهجرة؟",
             ["622", "570", "632", "610"], 0,
             "كانت الهجرة سنة 622م، وبها يبدأ التقويم الهجري.",
             "السيرة — حقيقة ثابتة"))

    add("sira_128", "sira", "hard", "hadithBukhari", B, "2048", False,
        fr=L("Que répondit 'Abd ar-Rahmân ibn 'Awf quand son frère ansarite lui offrit la moitié de ses biens ?",
             ["« Montre-moi le marché »", "Il accepta tout", "Il demanda une maison", "Il refusa de parler"], 0,
             "Il dit : « Qu'Allah bénisse tes biens et ta famille ; montre-moi plutôt le marché », et fit fortune en commerçant.",
             "Sahîh al-Bukhârî, 2048"),
        en=L("What did 'Abd ar-Rahman ibn 'Awf reply when his Ansari brother offered him half of his wealth?",
             ["\"Show me the market\"", "He accepted everything", "He asked for a house", "He refused to speak"], 0,
             "He said: \"May Allah bless your wealth and family; just show me the market,\" and prospered through trade.",
             "Sahih al-Bukhari, 2048"),
        ar=L("بماذا أجاب عبد الرحمن بن عوف حين عرض عليه أخوه الأنصاري نصف ماله؟",
             ["«دلّني على السوق»", "قبل كل شيء", "طلب بيتًا", "رفض الكلام"], 0,
             "قال: «بارك الله لك في أهلك ومالك، دلّوني على السوق»، فاتّجر وربح.",
             "صحيح البخاري، 2048"))

    add("sira_129", "sira", "medium", "hadithMuslim", M, "810", False,
        fr=L("À quel compagnon le Prophète ﷺ demanda-t-il quel verset du Coran est le plus grand, avant de le féliciter pour sa réponse (le Verset du Trône) ?",
             ["Ubayy ibn Ka'b", "Abû Bakr", "Zayd ibn Thâbit", "Bilâl"], 0,
             "Ubayy répondit : « Allah, nulle divinité à part Lui, le Vivant… » ; le Prophète ﷺ dit : « Que la science te soit agréable, Abû al-Mundhir ! »",
             "Sahîh Muslim, 810"),
        en=L("Which companion did the Prophet ﷺ ask which verse of the Quran is the greatest, before congratulating him on his answer (the Throne Verse)?",
             ["Ubayy ibn Ka'b", "Abu Bakr", "Zayd ibn Thabit", "Bilal"], 0,
             "Ubayy answered: \"Allah, there is no god but He, the Ever-Living…\"; the Prophet ﷺ said: \"May knowledge delight you, Abu al-Mundhir!\"",
             "Sahih Muslim, 810"),
        ar=L("أي صحابي سأله النبي ﷺ عن أعظم آية في القرآن ثم هنّأه على جوابه (آية الكرسي)؟",
             ["أبيّ بن كعب", "أبو بكر", "زيد بن ثابت", "بلال"], 0,
             "أجاب أبيّ: ﴿الله لا إله إلا هو الحي القيوم﴾، فقال ﷺ: «ليهنك العلم أبا المنذر».",
             "صحيح مسلم، 810"))

    add("sira_130", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment fut choisi l'emplacement de la mosquée du Prophète ﷺ à Médine ?",
             ["Là où sa chamelle s'agenouilla", "Par tirage au sort", "Au centre du marché", "Sur le mont Uhud"], 0,
             "Il laissa sa chamelle avancer librement : là où elle s'agenouilla fut construite la mosquée.",
             "Sîra — fait établi"),
        en=L("How was the site of the Prophet's ﷺ mosque in Madinah chosen?",
             ["Where his she-camel knelt", "By drawing lots", "In the centre of the market", "On Mount Uhud"], 0,
             "He let his she-camel walk freely: where she knelt, the mosque was built.",
             "Sira — established fact"),
        ar=L("كيف اختير موضع مسجد النبي ﷺ في المدينة؟",
             ["حيث بركت ناقته", "بالقرعة", "في وسط السوق", "على جبل أُحد"], 0,
             "ترك ناقته تسير حتى بركت، فبُني المسجد في موضعها.",
             "السيرة — حقيقة ثابتة"))

    add("sira_131", "sira", "hard", "sira", S, WE, False,
        fr=L("Combien de fils le Prophète ﷺ a-t-il eus, tous morts en bas âge ?",
             ["Trois", "Un", "Cinq", "Aucun"], 0,
             "Al-Qâsim et 'Abdullâh, nés de Khadîja, et Ibrâhîm, né à Médine.",
             "Sîra — fait établi"),
        en=L("How many sons did the Prophet ﷺ have, all of whom died young?",
             ["Three", "One", "Five", "None"], 0,
             "Al-Qasim and 'Abdullah, born to Khadija, and Ibrahim, born in Madinah.",
             "Sira — established fact"),
        ar=L("كم ابنًا كان للنبي ﷺ، وماتوا جميعًا صغارًا؟",
             ["ثلاثة", "واحد", "خمسة", "لا أحد"], 0,
             "القاسم وعبد الله من خديجة، وإبراهيم الذي وُلد في المدينة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_132", "sira", "easy", "sira", S, WE, False,
        fr=L("Quel compagnon, affranchi par le Prophète ﷺ et élevé comme un fils, fut le père d'Usâma ?",
             ["Zayd ibn Hâritha", "Bilâl", "Salmân", "'Ammâr"], 0,
             "Zayd ibn Hâritha, aimé du Prophète ﷺ, fut le père d'Usâma ibn Zayd.",
             "Sîra — fait établi"),
        en=L("Which companion, freed by the Prophet ﷺ and raised like a son, was the father of Usama?",
             ["Zayd ibn Haritha", "Bilal", "Salman", "'Ammar"], 0,
             "Zayd ibn Haritha, beloved of the Prophet ﷺ, was the father of Usama ibn Zayd.",
             "Sira — established fact"),
        ar=L("أي صحابي أعتقه النبي ﷺ وربّاه كابنه وكان أبا أسامة؟",
             ["زيد بن حارثة", "بلال", "سلمان", "عمّار"], 0,
             "زيد بن حارثة، حِبّ النبي ﷺ، والد أسامة بن زيد.",
             "السيرة — حقيقة ثابتة"))

    add("sira_133", "sira", "medium", "hadithBukhari", B, "4469", False,
        fr=L("Quel jeune compagnon le Prophète ﷺ nomma-t-il à la tête d'une armée peu avant sa mort, malgré son jeune âge ?",
             ["Usâma ibn Zayd", "Anas ibn Mâlik", "Ibn 'Abbâs", "Ibn 'Umar"], 0,
             "Le Prophète ﷺ confia le commandement à Usâma et répondit à ceux qui critiquaient son âge qu'il en était digne, comme son père.",
             "Sahîh al-Bukhârî, 4469"),
        en=L("Which young companion did the Prophet ﷺ appoint to lead an army shortly before his death, despite his youth?",
             ["Usama ibn Zayd", "Anas ibn Malik", "Ibn 'Abbas", "Ibn 'Umar"], 0,
             "The Prophet ﷺ gave Usama the command and answered those who criticised his age that he was worthy of it, like his father.",
             "Sahih al-Bukhari, 4469"),
        ar=L("أي صحابي شاب أمّره النبي ﷺ على جيش قبيل وفاته رغم صغر سنه؟",
             ["أسامة بن زيد", "أنس بن مالك", "ابن عباس", "ابن عمر"], 0,
             "أمّر النبي ﷺ أسامة، وردّ على من طعن في إمارته بأنه خليق بها كما كان أبوه.",
             "صحيح البخاري، 4469"))

    add("sira_134", "sira", "medium", "sira", S, WE, False,
        fr=L("Quel grand-père du Prophète ﷺ fit recreuser le puits de Zamzam, comblé depuis longtemps ?",
             ["'Abd al-Muttalib", "Hâshim", "'Abd Manâf", "Qusayy"], 0,
             "'Abd al-Muttalib recreusa Zamzam et en assura la garde pour les pèlerins.",
             "Sîra — fait établi"),
        en=L("Which grandfather of the Prophet ﷺ re-dug the well of Zamzam, long filled in?",
             ["'Abd al-Muttalib", "Hashim", "'Abd Manaf", "Qusayy"], 0,
             "'Abd al-Muttalib re-dug Zamzam and took charge of it for the pilgrims.",
             "Sira — established fact"),
        ar=L("أي جدٍّ للنبي ﷺ أعاد حفر بئر زمزم بعد أن طُمرت زمنًا طويلًا؟",
             ["عبد المطلب", "هاشم", "عبد مناف", "قصيّ"], 0,
             "أعاد عبد المطلب حفر زمزم وتولّى سقاية الحجيج.",
             "السيرة — حقيقة ثابتة"))

    add("sira_135", "sira", "hard", "sira", S, WE, False,
        fr=L("Combien de personnes environ accompagnèrent le Prophète ﷺ à la bataille de Badr ?",
             ["Un peu plus de trois cents", "Dix mille", "Mille", "Cinquante"], 0,
             "Les musulmans à Badr étaient un peu plus de trois cents, face à une armée bien plus nombreuse.",
             "Sîra — fait établi"),
        en=L("Roughly how many people accompanied the Prophet ﷺ at the battle of Badr?",
             ["A little over three hundred", "Ten thousand", "A thousand", "Fifty"], 0,
             "The Muslims at Badr were a little over three hundred, facing a much larger army.",
             "Sira — established fact"),
        ar=L("كم كان عدد المسلمين تقريبًا مع النبي ﷺ في بدر؟",
             ["ثلاثمئة وبضعة عشر", "عشرة آلاف", "ألف", "خمسون"], 0,
             "كان المسلمون في بدر ثلاثمئة وبضعة عشر رجلًا أمام جيش أكبر بكثير.",
             "السيرة — حقيقة ثابتة"))

    add("sira_136", "sira", "easy", "sira", S, WE, False,
        fr=L("Dans quel mois du calendrier musulman le Prophète ﷺ est-il né ?",
             ["Rabî' al-Awwal", "Ramadan", "Muharram", "Dhul-Hijja"], 0,
             "Il est né au mois de Rabî' al-Awwal, l'année de l'Éléphant.",
             "Sîra — fait établi"),
        en=L("In which month of the Muslim calendar was the Prophet ﷺ born?",
             ["Rabi' al-Awwal", "Ramadan", "Muharram", "Dhul-Hijja"], 0,
             "He was born in the month of Rabi' al-Awwal, in the Year of the Elephant.",
             "Sira — established fact"),
        ar=L("في أي شهر من الأشهر الهجرية وُلد النبي ﷺ؟",
             ["ربيع الأول", "رمضان", "محرّم", "ذو الحجة"], 0,
             "وُلد في شهر ربيع الأول عام الفيل.",
             "السيرة — حقيقة ثابتة"))

    add("sira_137", "sira", "hard", "sira", S, WE, False,
        fr=L("Dans quel mois le Prophète ﷺ arriva-t-il à Médine lors de l'Hégire ?",
             ["Rabî' al-Awwal", "Ramadan", "Muharram", "Rajab"], 0,
             "Il arriva à Médine en Rabî' al-Awwal, après s'être arrêté à Qubâ.",
             "Sîra — fait établi"),
        en=L("In which month did the Prophet ﷺ arrive in Madinah during the Hijra?",
             ["Rabi' al-Awwal", "Ramadan", "Muharram", "Rajab"], 0,
             "He arrived in Madinah in Rabi' al-Awwal, after stopping at Quba.",
             "Sira — established fact"),
        ar=L("في أي شهر وصل النبي ﷺ إلى المدينة مهاجرًا؟",
             ["ربيع الأول", "رمضان", "محرّم", "رجب"], 0,
             "وصل المدينة في ربيع الأول بعد أن نزل بقباء.",
             "السيرة — حقيقة ثابتة"))

    add("sira_138", "sira", "hard", "sira", S, WE, False,
        fr=L("Quel pacte les Quraysh conclurent-ils pour isoler les Banû Hâshim, qui protégeaient le Prophète ﷺ ?",
             ["Un boycott : ni commerce ni mariage avec eux", "Une trêve de dix ans", "Un partage de la Ka'ba", "Une alliance militaire"], 0,
             "Les Quraysh signèrent un pacte de boycott, et les Banû Hâshim furent confinés dans une vallée pendant des années.",
             "Sîra — fait établi"),
        en=L("What pact did Quraysh make to isolate Banu Hashim, who protected the Prophet ﷺ?",
             ["A boycott: no trade or marriage with them", "A ten-year truce", "A sharing of the Ka'ba", "A military alliance"], 0,
             "Quraysh signed a boycott pact, and Banu Hashim were confined to a valley for years.",
             "Sira — established fact"),
        ar=L("ما العهد الذي عقدته قريش لعزل بني هاشم الذين حموا النبي ﷺ؟",
             ["مقاطعة: لا بيع ولا زواج معهم", "هدنة عشر سنين", "قسمة الكعبة", "حلف عسكري"], 0,
             "كتبت قريش صحيفة المقاطعة، وحُصر بنو هاشم في الشِّعب سنوات.",
             "السيرة — حقيقة ثابتة"))

    add("sira_139", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment le Prophète ﷺ commença-t-il sa mission à La Mecque, avant l'appel public ?",
             ["Par un appel discret à ses proches", "Par une armée", "Par une lettre aux rois", "Par un pèlerinage"], 0,
             "Il appela d'abord discrètement ses proches et amis, avant que l'appel ne devienne public.",
             "Sîra — fait établi"),
        en=L("How did the Prophet ﷺ begin his mission in Makkah, before the public call?",
             ["By calling his close circle discreetly", "With an army", "With a letter to kings", "With a pilgrimage"], 0,
             "He first called his relatives and friends privately, before the call became public.",
             "Sira — established fact"),
        ar=L("كيف بدأ النبي ﷺ دعوته في مكة قبل الجهر بها؟",
             ["بدعوة سرّية لأقربائه وأصحابه", "بجيش", "برسالة إلى الملوك", "بحج"], 0,
             "دعا أولًا أقاربه وأصدقاءه سرًّا قبل أن يجهر بالدعوة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_140", "sira", "easy", "hadithBukhari", B, "3364", False,
        fr=L("Entre quelles deux collines Hâjar courut-elle à la recherche d'eau pour Ismâ'îl ?",
             ["As-Safâ et Al-Marwa", "Uhud et Thawr", "Arafat et Minâ", "Hirâ et Thawr"], 0,
             "Elle courut sept fois entre as-Safâ et al-Marwa : c'est l'origine du sa'y des pèlerins.",
             "Sahîh al-Bukhârî, 3364"),
        en=L("Between which two hills did Hajar run looking for water for Isma'il?",
             ["As-Safa and Al-Marwa", "Uhud and Thawr", "Arafat and Mina", "Hira and Thawr"], 0,
             "She ran seven times between as-Safa and al-Marwa: the origin of the pilgrims' sa'y.",
             "Sahih al-Bukhari, 3364"),
        ar=L("بين أي جبلين سعت هاجر تبحث عن الماء لإسماعيل؟",
             ["الصفا والمروة", "أُحد وثور", "عرفات ومنى", "حراء وثور"], 0,
             "سعت سبع مرات بين الصفا والمروة، ومن هنا سعي الحجاج.",
             "صحيح البخاري، 3364"))

    add("sira_141", "sira", "medium", "hadithBukhari", B, "2704", False,
        fr=L("De quel petit-fils le Prophète ﷺ dit-il : « Ce fils que voici est un sayyid ; Allah réconciliera par lui deux groupes de musulmans » ?",
             ["Al-Hasan", "Al-Husayn", "Usâma", "Ibn 'Abbâs"], 0,
             "Al-Hasan ibn 'Alî réconcilia plus tard deux grands groupes de musulmans, comme le Prophète ﷺ l'avait annoncé.",
             "Sahîh al-Bukhârî, 2704"),
        en=L("Of which grandson did the Prophet ﷺ say: \"This son of mine is a sayyid; Allah will reconcile two groups of Muslims through him\"?",
             ["Al-Hasan", "Al-Husayn", "Usama", "Ibn 'Abbas"], 0,
             "Al-Hasan ibn 'Ali later reconciled two large groups of Muslims, as the Prophet ﷺ had foretold.",
             "Sahih al-Bukhari, 2704"),
        ar=L("عن أي حفيد قال النبي ﷺ: «ابني هذا سيد، ولعل الله أن يصلح به بين فئتين من المسلمين»؟",
             ["الحسن", "الحسين", "أسامة", "ابن عباس"], 0,
             "أصلح الحسن بن علي لاحقًا بين فئتين عظيمتين من المسلمين كما أخبر النبي ﷺ.",
             "صحيح البخاري، 2704"))

    add("sira_142", "sira", "easy", "sira", S, WE, False,
        fr=L("Comment s'appelait la fille du Prophète ﷺ, mère d'Al-Hasan et d'Al-Husayn ?",
             ["Fâtima", "Zaynab", "Ruqayya", "Umm Kulthûm"], 0,
             "Fâtima, épouse de 'Alî, fut la mère d'Al-Hasan et d'Al-Husayn.",
             "Sîra — fait établi"),
        en=L("What was the name of the Prophet's ﷺ daughter, mother of Al-Hasan and Al-Husayn?",
             ["Fatima", "Zaynab", "Ruqayya", "Umm Kulthum"], 0,
             "Fatima, wife of 'Ali, was the mother of Al-Hasan and Al-Husayn.",
             "Sira — established fact"),
        ar=L("ما اسم بنت النبي ﷺ أم الحسن والحسين؟",
             ["فاطمة", "زينب", "رقية", "أم كلثوم"], 0,
             "فاطمة زوجة علي، أم الحسن والحسين.",
             "السيرة — حقيقة ثابتة"))

    add("sira_143", "sira", "medium", "sira", S, WE, False,
        fr=L("Quelle était la fille aînée du Prophète ﷺ ?",
             ["Zaynab", "Fâtima", "Ruqayya", "Umm Kulthûm"], 0,
             "Zaynab était l'aînée des quatre filles du Prophète ﷺ.",
             "Sîra — fait établi"),
        en=L("Who was the eldest daughter of the Prophet ﷺ?",
             ["Zaynab", "Fatima", "Ruqayya", "Umm Kulthum"], 0,
             "Zaynab was the eldest of the Prophet's ﷺ four daughters.",
             "Sira — established fact"),
        ar=L("من كانت كبرى بنات النبي ﷺ؟",
             ["زينب", "فاطمة", "رقية", "أم كلثوم"], 0,
             "زينب هي كبرى بنات النبي ﷺ الأربع.",
             "السيرة — حقيقة ثابتة"))

    add("sira_144", "sira", "easy", "sira", S, WE, False,
        fr=L("Quel compagnon, ancien esclave d'origine abyssinienne, fut choisi pour sa belle voix comme muezzin ?",
             ["Bilâl ibn Rabâh", "Salmân", "Suhayb", "Zayd"], 0,
             "Bilâl, affranchi par Abû Bakr, devint le muezzin du Prophète ﷺ.",
             "Sîra — fait établi"),
        en=L("Which companion, a former slave of Abyssinian origin, was chosen as muezzin for his beautiful voice?",
             ["Bilal ibn Rabah", "Salman", "Suhayb", "Zayd"], 0,
             "Bilal, freed by Abu Bakr, became the Prophet's ﷺ muezzin.",
             "Sira — established fact"),
        ar=L("أي صحابي حبشي الأصل كان عبدًا واختير مؤذّنًا لجمال صوته؟",
             ["بلال بن رباح", "سلمان", "صهيب", "زيد"], 0,
             "بلال الذي أعتقه أبو بكر صار مؤذّن النبي ﷺ.",
             "السيرة — حقيقة ثابتة"))

    add("sira_145", "sira", "hard", "hadithBukhari", B, "3661", False,
        fr=L("De quel compagnon le Prophète ﷺ dit-il : « Si je devais prendre un ami intime (khalîl) parmi les hommes, ce serait lui » ?",
             ["Abû Bakr", "'Umar", "'Alî", "'Uthmân"], 0,
             "« Si j'avais pris un ami intime parmi ma communauté, j'aurais pris Abû Bakr, mais il est mon frère et mon compagnon. »",
             "Sahîh al-Bukhârî, 3661"),
        en=L("Of which companion did the Prophet ﷺ say: \"If I were to take a bosom friend (khalil) from among men, it would be him\"?",
             ["Abu Bakr", "'Umar", "'Ali", "'Uthman"], 0,
             "\"If I were to take a bosom friend from my nation, I would take Abu Bakr, but he is my brother and companion.\"",
             "Sahih al-Bukhari, 3661"),
        ar=L("عن أي صحابي قال النبي ﷺ: «لو كنت متخذًا خليلًا من الناس لاتخذته»؟",
             ["أبو بكر", "عمر", "علي", "عثمان"], 0,
             "«لو كنت متخذًا من أمتي خليلًا لاتخذت أبا بكر، ولكن أخي وصاحبي».",
             "صحيح البخاري، 3661"))

    add("sira_146", "sira", "medium", "sira", S, WE, False,
        fr=L("Quelle ville, avec La Mecque, est appelée « al-Haramayn », les deux sanctuaires ?",
             ["Médine", "Jérusalem", "Tâ'if", "Damas"], 0,
             "La Mecque et Médine sont les deux villes saintes, al-Haramayn.",
             "Sîra — terminologie établie"),
        en=L("Which city, together with Makkah, is called \"al-Haramayn\", the two sanctuaries?",
             ["Madinah", "Jerusalem", "Ta'if", "Damascus"], 0,
             "Makkah and Madinah are the two holy cities, al-Haramayn.",
             "Sira — established terminology"),
        ar=L("أي مدينة تُسمّى مع مكة «الحرمين»؟",
             ["المدينة", "القدس", "الطائف", "دمشق"], 0,
             "مكة والمدينة هما الحرمان الشريفان.",
             "السيرة — مصطلح ثابت"))

    add("sira_147", "sira", "medium", "sira", S, WE, False,
        fr=L("Combien de fois le Prophète ﷺ accomplit-il le Hajj après l'Hégire ?",
             ["Une fois, le pèlerinage d'adieu", "Trois fois", "Chaque année", "Jamais"], 0,
             "Il n'accomplit qu'un seul Hajj après l'Hégire : le pèlerinage d'adieu, en l'an 10.",
             "Sîra — fait établi"),
        en=L("How many times did the Prophet ﷺ perform Hajj after the Hijra?",
             ["Once, the Farewell Pilgrimage", "Three times", "Every year", "Never"], 0,
             "He performed only one Hajj after the Hijra: the Farewell Pilgrimage, in 10 AH.",
             "Sira — established fact"),
        ar=L("كم مرة حجّ النبي ﷺ بعد الهجرة؟",
             ["مرة واحدة: حجة الوداع", "ثلاث مرات", "كل سنة", "لم يحج"], 0,
             "لم يحج بعد الهجرة إلا حجة واحدة: حجة الوداع سنة 10.",
             "السيرة — حقيقة ثابتة"))

    add("sira_148", "sira", "hard", "hadithBukhari", B, "3149", False,
        fr=L("Selon Anas, que dit le Prophète ﷺ quand un bédouin tira violemment sur son manteau pour lui demander des biens ?",
             ["Il sourit et ordonna qu'on lui donne", "Il le fit punir", "Il partit sans rien dire", "Il le chassa"], 0,
             "Le Prophète ﷺ se tourna vers lui, rit, et ordonna qu'on lui donne quelque chose.",
             "Sahîh al-Bukhârî, 3149"),
        en=L("According to Anas, what did the Prophet ﷺ do when a Bedouin pulled hard on his cloak demanding goods?",
             ["He smiled and ordered that he be given something", "He had him punished", "He left without a word", "He drove him away"], 0,
             "The Prophet ﷺ turned to him, laughed, and ordered that he be given something.",
             "Sahih al-Bukhari, 3149"),
        ar=L("بحسب أنس، ماذا فعل النبي ﷺ حين جذب أعرابي رداءه بشدة يطلب عطاءً؟",
             ["ضحك وأمر له بعطاء", "أمر بعقابه", "انصرف دون كلام", "طرده"], 0,
             "التفت إليه النبي ﷺ فضحك ثم أمر له بعطاء.",
             "صحيح البخاري، 3149"))

    add("sira_149", "sira", "easy", "sira", S, WE, False,
        fr=L("Quelle ville, dans laquelle se trouve la mosquée al-Aqsâ, fut la destination du voyage nocturne ?",
             ["Jérusalem", "Damas", "Le Caire", "Bagdad"], 0,
             "Le voyage nocturne mena le Prophète ﷺ de La Mecque à la mosquée al-Aqsâ, à Jérusalem.",
             "Sîra — fait établi"),
        en=L("Which city, home to al-Aqsa Mosque, was the destination of the Night Journey?",
             ["Jerusalem", "Damascus", "Cairo", "Baghdad"], 0,
             "The Night Journey took the Prophet ﷺ from Makkah to al-Aqsa Mosque in Jerusalem.",
             "Sira — established fact"),
        ar=L("أي مدينة فيها المسجد الأقصى وكانت مقصد الإسراء؟",
             ["القدس", "دمشق", "القاهرة", "بغداد"], 0,
             "أُسري بالنبي ﷺ من مكة إلى المسجد الأقصى في القدس.",
             "السيرة — حقيقة ثابتة"))

    add("sira_150", "sira", "easy", "sira", S, WE, False,
        fr=L("Quel âge avait le Prophète ﷺ à sa mort ?",
             ["Soixante-trois ans", "Quarante ans", "Cinquante ans", "Quatre-vingts ans"], 0,
             "Il mourut à soixante-trois ans, en l'an 11 de l'Hégire.",
             "Sîra — fait établi"),
        en=L("How old was the Prophet ﷺ when he died?",
             ["Sixty-three", "Forty", "Fifty", "Eighty"], 0,
             "He died at the age of sixty-three, in 11 AH.",
             "Sira — established fact"),
        ar=L("كم كان عمر النبي ﷺ حين تُوفّي؟",
             ["ثلاثًا وستين سنة", "أربعين", "خمسين", "ثمانين"], 0,
             "تُوفّي وعمره ثلاث وستون سنة، في السنة 11 للهجرة.",
             "السيرة — حقيقة ثابتة"))
