"""Virtues and manners — part C (virtues_051 … virtues_100).

Weighted toward the Qur'an, where the verse states the manner plainly,
with a small number of hadiths from the two Ṣaḥīḥs whose wording and
reference are beyond doubt. Nothing here needs a school of law to
answer: these are the manners the whole community agrees on.
"""


def register(add, L):
    Q = "Quran"
    B = "Sahih al-Bukhari"
    M = "Sahih Muslim"

    add("virtues_051", "virtues", "easy", "quran", Q, "31:19", False,
        fr=L("Que conseille Luqmân à son fils au sujet de la voix ?",
             ["Baisser la voix : la plus détestable est celle de l'âne", "Parler très fort", "Ne jamais parler", "Chanter en marchant"], 0,
             "« Et sois modeste dans ta démarche, et baisse ta voix : la plus détestée des voix est bien la voix des ânes. »",
             "Coran — Sourate Luqmân, 31:19"),
        en=L("What does Luqman advise his son about the voice?",
             ["To lower it: the most hateful of voices is the braying of the donkey", "To speak very loudly", "Never to speak", "To sing while walking"], 0,
             "\"And be moderate in your pace and lower your voice: indeed, the most disagreeable of sounds is the voice of donkeys.\"",
             "Quran — Surah Luqman, 31:19"),
        ar=L("بماذا أوصى لقمانُ ابنَه في شأن الصوت؟",
             ["أن يغضّ من صوته، فإن أنكر الأصوات صوت الحمير", "أن يرفع صوته", "ألا يتكلم", "أن يغني في مشيه"], 0,
             "«واقصد في مشيك واغضض من صوتك، إن أنكر الأصوات لصوت الحمير».",
             "القرآن — سورة لقمان، 31:19"))

    add("virtues_052", "virtues", "medium", "quran", Q, "31:17", False,
        fr=L("Quelles trois recommandations Luqmân donne-t-il à son fils avant de parler de patience ?",
             ["Accomplir la prière, commander le convenable, interdire le blâmable", "Voyager, commercer, écrire", "Manger peu, dormir peu, parler peu", "Bâtir, planter, récolter"], 0,
             "« Ô mon fils, accomplis la prière, commande le convenable, interdis le blâmable et endure ce qui t'arrive. »",
             "Coran — Sourate Luqmân, 31:17"),
        en=L("Which three counsels does Luqman give his son before speaking of patience?",
             ["Establish prayer, enjoin the right, forbid the wrong", "Travel, trade, write", "Eat little, sleep little, speak little", "Build, plant, harvest"], 0,
             "\"O my son, establish prayer, enjoin what is right, forbid what is wrong, and be patient over what befalls you.\"",
             "Quran — Surah Luqman, 31:17"),
        ar=L("أي ثلاث وصايا أوصى بها لقمان ابنه قبل ذكر الصبر؟",
             ["إقامة الصلاة والأمر بالمعروف والنهي عن المنكر", "السفر والتجارة والكتابة", "قلة الأكل والنوم والكلام", "البناء والغرس والحصاد"], 0,
             "«يا بنيّ أقم الصلاة وأمر بالمعروف وانهَ عن المنكر واصبر على ما أصابك».",
             "القرآن — سورة لقمان، 31:17"))

    add("virtues_053", "virtues", "hard", "quran", Q, "3:134", False,
        fr=L("Quelles trois qualités le Coran attribue-t-il aux pieux, dans la sourate Âl ʿImrân ?",
             ["Dépenser dans l'aisance et la gêne, contenir leur colère, pardonner aux gens", "Jeûner, veiller, se taire", "Bâtir, planter, donner", "Voyager, apprendre, enseigner"], 0,
             "« Ceux qui dépensent dans l'aisance et dans l'adversité, qui dominent leur colère et pardonnent aux gens : Allah aime les bienfaisants. »",
             "Coran — Sourate Âl ʿImrân, 3:134"),
        en=L("Which three qualities does the Quran give the God-fearing, in Surah Al-'Imran?",
             ["Spending in ease and hardship, restraining anger, pardoning people", "Fasting, night prayer, silence", "Building, planting, giving", "Travelling, learning, teaching"], 0,
             "\"Who spend in ease and in hardship, and who restrain anger and who pardon the people — and Allah loves the doers of good.\"",
             "Quran — Surah Al-'Imran, 3:134"),
        ar=L("أي ثلاث خصال نسبها القرآن للمتقين في سورة آل عمران؟",
             ["الإنفاق في السراء والضراء وكظم الغيظ والعفو عن الناس", "الصيام والقيام والصمت", "البناء والغرس والعطاء", "السفر والتعلم والتعليم"], 0,
             "«الذين ينفقون في السراء والضراء والكاظمين الغيظ والعافين عن الناس، والله يحب المحسنين».",
             "القرآن — سورة آل عمران، 3:134"))

    add("virtues_054", "virtues", "easy", "quran", Q, "2:263", False,
        fr=L("Que le Coran juge meilleur qu'une aumône suivie d'une offense ?",
             ["Une parole convenable et un pardon", "Un don plus grand", "Un silence total", "Un serment"], 0,
             "« Une parole agréable et un pardon valent mieux qu'une aumône suivie d'un tort. »",
             "Coran — Sourate Al-Baqara, 2:263"),
        en=L("What does the Quran hold better than a charity followed by injury?",
             ["A kind word and forgiveness", "A larger gift", "Total silence", "An oath"], 0,
             "\"Kind speech and forgiveness are better than charity followed by injury.\"",
             "Quran — Surah Al-Baqarah, 2:263"),
        ar=L("ما الذي جعله القرآن خيرًا من صدقة يتبعها أذى؟",
             ["قول معروف ومغفرة", "عطاء أكبر", "صمت تام", "قسم"], 0,
             "«قول معروف ومغفرة خير من صدقة يتبعها أذى».",
             "القرآن — سورة البقرة، 2:263"))

    add("virtues_055", "virtues", "medium", "quran", Q, "2:271", False,
        fr=L("Que dit le Coran de l'aumône faite en secret ?",
             ["Elle est meilleure pour celui qui donne", "Elle ne compte pas", "Elle doit être annoncée", "Elle est interdite"], 0,
             "« Si vous donnez publiquement vos aumônes, c'est bien ; mais si vous les cachez en les donnant aux pauvres, cela est meilleur pour vous. »",
             "Coran — Sourate Al-Baqara, 2:271"),
        en=L("What does the Quran say of charity given in secret?",
             ["It is better for the giver", "It does not count", "It must be announced", "It is forbidden"], 0,
             "\"If you disclose your charitable expenditures, they are good; but if you conceal them and give them to the poor, it is better for you.\"",
             "Quran — Surah Al-Baqarah, 2:271"),
        ar=L("ماذا قال القرآن عن الصدقة في السر؟",
             ["هي خير للمتصدق", "لا تُحتسب", "يجب إعلانها", "محرّمة"], 0,
             "«إن تُبدوا الصدقات فنعمّا هي، وإن تُخفوها وتؤتوها الفقراء فهو خير لكم».",
             "القرآن — سورة البقرة، 2:271"))

    add("virtues_056", "virtues", "hard", "quran", Q, "2:267", False,
        fr=L("De quoi le Coran interdit-il de faire l'aumône ?",
             ["De ce qu'on n'accepterait soi-même qu'en fermant les yeux", "De ce qui est neuf", "De ce qu'on aime", "De ce qui vient d'un héritage"], 0,
             "« Ne vous portez pas vers ce qui est vil pour en faire dépense, alors que vous ne l'accepteriez qu'en fermant les yeux. »",
             "Coran — Sourate Al-Baqara, 2:267"),
        en=L("What does the Quran forbid be given as charity?",
             ["What one would only accept oneself with eyes closed", "What is new", "What one loves", "What comes from an inheritance"], 0,
             "\"And do not aim toward the defective of it, spending from that which you would not take yourself except with closed eyes.\"",
             "Quran — Surah Al-Baqarah, 2:267"),
        ar=L("مِمّ نهى القرآن أن يُتصدّق؟",
             ["من الخبيث الذي لا يأخذه المرء إلا بإغماض", "من الجديد", "مما يحب", "من الميراث"], 0,
             "«ولا تيمّموا الخبيث منه تنفقون ولستم بآخذيه إلا أن تُغمضوا فيه».",
             "القرآن — سورة البقرة، 2:267"))

    add("virtues_057", "virtues", "easy", "quran", Q, "3:92", False,
        fr=L("Quand atteint-on la vraie piété, selon la sourate Âl ʿImrân ?",
             ["En dépensant de ce que l'on aime", "En dépensant le surplus", "En dépensant en public", "En gardant tout"], 0,
             "« Vous n'atteindrez la vraie piété que si vous faites largesse de ce que vous chérissez. »",
             "Coran — Sourate Âl ʿImrân, 3:92"),
        en=L("When is true righteousness attained, according to Surah Al-'Imran?",
             ["By spending from what one loves", "By spending the surplus", "By spending in public", "By keeping everything"], 0,
             "\"Never will you attain righteousness until you spend from that which you love.\"",
             "Quran — Surah Al-'Imran, 3:92"),
        ar=L("متى يُنال البرّ بحسب سورة آل عمران؟",
             ["بالإنفاق مما تحب", "بإنفاق الفاضل", "بالإنفاق علنًا", "بالإمساك"], 0,
             "«لن تنالوا البرّ حتى تنفقوا مما تحبون».",
             "القرآن — سورة آل عمران، 3:92"))

    add("virtues_058", "virtues", "medium", "quran", Q, "17:29", False,
        fr=L("Quelle image le Coran emploie-t-il pour l'équilibre dans la dépense ?",
             ["Ne pas garder la main fermée au cou, ni l'étendre trop largement", "Fermer la porte", "Marcher lentement", "Compter deux fois"], 0,
             "« Ne porte pas ta main enchaînée à ton cou, et ne l'étends pas non plus trop largement, sinon tu te retrouveras blâmé et dénué. »",
             "Coran — Sourate Al-Isrâ, 17:29"),
        en=L("Which image does the Quran use for balance in spending?",
             ["Neither keeping the hand chained to the neck, nor extending it completely", "Shutting the door", "Walking slowly", "Counting twice"], 0,
             "\"And do not make your hand chained to your neck, nor extend it completely, lest you sit blamed and destitute.\"",
             "Quran — Surah Al-Isra, 17:29"),
        ar=L("أي صورة ضربها القرآن للاعتدال في الإنفاق؟",
             ["لا تجعل يدك مغلولة إلى عنقك ولا تبسطها كل البسط", "إغلاق الباب", "المشي ببطء", "العدّ مرتين"], 0,
             "«ولا تجعل يدك مغلولة إلى عنقك ولا تبسطها كل البسط فتقعد ملومًا محسورًا».",
             "القرآن — سورة الإسراء، 17:29"))

    add("virtues_059", "virtues", "hard", "quran", Q, "25:67", False,
        fr=L("Comment le Coran décrit-il la dépense des « serviteurs du Tout Miséricordieux » ?",
             ["Ni prodigues ni avares, mais au juste milieu", "Toujours généreux sans mesure", "Toujours économes", "Sans jamais donner"], 0,
             "« Ceux qui, lorsqu'ils dépensent, ne sont ni prodigues ni avares, mais se tiennent au juste milieu. »",
             "Coran — Sourate Al-Furqân, 25:67"),
        en=L("How does the Quran describe the spending of \"the servants of the Most Merciful\"?",
             ["Neither extravagant nor niggardly, but between the two", "Always giving without measure", "Always saving", "Never giving"], 0,
             "\"And those who, when they spend, are neither extravagant nor stingy, but are ever between that, moderate.\"",
             "Quran — Surah Al-Furqan, 25:67"),
        ar=L("كيف وصف القرآن إنفاق «عباد الرحمن»؟",
             ["لم يُسرفوا ولم يقتروا وكان بين ذلك قوامًا", "عطاء بلا حساب", "إمساك دائم", "لا ينفقون"], 0,
             "«والذين إذا أنفقوا لم يُسرفوا ولم يقتروا وكان بين ذلك قوامًا».",
             "القرآن — سورة الفرقان، 25:67"))

    add("virtues_060", "virtues", "easy", "quran", Q, "24:27", False,
        fr=L("Que le Coran ordonne-t-il avant d'entrer dans une maison qui n'est pas la sienne ?",
             ["Demander la permission et saluer ses habitants", "Frapper trois fois puis entrer", "Entrer directement", "Appeler de loin"], 0,
             "« N'entrez pas dans des maisons autres que les vôtres avant de demander la permission et de saluer leurs habitants. »",
             "Coran — Sourate An-Nûr, 24:27"),
        en=L("What does the Quran command before entering a house that is not one's own?",
             ["To ask permission and greet its people", "To knock three times then enter", "To enter directly", "To call from afar"], 0,
             "\"Do not enter houses other than your own until you have asked permission and greeted their inhabitants.\"",
             "Quran — Surah An-Nur, 24:27"),
        ar=L("بماذا أمر القرآن قبل دخول بيت غير بيتك؟",
             ["الاستئذان والسلام على أهله", "الطرق ثلاثًا ثم الدخول", "الدخول مباشرة", "النداء من بعيد"], 0,
             "«لا تدخلوا بيوتًا غير بيوتكم حتى تستأنسوا وتسلّموا على أهلها».",
             "القرآن — سورة النور، 24:27"))

    add("virtues_061", "virtues", "medium", "quran", Q, "24:28", False,
        fr=L("Que faire si l'on demande de repartir, selon la sourate An-Nûr ?",
             ["Repartir : c'est plus pur pour soi", "Insister", "Attendre à la porte", "Entrer quand même"], 0,
             "« Et si on vous dit : “Retournez”, eh bien, retournez : cela est plus pur pour vous. »",
             "Coran — Sourate An-Nûr, 24:28"),
        en=L("What should be done if one is asked to go back, according to Surah An-Nur?",
             ["Go back: it is purer for you", "Insist", "Wait at the door", "Enter anyway"], 0,
             "\"And if you are told: 'Go back', then go back; it is purer for you.\"",
             "Quran — Surah An-Nur, 24:28"),
        ar=L("ماذا يُفعل إذا قيل للزائر «ارجع» بحسب سورة النور؟",
             ["يرجع، فهو أزكى له", "يُلحّ", "ينتظر عند الباب", "يدخل رغم ذلك"], 0,
             "«وإن قيل لكم ارجعوا فارجعوا، هو أزكى لكم».",
             "القرآن — سورة النور، 24:28"))

    add("virtues_062", "virtues", "hard", "quran", Q, "49:6", False,
        fr=L("Que le Coran ordonne-t-il de faire quand un homme peu sûr apporte une nouvelle ?",
             ["Vérifier, de peur d'atteindre des gens par ignorance", "La répandre aussitôt", "L'écrire", "L'ignorer toujours"], 0,
             "« Si un pervers vous apporte une nouvelle, voyez bien clair, de crainte que par ignorance vous ne portiez atteinte à des gens et que vous ne regrettiez ce que vous avez fait. »",
             "Coran — Sourate Al-Hujurât, 49:6"),
        en=L("What does the Quran command when an unreliable person brings news?",
             ["To verify it, lest people be harmed out of ignorance", "To spread it at once", "To write it down", "Always to ignore it"], 0,
             "\"If there comes to you a disobedient one with information, investigate, lest you harm a people out of ignorance and become regretful.\"",
             "Quran — Surah Al-Hujurat, 49:6"),
        ar=L("بماذا أمر القرآن إذا جاء فاسق بنبأ؟",
             ["بالتبيّن كي لا يُصاب قوم بجهالة", "بنشره فورًا", "بكتابته", "بإهماله دائمًا"], 0,
             "«إن جاءكم فاسق بنبأ فتبيّنوا أن تصيبوا قومًا بجهالة فتصبحوا على ما فعلتم نادمين».",
             "القرآن — سورة الحجرات، 49:6"))

    add("virtues_063", "virtues", "medium", "quran", Q, "49:12", False,
        fr=L("Quel comportement, avec la médisance, la sourate Al-Hujurât interdit-elle ?",
             ["Espionner et soupçonner à l'excès", "Voyager seul", "Parler à voix basse", "Écrire des lettres"], 0,
             "« Ô les croyants ! Évitez de trop conjecturer ; certaines conjectures sont un péché. Et n'espionnez pas ; et ne médisez pas les uns des autres. »",
             "Coran — Sourate Al-Hujurât, 49:12"),
        en=L("Which behaviour, alongside backbiting, does Surah Al-Hujurat forbid?",
             ["Spying and excessive suspicion", "Travelling alone", "Speaking softly", "Writing letters"], 0,
             "\"O you who have believed, avoid much assumption; indeed, some assumption is sin. And do not spy or backbite one another.\"",
             "Quran — Surah Al-Hujurat, 49:12"),
        ar=L("أي سلوك حرّمته سورة الحجرات مع الغيبة؟",
             ["التجسس وكثرة الظن", "السفر منفردًا", "خفض الصوت", "كتابة الرسائل"], 0,
             "«يا أيها الذين آمنوا اجتنبوا كثيرًا من الظن، إن بعض الظن إثم، ولا تجسّسوا ولا يغتب بعضكم بعضًا».",
             "القرآن — سورة الحجرات، 49:12"))

    add("virtues_064", "virtues", "easy", "quran", Q, "49:9", False,
        fr=L("Que le Coran ordonne-t-il quand deux groupes de croyants se combattent ?",
             ["Les réconcilier avec équité", "Choisir un camp", "Les ignorer", "Les séparer par la force seule"], 0,
             "« Et si deux groupes de croyants se combattent, faites la conciliation entre eux… et soyez équitables : Allah aime ceux qui sont équitables. »",
             "Coran — Sourate Al-Hujurât, 49:9"),
        en=L("What does the Quran command when two groups of believers fight?",
             ["To reconcile them with justice", "To pick a side", "To ignore them", "To separate them by force alone"], 0,
             "\"And if two factions among the believers should fight, then make settlement between them… and act justly. Indeed, Allah loves those who act justly.\"",
             "Quran — Surah Al-Hujurat, 49:9"),
        ar=L("بماذا أمر القرآن إذا اقتتلت طائفتان من المؤمنين؟",
             ["بالإصلاح بينهما بالعدل", "بالانحياز لطرف", "بتركهما", "بالتفريق بالقوة وحدها"], 0,
             "«وإن طائفتان من المؤمنين اقتتلوا فأصلحوا بينهما… وأقسطوا، إن الله يحب المقسطين».",
             "القرآن — سورة الحجرات، 49:9"))

    add("virtues_065", "virtues", "hard", "quran", Q, "5:8", False,
        fr=L("Que le Coran interdit-il expressément, même envers un peuple qu'on déteste ?",
             ["Que la haine fasse dévier de la justice", "Le commerce", "La parole", "Le voisinage"], 0,
             "« Que la haine pour un peuple ne vous incite pas à être injustes. Soyez justes : cela est plus proche de la piété. »",
             "Coran — Sourate Al-Mâ'ida, 5:8"),
        en=L("What does the Quran expressly forbid, even toward a people one detests?",
             ["Letting hatred lead one away from justice", "Trade", "Speech", "Neighbourliness"], 0,
             "\"And do not let the hatred of a people prevent you from being just. Be just; that is nearer to righteousness.\"",
             "Quran — Surah Al-Ma'idah, 5:8"),
        ar=L("ماذا نهى عنه القرآن صراحةً حتى تجاه قوم تُبغضهم؟",
             ["أن يحملك الشنآن على ترك العدل", "التجارة", "الكلام", "الجوار"], 0,
             "«ولا يجرمنّكم شنآن قوم على ألا تعدلوا، اعدلوا هو أقرب للتقوى».",
             "القرآن — سورة المائدة، 5:8"))

    add("virtues_066", "virtues", "medium", "quran", Q, "4:135", False,
        fr=L("Contre qui le Coran demande-t-il de témoigner en équité, s'il le faut ?",
             ["Contre soi-même, ses père et mère, et ses proches", "Contre les étrangers seulement", "Contre les riches seulement", "Contre les pauvres seulement"], 0,
             "« Soyez stricts dans la justice, témoins devant Allah, fût-ce contre vous-mêmes, contre vos père et mère ou vos proches. »",
             "Coran — Sourate An-Nisâ, 4:135"),
        en=L("Against whom does the Quran require just testimony, if need be?",
             ["Against oneself, one's parents and one's relatives", "Against strangers only", "Against the rich only", "Against the poor only"], 0,
             "\"Be persistently standing firm in justice, witnesses for Allah, even if it be against yourselves or parents and relatives.\"",
             "Quran — Surah An-Nisa, 4:135"),
        ar=L("على مَن أمر القرآن بالشهادة بالقسط ولو اقتضى الأمر؟",
             ["على النفس والوالدين والأقربين", "على الغرباء فقط", "على الأغنياء فقط", "على الفقراء فقط"], 0,
             "«كونوا قوّامين بالقسط شهداء لله ولو على أنفسكم أو الوالدين والأقربين».",
             "القرآن — سورة النساء، 4:135"))

    add("virtues_067", "virtues", "easy", "quran", Q, "4:58", False,
        fr=L("Que le Coran ordonne-t-il de restituer à leurs ayants droit ?",
             ["Les dépôts confiés (amânât)", "Les lettres", "Les récoltes", "Les récits"], 0,
             "« Allah vous commande de restituer les dépôts à leurs ayants droit, et quand vous jugez entre les gens, de juger avec équité. »",
             "Coran — Sourate An-Nisâ, 4:58"),
        en=L("What does the Quran command be returned to those entitled to them?",
             ["Trusts (amanat)", "Letters", "Harvests", "Stories"], 0,
             "\"Indeed, Allah commands you to render trusts to whom they are due and, when you judge between people, to judge with justice.\"",
             "Quran — Surah An-Nisa, 4:58"),
        ar=L("بماذا أمر القرآن أن يُردّ إلى أهله؟",
             ["الأمانات", "الرسائل", "الزروع", "الأخبار"], 0,
             "«إن الله يأمركم أن تؤدّوا الأمانات إلى أهلها وإذا حكمتم بين الناس أن تحكموا بالعدل».",
             "القرآن — سورة النساء، 4:58"))

    add("virtues_068", "virtues", "hard", "quran", Q, "4:36", False,
        fr=L("Combien de catégories de personnes le verset 4:36 énumère-t-il pour la bienfaisance, après les parents ?",
             ["Les proches, les orphelins, les pauvres, le voisin proche et lointain, le compagnon, le voyageur et le serviteur", "Les rois et les chefs", "Les marchands", "Les savants seuls"], 0,
             "« Adorez Allah et ne Lui donnez aucun associé. Agissez avec bonté envers les père et mère, les proches, les orphelins, les pauvres, le voisin proche et le voisin lointain, le compagnon de route, le voyageur et ce que vos mains droites possèdent. »",
             "Coran — Sourate An-Nisâ, 4:36"),
        en=L("Which people does verse 4:36 list for good treatment, after the parents?",
             ["Relatives, orphans, the poor, the near and distant neighbour, the companion, the traveller and the servant", "Kings and chiefs", "Merchants", "Scholars only"], 0,
             "\"Worship Allah and associate nothing with Him, and to parents do good, and to relatives, orphans, the needy, the near neighbour, the neighbour farther away, the companion at your side, the traveller, and those whom your right hands possess.\"",
             "Quran — Surah An-Nisa, 4:36"),
        ar=L("مَن ذكرتهم الآية 4:36 للإحسان بعد الوالدين؟",
             ["ذو القربى واليتامى والمساكين والجار القريب والجنب والصاحب وابن السبيل والمملوك", "الملوك والرؤساء", "التجار", "العلماء وحدهم"], 0,
             "«واعبدوا الله ولا تشركوا به شيئًا وبالوالدين إحسانًا وبذي القربى واليتامى والمساكين والجار ذي القربى والجار الجنب والصاحب بالجنب وابن السبيل وما ملكت أيمانكم».",
             "القرآن — سورة النساء، 4:36"))

    add("virtues_069", "virtues", "medium", "quran", Q, "2:280", False,
        fr=L("Que le Coran ordonne-t-il envers un débiteur en difficulté ?",
             ["Lui accorder un délai jusqu'à l'aisance", "Le poursuivre", "Doubler la dette", "L'expulser"], 0,
             "« Et s'il est dans la gêne, qu'on lui accorde un délai jusqu'à ce qu'il soit dans l'aisance ; mais il est mieux pour vous de faire remise de la dette. »",
             "Coran — Sourate Al-Baqara, 2:280"),
        en=L("What does the Quran command toward a debtor in hardship?",
             ["To grant him time until ease", "To pursue him", "To double the debt", "To expel him"], 0,
             "\"And if someone is in hardship, then let there be postponement until a time of ease. But if you give from your right as charity, it is better for you.\"",
             "Quran — Surah Al-Baqarah, 2:280"),
        ar=L("بماذا أمر القرآن تجاه المدين المعسر؟",
             ["إنظاره إلى ميسرة", "ملاحقته", "مضاعفة الدين", "إخراجه"], 0,
             "«وإن كان ذو عسرة فنظرة إلى ميسرة، وأن تصدّقوا خير لكم».",
             "القرآن — سورة البقرة، 2:280"))

    add("virtues_070", "virtues", "hard", "quran", Q, "2:282", False,
        fr=L("Que le plus long verset du Coran ordonne-t-il pour une dette à terme ?",
             ["De la mettre par écrit", "De la garder secrète", "De l'oublier", "De la transmettre oralement"], 0,
             "« Ô les croyants ! Quand vous contractez une dette à échéance déterminée, mettez-la par écrit. »",
             "Coran — Sourate Al-Baqara, 2:282"),
        en=L("What does the longest verse of the Quran command for a debt with a set term?",
             ["That it be written down", "That it be kept secret", "That it be forgotten", "That it be passed on orally"], 0,
             "\"O you who have believed, when you contract a debt for a specified term, write it down.\"",
             "Quran — Surah Al-Baqarah, 2:282"),
        ar=L("بماذا أمرت أطول آية في القرآن في شأن الدَّين المؤجل؟",
             ["بكتابته", "بكتمانه", "بنسيانه", "بنقله شفاهًا"], 0,
             "«يا أيها الذين آمنوا إذا تداينتم بدَين إلى أجل مسمّى فاكتبوه».",
             "القرآن — سورة البقرة، 2:282"))

    add("virtues_071", "virtues", "easy", "quran", Q, "2:188", False,
        fr=L("Que le Coran interdit-il au sujet des biens d'autrui ?",
             ["Les dévorer illégalement, ou par des pots-de-vin aux juges", "Les compter", "Les vendre", "Les garder"], 0,
             "« Ne dévorez pas illégalement les biens les uns des autres, et ne vous en servez pas pour corrompre des juges. »",
             "Coran — Sourate Al-Baqara, 2:188"),
        en=L("What does the Quran forbid concerning the property of others?",
             ["Consuming it unjustly, or using it to bribe judges", "Counting it", "Selling it", "Keeping it"], 0,
             "\"And do not consume one another's wealth unjustly, or send it to the rulers in order to consume a portion of the wealth of the people in sin.\"",
             "Quran — Surah Al-Baqarah, 2:188"),
        ar=L("ماذا حرّم القرآن في شأن أموال الناس؟",
             ["أكلها بالباطل والإدلاء بها إلى الحكام", "عدّها", "بيعها", "حفظها"], 0,
             "«ولا تأكلوا أموالكم بينكم بالباطل وتُدلوا بها إلى الحكام لتأكلوا فريقًا من أموال الناس بالإثم».",
             "القرآن — سورة البقرة، 2:188"))

    add("virtues_072", "virtues", "medium", "quran", Q, "4:2", False,
        fr=L("Que le Coran ordonne-t-il au sujet des biens des orphelins ?",
             ["Les leur rendre, sans échanger le bon contre le mauvais", "Les partager", "Les vendre", "Les garder à vie"], 0,
             "« Donnez aux orphelins leurs biens ; n'y substituez pas le mauvais au bon, et ne mangez pas leurs biens avec les vôtres : ce serait un grand péché. »",
             "Coran — Sourate An-Nisâ, 4:2"),
        en=L("What does the Quran command concerning the property of orphans?",
             ["To give it to them, not exchanging the good for the bad", "To share it out", "To sell it", "To keep it for life"], 0,
             "\"And give to the orphans their properties and do not substitute the defective for the good, and do not consume their properties into your own.\"",
             "Quran — Surah An-Nisa, 4:2"),
        ar=L("بماذا أمر القرآن في أموال اليتامى؟",
             ["بأدائها إليهم ولا يُتبدَّل الخبيث بالطيب", "بقسمتها", "ببيعها", "بحبسها دائمًا"], 0,
             "«وآتوا اليتامى أموالهم ولا تتبدّلوا الخبيث بالطيب ولا تأكلوا أموالهم إلى أموالكم».",
             "القرآن — سورة النساء، 4:2"))

    add("virtues_073", "virtues", "hard", "quran", Q, "17:35", False,
        fr=L("Comment le Coran ordonne-t-il de mesurer et de peser ?",
             ["Donner la pleine mesure et peser avec une balance juste", "Arrondir en sa faveur", "Peser à l'œil", "Mesurer deux fois"], 0,
             "« Et donnez la pleine mesure quand vous mesurez, et pesez avec une balance exacte : c'est mieux, et le résultat en est meilleur. »",
             "Coran — Sourate Al-Isrâ, 17:35"),
        en=L("How does the Quran command measuring and weighing?",
             ["Give full measure and weigh with an even balance", "Round in one's own favour", "Weigh by eye", "Measure twice"], 0,
             "\"And give full measure when you measure, and weigh with an even balance. That is the best and fairest in result.\"",
             "Quran — Surah Al-Isra, 17:35"),
        ar=L("كيف أمر القرآن بالكيل والوزن؟",
             ["إيفاء الكيل والوزن بالقسطاس المستقيم", "التقريب لصالحه", "الوزن بالنظر", "الكيل مرتين"], 0,
             "«وأوفوا الكيل إذا كلتم وزنوا بالقسطاس المستقيم، ذلك خير وأحسن تأويلًا».",
             "القرآن — سورة الإسراء، 17:35"))

    add("virtues_074", "virtues", "easy", "quran", Q, "17:36", False,
        fr=L("Que le Coran interdit-il de suivre, faute de savoir ?",
             ["Ce dont on n'a pas connaissance : l'ouïe, la vue et le cœur en répondront", "Le chemin le plus court", "Les caravanes", "Le silence"], 0,
             "« Ne poursuis pas ce dont tu n'as aucune connaissance : l'ouïe, la vue et le cœur, sur tout cela on sera interrogé. »",
             "Coran — Sourate Al-Isrâ, 17:36"),
        en=L("What does the Quran forbid one to follow, for lack of knowledge?",
             ["That of which one has no knowledge: hearing, sight and heart will be questioned", "The shortest road", "The caravans", "Silence"], 0,
             "\"And do not pursue that of which you have no knowledge. Indeed, the hearing, the sight and the heart — about all those one will be questioned.\"",
             "Quran — Surah Al-Isra, 17:36"),
        ar=L("مِمّ نهى القرآن عن اتّباعه بلا علم؟",
             ["ما ليس لك به علم؛ فالسمع والبصر والفؤاد مسؤولون", "أقصر الطرق", "القوافل", "الصمت"], 0,
             "«ولا تقفُ ما ليس لك به علم، إن السمع والبصر والفؤاد كل أولئك كان عنه مسؤولًا».",
             "القرآن — سورة الإسراء، 17:36"))

    add("virtues_075", "virtues", "medium", "quran", Q, "17:37", False,
        fr=L("Quelle image le Coran donne-t-il de l'orgueil dans la démarche ?",
             ["On ne peut fendre la terre ni atteindre la hauteur des montagnes", "On avance plus vite", "On se fatigue moins", "On se fait respecter"], 0,
             "« Et ne foule pas la terre avec orgueil : tu ne pourras jamais fendre la terre, ni égaler les montagnes en hauteur. »",
             "Coran — Sourate Al-Isrâ, 17:37"),
        en=L("Which image does the Quran give of pride in one's gait?",
             ["You cannot split the earth, nor reach the mountains in height", "You go faster", "You tire less", "You earn respect"], 0,
             "\"And do not walk upon the earth exultantly. Indeed, you will never tear the earth apart, and you will never reach the mountains in height.\"",
             "Quran — Surah Al-Isra, 17:37"),
        ar=L("أي صورة ضربها القرآن للكبر في المشي؟",
             ["لن تخرق الأرض ولن تبلغ الجبال طولًا", "تسرع أكثر", "تتعب أقل", "تُهاب"], 0,
             "«ولا تمشِ في الأرض مرحًا، إنك لن تخرق الأرض ولن تبلغ الجبال طولًا».",
             "القرآن — سورة الإسراء، 17:37"))

    # -- Speech, patience, gratitude, company ----------------------------
    add("virtues_076", "virtues", "hard", "quran", Q, "33:70-71", False,
        fr=L("Quelle qualité de parole le Coran ordonne-t-il, promettant que les œuvres seront réformées ?",
             ["Une parole juste et droite (qawl sadîd)", "Une parole brève", "Une parole savante", "Une parole écrite"], 0,
             "« Ô les croyants ! Craignez Allah et dites une parole juste : Il réformera pour vous vos œuvres et vous pardonnera vos péchés. »",
             "Coran — Sourate Al-Ahzâb, 33:70-71"),
        en=L("Which quality of speech does the Quran command, promising that deeds will be set right?",
             ["Upright, truthful speech (qawl sadid)", "Brief speech", "Learned speech", "Written speech"], 0,
             "\"O you who have believed, fear Allah and speak words of appropriate justice. He will amend for you your deeds and forgive you your sins.\"",
             "Quran — Surah Al-Ahzab, 33:70-71"),
        ar=L("أي صفة للقول أمر بها القرآن ووعد بإصلاح الأعمال؟",
             ["قولًا سديدًا", "قولًا موجزًا", "قولًا عالمًا", "قولًا مكتوبًا"], 0,
             "«يا أيها الذين آمنوا اتقوا الله وقولوا قولًا سديدًا، يُصلح لكم أعمالكم ويغفر لكم ذنوبكم».",
             "القرآن — سورة الأحزاب، 33:70-71"))

    add("virtues_077", "virtues", "easy", "quran", Q, "20:44", False,
        fr=L("Quelle sorte de parole fut ordonnée même face à un tyran, dans le Coran ?",
             ["Une parole douce", "Une parole menaçante", "Une parole ironique", "Le silence"], 0,
             "« Et parlez-lui gentiment : peut-être se rappellera-t-il ou craindra-t-il. »",
             "Coran — Sourate Tâ-Hâ, 20:44"),
        en=L("What kind of speech was commanded even before a tyrant, in the Quran?",
             ["Gentle speech", "Threatening speech", "Ironic speech", "Silence"], 0,
             "\"And speak to him with gentle speech, that perhaps he may be reminded or fear Allah.\"",
             "Quran — Surah Ta-Ha, 20:44"),
        ar=L("أي قول أُمر به حتى مع الطاغية في القرآن؟",
             ["قول ليّن", "قول مهدِّد", "قول ساخر", "الصمت"], 0,
             "«فقولا له قولًا ليّنًا لعله يتذكر أو يخشى».",
             "القرآن — سورة طه، 20:44"))

    add("virtues_078", "virtues", "hard", "quran", Q, "41:33", False,
        fr=L("De qui le Coran dit-il qu'il tient le plus beau langage ?",
             ["Celui qui appelle à Allah, fait le bien et dit : je suis du nombre des musulmans", "Le poète", "L'orateur", "Le juge"], 0,
             "« Et qui profère plus belle parole que celui qui appelle à Allah, fait bonne œuvre et dit : “Je suis du nombre des soumis” ? »",
             "Coran — Sourate Fussilat, 41:33"),
        en=L("Of whom does the Quran say his speech is the best?",
             ["One who calls to Allah, does righteousness and says: I am of the Muslims", "The poet", "The orator", "The judge"], 0,
             "\"And who is better in speech than one who invites to Allah and does righteousness and says: indeed, I am of the Muslims?\"",
             "Quran — Surah Fussilat, 41:33"),
        ar=L("عمّن قال القرآن إنه أحسن قولًا؟",
             ["من دعا إلى الله وعمل صالحًا وقال إنني من المسلمين", "الشاعر", "الخطيب", "القاضي"], 0,
             "«ومن أحسن قولًا ممن دعا إلى الله وعمل صالحًا وقال إنني من المسلمين».",
             "القرآن — سورة فصلت، 41:33"))

    add("virtues_079", "virtues", "easy", "quran", Q, "23:3", False,
        fr=L("De quoi les croyants qui réussissent se détournent-ils, selon Al-Mu'minûn ?",
             ["Des futilités (al-laghw)", "Du travail", "Des voyages", "Des repas"], 0,
             "« … et qui se détournent des futilités. »",
             "Coran — Sourate Al-Mu'minûn, 23:3"),
        en=L("From what do the successful believers turn away, according to Al-Mu'minun?",
             ["From idle talk (al-laghw)", "From work", "From travel", "From meals"], 0,
             "\"And they who turn away from ill speech.\"",
             "Quran — Surah Al-Mu'minun, 23:3"),
        ar=L("عمّ يُعرض المؤمنون المفلحون بحسب سورة المؤمنون؟",
             ["عن اللغو", "عن العمل", "عن السفر", "عن الطعام"], 0,
             "«والذين هم عن اللغو معرضون».",
             "القرآن — سورة المؤمنون، 23:3"))

    add("virtues_080", "virtues", "medium", "quran", Q, "23:8", False,
        fr=L("Quelles deux charges les croyants qui réussissent observent-ils, selon Al-Mu'minûn ?",
             ["Les dépôts qui leur sont confiés et leurs engagements", "Le jeûne et la veille", "Le voyage et le commerce", "L'écriture et la lecture"], 0,
             "« Et qui veillent sur les dépôts confiés à eux et honorent leurs engagements. »",
             "Coran — Sourate Al-Mu'minûn, 23:8"),
        en=L("Which two charges do the successful believers keep, according to Al-Mu'minun?",
             ["Their trusts and their covenants", "Fasting and night prayer", "Travel and trade", "Writing and reading"], 0,
             "\"And they who are to their trusts and their promises attentive.\"",
             "Quran — Surah Al-Mu'minun, 23:8"),
        ar=L("أي أمانتين يرعاهما المؤمنون المفلحون بحسب سورة المؤمنون؟",
             ["أماناتهم وعهدهم", "الصيام والقيام", "السفر والتجارة", "الكتابة والقراءة"], 0,
             "«والذين هم لأماناتهم وعهدهم راعون».",
             "القرآن — سورة المؤمنون، 23:8"))

    add("virtues_081", "virtues", "hard", "quran", Q, "42:40", False,
        fr=L("Que le Coran dit-il de celui qui pardonne et réconcilie, alors qu'il pourrait rendre le mal ?",
             ["Sa récompense incombe à Allah", "Il perd son droit", "Il est blâmé", "Il doit se taire"], 0,
             "« La sanction d'une mauvaise action est une mauvaise action identique. Mais quiconque pardonne et réforme, sa récompense incombe à Allah. »",
             "Coran — Sourate Ash-Shûrâ, 42:40"),
        en=L("What does the Quran say of one who pardons and reconciles, though he could repay evil?",
             ["His reward is due from Allah", "He loses his right", "He is blamed", "He must stay silent"], 0,
             "\"And the retribution for an evil act is an evil one like it, but whoever pardons and makes reconciliation — his reward is due from Allah.\"",
             "Quran — Surah Ash-Shura, 42:40"),
        ar=L("ماذا قال القرآن فيمن عفا وأصلح وهو قادر على المجازاة؟",
             ["فأجره على الله", "يسقط حقه", "يُلام", "عليه أن يصمت"], 0,
             "«وجزاء سيئة سيئة مثلها، فمن عفا وأصلح فأجره على الله».",
             "القرآن — سورة الشورى، 42:40"))

    add("virtues_082", "virtues", "medium", "quran", Q, "24:22", False,
        fr=L("Quel argument le Coran donne-t-il pour pardonner à celui qui nous a fait du tort ?",
             ["« N'aimez-vous pas qu'Allah vous pardonne ? »", "« Vous serez récompensés en argent »", "« Cela vous rendra puissants »", "« Cela vous évitera un procès »"], 0,
             "« Qu'ils pardonnent et absolvent. N'aimez-vous pas qu'Allah vous pardonne ? Et Allah est Pardonneur, Miséricordieux. »",
             "Coran — Sourate An-Nûr, 24:22"),
        en=L("What argument does the Quran give for pardoning one who has wronged you?",
             ["\"Do you not love that Allah should forgive you?\"", "\"You will be paid in money\"", "\"It will make you powerful\"", "\"It will spare you a lawsuit\""], 0,
             "\"Let them pardon and overlook. Would you not like that Allah should forgive you? And Allah is Forgiving and Merciful.\"",
             "Quran — Surah An-Nur, 24:22"),
        ar=L("بأي حجة رغّب القرآن في العفو عمّن أساء؟",
             ["«ألا تحبون أن يغفر الله لكم؟»", "«ستُعوَّضون مالًا»", "«ستقوَون»", "«تتجنبون القضاء»"], 0,
             "«وليعفوا وليصفحوا، ألا تحبون أن يغفر الله لكم، والله غفور رحيم».",
             "القرآن — سورة النور، 24:22"))

    add("virtues_083", "virtues", "easy", "quran", Q, "7:199", False,
        fr=L("Quelles trois consignes le verset 7:199 réunit-il ?",
             ["Accepter l'excuse, ordonner le convenable, s'écarter des ignorants", "Combattre, fuir, se taire", "Manger, boire, dormir", "Compter, écrire, lire"], 0,
             "« Accepte ce qu'on t'offre de raisonnable, commande ce qui est convenable, et éloigne-toi des ignorants. »",
             "Coran — Sourate Al-Aʿrâf, 7:199"),
        en=L("Which three instructions does verse 7:199 gather?",
             ["Take what is easily given, enjoin what is right, turn away from the ignorant", "Fight, flee, be silent", "Eat, drink, sleep", "Count, write, read"], 0,
             "\"Take what is given freely, enjoin what is good, and turn away from the ignorant.\"",
             "Quran — Surah Al-A'raf, 7:199"),
        ar=L("أي ثلاث وصايا جمعتها الآية 7:199؟",
             ["خذ العفو وأمر بالعرف وأعرض عن الجاهلين", "القتال والفرار والصمت", "الأكل والشرب والنوم", "العدّ والكتابة والقراءة"], 0,
             "«خذ العفو وأمر بالعرف وأعرض عن الجاهلين».",
             "القرآن — سورة الأعراف، 7:199"))

    add("virtues_084", "virtues", "hard", "quran", Q, "3:186", False,
        fr=L("Quelle attitude le Coran recommande-t-il face aux paroles blessantes et à l'épreuve ?",
             ["La patience et la piété : cela fait partie des bonnes résolutions", "La réplique immédiate", "Le retrait définitif", "Le silence méprisant"], 0,
             "« Vous entendrez de la part de ceux qui ont reçu le Livre avant vous beaucoup de propos blessants. Mais si vous êtes endurants et pieux, cela fait partie des bonnes résolutions. »",
             "Coran — Sourate Âl ʿImrân, 3:186"),
        en=L("What attitude does the Quran recommend in the face of hurtful words and trial?",
             ["Patience and God-consciousness: that is of the matters requiring determination", "Immediate reply", "Permanent withdrawal", "Contemptuous silence"], 0,
             "\"And you will surely hear much abuse from those who were given the Scripture before you. But if you are patient and fear Allah, that is of the matters requiring determination.\"",
             "Quran — Surah Al-'Imran, 3:186"),
        ar=L("بأي خلق أوصى القرآن عند سماع الأذى والابتلاء؟",
             ["الصبر والتقوى، فذلك من عزم الأمور", "الرد فورًا", "الاعتزال الدائم", "الصمت المحتقِر"], 0,
             "«ولتسمعنّ من الذين أوتوا الكتاب من قبلكم أذى كثيرًا، وإن تصبروا وتتقوا فإن ذلك من عزم الأمور».",
             "القرآن — سورة آل عمران، 3:186"))

    add("virtues_085", "virtues", "hard", "quran", Q, "42:43", False,
        fr=L("Comment le Coran qualifie-t-il l'endurance et le pardon ?",
             ["Cela fait partie des bonnes résolutions", "Cela est une faiblesse", "Cela est facultatif", "Cela est réservé aux savants"], 0,
             "« Et celui qui endure et pardonne, cela fait partie des bonnes résolutions. »",
             "Coran — Sourate Ash-Shûrâ, 42:43"),
        en=L("How does the Quran describe patience and forgiveness?",
             ["They are of the matters requiring determination", "They are weakness", "They are optional", "They are for scholars only"], 0,
             "\"And whoever is patient and forgives — indeed, that is of the matters requiring determination.\"",
             "Quran — Surah Ash-Shura, 42:43"),
        ar=L("كيف وصف القرآن الصبر والمغفرة؟",
             ["من عزم الأمور", "ضعفًا", "أمرًا اختياريًّا", "خاصًّا بالعلماء"], 0,
             "«ولمن صبر وغفر إن ذلك لمن عزم الأمور».",
             "القرآن — سورة الشورى، 42:43"))

    add("virtues_086", "virtues", "hard", "quran", Q, "2:45", False,
        fr=L("À qui le Coran dit-il que le recours à la prière est lourd, sauf pour eux ?",
             ["Aux humbles devant Allah (al-khâshiʿîn)", "Aux riches", "Aux savants", "Aux voyageurs"], 0,
             "« Cherchez secours dans l'endurance et la prière : certes, la prière est une lourde obligation, sauf pour les humbles. »",
             "Coran — Sourate Al-Baqara, 2:45"),
        en=L("For whom does the Quran say the prayer is not burdensome?",
             ["For the humbly submissive (al-khashi'in)", "For the rich", "For scholars", "For travellers"], 0,
             "\"And seek help through patience and prayer; indeed, it is difficult except for the humbly submissive.\"",
             "Quran — Surah Al-Baqarah, 2:45"),
        ar=L("على مَن ليست الصلاة كبيرة بحسب القرآن؟",
             ["على الخاشعين", "على الأغنياء", "على العلماء", "على المسافرين"], 0,
             "«واستعينوا بالصبر والصلاة، وإنها لكبيرة إلا على الخاشعين».",
             "القرآن — سورة البقرة، 2:45"))

    add("virtues_087", "virtues", "easy", "quran", Q, "2:216", False,
        fr=L("Que rappelle le Coran sur ce que l'on déteste ou ce que l'on aime ?",
             ["Il se peut qu'on déteste une chose qui est un bien, et qu'on aime une chose qui est un mal", "Ce qu'on aime est toujours bon", "Ce qu'on déteste est toujours mauvais", "On sait toujours ce qui est bon"], 0,
             "« Il se peut que vous ayez de l'aversion pour une chose alors qu'elle vous est un bien, et il se peut que vous aimiez une chose alors qu'elle vous est mauvaise. Allah sait, et vous ne savez pas. »",
             "Coran — Sourate Al-Baqara, 2:216"),
        en=L("What does the Quran remind about what one dislikes or loves?",
             ["You may dislike a thing that is good for you, and love a thing that is bad for you", "What you love is always good", "What you dislike is always bad", "You always know what is good"], 0,
             "\"Perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. Allah knows, while you know not.\"",
             "Quran — Surah Al-Baqarah, 2:216"),
        ar=L("بماذا ذكّر القرآن في شأن ما تكره وما تحب؟",
             ["عسى أن تكرهوا شيئًا وهو خير لكم، وعسى أن تحبوا شيئًا وهو شر لكم", "ما تحبه خير دائمًا", "ما تكرهه شر دائمًا", "أنت تعلم الخير دائمًا"], 0,
             "«وعسى أن تكرهوا شيئًا وهو خير لكم، وعسى أن تحبوا شيئًا وهو شر لكم، والله يعلم وأنتم لا تعلمون».",
             "القرآن — سورة البقرة، 2:216"))

    add("virtues_088", "virtues", "hard", "quran", Q, "65:2-3", False,
        fr=L("Que promet le Coran à celui qui craint Allah, en matière d'issue et de subsistance ?",
             ["Une issue et une subsistance d'où il ne s'attend pas", "La richesse immédiate", "Un long voyage", "Une charge publique"], 0,
             "« Et quiconque craint Allah, Il lui donnera une issue favorable, et lui accordera Ses dons par des voies insoupçonnées. »",
             "Coran — Sourate At-Talâq, 65:2-3"),
        en=L("What does the Quran promise one who fears Allah, as to relief and provision?",
             ["A way out, and provision from where he does not expect", "Immediate wealth", "A long journey", "A public office"], 0,
             "\"And whoever fears Allah, He will make for him a way out, and will provide for him from where he does not expect.\"",
             "Quran — Surah At-Talaq, 65:2-3"),
        ar=L("بماذا وعد القرآن من اتقى الله في المخرج والرزق؟",
             ["مخرجًا ورزقًا من حيث لا يحتسب", "غنى فوريًّا", "سفرًا طويلًا", "منصبًا"], 0,
             "«ومن يتقِ الله يجعل له مخرجًا، ويرزقه من حيث لا يحتسب».",
             "القرآن — سورة الطلاق، 65:2-3"))

    add("virtues_089", "virtues", "medium", "quran", Q, "31:14", False,
        fr=L("Quelle reconnaissance le Coran ordonne-t-il dans le même souffle que celle envers Allah ?",
             ["La reconnaissance envers ses parents", "Envers son maître", "Envers son voisin", "Envers son roi"], 0,
             "« Sois reconnaissant envers Moi et envers tes parents : c'est vers Moi que sera le retour. »",
             "Coran — Sourate Luqmân, 31:14"),
        en=L("Which gratitude does the Quran command in the same breath as gratitude to Allah?",
             ["Gratitude to one's parents", "To one's master", "To one's neighbour", "To one's king"], 0,
             "\"Be grateful to Me and to your parents; to Me is the final destination.\"",
             "Quran — Surah Luqman, 31:14"),
        ar=L("أي شكر قرنه القرآن بشكر الله؟",
             ["شكر الوالدين", "شكر السيد", "شكر الجار", "شكر الملك"], 0,
             "«أن اشكر لي ولوالديك، إليّ المصير».",
             "القرآن — سورة لقمان، 31:14"))

    add("virtues_090", "virtues", "hard", "quran", Q, "29:8", False,
        fr=L("Quelle limite le Coran pose-t-il à l'obéissance aux parents ?",
             ["Ne pas leur obéir s'ils ordonnent d'associer à Allah", "Ne jamais leur obéir", "Leur obéir en tout", "Ne leur obéir qu'en voyage"], 0,
             "« Et si tous deux te forcent à M'associer ce dont tu n'as aucune connaissance, alors ne leur obéis pas ; mais comporte-toi bien envers eux ici-bas. »",
             "Coran — Sourate Al-ʿAnkabût, 29:8"),
        en=L("What limit does the Quran set on obedience to parents?",
             ["Not to obey them if they command associating others with Allah", "Never to obey them", "To obey them in everything", "To obey them only when travelling"], 0,
             "\"But if they endeavour to make you associate with Me that of which you have no knowledge, do not obey them; but accompany them in this world with appropriate kindness.\"",
             "Quran — Surah Al-'Ankabut, 29:8"),
        ar=L("أي حدّ وضعه القرآن لطاعة الوالدين؟",
             ["ألا يُطاعا في الشرك بالله", "ألا يُطاعا مطلقًا", "أن يُطاعا في كل شيء", "أن يُطاعا في السفر فقط"], 0,
             "«وإن جاهداك لتشرك بي ما ليس لك به علم فلا تطعهما، وصاحبهما في الدنيا معروفًا».",
             "القرآن — سورة العنكبوت، 29:8"))

    add("virtues_091", "virtues", "easy", "quran", Q, "46:15", False,
        fr=L("Quelle invocation le Coran enseigne-t-il pour les parents et la descendance ?",
             ["Rendre grâce pour le bienfait, agir en bien et réformer sa descendance", "Demander la richesse", "Demander un long voyage", "Demander une charge"], 0,
             "« Seigneur, inspire-moi de rendre grâce pour le bienfait dont Tu m'as comblé ainsi qu'à mes parents, et d'accomplir de bonnes œuvres ; et réforme ma descendance. »",
             "Coran — Sourate Al-Ahqâf, 46:15"),
        en=L("Which supplication does the Quran teach for one's parents and offspring?",
             ["To be grateful for the favour, to do good, and that one's offspring be set right", "To ask for wealth", "To ask for a long journey", "To ask for office"], 0,
             "\"My Lord, enable me to be grateful for Your favour which You have bestowed upon me and upon my parents, and to work righteousness; and make righteous for me my offspring.\"",
             "Quran — Surah Al-Ahqaf, 46:15"),
        ar=L("أي دعاء علّمه القرآن في شأن الوالدين والذرية؟",
             ["شكر النعمة والعمل الصالح وإصلاح الذرية", "طلب المال", "طلب سفر طويل", "طلب منصب"], 0,
             "«رب أوزعني أن أشكر نعمتك التي أنعمت عليّ وعلى والديّ وأن أعمل صالحًا ترضاه، وأصلح لي في ذريتي».",
             "القرآن — سورة الأحقاف، 46:15"))

    add("virtues_092", "virtues", "medium", "quran", Q, "25:74", False,
        fr=L("Que demandent « les serviteurs du Tout Miséricordieux » au sujet de leur famille ?",
             ["Qu'elle soit une joie pour les yeux, et qu'ils soient un modèle pour les pieux", "Qu'elle soit riche", "Qu'elle soit nombreuse", "Qu'elle voyage"], 0,
             "« Seigneur, fais que nos épouses et notre descendance soient une joie pour nos yeux, et fais de nous un modèle pour les pieux. »",
             "Coran — Sourate Al-Furqân, 25:74"),
        en=L("What do \"the servants of the Most Merciful\" ask concerning their families?",
             ["That they be a comfort to the eyes, and that they be an example for the righteous", "That they be rich", "That they be many", "That they travel"], 0,
             "\"Our Lord, grant us from among our wives and offspring comfort to our eyes, and make us an example for the righteous.\"",
             "Quran — Surah Al-Furqan, 25:74"),
        ar=L("بماذا يدعو «عباد الرحمن» في شأن أهليهم؟",
             ["أن يكونوا قرة أعين وأن يكونوا للمتقين إمامًا", "أن يكونوا أغنياء", "أن يكونوا كثيرين", "أن يسافروا"], 0,
             "«ربنا هب لنا من أزواجنا وذرياتنا قرة أعين واجعلنا للمتقين إمامًا».",
             "القرآن — سورة الفرقان، 25:74"))

    add("virtues_093", "virtues", "hard", "quran", Q, "25:72", False,
        fr=L("Comment « les serviteurs du Tout Miséricordieux » se comportent-ils devant la futilité ?",
             ["Ils passent noblement leur chemin", "Ils s'arrêtent pour écouter", "Ils répondent vivement", "Ils l'écrivent"], 0,
             "« Ceux qui ne donnent pas de faux témoignages, et qui, lorsqu'ils passent auprès d'une frivolité, s'en écartent noblement. »",
             "Coran — Sourate Al-Furqân, 25:72"),
        en=L("How do \"the servants of the Most Merciful\" behave in the face of frivolity?",
             ["They pass by with dignity", "They stop to listen", "They answer sharply", "They write it down"], 0,
             "\"And those who do not testify to falsehood, and when they pass near ill speech, they pass by with dignity.\"",
             "Quran — Surah Al-Furqan, 25:72"),
        ar=L("كيف يمرّ «عباد الرحمن» باللغو؟",
             ["يمرّون كرامًا", "يقفون للاستماع", "يردّون بشدة", "يكتبونه"], 0,
             "«والذين لا يشهدون الزور وإذا مرّوا باللغو مرّوا كرامًا».",
             "القرآن — سورة الفرقان، 25:72"))

    add("virtues_094", "virtues", "easy", "quran", Q, "58:11", False,
        fr=L("Que le Coran ordonne-t-il de faire dans une assemblée quand on demande de la place ?",
             ["Faire de la place : Allah vous ménagera une place", "Rester serré", "Sortir", "Se taire"], 0,
             "« Ô les croyants ! Quand on vous dit : “Faites place dans les assemblées”, faites place : Allah vous ménagera une place. »",
             "Coran — Sourate Al-Mujâdila, 58:11"),
        en=L("What does the Quran command in a gathering when room is asked for?",
             ["Make room: Allah will make room for you", "Stay crowded", "Leave", "Keep silent"], 0,
             "\"O you who have believed, when you are told: 'Make room in the assemblies', then make room; Allah will make room for you.\"",
             "Quran — Surah Al-Mujadilah, 58:11"),
        ar=L("بماذا أمر القرآن في المجلس إذا قيل تفسّحوا؟",
             ["بالتفسّح، يفسح الله لكم", "بالتضايق", "بالخروج", "بالسكوت"], 0,
             "«يا أيها الذين آمنوا إذا قيل لكم تفسّحوا في المجالس فافسحوا يفسح الله لكم».",
             "القرآن — سورة المجادلة، 58:11"))

    add("virtues_095", "virtues", "hard", "quran", Q, "9:119", False,
        fr=L("Avec qui le Coran ordonne-t-il d'être, dans la sourate At-Tawba ?",
             ["Avec les véridiques", "Avec les puissants", "Avec les riches", "Avec les voyageurs"], 0,
             "« Ô les croyants ! Craignez Allah et soyez avec les véridiques. »",
             "Coran — Sourate At-Tawba, 9:119"),
        en=L("With whom does the Quran command one to be, in Surah At-Tawbah?",
             ["With the truthful", "With the powerful", "With the rich", "With travellers"], 0,
             "\"O you who have believed, fear Allah and be with those who are true.\"",
             "Quran — Surah At-Tawbah, 9:119"),
        ar=L("مع مَن أمر القرآن أن يكون المؤمن في سورة التوبة؟",
             ["مع الصادقين", "مع الأقوياء", "مع الأغنياء", "مع المسافرين"], 0,
             "«يا أيها الذين آمنوا اتقوا الله وكونوا مع الصادقين».",
             "القرآن — سورة التوبة، 9:119"))

    add("virtues_096", "virtues", "easy", "quran", Q, "18:28", False,
        fr=L("Avec qui le Coran ordonne-t-il au Prophète ﷺ de rester patient, dans Al-Kahf ?",
             ["Ceux qui invoquent leur Seigneur matin et soir, désirant Sa face", "Les chefs de tribu", "Les riches marchands", "Les poètes"], 0,
             "« Fais preuve de patience en compagnie de ceux qui invoquent leur Seigneur matin et soir, désirant Sa face ; et que tes yeux ne se détachent point d'eux. »",
             "Coran — Sourate Al-Kahf, 18:28"),
        en=L("With whom does the Quran command the Prophet ﷺ to keep patient company, in Al-Kahf?",
             ["Those who call upon their Lord morning and evening, seeking His face", "The tribal chiefs", "The rich merchants", "The poets"], 0,
             "\"And keep yourself patient with those who call upon their Lord in the morning and the evening, seeking His face; and let not your eyes pass beyond them.\"",
             "Quran — Surah Al-Kahf, 18:28"),
        ar=L("مع مَن أُمر النبي ﷺ بالصبر في سورة الكهف؟",
             ["مع الذين يدعون ربهم بالغداة والعشي يريدون وجهه", "مع سادة القبائل", "مع كبار التجار", "مع الشعراء"], 0,
             "«واصبر نفسك مع الذين يدعون ربهم بالغداة والعشي يريدون وجهه، ولا تعدُ عيناك عنهم».",
             "القرآن — سورة الكهف، 18:28"))

    add("virtues_097", "virtues", "medium", "quran", Q, "5:2", False,
        fr=L("Sur quoi le Coran ordonne-t-il de s'entraider, et sur quoi il l'interdit ?",
             ["S'entraider dans la piété et le bien, non dans le péché et l'agression", "S'entraider en tout", "Ne s'entraider avec personne", "S'entraider seulement en famille"], 0,
             "« Entraidez-vous dans l'accomplissement des bonnes œuvres et de la piété, et ne vous entraidez pas dans le péché et la transgression. »",
             "Coran — Sourate Al-Mâ'ida, 5:2"),
        en=L("On what does the Quran command mutual help, and on what does it forbid it?",
             ["Cooperate in righteousness and piety, not in sin and aggression", "Cooperate in everything", "Cooperate with no one", "Cooperate only within the family"], 0,
             "\"And cooperate in righteousness and piety, but do not cooperate in sin and aggression.\"",
             "Quran — Surah Al-Ma'idah, 5:2"),
        ar=L("على ماذا أمر القرآن بالتعاون وعلى ماذا نهى؟",
             ["التعاون على البر والتقوى لا على الإثم والعدوان", "التعاون في كل شيء", "ترك التعاون", "التعاون داخل الأسرة فقط"], 0,
             "«وتعاونوا على البر والتقوى ولا تعاونوا على الإثم والعدوان».",
             "القرآن — سورة المائدة، 5:2"))

    add("virtues_098", "virtues", "hard", "quran", Q, "16:91", False,
        fr=L("Que le Coran ordonne-t-il au sujet du pacte conclu et des serments confirmés ?",
             ["Remplir le pacte et ne pas violer les serments après les avoir affermis", "Les renégocier", "Les oublier", "Les cacher"], 0,
             "« Soyez fidèles au pacte d'Allah après l'avoir contracté et ne violez pas vos serments après les avoir solennellement prêtés. »",
             "Coran — Sourate An-Nahl, 16:91"),
        en=L("What does the Quran command about a covenant made and oaths confirmed?",
             ["To fulfil the covenant and not break oaths after confirming them", "To renegotiate them", "To forget them", "To hide them"], 0,
             "\"And fulfil the covenant of Allah when you have taken it, and do not break oaths after their confirmation.\"",
             "Quran — Surah An-Nahl, 16:91"),
        ar=L("بماذا أمر القرآن في العهد المعقود والأيمان المؤكَّدة؟",
             ["الوفاء بالعهد وعدم نقض الأيمان بعد توكيدها", "إعادة التفاوض", "النسيان", "الكتمان"], 0,
             "«وأوفوا بعهد الله إذا عاهدتم ولا تنقضوا الأيمان بعد توكيدها».",
             "القرآن — سورة النحل، 16:91"))

    add("virtues_099", "virtues", "hard", "hadithBukhari", B, "13", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, quand la foi d'un homme est-elle complète ?",
             ["Quand il aime pour son frère ce qu'il aime pour lui-même", "Quand il jeûne toute l'année", "Quand il donne tout son bien", "Quand il voyage vers La Mecque"], 0,
             "« Aucun de vous ne croit vraiment tant qu'il n'aime pas pour son frère ce qu'il aime pour lui-même. »",
             "Sahîh al-Bukhârî, 13"),
        en=L("According to a hadith reported by al-Bukhari, when is a man's faith complete?",
             ["When he loves for his brother what he loves for himself", "When he fasts the whole year", "When he gives away all his wealth", "When he travels to Makkah"], 0,
             "\"None of you truly believes until he loves for his brother what he loves for himself.\"",
             "Sahih al-Bukhari, 13"),
        ar=L("بحسب حديث رواه البخاري، متى يكمل إيمان المرء؟",
             ["حتى يحب لأخيه ما يحب لنفسه", "حتى يصوم الدهر", "حتى ينفق ماله كله", "حتى يسافر إلى مكة"], 0,
             "«لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه».",
             "صحيح البخاري، 13"))

    add("virtues_100", "virtues", "medium", "quran", Q, "4:114", False,
        fr=L("Dans quels cas le Coran voit-il du bien dans les conciliabules ?",
             ["Ordonner une aumône, une bonne action, ou une réconciliation entre les gens", "Discuter d'affaires", "Préparer un voyage", "Raconter des nouvelles"], 0,
             "« Il n'y a rien de bon dans la plupart de leurs conversations secrètes, sauf si l'un d'eux ordonne une aumône, une bonne action ou une conciliation entre les gens. »",
             "Coran — Sourate An-Nisâ, 4:114"),
        en=L("In which cases does the Quran see good in private conversation?",
             ["Enjoining charity, a good deed, or reconciliation between people", "Discussing business", "Planning a journey", "Passing on news"], 0,
             "\"No good is there in much of their private conversation, except for one who enjoins charity or what is right or conciliation between people.\"",
             "Quran — Surah An-Nisa, 4:114"),
        ar=L("في أي الأحوال جعل القرآن في النجوى خيرًا؟",
             ["من أمر بصدقة أو معروف أو إصلاح بين الناس", "في مدارسة التجارة", "في تدبير سفر", "في نقل الأخبار"], 0,
             "«لا خير في كثير من نجواهم إلا من أمر بصدقة أو معروف أو إصلاح بين الناس».",
             "القرآن — سورة النساء، 4:114"))
