"""Virtues & manners — part B (virtues_019 … virtues_050)."""


def register(add, L):
    Q = "Quran"
    B = "Sahih al-Bukhari"
    M = "Sahih Muslim"

    add("virtues_019", "virtues", "easy", "hadithBukhari", B, "6094", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, vers quoi la véracité (sidq) conduit-elle ?",
             ["Vers la piété, et la piété conduit au Paradis", "Vers la richesse", "Vers la célébrité", "Vers la force"], 0,
             "« La véracité mène à la piété, et la piété mène au Paradis ; le mensonge mène à la perversité, et la perversité mène au Feu. »",
             "Sahîh al-Bukhârî, 6094"),
        en=L("According to a hadith in al-Bukhari, where does truthfulness (sidq) lead?",
             ["To righteousness, and righteousness leads to Paradise", "To wealth", "To fame", "To strength"], 0,
             "\"Truthfulness leads to righteousness, and righteousness leads to Paradise; lying leads to wickedness, and wickedness leads to the Fire.\"",
             "Sahih al-Bukhari, 6094"),
        ar=L("بحسب حديث رواه البخاري، إلامَ يهدي الصدق؟",
             ["إلى البر، والبر يهدي إلى الجنة", "إلى الغنى", "إلى الشهرة", "إلى القوة"], 0,
             "«إن الصدق يهدي إلى البر، وإن البر يهدي إلى الجنة، وإن الكذب يهدي إلى الفجور، وإن الفجور يهدي إلى النار».",
             "صحيح البخاري، 6094"))

    add("virtues_020", "virtues", "medium", "hadithBukhari", B, "33", False,
        fr=L("Selon un hadith authentique, quels sont les trois signes de l'hypocrite ?",
             ["Il ment quand il parle, trahit sa promesse et trahit la confiance", "Il dort, mange et parle trop", "Il voyage, commerce et chante", "Il prie peu, jeûne peu et lit peu"], 0,
             "« Les signes de l'hypocrite sont trois : quand il parle il ment, quand il promet il ne tient pas, et quand on lui confie quelque chose il trahit. »",
             "Sahîh al-Bukhârî, 33"),
        en=L("According to an authentic hadith, what are the three signs of a hypocrite?",
             ["He lies when he speaks, breaks his promise and betrays trust", "He sleeps, eats and talks too much", "He travels, trades and sings", "He prays little, fasts little and reads little"], 0,
             "\"The signs of a hypocrite are three: when he speaks he lies, when he promises he breaks it, and when he is trusted he betrays.\"",
             "Sahih al-Bukhari, 33"),
        ar=L("بحسب الحديث الصحيح، ما علامات المنافق الثلاث؟",
             ["إذا حدّث كذب، وإذا وعد أخلف، وإذا اؤتمن خان", "كثرة النوم والأكل والكلام", "السفر والتجارة والغناء", "قلة الصلاة والصيام والقراءة"], 0,
             "«آية المنافق ثلاث: إذا حدّث كذب، وإذا وعد أخلف، وإذا اؤتمن خان».",
             "صحيح البخاري، 33"))

    add("virtues_021", "virtues", "easy", "hadithBukhari", B, "6116", False,
        fr=L("Un homme demanda un conseil au Prophète ﷺ ; que lui répéta-t-il plusieurs fois ?",
             ["« Ne te mets pas en colère »", "« Voyage beaucoup »", "« Mange peu »", "« Parle fort »"], 0,
             "L'homme dit : « Conseille-moi. » Il répondit : « Ne te mets pas en colère. » L'homme insista, et il répéta : « Ne te mets pas en colère. »",
             "Sahîh al-Bukhârî, 6116"),
        en=L("A man asked the Prophet ﷺ for advice; what did he repeat to him several times?",
             ["\"Do not get angry\"", "\"Travel a lot\"", "\"Eat little\"", "\"Speak loudly\""], 0,
             "The man said: \"Advise me.\" He replied: \"Do not get angry.\" The man asked again, and he repeated: \"Do not get angry.\"",
             "Sahih al-Bukhari, 6116"),
        ar=L("طلب رجل من النبي ﷺ وصية، فماذا كرّر له مرات؟",
             ["«لا تغضب»", "«أكثر من السفر»", "«قلّل الأكل»", "«ارفع صوتك»"], 0,
             "قال الرجل: أوصني. قال: «لا تغضب». فردّد مرارًا، قال: «لا تغضب».",
             "صحيح البخاري، 6116"))

    add("virtues_022", "virtues", "easy", "hadithBukhari", B, "6114", False,
        fr=L("Selon le Prophète ﷺ, qui est vraiment fort ?",
             ["Celui qui se maîtrise dans la colère", "Celui qui gagne à la lutte", "Celui qui porte les charges les plus lourdes", "Celui qui court le plus vite"], 0,
             "« Le fort n'est pas celui qui terrasse les autres ; le fort est celui qui se maîtrise au moment de la colère. »",
             "Sahîh al-Bukhârî, 6114"),
        en=L("According to the Prophet ﷺ, who is truly strong?",
             ["The one who controls himself when angry", "The one who wins at wrestling", "The one who carries the heaviest loads", "The one who runs fastest"], 0,
             "\"The strong one is not the one who overcomes others in wrestling; the strong one is the one who controls himself when angry.\"",
             "Sahih al-Bukhari, 6114"),
        ar=L("من هو الشديد حقًا بحسب النبي ﷺ؟",
             ["الذي يملك نفسه عند الغضب", "الذي يغلب في المصارعة", "الذي يحمل أثقل الأحمال", "الذي يجري أسرع"], 0,
             "«ليس الشديد بالصُّرَعة، إنما الشديد الذي يملك نفسه عند الغضب».",
             "صحيح البخاري، 6114"))

    add("virtues_023", "virtues", "easy", "hadithBukhari", B, "24", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, de quoi la pudeur (hayâ') fait-elle partie ?",
             ["De la foi", "De la faiblesse", "De la richesse", "De la timidité blâmable"], 0,
             "Voyant un homme reprocher sa pudeur à son frère, le Prophète ﷺ dit : « Laisse-le, car la pudeur fait partie de la foi. »",
             "Sahîh al-Bukhârî, 24"),
        en=L("According to a hadith in al-Bukhari, what is modesty (haya') a part of?",
             ["Faith", "Weakness", "Wealth", "Blameworthy shyness"], 0,
             "Seeing a man rebuke his brother for his modesty, the Prophet ﷺ said: \"Leave him, for modesty is part of faith.\"",
             "Sahih al-Bukhari, 24"),
        ar=L("بحسب حديث رواه البخاري، الحياء من ماذا؟",
             ["من الإيمان", "من الضعف", "من الغنى", "من الخجل المذموم"], 0,
             "رأى النبي ﷺ رجلًا يعاتب أخاه في الحياء فقال: «دعه، فإن الحياء من الإيمان».",
             "صحيح البخاري، 24"))

    add("virtues_024", "virtues", "easy", "hadithBukhari", B, "5997", False,
        fr=L("Que dit le Prophète ﷺ à un homme qui se vantait de n'avoir jamais embrassé ses dix enfants ?",
             ["« Celui qui ne fait pas miséricorde ne recevra pas de miséricorde »", "« Tu as raison »", "« Les enfants ne comptent pas »", "« C'est une affaire privée »"], 0,
             "Le Prophète ﷺ embrassait ses petits-enfants ; à Al-Aqra' qui s'en étonnait, il répondit : « Man lâ yarham lâ yurham. »",
             "Sahîh al-Bukhârî, 5997"),
        en=L("What did the Prophet ﷺ say to a man who boasted that he had never kissed any of his ten children?",
             ["\"Whoever does not show mercy will not be shown mercy\"", "\"You are right\"", "\"Children do not matter\"", "\"That is a private matter\""], 0,
             "The Prophet ﷺ used to kiss his grandchildren; to Al-Aqra', who was surprised, he replied: \"Man la yarham la yurham.\"",
             "Sahih al-Bukhari, 5997"),
        ar=L("ماذا قال النبي ﷺ لرجل افتخر بأنه لم يقبّل أحدًا من أولاده العشرة؟",
             ["«من لا يَرحم لا يُرحم»", "«أصبت»", "«الأولاد لا يهمون»", "«هذا أمر خاص»"], 0,
             "كان النبي ﷺ يقبّل أحفاده، فلما تعجب الأقرع بن حابس قال له: «من لا يَرحم لا يُرحم».",
             "صحيح البخاري، 5997"))

    add("virtues_025", "virtues", "easy", "hadithBukhari", B, "2363", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, pour quel acte un homme fut-il pardonné ?",
             ["Pour avoir donné à boire à un chien assoiffé", "Pour avoir construit un puits", "Pour avoir planté un arbre", "Pour avoir chassé un loup"], 0,
             "L'homme descendit dans un puits, remplit sa chaussure d'eau et abreuva le chien qui haletait de soif ; Allah lui pardonna.",
             "Sahîh al-Bukhârî, 2363"),
        en=L("According to a hadith in al-Bukhari, for which deed was a man forgiven?",
             ["For giving water to a thirsty dog", "For building a well", "For planting a tree", "For driving away a wolf"], 0,
             "The man went down a well, filled his shoe with water and gave it to a dog panting with thirst; Allah forgave him.",
             "Sahih al-Bukhari, 2363"),
        ar=L("بحسب حديث رواه البخاري، بأي عمل غُفر لرجل؟",
             ["بسقي كلب عطشان", "ببناء بئر", "بغرس شجرة", "بطرد ذئب"], 0,
             "نزل الرجل البئر فملأ خفّه ماءً وسقى الكلب الذي يلهث من العطش، فغفر الله له.",
             "صحيح البخاري، 2363"))

    add("virtues_026", "virtues", "medium", "hadithBukhari", B, "3318", False,
        fr=L("Selon un hadith authentique, pourquoi une femme fut-elle châtiée ?",
             ["Pour avoir enfermé un chat sans le nourrir ni le laisser chercher sa nourriture", "Pour avoir vendu un chat", "Pour avoir chassé un chat de sa maison", "Pour avoir adopté trop de chats"], 0,
             "« Une femme fut châtiée à cause d'un chat qu'elle avait enfermé jusqu'à ce qu'il meure : elle ne le nourrissait pas et ne le laissait pas manger les bêtes de la terre. »",
             "Sahîh al-Bukhârî, 3318"),
        en=L("According to an authentic hadith, why was a woman punished?",
             ["For locking up a cat without feeding it or letting it find food", "For selling a cat", "For chasing a cat from her house", "For adopting too many cats"], 0,
             "\"A woman was punished because of a cat she had confined until it died: she neither fed it nor let it eat from the creatures of the earth.\"",
             "Sahih al-Bukhari, 3318"),
        ar=L("بحسب الحديث الصحيح، لماذا عُذّبت امرأة؟",
             ["لأنها حبست هرّة فلم تطعمها ولم تتركها تأكل من خشاش الأرض", "لأنها باعت هرّة", "لأنها طردت هرّة من بيتها", "لأنها ربّت هررًا كثيرة"], 0,
             "«عُذّبت امرأة في هرّة حبستها حتى ماتت جوعًا، فلا هي أطعمتها ولا هي أرسلتها تأكل من خشاش الأرض».",
             "صحيح البخاري، 3318"))

    add("virtues_027", "virtues", "medium", "hadithBukhari", B, "6014", False,
        fr=L("À propos de qui le Prophète ﷺ dit-il que Jibrîl lui fit tant de recommandations qu'il crut qu'il en ferait un héritier ?",
             ["Le voisin", "L'invité", "L'orphelin", "Le voyageur"], 0,
             "« Jibrîl n'a cessé de me recommander le voisin, au point que j'ai cru qu'il allait le faire hériter. »",
             "Sahîh al-Bukhârî, 6014"),
        en=L("About whom did the Prophet ﷺ say that Jibril kept recommending him so much that he thought he would make him an heir?",
             ["The neighbour", "The guest", "The orphan", "The traveller"], 0,
             "\"Jibril kept recommending the neighbour to me until I thought he would make him an heir.\"",
             "Sahih al-Bukhari, 6014"),
        ar=L("في حق من قال النبي ﷺ إن جبريل ما زال يوصيه به حتى ظن أنه سيورّثه؟",
             ["الجار", "الضيف", "اليتيم", "المسافر"], 0,
             "«ما زال جبريل يوصيني بالجار حتى ظننت أنه سيورّثه».",
             "صحيح البخاري، 6014"))

    add("virtues_028", "virtues", "hard", "hadithBukhari", B, "1240", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, combien de droits le musulman a-t-il sur son frère musulman ?",
             ["Cinq", "Trois", "Sept", "Dix"], 0,
             "« Rendre le salut, visiter le malade, suivre le convoi funèbre, répondre à l'invitation, et dire “yarhamuka Allâh” à celui qui éternue. »",
             "Sahîh al-Bukhârî, 1240"),
        en=L("According to a hadith in al-Bukhari, how many rights does a Muslim have over his fellow Muslim?",
             ["Five", "Three", "Seven", "Ten"], 0,
             "\"Returning the greeting, visiting the sick, following the funeral, accepting the invitation, and responding to the one who sneezes.\"",
             "Sahih al-Bukhari, 1240"),
        ar=L("بحسب حديث رواه البخاري، كم حقًا للمسلم على المسلم؟",
             ["خمسة", "ثلاثة", "سبعة", "عشرة"], 0,
             "«ردّ السلام، وعيادة المريض، واتباع الجنائز، وإجابة الدعوة، وتشميت العاطس».",
             "صحيح البخاري، 1240"))

    add("virtues_029", "virtues", "medium", "hadithBukhari", B, "12", False,
        fr=L("À la question « Quel islam est le meilleur ? », que répondit le Prophète ﷺ ?",
             ["Nourrir les gens et saluer ceux que tu connais et ceux que tu ne connais pas", "Construire des mosquées", "Beaucoup voyager", "Parler peu"], 0,
             "« Tu donnes à manger, et tu adresses le salut à celui que tu connais et à celui que tu ne connais pas. »",
             "Sahîh al-Bukhârî, 12"),
        en=L("When asked \"Which Islam is best?\", what did the Prophet ﷺ answer?",
             ["Feeding people and greeting those you know and those you do not", "Building mosques", "Travelling a lot", "Speaking little"], 0,
             "\"To feed others, and to give the greeting of peace to those you know and those you do not know.\"",
             "Sahih al-Bukhari, 12"),
        ar=L("لما سُئل النبي ﷺ: أي الإسلام خير؟ بماذا أجاب؟",
             ["تُطعم الطعام وتقرأ السلام على من عرفت ومن لم تعرف", "بناء المساجد", "كثرة السفر", "قلة الكلام"], 0,
             "«تُطعم الطعام، وتقرأ السلام على من عرفت ومن لم تعرف».",
             "صحيح البخاري، 12"))

    add("virtues_030", "virtues", "easy", "hadithBukhari", B, "6011", False,
        fr=L("À quoi le Prophète ﷺ compare-t-il les croyants dans leur affection et leur entraide ?",
             ["À un seul corps : si un membre souffre, tout le corps veille et a la fièvre", "À une forêt", "À une caravane", "À un troupeau"], 0,
             "« Les croyants, dans leur amour, leur miséricorde et leur compassion mutuels, sont comme un seul corps. »",
             "Sahîh al-Bukhârî, 6011"),
        en=L("To what does the Prophet ﷺ compare the believers in their love and mutual support?",
             ["To one body: if one limb suffers, the whole body stays awake with fever", "To a forest", "To a caravan", "To a flock"], 0,
             "\"The believers, in their mutual love, mercy and compassion, are like one body.\"",
             "Sahih al-Bukhari, 6011"),
        ar=L("بماذا شبّه النبي ﷺ المؤمنين في توادّهم وتراحمهم؟",
             ["بالجسد الواحد: إذا اشتكى منه عضو تداعى له سائر الجسد بالسهر والحمى", "بالغابة", "بالقافلة", "بالقطيع"], 0,
             "«مثل المؤمنين في توادّهم وتراحمهم وتعاطفهم مثل الجسد».",
             "صحيح البخاري، 6011"))

    add("virtues_031", "virtues", "medium", "hadithBukhari", B, "6064", False,
        fr=L("Selon le Prophète ﷺ, qu'est-ce qui est « la plus mensongère des paroles » ?",
             ["La suspicion (zann)", "La poésie", "La plaisanterie", "Le silence"], 0,
             "« Gardez-vous de la suspicion, car la suspicion est la plus mensongère des paroles. »",
             "Sahîh al-Bukhârî, 6064"),
        en=L("According to the Prophet ﷺ, what is \"the most false of speech\"?",
             ["Suspicion (zann)", "Poetry", "Joking", "Silence"], 0,
             "\"Beware of suspicion, for suspicion is the most false of speech.\"",
             "Sahih al-Bukhari, 6064"),
        ar=L("ما «أكذب الحديث» بحسب النبي ﷺ؟",
             ["الظن", "الشعر", "المزاح", "الصمت"], 0,
             "«إياكم والظن، فإن الظن أكذب الحديث».",
             "صحيح البخاري، 6064"))

    add("virtues_032", "virtues", "easy", "hadithBukhari", B, "6077", False,
        fr=L("Selon un hadith authentique, combien de jours au maximum un musulman peut-il bouder son frère ?",
             ["Trois jours", "Sept jours", "Un mois", "Un an"], 0,
             "« Il n'est pas permis à un homme de bouder son frère plus de trois nuits… et le meilleur des deux est celui qui salue le premier. »",
             "Sahîh al-Bukhârî, 6077"),
        en=L("According to an authentic hadith, for how many days at most may a Muslim shun his brother?",
             ["Three days", "Seven days", "A month", "A year"], 0,
             "\"It is not lawful for a man to shun his brother for more than three nights… and the better of the two is the one who greets first.\"",
             "Sahih al-Bukhari, 6077"),
        ar=L("بحسب الحديث الصحيح، كم يومًا على الأكثر يجوز للمسلم أن يهجر أخاه؟",
             ["ثلاثة أيام", "سبعة أيام", "شهرًا", "سنة"], 0,
             "«لا يحل لرجل أن يهجر أخاه فوق ثلاث ليال... وخيرهما الذي يبدأ بالسلام».",
             "صحيح البخاري، 6077"))

    add("virtues_033", "virtues", "easy", "hadithBukhari", B, "6021", False,
        fr=L("Selon le Prophète ﷺ, quelle est la valeur de chaque bonne action, même petite ?",
             ["C'est une aumône (sadaqa)", "Elle ne compte pas", "Elle vaut un dinar", "Elle remplace la prière"], 0,
             "« Toute bonne action est une aumône. »",
             "Sahîh al-Bukhârî, 6021"),
        en=L("According to the Prophet ﷺ, what is the value of every good deed, however small?",
             ["It is a charity (sadaqa)", "It does not count", "It is worth a dinar", "It replaces the prayer"], 0,
             "\"Every good deed is a charity.\"",
             "Sahih al-Bukhari, 6021"),
        ar=L("ما قيمة كل عمل خير مهما صغر بحسب النبي ﷺ؟",
             ["صدقة", "لا يُحسب", "يساوي دينارًا", "يغني عن الصلاة"], 0,
             "«كل معروف صدقة».",
             "صحيح البخاري، 6021"))

    add("virtues_034", "virtues", "hard", "hadithMuslim", M, "35", False,
        fr=L("Selon un hadith rapporté par Muslim, quelle est la plus humble des branches de la foi ?",
             ["Écarter ce qui nuit du chemin", "Bâtir une mosquée", "Réciter un juz'", "Jeûner un jour"], 0,
             "« La foi compte soixante-dix et quelques branches : la plus haute est “lâ ilâha illa Allâh”, la plus humble est d'écarter ce qui nuit du chemin ; et la pudeur est une branche de la foi. »",
             "Sahîh Muslim, 35"),
        en=L("According to a hadith in Sahih Muslim, what is the humblest branch of faith?",
             ["Removing something harmful from the road", "Building a mosque", "Reciting a juz'", "Fasting a day"], 0,
             "\"Faith has seventy-odd branches: the highest is 'la ilaha illa Allah', the lowest is removing something harmful from the road; and modesty is a branch of faith.\"",
             "Sahih Muslim, 35"),
        ar=L("بحسب حديث رواه مسلم، ما أدنى شعب الإيمان؟",
             ["إماطة الأذى عن الطريق", "بناء مسجد", "قراءة جزء", "صيام يوم"], 0,
             "«الإيمان بضع وسبعون شعبة: فأفضلها قول لا إله إلا الله، وأدناها إماطة الأذى عن الطريق، والحياء شعبة من الإيمان».",
             "صحيح مسلم، 35"))

    add("virtues_035", "virtues", "medium", "hadithMuslim", M, "223", False,
        fr=L("Selon un hadith rapporté par Muslim, la propreté (tahâra) est… ?",
             ["La moitié de la foi", "Un tiers de la foi", "Un dixième de la foi", "Sans rapport avec la foi"], 0,
             "« La propreté est la moitié de la foi, et “al-hamdu li-Llâh” remplit la balance. »",
             "Sahîh Muslim, 223"),
        en=L("According to a hadith in Sahih Muslim, cleanliness (tahara) is… ?",
             ["Half of faith", "A third of faith", "A tenth of faith", "Unrelated to faith"], 0,
             "\"Purity is half of faith, and 'al-hamdu li-Llah' fills the scale.\"",
             "Sahih Muslim, 223"),
        ar=L("بحسب حديث رواه مسلم، الطهور…؟",
             ["شطر الإيمان", "ثلث الإيمان", "عُشر الإيمان", "لا علاقة له بالإيمان"], 0,
             "«الطهور شطر الإيمان، والحمد لله تملأ الميزان».",
             "صحيح مسلم، 223"))

    add("virtues_036", "virtues", "hard", "hadithMuslim", M, "55", False,
        fr=L("Le Prophète ﷺ a dit : « La religion, c'est la nasîha (le conseil sincère) » — envers qui, en premier ?",
             ["Envers Allah, Son Livre, Son Messager, les dirigeants et l'ensemble des musulmans", "Envers soi-même seulement", "Envers les riches", "Envers les étrangers"], 0,
             "On demanda : « Envers qui ? » Il dit : « Envers Allah, Son Livre, Son Messager, les chefs des musulmans et leur ensemble. »",
             "Sahîh Muslim, 55"),
        en=L("The Prophet ﷺ said: \"Religion is nasiha (sincere counsel)\" — towards whom?",
             ["Towards Allah, His Book, His Messenger, the leaders and all the Muslims", "Towards oneself only", "Towards the rich", "Towards strangers"], 0,
             "They asked: \"Towards whom?\" He said: \"Towards Allah, His Book, His Messenger, the leaders of the Muslims and their common people.\"",
             "Sahih Muslim, 55"),
        ar=L("قال النبي ﷺ: «الدين النصيحة» — لمن؟",
             ["لله ولكتابه ولرسوله ولأئمة المسلمين وعامتهم", "للنفس فقط", "للأغنياء", "للغرباء"], 0,
             "قالوا: لمن؟ قال: «لله، ولكتابه، ولرسوله، ولأئمة المسلمين وعامتهم».",
             "صحيح مسلم، 55"))

    add("virtues_037", "virtues", "easy", "hadithMuslim", M, "2564", False,
        fr=L("Selon un hadith rapporté par Muslim, que regarde Allah chez Ses serviteurs ?",
             ["Leurs cœurs et leurs actes", "Leur apparence", "Leur richesse", "Leur nombre"], 0,
             "« Allah ne regarde ni vos corps ni vos apparences, mais Il regarde vos cœurs et vos actes. »",
             "Sahîh Muslim, 2564"),
        en=L("According to a hadith in Sahih Muslim, what does Allah look at in His servants?",
             ["Their hearts and their deeds", "Their appearance", "Their wealth", "Their number"], 0,
             "\"Allah does not look at your bodies or your appearances, but He looks at your hearts and your deeds.\"",
             "Sahih Muslim, 2564"),
        ar=L("بحسب حديث رواه مسلم، إلامَ ينظر الله من عباده؟",
             ["إلى قلوبهم وأعمالهم", "إلى صورهم", "إلى أموالهم", "إلى عددهم"], 0,
             "«إن الله لا ينظر إلى أجسادكم ولا إلى صوركم، ولكن ينظر إلى قلوبكم وأعمالكم».",
             "صحيح مسلم، 2564"))

    add("virtues_038", "virtues", "medium", "hadithMuslim", M, "2699", False,
        fr=L("Selon un hadith rapporté par Muslim, que fait Allah pour celui qui soulage un croyant d'une difficulté de ce monde ?",
             ["Il le soulage d'une difficulté du Jour de la Résurrection", "Il le rend riche", "Il lui accorde une longue vie", "Il le rend célèbre"], 0,
             "« Quiconque soulage un croyant d'une peine de ce monde, Allah le soulagera d'une peine du Jour de la Résurrection. »",
             "Sahîh Muslim, 2699"),
        en=L("According to a hadith in Sahih Muslim, what does Allah do for the one who relieves a believer of a hardship of this world?",
             ["He relieves him of a hardship on the Day of Resurrection", "He makes him rich", "He grants him a long life", "He makes him famous"], 0,
             "\"Whoever relieves a believer of a hardship of this world, Allah will relieve him of a hardship on the Day of Resurrection.\"",
             "Sahih Muslim, 2699"),
        ar=L("بحسب حديث رواه مسلم، ماذا يفعل الله لمن نفّس عن مؤمن كربة من كرب الدنيا؟",
             ["ينفّس عنه كربة من كرب يوم القيامة", "يجعله غنيًا", "يطيل عمره", "يجعله مشهورًا"], 0,
             "«من نفّس عن مؤمن كربة من كرب الدنيا نفّس الله عنه كربة من كرب يوم القيامة».",
             "صحيح مسلم، 2699"))

    add("virtues_039", "virtues", "easy", "hadithMuslim", M, "2699", False,
        fr=L("Selon le Prophète ﷺ, que fait Allah pour celui qui emprunte un chemin à la recherche du savoir ?",
             ["Il lui facilite un chemin vers le Paradis", "Il le dispense de prier", "Il le rend riche", "Il le fait roi"], 0,
             "« Quiconque emprunte un chemin pour y chercher un savoir, Allah lui facilite par là un chemin vers le Paradis. »",
             "Sahîh Muslim, 2699"),
        en=L("According to the Prophet ﷺ, what does Allah do for the one who travels a path in search of knowledge?",
             ["He makes easy for him a path to Paradise", "He excuses him from prayer", "He makes him rich", "He makes him a king"], 0,
             "\"Whoever travels a path in search of knowledge, Allah makes easy for him a path to Paradise.\"",
             "Sahih Muslim, 2699"),
        ar=L("بحسب النبي ﷺ، ماذا يفعل الله لمن سلك طريقًا يطلب فيه علمًا؟",
             ["يسهّل له طريقًا إلى الجنة", "يعفيه من الصلاة", "يجعله غنيًا", "يجعله ملكًا"], 0,
             "«ومن سلك طريقًا يلتمس فيه علمًا سهّل الله له به طريقًا إلى الجنة».",
             "صحيح مسلم، 2699"))

    add("virtues_040", "virtues", "easy", "hadithBukhari", B, "5027", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, qui est « le meilleur d'entre vous » ?",
             ["Celui qui apprend le Coran et l'enseigne", "Celui qui parle le mieux", "Celui qui possède le plus", "Celui qui voyage le plus"], 0,
             "« Le meilleur d'entre vous est celui qui apprend le Coran et l'enseigne. »",
             "Sahîh al-Bukhârî, 5027"),
        en=L("According to a hadith in al-Bukhari, who is \"the best of you\"?",
             ["The one who learns the Qur'an and teaches it", "The one who speaks best", "The one who owns the most", "The one who travels the most"], 0,
             "\"The best of you is the one who learns the Qur'an and teaches it.\"",
             "Sahih al-Bukhari, 5027"),
        ar=L("بحسب حديث رواه البخاري، من «خيركم»؟",
             ["من تعلّم القرآن وعلّمه", "أفصحكم", "أكثركم مالًا", "أكثركم سفرًا"], 0,
             "«خيركم من تعلّم القرآن وعلّمه».",
             "صحيح البخاري، 5027"))

    add("virtues_041", "virtues", "hard", "hadithMuslim", M, "91", False,
        fr=L("Comment le Prophète ﷺ a-t-il défini l'orgueil (kibr) ?",
             ["Rejeter la vérité et mépriser les gens", "Porter de beaux habits", "Aimer les belles chaussures", "Marcher vite"], 0,
             "À l'homme qui aimait avoir de beaux habits, il dit : « Allah est beau et aime la beauté. L'orgueil, c'est rejeter la vérité et mépriser les gens. »",
             "Sahîh Muslim, 91"),
        en=L("How did the Prophet ﷺ define arrogance (kibr)?",
             ["Rejecting the truth and looking down on people", "Wearing fine clothes", "Liking nice shoes", "Walking fast"], 0,
             "To the man who liked fine clothes he said: \"Allah is beautiful and loves beauty. Arrogance is rejecting the truth and despising people.\"",
             "Sahih Muslim, 91"),
        ar=L("كيف عرّف النبي ﷺ الكِبر؟",
             ["بطر الحق وغمط الناس", "لبس الثياب الحسنة", "حب النعال الجميلة", "سرعة المشي"], 0,
             "قال للرجل الذي يحب الثوب الحسن: «إن الله جميل يحب الجمال، الكبر بطر الحق وغمط الناس».",
             "صحيح مسلم، 91"))

    add("virtues_042", "virtues", "medium", "hadithBukhari", B, "6412", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, quels sont les deux bienfaits dont beaucoup de gens ne profitent pas ?",
             ["La santé et le temps libre", "L'argent et la gloire", "La force et la beauté", "La famille et les amis"], 0,
             "« Il y a deux bienfaits au sujet desquels beaucoup de gens sont perdants : la santé et le temps libre. »",
             "Sahîh al-Bukhârî, 6412"),
        en=L("According to a hadith in al-Bukhari, which two blessings do many people fail to make use of?",
             ["Health and free time", "Money and fame", "Strength and beauty", "Family and friends"], 0,
             "\"There are two blessings in which many people are at a loss: health and free time.\"",
             "Sahih al-Bukhari, 6412"),
        ar=L("بحسب حديث رواه البخاري، ما النعمتان اللتان يُغبن فيهما كثير من الناس؟",
             ["الصحة والفراغ", "المال والجاه", "القوة والجمال", "الأهل والأصحاب"], 0,
             "«نعمتان مغبون فيهما كثير من الناس: الصحة والفراغ».",
             "صحيح البخاري، 6412"))

    add("virtues_043", "virtues", "hard", "hadithBukhari", B, "6133", False,
        fr=L("Complétez ce hadith : « Le croyant n'est pas piqué deux fois… »",
             ["« …du même trou »", "« …par le même scorpion »", "« …dans la même journée »", "« …par la même abeille »"], 0,
             "« Lâ yuldaghu al-mu'minu min juhrin wâhidin marratayn » : le croyant tire leçon de ses erreurs.",
             "Sahîh al-Bukhârî, 6133"),
        en=L("Complete this hadith: \"The believer is not stung twice…\"",
             ["\"…from the same hole\"", "\"…by the same scorpion\"", "\"…in the same day\"", "\"…by the same bee\""], 0,
             "\"La yuldaghu al-mu'minu min juhrin wahidin marratayn\": the believer learns from his mistakes.",
             "Sahih al-Bukhari, 6133"),
        ar=L("أكمل الحديث: «لا يُلدغ المؤمن...»",
             ["«...من جحر واحد مرتين»", "«...من عقرب واحد»", "«...في يوم واحد»", "«...من نحلة واحدة»"], 0,
             "«لا يُلدغ المؤمن من جحر واحد مرتين»: المؤمن يتعظ من خطئه.",
             "صحيح البخاري، 6133"))

    add("virtues_044", "virtues", "medium", "hadithBukhari", B, "5534", False,
        fr=L("À quoi le Prophète ﷺ compare-t-il le bon compagnon, par opposition au forgeron ?",
             ["Au vendeur de musc", "Au boulanger", "Au berger", "Au marchand de tissu"], 0,
             "« Le bon compagnon est comme le porteur de musc : il t'en offre, ou tu lui en achètes, ou tu en sens l'odeur ; le mauvais est comme le soufflet du forgeron. »",
             "Sahîh al-Bukhârî, 5534"),
        en=L("To what does the Prophet ﷺ compare the good companion, as opposed to the blacksmith?",
             ["To the seller of musk", "To the baker", "To the shepherd", "To the cloth merchant"], 0,
             "\"The good companion is like the bearer of musk: he gives you some, or you buy from him, or you smell its fragrance; the bad one is like the blacksmith's bellows.\"",
             "Sahih al-Bukhari, 5534"),
        ar=L("بماذا شبّه النبي ﷺ الجليس الصالح في مقابل نافخ الكير؟",
             ["بحامل المسك", "بالخبّاز", "بالراعي", "ببائع القماش"], 0,
             "«مثل الجليس الصالح والسوء كحامل المسك ونافخ الكير: فحامل المسك إما أن يحذيك، وإما أن تبتاع منه، وإما أن تجد منه ريحًا طيبة».",
             "صحيح البخاري، 5534"))

    add("virtues_045", "virtues", "medium", "hadithBukhari", B, "893", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, de quoi chacun de nous est-il responsable, « comme un berger » ?",
             ["De ceux dont il a la charge", "De la météo", "Des étoiles", "Des récoltes des autres"], 0,
             "« Chacun de vous est un berger, et chacun est responsable de son troupeau » : le dirigeant de son peuple, l'homme de sa famille, la femme de sa maison.",
             "Sahîh al-Bukhârî, 893"),
        en=L("According to a hadith in al-Bukhari, for what is each of us responsible, \"like a shepherd\"?",
             ["For those in our care", "For the weather", "For the stars", "For other people's harvests"], 0,
             "\"Each of you is a shepherd, and each is responsible for his flock\": the ruler for his people, the man for his family, the woman for her household.",
             "Sahih al-Bukhari, 893"),
        ar=L("بحسب حديث رواه البخاري، عمّ يكون كل واحد منا مسؤولًا «كالراعي»؟",
             ["عن رعيته ومن تحت يده", "عن الطقس", "عن النجوم", "عن محاصيل الآخرين"], 0,
             "«كلكم راعٍ وكلكم مسؤول عن رعيته»: الإمام عن الناس، والرجل عن أهله، والمرأة عن بيت زوجها.",
             "صحيح البخاري، 893"))

    add("virtues_046", "virtues", "medium", "quran", Q, "41:34", False,
        fr=L("Selon le Coran, que se passe-t-il si l'on repousse le mal par ce qui est meilleur ?",
             ["Celui qui était un ennemi devient comme un ami chaleureux", "Le mal disparaît de la terre", "On devient riche", "Rien ne change"], 0,
             "« Repousse le mal par ce qui est meilleur, et voilà que celui avec qui tu avais une inimitié devient tel un ami chaleureux » (41:34).",
             "Coran 41:34"),
        en=L("According to the Qur'an, what happens if one repels evil with what is better?",
             ["The one who was an enemy becomes like a warm friend", "Evil vanishes from the earth", "One becomes rich", "Nothing changes"], 0,
             "\"Repel evil with what is better, and the one between whom and you was enmity will become as though he were a warm friend\" (41:34).",
             "Qur'an 41:34"),
        ar=L("بحسب القرآن، ماذا يحدث إذا دفع الإنسان السيئة بالتي هي أحسن؟",
             ["يصير الذي بينه وبينه عداوة كأنه وليّ حميم", "يختفي الشر من الأرض", "يصير غنيًا", "لا شيء يتغير"], 0,
             "«ادفع بالتي هي أحسن فإذا الذي بينك وبينه عداوة كأنه وليّ حميم» (41:34).",
             "القرآن 41:34"))

    add("virtues_047", "virtues", "medium", "quran", Q, "25:63", False,
        fr=L("Comment « les serviteurs du Tout-Miséricordieux » répondent-ils aux ignorants qui les provoquent, selon la sourate Al-Furqân ?",
             ["Ils disent : « Paix ! »", "Ils répondent par la colère", "Ils se moquent d'eux", "Ils les frappent"], 0,
             "« Les serviteurs du Tout-Miséricordieux marchent humblement sur la terre, et quand les ignorants s'adressent à eux, ils disent : Paix ! » (25:63).",
             "Coran 25:63"),
        en=L("How do \"the servants of the Most Merciful\" answer the ignorant who provoke them, according to Surah Al-Furqan?",
             ["They say: \"Peace!\"", "They answer with anger", "They mock them", "They strike them"], 0,
             "\"The servants of the Most Merciful walk humbly on the earth, and when the ignorant address them, they say: Peace!\" (25:63).",
             "Qur'an 25:63"),
        ar=L("كيف يردّ «عباد الرحمن» على الجاهلين إذا خاطبوهم، بحسب سورة الفرقان؟",
             ["يقولون: سلامًا", "يردّون بالغضب", "يسخرون منهم", "يضربونهم"], 0,
             "«وعباد الرحمن الذين يمشون على الأرض هونًا وإذا خاطبهم الجاهلون قالوا سلامًا» (25:63).",
             "القرآن 25:63"))

    add("virtues_048", "virtues", "easy", "quran", Q, "17:34", False,
        fr=L("Que dit le Coran au sujet de l'engagement (la promesse, le pacte) ?",
             ["« Tenez l'engagement, car on sera interrogé sur l'engagement »", "« L'engagement n'engage à rien »", "« Promettez seulement aux riches »", "« Ne promettez jamais »"], 0,
             "« Et remplissez l'engagement, car on sera interrogé au sujet des engagements » (17:34).",
             "Coran 17:34"),
        en=L("What does the Qur'an say about the covenant (a promise, a pledge)?",
             ["\"Fulfil the covenant, for the covenant will be questioned about\"", "\"A promise binds no one\"", "\"Only promise the rich\"", "\"Never promise\""], 0,
             "\"And fulfil the covenant; indeed, the covenant will be questioned about\" (17:34).",
             "Qur'an 17:34"),
        ar=L("ماذا قال القرآن عن العهد (الوعد والميثاق)؟",
             ["«وأوفوا بالعهد إن العهد كان مسؤولًا»", "«العهد لا يلزم أحدًا»", "«لا تعدوا إلا الأغنياء»", "«لا تعدوا أبدًا»"], 0,
             "«وأوفوا بالعهد إن العهد كان مسؤولًا» (17:34).",
             "القرآن 17:34"))

    add("virtues_049", "virtues", "medium", "quran", Q, "17:27", False,
        fr=L("De qui le Coran dit-il qu'ils sont « les frères des diables » ?",
             ["Les gaspilleurs", "Les voyageurs", "Les commerçants", "Les poètes"], 0,
             "« Les gaspilleurs sont les frères des diables, et le Diable est très ingrat envers son Seigneur » (17:27).",
             "Coran 17:27"),
        en=L("Of whom does the Qur'an say that they are \"the brothers of the devils\"?",
             ["The squanderers", "The travellers", "The merchants", "The poets"], 0,
             "\"The squanderers are the brothers of the devils, and the Devil is ever ungrateful to his Lord\" (17:27).",
             "Qur'an 17:27"),
        ar=L("من الذين وصفهم القرآن بأنهم «إخوان الشياطين»؟",
             ["المبذّرون", "المسافرون", "التجار", "الشعراء"], 0,
             "«إن المبذرين كانوا إخوان الشياطين وكان الشيطان لربه كفورًا» (17:27).",
             "القرآن 17:27"))

    add("virtues_050", "virtues", "hard", "hadithBukhari", B, "6406", False,
        fr=L("Quelles sont les « deux paroles légères sur la langue, lourdes dans la balance et aimées du Tout-Miséricordieux » ?",
             ["« Subhâna Allâhi wa bi-hamdih, subhâna Allâhi al-'Azîm »", "« Allâhu akbar, al-hamdu li-Llâh »", "« Lâ ilâha illa Allâh, Muhammad rasûlu Allâh »", "« Bismi Allâh, mâ shâ'a Allâh »"], 0,
             "« Deux paroles légères sur la langue, lourdes dans la balance, aimées du Tout-Miséricordieux : Gloire à Allah et louange à Lui ; gloire à Allah l'Immense. »",
             "Sahîh al-Bukhârî, 6406"),
        en=L("What are the \"two words light on the tongue, heavy on the scale, and beloved to the Most Merciful\"?",
             ["\"Subhana Allahi wa bi-hamdih, subhana Allahi al-'Azim\"", "\"Allahu akbar, al-hamdu li-Llah\"", "\"La ilaha illa Allah, Muhammad rasulu Allah\"", "\"Bismi Allah, ma sha'a Allah\""], 0,
             "\"Two words light on the tongue, heavy on the scale, beloved to the Most Merciful: Glory be to Allah and praise Him; glory be to Allah the Immense.\"",
             "Sahih al-Bukhari, 6406"),
        ar=L("ما الكلمتان «الخفيفتان على اللسان، الثقيلتان في الميزان، الحبيبتان إلى الرحمن»؟",
             ["«سبحان الله وبحمده، سبحان الله العظيم»", "«الله أكبر، الحمد لله»", "«لا إله إلا الله، محمد رسول الله»", "«بسم الله، ما شاء الله»"], 0,
             "«كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن: سبحان الله وبحمده، سبحان الله العظيم».",
             "صحيح البخاري، 6406"))
