"""Qur'anic sciences and content — part B (quran_081 … quran_150).

Facts about the Book itself: its names, its structure, its imagery, and
verses whose plain sense is what the question asks about. The
`well-established` class of CONTENT_SOURCE_POLICY §2bis covers the
counts and the terminology, which no single work is the source of.
"""

WT = "well-established terminology"


def register(add, L):
    Q = "Quran"

    add("quran_081", "quran", "easy", "quran", Q, "78:1-2", False,
        fr=L("Sur quoi les gens s'interrogent-ils, au début de la sourate An-Naba ?",
             ["La grande nouvelle", "La pluie", "Les étoiles", "Les récoltes"], 0,
             "« Sur quoi s'interrogent-ils mutuellement ? Sur la grande nouvelle. »",
             "Coran — Sourate An-Naba, 78:1-2"),
        en=L("What are people questioning one another about, at the start of Surah An-Naba?",
             ["The great news", "The rain", "The stars", "The harvests"], 0,
             "\"About what are they asking one another? About the great news.\"",
             "Quran — Surah An-Naba, 78:1-2"),
        ar=L("عمّ يتساءل الناس في مطلع سورة النبأ؟",
             ["عن النبأ العظيم", "عن المطر", "عن النجوم", "عن الزروع"], 0,
             "«عمّ يتساءلون، عن النبأ العظيم».",
             "القرآن — سورة النبأ، 78:1-2"))

    add("quran_082", "quran", "medium", "quran", Q, "101:1-3", False,
        fr=L("Que signifie « Al-Qâriʿa », titre de la sourate 101 ?",
             ["Le fracas (le jour qui frappe)", "L'aurore", "La caravane", "La montagne"], 0,
             "« Al-Qâriʿa ! Qu'est-ce que Al-Qâriʿa ? Et qui te dira ce qu'est Al-Qâriʿa ? » : c'est un nom du Jour dernier.",
             "Coran — Sourate Al-Qâriʿa, 101:1-3"),
        en=L("What does \"Al-Qari'ah\", the title of surah 101, mean?",
             ["The Striking Calamity", "The dawn", "The caravan", "The mountain"], 0,
             "\"The Striking Calamity! What is the Striking Calamity? And what can make you know what it is?\" — it is a name of the Last Day.",
             "Quran — Surah Al-Qari'ah, 101:1-3"),
        ar=L("ما معنى «القارعة» عنوان السورة 101؟",
             ["اسم من أسماء يوم القيامة", "الفجر", "القافلة", "الجبل"], 0,
             "«القارعة، ما القارعة، وما أدراك ما القارعة»: اسم من أسماء يوم القيامة.",
             "القرآن — سورة القارعة، 101:1-3"))

    add("quran_083", "quran", "hard", "quran", Q, "101:6-9", False,
        fr=L("Dans la sourate Al-Qâriʿa, à quoi sont comparées les balances de celui dont les œuvres sont légères ?",
             ["Son refuge sera un abîme (Hâwiya)", "Un jardin", "Une source", "Une maison"], 0,
             "« Quant à celui dont la balance sera légère, son refuge sera un abîme. »",
             "Coran — Sourate Al-Qâriʿa, 101:6-9"),
        en=L("In Surah Al-Qari'ah, what awaits the one whose scales are light?",
             ["His refuge will be an abyss (Hawiyah)", "A garden", "A spring", "A house"], 0,
             "\"But as for one whose scales are light, his refuge will be an abyss.\"",
             "Quran — Surah Al-Qari'ah, 101:6-9"),
        ar=L("في سورة القارعة، ما مصير من خفّت موازينه؟",
             ["فأمه هاوية", "جنة", "عين", "دار"], 0,
             "«وأما من خفّت موازينه فأمه هاوية».",
             "القرآن — سورة القارعة، 101:6-9"))

    add("quran_084", "quran", "easy", "quran", Q, "102:1", False,
        fr=L("De quoi la sourate At-Takâthur avertit-elle ?",
             ["La rivalité par l'accumulation, qui détourne", "Le voyage", "La faim", "Le silence"], 0,
             "« La rivalité par l'accumulation vous distrait, jusqu'à ce que vous visitiez les tombes. »",
             "Coran — Sourate At-Takâthur, 102:1"),
        en=L("What does Surah At-Takathur warn against?",
             ["Competition in amassing, which distracts", "Travelling", "Hunger", "Silence"], 0,
             "\"Competition in increase diverts you, until you visit the graveyards.\"",
             "Quran — Surah At-Takathur, 102:1"),
        ar=L("مِمّ تحذّر سورة التكاثر؟",
             ["من التكاثر الذي يُلهي", "من السفر", "من الجوع", "من الصمت"], 0,
             "«ألهاكم التكاثر حتى زرتم المقابر».",
             "القرآن — سورة التكاثر، 102:1"))

    add("quran_085", "quran", "medium", "quran", Q, "104:1", False,
        fr=L("Contre qui la sourate Al-Humaza commence-t-elle par « Malheur à… » ?",
             ["Le calomniateur médisant", "Le voyageur", "L'endormi", "Le pauvre"], 0,
             "« Malheur à tout calomniateur diffamateur, qui amasse une fortune et la compte. »",
             "Coran — Sourate Al-Humaza, 104:1"),
        en=L("Against whom does Surah Al-Humazah open with \"Woe to…\"?",
             ["Every scorner and backbiter", "The traveller", "The sleeper", "The poor"], 0,
             "\"Woe to every scorner and mocker, who collects wealth and counts it.\"",
             "Quran — Surah Al-Humazah, 104:1"),
        ar=L("على مَن افتُتحت سورة الهمزة بـ«ويل»؟",
             ["كل همزة لمزة", "المسافر", "النائم", "الفقير"], 0,
             "«ويل لكل همزة لمزة، الذي جمع مالًا وعدّده».",
             "القرآن — سورة الهمزة، 104:1"))

    add("quran_086", "quran", "hard", "quran", Q, "106:3-4", False,
        fr=L("Que la sourate Quraych demande-t-elle aux Quraych de faire, en retour des voyages d'hiver et d'été ?",
             ["Adorer le Seigneur de cette Maison, qui les a nourris et rassurés", "Bâtir des remparts", "Cesser le commerce", "Partir vers le Yémen"], 0,
             "« Qu'ils adorent donc le Seigneur de cette Maison, qui les a nourris contre la faim et rassurés contre la peur. »",
             "Coran — Sourate Quraych, 106:3-4"),
        en=L("What does Surah Quraysh ask Quraysh to do, in return for the winter and summer journeys?",
             ["Worship the Lord of this House, who fed them and secured them", "Build walls", "Stop trading", "Leave for Yemen"], 0,
             "\"Let them worship the Lord of this House, who has fed them against hunger and made them safe from fear.\"",
             "Quran — Surah Quraysh, 106:3-4"),
        ar=L("بماذا أمرت سورة قريش قريشًا في مقابل رحلتي الشتاء والصيف؟",
             ["أن يعبدوا رب هذا البيت الذي أطعمهم وآمنهم", "أن يبنوا الأسوار", "أن يتركوا التجارة", "أن يرحلوا إلى اليمن"], 0,
             "«فليعبدوا رب هذا البيت، الذي أطعمهم من جوع وآمنهم من خوف».",
             "القرآن — سورة قريش، 106:3-4"))

    add("quran_087", "quran", "easy", "quran", Q, "94:1", False,
        fr=L("Par quelle question commence la sourate Ash-Sharh ?",
             ["« N'avons-Nous pas ouvert ta poitrine ? »", "« N'as-tu pas vu ? »", "« Qui t'a créé ? »", "« Où vas-tu ? »"], 0,
             "« N'avons-Nous pas ouvert pour toi ta poitrine ? »",
             "Coran — Sourate Ash-Sharh, 94:1"),
        en=L("With what question does Surah Ash-Sharh open?",
             ["\"Did We not expand for you your breast?\"", "\"Have you not seen?\"", "\"Who created you?\"", "\"Where are you going?\""], 0,
             "\"Did We not expand for you your breast?\"",
             "Quran — Surah Ash-Sharh, 94:1"),
        ar=L("بأي سؤال افتُتحت سورة الشرح؟",
             ["«ألم نشرح لك صدرك؟»", "«ألم ترَ؟»", "«من خلقك؟»", "«أين تذهب؟»"], 0,
             "«ألم نشرح لك صدرك».",
             "القرآن — سورة الشرح، 94:1"))

    add("quran_088", "quran", "medium", "quran", Q, "95:1-3", False,
        fr=L("Par quoi Allah jure-t-Il au début de la sourate At-Tîn ?",
             ["Par le figuier, l'olivier, le mont Sinaï et cette cité sûre", "Par la nuit et le jour", "Par les étoiles", "Par la mer"], 0,
             "« Par le figuier et l'olivier ! Et par le mont Sinîn ! Et par cette cité sûre ! »",
             "Coran — Sourate At-Tîn, 95:1-3"),
        en=L("By what does Allah swear at the start of Surah At-Tin?",
             ["By the fig, the olive, Mount Sinai and this secure city", "By the night and the day", "By the stars", "By the sea"], 0,
             "\"By the fig and the olive, and by Mount Sinai, and by this secure city.\"",
             "Quran — Surah At-Tin, 95:1-3"),
        ar=L("بماذا أقسم الله في مطلع سورة التين؟",
             ["بالتين والزيتون وطور سينين والبلد الأمين", "بالليل والنهار", "بالنجوم", "بالبحر"], 0,
             "«والتين والزيتون، وطور سينين، وهذا البلد الأمين».",
             "القرآن — سورة التين، 95:1-3"))

    add("quran_089", "quran", "hard", "quran", Q, "95:4", False,
        fr=L("Comment la sourate At-Tîn décrit-elle la création de l'homme ?",
             ["Dans la forme la plus parfaite", "Faible et petit", "De feu", "De lumière"], 0,
             "« Nous avons certes créé l'homme dans la forme la plus parfaite. »",
             "Coran — Sourate At-Tîn, 95:4"),
        en=L("How does Surah At-Tin describe the creation of the human being?",
             ["In the best of forms", "Weak and small", "From fire", "From light"], 0,
             "\"We have certainly created man in the best of stature.\"",
             "Quran — Surah At-Tin, 95:4"),
        ar=L("كيف وصفت سورة التين خلق الإنسان؟",
             ["في أحسن تقويم", "ضعيفًا صغيرًا", "من نار", "من نور"], 0,
             "«لقد خلقنا الإنسان في أحسن تقويم».",
             "القرآن — سورة التين، 95:4"))

    add("quran_090", "quran", "easy", "quran", Q, "90:1-2", False,
        fr=L("Sur quelle cité Allah jure-t-Il au début de la sourate Al-Balad ?",
             ["La Mecque, où le Prophète ﷺ résidait", "Madîna", "Jérusalem", "Tâ'if"], 0,
             "« Non !… Je jure par cette cité, et toi, tu es un résident de cette cité. »",
             "Coran — Sourate Al-Balad, 90:1-2"),
        en=L("Which city does Allah swear by at the start of Surah Al-Balad?",
             ["Makkah, where the Prophet ﷺ dwelt", "Madinah", "Jerusalem", "Ta'if"], 0,
             "\"I swear by this city, and you are a dweller in this city.\"",
             "Quran — Surah Al-Balad, 90:1-2"),
        ar=L("بأي بلد أقسم الله في مطلع سورة البلد؟",
             ["مكة التي كان النبي ﷺ حالًّا بها", "المدينة", "بيت المقدس", "الطائف"], 0,
             "«لا أقسم بهذا البلد، وأنت حلّ بهذا البلد».",
             "القرآن — سورة البلد، 90:1-2"))

    add("quran_091", "quran", "hard", "quran", Q, "90:12-16", False,
        fr=L("Quelle « voie ardue » la sourate Al-Balad décrit-elle ?",
             ["Affranchir un esclave, nourrir l'orphelin et le pauvre en un jour de disette", "Traverser le désert", "Gravir une montagne", "Franchir la mer"], 0,
             "« Et qui te dira ce qu'est la voie ardue ? C'est affranchir une nuque, ou nourrir en un jour de famine un orphelin proche parent ou un pauvre dans le dénuement. »",
             "Coran — Sourate Al-Balad, 90:12-16"),
        en=L("What is the \"steep path\" that Surah Al-Balad describes?",
             ["Freeing a slave, feeding an orphan or a needy person on a day of hunger", "Crossing the desert", "Climbing a mountain", "Crossing the sea"], 0,
             "\"And what can make you know what is the steep path? It is freeing a slave, or feeding on a day of severe hunger an orphan of near relationship, or a needy person in misery.\"",
             "Quran — Surah Al-Balad, 90:12-16"),
        ar=L("ما «العقبة» التي وصفتها سورة البلد؟",
             ["فكّ رقبة أو إطعام في يوم ذي مسغبة يتيمًا أو مسكينًا", "قطع الصحراء", "صعود جبل", "عبور البحر"], 0,
             "«وما أدراك ما العقبة، فكّ رقبة، أو إطعام في يوم ذي مسغبة، يتيمًا ذا مقربة، أو مسكينًا ذا متربة».",
             "القرآن — سورة البلد، 90:12-16"))

    add("quran_092", "quran", "medium", "quran", Q, "92:1-4", False,
        fr=L("Par quoi Allah jure-t-Il au début de la sourate Al-Layl ?",
             ["Par la nuit quand elle enveloppe et le jour quand il éclaire", "Par la mer et la montagne", "Par le figuier et l'olivier", "Par la plume"], 0,
             "« Par la nuit quand elle enveloppe ! Par le jour quand il éclaire ! … Vos efforts sont divergents. »",
             "Coran — Sourate Al-Layl, 92:1-4"),
        en=L("By what does Allah swear at the start of Surah Al-Layl?",
             ["By the night when it covers and the day when it appears", "By the sea and the mountain", "By the fig and the olive", "By the pen"], 0,
             "\"By the night when it covers, and by the day when it appears… indeed, your efforts are diverse.\"",
             "Quran — Surah Al-Layl, 92:1-4"),
        ar=L("بماذا أقسم الله في مطلع سورة الليل؟",
             ["بالليل إذا يغشى والنهار إذا تجلّى", "بالبحر والجبل", "بالتين والزيتون", "بالقلم"], 0,
             "«والليل إذا يغشى، والنهار إذا تجلّى… إن سعيكم لشتّى».",
             "القرآن — سورة الليل، 92:1-4"))

    add("quran_093", "quran", "hard", "quran", Q, "87:1", False,
        fr=L("Par quel ordre s'ouvre la sourate Al-Aʿlâ ?",
             ["« Glorifie le nom de ton Seigneur, le Très-Haut »", "« Lis »", "« Lève-toi »", "« Écoute »"], 0,
             "« Glorifie le nom de ton Seigneur, le Très-Haut. »",
             "Coran — Sourate Al-Aʿlâ, 87:1"),
        en=L("With what command does Surah Al-A'la open?",
             ["\"Exalt the name of your Lord, the Most High\"", "\"Read\"", "\"Arise\"", "\"Listen\""], 0,
             "\"Exalt the name of your Lord, the Most High.\"",
             "Quran — Surah Al-A'la, 87:1"),
        ar=L("بأي أمر افتُتحت سورة الأعلى؟",
             ["«سبّح اسم ربك الأعلى»", "«اقرأ»", "«قم»", "«اسمع»"], 0,
             "«سبّح اسم ربك الأعلى».",
             "القرآن — سورة الأعلى، 87:1"))

    add("quran_094", "quran", "easy", "quran", Q, "88:1", False,
        fr=L("De quoi parle le début de la sourate Al-Ghâshiya ?",
             ["De l'événement qui recouvre tout : le Jour dernier", "D'un voyage", "D'un marché", "D'une bataille"], 0,
             "« T'est-il parvenu le récit de l'événement qui couvre tout ? »",
             "Coran — Sourate Al-Ghâshiya, 88:1"),
        en=L("What does the opening of Surah Al-Ghashiyah speak of?",
             ["The overwhelming event: the Last Day", "A journey", "A market", "A battle"], 0,
             "\"Has there reached you the report of the Overwhelming Event?\"",
             "Quran — Surah Al-Ghashiyah, 88:1"),
        ar=L("عمّ يتحدث مطلع سورة الغاشية؟",
             ["عن الغاشية، وهي يوم القيامة", "عن رحلة", "عن سوق", "عن معركة"], 0,
             "«هل أتاك حديث الغاشية».",
             "القرآن — سورة الغاشية، 88:1"))

    add("quran_095", "quran", "medium", "quran", Q, "88:17", False,
        fr=L("Sur quelle créature la sourate Al-Ghâshiya invite-t-elle à méditer ?",
             ["Le chameau, et comment il a été créé", "Le lion", "L'aigle", "Le poisson"], 0,
             "« Ne considèrent-ils donc pas les chameaux, comment ils ont été créés ? »",
             "Coran — Sourate Al-Ghâshiya, 88:17"),
        en=L("Which creature does Surah Al-Ghashiyah invite reflection upon?",
             ["The camel, and how it was created", "The lion", "The eagle", "The fish"], 0,
             "\"Then do they not look at the camels, how they are created?\"",
             "Quran — Surah Al-Ghashiyah, 88:17"),
        ar=L("في أي مخلوق دعت سورة الغاشية إلى النظر؟",
             ["الإبل، كيف خُلقت", "الأسد", "النسر", "السمك"], 0,
             "«أفلا ينظرون إلى الإبل كيف خُلقت».",
             "القرآن — سورة الغاشية، 88:17"))

    add("quran_096", "quran", "hard", "quran", Q, "85:1", False,
        fr=L("Par quoi Allah jure-t-Il au début de la sourate Al-Burûj ?",
             ["Par le ciel aux constellations", "Par la terre", "Par les fleuves", "Par les nuages"], 0,
             "« Par le ciel aux constellations ! Et par le jour promis ! »",
             "Coran — Sourate Al-Burûj, 85:1"),
        en=L("By what does Allah swear at the start of Surah Al-Buruj?",
             ["By the sky containing great stars", "By the earth", "By the rivers", "By the clouds"], 0,
             "\"By the sky containing great stars, and by the promised Day.\"",
             "Quran — Surah Al-Buruj, 85:1"),
        ar=L("بماذا أقسم الله في مطلع سورة البروج؟",
             ["بالسماء ذات البروج", "بالأرض", "بالأنهار", "بالسحاب"], 0,
             "«والسماء ذات البروج، واليوم الموعود».",
             "القرآن — سورة البروج، 85:1"))

    add("quran_097", "quran", "medium", "quran", Q, "86:1-3", False,
        fr=L("Que désigne « At-Târiq », titre de la sourate 86 ?",
             ["L'astre nocturne perçant", "La porte", "Le chemin", "Le tonnerre"], 0,
             "« Par le ciel et par At-Târiq ! Et qui te dira ce qu'est At-Târiq ? L'astre vivement brillant. »",
             "Coran — Sourate At-Târiq, 86:1-3"),
        en=L("What does \"At-Tariq\", the title of surah 86, refer to?",
             ["The piercing night star", "The door", "The road", "The thunder"], 0,
             "\"By the sky and the night comer — and what can make you know what the night comer is? It is the piercing star.\"",
             "Quran — Surah At-Tariq, 86:1-3"),
        ar=L("إلامَ يشير «الطارق» عنوان السورة 86؟",
             ["النجم الثاقب", "الباب", "الطريق", "الرعد"], 0,
             "«والسماء والطارق، وما أدراك ما الطارق، النجم الثاقب».",
             "القرآن — سورة الطارق، 86:1-3"))

    add("quran_098", "quran", "easy", "quran", Q, "99:1", False,
        fr=L("Quel événement décrit l'ouverture de la sourate Az-Zalzala ?",
             ["La terre secouée de son séisme", "Une pluie torrentielle", "Un vent violent", "Une éclipse"], 0,
             "« Quand la terre tremblera d'un violent tremblement, et que la terre rejettera ses fardeaux. »",
             "Coran — Sourate Az-Zalzala, 99:1"),
        en=L("What event does the opening of Surah Az-Zalzalah describe?",
             ["The earth shaken with its quake", "A torrential rain", "A violent wind", "An eclipse"], 0,
             "\"When the earth is shaken with its final earthquake, and the earth discharges its burdens.\"",
             "Quran — Surah Az-Zalzalah, 99:1"),
        ar=L("أي حدث يصفه مطلع سورة الزلزلة؟",
             ["زلزلة الأرض", "مطر غزير", "ريح شديدة", "كسوف"], 0,
             "«إذا زُلزلت الأرض زلزالها، وأخرجت الأرض أثقالها».",
             "القرآن — سورة الزلزلة، 99:1"))

    add("quran_099", "quran", "hard", "quran", Q, "99:7-8", False,
        fr=L("Quelle mesure la fin de la sourate Az-Zalzala fixe-t-elle pour les œuvres ?",
             ["Le poids d'un atome, en bien comme en mal", "Un boisseau", "Une année", "Une main"], 0,
             "« Quiconque fait un bien du poids d'un atome le verra, et quiconque fait un mal du poids d'un atome le verra. »",
             "Coran — Sourate Az-Zalzala, 99:7-8"),
        en=L("What measure does the end of Surah Az-Zalzalah set for deeds?",
             ["The weight of an atom, of good and of evil alike", "A bushel", "A year", "A hand"], 0,
             "\"So whoever does an atom's weight of good will see it, and whoever does an atom's weight of evil will see it.\"",
             "Quran — Surah Az-Zalzalah, 99:7-8"),
        ar=L("أي ميزان ختمت به سورة الزلزلة في شأن الأعمال؟",
             ["مثقال ذرة خيرًا وشرًّا", "مكيال", "سنة", "يد"], 0,
             "«فمن يعمل مثقال ذرة خيرًا يره، ومن يعمل مثقال ذرة شرًّا يره».",
             "القرآن — سورة الزلزلة، 99:7-8"))

    add("quran_100", "quran", "medium", "quran", Q, "100:1-5", False,
        fr=L("Que désignent « Al-ʿÂdiyât », titre de la sourate 100 ?",
             ["Les coursiers qui galopent en haletant", "Les vents", "Les vagues", "Les nuées"], 0,
             "« Par les coursiers haletants ! Qui font jaillir des étincelles ! Qui attaquent au matin ! »",
             "Coran — Sourate Al-ʿÂdiyât, 100:1-5"),
        en=L("What does \"Al-'Adiyat\", the title of surah 100, refer to?",
             ["The racers that gallop, panting", "The winds", "The waves", "The clouds"], 0,
             "\"By the racers, panting; and the producers of sparks when striking; and the chargers at dawn.\"",
             "Quran — Surah Al-'Adiyat, 100:1-5"),
        ar=L("إلامَ تشير «العاديات» عنوان السورة 100؟",
             ["الخيل تعدو ضبحًا", "الرياح", "الأمواج", "السحاب"], 0,
             "«والعاديات ضبحًا، فالموريات قدحًا، فالمغيرات صبحًا».",
             "القرآن — سورة العاديات، 100:1-5"))

    # -- Names, structure and sciences of the Book ----------------------
    add("quran_101", "quran", "easy", "quran", Q, "2:2", False,
        fr=L("Comment la sourate Al-Baqara décrit-elle le Livre dans son deuxième verset ?",
             ["Un livre sans nul doute, guide pour les pieux", "Un livre d'histoire", "Un recueil de poèmes", "Un livre de lois seulement"], 0,
             "« Voilà le Livre au sujet duquel il n'y a aucun doute : c'est un guide pour les pieux. »",
             "Coran — Sourate Al-Baqara, 2:2"),
        en=L("How does Surah Al-Baqarah describe the Book in its second verse?",
             ["A book about which there is no doubt, a guidance for the God-fearing", "A book of history", "A collection of poems", "A book of law only"], 0,
             "\"This is the Book about which there is no doubt, a guidance for those conscious of Allah.\"",
             "Quran — Surah Al-Baqarah, 2:2"),
        ar=L("كيف وصفت سورة البقرة الكتاب في آيتها الثانية؟",
             ["كتاب لا ريب فيه هدى للمتقين", "كتاب تاريخ", "ديوان شعر", "كتاب أحكام فقط"], 0,
             "«ذلك الكتاب لا ريب فيه هدى للمتقين».",
             "القرآن — سورة البقرة، 2:2"))

    add("quran_102", "quran", "hard", "quran", Q, "15:9", False,
        fr=L("Quel verset promet la préservation du Rappel révélé ?",
             ["« C'est Nous qui avons fait descendre le Rappel, et c'est Nous qui en sommes gardien »", "« Nul ne le lira »", "« Il sera oublié »", "« Il sera caché »"], 0,
             "« En vérité, c'est Nous qui avons fait descendre le Rappel, et c'est Nous qui en sommes gardien. »",
             "Coran — Sourate Al-Hijr, 15:9"),
        en=L("Which verse promises the preservation of the revealed Reminder?",
             ["\"Indeed, it is We who sent down the Reminder, and indeed, We will be its guardian\"", "\"None shall read it\"", "\"It will be forgotten\"", "\"It will be hidden\""], 0,
             "\"Indeed, it is We who sent down the Quran and indeed, We will be its guardian.\"",
             "Quran — Surah Al-Hijr, 15:9"),
        ar=L("أي آية وعدت بحفظ الذكر المنزَّل؟",
             ["«إنا نحن نزّلنا الذكر وإنا له لحافظون»", "«لن يقرأه أحد»", "«سيُنسى»", "«سيُخفى»"], 0,
             "«إنا نحن نزّلنا الذكر وإنا له لحافظون».",
             "القرآن — سورة الحجر، 15:9"))

    add("quran_103", "quran", "medium", "quran", Q, "4:82", False,
        fr=L("Quel argument le Coran avance-t-il sur son absence de contradictions ?",
             ["S'il venait d'un autre qu'Allah, on y trouverait beaucoup de contradictions", "Qu'il est court", "Qu'il est en arabe", "Qu'il est ancien"], 0,
             "« Ne méditent-ils pas sur le Coran ? S'il provenait d'un autre qu'Allah, ils y trouveraient certes maintes contradictions. »",
             "Coran — Sourate An-Nisâ, 4:82"),
        en=L("What argument does the Quran make about its freedom from contradiction?",
             ["Had it come from other than Allah, they would find much contradiction in it", "That it is short", "That it is in Arabic", "That it is ancient"], 0,
             "\"Then do they not reflect upon the Quran? If it had been from other than Allah, they would have found within it much contradiction.\"",
             "Quran — Surah An-Nisa, 4:82"),
        ar=L("ما الحجة التي ساقها القرآن على خلوّه من الاختلاف؟",
             ["لو كان من عند غير الله لوجدوا فيه اختلافًا كثيرًا", "أنه قصير", "أنه عربي", "أنه قديم"], 0,
             "«أفلا يتدبرون القرآن، ولو كان من عند غير الله لوجدوا فيه اختلافًا كثيرًا».",
             "القرآن — سورة النساء، 4:82"))

    add("quran_104", "quran", "hard", "quran", Q, "59:21", False,
        fr=L("À quoi le Coran compare-t-il l'effet qu'il aurait eu sur une montagne ?",
             ["Elle se serait humiliée et fendue par crainte d'Allah", "Elle aurait brillé", "Elle se serait déplacée", "Elle serait devenue verte"], 0,
             "« Si Nous avions fait descendre ce Coran sur une montagne, tu l'aurais vue s'humilier et se fendre par crainte d'Allah. »",
             "Coran — Sourate Al-Hashr, 59:21"),
        en=L("What does the Quran say would have happened to a mountain, had it been revealed upon it?",
             ["It would have been humbled and split apart from fear of Allah", "It would have shone", "It would have moved", "It would have turned green"], 0,
             "\"If We had sent down this Quran upon a mountain, you would have seen it humbled and coming apart from fear of Allah.\"",
             "Quran — Surah Al-Hashr, 59:21"),
        ar=L("بماذا وصف القرآن أثره لو أُنزل على جبل؟",
             ["لرأيته خاشعًا متصدّعًا من خشية الله", "لأضاء", "لتحرّك", "لاخضرّ"], 0,
             "«لو أنزلنا هذا القرآن على جبل لرأيته خاشعًا متصدّعًا من خشية الله».",
             "القرآن — سورة الحشر، 59:21"))

    add("quran_105", "quran", "easy", "quran", Q, "73:4", False,
        fr=L("Comment le Coran ordonne-t-il de le réciter, dans la sourate Al-Muzzammil ?",
             ["Posément et distinctement (tartîl)", "Le plus vite possible", "En silence", "En chantant"], 0,
             "« Et récite le Coran, lentement et clairement. »",
             "Coran — Sourate Al-Muzzammil, 73:4"),
        en=L("How does the Quran command that it be recited, in Surah Al-Muzzammil?",
             ["Measuredly and distinctly (tartil)", "As fast as possible", "Silently", "In song"], 0,
             "\"And recite the Quran with measured recitation.\"",
             "Quran — Surah Al-Muzzammil, 73:4"),
        ar=L("كيف أمر القرآن بتلاوته في سورة المزّمل؟",
             ["ترتيلًا", "بأسرع ما يمكن", "سرًّا", "غناءً"], 0,
             "«ورتّل القرآن ترتيلًا».",
             "القرآن — سورة المزّمل، 73:4"))

    add("quran_106", "quran", "medium", "quran", Q, "7:204", False,
        fr=L("Que faut-il faire lorsque le Coran est récité, selon la sourate Al-Aʿrâf ?",
             ["Écouter et se taire", "Répondre à voix haute", "Sortir", "Écrire"], 0,
             "« Et quand on récite le Coran, prêtez-lui l'oreille et gardez le silence, afin que vous obteniez la miséricorde. »",
             "Coran — Sourate Al-Aʿrâf, 7:204"),
        en=L("What should be done when the Quran is recited, according to Surah Al-A'raf?",
             ["Listen and be silent", "Answer aloud", "Leave", "Write"], 0,
             "\"So when the Quran is recited, listen to it and pay attention, that you may receive mercy.\"",
             "Quran — Surah Al-A'raf, 7:204"),
        ar=L("ماذا يُفعل إذا قُرئ القرآن بحسب سورة الأعراف؟",
             ["الاستماع والإنصات", "الرد بصوت عالٍ", "الخروج", "الكتابة"], 0,
             "«وإذا قُرئ القرآن فاستمعوا له وأنصتوا لعلكم تُرحمون».",
             "القرآن — سورة الأعراف، 7:204"))

    add("quran_107", "quran", "hard", "quran", Q, "16:98", False,
        fr=L("Que le Coran ordonne-t-il de dire avant d'entamer sa lecture ?",
             ["Chercher refuge auprès d'Allah contre Satan le banni", "Compter les versets", "Faire les ablutions à voix haute", "Réciter le dernier verset"], 0,
             "« Lorsque tu lis le Coran, cherche refuge auprès d'Allah contre Satan le banni. »",
             "Coran — Sourate An-Nahl, 16:98"),
        en=L("What does the Quran command be said before beginning to read it?",
             ["Seek refuge in Allah from Satan, the expelled", "Count the verses", "Say the ablution aloud", "Recite the last verse"], 0,
             "\"So when you recite the Quran, seek refuge in Allah from Satan, the expelled.\"",
             "Quran — Surah An-Nahl, 16:98"),
        ar=L("بماذا أمر القرآن قبل الشروع في قراءته؟",
             ["بالاستعاذة بالله من الشيطان الرجيم", "بعدّ الآيات", "بالجهر بالوضوء", "بتلاوة آخر آية"], 0,
             "«فإذا قرأت القرآن فاستعذ بالله من الشيطان الرجيم».",
             "القرآن — سورة النحل، 16:98"))

    add("quran_108", "quran", "medium", "quran", Q, "38:29", False,
        fr=L("Pourquoi le Livre a-t-il été fait descendre, selon la sourate Sâd ?",
             ["Pour qu'on médite ses versets et que les doués d'intelligence se rappellent", "Pour qu'on le copie", "Pour qu'on le compte", "Pour qu'on le cache"], 0,
             "« C'est un Livre béni que Nous avons fait descendre vers toi, afin qu'ils méditent sur ses versets. »",
             "Coran — Sourate Sâd, 38:29"),
        en=L("Why was the Book sent down, according to Surah Sad?",
             ["So that its verses would be pondered and the people of understanding reminded", "So that it be copied", "So that it be counted", "So that it be hidden"], 0,
             "\"This is a blessed Book which We have revealed to you, that they might reflect upon its verses.\"",
             "Quran — Surah Sad, 38:29"),
        ar=L("لماذا أُنزل الكتاب بحسب سورة ص؟",
             ["ليتدبّروا آياته وليتذكّر أولو الألباب", "لينسخوه", "ليعدّوه", "ليخفوه"], 0,
             "«كتاب أنزلناه إليك مبارك ليدّبّروا آياته وليتذكّر أولو الألباب».",
             "القرآن — سورة ص، 38:29"))

    add("quran_109", "quran", "hard", "quran", Q, "17:88", False,
        fr=L("Quel défi la sourate Al-Isrâ lance-t-elle aux hommes et aux djinns réunis ?",
             ["Produire un semblable de ce Coran, même en s'entraidant", "Traverser les cieux", "Compter les étoiles", "Bâtir une cité"], 0,
             "« Si les hommes et les djinns s'unissaient pour produire quelque chose de semblable à ce Coran, ils ne pourraient rien produire de tel. »",
             "Coran — Sourate Al-Isrâ, 17:88"),
        en=L("What challenge does Surah Al-Isra issue to mankind and jinn together?",
             ["To produce the like of this Quran, even helping one another", "To cross the heavens", "To count the stars", "To build a city"], 0,
             "\"If mankind and the jinn gathered to produce the like of this Quran, they could not produce the like of it, even if they were helpers of one another.\"",
             "Quran — Surah Al-Isra, 17:88"),
        ar=L("أي تحدٍّ وجّهته سورة الإسراء للإنس والجن معًا؟",
             ["أن يأتوا بمثل هذا القرآن ولو تعاونوا", "أن يعبروا السماء", "أن يعدّوا النجوم", "أن يبنوا مدينة"], 0,
             "«قل لئن اجتمعت الإنس والجن على أن يأتوا بمثل هذا القرآن لا يأتون بمثله ولو كان بعضهم لبعض ظهيرًا».",
             "القرآن — سورة الإسراء، 17:88"))

    add("quran_110", "quran", "easy", "quran", Q, "20:114", False,
        fr=L("Quelle invocation le Coran enseigne-t-il au sujet du savoir ?",
             ["« Seigneur, accrois-moi en savoir »", "« Seigneur, donne-moi la richesse »", "« Seigneur, allonge ma vie »", "« Seigneur, ouvre-moi les routes »"], 0,
             "« Et dis : Seigneur, accrois-moi en savoir. »",
             "Coran — Sourate Tâ-Hâ, 20:114"),
        en=L("Which supplication does the Quran teach concerning knowledge?",
             ["\"My Lord, increase me in knowledge\"", "\"My Lord, give me wealth\"", "\"My Lord, lengthen my life\"", "\"My Lord, open the roads to me\""], 0,
             "\"And say: My Lord, increase me in knowledge.\"",
             "Quran — Surah Ta-Ha, 20:114"),
        ar=L("أي دعاء علّمه القرآن في شأن العلم؟",
             ["«ربّ زدني علمًا»", "«ربّ آتني مالًا»", "«ربّ أطل عمري»", "«ربّ افتح لي الطرق»"], 0,
             "«وقل ربّ زدني علمًا».",
             "القرآن — سورة طه، 20:114"))

    add("quran_111", "quran", "hard", "quran", Q, "39:23", False,
        fr=L("Comment la sourate Az-Zumar décrit-elle le plus beau des récits révélés ?",
             ["Un Livre dont les parties se ressemblent et se répètent, qui fait frissonner les peaux", "Un livre bref", "Un livre de lois", "Un livre en vers"], 0,
             "« Allah a fait descendre le plus beau des récits : un Livre dont les parties se ressemblent et se répètent. Les peaux de ceux qui redoutent leur Seigneur en frissonnent. »",
             "Coran — Sourate Az-Zumar, 39:23"),
        en=L("How does Surah Az-Zumar describe the best of narrations revealed?",
             ["A Book of similar, repeated parts, at which the skins shiver", "A short book", "A book of laws", "A book in verse"], 0,
             "\"Allah has sent down the best statement: a consistent Book wherein is reiteration. The skins shiver therefrom of those who fear their Lord.\"",
             "Quran — Surah Az-Zumar, 39:23"),
        ar=L("كيف وصفت سورة الزمر أحسن الحديث المنزَّل؟",
             ["كتابًا متشابهًا مثاني تقشعرّ منه الجلود", "كتابًا قصيرًا", "كتاب أحكام", "كتابًا منظومًا"], 0,
             "«الله نزّل أحسن الحديث كتابًا متشابهًا مثاني تقشعرّ منه جلود الذين يخشون ربهم».",
             "القرآن — سورة الزمر، 39:23"))

    add("quran_112", "quran", "medium", "quran", Q, "14:24-25", False,
        fr=L("À quoi le Coran compare-t-il la bonne parole, dans la sourate Ibrâhîm ?",
             ["À un bel arbre, racine ferme et branches dans le ciel", "À une rivière", "À une montagne", "À une étoile"], 0,
             "« Une bonne parole est comme un bel arbre : sa racine est ferme et ses branches s'élèvent dans le ciel ; il donne son fruit en toute saison. »",
             "Coran — Sourate Ibrâhîm, 14:24-25"),
        en=L("To what does the Quran compare a good word, in Surah Ibrahim?",
             ["To a good tree, firm of root and branches in the sky", "To a river", "To a mountain", "To a star"], 0,
             "\"A good word is like a good tree, whose root is firmly fixed and its branches in the sky; it gives its fruit every season.\"",
             "Quran — Surah Ibrahim, 14:24-25"),
        ar=L("بماذا شبّه القرآن الكلمة الطيبة في سورة إبراهيم؟",
             ["بشجرة طيبة أصلها ثابت وفرعها في السماء", "بنهر", "بجبل", "بنجم"], 0,
             "«كلمة طيبة كشجرة طيبة أصلها ثابت وفرعها في السماء، تؤتي أكلها كل حين».",
             "القرآن — سورة إبراهيم، 14:24-25"))

    add("quran_113", "quran", "hard", "quran", Q, "13:17", False,
        fr=L("À quoi la sourate Ar-Raʿd compare-t-elle le vrai et le faux ?",
             ["À l'écume que le torrent emporte, et à ce qui profite aux hommes et demeure", "À deux montagnes", "À deux villes", "À deux caravanes"], 0,
             "« Quant à l'écume, elle s'en va, au rebut ; mais ce qui est utile aux hommes demeure sur la terre. »",
             "Coran — Sourate Ar-Raʿd, 13:17"),
        en=L("To what does Surah Ar-Ra'd compare truth and falsehood?",
             ["To the froth the torrent carries off, and what benefits people and remains", "To two mountains", "To two cities", "To two caravans"], 0,
             "\"As for the foam, it vanishes as scum; but what benefits the people remains on the earth.\"",
             "Quran — Surah Ar-Ra'd, 13:17"),
        ar=L("بماذا ضرب الرعدُ المثل للحق والباطل؟",
             ["بالزبد الذي يذهب جفاءً وما ينفع الناس فيمكث", "بجبلين", "بمدينتين", "بقافلتين"], 0,
             "«فأما الزبد فيذهب جفاءً، وأما ما ينفع الناس فيمكث في الأرض».",
             "القرآن — سورة الرعد، 13:17"))

    add("quran_114", "quran", "easy", "quran", Q, "13:28", False,
        fr=L("Par quoi les cœurs se tranquillisent-ils, selon la sourate Ar-Raʿd ?",
             ["Par le rappel d'Allah", "Par la richesse", "Par le voyage", "Par le sommeil"], 0,
             "« N'est-ce point par le rappel d'Allah que se tranquillisent les cœurs ? »",
             "Coran — Sourate Ar-Raʿd, 13:28"),
        en=L("By what do hearts find rest, according to Surah Ar-Ra'd?",
             ["By the remembrance of Allah", "By wealth", "By travel", "By sleep"], 0,
             "\"Unquestionably, by the remembrance of Allah hearts are assured.\"",
             "Quran — Surah Ar-Ra'd, 13:28"),
        ar=L("بماذا تطمئن القلوب بحسب سورة الرعد؟",
             ["بذكر الله", "بالمال", "بالسفر", "بالنوم"], 0,
             "«ألا بذكر الله تطمئن القلوب».",
             "القرآن — سورة الرعد، 13:28"))

    add("quran_115", "quran", "hard", "quran", Q, "18:109", False,
        fr=L("Que dit la sourate Al-Kahf de l'encre nécessaire pour écrire les paroles d'Allah ?",
             ["La mer s'épuiserait avant les paroles de son Seigneur", "Il faudrait un encrier", "Une nuit suffirait", "Sept plumes suffiraient"], 0,
             "« Si la mer était une encre pour écrire les paroles de mon Seigneur, elle serait tarie avant que ne soient épuisées les paroles de mon Seigneur. »",
             "Coran — Sourate Al-Kahf, 18:109"),
        en=L("What does Surah Al-Kahf say of the ink needed to write the words of Allah?",
             ["The sea would run dry before the words of his Lord were exhausted", "One inkwell would do", "One night would do", "Seven pens would do"], 0,
             "\"If the sea were ink for the words of my Lord, the sea would be exhausted before the words of my Lord were exhausted.\"",
             "Quran — Surah Al-Kahf, 18:109"),
        ar=L("ماذا قالت سورة الكهف عن المداد اللازم لكلمات الله؟",
             ["لنفد البحر قبل أن تنفد كلمات ربي", "يكفي محبرة", "تكفي ليلة", "تكفي سبعة أقلام"], 0,
             "«قل لو كان البحر مدادًا لكلمات ربي لنفد البحر قبل أن تنفد كلمات ربي».",
             "القرآن — سورة الكهف، 18:109"))

    add("quran_116", "quran", "medium", "quran", Q, "31:27", False,
        fr=L("Combien de mers, selon la sourate Luqmân, ne suffiraient pas à épuiser les paroles d'Allah ?",
             ["Sept mers pour renfort, et elles ne suffiraient pas", "Une seule", "Trois", "Douze"], 0,
             "« Quand bien même tous les arbres de la terre seraient des calames et la mer serait de l'encre, gonflée par sept autres mers, les paroles d'Allah ne s'épuiseraient pas. »",
             "Coran — Sourate Luqmân, 31:27"),
        en=L("How many seas, according to Surah Luqman, would still not exhaust the words of Allah?",
             ["Seven seas in reinforcement, and still not enough", "One", "Three", "Twelve"], 0,
             "\"And if whatever trees upon the earth were pens and the sea was ink, replenished thereafter by seven more seas, the words of Allah would not be exhausted.\"",
             "Quran — Surah Luqman, 31:27"),
        ar=L("كم بحرًا، بحسب سورة لقمان، لا تنفد معها كلمات الله؟",
             ["سبعة أبحر مددًا ولا تنفد", "واحد", "ثلاثة", "اثنا عشر"], 0,
             "«ولو أنما في الأرض من شجرة أقلام والبحر يمدّه من بعده سبعة أبحر ما نفدت كلمات الله».",
             "القرآن — سورة لقمان، 31:27"))

    add("quran_117", "quran", "hard", "quran", Q, "41:44", False,
        fr=L("Que serait-il objecté si le Coran avait été révélé en langue étrangère à un messager arabe ?",
             ["« Pourquoi ses versets ne sont-ils pas exposés clairement ? »", "« Il est trop court »", "« Il est trop long »", "« Il n'a pas de titre »"], 0,
             "« Si Nous en avions fait un Coran en une langue étrangère, ils auraient dit : “Pourquoi ses versets n'ont-ils pas été exposés clairement ?” »",
             "Coran — Sourate Fussilat, 41:44"),
        en=L("What objection does the Quran say would have been raised, had it been revealed in a foreign tongue to an Arab messenger?",
             ["\"Why are its verses not explained in detail?\"", "\"It is too short\"", "\"It is too long\"", "\"It has no title\""], 0,
             "\"And if We had made it a foreign Quran, they would have said: 'Why are its verses not explained in detail?'\"",
             "Quran — Surah Fussilat, 41:44"),
        ar=L("أي اعتراض ذكره القرآن لو نزل أعجميًّا على رسول عربي؟",
             ["«لولا فُصّلت آياته»", "«إنه قصير»", "«إنه طويل»", "«لا عنوان له»"], 0,
             "«ولو جعلناه قرآنًا أعجميًّا لقالوا لولا فُصّلت آياته».",
             "القرآن — سورة فصلت، 41:44"))

    add("quran_118", "quran", "easy", "quran", Q, "17:9", False,
        fr=L("Vers quoi le Coran guide-t-il, selon la sourate Al-Isrâ ?",
             ["Vers ce qu'il y a de plus droit", "Vers la richesse", "Vers le pouvoir", "Vers le repos"], 0,
             "« Certes, ce Coran guide vers ce qu'il y a de plus droit, et il annonce aux croyants qui font de bonnes œuvres une grande récompense. »",
             "Coran — Sourate Al-Isrâ, 17:9"),
        en=L("To what does the Quran guide, according to Surah Al-Isra?",
             ["To that which is most upright", "To wealth", "To power", "To rest"], 0,
             "\"Indeed, this Quran guides to that which is most suitable, and gives good tidings to the believers who do righteous deeds of a great reward.\"",
             "Quran — Surah Al-Isra, 17:9"),
        ar=L("إلامَ يهدي القرآن بحسب سورة الإسراء؟",
             ["للتي هي أقوم", "إلى المال", "إلى السلطان", "إلى الراحة"], 0,
             "«إن هذا القرآن يهدي للتي هي أقوم ويبشّر المؤمنين الذين يعملون الصالحات أن لهم أجرًا كبيرًا».",
             "القرآن — سورة الإسراء، 17:9"))

    add("quran_119", "quran", "medium", "quran", Q, "10:57", False,
        fr=L("Comment la sourate Yûnus décrit-elle ce qui est descendu du Seigneur ?",
             ["Une exhortation, une guérison pour ce qui est dans les poitrines, un guide et une miséricorde", "Un décompte", "Un décret royal", "Un traité"], 0,
             "« Ô hommes ! Une exhortation vous est venue de votre Seigneur, une guérison de ce qui est dans les poitrines, un guide et une miséricorde pour les croyants. »",
             "Coran — Sourate Yûnus, 10:57"),
        en=L("How does Surah Yunus describe what has come down from the Lord?",
             ["An admonition, a healing for what is in the breasts, guidance and mercy", "A reckoning", "A royal decree", "A treaty"], 0,
             "\"O mankind, there has come to you instruction from your Lord and healing for what is in the breasts, and guidance and mercy for the believers.\"",
             "Quran — Surah Yunus, 10:57"),
        ar=L("كيف وصفت سورة يونس ما نزل من الرب؟",
             ["موعظة وشفاء لما في الصدور وهدى ورحمة", "حسابًا", "مرسومًا ملكيًّا", "معاهدة"], 0,
             "«يا أيها الناس قد جاءتكم موعظة من ربكم وشفاء لما في الصدور وهدى ورحمة للمؤمنين».",
             "القرآن — سورة يونس، 10:57"))

    add("quran_120", "quran", "hard", "quran", Q, "2:185", False,
        fr=L("Comment la sourate Al-Baqara qualifie-t-elle le Coran quant à son rôle de critère ?",
             ["Un guide pour les gens et des preuves claires, et le discernement", "Un livre de comptes", "Un recueil de récits", "Un code pénal"], 0,
             "« Le mois de Ramadan, au cours duquel le Coran a été descendu comme guide pour les gens, et preuves claires de la guidée et du discernement. »",
             "Coran — Sourate Al-Baqara, 2:185"),
        en=L("How does Surah Al-Baqarah describe the Quran's role as a criterion?",
             ["Guidance for the people, clear proofs, and the criterion", "A book of accounts", "A collection of stories", "A penal code"], 0,
             "\"The month of Ramadan in which was revealed the Quran, a guidance for the people and clear proofs of guidance and criterion.\"",
             "Quran — Surah Al-Baqarah, 2:185"),
        ar=L("كيف وصفت سورة البقرة القرآن من جهة الفرقان؟",
             ["هدى للناس وبيّنات من الهدى والفرقان", "كتاب حساب", "مجموعة قصص", "قانون عقوبات"], 0,
             "«شهر رمضان الذي أُنزل فيه القرآن هدى للناس وبيّنات من الهدى والفرقان».",
             "القرآن — سورة البقرة، 2:185"))

    add("quran_121", "quran", "easy", "quran", Q, "50:1", False,
        fr=L("Par quoi Allah jure-t-Il au début de la sourate Qâf ?",
             ["Par le Coran glorieux", "Par la montagne", "Par le vent", "Par l'aube"], 0,
             "« Qâf. Par le Coran glorieux ! »",
             "Coran — Sourate Qâf, 50:1"),
        en=L("By what does Allah swear at the start of Surah Qaf?",
             ["By the glorious Quran", "By the mountain", "By the wind", "By the dawn"], 0,
             "\"Qaf. By the honoured Quran.\"",
             "Quran — Surah Qaf, 50:1"),
        ar=L("بماذا أقسم الله في مطلع سورة ق؟",
             ["بالقرآن المجيد", "بالجبل", "بالريح", "بالفجر"], 0,
             "«ق، والقرآن المجيد».",
             "القرآن — سورة ق، 50:1"))

    add("quran_122", "quran", "medium", "quran", Q, "77:1", False,
        fr=L("Que désignent « Al-Mursalât », titre de la sourate 77 ?",
             ["Celles qui sont envoyées, l'une après l'autre", "Les caravanes", "Les étoiles", "Les rivières"], 0,
             "« Par ceux qui sont envoyés successivement ! »",
             "Coran — Sourate Al-Mursalât, 77:1"),
        en=L("What does \"Al-Mursalat\", the title of surah 77, refer to?",
             ["Those sent forth, one after another", "The caravans", "The stars", "The rivers"], 0,
             "\"By those sent forth in gusts, one after another.\"",
             "Quran — Surah Al-Mursalat, 77:1"),
        ar=L("إلامَ تشير «المرسلات» عنوان السورة 77؟",
             ["المرسلات عرفًا", "القوافل", "النجوم", "الأنهار"], 0,
             "«والمرسلات عرفًا».",
             "القرآن — سورة المرسلات، 77:1"))

    add("quran_123", "quran", "hard", "quran", Q, "83:18-21", False,
        fr=L("Quel registre la sourate Al-Mutaffifîn nomme-t-elle pour les vertueux ?",
             ["ʿIlliyyûn", "Sijjîn", "Al-Lawh", "Az-Zabûr"], 0,
             "« Le livre des bons sera dans ʿIlliyyûn… un livre marqué, dont témoignent les rapprochés. »",
             "Coran — Sourate Al-Mutaffifîn, 83:18-21"),
        en=L("Which register does Surah Al-Mutaffifin name for the righteous?",
             ["'Illiyyun", "Sijjin", "Al-Lawh", "Az-Zabur"], 0,
             "\"The record of the righteous is in 'Illiyyun… a register inscribed, which the near angels witness.\"",
             "Quran — Surah Al-Mutaffifin, 83:18-21"),
        ar=L("أي كتاب سمّته سورة المطففين للأبرار؟",
             ["عِلّيّون", "سِجّين", "اللوح", "الزبور"], 0,
             "«إن كتاب الأبرار لفي عليين… كتاب مرقوم يشهده المقرّبون».",
             "القرآن — سورة المطففين، 83:18-21"))

    add("quran_124", "quran", "hard", "quran", Q, "84:1-2", False,
        fr=L("Par quel événement s'ouvre la sourate Al-Inshiqâq ?",
             ["Le ciel qui se fend", "La mer qui déborde", "La terre qui verdit", "Le soleil qui se lève"], 0,
             "« Quand le ciel se déchirera et obéira à son Seigneur — et il le doit. »",
             "Coran — Sourate Al-Inshiqâq, 84:1-2"),
        en=L("With what event does Surah Al-Inshiqaq open?",
             ["The sky splitting asunder", "The sea overflowing", "The earth turning green", "The sun rising"], 0,
             "\"When the sky has split asunder and has listened to its Lord, as it must.\"",
             "Quran — Surah Al-Inshiqaq, 84:1-2"),
        ar=L("بأي حدث افتُتحت سورة الانشقاق؟",
             ["انشقاق السماء", "فيضان البحر", "اخضرار الأرض", "طلوع الشمس"], 0,
             "«إذا السماء انشقّت، وأذنت لربها وحُقّت».",
             "القرآن — سورة الانشقاق، 84:1-2"))

    add("quran_125", "quran", "medium", "quran", Q, "81:1", False,
        fr=L("Par quel signe s'ouvre la sourate At-Takwîr ?",
             ["Le soleil enroulé", "La lune fendue", "Le vent levé", "Le tonnerre"], 0,
             "« Quand le soleil sera obscurci, quand les étoiles deviendront ternes. »",
             "Coran — Sourate At-Takwîr, 81:1"),
        en=L("With which sign does Surah At-Takwir open?",
             ["The sun wrapped up", "The moon split", "The wind rising", "The thunder"], 0,
             "\"When the sun is wrapped up in darkness, and when the stars fall, losing their lustre.\"",
             "Quran — Surah At-Takwir, 81:1"),
        ar=L("بأي علامة افتُتحت سورة التكوير؟",
             ["تكوير الشمس", "انشقاق القمر", "هبوب الريح", "الرعد"], 0,
             "«إذا الشمس كُوّرت، وإذا النجوم انكدرت».",
             "القرآن — سورة التكوير، 81:1"))

    # -- Imagery, terminology, and the shape of the text ----------------
    add("quran_126", "quran", "easy", "quran", Q, "2:286", False,
        fr=L("Que dit le dernier verset de la sourate Al-Baqara sur la charge imposée à une âme ?",
             ["Allah n'impose à aucune âme une charge supérieure à sa capacité", "Chaque âme porte double", "Nul n'est éprouvé", "Les charges sont égales"], 0,
             "« Allah n'impose à aucune âme une charge supérieure à sa capacité. »",
             "Coran — Sourate Al-Baqara, 2:286"),
        en=L("What does the last verse of Surah Al-Baqarah say about the burden placed on a soul?",
             ["Allah does not burden a soul beyond its capacity", "Each soul carries double", "No one is tested", "All burdens are equal"], 0,
             "\"Allah does not charge a soul except with that within its capacity.\"",
             "Quran — Surah Al-Baqarah, 2:286"),
        ar=L("ماذا قالت خاتمة سورة البقرة في تكليف النفس؟",
             ["لا يكلّف الله نفسًا إلا وسعها", "كل نفس تحمل ضعفين", "لا يُبتلى أحد", "التكاليف سواء"], 0,
             "«لا يكلّف الله نفسًا إلا وسعها».",
             "القرآن — سورة البقرة، 2:286"))

    add("quran_127", "quran", "hard", "quran", Q, "2:261", False,
        fr=L("À quoi le Coran compare-t-il la dépense dans le chemin d'Allah ?",
             ["À un grain qui produit sept épis, chacun de cent grains", "À une pierre", "À un puits", "À une lampe"], 0,
             "« Ceux qui dépensent leurs biens dans le sentier d'Allah ressemblent à un grain d'où naissent sept épis, à cent grains l'épi. »",
             "Coran — Sourate Al-Baqara, 2:261"),
        en=L("To what does the Quran compare spending in the way of Allah?",
             ["To a seed that grows seven ears, each with a hundred grains", "To a stone", "To a well", "To a lamp"], 0,
             "\"The example of those who spend their wealth in the way of Allah is like a seed which grows seven spikes; in each spike is a hundred grains.\"",
             "Quran — Surah Al-Baqarah, 2:261"),
        ar=L("بماذا شبّه القرآن الإنفاق في سبيل الله؟",
             ["بحبة أنبتت سبع سنابل في كل سنبلة مائة حبة", "بحجر", "ببئر", "بمصباح"], 0,
             "«مثل الذين ينفقون أموالهم في سبيل الله كمثل حبة أنبتت سبع سنابل في كل سنبلة مائة حبة».",
             "القرآن — سورة البقرة، 2:261"))

    add("quran_128", "quran", "medium", "quran", Q, "2:264", False,
        fr=L("À quoi est comparée l'aumône annulée par le rappel et l'offense ?",
             ["À un rocher couvert de terre, lavé par une averse et laissé nu", "À un arbre fruitier", "À une source", "À une maison"], 0,
             "« Il ressemble à un rocher recouvert de terre : qu'une averse l'atteigne, elle le laisse dénudé. »",
             "Coran — Sourate Al-Baqara, 2:264"),
        en=L("To what is charity nullified by reproach and injury compared?",
             ["To a rock covered with soil, stripped bare by a downpour", "To a fruit tree", "To a spring", "To a house"], 0,
             "\"His example is like that of a smooth stone upon which is dust and is hit by a downpour that leaves it bare.\"",
             "Quran — Surah Al-Baqarah, 2:264"),
        ar=L("بماذا شُبّهت الصدقة التي يُبطلها المنّ والأذى؟",
             ["بصفوان عليه تراب أصابه وابل فتركه صلدًا", "بشجرة مثمرة", "بعين ماء", "ببيت"], 0,
             "«فمثله كمثل صفوان عليه تراب فأصابه وابل فتركه صلدًا».",
             "القرآن — سورة البقرة، 2:264"))

    add("quran_129", "quran", "hard", "quran", Q, "24:39", False,
        fr=L("À quoi le Coran compare-t-il les œuvres des mécréants dans la sourate An-Nûr ?",
             ["À un mirage dans une plaine, que l'assoiffé prend pour de l'eau", "À une montagne", "À une pluie", "À un jardin"], 0,
             "« Quant à ceux qui ont mécru, leurs actions sont comme un mirage dans une plaine : l'assoiffé y voit de l'eau, et quand il y arrive, il n'y trouve rien. »",
             "Coran — Sourate An-Nûr, 24:39"),
        en=L("To what does the Quran compare the deeds of the disbelievers in Surah An-Nur?",
             ["To a mirage on a plain, which the thirsty man takes for water", "To a mountain", "To rain", "To a garden"], 0,
             "\"But those who disbelieved — their deeds are like a mirage in a lowland which a thirsty one thinks is water, until he comes to it and finds it is nothing.\"",
             "Quran — Surah An-Nur, 24:39"),
        ar=L("بماذا شبّه القرآن أعمال الكافرين في سورة النور؟",
             ["بسراب بقيعة يحسبه الظمآن ماء", "بجبل", "بمطر", "بحديقة"], 0,
             "«والذين كفروا أعمالهم كسراب بقيعة يحسبه الظمآن ماءً حتى إذا جاءه لم يجده شيئًا».",
             "القرآن — سورة النور، 24:39"))

    add("quran_130", "quran", "easy", "quran", Q, "29:1-2", False,
        fr=L("Quelle question ouvre la sourate Al-ʿAnkabût, après les lettres isolées ?",
             ["« Les gens pensent-ils qu'on les laissera dire “nous croyons” sans être éprouvés ? »", "« Où sont les cieux ? »", "« Qui a créé la mer ? »", "« Que ferez-vous demain ? »"], 0,
             "« Est-ce que les gens pensent qu'on les laissera dire : “Nous croyons !”, sans les éprouver ? »",
             "Coran — Sourate Al-ʿAnkabût, 29:1-2"),
        en=L("Which question opens Surah Al-'Ankabut, after the isolated letters?",
             ["\"Do people think they will be left to say 'we believe' without being tested?\"", "\"Where are the heavens?\"", "\"Who created the sea?\"", "\"What will you do tomorrow?\""], 0,
             "\"Do the people think that they will be left to say 'we believe' and they will not be tried?\"",
             "Quran — Surah Al-'Ankabut, 29:1-2"),
        ar=L("بأي سؤال افتُتحت سورة العنكبوت بعد الحروف؟",
             ["«أحسب الناس أن يُتركوا أن يقولوا آمنا وهم لا يُفتنون؟»", "«أين السماوات؟»", "«من خلق البحر؟»", "«ماذا تفعلون غدًا؟»"], 0,
             "«أحسب الناس أن يُتركوا أن يقولوا آمنا وهم لا يُفتنون».",
             "القرآن — سورة العنكبوت، 29:1-2"))

    add("quran_131", "quran", "hard", "quran", Q, "35:1", False,
        fr=L("Comment la sourate Fâtir décrit-elle les anges dans son premier verset ?",
             ["Messagers pourvus d'ailes, deux, trois ou quatre", "Créés de terre", "Sans nombre connu", "Semblables aux hommes"], 0,
             "« Louange à Allah, Créateur des cieux et de la terre, qui a fait des anges des messagers dotés de deux, trois ou quatre ailes. »",
             "Coran — Sourate Fâtir, 35:1"),
        en=L("How does Surah Fatir describe the angels in its first verse?",
             ["Messengers having wings, two, three or four", "Created from clay", "Of unknown number", "Resembling human beings"], 0,
             "\"Praise to Allah, Creator of the heavens and the earth, who made the angels messengers having wings, two or three or four.\"",
             "Quran — Surah Fatir, 35:1"),
        ar=L("كيف وصفت سورة فاطر الملائكة في أول آية؟",
             ["رسلًا أولي أجنحة مثنى وثلاث ورباع", "خُلقوا من طين", "لا يُعرف عددهم", "يشبهون البشر"], 0,
             "«الحمد لله فاطر السماوات والأرض جاعل الملائكة رسلًا أولي أجنحة مثنى وثلاث ورباع».",
             "القرآن — سورة فاطر، 35:1"))

    add("quran_132", "quran", "medium", "quran", Q, "30:21", False,
        fr=L("Quel signe la sourate Ar-Rûm mentionne-t-elle au sujet des époux ?",
             ["Qu'Il a mis entre eux affection et miséricorde", "Qu'ils vivent séparés", "Qu'ils travaillent ensemble", "Qu'ils voyagent"], 0,
             "« Et parmi Ses signes : Il vous a créé des épouses issues de vous, pour que vous viviez en tranquillité avec elles, et Il a mis entre vous affection et miséricorde. »",
             "Coran — Sourate Ar-Rûm, 30:21"),
        en=L("What sign does Surah Ar-Rum mention concerning spouses?",
             ["That He placed affection and mercy between them", "That they live apart", "That they work together", "That they travel"], 0,
             "\"And of His signs is that He created for you from yourselves mates that you may find tranquillity in them, and He placed between you affection and mercy.\"",
             "Quran — Surah Ar-Rum, 30:21"),
        ar=L("أي آية ذكرتها سورة الروم في شأن الأزواج؟",
             ["أنه جعل بينهم مودة ورحمة", "أنهم يعيشون متفرقين", "أنهم يعملون معًا", "أنهم يسافرون"], 0,
             "«ومن آياته أن خلق لكم من أنفسكم أزواجًا لتسكنوا إليها وجعل بينكم مودة ورحمة».",
             "القرآن — سورة الروم، 30:21"))

    add("quran_133", "quran", "hard", "quran", Q, "30:22", False,
        fr=L("Quels deux signes la sourate Ar-Rûm cite-t-elle juste après la création des cieux et de la terre ?",
             ["La diversité des langues et des couleurs", "Le jour et la nuit", "Le vent et la pluie", "La mer et la montagne"], 0,
             "« Et parmi Ses signes : la création des cieux et de la terre, et la diversité de vos langues et de vos couleurs. »",
             "Coran — Sourate Ar-Rûm, 30:22"),
        en=L("Which two signs does Surah Ar-Rum name just after the creation of the heavens and the earth?",
             ["The diversity of languages and colours", "The day and the night", "The wind and the rain", "The sea and the mountain"], 0,
             "\"And of His signs is the creation of the heavens and the earth and the diversity of your languages and your colours.\"",
             "Quran — Surah Ar-Rum, 30:22"),
        ar=L("أي آيتين ذكرتهما سورة الروم بعد خلق السماوات والأرض؟",
             ["اختلاف الألسنة والألوان", "الليل والنهار", "الريح والمطر", "البحر والجبل"], 0,
             "«ومن آياته خلق السماوات والأرض واختلاف ألسنتكم وألوانكم».",
             "القرآن — سورة الروم، 30:22"))

    add("quran_134", "quran", "easy", "quran", Q, "21:30", False,
        fr=L("De quoi le Coran dit-il qu'Allah a fait toute chose vivante, dans la sourate Al-Anbiyâ ?",
             ["De l'eau", "Du feu", "De la pierre", "De l'air"], 0,
             "« Et Nous avons fait de l'eau toute chose vivante. Ne croiront-ils donc pas ? »",
             "Coran — Sourate Al-Anbiyâ, 21:30"),
        en=L("From what does the Quran say Allah made every living thing, in Surah Al-Anbiya?",
             ["From water", "From fire", "From stone", "From air"], 0,
             "\"And We made from water every living thing. Then will they not believe?\"",
             "Quran — Surah Al-Anbiya, 21:30"),
        ar=L("مِمّ جعل الله كل شيء حي بحسب سورة الأنبياء؟",
             ["من الماء", "من النار", "من الحجر", "من الهواء"], 0,
             "«وجعلنا من الماء كل شيء حي، أفلا يؤمنون».",
             "القرآن — سورة الأنبياء، 21:30"))

    add("quran_135", "quran", "hard", "quran", Q, "21:22", False,
        fr=L("Quel argument le Coran donne-t-il contre la pluralité des divinités, dans la sourate Al-Anbiyâ ?",
             ["S'il y avait d'autres divinités qu'Allah, les cieux et la terre seraient corrompus", "Elles se cacheraient", "Elles se tairaient", "Elles disparaîtraient"], 0,
             "« S'il y avait dans le ciel et la terre des divinités autres qu'Allah, tous deux seraient certes corrompus. »",
             "Coran — Sourate Al-Anbiyâ, 21:22"),
        en=L("What argument does the Quran give against a plurality of gods, in Surah Al-Anbiya?",
             ["Had there been gods besides Allah, the heavens and earth would be in ruin", "They would hide", "They would fall silent", "They would vanish"], 0,
             "\"Had there been within the heavens and earth gods besides Allah, they both would have been ruined.\"",
             "Quran — Surah Al-Anbiya, 21:22"),
        ar=L("ما الحجة التي ساقتها سورة الأنبياء على بطلان تعدد الآلهة؟",
             ["لو كان فيهما آلهة إلا الله لفسدتا", "لاختفت", "لسكتت", "لزالت"], 0,
             "«لو كان فيهما آلهة إلا الله لفسدتا».",
             "القرآن — سورة الأنبياء، 21:22"))

    add("quran_136", "quran", "medium", "quran", Q, "16:90", False,
        fr=L("Quelles trois choses le verset 16:90 dit-il qu'Allah commande ?",
             ["La justice, la bienfaisance et l'aide aux proches", "Le jeûne, la prière et le pèlerinage", "Le commerce, le voyage et l'écriture", "Le silence, la patience et la retraite"], 0,
             "« Certes, Allah commande la justice, la bienfaisance et l'aide aux proches. »",
             "Coran — Sourate An-Nahl, 16:90"),
        en=L("Which three things does verse 16:90 say Allah commands?",
             ["Justice, excellence, and giving to relatives", "Fasting, prayer and pilgrimage", "Trade, travel and writing", "Silence, patience and retreat"], 0,
             "\"Indeed, Allah orders justice and good conduct and giving to relatives.\"",
             "Quran — Surah An-Nahl, 16:90"),
        ar=L("بأي ثلاث أمر الله في الآية 16:90؟",
             ["العدل والإحسان وإيتاء ذي القربى", "الصيام والصلاة والحج", "التجارة والسفر والكتابة", "الصمت والصبر والاعتزال"], 0,
             "«إن الله يأمر بالعدل والإحسان وإيتاء ذي القربى».",
             "القرآن — سورة النحل، 16:90"))

    add("quran_137", "quran", "hard", "quran", Q, "16:69", False,
        fr=L("De quoi sort, selon la sourate An-Nahl, un breuvage aux couleurs variées qui est une guérison pour les gens ?",
             ["Du ventre des abeilles", "De la mer", "Des palmiers", "Des sources de la montagne"], 0,
             "« De leur ventre sort une liqueur aux couleurs variées, dans laquelle il y a une guérison pour les gens. »",
             "Coran — Sourate An-Nahl, 16:69"),
        en=L("From what, according to Surah An-Nahl, comes a drink of varying colours in which is healing for people?",
             ["From the bellies of the bees", "From the sea", "From the palm trees", "From mountain springs"], 0,
             "\"There emerges from their bellies a drink of varying colours in which there is healing for people.\"",
             "Quran — Surah An-Nahl, 16:69"),
        ar=L("مِمّ يخرج شراب مختلف ألوانه فيه شفاء للناس بحسب سورة النحل؟",
             ["من بطون النحل", "من البحر", "من النخل", "من عيون الجبل"], 0,
             "«يخرج من بطونها شراب مختلف ألوانه فيه شفاء للناس».",
             "القرآن — سورة النحل، 16:69"))

    add("quran_138", "quran", "easy", "quran", Q, "55:1-4", False,
        fr=L("Par quoi s'ouvre la sourate Ar-Rahmân ?",
             ["« Le Tout Miséricordieux a enseigné le Coran »", "« Par la nuit »", "« Louange à Allah »", "« Lis »"], 0,
             "« Le Tout Miséricordieux. Il a enseigné le Coran. Il a créé l'homme. Il lui a appris à s'exprimer clairement. »",
             "Coran — Sourate Ar-Rahmân, 55:1-4"),
        en=L("How does Surah Ar-Rahman open?",
             ["\"The Most Merciful taught the Quran\"", "\"By the night\"", "\"Praise be to Allah\"", "\"Read\""], 0,
             "\"The Most Merciful taught the Quran, created man, and taught him eloquence.\"",
             "Quran — Surah Ar-Rahman, 55:1-4"),
        ar=L("بماذا افتُتحت سورة الرحمن؟",
             ["«الرحمن، علّم القرآن»", "«والليل»", "«الحمد لله»", "«اقرأ»"], 0,
             "«الرحمن، علّم القرآن، خلق الإنسان، علّمه البيان».",
             "القرآن — سورة الرحمن، 55:1-4"))

    add("quran_139", "quran", "hard", "quran", Q, "56:7-10", False,
        fr=L("En combien de groupes la sourate Al-Wâqiʿa répartit-elle les hommes au Jour dernier ?",
             ["Trois", "Deux", "Quatre", "Sept"], 0,
             "« Vous serez alors trois catégories : les gens de la droite, les gens de la gauche, et les devanciers. »",
             "Coran — Sourate Al-Wâqiʿa, 56:7-10"),
        en=L("Into how many groups does Surah Al-Waqi'ah divide people on the Last Day?",
             ["Three", "Two", "Four", "Seven"], 0,
             "\"And you become of three kinds: the companions of the right, the companions of the left, and the forerunners.\"",
             "Quran — Surah Al-Waqi'ah, 56:7-10"),
        ar=L("إلى كم صنف قسّمت سورة الواقعة الناسَ يوم القيامة؟",
             ["ثلاثة", "اثنين", "أربعة", "سبعة"], 0,
             "«وكنتم أزواجًا ثلاثة: أصحاب الميمنة، وأصحاب المشأمة، والسابقون».",
             "القرآن — سورة الواقعة، 56:7-10"))

    add("quran_140", "quran", "medium", "quran", Q, "62:5", False,
        fr=L("À quoi le Coran compare-t-il ceux qui portent la Torah sans l'appliquer ?",
             ["À un âne chargé de livres", "À un oiseau", "À une montagne", "À un navire"], 0,
             "« Ceux qui ont été chargés de la Torah et qui ne l'ont pas appliquée sont pareils à l'âne qui porte des livres. »",
             "Coran — Sourate Al-Jumuʿa, 62:5"),
        en=L("To what does the Quran compare those who carry the Torah without acting on it?",
             ["To a donkey carrying books", "To a bird", "To a mountain", "To a ship"], 0,
             "\"The example of those who were entrusted with the Torah and then did not take it on is like that of a donkey carrying volumes of books.\"",
             "Quran — Surah Al-Jumu'ah, 62:5"),
        ar=L("بماذا شبّه القرآن من حُمّلوا التوراة ثم لم يعملوا بها؟",
             ["بالحمار يحمل أسفارًا", "بالطائر", "بالجبل", "بالسفينة"], 0,
             "«مثل الذين حُمّلوا التوراة ثم لم يحملوها كمثل الحمار يحمل أسفارًا».",
             "القرآن — سورة الجمعة، 62:5"))

    add("quran_141", "quran", "hard", "quran", Q, "66:11", False,
        fr=L("Quelle femme le Coran donne-t-il en exemple aux croyants, en citant sa demande d'une maison auprès d'Allah ?",
             ["La femme de Pharaon", "La reine de Saba", "La femme de Nûh", "La femme de Lût"], 0,
             "« Allah a cité en exemple pour ceux qui croient la femme de Pharaon, quand elle dit : “Seigneur, bâtis-moi auprès de Toi une maison au Paradis.” »",
             "Coran — Sourate At-Tahrîm, 66:11"),
        en=L("Which woman does the Quran hold up as an example to the believers, citing her request for a house with Allah?",
             ["The wife of Pharaoh", "The queen of Saba", "The wife of Nuh", "The wife of Lut"], 0,
             "\"And Allah presents an example of those who believed: the wife of Pharaoh, when she said: 'My Lord, build for me near You a house in Paradise.'\"",
             "Quran — Surah At-Tahrim, 66:11"),
        ar=L("أي امرأة ضربها القرآن مثلًا للمؤمنين بدعائها ببيت عند الله؟",
             ["امرأة فرعون", "ملكة سبأ", "امرأة نوح", "امرأة لوط"], 0,
             "«وضرب الله مثلًا للذين آمنوا امرأة فرعون إذ قالت رب ابنِ لي عندك بيتًا في الجنة».",
             "القرآن — سورة التحريم، 66:11"))

    add("quran_142", "quran", "easy", "quran", Q, "112:1", False,
        fr=L("Quel autre nom porte souvent la sourate Al-Ikhlâs, en raison de son sujet ?",
             ["La sourate de l'unicité (at-tawhîd)", "La sourate du voyage", "La sourate de la lumière", "La sourate du butin"], 0,
             "Al-Ikhlâs, « le monothéisme pur », est aussi appelée la sourate du tawhîd, car elle décrit Allah comme l'Unique.",
             "Coran — Sourate Al-Ikhlâs, 112:1"),
        en=L("By what other name is Surah Al-Ikhlas often known, from its subject?",
             ["The surah of oneness (at-tawhid)", "The surah of the journey", "The surah of light", "The surah of the spoils"], 0,
             "Al-Ikhlas, \"pure devotion\", is also called the surah of tawhid, for it describes Allah as the One.",
             "Quran — Surah Al-Ikhlas, 112:1"),
        ar=L("بأي اسم آخر تُعرف سورة الإخلاص لموضوعها؟",
             ["سورة التوحيد", "سورة السفر", "سورة النور", "سورة الغنيمة"], 0,
             "سورة الإخلاص تُسمّى أيضًا سورة التوحيد لأنها تصف الله بالوحدانية.",
             "القرآن — سورة الإخلاص، 112:1"))

    add("quran_143", "quran", "easy", "quran", Q, "112:3", False,
        fr=L("Que nie le troisième verset de la sourate Al-Ikhlâs ?",
             ["Qu'Il ait engendré ou été engendré", "Qu'Il soit puissant", "Qu'Il entende", "Qu'Il crée"], 0,
             "« Il n'a jamais engendré, n'a pas été engendré non plus. »",
             "Coran — Sourate Al-Ikhlâs, 112:3"),
        en=L("What does the third verse of Surah Al-Ikhlas deny?",
             ["That He begot or was begotten", "That He is powerful", "That He hears", "That He creates"], 0,
             "\"He neither begets nor is born.\"",
             "Quran — Surah Al-Ikhlas, 112:3"),
        ar=L("ماذا نفت الآية الثالثة من سورة الإخلاص؟",
             ["أن يلد أو يولد", "أن يكون قادرًا", "أن يسمع", "أن يخلق"], 0,
             "«لم يلد ولم يولد».",
             "القرآن — سورة الإخلاص، 112:3"))

    add("quran_144", "quran", "easy", "quran", Q, "114:4-6", False,
        fr=L("Contre quoi la sourate An-Nâs demande-t-elle refuge ?",
             ["Le mauvais conseiller furtif, parmi les djinns et les hommes", "La tempête", "La maladie", "La pauvreté"], 0,
             "« … contre le mal du mauvais conseiller furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit des djinns ou des hommes. »",
             "Coran — Sourate An-Nâs, 114:4-6"),
        en=L("Against what does Surah An-Nas seek refuge?",
             ["The retreating whisperer, from among jinn and mankind", "The storm", "Illness", "Poverty"], 0,
             "\"…from the evil of the retreating whisperer, who whispers in the breasts of mankind, from among the jinn and mankind.\"",
             "Quran — Surah An-Nas, 114:4-6"),
        ar=L("مِمّ استعاذت سورة الناس؟",
             ["من شر الوسواس الخنّاس من الجِنّة والناس", "من العاصفة", "من المرض", "من الفقر"], 0,
             "«من شر الوسواس الخنّاس، الذي يوسوس في صدور الناس، من الجِنّة والناس».",
             "القرآن — سورة الناس، 114:4-6"))

    add("quran_145", "quran", "hard", "quran", Q, "113:2-5", False,
        fr=L("Combien de maux distincts la sourate Al-Falaq nomme-t-elle après « le mal des êtres créés » ?",
             ["Trois : la nuit obscure, les souffleuses sur les nœuds, et l'envieux", "Un seul", "Cinq", "Sept"], 0,
             "« … contre le mal de l'obscurité quand elle s'approfondit, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie. »",
             "Coran — Sourate Al-Falaq, 113:2-5"),
        en=L("How many distinct evils does Surah Al-Falaq name after \"the evil of what He created\"?",
             ["Three: the darkening night, those who blow on knots, and the envier", "One", "Five", "Seven"], 0,
             "\"…from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies.\"",
             "Quran — Surah Al-Falaq, 113:2-5"),
        ar=L("كم شرًّا سمّته سورة الفلق بعد «شر ما خلق»؟",
             ["ثلاثة: الغاسق، والنفاثات في العقد، والحاسد", "واحدًا", "خمسة", "سبعة"], 0,
             "«ومن شر غاسق إذا وقب، ومن شر النفاثات في العقد، ومن شر حاسد إذا حسد».",
             "القرآن — سورة الفلق، 113:2-5"))

    add("quran_146", "quran", "easy", "quran", Q, "1:5", False,
        fr=L("Quel verset de la Fâtiha exprime le cœur de l'adoration et de la demande d'aide ?",
             ["« C'est Toi que nous adorons, et c'est Toi dont nous implorons secours »", "« Louange à Allah »", "« Guide-nous »", "« Maître du Jour de la rétribution »"], 0,
             "« C'est Toi que nous adorons, et c'est Toi dont nous implorons secours. »",
             "Coran — Sourate Al-Fâtiha, 1:5"),
        en=L("Which verse of Al-Fatihah expresses the heart of worship and of seeking help?",
             ["\"You alone we worship, and You alone we ask for help\"", "\"Praise be to Allah\"", "\"Guide us\"", "\"Master of the Day of Judgement\""], 0,
             "\"You alone we worship and You alone we ask for help.\"",
             "Quran — Surah Al-Fatihah, 1:5"),
        ar=L("أي آية من الفاتحة تجمع لبّ العبادة والاستعانة؟",
             ["«إياك نعبد وإياك نستعين»", "«الحمد لله»", "«اهدنا»", "«مالك يوم الدين»"], 0,
             "«إياك نعبد وإياك نستعين».",
             "القرآن — سورة الفاتحة، 1:5"))

    add("quran_147", "quran", "hard", "quran", Q, "1:6-7", False,
        fr=L("Quelle demande clôt la sourate Al-Fâtiha ?",
             ["Être guidé sur le droit chemin, celui des favorisés", "La richesse", "La victoire", "La longue vie"], 0,
             "« Guide-nous dans le droit chemin, le chemin de ceux que Tu as comblés de faveurs. »",
             "Coran — Sourate Al-Fâtiha, 1:6-7"),
        en=L("What request closes Surah Al-Fatihah?",
             ["To be guided on the straight path, the path of those favoured", "Wealth", "Victory", "Long life"], 0,
             "\"Guide us to the straight path, the path of those upon whom You have bestowed favour.\"",
             "Quran — Surah Al-Fatihah, 1:6-7"),
        ar=L("بأي سؤال خُتمت سورة الفاتحة؟",
             ["الهداية إلى الصراط المستقيم صراط المنعَم عليهم", "المال", "النصر", "طول العمر"], 0,
             "«اهدنا الصراط المستقيم، صراط الذين أنعمت عليهم».",
             "القرآن — سورة الفاتحة، 1:6-7"))

    add("quran_148", "quran", "medium", "quran", Q, "3:7", False,
        fr=L("Quels deux types de versets la sourate Âl ʿImrân distingue-t-elle ?",
             ["Les versets clairs (muhkamât) et les versets ambigus (mutashâbihât)", "Les longs et les courts", "Les mecquois et les médinois", "Les récités et les écrits"], 0,
             "« C'est Lui qui a fait descendre sur toi le Livre : il s'y trouve des versets sans équivoque, qui sont la base du Livre, et d'autres qui sont susceptibles d'interprétations diverses. »",
             "Coran — Sourate Âl ʿImrân, 3:7"),
        en=L("Which two kinds of verses does Surah Al-'Imran distinguish?",
             ["Clear verses (muhkamat) and ambiguous verses (mutashabihat)", "The long and the short", "The Makkan and the Madinan", "The recited and the written"], 0,
             "\"It is He who revealed to you the Book: in it are verses that are precise — they are the foundation of the Book — and others unspecific.\"",
             "Quran — Surah Al-'Imran, 3:7"),
        ar=L("أي نوعين من الآيات فرّقت بينهما سورة آل عمران؟",
             ["المحكمات والمتشابهات", "الطوال والقصار", "المكي والمدني", "المتلوّ والمكتوب"], 0,
             "«هو الذي أنزل عليك الكتاب منه آيات محكمات هن أم الكتاب وأُخر متشابهات».",
             "القرآن — سورة آل عمران، 3:7"))

    add("quran_149", "quran", "hard", "quran", Q, "2:106", False,
        fr=L("Quel principe le verset 2:106 énonce-t-il au sujet des versets remplacés ?",
             ["Allah en apporte un meilleur ou un semblable", "Ils sont effacés sans remplacement", "Ils sont oubliés", "Ils sont réécrits par les hommes"], 0,
             "« Si Nous abrogeons un verset quelconque ou que Nous le fassions oublier, Nous en apportons un meilleur, ou un semblable. »",
             "Coran — Sourate Al-Baqara, 2:106"),
        en=L("What principle does verse 2:106 state about replaced verses?",
             ["Allah brings one better than it or like it", "They are erased with no replacement", "They are forgotten", "They are rewritten by people"], 0,
             "\"We do not abrogate a verse or cause it to be forgotten except that We bring forth one better than it or similar to it.\"",
             "Quran — Surah Al-Baqarah, 2:106"),
        ar=L("أي أصل قرّرته الآية 2:106 في شأن الآيات المنسوخة؟",
             ["يأتي الله بخير منها أو مثلها", "تُمحى بلا بديل", "تُنسى", "يعيد الناس كتابتها"], 0,
             "«ما ننسخ من آية أو نُنسها نأتِ بخير منها أو مثلها».",
             "القرآن — سورة البقرة، 2:106"))

    add("quran_150", "quran", "hard", "quran", Q, "25:30", False,
        fr=L("De quoi le Messager ﷺ se plaindra-t-il à son Seigneur, selon la sourate Al-Furqân ?",
             ["Que son peuple a délaissé ce Coran", "Qu'il est fatigué", "Qu'il est seul", "Qu'il est pauvre"], 0,
             "« Et le Messager dira : “Seigneur, mon peuple a vraiment pris ce Coran pour une chose délaissée.” »",
             "Coran — Sourate Al-Furqân, 25:30"),
        en=L("Of what will the Messenger ﷺ complain to his Lord, according to Surah Al-Furqan?",
             ["That his people abandoned this Quran", "That he is tired", "That he is alone", "That he is poor"], 0,
             "\"And the Messenger will say: 'O my Lord, indeed my people have taken this Quran as a thing abandoned.'\"",
             "Quran — Surah Al-Furqan, 25:30"),
        ar=L("مِمّ يشكو الرسول ﷺ إلى ربه بحسب سورة الفرقان؟",
             ["أن قومه اتخذوا هذا القرآن مهجورًا", "أنه تعِب", "أنه وحيد", "أنه فقير"], 0,
             "«وقال الرسول يا رب إن قومي اتخذوا هذا القرآن مهجورًا».",
             "القرآن — سورة الفرقان، 25:30"))
