"""Faith & worship — part B (faith_019 … faith_070)."""

WT = "well-established terminology"
WP = "well-established practice, agreed across the schools"


def register(add, L):
    Q = "Quran"
    C = "Creed"
    B = "Sahih al-Bukhari"
    M = "Sahih Muslim"

    add("faith_019", "faith", "easy", "quran", Q, "5:44", False,
        fr=L("Quel Livre Allah a-t-Il révélé au prophète Mûsâ ?",
             ["La Tawrât (Torah)", "L'Injîl (Évangile)", "Le Zabûr (Psaumes)", "Le Coran"], 0,
             "« Nous avons fait descendre la Tawrât, dans laquelle il y a guide et lumière » (5:44).",
             "Coran 5:44"),
        en=L("Which Book did Allah reveal to the prophet Musa?",
             ["The Tawrat (Torah)", "The Injil (Gospel)", "The Zabur (Psalms)", "The Qur'an"], 0,
             "\"We sent down the Tawrat, in which was guidance and light\" (5:44).",
             "Qur'an 5:44"),
        ar=L("أي كتاب أنزله الله على النبي موسى؟",
             ["التوراة", "الإنجيل", "الزبور", "القرآن"], 0,
             "«إنا أنزلنا التوراة فيها هدى ونور» (5:44).",
             "القرآن 5:44"))

    add("faith_020", "faith", "easy", "quran", Q, "5:46", False,
        fr=L("Quel Livre Allah a-t-Il donné au prophète 'Îsâ ?",
             ["L'Injîl (Évangile)", "La Tawrât", "Le Zabûr", "Les Feuillets d'Ibrâhîm"], 0,
             "« Nous lui avons donné l'Injîl, où il y a guide et lumière » (5:46).",
             "Coran 5:46"),
        en=L("Which Book did Allah give to the prophet 'Isa?",
             ["The Injil (Gospel)", "The Tawrat", "The Zabur", "The Scrolls of Ibrahim"], 0,
             "\"We gave him the Injil, in which was guidance and light\" (5:46).",
             "Qur'an 5:46"),
        ar=L("أي كتاب آتاه الله النبي عيسى؟",
             ["الإنجيل", "التوراة", "الزبور", "صحف إبراهيم"], 0,
             "«وآتيناه الإنجيل فيه هدى ونور» (5:46).",
             "القرآن 5:46"))

    add("faith_021", "faith", "easy", "quran", Q, "4:86", False,
        fr=L("Selon le Coran, que doit-on faire lorsqu'on reçoit une salutation ?",
             ["Répondre par une meilleure salutation, ou la rendre", "Rester silencieux", "Baisser les yeux", "Répondre seulement aux amis"], 0,
             "« Quand on vous adresse une salutation, saluez d'une façon meilleure, ou rendez-la simplement » (4:86).",
             "Coran 4:86"),
        en=L("According to the Qur'an, what should one do when greeted?",
             ["Answer with a better greeting, or return it", "Stay silent", "Look down", "Answer only friends"], 0,
             "\"When you are greeted with a greeting, greet with one better than it, or return it\" (4:86).",
             "Qur'an 4:86"),
        ar=L("بحسب القرآن، ماذا يفعل المسلم إذا حُيّي بتحية؟",
             ["يردّ بأحسن منها أو يردّها", "يسكت", "يخفض بصره", "يردّ على الأصدقاء فقط"], 0,
             "«وإذا حُيّيتم بتحية فحيّوا بأحسن منها أو ردّوها» (4:86).",
             "القرآن 4:86"))

    add("faith_022", "faith", "hard", "quran", Q, "87:18-19", False,
        fr=L("La sourate Al-A'lâ mentionne « les Feuillets » (suhuf) de quels deux prophètes ?",
             ["Ibrâhîm et Mûsâ", "Nûh et Hûd", "Dâwûd et Sulaymân", "Zakariyyâ et Yahyâ"], 0,
             "« Ceci se trouve dans les Feuillets anciens, les Feuillets d'Ibrâhîm et de Mûsâ » (87:18-19).",
             "Coran 87:18-19"),
        en=L("Surah Al-A'la mentions \"the Scrolls\" (suhuf) of which two prophets?",
             ["Ibrahim and Musa", "Nuh and Hud", "Dawud and Sulayman", "Zakariyya and Yahya"], 0,
             "\"This is in the former Scrolls, the Scrolls of Ibrahim and Musa\" (87:18-19).",
             "Qur'an 87:18-19"),
        ar=L("ذكرت سورة الأعلى «صحف» أي نبيين؟",
             ["إبراهيم وموسى", "نوح وهود", "داود وسليمان", "زكريا ويحيى"], 0,
             "«إن هذا لفي الصحف الأولى صحف إبراهيم وموسى» (87:18-19).",
             "القرآن 87:18-19"))

    add("faith_023", "faith", "hard", "quran", Q, "43:77", False,
        fr=L("Quel est le nom de l'ange gardien de l'Enfer, cité dans le Coran ?",
             ["Mâlik", "Ridwân", "Mîkâ'îl", "Isrâfîl"], 0,
             "Les gens de l'Enfer appelleront : « Ô Mâlik, que ton Seigneur nous achève ! » (43:77).",
             "Coran 43:77"),
        en=L("What is the name of the angel who guards Hell, mentioned in the Qur'an?",
             ["Malik", "Ridwan", "Mika'il", "Israfil"], 0,
             "The people of Hell will call: \"O Malik, let your Lord put an end to us!\" (43:77).",
             "Qur'an 43:77"),
        ar=L("ما اسم الملك خازن النار المذكور في القرآن؟",
             ["مالك", "رضوان", "ميكائيل", "إسرافيل"], 0,
             "ينادي أهل النار: «يا مالك ليقض علينا ربك» (43:77).",
             "القرآن 43:77"))

    add("faith_024", "faith", "hard", "quran", Q, "69:17", False,
        fr=L("Selon la sourate Al-Hâqqa, combien d'anges porteront le Trône d'Allah le Jour de la Résurrection ?",
             ["Huit", "Quatre", "Douze", "Un seul"], 0,
             "« Et ce Jour-là, huit porteront au-dessus d'eux le Trône de ton Seigneur » (69:17).",
             "Coran 69:17"),
        en=L("According to Surah Al-Haqqa, how many angels will carry the Throne of Allah on the Day of Resurrection?",
             ["Eight", "Four", "Twelve", "One"], 0,
             "\"And on that Day, eight will bear the Throne of your Lord above them\" (69:17).",
             "Qur'an 69:17"),
        ar=L("بحسب سورة الحاقة، كم ملكًا يحملون عرش الله يوم القيامة؟",
             ["ثمانية", "أربعة", "اثنا عشر", "واحد"], 0,
             "«ويحمل عرش ربك فوقهم يومئذ ثمانية» (69:17).",
             "القرآن 69:17"))

    add("faith_025", "faith", "medium", "quran", Q, "32:11", False,
        fr=L("Selon le Coran, qui est chargé de recueillir les âmes au moment de la mort ?",
             ["L'ange de la mort", "Jibrîl", "Le prophète", "Les djinns"], 0,
             "« Dis : l'ange de la mort qui est chargé de vous recueillera votre âme » (32:11).",
             "Coran 32:11"),
        en=L("According to the Qur'an, who is charged with taking souls at death?",
             ["The angel of death", "Jibril", "The prophet", "The jinn"], 0,
             "\"Say: the angel of death, who is put in charge of you, will take your souls\" (32:11).",
             "Qur'an 32:11"),
        ar=L("بحسب القرآن، من الموكّل بقبض الأرواح عند الموت؟",
             ["ملك الموت", "جبريل", "النبي", "الجن"], 0,
             "«قل يتوفاكم ملك الموت الذي وُكّل بكم» (32:11).",
             "القرآن 32:11"))

    add("faith_026", "faith", "medium", "hadithMuslim", M, "2996", False,
        fr=L("De quoi les anges ont-ils été créés, selon un hadith rapporté par Muslim ?",
             ["De lumière", "De feu", "D'argile", "D'eau"], 0,
             "« Les anges ont été créés de lumière, les djinns d'un feu sans fumée, et Adam de ce qui vous a été décrit. »",
             "Sahîh Muslim, 2996"),
        en=L("From what were the angels created, according to a hadith in Sahih Muslim?",
             ["From light", "From fire", "From clay", "From water"], 0,
             "\"The angels were created from light, the jinn from smokeless fire, and Adam from what has been described to you.\"",
             "Sahih Muslim, 2996"),
        ar=L("مِمّ خُلقت الملائكة بحسب حديث رواه مسلم؟",
             ["من نور", "من نار", "من طين", "من ماء"], 0,
             "«خُلقت الملائكة من نور، وخُلق الجانّ من مارج من نار، وخُلق آدم مما وُصف لكم».",
             "صحيح مسلم، 2996"))

    add("faith_027", "faith", "easy", "quran", Q, "55:15", False,
        fr=L("De quoi les djinns ont-ils été créés, selon le Coran ?",
             ["D'un feu sans fumée", "De lumière", "D'argile", "De vent"], 0,
             "« Et Il a créé les djinns d'une flamme de feu sans fumée » (55:15).",
             "Coran 55:15"),
        en=L("From what were the jinn created, according to the Qur'an?",
             ["From smokeless fire", "From light", "From clay", "From wind"], 0,
             "\"And He created the jinn from a smokeless flame of fire\" (55:15).",
             "Qur'an 55:15"),
        ar=L("مِمّ خُلق الجن بحسب القرآن؟",
             ["من مارج من نار", "من نور", "من طين", "من ريح"], 0,
             "«وخلق الجانّ من مارج من نار» (55:15).",
             "القرآن 55:15"))

    add("faith_028", "faith", "easy", "quran", Q, "35:6", False,
        fr=L("Qui le Coran désigne-t-il comme un ennemi déclaré de l'être humain ?",
             ["Satan (ash-Shaytân)", "Les anges", "Les animaux", "La nuit"], 0,
             "« Le Diable est pour vous un ennemi : prenez-le donc pour ennemi » (35:6).",
             "Coran 35:6"),
        en=L("Whom does the Qur'an name as a declared enemy of human beings?",
             ["Satan (ash-Shaytan)", "The angels", "The animals", "The night"], 0,
             "\"Indeed, Satan is an enemy to you; so take him as an enemy\" (35:6).",
             "Qur'an 35:6"),
        ar=L("من الذي وصفه القرآن بأنه عدوّ للإنسان؟",
             ["الشيطان", "الملائكة", "الحيوانات", "الليل"], 0,
             "«إن الشيطان لكم عدوّ فاتخذوه عدوًّا» (35:6).",
             "القرآن 35:6"))

    add("faith_029", "faith", "hard", "quran", Q, "46:35; 42:13", False,
        fr=L("Combien de prophètes sont appelés « Ulû al-'Azm » (doués de fermeté) ?",
             ["Cinq : Nûh, Ibrâhîm, Mûsâ, 'Îsâ et Muhammad ﷺ", "Trois", "Dix", "Vingt-cinq"], 0,
             "« Endure comme ont enduré les messagers doués de fermeté » (46:35) ; la sourate Ash-Shûrâ (42:13) cite ces cinq noms ensemble.",
             "Coran 46:35 ; 42:13"),
        en=L("How many prophets are called \"Ulu al-'Azm\" (those of firm resolve)?",
             ["Five: Nuh, Ibrahim, Musa, 'Isa and Muhammad ﷺ", "Three", "Ten", "Twenty-five"], 0,
             "\"Be patient as the messengers of firm resolve were patient\" (46:35); Surah Ash-Shura (42:13) names these five together.",
             "Qur'an 46:35; 42:13"),
        ar=L("كم عدد الرسل الملقبين بـ«أولي العزم»؟",
             ["خمسة: نوح وإبراهيم وموسى وعيسى ومحمد ﷺ", "ثلاثة", "عشرة", "خمسة وعشرون"], 0,
             "«فاصبر كما صبر أولو العزم من الرسل» (46:35)، وقد جمعت سورة الشورى (42:13) هذه الأسماء الخمسة.",
             "القرآن 46:35؛ 42:13"))

    add("faith_030", "faith", "medium", "quran", Q, "39:68", False,
        fr=L("Dans quoi soufflera-t-on pour annoncer la Résurrection, selon le Coran ?",
             ["Dans la Trompe (as-Sûr)", "Dans un cor de bélier", "Dans une flûte", "Dans une cloche"], 0,
             "« On soufflera dans la Trompe, et ceux qui sont dans les cieux et sur la terre seront foudroyés… puis on y soufflera de nouveau » (39:68).",
             "Coran 39:68"),
        en=L("What will be blown to announce the Resurrection, according to the Qur'an?",
             ["The Trumpet (as-Sur)", "A ram's horn", "A flute", "A bell"], 0,
             "\"The Trumpet will be blown, and whoever is in the heavens and the earth will fall dead… then it will be blown again\" (39:68).",
             "Qur'an 39:68"),
        ar=L("فيمَ يُنفخ إيذانًا بالبعث بحسب القرآن؟",
             ["في الصور", "في قرن كبش", "في ناي", "في جرس"], 0,
             "«ونُفخ في الصور فصعق من في السماوات ومن في الأرض... ثم نُفخ فيه أخرى» (39:68).",
             "القرآن 39:68"))

    add("faith_031", "faith", "medium", "quran", Q, "21:47", False,
        fr=L("Comment le Coran appelle-t-il ce qui pèsera les actes le Jour de la Résurrection ?",
             ["Les balances (al-Mawâzîn)", "Le registre", "Le pont", "La trompe"], 0,
             "« Nous placerons les balances exactes au Jour de la Résurrection ; nulle âme ne sera lésée en rien » (21:47).",
             "Coran 21:47"),
        en=L("What does the Qur'an call that which will weigh deeds on the Day of Resurrection?",
             ["The scales (al-Mawazin)", "The register", "The bridge", "The trumpet"], 0,
             "\"We will set up the just scales on the Day of Resurrection; no soul will be wronged in anything\" (21:47).",
             "Qur'an 21:47"),
        ar=L("ماذا يسمّي القرآن ما تُوزن به الأعمال يوم القيامة؟",
             ["الموازين", "السجلّ", "الصراط", "الصور"], 0,
             "«ونضع الموازين القسط ليوم القيامة فلا تُظلم نفس شيئًا» (21:47).",
             "القرآن 21:47"))

    add("faith_032", "faith", "medium", "quran", Q, "18:107", False,
        fr=L("Quel nom le Coran donne-t-il au plus haut degré du Paradis, promis à ceux qui croient et font le bien ?",
             ["Al-Firdaws", "Al-Kawthar", "As-Sirât", "Al-A'râf"], 0,
             "« Ceux qui croient et font de bonnes œuvres auront pour résidence les Jardins du Firdaws » (18:107).",
             "Coran 18:107"),
        en=L("What name does the Qur'an give to the highest level of Paradise, promised to those who believe and do good?",
             ["Al-Firdaws", "Al-Kawthar", "As-Sirat", "Al-A'raf"], 0,
             "\"Those who believe and do righteous deeds will have the Gardens of Firdaws as a lodging\" (18:107).",
             "Qur'an 18:107"),
        ar=L("ما اسم أعلى درجات الجنة الذي وعد الله به الذين آمنوا وعملوا الصالحات؟",
             ["الفردوس", "الكوثر", "الصراط", "الأعراف"], 0,
             "«إن الذين آمنوا وعملوا الصالحات كانت لهم جنات الفردوس نزلًا» (18:107).",
             "القرآن 18:107"))

    add("faith_033", "faith", "easy", "quran", Q, "3:12", False,
        fr=L("Quel est le nom le plus courant de l'Enfer dans le Coran ?",
             ["Jahannam", "Firdaws", "Kawthar", "Tasnîm"], 0,
             "Le Coran nomme l'Enfer « Jahannam » des dizaines de fois, par exemple : « Vous serez rassemblés vers Jahannam » (3:12).",
             "Coran 3:12"),
        en=L("What is the most common name for Hell in the Qur'an?",
             ["Jahannam", "Firdaws", "Kawthar", "Tasnim"], 0,
             "The Qur'an calls Hell \"Jahannam\" dozens of times, for example: \"You will be gathered to Jahannam\" (3:12).",
             "Qur'an 3:12"),
        ar=L("ما أكثر أسماء النار ورودًا في القرآن؟",
             ["جهنم", "الفردوس", "الكوثر", "تسنيم"], 0,
             "سمّى القرآن النار «جهنم» عشرات المرات، مثل: «وتُحشرون إلى جهنم» (3:12).",
             "القرآن 3:12"))

    add("faith_034", "faith", "hard", "quran", Q, "54:49", False,
        fr=L("Quel pilier de la foi affirme le verset : « Nous avons créé toute chose avec mesure » ?",
             ["La croyance au destin (al-qadar)", "La croyance aux anges", "La croyance aux Livres", "La croyance aux messagers"], 0,
             "« Nous avons créé toute chose selon une mesure (qadar) » (54:49) : rien n'arrive sans la science et la volonté d'Allah.",
             "Coran 54:49"),
        en=L("Which pillar of faith does the verse \"We have created everything with measure\" affirm?",
             ["Belief in the divine decree (al-qadar)", "Belief in angels", "Belief in the Books", "Belief in the messengers"], 0,
             "\"We have created everything according to a measure (qadar)\" (54:49): nothing happens outside Allah's knowledge and will.",
             "Qur'an 54:49"),
        ar=L("أي ركن من أركان الإيمان تقرره الآية: «إنا كل شيء خلقناه بقدر»؟",
             ["الإيمان بالقدر", "الإيمان بالملائكة", "الإيمان بالكتب", "الإيمان بالرسل"], 0,
             "«إنا كل شيء خلقناه بقدر» (54:49)، فلا يقع شيء إلا بعلم الله ومشيئته.",
             "القرآن 54:49"))

    add("faith_035", "faith", "medium", "quran", Q, "4:48", False,
        fr=L("Quel péché Allah déclare-t-Il ne pas pardonner à celui qui meurt sans s'en repentir ?",
             ["Le shirk (associer quelque chose à Allah)", "Le mensonge", "L'avarice", "La colère"], 0,
             "« Allah ne pardonne pas qu'on Lui donne un associé, et Il pardonne ce qui est en deçà à qui Il veut » (4:48).",
             "Coran 4:48"),
        en=L("Which sin does Allah declare He does not forgive for one who dies without repenting of it?",
             ["Shirk (associating partners with Allah)", "Lying", "Miserliness", "Anger"], 0,
             "\"Allah does not forgive that partners be associated with Him, and He forgives what is less than that to whom He wills\" (4:48).",
             "Qur'an 4:48"),
        ar=L("ما الذنب الذي أخبر الله أنه لا يغفره لمن مات عليه دون توبة؟",
             ["الشرك بالله", "الكذب", "البخل", "الغضب"], 0,
             "«إن الله لا يغفر أن يُشرك به ويغفر ما دون ذلك لمن يشاء» (4:48).",
             "القرآن 4:48"))

    add("faith_036", "faith", "easy", "quran", Q, "2:222", False,
        fr=L("Selon le Coran, qui Allah aime-t-Il, parmi ceux qui ont commis des fautes ?",
             ["Ceux qui se repentent", "Ceux qui cachent leurs fautes", "Ceux qui désespèrent", "Ceux qui accusent les autres"], 0,
             "« Certes, Allah aime ceux qui se repentent et Il aime ceux qui se purifient » (2:222).",
             "Coran 2:222"),
        en=L("According to the Qur'an, whom does Allah love among those who have sinned?",
             ["Those who repent", "Those who hide their sins", "Those who despair", "Those who blame others"], 0,
             "\"Indeed, Allah loves those who repent and He loves those who purify themselves\" (2:222).",
             "Qur'an 2:222"),
        ar=L("بحسب القرآن، من يحب الله ممن أخطؤوا؟",
             ["التوابين", "الذين يخفون ذنوبهم", "اليائسين", "الذين يتهمون غيرهم"], 0,
             "«إن الله يحب التوابين ويحب المتطهرين» (2:222).",
             "القرآن 2:222"))

    add("faith_037", "faith", "medium", "quran", Q, "71:10-11", False,
        fr=L("Selon la sourate Nûh, qu'apporte la demande de pardon (istighfâr) à un peuple ?",
             ["Une pluie abondante et des bienfaits", "Rien du tout", "Une sécheresse", "Un long sommeil"], 0,
             "« Implorez le pardon de votre Seigneur, car Il est grand Pardonneur ; Il enverra sur vous le ciel en pluie abondante » (71:10-11).",
             "Coran 71:10-11"),
        en=L("According to Surah Nuh, what does seeking forgiveness (istighfar) bring a people?",
             ["Abundant rain and blessings", "Nothing at all", "A drought", "A long sleep"], 0,
             "\"Ask forgiveness of your Lord; indeed, He is ever Forgiving. He will send the sky upon you in abundant rain\" (71:10-11).",
             "Qur'an 71:10-11"),
        ar=L("بحسب سورة نوح، ماذا يجلب الاستغفار للقوم؟",
             ["مطرًا غزيرًا وبركات", "لا شيء", "جفافًا", "نومًا طويلًا"], 0,
             "«استغفروا ربكم إنه كان غفارًا يرسل السماء عليكم مدرارًا» (71:10-11).",
             "القرآن 71:10-11"))

    add("faith_038", "faith", "medium", "quran", Q, "65:3", False,
        fr=L("Que promet le Coran à celui qui place sa confiance en Allah (tawakkul) ?",
             ["Allah lui suffit", "Il deviendra riche", "Il ne sera jamais malade", "Il n'aura plus à travailler"], 0,
             "« Et quiconque place sa confiance en Allah, Il lui suffit » (65:3).",
             "Coran 65:3"),
        en=L("What does the Qur'an promise the one who puts their trust in Allah (tawakkul)?",
             ["Allah is enough for them", "They will become rich", "They will never be ill", "They will no longer have to work"], 0,
             "\"And whoever relies upon Allah, He is sufficient for him\" (65:3).",
             "Qur'an 65:3"),
        ar=L("ماذا وعد الله من توكّل عليه؟",
             ["أن الله حسبه وكافيه", "أن يصير غنيًا", "ألا يمرض أبدًا", "ألا يحتاج إلى العمل"], 0,
             "«ومن يتوكل على الله فهو حسبه» (65:3).",
             "القرآن 65:3"))

    add("faith_039", "faith", "easy", "quran", Q, "40:60", False,
        fr=L("Que dit Allah au sujet de l'invocation (du'â') dans la sourate Ghâfir ?",
             ["« Invoquez-Moi, Je vous répondrai »", "« N'invoquez que la nuit »", "« Invoquez les anges »", "« Le du'â' est réservé aux prophètes »"], 0,
             "« Votre Seigneur a dit : Invoquez-Moi, Je vous répondrai » (40:60).",
             "Coran 40:60"),
        en=L("What does Allah say about supplication (du'a) in Surah Ghafir?",
             ["\"Call upon Me; I will respond to you\"", "\"Only call at night\"", "\"Call upon the angels\"", "\"Du'a is for prophets only\""], 0,
             "\"Your Lord says: Call upon Me; I will respond to you\" (40:60).",
             "Qur'an 40:60"),
        ar=L("ماذا قال الله عن الدعاء في سورة غافر؟",
             ["«ادعوني أستجب لكم»", "«لا تدعوا إلا ليلًا»", "«ادعوا الملائكة»", "«الدعاء للأنبياء فقط»"], 0,
             "«وقال ربكم ادعوني أستجب لكم» (40:60).",
             "القرآن 40:60"))

    add("faith_040", "faith", "easy", "quran", Q, "13:28", False,
        fr=L("Par quoi, selon le Coran, les cœurs trouvent-ils la quiétude ?",
             ["Par le rappel d'Allah (dhikr)", "Par l'argent", "Par le sommeil", "Par les voyages"], 0,
             "« N'est-ce pas par le rappel d'Allah que les cœurs se tranquillisent ? » (13:28).",
             "Coran 13:28"),
        en=L("By what, according to the Qur'an, do hearts find rest?",
             ["By the remembrance of Allah (dhikr)", "By money", "By sleep", "By travel"], 0,
             "\"Is it not by the remembrance of Allah that hearts find rest?\" (13:28).",
             "Qur'an 13:28"),
        ar=L("بماذا تطمئن القلوب بحسب القرآن؟",
             ["بذكر الله", "بالمال", "بالنوم", "بالأسفار"], 0,
             "«ألا بذكر الله تطمئن القلوب» (13:28).",
             "القرآن 13:28"))

    add("faith_041", "faith", "easy", "creed", C, WP + " (the five daily prayers)", False,
        fr=L("Quelle est la première prière obligatoire de la journée ?",
             ["Al-Fajr (l'aube)", "Adh-Dhuhr (midi)", "Al-'Asr (après-midi)", "Al-'Ishâ' (nuit)"], 0,
             "Les cinq prières sont, dans l'ordre : Fajr, Dhuhr, 'Asr, Maghrib et 'Ishâ'.",
             "Pratique établie, unanime"),
        en=L("What is the first obligatory prayer of the day?",
             ["Al-Fajr (dawn)", "Adh-Dhuhr (noon)", "Al-'Asr (afternoon)", "Al-'Isha' (night)"], 0,
             "The five prayers are, in order: Fajr, Dhuhr, 'Asr, Maghrib and 'Isha'.",
             "Established, unanimous practice"),
        ar=L("ما أول صلاة مفروضة في اليوم؟",
             ["الفجر", "الظهر", "العصر", "العشاء"], 0,
             "الصلوات الخمس بالترتيب: الفجر والظهر والعصر والمغرب والعشاء.",
             "عمل مستقر بالإجماع"))

    add("faith_042", "faith", "easy", "creed", C, WP + " (Fajr: two rak'ahs)", False,
        fr=L("Combien de rak'a compte la prière obligatoire du Fajr ?",
             ["Deux", "Trois", "Quatre", "Une"], 0,
             "Le Fajr compte deux rak'a ; le Maghrib trois ; Dhuhr, 'Asr et 'Ishâ' quatre chacune.",
             "Pratique établie, unanime"),
        en=L("How many rak'ahs are there in the obligatory Fajr prayer?",
             ["Two", "Three", "Four", "One"], 0,
             "Fajr has two rak'ahs; Maghrib three; Dhuhr, 'Asr and 'Isha' four each.",
             "Established, unanimous practice"),
        ar=L("كم ركعة في صلاة الفجر المفروضة؟",
             ["ركعتان", "ثلاث", "أربع", "ركعة واحدة"], 0,
             "الفجر ركعتان، والمغرب ثلاث، والظهر والعصر والعشاء أربع ركعات لكل منها.",
             "عمل مستقر بالإجماع"))

    add("faith_043", "faith", "medium", "creed", C, WP + " (Maghrib: three rak'ahs)", False,
        fr=L("Quelle prière obligatoire compte trois rak'a ?",
             ["Al-Maghrib", "Al-Fajr", "Adh-Dhuhr", "Al-'Ishâ'"], 0,
             "Le Maghrib, juste après le coucher du soleil, est la seule prière obligatoire de trois rak'a.",
             "Pratique établie, unanime"),
        en=L("Which obligatory prayer has three rak'ahs?",
             ["Al-Maghrib", "Al-Fajr", "Adh-Dhuhr", "Al-'Isha'"], 0,
             "Maghrib, just after sunset, is the only obligatory prayer with three rak'ahs.",
             "Established, unanimous practice"),
        ar=L("أي صلاة مفروضة عدد ركعاتها ثلاث؟",
             ["المغرب", "الفجر", "الظهر", "العشاء"], 0,
             "المغرب، بعد غروب الشمس مباشرة، هي الصلاة المفروضة الوحيدة ذات الثلاث ركعات.",
             "عمل مستقر بالإجماع"))

    add("faith_044", "faith", "easy", "creed", C, WT + " (adhan / mu'adhdhin)", False,
        fr=L("Comment appelle-t-on l'appel à la prière lancé depuis la mosquée ?",
             ["L'adhân", "La khutba", "Le tasbîh", "La talbiya"], 0,
             "L'adhân est lancé par le muezzin (mu'adhdhin) avant chacune des cinq prières.",
             "Terminologie établie"),
        en=L("What is the call to prayer made from the mosque called?",
             ["The adhan", "The khutba", "The tasbih", "The talbiya"], 0,
             "The adhan is called by the muezzin (mu'adhdhin) before each of the five prayers.",
             "Established terminology"),
        ar=L("ماذا يُسمّى النداء إلى الصلاة الذي يُرفع من المسجد؟",
             ["الأذان", "الخطبة", "التسبيح", "التلبية"], 0,
             "يرفع المؤذن الأذان قبل كل صلاة من الصلوات الخمس.",
             "مصطلح مستقر"))

    add("faith_045", "faith", "medium", "quran", Q, "5:6", False,
        fr=L("Selon le verset des ablutions, jusqu'où faut-il laver les bras ?",
             ["Jusqu'aux coudes", "Jusqu'aux poignets", "Jusqu'aux épaules", "Seulement les mains"], 0,
             "« Lavez vos visages et vos mains jusqu'aux coudes, passez les mains mouillées sur vos têtes, et lavez vos pieds jusqu'aux chevilles » (5:6).",
             "Coran 5:6"),
        en=L("According to the verse of ablution, up to where should the arms be washed?",
             ["Up to the elbows", "Up to the wrists", "Up to the shoulders", "Only the hands"], 0,
             "\"Wash your faces and your hands up to the elbows, wipe your heads, and wash your feet up to the ankles\" (5:6).",
             "Qur'an 5:6"),
        ar=L("بحسب آية الوضوء، إلى أين تُغسل اليدان؟",
             ["إلى المرفقين", "إلى الرسغين", "إلى الكتفين", "الكفان فقط"], 0,
             "«فاغسلوا وجوهكم وأيديكم إلى المرافق وامسحوا برؤوسكم وأرجلكم إلى الكعبين» (5:6).",
             "القرآن 5:6"))

    add("faith_046", "faith", "hard", "quran", Q, "5:6", False,
        fr=L("Que permet le Coran quand on ne trouve pas d'eau pour se purifier avant la prière ?",
             ["Le tayammum avec de la terre propre", "Prier sans purification", "Reporter la prière au lendemain", "Se laver avec du sable mouillé"], 0,
             "« Si vous ne trouvez pas d'eau, recourez à une terre pure et passez-en sur vos visages et vos mains » (5:6).",
             "Coran 5:6"),
        en=L("What does the Qur'an allow when no water is found for purification before prayer?",
             ["Tayammum with clean earth", "Praying without purification", "Postponing the prayer to the next day", "Washing with wet sand"], 0,
             "\"If you find no water, then seek clean earth and wipe your faces and hands with it\" (5:6).",
             "Qur'an 5:6"),
        ar=L("ماذا أباح القرآن لمن لم يجد ماء للطهارة قبل الصلاة؟",
             ["التيمم بصعيد طيب", "الصلاة بلا طهارة", "تأجيل الصلاة إلى الغد", "الغسل بالرمل المبلل"], 0,
             "«فلم تجدوا ماء فتيمموا صعيدًا طيبًا فامسحوا بوجوهكم وأيديكم منه» (5:6).",
             "القرآن 5:6"))

    add("faith_047", "faith", "easy", "creed", C, WT + " (khutba)", False,
        fr=L("Comment appelle-t-on le sermon prononcé par l'imam avant la prière du vendredi ?",
             ["La khutba", "L'adhân", "L'iqâma", "Le takbîr"], 0,
             "La khutba du vendredi est prononcée en deux parties depuis le minbar, avant la prière.",
             "Terminologie établie"),
        en=L("What is the sermon delivered by the imam before the Friday prayer called?",
             ["The khutba", "The adhan", "The iqama", "The takbir"], 0,
             "The Friday khutba is delivered in two parts from the minbar, before the prayer.",
             "Established terminology"),
        ar=L("ماذا تُسمّى الموعظة التي يلقيها الإمام قبل صلاة الجمعة؟",
             ["الخطبة", "الأذان", "الإقامة", "التكبير"], 0,
             "تُلقى خطبة الجمعة على جزأين من على المنبر قبل الصلاة.",
             "مصطلح مستقر"))

    add("faith_048", "faith", "medium", "creed", C, WP + " (zakat on savings: 2.5%)", False,
        fr=L("Quelle part de son épargne, gardée une année entière, le musulman verse-t-il en zakât ?",
             ["2,5 %", "10 %", "25 %", "1 %"], 0,
             "La zakât sur l'argent épargné est du quart du dixième, soit 2,5 %, lorsqu'il dépasse le seuil (nisâb) pendant une année lunaire.",
             "Pratique établie, unanime"),
        en=L("What share of savings held for a full year does a Muslim give as zakat?",
             ["2.5%", "10%", "25%", "1%"], 0,
             "Zakat on saved money is a quarter of a tenth, 2.5%, once it exceeds the threshold (nisab) for a lunar year.",
             "Established, unanimous practice"),
        ar=L("كم يُخرج المسلم زكاةً من ماله المدّخر إذا حال عليه الحول؟",
             ["2.5%", "10%", "25%", "1%"], 0,
             "زكاة المال المدّخر ربع العشر، أي 2.5%، إذا بلغ النصاب وحال عليه الحول.",
             "عمل مستقر بالإجماع"))

    add("faith_049", "faith", "medium", "hadithBukhari", B, "1503", False,
        fr=L("Quelle aumône particulière est due à la fin du Ramadan, avant la prière de l'Aïd ?",
             ["La zakât al-fitr", "La zakât sur l'or", "Le khums", "La kaffâra"], 0,
             "Le Prophète ﷺ a rendu obligatoire la zakât al-fitr, un sâ' de dattes ou d'orge, pour chaque musulman, petit ou grand.",
             "Sahîh al-Bukhârî, 1503"),
        en=L("Which particular charity is due at the end of Ramadan, before the Eid prayer?",
             ["Zakat al-fitr", "Zakat on gold", "The khums", "The kaffara"], 0,
             "The Prophet ﷺ made zakat al-fitr obligatory, a sa' of dates or barley, for every Muslim, young or old.",
             "Sahih al-Bukhari, 1503"),
        ar=L("ما الصدقة الخاصة الواجبة في آخر رمضان قبل صلاة العيد؟",
             ["زكاة الفطر", "زكاة الذهب", "الخمس", "الكفارة"], 0,
             "فرض النبي ﷺ زكاة الفطر صاعًا من تمر أو صاعًا من شعير على كل مسلم، صغيرًا أو كبيرًا.",
             "صحيح البخاري، 1503"))

    add("faith_050", "faith", "easy", "quran", Q, "2:187", False,
        fr=L("Selon le Coran, de quel moment à quel moment dure le jeûne quotidien de Ramadan ?",
             ["De l'aube jusqu'à la nuit", "De midi jusqu'au soir", "Du lever du soleil à midi", "Toute la journée et toute la nuit"], 0,
             "« Mangez et buvez jusqu'à ce que se distingue pour vous le fil blanc de l'aube du fil noir de la nuit, puis accomplissez le jeûne jusqu'à la nuit » (2:187).",
             "Coran 2:187"),
        en=L("According to the Qur'an, from when until when does the daily fast of Ramadan last?",
             ["From dawn until nightfall", "From noon until evening", "From sunrise until noon", "All day and all night"], 0,
             "\"Eat and drink until the white thread of dawn becomes distinct from the black thread, then complete the fast until night\" (2:187).",
             "Qur'an 2:187"),
        ar=L("بحسب القرآن، من متى إلى متى يستمر صوم اليوم في رمضان؟",
             ["من الفجر إلى الليل", "من الظهر إلى المساء", "من شروق الشمس إلى الظهر", "طوال النهار والليل"], 0,
             "«وكلوا واشربوا حتى يتبين لكم الخيط الأبيض من الخيط الأسود من الفجر ثم أتموا الصيام إلى الليل» (2:187).",
             "القرآن 2:187"))

    add("faith_051", "faith", "easy", "hadithBukhari", B, "1923", False,
        fr=L("Comment appelle-t-on le repas pris avant l'aube par celui qui va jeûner ?",
             ["Le suhûr", "L'iftâr", "Le walîma", "Le 'aqîqa"], 0,
             "Le Prophète ﷺ dit : « Prenez le suhûr, car il y a une bénédiction dans le suhûr. »",
             "Sahîh al-Bukhârî, 1923"),
        en=L("What is the meal eaten before dawn by the one who is going to fast called?",
             ["The suhur", "The iftar", "The walima", "The 'aqiqa"], 0,
             "The Prophet ﷺ said: \"Take the suhur, for there is blessing in the suhur.\"",
             "Sahih al-Bukhari, 1923"),
        ar=L("ماذا تُسمّى وجبة ما قبل الفجر لمن سيصوم؟",
             ["السحور", "الإفطار", "الوليمة", "العقيقة"], 0,
             "قال النبي ﷺ: «تسحّروا فإن في السحور بركة».",
             "صحيح البخاري، 1923"))

    add("faith_052", "faith", "easy", "creed", C, WT + " (iftar)", False,
        fr=L("Comment appelle-t-on le repas qui rompt le jeûne au coucher du soleil ?",
             ["L'iftâr", "Le suhûr", "Le tarâwîh", "Le tahajjud"], 0,
             "L'iftâr rompt le jeûne dès le coucher du soleil, à l'heure de la prière du Maghrib.",
             "Terminologie établie"),
        en=L("What is the meal that breaks the fast at sunset called?",
             ["The iftar", "The suhur", "The tarawih", "The tahajjud"], 0,
             "The iftar breaks the fast as soon as the sun sets, at the time of the Maghrib prayer.",
             "Established terminology"),
        ar=L("ماذا تُسمّى الوجبة التي يُفطر عليها الصائم عند غروب الشمس؟",
             ["الإفطار", "السحور", "التراويح", "التهجد"], 0,
             "يُفطر الصائم عند غروب الشمس وقت صلاة المغرب.",
             "مصطلح مستقر"))

    add("faith_053", "faith", "easy", "creed", C, WP + " (the two Eids)", False,
        fr=L("Combien de fêtes (Aïd) l'islam compte-t-il dans l'année ?",
             ["Deux : l'Aïd al-Fitr et l'Aïd al-Adhâ", "Une seule", "Quatre", "Douze"], 0,
             "L'Aïd al-Fitr clôt le mois de Ramadan ; l'Aïd al-Adhâ a lieu le 10 Dhû al-Hijja, pendant le pèlerinage.",
             "Pratique établie, unanime"),
        en=L("How many festivals (Eids) does Islam have in the year?",
             ["Two: Eid al-Fitr and Eid al-Adha", "Only one", "Four", "Twelve"], 0,
             "Eid al-Fitr closes the month of Ramadan; Eid al-Adha falls on 10 Dhul-Hijja, during the pilgrimage.",
             "Established, unanimous practice"),
        ar=L("كم عيدًا في الإسلام خلال السنة؟",
             ["عيدان: الفطر والأضحى", "عيد واحد", "أربعة", "اثنا عشر"], 0,
             "عيد الفطر يختم شهر رمضان، وعيد الأضحى في العاشر من ذي الحجة أيام الحج.",
             "عمل مستقر بالإجماع"))

    add("faith_054", "faith", "medium", "quran", Q, "37:107", False,
        fr=L("Quel événement l'Aïd al-Adhâ rappelle-t-il ?",
             ["Le sacrifice d'Ibrâhîm, racheté par un bélier", "La naissance du Prophète ﷺ", "La bataille de Badr", "La révélation du Coran"], 0,
             "Prêt à sacrifier son fils, Ibrâhîm vit celui-ci racheté : « Nous le rachetâmes par un sacrifice immense » (37:107).",
             "Coran 37:107"),
        en=L("Which event does Eid al-Adha commemorate?",
             ["Ibrahim's sacrifice, ransomed by a ram", "The birth of the Prophet ﷺ", "The battle of Badr", "The revelation of the Qur'an"], 0,
             "Ready to sacrifice his son, Ibrahim saw him ransomed: \"We ransomed him with a great sacrifice\" (37:107).",
             "Qur'an 37:107"),
        ar=L("أي حدث يذكّر به عيد الأضحى؟",
             ["ذبح إبراهيم الذي فُدي بكبش", "مولد النبي ﷺ", "غزوة بدر", "نزول القرآن"], 0,
             "لما استسلم إبراهيم لذبح ابنه فُدي الابن: «وفديناه بذبح عظيم» (37:107).",
             "القرآن 37:107"))

    add("faith_055", "faith", "easy", "creed", C, WP + " (hajj in Dhul-Hijja)", False,
        fr=L("Durant quel mois du calendrier islamique a lieu le pèlerinage (hajj) ?",
             ["Dhû al-Hijja", "Ramadan", "Muharram", "Rajab"], 0,
             "Le hajj se déroule du 8 au 13 Dhû al-Hijja, le douzième et dernier mois de l'année lunaire.",
             "Pratique établie, unanime"),
        en=L("In which month of the Islamic calendar does the pilgrimage (hajj) take place?",
             ["Dhul-Hijja", "Ramadan", "Muharram", "Rajab"], 0,
             "The hajj takes place from 8 to 13 Dhul-Hijja, the twelfth and last month of the lunar year.",
             "Established, unanimous practice"),
        ar=L("في أي شهر من التقويم الهجري يكون الحج؟",
             ["ذو الحجة", "رمضان", "محرم", "رجب"], 0,
             "يكون الحج من الثامن إلى الثالث عشر من ذي الحجة، الشهر الثاني عشر والأخير من السنة الهجرية.",
             "عمل مستقر بالإجماع"))

    add("faith_056", "faith", "hard", "creed", C, WP + " (day of 'Arafat: 9 Dhul-Hijja)", False,
        fr=L("Quel jour du mois de Dhû al-Hijja les pèlerins se tiennent-ils sur la plaine de 'Arafât ?",
             ["Le 9", "Le 1er", "Le 10", "Le 27"], 0,
             "La station à 'Arafât, le 9 Dhû al-Hijja, est le pilier central du hajj ; l'Aïd al-Adhâ suit le lendemain.",
             "Pratique établie, unanime"),
        en=L("On which day of Dhul-Hijja do pilgrims stand on the plain of 'Arafat?",
             ["The 9th", "The 1st", "The 10th", "The 27th"], 0,
             "Standing at 'Arafat on 9 Dhul-Hijja is the central pillar of the hajj; Eid al-Adha follows the next day.",
             "Established, unanimous practice"),
        ar=L("في أي يوم من ذي الحجة يقف الحجاج بعرفة؟",
             ["التاسع", "الأول", "العاشر", "السابع والعشرين"], 0,
             "الوقوف بعرفة في التاسع من ذي الحجة هو ركن الحج الأعظم، ويليه عيد الأضحى في اليوم التالي.",
             "عمل مستقر بالإجماع"))

    add("faith_057", "faith", "easy", "creed", C, WP + " (tawaf: seven circuits)", False,
        fr=L("Combien de tours autour de la Ka'ba compte un tawâf ?",
             ["Sept", "Trois", "Cinq", "Dix"], 0,
             "Le tawâf se fait en sept tours autour de la Ka'ba, dans le sens inverse des aiguilles d'une montre, en commençant à la Pierre noire.",
             "Pratique établie, unanime"),
        en=L("How many circuits around the Ka'ba make up a tawaf?",
             ["Seven", "Three", "Five", "Ten"], 0,
             "The tawaf is seven circuits around the Ka'ba, anticlockwise, starting at the Black Stone.",
             "Established, unanimous practice"),
        ar=L("كم شوطًا حول الكعبة في الطواف الواحد؟",
             ["سبعة", "ثلاثة", "خمسة", "عشرة"], 0,
             "الطواف سبعة أشواط حول الكعبة، تبدأ من الحجر الأسود والكعبة عن يسار الطائف.",
             "عمل مستقر بالإجماع"))

    add("faith_058", "faith", "hard", "creed", C, WP + " (sa'y: seven laps)", False,
        fr=L("Combien de trajets entre As-Safâ et Al-Marwa compte le sa'y ?",
             ["Sept", "Deux", "Quatre", "Douze"], 0,
             "Le sa'y rappelle la course de Hâjar cherchant de l'eau pour Ismâ'îl : sept trajets, de Safâ à Marwa puis retour, en comptant chaque sens.",
             "Pratique établie, unanime"),
        en=L("How many laps between As-Safa and Al-Marwa make up the sa'y?",
             ["Seven", "Two", "Four", "Twelve"], 0,
             "The sa'y recalls Hajar's search for water for Isma'il: seven laps, from Safa to Marwa and back, each direction counted.",
             "Established, unanimous practice"),
        ar=L("كم شوطًا بين الصفا والمروة في السعي؟",
             ["سبعة", "اثنان", "أربعة", "اثنا عشر"], 0,
             "يذكّر السعي بسعي هاجر بحثًا عن الماء لإسماعيل: سبعة أشواط من الصفا إلى المروة، يُعدّ كل اتجاه شوطًا.",
             "عمل مستقر بالإجماع"))

    add("faith_059", "faith", "medium", "creed", C, WT + " (ihram)", False,
        fr=L("Comment appelle-t-on l'état de sacralisation dans lequel entre le pèlerin, avec ses deux pièces d'étoffe blanche ?",
             ["L'ihrâm", "Le tawâf", "Le wuqûf", "La talbiya"], 0,
             "En ihrâm, l'homme porte deux pièces de tissu non cousues et le pèlerin s'abstient de parfum, de chasse et de disputes.",
             "Terminologie établie"),
        en=L("What is the state of consecration the pilgrim enters, with its two white cloths, called?",
             ["Ihram", "Tawaf", "Wuquf", "Talbiya"], 0,
             "In ihram, men wear two unsewn cloths and the pilgrim refrains from perfume, hunting and quarrelling.",
             "Established terminology"),
        ar=L("ماذا تُسمّى حالة التحريم التي يدخل فيها الحاج بإزاره وردائه الأبيضين؟",
             ["الإحرام", "الطواف", "الوقوف", "التلبية"], 0,
             "في الإحرام يلبس الرجل إزارًا ورداءً غير مخيطين، ويمتنع الحاج عن الطيب والصيد والجدال.",
             "مصطلح مستقر"))

    add("faith_060", "faith", "medium", "hadithBukhari", B, "1549", False,
        fr=L("Par quels mots commence la talbiya, que les pèlerins répètent en route vers La Mecque ?",
             ["« Labbayka Allâhumma labbayk » (Me voici, ô Allah, me voici)", "« Allâhu akbar »", "« Subhâna Allâh »", "« Al-hamdu li-Llâh »"], 0,
             "La talbiya du Prophète ﷺ était : « Labbayka Allâhumma labbayk, labbayka lâ sharîka laka labbayk… »",
             "Sahîh al-Bukhârî, 1549"),
        en=L("With which words does the talbiya, repeated by pilgrims on the way to Makkah, begin?",
             ["\"Labbayka Allahumma labbayk\" (Here I am, O Allah, here I am)", "\"Allahu akbar\"", "\"Subhana Allah\"", "\"Al-hamdu li-Llah\""], 0,
             "The Prophet's ﷺ talbiya was: \"Labbayka Allahumma labbayk, labbayka la sharika laka labbayk…\"",
             "Sahih al-Bukhari, 1549"),
        ar=L("بأي كلمات تبدأ التلبية التي يرددها الحجاج في طريقهم إلى مكة؟",
             ["«لبيك اللهم لبيك»", "«الله أكبر»", "«سبحان الله»", "«الحمد لله»"], 0,
             "كانت تلبية النبي ﷺ: «لبيك اللهم لبيك، لبيك لا شريك لك لبيك...».",
             "صحيح البخاري، 1549"))

    add("faith_061", "faith", "hard", "creed", C, WT + " (ramy al-jamarat at Mina)", False,
        fr=L("Que font les pèlerins à Minâ lorsqu'ils lancent des cailloux sur trois stèles ?",
             ["La lapidation des jamarât", "Le tawâf", "Le sa'y", "La station de 'Arafât"], 0,
             "Le ramy al-jamarât rappelle Ibrâhîm chassant Satan à coups de pierres ; il se fait à Minâ les jours de l'Aïd.",
             "Terminologie établie"),
        en=L("What do pilgrims do at Mina when they throw pebbles at three pillars?",
             ["The stoning of the jamarat", "The tawaf", "The sa'y", "The standing at 'Arafat"], 0,
             "The ramy al-jamarat recalls Ibrahim driving away Satan with stones; it is done at Mina during the days of Eid.",
             "Established terminology"),
        ar=L("ماذا يفعل الحجاج في منى حين يرمون الحصى على ثلاثة أعمدة؟",
             ["رمي الجمرات", "الطواف", "السعي", "الوقوف بعرفة"], 0,
             "رمي الجمرات يذكّر بطرد إبراهيم للشيطان بالحجارة، ويكون في منى أيام العيد.",
             "مصطلح مستقر"))

    add("faith_062", "faith", "medium", "creed", C, WT + " (al-Hajar al-Aswad)", False,
        fr=L("Où se trouve la Pierre noire (al-Hajar al-Aswad) ?",
             ["Dans un angle de la Ka'ba", "Sur le mont 'Arafât", "À Médine", "Au sommet du mont Hirâ'"], 0,
             "Enchâssée dans l'angle est de la Ka'ba, elle marque le point de départ de chaque tour du tawâf.",
             "Terminologie établie"),
        en=L("Where is the Black Stone (al-Hajar al-Aswad)?",
             ["In a corner of the Ka'ba", "On Mount 'Arafat", "In Madinah", "At the top of Mount Hira'"], 0,
             "Set into the eastern corner of the Ka'ba, it marks the starting point of every circuit of the tawaf.",
             "Established terminology"),
        ar=L("أين يوجد الحجر الأسود؟",
             ["في ركن من أركان الكعبة", "على جبل عرفات", "في المدينة", "على قمة جبل حراء"], 0,
             "الحجر الأسود مثبّت في الركن الشرقي للكعبة، ومنه يبدأ كل شوط من الطواف.",
             "مصطلح مستقر"))

    add("faith_063", "faith", "medium", "creed", C, WT + " (kiswa)", False,
        fr=L("Comment appelle-t-on la grande étoffe noire qui recouvre la Ka'ba ?",
             ["La kiswa", "Le hijâb", "Le minbar", "Le mihrâb"], 0,
             "La kiswa, brodée de versets en fil d'or, est remplacée chaque année pendant le pèlerinage.",
             "Terminologie établie"),
        en=L("What is the great black cloth that covers the Ka'ba called?",
             ["The kiswa", "The hijab", "The minbar", "The mihrab"], 0,
             "The kiswa, embroidered with verses in gold thread, is replaced every year during the pilgrimage.",
             "Established terminology"),
        ar=L("ماذا يُسمّى الثوب الأسود الكبير الذي يغطي الكعبة؟",
             ["الكسوة", "الحجاب", "المنبر", "المحراب"], 0,
             "الكسوة مطرّزة بآيات من خيوط الذهب، وتُبدَّل كل عام أيام الحج.",
             "مصطلح مستقر"))

    add("faith_064", "faith", "easy", "creed", C, WT + " ('umra)", False,
        fr=L("Comment appelle-t-on la « petite » visite pieuse à La Mecque, que l'on peut faire à tout moment de l'année ?",
             ["La 'umra", "Le hajj", "La hijra", "La ziyâra"], 0,
             "La 'umra comprend l'ihrâm, le tawâf et le sa'y ; contrairement au hajj, elle n'est pas liée à un mois précis.",
             "Terminologie établie"),
        en=L("What is the \"lesser\" pilgrimage to Makkah, which can be done at any time of the year, called?",
             ["The 'umra", "The hajj", "The hijra", "The ziyara"], 0,
             "The 'umra consists of ihram, tawaf and sa'y; unlike the hajj, it is not tied to a specific month.",
             "Established terminology"),
        ar=L("ماذا تُسمّى الزيارة الصغرى لمكة التي يمكن أداؤها في أي وقت من السنة؟",
             ["العمرة", "الحج", "الهجرة", "الزيارة"], 0,
             "العمرة إحرام وطواف وسعي، وليست مرتبطة بشهر معين بخلاف الحج.",
             "مصطلح مستقر"))

    add("faith_065", "faith", "easy", "quran", Q, "59:24", False,
        fr=L("Que signifie le nom d'Allah « Al-Khâliq » ?",
             ["Le Créateur", "Le Pardonneur", "Le Pourvoyeur", "Le Roi"], 0,
             "« C'est Lui Allah, le Créateur (al-Khâliq), Celui qui donne un commencement à toute chose, le Formateur » (59:24).",
             "Coran 59:24"),
        en=L("What does the name of Allah \"Al-Khaliq\" mean?",
             ["The Creator", "The Forgiver", "The Provider", "The King"], 0,
             "\"He is Allah, the Creator (al-Khaliq), the Originator, the Fashioner\" (59:24).",
             "Qur'an 59:24"),
        ar=L("ما معنى اسم الله «الخالق»؟",
             ["الذي أوجد الخلق من العدم", "الغفور", "الرزاق", "الملك"], 0,
             "«هو الله الخالق البارئ المصور» (59:24).",
             "القرآن 59:24"))

    add("faith_066", "faith", "easy", "quran", Q, "39:53", False,
        fr=L("Que signifie le nom d'Allah « Al-Ghafûr » ?",
             ["Celui qui pardonne beaucoup", "Le Créateur", "Le Tout-Puissant", "Le Généreux"], 0,
             "« Ne désespérez pas de la miséricorde d'Allah… c'est Lui le Pardonneur (al-Ghafûr), le Miséricordieux » (39:53).",
             "Coran 39:53"),
        en=L("What does the name of Allah \"Al-Ghafur\" mean?",
             ["The All-Forgiving", "The Creator", "The Almighty", "The Generous"], 0,
             "\"Do not despair of the mercy of Allah… He is the Forgiving (al-Ghafur), the Merciful\" (39:53).",
             "Qur'an 39:53"),
        ar=L("ما معنى اسم الله «الغفور»؟",
             ["كثير المغفرة", "الخالق", "القدير", "الكريم"], 0,
             "«لا تقنطوا من رحمة الله... إنه هو الغفور الرحيم» (39:53).",
             "القرآن 39:53"))

    add("faith_067", "faith", "easy", "quran", Q, "17:1", False,
        fr=L("Que signifient les deux noms d'Allah « As-Samî' » et « Al-Basîr » ?",
             ["Celui qui entend tout et Celui qui voit tout", "Le Roi et le Juge", "Le Créateur et le Pourvoyeur", "Le Premier et le Dernier"], 0,
             "Le verset du Voyage nocturne se termine ainsi : « C'est Lui l'Audient (as-Samî'), le Clairvoyant (al-Basîr) » (17:1).",
             "Coran 17:1"),
        en=L("What do the two names of Allah \"As-Sami'\" and \"Al-Basir\" mean?",
             ["The All-Hearing and the All-Seeing", "The King and the Judge", "The Creator and the Provider", "The First and the Last"], 0,
             "The verse of the Night Journey ends: \"He is the Hearing (as-Sami'), the Seeing (al-Basir)\" (17:1).",
             "Qur'an 17:1"),
        ar=L("ما معنى اسمي الله «السميع» و«البصير»؟",
             ["الذي يسمع كل شيء ويرى كل شيء", "الملك والحكم", "الخالق والرزاق", "الأول والآخر"], 0,
             "تُختم آية الإسراء بقوله: «إنه هو السميع البصير» (17:1).",
             "القرآن 17:1"))

    add("faith_068", "faith", "hard", "quran", Q, "112:2", False,
        fr=L("Que signifie « As-Samad », nom d'Allah cité dans la sourate Al-Ikhlâs ?",
             ["Celui dont tout dépend et qui ne dépend de rien", "Celui qui pardonne", "Celui qui entend", "Celui qui crée"], 0,
             "« Allâhu as-Samad » (112:2) : le Maître absolu vers qui toutes les créatures se tournent pour leurs besoins.",
             "Coran 112:2"),
        en=L("What does \"As-Samad\", a name of Allah in Surah Al-Ikhlas, mean?",
             ["The One on whom all depend and who depends on none", "The One who forgives", "The One who hears", "The One who creates"], 0,
             "\"Allahu as-Samad\" (112:2): the absolute Master to whom all creatures turn for their needs.",
             "Qur'an 112:2"),
        ar=L("ما معنى «الصمد» اسم الله في سورة الإخلاص؟",
             ["الذي يُقصد في الحوائج ولا يحتاج إلى أحد", "الذي يغفر", "الذي يسمع", "الذي يخلق"], 0,
             "«الله الصمد» (112:2): السيد الذي تقصده الخلائق كلها في حوائجها.",
             "القرآن 112:2"))

    add("faith_069", "faith", "medium", "quran", Q, "2:255", False,
        fr=L("Quels deux noms d'Allah ouvrent le verset du Trône, juste après « Allah, nulle divinité en dehors de Lui » ?",
             ["Al-Hayy et Al-Qayyûm (le Vivant, Celui qui subsiste par Lui-même)", "Ar-Rahmân et Ar-Rahîm", "Al-Malik et Al-Quddûs", "Al-'Azîz et Al-Hakîm"], 0,
             "« Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même » (2:255).",
             "Coran 2:255"),
        en=L("Which two names of Allah open the Throne Verse, right after \"Allah, there is no god but Him\"?",
             ["Al-Hayy and Al-Qayyum (the Ever-Living, the Self-Sustaining)", "Ar-Rahman and Ar-Rahim", "Al-Malik and Al-Quddus", "Al-'Aziz and Al-Hakim"], 0,
             "\"Allah! There is no god but Him, the Ever-Living, the Self-Sustaining\" (2:255).",
             "Qur'an 2:255"),
        ar=L("ما اسما الله اللذان تُفتتح بهما آية الكرسي بعد «الله لا إله إلا هو»؟",
             ["الحي القيوم", "الرحمن الرحيم", "الملك القدوس", "العزيز الحكيم"], 0,
             "«الله لا إله إلا هو الحي القيوم» (2:255).",
             "القرآن 2:255"))

    add("faith_070", "faith", "medium", "quran", Q, "51:58", False,
        fr=L("Que signifie le nom d'Allah « Ar-Razzâq » ?",
             ["Le Grand Pourvoyeur", "Le Pardonneur", "Le Juste", "Le Doux"], 0,
             "« En vérité, c'est Allah qui est le Grand Pourvoyeur (ar-Razzâq), le Détenteur de la force, l'Inébranlable » (51:58).",
             "Coran 51:58"),
        en=L("What does the name of Allah \"Ar-Razzaq\" mean?",
             ["The Great Provider", "The Forgiver", "The Just", "The Gentle"], 0,
             "\"Indeed, it is Allah who is the Provider (ar-Razzaq), the Possessor of strength, the Firm\" (51:58).",
             "Qur'an 51:58"),
        ar=L("ما معنى اسم الله «الرزاق»؟",
             ["كثير الرزق لخلقه", "الغفور", "العدل", "اللطيف"], 0,
             "«إن الله هو الرزاق ذو القوة المتين» (51:58).",
             "القرآن 51:58"))
