"""Prophets — part B (prophets_091 … prophets_150)."""


def register(add, L):
    Q = "Quran"

    add("prophets_091", "prophets", "medium", "quran", Q, "34:10", False,
        fr=L("Quel métal Allah a-t-Il rendu malléable pour Dâwûd ?",
             ["Le fer", "L'or", "Le cuivre", "L'argent"], 0,
             "« Nous lui rendîmes le fer malléable. »",
             "Coran — Sourate Saba, 34:10"),
        en=L("Which metal did Allah make soft for Dawud?",
             ["Iron", "Gold", "Copper", "Silver"], 0,
             "\"And We made iron pliable for him.\"",
             "Quran — Surah Saba, 34:10"),
        ar=L("أي معدن ألان الله لداوود؟",
             ["الحديد", "الذهب", "النحاس", "الفضة"], 0,
             "﴿وألنّا له الحديد﴾.",
             "القرآن — سورة سبأ، 34:10"))

    add("prophets_092", "prophets", "medium", "quran", Q, "21:80", False,
        fr=L("Qu'Allah enseigna-t-Il à Dâwûd de fabriquer pour protéger les hommes au combat ?",
             ["Des cottes de mailles", "Des épées", "Des boucliers en bois", "Des tours"], 0,
             "« Nous lui apprîmes la fabrication des cottes de mailles pour vous protéger. »",
             "Coran — Sourate Al-Anbiyâ, 21:80"),
        en=L("What did Allah teach Dawud to make, to protect people in battle?",
             ["Coats of mail", "Swords", "Wooden shields", "Towers"], 0,
             "\"We taught him the fashioning of coats of armour to protect you.\"",
             "Quran — Surah Al-Anbiya, 21:80"),
        ar=L("ماذا علّم الله داوود أن يصنع لحماية الناس في القتال؟",
             ["الدروع", "السيوف", "التروس الخشبية", "الأبراج"], 0,
             "﴿وعلّمناه صنعة لبوس لكم لتحصنكم من بأسكم﴾.",
             "القرآن — سورة الأنبياء، 21:80"))

    add("prophets_093", "prophets", "easy", "quran", Q, "2:251", False,
        fr=L("Quel géant Dâwûd tua-t-il au combat, selon le Coran ?",
             ["Jâlût", "Fir'awn", "Hâmân", "Nimrod"], 0,
             "« Et Dâwûd tua Jâlût, et Allah lui donna la royauté et la sagesse. »",
             "Coran — Sourate Al-Baqara, 2:251"),
        en=L("Which giant did Dawud kill in battle, according to the Quran?",
             ["Jalut (Goliath)", "Pharaoh", "Haman", "Nimrod"], 0,
             "\"And Dawud killed Jalut, and Allah gave him the kingship and wisdom.\"",
             "Quran — Surah Al-Baqara, 2:251"),
        ar=L("من قتل داوود في المعركة بحسب القرآن؟",
             ["جالوت", "فرعون", "هامان", "النمرود"], 0,
             "﴿وقتل داوود جالوت وآتاه الله الملك والحكمة﴾.",
             "القرآن — سورة البقرة، 2:251"))

    add("prophets_094", "prophets", "hard", "quran", Q, "2:249", False,
        fr=L("Par quoi le roi Tâlût mit-il son armée à l'épreuve avant d'affronter Jâlût ?",
             ["Une rivière : ne pas en boire, sauf une gorgée dans la main", "Une course", "Un jeûne de trois jours", "Une montagne à gravir"], 0,
             "« Allah va vous éprouver par une rivière : celui qui en boit n'est pas des miens, sauf une gorgée dans le creux de la main. »",
             "Coran — Sourate Al-Baqara, 2:249"),
        en=L("How did King Talut test his army before facing Jalut?",
             ["A river: not to drink from it, except a handful", "A race", "A three-day fast", "A mountain to climb"], 0,
             "\"Allah will test you with a river: whoever drinks from it is not of me, except one who scoops a handful.\"",
             "Quran — Surah Al-Baqara, 2:249"),
        ar=L("بماذا ابتلى الملك طالوت جنده قبل لقاء جالوت؟",
             ["بنهر: من شرب منه فليس منه إلا غرفة بيده", "بسباق", "بصيام ثلاثة أيام", "بجبل يصعدونه"], 0,
             "﴿إن الله مبتليكم بنهر فمن شرب منه فليس مني… إلا من اغترف غرفة بيده﴾.",
             "القرآن — سورة البقرة، 2:249"))

    add("prophets_095", "prophets", "medium", "quran", Q, "21:79", False,
        fr=L("Qu'Allah soumit-Il à Dâwûd pour glorifier avec lui ?",
             ["Les montagnes et les oiseaux", "Les vents", "Les djinns", "Les poissons"], 0,
             "« Nous soumîmes les montagnes et les oiseaux à glorifier avec Dâwûd. »",
             "Coran — Sourate Al-Anbiyâ, 21:79"),
        en=L("What did Allah make glorify Him together with Dawud?",
             ["The mountains and the birds", "The winds", "The jinn", "The fish"], 0,
             "\"And We subjected the mountains to exalt Us, along with Dawud, and the birds.\"",
             "Quran — Surah Al-Anbiya, 21:79"),
        ar=L("ماذا سخّر الله ليسبّح مع داوود؟",
             ["الجبال والطير", "الرياح", "الجن", "الأسماك"], 0,
             "﴿وسخّرنا مع داوود الجبال يسبّحن والطير﴾.",
             "القرآن — سورة الأنبياء، 21:79"))

    add("prophets_096", "prophets", "medium", "quran", Q, "21:81", False,
        fr=L("Quel élément Allah soumit-Il à Sulaymân pour le porter là où il voulait ?",
             ["Le vent", "Le feu", "La pluie", "La mer"], 0,
             "« À Sulaymân, le vent impétueux, qui soufflait sur son ordre vers la terre bénie. »",
             "Coran — Sourate Al-Anbiyâ, 21:81"),
        en=L("Which element did Allah subject to Sulayman to carry him wherever he wished?",
             ["The wind", "Fire", "Rain", "The sea"], 0,
             "\"And to Sulayman, the wind, blowing forcefully by his command towards the blessed land.\"",
             "Quran — Surah Al-Anbiya, 21:81"),
        ar=L("ماذا سخّر الله لسليمان ليحمله حيث يشاء؟",
             ["الريح", "النار", "المطر", "البحر"], 0,
             "﴿ولسليمان الريح عاصفة تجري بأمره إلى الأرض التي باركنا فيها﴾.",
             "القرآن — سورة الأنبياء، 21:81"))

    add("prophets_097", "prophets", "easy", "quran", Q, "27:20-22", False,
        fr=L("Quel oiseau apporta à Sulaymân des nouvelles du royaume de Saba ?",
             ["La huppe", "L'aigle", "La colombe", "Le corbeau"], 0,
             "La huppe (hudhud) revint et dit : « J'ai appris une chose que tu ne sais pas, et je t'apporte de Saba une nouvelle sûre. »",
             "Coran — Sourate An-Naml, 27:20-22"),
        en=L("Which bird brought Sulayman news of the kingdom of Saba?",
             ["The hoopoe", "The eagle", "The dove", "The crow"], 0,
             "The hoopoe returned and said: \"I have learned something you do not know, and I bring you sure news from Saba.\"",
             "Quran — Surah An-Naml, 27:20-22"),
        ar=L("أي طائر جاء سليمان بخبر مملكة سبأ؟",
             ["الهدهد", "النسر", "الحمامة", "الغراب"], 0,
             "جاء الهدهد فقال: ﴿أحطتُ بما لم تحط به وجئتك من سبأ بنبإ يقين﴾.",
             "القرآن — سورة النمل، 27:20-22"))

    add("prophets_098", "prophets", "easy", "quran", Q, "27:18", False,
        fr=L("Quelle petite créature avertit ses semblables de rentrer, à l'approche de l'armée de Sulaymân ?",
             ["Une fourmi", "Une abeille", "Une souris", "Une araignée"], 0,
             "Une fourmi dit : « Ô fourmis, entrez dans vos demeures, que Sulaymân et ses troupes ne vous écrasent pas sans s'en apercevoir. »",
             "Coran — Sourate An-Naml, 27:18"),
        en=L("Which small creature warned its kind to go inside as Sulayman's army approached?",
             ["An ant", "A bee", "A mouse", "A spider"], 0,
             "An ant said: \"O ants, enter your dwellings, lest Sulayman and his soldiers crush you unaware.\"",
             "Quran — Surah An-Naml, 27:18"),
        ar=L("أي مخلوق صغير حذّر بني جنسه بالدخول إلى مساكنهم عند اقتراب جنود سليمان؟",
             ["نملة", "نحلة", "فأرة", "عنكبوت"], 0,
             "﴿قالت نملة يا أيها النمل ادخلوا مساكنكم لا يحطمنّكم سليمان وجنوده وهم لا يشعرون﴾.",
             "القرآن — سورة النمل، 27:18"))

    add("prophets_099", "prophets", "hard", "quran", Q, "27:40", False,
        fr=L("En combien de temps le trône de la reine de Saba fut-il apporté à Sulaymân ?",
             ["Avant que son regard ne revienne à lui", "En un jour", "En sept jours", "En un mois"], 0,
             "Celui qui avait une science du Livre dit : « Je te l'apporterai avant que ton regard ne revienne à toi. »",
             "Coran — Sourate An-Naml, 27:40"),
        en=L("How quickly was the throne of the Queen of Saba brought to Sulayman?",
             ["Before his glance returned to him", "In a day", "In seven days", "In a month"], 0,
             "The one who had knowledge of the Book said: \"I will bring it to you before your glance returns to you.\"",
             "Quran — Surah An-Naml, 27:40"),
        ar=L("في كم من الوقت أُحضر عرش ملكة سبأ إلى سليمان؟",
             ["قبل أن يرتد إليه طرفه", "في يوم", "في سبعة أيام", "في شهر"], 0,
             "قال الذي عنده علم من الكتاب: ﴿أنا آتيك به قبل أن يرتد إليك طرفك﴾.",
             "القرآن — سورة النمل، 27:40"))

    add("prophets_100", "prophets", "hard", "quran", Q, "34:13", False,
        fr=L("Selon le Coran, que fabriquaient les djinns pour Sulaymân ?",
             ["Des sanctuaires, des statues et de grands bassins", "Des tapis volants", "Des navires", "Des montagnes"], 0,
             "« Ils lui faisaient ce qu'il voulait : sanctuaires, statues, bassins comme des réservoirs et marmites fixes. »",
             "Coran — Sourate Saba, 34:13"),
        en=L("According to the Quran, what did the jinn make for Sulayman?",
             ["Sanctuaries, statues and great basins", "Flying carpets", "Ships", "Mountains"], 0,
             "\"They made for him what he willed: elevated chambers, statues, bowls like reservoirs and fixed cauldrons.\"",
             "Quran — Surah Saba, 34:13"),
        ar=L("بحسب القرآن، ماذا كان الجن يصنعون لسليمان؟",
             ["محاريب وتماثيل وجفانًا كالجواب", "بُسطًا طائرة", "سفنًا", "جبالًا"], 0,
             "﴿يعملون له ما يشاء من محاريب وتماثيل وجفان كالجواب وقدور راسيات﴾.",
             "القرآن — سورة سبأ، 34:13"))

    add("prophets_101", "prophets", "hard", "quran", Q, "34:14", False,
        fr=L("Comment les djinns apprirent-ils la mort de Sulaymân ?",
             ["Une bête de la terre rongea son bâton et il tomba", "Un ange le leur annonça", "La huppe le leur dit", "Ils le virent mourir"], 0,
             "Seule la « bête de la terre » rongeant son bâton révéla sa mort ; les djinns comprirent qu'ils ne connaissaient pas l'invisible.",
             "Coran — Sourate Saba, 34:14"),
        en=L("How did the jinn learn of Sulayman's death?",
             ["A creature of the earth gnawed his staff and he fell", "An angel told them", "The hoopoe told them", "They saw him die"], 0,
             "Only the \"creature of the earth\" eating his staff revealed his death; the jinn realised they did not know the unseen.",
             "Quran — Surah Saba, 34:14"),
        ar=L("كيف علم الجن بموت سليمان؟",
             ["أكلت دابة الأرض منسأته فخرّ", "أخبرهم ملك", "أخبرهم الهدهد", "رأوه يموت"], 0,
             "﴿ما دلّهم على موته إلا دابة الأرض تأكل منسأته﴾ فتبيّنت الجن أنهم لا يعلمون الغيب.",
             "القرآن — سورة سبأ، 34:14"))

    add("prophets_102", "prophets", "hard", "quran", Q, "38:35", False,
        fr=L("Quelle prière particulière Sulaymân adressa-t-il à Allah ?",
             ["Un royaume que nul après lui ne posséderait", "Une longue vie", "La richesse de Qârûn", "Le pouvoir de voler"], 0,
             "« Seigneur, pardonne-moi et accorde-moi un royaume tel que nul après moi n'en aura de pareil. »",
             "Coran — Sourate Sâd, 38:35"),
        en=L("What particular prayer did Sulayman make to Allah?",
             ["A kingdom no one after him would have", "A long life", "The wealth of Qarun", "The power to fly"], 0,
             "\"My Lord, forgive me and grant me a kingdom such as will not belong to anyone after me.\"",
             "Quran — Surah Sad, 38:35"),
        ar=L("بماذا دعا سليمان ربه دعاءً خاصًا؟",
             ["ملكًا لا ينبغي لأحد من بعده", "عمرًا طويلًا", "مال قارون", "القدرة على الطيران"], 0,
             "﴿ربِّ اغفر لي وهب لي ملكًا لا ينبغي لأحد من بعدي﴾.",
             "القرآن — سورة ص، 38:35"))

    add("prophets_103", "prophets", "hard", "quran", Q, "38:42", False,
        fr=L("Qu'ordonna Allah à Ayyûb pour qu'il retrouve la santé ?",
             ["Frapper le sol du pied : une source fraîche jaillit", "Jeûner un mois", "Se baigner dans la mer", "Monter sur une montagne"], 0,
             "« Frappe du pied : voici une eau fraîche pour te laver et pour boire. »",
             "Coran — Sourate Sâd, 38:42"),
        en=L("What did Allah command Ayyub to do to recover his health?",
             ["Strike the ground with his foot: a cool spring gushed", "Fast for a month", "Bathe in the sea", "Climb a mountain"], 0,
             "\"Strike with your foot: here is a cool spring to wash with, and to drink.\"",
             "Quran — Surah Sad, 38:42"),
        ar=L("بماذا أمر الله أيوب ليشفى؟",
             ["أن يركض برجله فتنبع عين باردة", "أن يصوم شهرًا", "أن يغتسل في البحر", "أن يصعد جبلًا"], 0,
             "﴿اركض برجلك هذا مغتسل بارد وشراب﴾.",
             "القرآن — سورة ص، 38:42"))

    add("prophets_104", "prophets", "medium", "quran", Q, "21:87", False,
        fr=L("Quelle invocation Yûnus prononça-t-il dans les ténèbres du ventre du poisson ?",
             ["« Pas de divinité à part Toi ! Gloire à Toi, j'ai été parmi les injustes »", "« Seigneur, donne-moi un royaume »", "« Seigneur, envoie-moi de la pluie »", "« Seigneur, fais-moi voir Ta face »"], 0,
             "« Il appela dans les ténèbres : nulle divinité à part Toi ! Gloire à Toi, j'ai été du nombre des injustes. »",
             "Coran — Sourate Al-Anbiyâ, 21:87"),
        en=L("What supplication did Yunus make in the darkness of the fish's belly?",
             ["\"There is no god but You! Glory be to You, I have been among the wrongdoers\"", "\"My Lord, give me a kingdom\"", "\"My Lord, send me rain\"", "\"My Lord, let me see You\""], 0,
             "\"He called out in the darkness: there is no deity except You! Exalted are You; I have been of the wrongdoers.\"",
             "Quran — Surah Al-Anbiya, 21:87"),
        ar=L("بماذا نادى يونس في الظلمات في بطن الحوت؟",
             ["«لا إله إلا أنت سبحانك إني كنت من الظالمين»", "«ربِّ هب لي ملكًا»", "«ربِّ أنزل عليّ المطر»", "«ربِّ أرني أنظر إليك»"], 0,
             "﴿فنادى في الظلمات أن لا إله إلا أنت سبحانك إني كنت من الظالمين﴾.",
             "القرآن — سورة الأنبياء، 21:87"))

    add("prophets_105", "prophets", "hard", "quran", Q, "37:146", False,
        fr=L("Quelle plante Allah fit-Il pousser au-dessus de Yûnus après qu'il fut rejeté par le poisson ?",
             ["Une plante de courge (yaqtîn)", "Un palmier", "Un olivier", "De la vigne"], 0,
             "« Nous fîmes pousser au-dessus de lui un plant de courge. »",
             "Coran — Sourate As-Sâffât, 37:146"),
        en=L("Which plant did Allah make grow over Yunus after the fish cast him out?",
             ["A gourd plant (yaqtin)", "A palm tree", "An olive tree", "A vine"], 0,
             "\"And We caused to grow over him a gourd vine.\"",
             "Quran — Surah As-Saffat, 37:146"),
        ar=L("أي نبتة أنبتها الله فوق يونس بعد أن نبذه الحوت؟",
             ["شجرة من يقطين", "نخلة", "زيتونة", "كرمة"], 0,
             "﴿وأنبتنا عليه شجرة من يقطين﴾.",
             "القرآن — سورة الصافات، 37:146"))

    add("prophets_106", "prophets", "hard", "quran", Q, "37:147", False,
        fr=L("Vers combien de personnes Yûnus fut-il envoyé, selon le Coran ?",
             ["Cent mille, ou davantage", "Mille", "Dix mille", "Douze"], 0,
             "« Nous l'envoyâmes vers cent mille, ou davantage. »",
             "Coran — Sourate As-Sâffât, 37:147"),
        en=L("To how many people was Yunus sent, according to the Quran?",
             ["A hundred thousand, or more", "A thousand", "Ten thousand", "Twelve"], 0,
             "\"And We sent him to a hundred thousand, or more.\"",
             "Quran — Surah As-Saffat, 37:147"),
        ar=L("إلى كم من الناس أُرسل يونس بحسب القرآن؟",
             ["مئة ألف أو يزيدون", "ألف", "عشرة آلاف", "اثني عشر"], 0,
             "﴿وأرسلناه إلى مئة ألف أو يزيدون﴾.",
             "القرآن — سورة الصافات، 37:147"))

    add("prophets_107", "prophets", "medium", "quran", Q, "19:10", False,
        fr=L("Quel signe Allah donna-t-Il à Zakariyyâ pour lui confirmer la venue de son fils ?",
             ["Ne pas parler aux gens pendant trois nuits, sans être malade", "Une étoile filante", "Une pluie en été", "Un rêve"], 0,
             "« Ton signe sera que tu ne parleras pas aux gens pendant trois nuits, tout en étant sain. »",
             "Coran — Sourate Maryam, 19:10"),
        en=L("What sign did Allah give Zakariyya to confirm the coming of his son?",
             ["Not speaking to people for three nights, though sound", "A shooting star", "Rain in summer", "A dream"], 0,
             "\"Your sign is that you will not speak to people for three nights, though sound.\"",
             "Quran — Surah Maryam, 19:10"),
        ar=L("ما الآية التي جعلها الله لزكريا تأكيدًا لبشارة ابنه؟",
             ["ألا يكلّم الناس ثلاث ليال سويًا", "شهاب", "مطر في الصيف", "رؤيا"], 0,
             "﴿آيتك ألا تكلّم الناس ثلاث ليال سويًا﴾.",
             "القرآن — سورة مريم، 19:10"))

    add("prophets_108", "prophets", "hard", "quran", Q, "19:7", False,
        fr=L("Que dit Allah au sujet du nom de Yahyâ ?",
             ["Personne avant lui n'avait porté ce nom", "C'était le nom de son grand-père", "Sa mère l'avait choisi", "C'était un nom de roi"], 0,
             "« Nous t'annonçons un garçon nommé Yahyâ : Nous n'avons donné ce nom à personne auparavant. »",
             "Coran — Sourate Maryam, 19:7"),
        en=L("What does Allah say about the name Yahya?",
             ["No one before him had been given that name", "It was his grandfather's name", "His mother chose it", "It was a king's name"], 0,
             "\"We give you good tidings of a boy whose name will be Yahya; We have not given this name to anyone before.\"",
             "Quran — Surah Maryam, 19:7"),
        ar=L("ماذا قال الله عن اسم يحيى؟",
             ["لم يجعل له من قبل سميًّا", "كان اسم جده", "اختارته أمه", "كان اسم ملك"], 0,
             "﴿إنا نبشّرك بغلام اسمه يحيى لم نجعل له من قبل سميًّا﴾.",
             "القرآن — سورة مريم، 19:7"))

    add("prophets_109", "prophets", "medium", "quran", Q, "19:12", False,
        fr=L("Qu'Allah accorda-t-Il à Yahyâ alors qu'il était encore enfant ?",
             ["La sagesse", "Un royaume", "Un cheval", "Un trésor"], 0,
             "« Ô Yahyâ, prends le Livre avec force ! » Et Nous lui donnâmes la sagesse dès l'enfance.",
             "Coran — Sourate Maryam, 19:12"),
        en=L("What did Allah grant Yahya while he was still a child?",
             ["Wisdom", "A kingdom", "A horse", "A treasure"], 0,
             "\"O Yahya, take the Scripture with determination.\" And We gave him judgement while yet a boy.",
             "Quran — Surah Maryam, 19:12"),
        ar=L("ماذا آتى الله يحيى وهو صبي؟",
             ["الحكم (الحكمة)", "ملكًا", "فرسًا", "كنزًا"], 0,
             "﴿يا يحيى خذ الكتاب بقوة وآتيناه الحكم صبيًا﴾.",
             "القرآن — سورة مريم، 19:12"))

    add("prophets_110", "prophets", "medium", "quran", Q, "3:35", False,
        fr=L("Qu'avait promis la mère de Maryam pour l'enfant qu'elle portait ?",
             ["De le consacrer au service d'Allah", "De l'envoyer en Égypte", "De le faire roi", "De le confier à un berger"], 0,
             "« Seigneur, je Te consacre ce qui est dans mon ventre, en toute liberté. »",
             "Coran — Sourate Âl 'Imrân, 3:35"),
        en=L("What had Maryam's mother vowed for the child she was carrying?",
             ["To dedicate it to Allah's service", "To send it to Egypt", "To make it a king", "To entrust it to a shepherd"], 0,
             "\"My Lord, I have vowed to You what is in my womb, consecrated to Your service.\"",
             "Quran — Surah Al 'Imran, 3:35"),
        ar=L("بماذا نذرت أم مريم لما في بطنها؟",
             ["أن يكون محرَّرًا لخدمة الله", "أن ترسله إلى مصر", "أن تجعله ملكًا", "أن تسلّمه لراعٍ"], 0,
             "﴿ربِّ إني نذرت لك ما في بطني محرَّرًا﴾.",
             "القرآن — سورة آل عمران، 3:35"))

    add("prophets_111", "prophets", "medium", "quran", Q, "3:37", False,
        fr=L("Quel prophète prit Maryam en charge après sa naissance ?",
             ["Zakariyyâ", "Yahyâ", "Îsâ", "Dâwûd"], 0,
             "« Il la confia à Zakariyyâ », qui trouvait auprès d'elle une subsistance venue d'Allah.",
             "Coran — Sourate Âl 'Imrân, 3:37"),
        en=L("Which prophet took charge of Maryam after her birth?",
             ["Zakariyya", "Yahya", "Isa", "Dawud"], 0,
             "\"And He put her in the care of Zakariyya,\" who found with her provision from Allah.",
             "Quran — Surah Al 'Imran, 3:37"),
        ar=L("أي نبي كفل مريم بعد ولادتها؟",
             ["زكريا", "يحيى", "عيسى", "داوود"], 0,
             "﴿وكفّلها زكريا﴾ وكان يجد عندها رزقًا من عند الله.",
             "القرآن — سورة آل عمران، 3:37"))

    add("prophets_112", "prophets", "easy", "quran", Q, "3:42", False,
        fr=L("Selon le Coran, Allah a choisi Maryam au-dessus de qui ?",
             ["Des femmes de l'univers", "Des reines", "Des anges", "Des prophètes"], 0,
             "« Ô Maryam, Allah t'a élue et purifiée, et Il t'a choisie au-dessus des femmes des mondes. »",
             "Coran — Sourate Âl 'Imrân, 3:42"),
        en=L("According to the Quran, Allah chose Maryam above whom?",
             ["The women of the worlds", "The queens", "The angels", "The prophets"], 0,
             "\"O Maryam, Allah has chosen you and purified you, and chosen you above the women of the worlds.\"",
             "Quran — Surah Al 'Imran, 3:42"),
        ar=L("بحسب القرآن، على من اصطفى الله مريم؟",
             ["على نساء العالمين", "على الملكات", "على الملائكة", "على الأنبياء"], 0,
             "﴿يا مريم إن الله اصطفاك وطهّرك واصطفاك على نساء العالمين﴾.",
             "القرآن — سورة آل عمران، 3:42"))

    add("prophets_113", "prophets", "easy", "quran", Q, "19:25", False,
        fr=L("Qu'est-ce qui tomba sur Maryam quand elle secoua le tronc du palmier ?",
             ["Des dattes fraîches et mûres", "Des olives", "Des figues", "De la pluie"], 0,
             "« Secoue vers toi le tronc du palmier : il fera tomber sur toi des dattes fraîches et mûres. »",
             "Coran — Sourate Maryam, 19:25"),
        en=L("What fell for Maryam when she shook the trunk of the palm tree?",
             ["Fresh ripe dates", "Olives", "Figs", "Rain"], 0,
             "\"Shake the trunk of the palm tree towards you: it will drop upon you fresh, ripe dates.\"",
             "Quran — Surah Maryam, 19:25"),
        ar=L("ماذا تساقط على مريم حين هزّت جذع النخلة؟",
             ["رطب جنيّ", "زيتون", "تين", "مطر"], 0,
             "﴿وهزّي إليك بجذع النخلة تساقط عليك رطبًا جنيًا﴾.",
             "القرآن — سورة مريم، 19:25"))

    add("prophets_114", "prophets", "hard", "quran", Q, "5:75", False,
        fr=L("Par quel mot le Coran qualifie-t-il Maryam dans la sourate Al-Mâ'ida ?",
             ["Véridique (siddîqa)", "Reine", "Prophétesse", "Guerrière"], 0,
             "« Le Messie fils de Maryam n'était qu'un messager… et sa mère était une véridique. »",
             "Coran — Sourate Al-Mâ'ida, 5:75"),
        en=L("What word does the Quran use for Maryam in Surah Al-Ma'ida?",
             ["Truthful (siddiqa)", "Queen", "Prophetess", "Warrior"], 0,
             "\"The Messiah, son of Maryam, was only a messenger… and his mother was a supporter of truth.\"",
             "Quran — Surah Al-Ma'ida, 5:75"),
        ar=L("بأي كلمة وصف القرآن مريم في سورة المائدة؟",
             ["صدّيقة", "ملكة", "نبيّة", "محاربة"], 0,
             "﴿ما المسيح ابن مريم إلا رسول… وأمه صدّيقة﴾.",
             "القرآن — سورة المائدة، 5:75"))

    add("prophets_115", "prophets", "easy", "quran", Q, "3:45", False,
        fr=L("Quel titre le Coran donne-t-il à Îsâ fils de Maryam ?",
             ["Al-Masîh (le Messie)", "Al-Khalîl", "Al-Kalîm", "As-Siddîq"], 0,
             "« Son nom sera le Messie, Îsâ fils de Maryam, illustre ici-bas et dans l'au-delà. »",
             "Coran — Sourate Âl 'Imrân, 3:45"),
        en=L("What title does the Quran give to Isa, son of Maryam?",
             ["Al-Masih (the Messiah)", "Al-Khalil", "Al-Kalim", "As-Siddiq"], 0,
             "\"His name will be the Messiah, Isa son of Maryam, distinguished in this world and the Hereafter.\"",
             "Quran — Surah Al 'Imran, 3:45"),
        ar=L("ما اللقب الذي أطلقه القرآن على عيسى ابن مريم؟",
             ["المسيح", "الخليل", "الكليم", "الصدّيق"], 0,
             "﴿اسمه المسيح عيسى ابن مريم وجيهًا في الدنيا والآخرة﴾.",
             "القرآن — سورة آل عمران، 3:45"))

    add("prophets_116", "prophets", "medium", "quran", Q, "3:49", False,
        fr=L("Que façonnait Îsâ avec de l'argile, par la permission d'Allah ?",
             ["La forme d'un oiseau, qui devenait vivant", "Une maison", "Une statue de roi", "Un bateau"], 0,
             "« Je façonne pour vous, avec de l'argile, la forme d'un oiseau ; je souffle dedans et il devient oiseau, par la permission d'Allah. »",
             "Coran — Sourate Âl 'Imrân, 3:49"),
        en=L("What did Isa fashion from clay, by Allah's permission?",
             ["The shape of a bird, which became alive", "A house", "A statue of a king", "A boat"], 0,
             "\"I design for you from clay the form of a bird, then I breathe into it and it becomes a bird by Allah's permission.\"",
             "Quran — Surah Al 'Imran, 3:49"),
        ar=L("ماذا كان عيسى يصنع من الطين بإذن الله؟",
             ["هيئة الطير فيصير طيرًا", "بيتًا", "تمثال ملك", "قاربًا"], 0,
             "﴿أني أخلق لكم من الطين كهيئة الطير فأنفخ فيه فيكون طيرًا بإذن الله﴾.",
             "القرآن — سورة آل عمران، 3:49"))

    add("prophets_117", "prophets", "medium", "quran", Q, "3:52", False,
        fr=L("Comment appelle-t-on les compagnons proches d'Îsâ qui se déclarèrent « soutiens d'Allah » ?",
             ["Les Hawâriyyûn (apôtres)", "Les Ansâr", "Les Muhâjirûn", "Les Sahâba"], 0,
             "« Les apôtres dirent : nous sommes les soutiens d'Allah. »",
             "Coran — Sourate Âl 'Imrân, 3:52"),
        en=L("What are Isa's close companions called, who declared themselves \"Allah's helpers\"?",
             ["The Hawariyyun (disciples)", "The Ansar", "The Muhajirun", "The Sahaba"], 0,
             "\"The disciples said: we are supporters of Allah.\"",
             "Quran — Surah Al 'Imran, 3:52"),
        ar=L("ماذا يُسمّى أصحاب عيسى المقرّبون الذين قالوا «نحن أنصار الله»؟",
             ["الحواريون", "الأنصار", "المهاجرون", "الصحابة"], 0,
             "﴿قال الحواريون نحن أنصار الله﴾.",
             "القرآن — سورة آل عمران، 3:52"))

    add("prophets_118", "prophets", "hard", "quran", Q, "5:112-114", False,
        fr=L("Que demandèrent les apôtres à Îsâ, ce qui donna son nom à la sourate Al-Mâ'ida ?",
             ["Une table servie descendue du ciel", "Un livre", "Un royaume", "De l'or"], 0,
             "« Ton Seigneur peut-Il faire descendre sur nous une table servie du ciel ? »",
             "Coran — Sourate Al-Mâ'ida, 5:112-114"),
        en=L("What did the disciples ask Isa for, which gave Surah Al-Ma'ida its name?",
             ["A table spread with food sent down from heaven", "A book", "A kingdom", "Gold"], 0,
             "\"Can your Lord send down to us a table spread with food from heaven?\"",
             "Quran — Surah Al-Ma'ida, 5:112-114"),
        ar=L("ماذا طلب الحواريون من عيسى، وبه سُمّيت سورة المائدة؟",
             ["مائدة تنزل من السماء", "كتابًا", "ملكًا", "ذهبًا"], 0,
             "﴿هل يستطيع ربك أن ينزّل علينا مائدة من السماء﴾.",
             "القرآن — سورة المائدة، 5:112-114"))

    add("prophets_119", "prophets", "medium", "quran", Q, "4:157-158", False,
        fr=L("Que dit le Coran sur la fin de la mission d'Îsâ sur terre ?",
             ["Il ne fut ni tué ni crucifié : Allah l'éleva vers Lui", "Il mourut de vieillesse", "Il se noya", "Il partit en Égypte"], 0,
             "« Ils ne l'ont ni tué ni crucifié… mais Allah l'a élevé vers Lui. »",
             "Coran — Sourate An-Nisâ, 4:157-158"),
        en=L("What does the Quran say about the end of Isa's mission on earth?",
             ["He was neither killed nor crucified: Allah raised him to Himself", "He died of old age", "He drowned", "He went to Egypt"], 0,
             "\"They did not kill him, nor did they crucify him… rather, Allah raised him to Himself.\"",
             "Quran — Surah An-Nisa, 4:157-158"),
        ar=L("ماذا يقول القرآن عن نهاية رسالة عيسى على الأرض؟",
             ["ما قُتل وما صُلب بل رفعه الله إليه", "مات هرمًا", "غرق", "ذهب إلى مصر"], 0,
             "﴿وما قتلوه وما صلبوه… بل رفعه الله إليه﴾.",
             "القرآن — سورة النساء، 4:157-158"))

    add("prophets_120", "prophets", "hard", "quran", Q, "61:6", False,
        fr=L("Sous quel nom Îsâ annonça-t-il un messager qui viendrait après lui ?",
             ["Ahmad", "Yahyâ", "Mûsâ", "Ilyâs"], 0,
             "« …annonciateur d'un messager à venir après moi, dont le nom sera Ahmad. »",
             "Coran — Sourate As-Saff, 61:6"),
        en=L("By what name did Isa announce a messenger who would come after him?",
             ["Ahmad", "Yahya", "Musa", "Ilyas"], 0,
             "\"…bringing good tidings of a messenger to come after me, whose name is Ahmad.\"",
             "Quran — Surah As-Saff, 61:6"),
        ar=L("بأي اسم بشّر عيسى برسول يأتي من بعده؟",
             ["أحمد", "يحيى", "موسى", "إلياس"], 0,
             "﴿ومبشّرًا برسول يأتي من بعدي اسمه أحمد﴾.",
             "القرآن — سورة الصف، 61:6"))

    add("prophets_121", "prophets", "hard", "quran", Q, "37:125", False,
        fr=L("Quelle idole le prophète Ilyâs reprocha-t-il à son peuple d'adorer ?",
             ["Ba'l", "Hubal", "Al-Lât", "Wadd"], 0,
             "« Invoquez-vous Ba'l, et délaissez-vous le Meilleur des créateurs ? »",
             "Coran — Sourate As-Sâffât, 37:125"),
        en=L("Which idol did the prophet Ilyas rebuke his people for worshipping?",
             ["Ba'l", "Hubal", "Al-Lat", "Wadd"], 0,
             "\"Do you call upon Ba'l and leave the best of creators?\"",
             "Quran — Surah As-Saffat, 37:125"),
        ar=L("أي صنم أنكر إلياس على قومه عبادته؟",
             ["بعل", "هُبل", "اللات", "ودّ"], 0,
             "﴿أتدعون بعلًا وتذرون أحسن الخالقين﴾.",
             "القرآن — سورة الصافات، 37:125"))

    add("prophets_122", "prophets", "hard", "quran", Q, "21:85", False,
        fr=L("Quels trois prophètes le Coran cite-t-il ensemble comme « parmi les endurants » ?",
             ["Ismâ'îl, Idrîs et Dhul-Kifl", "Nûh, Hûd et Sâlih", "Mûsâ, Hârûn et Yûsha'", "Dâwûd, Sulaymân et Ayyûb"], 0,
             "« Et Ismâ'îl, Idrîs et Dhul-Kifl : tous étaient parmi les endurants. »",
             "Coran — Sourate Al-Anbiyâ, 21:85"),
        en=L("Which three prophets does the Quran mention together as \"among the patient\"?",
             ["Isma'il, Idris and Dhul-Kifl", "Nuh, Hud and Salih", "Musa, Harun and Yusha'", "Dawud, Sulayman and Ayyub"], 0,
             "\"And Isma'il, Idris and Dhul-Kifl: all were of the patient.\"",
             "Quran — Surah Al-Anbiya, 21:85"),
        ar=L("أي ثلاثة أنبياء ذكرهم القرآن معًا «من الصابرين»؟",
             ["إسماعيل وإدريس وذو الكفل", "نوح وهود وصالح", "موسى وهارون ويوشع", "داوود وسليمان وأيوب"], 0,
             "﴿وإسماعيل وإدريس وذا الكفل كلٌّ من الصابرين﴾.",
             "القرآن — سورة الأنبياء، 21:85"))

    add("prophets_123", "prophets", "hard", "quran", Q, "38:48", False,
        fr=L("Quel prophète est cité dans la sourate Sâd aux côtés d'Ismâ'îl et de Dhul-Kifl ?",
             ["Al-Yasa'", "Yûnus", "Lût", "Shu'ayb"], 0,
             "« Et rappelle-toi Ismâ'îl, Al-Yasa' et Dhul-Kifl : tous parmi les meilleurs. »",
             "Coran — Sourate Sâd, 38:48"),
        en=L("Which prophet is named in Surah Sad alongside Isma'il and Dhul-Kifl?",
             ["Al-Yasa' (Elisha)", "Yunus", "Lut", "Shu'ayb"], 0,
             "\"And remember Isma'il, Al-Yasa' and Dhul-Kifl: all are among the outstanding.\"",
             "Quran — Surah Sad, 38:48"),
        ar=L("أي نبي ذُكر في سورة ص مع إسماعيل وذي الكفل؟",
             ["اليسع", "يونس", "لوط", "شعيب"], 0,
             "﴿واذكر إسماعيل واليسع وذا الكفل وكلٌّ من الأخيار﴾.",
             "القرآن — سورة ص، 38:48"))

    add("prophets_124", "prophets", "easy", "quran", Q, "33:40", False,
        fr=L("Quel titre le Coran donne-t-il au prophète Muhammad ﷺ dans le verset 33:40 ?",
             ["Le Sceau des prophètes", "Le Roi des Arabes", "Le Père des croyants", "L'Ami d'Allah"], 0,
             "« Muhammad… est le Messager d'Allah et le Sceau des prophètes. »",
             "Coran — Sourate Al-Ahzâb, 33:40"),
        en=L("What title does the Quran give the Prophet Muhammad ﷺ in verse 33:40?",
             ["The Seal of the Prophets", "The King of the Arabs", "The Father of the believers", "The Friend of Allah"], 0,
             "\"Muhammad… is the Messenger of Allah and the Seal of the Prophets.\"",
             "Quran — Surah Al-Ahzab, 33:40"),
        ar=L("ما اللقب الذي أطلقه القرآن على النبي محمد ﷺ في الآية 33:40؟",
             ["خاتم النبيين", "ملك العرب", "أبو المؤمنين", "خليل الله"], 0,
             "﴿ولكن رسول الله وخاتم النبيين﴾.",
             "القرآن — سورة الأحزاب، 33:40"))

    add("prophets_125", "prophets", "easy", "quran", Q, "21:107", False,
        fr=L("Selon le Coran, en tant que quoi le Prophète Muhammad ﷺ a-t-il été envoyé ?",
             ["Une miséricorde pour les mondes", "Un roi", "Un juge", "Un guerrier"], 0,
             "« Nous ne t'avons envoyé qu'en miséricorde pour les mondes. »",
             "Coran — Sourate Al-Anbiyâ, 21:107"),
        en=L("According to the Quran, as what was the Prophet Muhammad ﷺ sent?",
             ["A mercy to the worlds", "A king", "A judge", "A warrior"], 0,
             "\"We have not sent you except as a mercy to the worlds.\"",
             "Quran — Surah Al-Anbiya, 21:107"),
        ar=L("بحسب القرآن، بأي صفة أُرسل النبي محمد ﷺ؟",
             ["رحمة للعالمين", "ملكًا", "قاضيًا", "محاربًا"], 0,
             "﴿وما أرسلناك إلا رحمة للعالمين﴾.",
             "القرآن — سورة الأنبياء، 21:107"))

    add("prophets_126", "prophets", "easy", "quran", Q, "33:56", False,
        fr=L("Selon le verset 33:56, qu'Allah et Ses anges font-ils envers le Prophète ﷺ ?",
             ["Ils prient sur lui (le bénissent)", "Ils le protègent des vents", "Ils lui envoient de la pluie", "Ils l'observent en silence"], 0,
             "« Allah et Ses anges prient sur le Prophète. Ô croyants, priez sur lui et saluez-le. »",
             "Coran — Sourate Al-Ahzâb, 33:56"),
        en=L("According to verse 33:56, what do Allah and His angels do for the Prophet ﷺ?",
             ["They send blessings upon him", "They shield him from winds", "They send him rain", "They watch him in silence"], 0,
             "\"Allah and His angels send blessings upon the Prophet. O believers, send blessings upon him and greet him with peace.\"",
             "Quran — Surah Al-Ahzab, 33:56"),
        ar=L("بحسب الآية 33:56، ماذا يفعل الله وملائكته تجاه النبي ﷺ؟",
             ["يصلّون عليه", "يحمونه من الرياح", "يرسلون له المطر", "يراقبونه بصمت"], 0,
             "﴿إن الله وملائكته يصلّون على النبي يا أيها الذين آمنوا صلّوا عليه وسلّموا تسليمًا﴾.",
             "القرآن — سورة الأحزاب، 33:56"))

    add("prophets_127", "prophets", "medium", "quran", Q, "68:4", False,
        fr=L("Comment le Coran décrit-il le caractère du Prophète ﷺ dans la sourate Al-Qalam ?",
             ["« Tu es d'un caractère immense »", "« Tu es un grand roi »", "« Tu es le plus riche »", "« Tu es le plus fort »"], 0,
             "« Et tu es certes d'une moralité éminente. »",
             "Coran — Sourate Al-Qalam, 68:4"),
        en=L("How does the Quran describe the Prophet's ﷺ character in Surah Al-Qalam?",
             ["\"You are of a great moral character\"", "\"You are a great king\"", "\"You are the richest\"", "\"You are the strongest\""], 0,
             "\"And indeed, you are of a great moral character.\"",
             "Quran — Surah Al-Qalam, 68:4"),
        ar=L("كيف وصف القرآن خُلُق النبي ﷺ في سورة القلم؟",
             ["«وإنك لعلى خلق عظيم»", "«إنك ملك عظيم»", "«إنك أغنى الناس»", "«إنك أقوى الناس»"], 0,
             "﴿وإنك لعلى خلق عظيم﴾.",
             "القرآن — سورة القلم، 68:4"))

    add("prophets_128", "prophets", "medium", "quran", Q, "3:144", False,
        fr=L("Que rappelle le verset 3:144 au sujet de Muhammad ﷺ ?",
             ["Il n'est qu'un messager, et d'autres messagers sont passés avant lui", "Il ne mourra jamais", "Il est un ange", "Il connaît l'avenir"], 0,
             "« Muhammad n'est qu'un messager ; des messagers sont passés avant lui. »",
             "Coran — Sourate Âl 'Imrân, 3:144"),
        en=L("What does verse 3:144 remind us about Muhammad ﷺ?",
             ["He is only a messenger, and messengers have passed before him", "He will never die", "He is an angel", "He knows the future"], 0,
             "\"Muhammad is not but a messenger; messengers have passed on before him.\"",
             "Quran — Surah Al 'Imran, 3:144"),
        ar=L("بماذا تذكّر الآية 3:144 عن محمد ﷺ؟",
             ["ما هو إلا رسول قد خلت من قبله الرسل", "لن يموت أبدًا", "إنه ملك", "يعلم الغيب"], 0,
             "﴿وما محمد إلا رسول قد خلت من قبله الرسل﴾.",
             "القرآن — سورة آل عمران، 3:144"))

    add("prophets_129", "prophets", "hard", "quran", Q, "33:7", False,
        fr=L("Quels cinq prophètes le verset 33:7 nomme-t-il ensemble pour le pacte solennel ?",
             ["Nûh, Ibrâhîm, Mûsâ, Îsâ et Muhammad ﷺ", "Âdam, Nûh, Hûd, Sâlih et Lût", "Dâwûd, Sulaymân, Ayyûb, Yûnus et Idrîs", "Ismâ'îl, Ishâq, Ya'qûb, Yûsuf et Mûsâ"], 0,
             "« Nous prîmes des prophètes leur engagement : de toi, de Nûh, d'Ibrâhîm, de Mûsâ et d'Îsâ fils de Maryam. »",
             "Coran — Sourate Al-Ahzâb, 33:7"),
        en=L("Which five prophets does verse 33:7 name together for the solemn covenant?",
             ["Nuh, Ibrahim, Musa, Isa and Muhammad ﷺ", "Adam, Nuh, Hud, Salih and Lut", "Dawud, Sulayman, Ayyub, Yunus and Idris", "Isma'il, Ishaq, Ya'qub, Yusuf and Musa"], 0,
             "\"We took from the prophets their covenant: from you, from Nuh, Ibrahim, Musa and Isa son of Maryam.\"",
             "Quran — Surah Al-Ahzab, 33:7"),
        ar=L("أي خمسة أنبياء ذكرتهم الآية 33:7 معًا في أخذ الميثاق الغليظ؟",
             ["نوح وإبراهيم وموسى وعيسى ومحمد ﷺ", "آدم ونوح وهود وصالح ولوط", "داوود وسليمان وأيوب ويونس وإدريس", "إسماعيل وإسحاق ويعقوب ويوسف وموسى"], 0,
             "﴿وإذ أخذنا من النبيين ميثاقهم ومنك ومن نوح وإبراهيم وموسى وعيسى ابن مريم﴾.",
             "القرآن — سورة الأحزاب، 33:7"))

    add("prophets_130", "prophets", "medium", "hadithBukhari", "Sahih al-Bukhari", "2262", False,
        fr=L("Selon un hadith d'al-Bukhârî, quel métier tous les prophètes ont-ils exercé ?",
             ["Berger", "Charpentier", "Forgeron", "Marchand"], 0,
             "« Allah n'a envoyé aucun prophète qui n'ait gardé les moutons », et le Prophète ﷺ les gardait pour les Mecquois.",
             "Sahîh al-Bukhârî, 2262"),
        en=L("According to a hadith in al-Bukhari, which job did every prophet do?",
             ["Shepherd", "Carpenter", "Blacksmith", "Merchant"], 0,
             "\"Allah did not send any prophet but that he tended sheep,\" and the Prophet ﷺ tended them for the people of Makkah.",
             "Sahih al-Bukhari, 2262"),
        ar=L("بحسب حديث في البخاري، ما المهنة التي عمل بها كل الأنبياء؟",
             ["رعي الغنم", "النجارة", "الحدادة", "التجارة"], 0,
             "«ما بعث الله نبيًا إلا رعى الغنم»، وكان النبي ﷺ يرعاها لأهل مكة.",
             "صحيح البخاري، 2262"))

    add("prophets_131", "prophets", "hard", "hadithMuslim", "Sahih Muslim", "2379", False,
        fr=L("Selon un hadith de Muslim, quel prophète exerçait le métier de charpentier ?",
             ["Zakariyyâ", "Nûh", "Idrîs", "Yûsuf"], 0,
             "Le Prophète ﷺ a dit : « Zakariyyâ était charpentier. »",
             "Sahîh Muslim, 2379"),
        en=L("According to a hadith in Muslim, which prophet worked as a carpenter?",
             ["Zakariyya", "Nuh", "Idris", "Yusuf"], 0,
             "The Prophet ﷺ said: \"Zakariyya was a carpenter.\"",
             "Sahih Muslim, 2379"),
        ar=L("بحسب حديث في صحيح مسلم، أي نبي كان نجّارًا؟",
             ["زكريا", "نوح", "إدريس", "يوسف"], 0,
             "قال النبي ﷺ: «كان زكريا نجّارًا».",
             "صحيح مسلم، 2379"))

    add("prophets_132", "prophets", "hard", "hadithBukhari", "Sahih al-Bukhari", "3442", False,
        fr=L("De quel prophète le Prophète ﷺ a-t-il dit être « le plus proche des gens », ici-bas et dans l'au-delà ?",
             ["Îsâ fils de Maryam", "Mûsâ", "Ibrâhîm", "Nûh"], 0,
             "« Je suis le plus proche des gens d'Îsâ fils de Maryam, ici-bas et dans l'au-delà ; les prophètes sont frères. »",
             "Sahîh al-Bukhârî, 3442"),
        en=L("Of which prophet did the Prophet ﷺ say he was \"the nearest of people\", in this world and the next?",
             ["Isa son of Maryam", "Musa", "Ibrahim", "Nuh"], 0,
             "\"I am the nearest of all people to Isa son of Maryam in this world and the Hereafter; the prophets are brothers.\"",
             "Sahih al-Bukhari, 3442"),
        ar=L("عن أي نبي قال النبي ﷺ إنه «أولى الناس به» في الدنيا والآخرة؟",
             ["عيسى ابن مريم", "موسى", "إبراهيم", "نوح"], 0,
             "«أنا أولى الناس بعيسى ابن مريم في الدنيا والآخرة، والأنبياء إخوة».",
             "صحيح البخاري، 3442"))

    add("prophets_133", "prophets", "hard", "quran", Q, "well-established count (six surahs bear a prophet's name: Yunus, Hud, Yusuf, Ibrahim, Muhammad, Nuh)", False,
        fr=L("Combien de sourates du Coran portent le nom d'un prophète ?",
             ["Six", "Deux", "Douze", "Vingt-cinq"], 0,
             "Yûnus (10), Hûd (11), Yûsuf (12), Ibrâhîm (14), Muhammad (47) et Nûh (71).",
             "Coran — fait établi (noms des sourates)"),
        en=L("How many surahs of the Quran are named after a prophet?",
             ["Six", "Two", "Twelve", "Twenty-five"], 0,
             "Yunus (10), Hud (11), Yusuf (12), Ibrahim (14), Muhammad (47) and Nuh (71).",
             "Quran — established fact (surah names)"),
        ar=L("كم سورة في القرآن تحمل اسم نبي؟",
             ["ست", "اثنتان", "اثنتا عشرة", "خمس وعشرون"], 0,
             "يونس (10)، هود (11)، يوسف (12)، إبراهيم (14)، محمد (47)، نوح (71).",
             "القرآن — حقيقة ثابتة (أسماء السور)"))

    add("prophets_134", "prophets", "hard", "quran", Q, "11:75", False,
        fr=L("Par quels trois mots le Coran décrit-il Ibrâhîm dans le verset 11:75 ?",
             ["Indulgent, plein de compassion, repentant", "Riche, puissant, savant", "Fort, rapide, courageux", "Roi, juge, guerrier"], 0,
             "« Ibrâhîm était indulgent (halîm), plein de compassion (awwâh) et repentant (munîb). »",
             "Coran — Sourate Hûd, 11:75"),
        en=L("With which three words does the Quran describe Ibrahim in verse 11:75?",
             ["Forbearing, tender-hearted, ever-returning", "Rich, powerful, learned", "Strong, fast, brave", "King, judge, warrior"], 0,
             "\"Indeed, Ibrahim was forbearing, grieving and ever-returning to Allah.\"",
             "Quran — Surah Hud, 11:75"),
        ar=L("بأي ثلاث كلمات وصف القرآن إبراهيم في الآية 11:75؟",
             ["حليم أوّاه منيب", "غني قوي عليم", "قوي سريع شجاع", "ملك قاضٍ محارب"], 0,
             "﴿إن إبراهيم لحليم أوّاه منيب﴾.",
             "القرآن — سورة هود، 11:75"))

    add("prophets_135", "prophets", "medium", "quran", Q, "7:85", False,
        fr=L("Quel reproche Shu'ayb adressa-t-il à son peuple, en plus de l'idolâtrie ?",
             ["De tricher sur les poids et les mesures", "De ne pas prier", "De voyager la nuit", "De manger du poisson"], 0,
             "« Donnez la pleine mesure et le poids exact, et ne lésez pas les gens dans leurs biens. »",
             "Coran — Sourate Al-A'râf, 7:85"),
        en=L("What did Shu'ayb rebuke his people for, besides idolatry?",
             ["Cheating in weights and measures", "Not praying", "Travelling at night", "Eating fish"], 0,
             "\"Give full measure and weight, and do not deprive people of their due.\"",
             "Quran — Surah Al-A'raf, 7:85"),
        ar=L("بماذا وبّخ شعيب قومه إضافة إلى الشرك؟",
             ["بالتطفيف في الكيل والميزان", "بترك الصلاة", "بالسفر ليلًا", "بأكل السمك"], 0,
             "﴿فأوفوا الكيل والميزان ولا تبخسوا الناس أشياءهم﴾.",
             "القرآن — سورة الأعراف، 7:85"))

    add("prophets_136", "prophets", "medium", "quran", Q, "7:91", False,
        fr=L("Par quoi le peuple de Shu'ayb fut-il saisi après avoir rejeté son message ?",
             ["Un tremblement de terre", "Un déluge", "Une pluie de feu", "Une nuée d'oiseaux"], 0,
             "« Le tremblement de terre les saisit, et ils gisaient morts dans leurs demeures. »",
             "Coran — Sourate Al-A'râf, 7:91"),
        en=L("What seized Shu'ayb's people after they rejected his message?",
             ["An earthquake", "A flood", "A rain of fire", "A flock of birds"], 0,
             "\"So the earthquake seized them, and they became within their home corpses fallen prone.\"",
             "Quran — Surah Al-A'raf, 7:91"),
        ar=L("بماذا أُخذ قوم شعيب بعد تكذيبهم؟",
             ["بالرجفة", "بالطوفان", "بمطر من نار", "بطير أبابيل"], 0,
             "﴿فأخذتهم الرجفة فأصبحوا في دارهم جاثمين﴾.",
             "القرآن — سورة الأعراف، 7:91"))

    add("prophets_137", "prophets", "hard", "quran", Q, "11:70", False,
        fr=L("Quelle nouvelle les anges donnèrent-ils à Ibrâhîm après avoir calmé sa crainte ?",
             ["Qu'ils étaient envoyés vers le peuple de Lût", "Qu'un déluge arrivait", "Que la Ka'ba serait détruite", "Que Pharaon se noierait"], 0,
             "« N'aie pas peur : nous sommes envoyés vers le peuple de Lût. »",
             "Coran — Sourate Hûd, 11:70"),
        en=L("What news did the angels give Ibrahim after calming his fear?",
             ["That they were sent to the people of Lut", "That a flood was coming", "That the Ka'ba would be destroyed", "That Pharaoh would drown"], 0,
             "\"Fear not: we have been sent to the people of Lut.\"",
             "Quran — Surah Hud, 11:70"),
        ar=L("بماذا أخبرت الملائكةُ إبراهيمَ بعد أن أزالت خوفه؟",
             ["أنهم أُرسلوا إلى قوم لوط", "أن طوفانًا قادم", "أن الكعبة ستُهدم", "أن فرعون سيغرق"], 0,
             "﴿لا تخف إنا أُرسلنا إلى قوم لوط﴾.",
             "القرآن — سورة هود، 11:70"))

    add("prophets_138", "prophets", "medium", "quran", Q, "14:40", False,
        fr=L("Que demanda Ibrâhîm pour lui-même et sa descendance dans le verset 14:40 ?",
             ["Être de ceux qui accomplissent la prière", "Être rois", "Être riches", "Vivre longtemps"], 0,
             "« Seigneur, fais que j'accomplisse la prière, ainsi que ma descendance. »",
             "Coran — Sourate Ibrâhîm, 14:40"),
        en=L("What did Ibrahim ask for himself and his descendants in verse 14:40?",
             ["To be establishers of prayer", "To be kings", "To be wealthy", "To live long"], 0,
             "\"My Lord, make me an establisher of prayer, and from my descendants.\"",
             "Quran — Surah Ibrahim, 14:40"),
        ar=L("ماذا سأل إبراهيم لنفسه ولذريته في الآية 14:40؟",
             ["أن يكونوا مقيمي الصلاة", "أن يكونوا ملوكًا", "أن يكونوا أغنياء", "أن يعيشوا طويلًا"], 0,
             "﴿ربِّ اجعلني مقيم الصلاة ومن ذريتي﴾.",
             "القرآن — سورة إبراهيم، 14:40"))

    add("prophets_139", "prophets", "hard", "quran", Q, "12:100", False,
        fr=L("À la fin de l'histoire de Yûsuf, qui fit-il monter sur le trône avant que tous se prosternent devant lui ?",
             ["Ses parents", "Le roi", "Ses frères", "Son fils"], 0,
             "« Il éleva ses parents sur le trône, et ils tombèrent prosternés devant lui » : le rêve d'enfance s'accomplissait.",
             "Coran — Sourate Yûsuf, 12:100"),
        en=L("At the end of Yusuf's story, whom did he raise onto the throne before all bowed down to him?",
             ["His parents", "The king", "His brothers", "His son"], 0,
             "\"He raised his parents upon the throne, and they fell before him in prostration\": the childhood dream came true.",
             "Quran — Surah Yusuf, 12:100"),
        ar=L("في نهاية قصة يوسف، من رفع على العرش قبل أن يخرّوا له سجّدًا؟",
             ["أبويه", "الملك", "إخوته", "ابنه"], 0,
             "﴿ورفع أبويه على العرش وخرّوا له سجّدًا﴾: تحققت رؤيا الطفولة.",
             "القرآن — سورة يوسف، 12:100"))

    add("prophets_140", "prophets", "easy", "quran", Q, "12:8-9", False,
        fr=L("Pourquoi les frères de Yûsuf ont-ils voulu se débarrasser de lui ?",
             ["Par jalousie : leur père l'aimait plus qu'eux", "Il avait volé", "Il refusait de travailler", "Il était malade"], 0,
             "« Yûsuf et son frère sont plus chers à notre père que nous… Tuez Yûsuf ou jetez-le dans une terre lointaine. »",
             "Coran — Sourate Yûsuf, 12:8-9"),
        en=L("Why did Yusuf's brothers want to get rid of him?",
             ["Out of jealousy: their father loved him more", "He had stolen", "He refused to work", "He was ill"], 0,
             "\"Yusuf and his brother are more beloved to our father than we are… Kill Yusuf or cast him out to some land.\"",
             "Quran — Surah Yusuf, 12:8-9"),
        ar=L("لماذا أراد إخوة يوسف التخلص منه؟",
             ["حسدًا لأن أباهم أحبّه أكثر", "لأنه سرق", "لأنه رفض العمل", "لأنه كان مريضًا"], 0,
             "﴿ليوسف وأخوه أحب إلى أبينا منا… اقتلوا يوسف أو اطرحوه أرضًا﴾.",
             "القرآن — سورة يوسف، 12:8-9"))

    add("prophets_141", "prophets", "easy", "quran", Q, "12:18", False,
        fr=L("Qu'apportèrent les frères de Yûsuf à leur père pour faire croire qu'un loup l'avait dévoré ?",
             ["Sa chemise tachée d'un faux sang", "Ses sandales", "Son bâton", "Une dent de loup"], 0,
             "« Ils apportèrent sa chemise tachée d'un faux sang » ; Ya'qûb répondit : « Patience, belle patience. »",
             "Coran — Sourate Yûsuf, 12:18"),
        en=L("What did Yusuf's brothers bring their father to make him believe a wolf had eaten him?",
             ["His shirt stained with false blood", "His sandals", "His staff", "A wolf's tooth"], 0,
             "\"They brought his shirt with false blood on it\"; Ya'qub replied: \"Patience is most fitting.\"",
             "Quran — Surah Yusuf, 12:18"),
        ar=L("بماذا جاء إخوة يوسف إلى أبيهم ليوهموه أن الذئب أكله؟",
             ["بقميصه عليه دم كذب", "بنعليه", "بعصاه", "بسنّ ذئب"], 0,
             "﴿وجاؤوا على قميصه بدم كذب﴾ فقال يعقوب: ﴿فصبر جميل﴾.",
             "القرآن — سورة يوسف، 12:18"))

    add("prophets_142", "prophets", "easy", "quran", Q, "28:7", False,
        fr=L("Qu'Allah promit-Il à la mère de Mûsâ en lui inspirant de le mettre dans le fleuve ?",
             ["De le lui rendre et d'en faire un messager", "De lui donner un autre fils", "De la rendre reine", "De faire pleuvoir"], 0,
             "« Ne crains pas et ne t'attriste pas : Nous te le rendrons et ferons de lui un messager. »",
             "Coran — Sourate Al-Qasas, 28:7"),
        en=L("What did Allah promise Musa's mother when inspiring her to place him in the river?",
             ["To return him to her and make him a messenger", "To give her another son", "To make her a queen", "To send rain"], 0,
             "\"Do not fear and do not grieve: We will return him to you and make him one of the messengers.\"",
             "Quran — Surah Al-Qasas, 28:7"),
        ar=L("بماذا وعد الله أمَّ موسى حين أوحى إليها أن تلقيه في اليم؟",
             ["أن يردّه إليها ويجعله من المرسلين", "أن يعطيها ابنًا آخر", "أن يجعلها ملكة", "أن ينزل المطر"], 0,
             "﴿ولا تخافي ولا تحزني إنا رادّوه إليك وجاعلوه من المرسلين﴾.",
             "القرآن — سورة القصص، 28:7"))

    add("prophets_143", "prophets", "easy", "quran", Q, "26:63", False,
        fr=L("Avec quoi Mûsâ frappa-t-il la mer pour qu'elle se fende ?",
             ["Son bâton", "Sa main", "Une pierre", "Son épée"], 0,
             "« Frappe la mer de ton bâton » : elle se fendit, et chaque pan fut comme une immense montagne.",
             "Coran — Sourate Ash-Shu'arâ, 26:63"),
        en=L("With what did Musa strike the sea so that it parted?",
             ["His staff", "His hand", "A stone", "His sword"], 0,
             "\"Strike the sea with your staff\": it parted, and each side was like a great mountain.",
             "Quran — Surah Ash-Shu'ara, 26:63"),
        ar=L("بماذا ضرب موسى البحر لينفلق؟",
             ["بعصاه", "بيده", "بحجر", "بسيفه"], 0,
             "﴿اضرب بعصاك البحر فانفلق فكان كل فرق كالطود العظيم﴾.",
             "القرآن — سورة الشعراء، 26:63"))

    add("prophets_144", "prophets", "easy", "quran", Q, "20:14", False,
        fr=L("Quelle fut la première chose qu'Allah dit à Mûsâ en Se présentant à lui ?",
             ["« Je suis Allah, pas de divinité à part Moi : adore-Moi et accomplis la prière »", "« Va pêcher »", "« Construis une arche »", "« Retourne chez Pharaon »"], 0,
             "« Je suis Allah, il n'y a de divinité que Moi : adore-Moi donc, et accomplis la prière pour te souvenir de Moi. »",
             "Coran — Sourate Tâ-Hâ, 20:14"),
        en=L("What was the first thing Allah told Musa when addressing him?",
             ["\"I am Allah, there is no god but Me: worship Me and establish prayer\"", "\"Go fishing\"", "\"Build an ark\"", "\"Go back to Pharaoh\""], 0,
             "\"Indeed, I am Allah; there is no deity except Me, so worship Me and establish prayer for My remembrance.\"",
             "Quran — Surah Ta-Ha, 20:14"),
        ar=L("ما أول ما قاله الله لموسى حين خاطبه؟",
             ["«إنني أنا الله لا إله إلا أنا فاعبدني وأقم الصلاة»", "«اذهب للصيد»", "«ابنِ سفينة»", "«ارجع إلى فرعون»"], 0,
             "﴿إنني أنا الله لا إله إلا أنا فاعبدني وأقم الصلاة لذكري﴾.",
             "القرآن — سورة طه، 20:14"))

    add("prophets_145", "prophets", "easy", "quran", Q, "20:43-44", False,
        fr=L("Comment Allah ordonna-t-Il à Mûsâ et Hârûn de parler à Pharaon ?",
             ["Avec des paroles douces", "Avec colère", "En criant", "En silence"], 0,
             "« Allez vers Pharaon… et parlez-lui avec douceur : peut-être se rappellera-t-il ou craindra-t-il. »",
             "Coran — Sourate Tâ-Hâ, 20:43-44"),
        en=L("How did Allah tell Musa and Harun to speak to Pharaoh?",
             ["With gentle words", "With anger", "By shouting", "In silence"], 0,
             "\"Go to Pharaoh… and speak to him with gentle speech; perhaps he may be reminded or fear.\"",
             "Quran — Surah Ta-Ha, 20:43-44"),
        ar=L("كيف أمر الله موسى وهارون أن يكلّما فرعون؟",
             ["بقول ليّن", "بغضب", "بصراخ", "بصمت"], 0,
             "﴿اذهبا إلى فرعون… فقولا له قولًا ليّنًا لعله يتذكّر أو يخشى﴾.",
             "القرآن — سورة طه، 20:43-44"))

    add("prophets_146", "prophets", "easy", "quran", Q, "18:60", False,
        fr=L("Que dit Mûsâ à son jeune serviteur au début de son voyage vers le confluent des deux mers ?",
             ["Qu'il ne s'arrêterait pas avant d'atteindre le confluent des deux mers", "Qu'il voulait rentrer", "Qu'il avait peur", "Qu'il cherchait de l'or"], 0,
             "« Je ne cesserai pas avant d'atteindre le confluent des deux mers, dussé-je marcher longtemps. »",
             "Coran — Sourate Al-Kahf, 18:60"),
        en=L("What did Musa tell his young servant at the start of his journey to the junction of the two seas?",
             ["That he would not stop until he reached the junction of the two seas", "That he wanted to go home", "That he was afraid", "That he was looking for gold"], 0,
             "\"I will not give up until I reach the junction of the two seas, even if I go on for ages.\"",
             "Quran — Surah Al-Kahf, 18:60"),
        ar=L("ماذا قال موسى لفتاه في بداية رحلته إلى مجمع البحرين؟",
             ["لا يبرح حتى يبلغ مجمع البحرين", "إنه يريد العودة", "إنه خائف", "إنه يبحث عن الذهب"], 0,
             "﴿لا أبرح حتى أبلغ مجمع البحرين أو أمضي حقبًا﴾.",
             "القرآن — سورة الكهف، 18:60"))

    add("prophets_147", "prophets", "medium", "quran", Q, "18:71-77", False,
        fr=L("Laquelle de ces actions le serviteur savant accomplit-elle devant Mûsâ, qui ne comprit pas sur le moment ?",
             ["Il perça un bateau", "Il construisit un pont", "Il alluma un feu", "Il planta un arbre"], 0,
             "Il perça le bateau, puis tua un jeune garçon, puis redressa un mur — et expliqua ensuite chaque acte à Mûsâ.",
             "Coran — Sourate Al-Kahf, 18:71-77"),
        en=L("Which of these did the knowledgeable servant do in front of Musa, who did not understand at the time?",
             ["He made a hole in a boat", "He built a bridge", "He lit a fire", "He planted a tree"], 0,
             "He holed the boat, then killed a boy, then straightened a wall — and afterwards explained each act to Musa.",
             "Quran — Surah Al-Kahf, 18:71-77"),
        ar=L("أيَّ هذه الأفعال فعل العبد الصالح أمام موسى فلم يفهمه في حينه؟",
             ["خرق سفينة", "بنى جسرًا", "أشعل نارًا", "غرس شجرة"], 0,
             "خرق السفينة، ثم قتل الغلام، ثم أقام الجدار — ثم فسّر لموسى كل فعل.",
             "القرآن — سورة الكهف، 18:71-77"))

    add("prophets_148", "prophets", "easy", "quran", Q, "19:30", False,
        fr=L("Quelles furent les premières paroles d'Îsâ, encore au berceau ?",
             ["« Je suis le serviteur d'Allah ; Il m'a donné le Livre et fait de moi un prophète »", "« Je suis le fils de Dieu »", "« Je suis roi »", "« J'ai faim »"], 0,
             "« Il dit : je suis le serviteur d'Allah. Il m'a donné le Livre et a fait de moi un prophète. »",
             "Coran — Sourate Maryam, 19:30"),
        en=L("What were Isa's first words, still in the cradle?",
             ["\"I am the servant of Allah; He gave me the Scripture and made me a prophet\"", "\"I am the son of God\"", "\"I am a king\"", "\"I am hungry\""], 0,
             "\"He said: indeed, I am the servant of Allah. He has given me the Scripture and made me a prophet.\"",
             "Quran — Surah Maryam, 19:30"),
        ar=L("ما أول ما تكلّم به عيسى وهو في المهد؟",
             ["«إني عبد الله آتاني الكتاب وجعلني نبيًا»", "«أنا ابن الله»", "«أنا ملك»", "«أنا جائع»"], 0,
             "﴿قال إني عبد الله آتاني الكتاب وجعلني نبيًا﴾.",
             "القرآن — سورة مريم، 19:30"))

    add("prophets_149", "prophets", "easy", "quran", Q, "7:23", False,
        fr=L("Que dirent Âdam et son épouse à Allah après avoir mangé de l'arbre ?",
             ["« Seigneur, nous nous sommes fait du tort ; si Tu ne nous pardonnes pas, nous serons perdus »", "« Ce n'est pas notre faute »", "« C'est la faute de l'arbre »", "Ils ne dirent rien"], 0,
             "« Seigneur, nous nous sommes fait du tort à nous-mêmes ; si Tu ne nous pardonnes pas et ne nous fais pas miséricorde, nous serons du nombre des perdants. »",
             "Coran — Sourate Al-A'râf, 7:23"),
        en=L("What did Adam and his wife say to Allah after eating from the tree?",
             ["\"Our Lord, we have wronged ourselves; if You do not forgive us, we will be lost\"", "\"It was not our fault\"", "\"It was the tree's fault\"", "They said nothing"], 0,
             "\"Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.\"",
             "Quran — Surah Al-A'raf, 7:23"),
        ar=L("ماذا قال آدم وزوجه لله بعد أكلهما من الشجرة؟",
             ["«ربنا ظلمنا أنفسنا وإن لم تغفر لنا وترحمنا لنكونن من الخاسرين»", "«ليس ذنبنا»", "«الذنب ذنب الشجرة»", "لم يقولا شيئًا"], 0,
             "﴿ربنا ظلمنا أنفسنا وإن لم تغفر لنا وترحمنا لنكونن من الخاسرين﴾.",
             "القرآن — سورة الأعراف، 7:23"))

    add("prophets_150", "prophets", "easy", "quran", Q, "71:1", False,
        fr=L("Quelle mission Allah confia-t-Il à Nûh envers son peuple, selon le premier verset de la sourate Nûh ?",
             ["Les avertir avant qu'un châtiment douloureux ne les atteigne", "Construire une ville", "Leur apprendre à pêcher", "Les faire rois"], 0,
             "« Nous avons envoyé Nûh vers son peuple : avertis ton peuple avant que ne leur vienne un châtiment douloureux. »",
             "Coran — Sourate Nûh, 71:1"),
        en=L("What mission did Allah give Nuh towards his people, in the first verse of Surah Nuh?",
             ["To warn them before a painful punishment came to them", "To build a city", "To teach them fishing", "To make them kings"], 0,
             "\"We sent Nuh to his people: warn your people before there comes to them a painful punishment.\"",
             "Quran — Surah Nuh, 71:1"),
        ar=L("ما المهمة التي كلّف الله بها نوحًا تجاه قومه في أول سورة نوح؟",
             ["أن ينذرهم قبل أن يأتيهم عذاب أليم", "أن يبني مدينة", "أن يعلّمهم الصيد", "أن يجعلهم ملوكًا"], 0,
             "﴿إنا أرسلنا نوحًا إلى قومه أن أنذر قومك من قبل أن يأتيهم عذاب أليم﴾.",
             "القرآن — سورة نوح، 71:1"))
