"""Qur'an — part B (quran_025 … quran_080)."""

WT = "well-established terminology"


def register(add, L):
    Q = "Quran"
    B = "Sahih al-Bukhari"
    M = "Sahih Muslim"

    add("quran_025", "quran", "easy", "quran", Q, "105:1", False,
        fr=L("Quelle sourate porte le nom de l'éléphant ?",
             ["Al-Fîl", "An-Nahl", "An-Naml", "Al-Baqara"], 0,
             "La sourate 105, Al-Fîl (« L'Éléphant »), rappelle l'armée d'éléphants d'Abraha, arrêtée avant La Mecque.",
             "Coran 105:1"),
        en=L("Which surah is named after the elephant?",
             ["Al-Fil", "An-Nahl", "An-Naml", "Al-Baqara"], 0,
             "Surah 105, Al-Fil (\"The Elephant\"), recalls Abraha's army of elephants, stopped before Makkah.",
             "Qur'an 105:1"),
        ar=L("أي سورة سُمّيت باسم الفيل؟",
             ["الفيل", "النحل", "النمل", "البقرة"], 0,
             "سورة الفيل (105) تذكّر بجيش أبرهة وفيلته الذي رُدّ قبل بلوغ مكة.",
             "القرآن 105:1"))

    add("quran_026", "quran", "easy", "quran", Q, "16:68", False,
        fr=L("La sourate An-Nahl porte le nom de quel insecte ?",
             ["L'abeille", "La fourmi", "L'araignée", "La mouche"], 0,
             "An-Nahl signifie « les abeilles » ; Allah y révèle à l'abeille de bâtir ses demeures (16:68).",
             "Coran 16:68"),
        en=L("Surah An-Nahl is named after which insect?",
             ["The bee", "The ant", "The spider", "The fly"], 0,
             "An-Nahl means \"the bees\"; in it Allah inspires the bee to build its homes (16:68).",
             "Qur'an 16:68"),
        ar=L("سورة النحل سُمّيت باسم أي حشرة؟",
             ["النحلة", "النملة", "العنكبوت", "الذبابة"], 0,
             "النحل هو اسم السورة، وفيها أوحى الله إلى النحل أن تتخذ من الجبال بيوتًا (16:68).",
             "القرآن 16:68"))

    add("quran_027", "quran", "easy", "quran", Q, "27:18", False,
        fr=L("Quelle sourate porte le nom de la fourmi ?",
             ["An-Naml", "An-Nahl", "Al-'Ankabût", "Al-An'âm"], 0,
             "An-Naml (« Les Fourmis », sourate 27) raconte la fourmi qui avertit les siennes du passage de l'armée de Sulaymân.",
             "Coran 27:18"),
        en=L("Which surah is named after the ant?",
             ["An-Naml", "An-Nahl", "Al-'Ankabut", "Al-An'am"], 0,
             "An-Naml (\"The Ants\", surah 27) tells of the ant that warned its fellows as Sulayman's army approached.",
             "Qur'an 27:18"),
        ar=L("أي سورة سُمّيت باسم النملة؟",
             ["النمل", "النحل", "العنكبوت", "الأنعام"], 0,
             "سورة النمل (27) تروي قصة النملة التي حذّرت النمل من جيش سليمان.",
             "القرآن 27:18"))

    add("quran_028", "quran", "medium", "quran", Q, "29:41", False,
        fr=L("À quoi le Coran compare-t-il ceux qui prennent des protecteurs en dehors d'Allah, dans la sourate Al-'Ankabût ?",
             ["À l'araignée qui se bâtit une maison fragile", "À l'abeille qui bâtit sa ruche", "À la fourmi qui amasse", "Au chien qui halète"], 0,
             "« La plus fragile des maisons est celle de l'araignée » (29:41) : d'où le nom de la sourate.",
             "Coran 29:41"),
        en=L("In Surah Al-'Ankabut, what does the Qur'an compare those who take protectors besides Allah to?",
             ["A spider building a flimsy house", "A bee building its hive", "An ant storing food", "A panting dog"], 0,
             "\"The frailest of houses is the spider's house\" (29:41), which gives the surah its name.",
             "Qur'an 29:41"),
        ar=L("بماذا شبّه القرآن من اتخذوا من دون الله أولياء في سورة العنكبوت؟",
             ["بالعنكبوت التي تتخذ بيتًا واهنًا", "بالنحلة التي تبني خليتها", "بالنملة التي تدّخر", "بالكلب الذي يلهث"], 0,
             "«وإن أوهن البيوت لبيت العنكبوت» (29:41)، ومن هنا اسم السورة.",
             "القرآن 29:41"))

    add("quran_029", "quran", "easy", "quran", Q, "2:67", False,
        fr=L("La sourate Al-Baqara porte le nom de quel animal ?",
             ["La vache", "Le chameau", "Le cheval", "Le mouton"], 0,
             "Al-Baqara (« La Vache ») rappelle la vache que les Enfants d'Israël furent ordonnés d'immoler (2:67).",
             "Coran 2:67"),
        en=L("Surah Al-Baqara is named after which animal?",
             ["The cow", "The camel", "The horse", "The sheep"], 0,
             "Al-Baqara (\"The Cow\") recalls the cow the Children of Israel were commanded to sacrifice (2:67).",
             "Qur'an 2:67"),
        ar=L("سورة البقرة سُمّيت باسم أي حيوان؟",
             ["البقرة", "الجمل", "الحصان", "الخروف"], 0,
             "سُمّيت بالبقرة التي أُمر بنو إسرائيل بذبحها (2:67).",
             "القرآن 2:67"))

    add("quran_030", "quran", "medium", "quran", Q, "6:136", False,
        fr=L("Que signifie le titre de la sourate 6, Al-An'âm ?",
             ["Les bestiaux", "Les oiseaux", "Les jardins", "Les étoiles"], 0,
             "Al-An'âm signifie « les bestiaux » : la sourate réfute les interdits que les païens inventaient sur le bétail.",
             "Coran 6:136"),
        en=L("What does the title of surah 6, Al-An'am, mean?",
             ["The cattle", "The birds", "The gardens", "The stars"], 0,
             "Al-An'am means \"the cattle\"; the surah refutes the pagans' invented rules about livestock.",
             "Qur'an 6:136"),
        ar=L("ما معنى عنوان السورة السادسة «الأنعام»؟",
             ["الماشية من الإبل والبقر والغنم", "الطيور", "الجنات", "النجوم"], 0,
             "الأنعام هي الإبل والبقر والغنم، وقد ردّت السورة على ما ابتدعه المشركون في شأنها.",
             "القرآن 6:136"))

    add("quran_031", "quran", "medium", "quran", Q, "55:13", False,
        fr=L("Quel verset revient de nombreuses fois dans la sourate Ar-Rahmân ?",
             ["« Lequel des bienfaits de votre Seigneur nierez-vous ? »", "« Allah est le plus Grand »", "« Dis : Il est Allah, Unique »", "« Louange à Allah »"], 0,
             "Ce refrain (« Fa-bi-ayyi âlâ'i rabbikumâ tukadhdhibân ») est répété 31 fois dans la sourate 55.",
             "Coran 55:13"),
        en=L("Which verse is repeated many times in Surah Ar-Rahman?",
             ["\"Which of the favours of your Lord will you deny?\"", "\"Allah is the Greatest\"", "\"Say: He is Allah, One\"", "\"Praise be to Allah\""], 0,
             "This refrain (\"Fa-bi-ayyi ala'i rabbikuma tukadhdhiban\") recurs 31 times in surah 55.",
             "Qur'an 55:13"),
        ar=L("ما الآية التي تتكرر مرات كثيرة في سورة الرحمن؟",
             ["«فبأي آلاء ربكما تكذبان»", "«الله أكبر»", "«قل هو الله أحد»", "«الحمد لله»"], 0,
             "تتكرر آية «فبأي آلاء ربكما تكذبان» إحدى وثلاثين مرة في سورة الرحمن.",
             "القرآن 55:13"))

    add("quran_032", "quran", "hard", "quran", Q, "18:25", False,
        fr=L("Selon la sourate Al-Kahf, combien de temps les Gens de la Caverne dormirent-ils ?",
             ["Trois cents ans, plus neuf", "Cent ans", "Quarante ans", "Mille ans"], 0,
             "« Ils demeurèrent dans leur caverne trois cents ans et en ajoutèrent neuf » (18:25).",
             "Coran 18:25"),
        en=L("According to Surah Al-Kahf, how long did the People of the Cave sleep?",
             ["Three hundred years, plus nine", "A hundred years", "Forty years", "A thousand years"], 0,
             "\"They stayed in their cave three hundred years, and added nine\" (18:25).",
             "Qur'an 18:25"),
        ar=L("بحسب سورة الكهف، كم لبث أصحاب الكهف نائمين؟",
             ["ثلاثمائة سنة وازدادوا تسعًا", "مائة سنة", "أربعين سنة", "ألف سنة"], 0,
             "«ولبثوا في كهفهم ثلاث مائة سنين وازدادوا تسعًا» (18:25).",
             "القرآن 18:25"))

    add("quran_033", "quran", "easy", "quran", Q, "18:18", False,
        fr=L("Quel animal accompagnait les Gens de la Caverne ?",
             ["Un chien", "Un chat", "Un âne", "Une chèvre"], 0,
             "« Leur chien étendait ses pattes à l'entrée » (18:18).",
             "Coran 18:18"),
        en=L("Which animal was with the People of the Cave?",
             ["A dog", "A cat", "A donkey", "A goat"], 0,
             "\"Their dog stretched its forelegs at the entrance\" (18:18).",
             "Qur'an 18:18"),
        ar=L("أي حيوان كان مع أصحاب الكهف؟",
             ["كلب", "قط", "حمار", "ماعز"], 0,
             "«وكلبهم باسط ذراعيه بالوصيد» (18:18).",
             "القرآن 18:18"))

    add("quran_034", "quran", "medium", "quran", Q, "18:94", False,
        fr=L("Contre quels peuples Dhûl-Qarnayn bâtit-il une barrière, selon Al-Kahf ?",
             ["Ya'jûj et Ma'jûj (Gog et Magog)", "'Âd et Thamûd", "Les Romains", "Les Perses"], 0,
             "Un peuple lui demanda protection contre Ya'jûj et Ma'jûj ; il édifia un rempart de fer et de cuivre (18:94-96).",
             "Coran 18:94"),
        en=L("Against which peoples did Dhul-Qarnayn build a barrier, according to Al-Kahf?",
             ["Ya'juj and Ma'juj (Gog and Magog)", "'Ad and Thamud", "The Romans", "The Persians"], 0,
             "A people asked him for protection from Ya'juj and Ma'juj; he raised a rampart of iron and copper (18:94-96).",
             "Qur'an 18:94"),
        ar=L("ضدّ من بنى ذو القرنين السدّ بحسب سورة الكهف؟",
             ["يأجوج ومأجوج", "عاد وثمود", "الروم", "الفرس"], 0,
             "طلب منه قوم أن يجعل بينهم وبين يأجوج ومأجوج سدًّا، فبناه من الحديد والنحاس (18:94-96).",
             "القرآن 18:94"))

    add("quran_035", "quran", "medium", "quran", Q, "24:35", False,
        fr=L("Quel verset commence par « Allah est la Lumière des cieux et de la terre » ?",
             ["Le verset de la Lumière (An-Nûr 24:35)", "Le verset du Trône", "Le verset de la Dette", "Le verset de la Caverne"], 0,
             "« Âyat an-Nûr » compare Sa lumière à une niche où brille une lampe (24:35).",
             "Coran 24:35"),
        en=L("Which verse begins \"Allah is the Light of the heavens and the earth\"?",
             ["The Verse of Light (An-Nur 24:35)", "The Throne Verse", "The Verse of Debt", "The Verse of the Cave"], 0,
             "\"Ayat an-Nur\" likens His light to a niche in which a lamp shines (24:35).",
             "Qur'an 24:35"),
        ar=L("أي آية تبدأ بقوله تعالى: «الله نور السماوات والأرض»؟",
             ["آية النور (24:35)", "آية الكرسي", "آية الدَّين", "آية الكهف"], 0,
             "آية النور تشبّه نوره بمشكاة فيها مصباح (24:35).",
             "القرآن 24:35"))

    add("quran_036", "quran", "easy", "hadithBukhari", B, "5013", False,
        fr=L("Selon un hadith rapporté par al-Bukhârî, quelle sourate équivaut au tiers du Coran ?",
             ["Al-Ikhlâs", "Al-Fâtiha", "Yâ-Sîn", "Al-Kahf"], 0,
             "Le Prophète ﷺ dit de « Qul huwa Allâhu ahad » qu'elle « équivaut au tiers du Coran ».",
             "Sahîh al-Bukhârî, 5013"),
        en=L("According to a hadith in al-Bukhari, which surah is equal to a third of the Qur'an?",
             ["Al-Ikhlas", "Al-Fatiha", "Ya-Sin", "Al-Kahf"], 0,
             "The Prophet ﷺ said of \"Qul huwa Allahu ahad\" that it \"is equal to a third of the Qur'an\".",
             "Sahih al-Bukhari, 5013"),
        ar=L("بحسب حديث رواه البخاري، أي سورة تعدل ثلث القرآن؟",
             ["الإخلاص", "الفاتحة", "يس", "الكهف"], 0,
             "قال النبي ﷺ عن «قل هو الله أحد»: «إنها لتعدل ثلث القرآن».",
             "صحيح البخاري، 5013"))

    add("quran_037", "quran", "medium", "hadithMuslim", M, "810", False,
        fr=L("Quel verset le Prophète ﷺ désigna-t-il comme le plus grand du Coran, selon Sahîh Muslim ?",
             ["Le verset du Trône (Âyat al-Kursî)", "Le premier verset d'Al-Fâtiha", "Le dernier verset d'Al-Baqara", "Le verset de la Lumière"], 0,
             "Il demanda à Ubayy ibn Ka'b quel verset était le plus grand ; Ubayy répondit Âyat al-Kursî, et le Prophète ﷺ le félicita.",
             "Sahîh Muslim, 810"),
        en=L("Which verse did the Prophet ﷺ name as the greatest in the Qur'an, according to Sahih Muslim?",
             ["The Throne Verse (Ayat al-Kursi)", "The first verse of Al-Fatiha", "The last verse of Al-Baqara", "The Verse of Light"], 0,
             "He asked Ubayy ibn Ka'b which verse was greatest; Ubayy answered Ayat al-Kursi, and the Prophet ﷺ congratulated him.",
             "Sahih Muslim, 810"),
        ar=L("أي آية سمّاها النبي ﷺ أعظم آية في القرآن بحسب صحيح مسلم؟",
             ["آية الكرسي", "أول آية في الفاتحة", "آخر آية في البقرة", "آية النور"], 0,
             "سأل النبي ﷺ أُبيّ بن كعب عن أعظم آية، فأجاب: آية الكرسي، فقال له: «ليهنك العلم أبا المنذر».",
             "صحيح مسلم، 810"))

    add("quran_038", "quran", "easy", "quran", Q, "111:1", False,
        fr=L("Quel ennemi du Prophète ﷺ est nommé dans la sourate Al-Masad ?",
             ["Abû Lahab", "Abû Jahl", "Abû Sufyân", "Al-Walîd"], 0,
             "« Que périssent les deux mains d'Abû Lahab » (111:1) : cet oncle du Prophète ﷺ le combattait ouvertement.",
             "Coran 111:1"),
        en=L("Which enemy of the Prophet ﷺ is named in Surah Al-Masad?",
             ["Abu Lahab", "Abu Jahl", "Abu Sufyan", "Al-Walid"], 0,
             "\"May the hands of Abu Lahab perish\" (111:1): this uncle of the Prophet ﷺ fought him openly.",
             "Qur'an 111:1"),
        ar=L("أي عدوّ للنبي ﷺ ذُكر باسمه في سورة المسد؟",
             ["أبو لهب", "أبو جهل", "أبو سفيان", "الوليد"], 0,
             "«تبّت يدا أبي لهب وتبّ» (111:1)، وهو عمّ النبي ﷺ الذي ناصبه العداء.",
             "القرآن 111:1"))

    add("quran_039", "quran", "easy", "quran", Q, "109:6", False,
        fr=L("Comment se termine la sourate Al-Kâfirûn ?",
             ["« À vous votre religion, et à moi ma religion »", "« Allah est le plus Grand »", "« Et Il n'a nul égal »", "« Contre le mal de l'envieux »"], 0,
             "« Lakum dînukum wa liya dîn » (109:6) affirme la séparation nette entre l'islam et l'idolâtrie.",
             "Coran 109:6"),
        en=L("How does Surah Al-Kafirun end?",
             ["\"To you your religion, and to me my religion\"", "\"Allah is the Greatest\"", "\"And there is none like Him\"", "\"From the evil of the envier\""], 0,
             "\"Lakum dinukum wa liya din\" (109:6) states the clear separation between Islam and idolatry.",
             "Qur'an 109:6"),
        ar=L("بماذا تُختم سورة الكافرون؟",
             ["«لكم دينكم ولي دين»", "«الله أكبر»", "«ولم يكن له كفوًا أحد»", "«ومن شر حاسد إذا حسد»"], 0,
             "«لكم دينكم ولي دين» (109:6) تقرر البراءة التامة من الشرك.",
             "القرآن 109:6"))

    add("quran_040", "quran", "medium", "quran", Q, "110:1-2", False,
        fr=L("De quoi parle la sourate An-Nasr ?",
             ["Du secours d'Allah et des gens entrant en foule dans la religion", "De la création du ciel", "Du jeûne de Ramadan", "Du récit de Yûsuf"], 0,
             "« Lorsque vient le secours d'Allah et la victoire, et que tu vois les gens entrer en foule dans la religion d'Allah » (110:1-2).",
             "Coran 110:1-2"),
        en=L("What is Surah An-Nasr about?",
             ["Allah's help and people entering the religion in crowds", "The creation of the sky", "Fasting in Ramadan", "The story of Yusuf"], 0,
             "\"When Allah's help and victory come, and you see people entering Allah's religion in crowds\" (110:1-2).",
             "Qur'an 110:1-2"),
        ar=L("عن ماذا تتحدث سورة النصر؟",
             ["عن نصر الله ودخول الناس في الدين أفواجًا", "عن خلق السماء", "عن صيام رمضان", "عن قصة يوسف"], 0,
             "«إذا جاء نصر الله والفتح ورأيت الناس يدخلون في دين الله أفواجًا» (110:1-2).",
             "القرآن 110:1-2"))

    add("quran_041", "quran", "easy", "quran", Q, "103:1-3", False,
        fr=L("Selon la sourate Al-'Asr, qui échappe à la perte ?",
             ["Ceux qui croient, font le bien, se recommandent la vérité et la patience", "Ceux qui sont riches", "Ceux qui sont forts", "Ceux qui voyagent"], 0,
             "« L'homme est certes en perte, sauf ceux qui croient, accomplissent les bonnes œuvres, s'enjoignent la vérité et la patience » (103:2-3).",
             "Coran 103:1-3"),
        en=L("According to Surah Al-'Asr, who is saved from loss?",
             ["Those who believe, do good, and urge one another to truth and patience", "Those who are rich", "Those who are strong", "Those who travel"], 0,
             "\"Man is in loss, except those who believe, do righteous deeds, and urge one another to truth and to patience\" (103:2-3).",
             "Qur'an 103:1-3"),
        ar=L("بحسب سورة العصر، من الذين لا يكونون في خسر؟",
             ["الذين آمنوا وعملوا الصالحات وتواصوا بالحق وبالصبر", "الأغنياء", "الأقوياء", "المسافرون"], 0,
             "«إن الإنسان لفي خسر إلا الذين آمنوا وعملوا الصالحات وتواصوا بالحق وتواصوا بالصبر» (103:2-3).",
             "القرآن 103:1-3"))

    add("quran_042", "quran", "hard", "quran", Q, "107:1-3", False,
        fr=L("Dans la sourate Al-Mâ'ûn, que fait « celui qui traite de mensonge la Rétribution » ?",
             ["Il repousse l'orphelin et n'encourage pas à nourrir le pauvre", "Il détruit les mosquées", "Il refuse de voyager", "Il ment sur ses biens"], 0,
             "« C'est celui qui repousse l'orphelin et n'encourage point à nourrir le pauvre » (107:2-3).",
             "Coran 107:1-3"),
        en=L("In Surah Al-Ma'un, what does \"the one who denies the Judgement\" do?",
             ["He repulses the orphan and does not urge feeding the poor", "He destroys mosques", "He refuses to travel", "He lies about his wealth"], 0,
             "\"That is the one who repulses the orphan and does not urge the feeding of the poor\" (107:2-3).",
             "Qur'an 107:1-3"),
        ar=L("في سورة الماعون، ماذا يفعل «الذي يكذّب بالدين»؟",
             ["يدعّ اليتيم ولا يحضّ على طعام المسكين", "يهدم المساجد", "يرفض السفر", "يكذب في ماله"], 0,
             "«فذلك الذي يدعّ اليتيم ولا يحضّ على طعام المسكين» (107:2-3).",
             "القرآن 107:1-3"))

    add("quran_043", "quran", "medium", "quran", Q, "96:2", False,
        fr=L("Selon les premiers versets révélés (Al-'Alaq), à partir de quoi Allah a-t-Il créé l'homme ?",
             ["D'une adhérence ('alaq)", "De lumière", "De feu", "De vent"], 0,
             "« Lis, au nom de ton Seigneur qui a créé, qui a créé l'homme d'une adhérence » (96:1-2).",
             "Coran 96:2"),
        en=L("According to the first revealed verses (Al-'Alaq), from what did Allah create man?",
             ["A clinging clot ('alaq)", "Light", "Fire", "Wind"], 0,
             "\"Read, in the name of your Lord who created, who created man from a clinging clot\" (96:1-2).",
             "Qur'an 96:2"),
        ar=L("بحسب أول ما نزل من القرآن (سورة العلق)، مِمّ خلق الله الإنسان؟",
             ["من علق", "من نور", "من نار", "من ريح"], 0,
             "«اقرأ باسم ربك الذي خلق، خلق الإنسان من علق» (96:1-2).",
             "القرآن 96:2"))

    add("quran_044", "quran", "hard", "quran", Q, "15:87", False,
        fr=L("Que désigne l'expression coranique « les sept versets répétés » (as-sab' al-mathânî) ?",
             ["Al-Fâtiha", "Les sept sourates les plus longues", "Âyat al-Kursî", "Les sept derniers versets du Coran"], 0,
             "« Nous t'avons donné sept versets que l'on répète, et le Coran sublime » (15:87) : c'est Al-Fâtiha, récitée à chaque rak'a.",
             "Coran 15:87"),
        en=L("What does the Qur'anic phrase \"the seven oft-repeated verses\" (as-sab' al-mathani) refer to?",
             ["Al-Fatiha", "The seven longest surahs", "Ayat al-Kursi", "The last seven verses of the Qur'an"], 0,
             "\"We have given you seven of the oft-repeated and the great Qur'an\" (15:87): Al-Fatiha, recited in every rak'ah.",
             "Qur'an 15:87"),
        ar=L("ما المراد بـ«السبع المثاني» في القرآن؟",
             ["سورة الفاتحة", "السور السبع الطوال", "آية الكرسي", "آخر سبع آيات في القرآن"], 0,
             "«ولقد آتيناك سبعًا من المثاني والقرآن العظيم» (15:87)، وهي الفاتحة التي تُكرَّر في كل ركعة.",
             "القرآن 15:87"))

    add("quran_045", "quran", "medium", "quran", Q, "25:1", False,
        fr=L("Que signifie « Al-Furqân », l'un des noms du Coran ?",
             ["Le Discernement (entre vrai et faux)", "La Lumière", "Le Rappel", "La Guérison"], 0,
             "« Béni soit Celui qui a fait descendre le Furqân sur Son serviteur » (25:1) : le Livre qui distingue le vrai du faux.",
             "Coran 25:1"),
        en=L("What does \"Al-Furqan\", one of the names of the Qur'an, mean?",
             ["The Criterion (between truth and falsehood)", "The Light", "The Reminder", "The Healing"], 0,
             "\"Blessed is He who sent down the Furqan upon His servant\" (25:1): the Book that separates truth from falsehood.",
             "Qur'an 25:1"),
        ar=L("ما معنى «الفرقان»، وهو من أسماء القرآن؟",
             ["الفارق بين الحق والباطل", "النور", "الذكر", "الشفاء"], 0,
             "«تبارك الذي نزّل الفرقان على عبده» (25:1)، فهو الكتاب الذي يفرق بين الحق والباطل.",
             "القرآن 25:1"))

    add("quran_046", "quran", "hard", "quran", Q, "52:1", False,
        fr=L("Par quoi Allah jure-t-Il au début de la sourate At-Tûr ?",
             ["Par le Mont (Tûr)", "Par le soleil", "Par le figuier", "Par la nuit"], 0,
             "« Par le Mont ! Et par un Livre écrit… » (52:1-2) : le Tûr est la montagne où Mûsâ reçut la révélation.",
             "Coran 52:1"),
        en=L("By what does Allah swear at the start of Surah At-Tur?",
             ["By the Mount (Tur)", "By the sun", "By the fig", "By the night"], 0,
             "\"By the Mount! And by a Book inscribed…\" (52:1-2): the Tur is the mountain where Musa received revelation.",
             "Qur'an 52:1"),
        ar=L("بماذا أقسم الله في مطلع سورة الطور؟",
             ["بالطور", "بالشمس", "بالتين", "بالليل"], 0,
             "«والطور وكتاب مسطور» (52:1-2)، والطور هو الجبل الذي كلّم الله عنده موسى.",
             "القرآن 52:1"))

    add("quran_047", "quran", "medium", "quran", Q, "53:1", False,
        fr=L("Que signifie « An-Najm », titre de la sourate 53 ?",
             ["L'étoile", "La lune", "Le soleil", "L'aube"], 0,
             "« Par l'étoile quand elle décline ! » (53:1).",
             "Coran 53:1"),
        en=L("What does \"An-Najm\", the title of surah 53, mean?",
             ["The star", "The moon", "The sun", "The dawn"], 0,
             "\"By the star when it descends!\" (53:1).",
             "Qur'an 53:1"),
        ar=L("ما معنى «النجم» عنوان السورة الثالثة والخمسين؟",
             ["الكوكب المضيء في السماء", "القمر", "الشمس", "الفجر"], 0,
             "«والنجم إذا هوى» (53:1).",
             "القرآن 53:1"))

    add("quran_048", "quran", "medium", "quran", Q, "97:4", False,
        fr=L("Selon la sourate Al-Qadr, qui descend durant la Nuit du Destin ?",
             ["Les anges et l'Esprit (Jibrîl)", "Les prophètes", "Les djinns", "Les vents"], 0,
             "« Durant celle-ci descendent les anges ainsi que l'Esprit, par permission de leur Seigneur » (97:4).",
             "Coran 97:4"),
        en=L("According to Surah Al-Qadr, who descends during the Night of Decree?",
             ["The angels and the Spirit (Jibril)", "The prophets", "The jinn", "The winds"], 0,
             "\"The angels and the Spirit descend therein by permission of their Lord\" (97:4).",
             "Qur'an 97:4"),
        ar=L("بحسب سورة القدر، من ينزل في ليلة القدر؟",
             ["الملائكة والروح (جبريل)", "الأنبياء", "الجن", "الرياح"], 0,
             "«تنزّل الملائكة والروح فيها بإذن ربهم» (97:4).",
             "القرآن 97:4"))

    add("quran_049", "quran", "easy", "quran", Q, "17:82", False,
        fr=L("Selon le Coran, qu'est-ce que le Coran pour les croyants ?",
             ["Une guérison et une miséricorde", "Un simple poème", "Un livre d'histoire", "Un calendrier"], 0,
             "« Nous faisons descendre du Coran ce qui est guérison et miséricorde pour les croyants » (17:82).",
             "Coran 17:82"),
        en=L("According to the Qur'an, what is the Qur'an for the believers?",
             ["A healing and a mercy", "Just a poem", "A history book", "A calendar"], 0,
             "\"We send down of the Qur'an that which is healing and mercy for the believers\" (17:82).",
             "Qur'an 17:82"),
        ar=L("بحسب القرآن، ماذا يكون القرآن للمؤمنين؟",
             ["شفاء ورحمة", "مجرد شعر", "كتاب تاريخ", "تقويم"], 0,
             "«وننزّل من القرآن ما هو شفاء ورحمة للمؤمنين» (17:82).",
             "القرآن 17:82"))

    add("quran_050", "quran", "hard", "quran", Q, "2:23", False,
        fr=L("Quel défi le Coran lance-t-il à ceux qui doutent de son origine divine ?",
             ["Produire une seule sourate semblable", "Réciter tout le Coran par cœur", "Traduire le Coran", "Construire une mosquée"], 0,
             "« Si vous avez un doute sur ce que Nous avons révélé, produisez donc une sourate semblable » (2:23).",
             "Coran 2:23"),
        en=L("What challenge does the Qur'an set for those who doubt its divine origin?",
             ["Produce a single surah like it", "Recite the whole Qur'an by heart", "Translate the Qur'an", "Build a mosque"], 0,
             "\"If you are in doubt about what We have sent down, then produce a surah like it\" (2:23).",
             "Qur'an 2:23"),
        ar=L("ما التحدي الذي وجّهه القرآن لمن شكّ في مصدره الإلهي؟",
             ["أن يأتوا بسورة من مثله", "أن يحفظوا القرآن كله", "أن يترجموا القرآن", "أن يبنوا مسجدًا"], 0,
             "«وإن كنتم في ريب مما نزّلنا على عبدنا فأتوا بسورة من مثله» (2:23).",
             "القرآن 2:23"))

    add("quran_051", "quran", "medium", "hadithBukhari", B, "4704", False,
        fr=L("Quelle sourate est appelée « Umm al-Qur'ân » (la Mère du Coran) ?",
             ["Al-Fâtiha", "Al-Baqara", "Yâ-Sîn", "Al-Ikhlâs"], 0,
             "Le Prophète ﷺ dit : « Umm al-Qur'ân, ce sont les sept versets répétés et le Coran sublime. »",
             "Sahîh al-Bukhârî, 4704"),
        en=L("Which surah is called \"Umm al-Qur'an\" (the Mother of the Qur'an)?",
             ["Al-Fatiha", "Al-Baqara", "Ya-Sin", "Al-Ikhlas"], 0,
             "The Prophet ﷺ said: \"Umm al-Qur'an is the seven oft-repeated verses and the great Qur'an.\"",
             "Sahih al-Bukhari, 4704"),
        ar=L("أي سورة تُسمّى «أمّ القرآن»؟",
             ["الفاتحة", "البقرة", "يس", "الإخلاص"], 0,
             "قال النبي ﷺ: «أم القرآن هي السبع المثاني والقرآن العظيم».",
             "صحيح البخاري، 4704"))

    add("quran_052", "quran", "medium", "quran", Q, WT + " (makki / madani)", False,
        fr=L("Qu'est-ce qu'une sourate « mecquoise » (makkiyya) ?",
             ["Une sourate révélée avant l'Hégire", "Une sourate révélée à Médine", "Une sourate sur la Ka'ba", "Une sourate très courte"], 0,
             "Les savants classent les sourates selon la période : avant l'émigration à Médine (mecquoises) ou après (médinoises).",
             "Terminologie établie des sciences du Coran"),
        en=L("What is a \"Makki\" surah?",
             ["A surah revealed before the Hijra", "A surah revealed in Madinah", "A surah about the Ka'ba", "A very short surah"], 0,
             "Scholars classify surahs by period: before the migration to Madinah (Makki) or after it (Madani).",
             "Established terminology of Qur'anic sciences"),
        ar=L("ما المقصود بالسورة «المكية»؟",
             ["السورة التي نزلت قبل الهجرة", "السورة التي نزلت في المدينة", "السورة التي تتحدث عن الكعبة", "السورة القصيرة جدًا"], 0,
             "يقسّم العلماء السور بحسب زمن نزولها: قبل الهجرة إلى المدينة (مكية) أو بعدها (مدنية).",
             "مصطلح مستقر في علوم القرآن"))

    add("quran_053", "quran", "hard", "quran", Q, "2:1; 3:1; 29:1; 30:1; 31:1; 32:1", False,
        fr=L("Combien de sourates commencent par les lettres « Alif, Lâm, Mîm » ?",
             ["Six", "Deux", "Dix", "Une"], 0,
             "Al-Baqara, Âl 'Imrân, Al-'Ankabût, Ar-Rûm, Luqmân et As-Sajda s'ouvrent sur « Alif, Lâm, Mîm ».",
             "Coran 2:1, 3:1, 29:1, 30:1, 31:1, 32:1"),
        en=L("How many surahs begin with the letters \"Alif, Lam, Mim\"?",
             ["Six", "Two", "Ten", "One"], 0,
             "Al-Baqara, Al 'Imran, Al-'Ankabut, Ar-Rum, Luqman and As-Sajda open with \"Alif, Lam, Mim\".",
             "Qur'an 2:1, 3:1, 29:1, 30:1, 31:1, 32:1"),
        ar=L("كم سورة تبدأ بالحروف «الم»؟",
             ["ست", "اثنتان", "عشر", "واحدة"], 0,
             "تبدأ بـ«الم» سور: البقرة، وآل عمران، والعنكبوت، والروم، ولقمان، والسجدة.",
             "القرآن 2:1، 3:1، 29:1، 30:1، 31:1، 32:1"))

    add("quran_054", "quran", "hard", "quran", Q, WT + " (al-huruf al-muqatta'a)", False,
        fr=L("Comment appelle-t-on les lettres isolées qui ouvrent certaines sourates (Alif Lâm Mîm, Yâ Sîn, Qâf…) ?",
             ["Les lettres détachées (al-hurûf al-muqatta'a)", "Les versets abrogés", "Les lettres solaires", "Les lettres de tajwîd"], 0,
             "Vingt-neuf sourates s'ouvrent sur ces lettres, dont seul Allah connaît pleinement le sens.",
             "Terminologie établie des sciences du Coran"),
        en=L("What are the isolated letters that open some surahs (Alif Lam Mim, Ya Sin, Qaf…) called?",
             ["The disconnected letters (al-huruf al-muqatta'a)", "The abrogated verses", "The sun letters", "The tajwid letters"], 0,
             "Twenty-nine surahs open with these letters, whose full meaning Allah alone knows.",
             "Established terminology of Qur'anic sciences"),
        ar=L("ماذا تُسمّى الحروف المفردة التي تُفتتح بها بعض السور (الم، يس، ق…)؟",
             ["الحروف المقطّعة", "الآيات المنسوخة", "الحروف الشمسية", "حروف التجويد"], 0,
             "تُفتتح تسع وعشرون سورة بهذه الحروف، والله أعلم بمرادها.",
             "مصطلح مستقر في علوم القرآن"))

    add("quran_055", "quran", "easy", "quran", Q, "47:2", False,
        fr=L("Quelle sourate porte le nom du Prophète Muhammad ﷺ ?",
             ["La sourate 47, Muhammad", "La sourate 1, Al-Fâtiha", "La sourate 36, Yâ-Sîn", "La sourate 112, Al-Ikhlâs"], 0,
             "La sourate 47 se nomme « Muhammad » ; elle cite son nom au verset 2.",
             "Coran 47:2"),
        en=L("Which surah is named after the Prophet Muhammad ﷺ?",
             ["Surah 47, Muhammad", "Surah 1, Al-Fatiha", "Surah 36, Ya-Sin", "Surah 112, Al-Ikhlas"], 0,
             "Surah 47 is called \"Muhammad\"; it mentions his name in verse 2.",
             "Qur'an 47:2"),
        ar=L("أي سورة سُمّيت باسم النبي محمد ﷺ؟",
             ["السورة 47، محمد", "السورة 1، الفاتحة", "السورة 36، يس", "السورة 112، الإخلاص"], 0,
             "سورة محمد هي السورة السابعة والأربعون، وقد ذُكر اسمه ﷺ في الآية الثانية منها.",
             "القرآن 47:2"))

    add("quran_056", "quran", "medium", "quran", Q, "31:13", False,
        fr=L("Quel est le premier conseil de Luqmân à son fils, cité dans le Coran ?",
             ["Ne rien associer à Allah", "Étudier les étoiles", "Devenir commerçant", "Voyager loin"], 0,
             "« Ô mon fils, n'associe rien à Allah, car l'association est vraiment une injustice énorme » (31:13).",
             "Coran 31:13"),
        en=L("What is Luqman's first piece of advice to his son, quoted in the Qur'an?",
             ["Do not associate anything with Allah", "Study the stars", "Become a merchant", "Travel far"], 0,
             "\"O my son, do not associate anything with Allah; indeed, association is a great injustice\" (31:13).",
             "Qur'an 31:13"),
        ar=L("ما أول وصية أوصى بها لقمان ابنه كما ورد في القرآن؟",
             ["ألّا يشرك بالله", "أن يدرس النجوم", "أن يصير تاجرًا", "أن يسافر بعيدًا"], 0,
             "«يا بني لا تشرك بالله إن الشرك لظلم عظيم» (31:13).",
             "القرآن 31:13"))

    add("quran_057", "quran", "hard", "quran", Q, "9:1", False,
        fr=L("Sous quel autre nom la sourate At-Tawba est-elle connue ?",
             ["Barâ'a (le Désaveu)", "An-Nûr", "Al-Anfâl", "Al-Fath"], 0,
             "Son premier mot est « Barâ'a » : un désaveu d'Allah et de Son Messager envers les polythéistes (9:1).",
             "Coran 9:1"),
        en=L("By what other name is Surah At-Tawba known?",
             ["Bara'a (the Disavowal)", "An-Nur", "Al-Anfal", "Al-Fath"], 0,
             "Its first word is \"Bara'a\": a declaration of disavowal from Allah and His Messenger towards the idolaters (9:1).",
             "Qur'an 9:1"),
        ar=L("بأي اسم آخر تُعرف سورة التوبة؟",
             ["براءة", "النور", "الأنفال", "الفتح"], 0,
             "أول كلمة فيها «براءة من الله ورسوله إلى الذين عاهدتم من المشركين» (9:1).",
             "القرآن 9:1"))

    add("quran_058", "quran", "easy", "quran", Q, "36:1", False,
        fr=L("Quelle sourate commence par les deux lettres « Yâ, Sîn » ?",
             ["Yâ-Sîn (sourate 36)", "Tâ-Hâ", "Qâf", "Sâd"], 0,
             "La sourate 36 s'ouvre sur « Yâ-Sîn. Par le Coran plein de sagesse ! »",
             "Coran 36:1"),
        en=L("Which surah begins with the two letters \"Ya, Sin\"?",
             ["Ya-Sin (surah 36)", "Ta-Ha", "Qaf", "Sad"], 0,
             "Surah 36 opens with \"Ya-Sin. By the wise Qur'an!\"",
             "Qur'an 36:1"),
        ar=L("أي سورة تبدأ بالحرفين «يس»؟",
             ["يس (السورة 36)", "طه", "ق", "ص"], 0,
             "تُفتتح السورة السادسة والثلاثون بقوله: «يس والقرآن الحكيم».",
             "القرآن 36:1"))

    add("quran_059", "quran", "medium", "quran", Q, "67:1", False,
        fr=L("Que signifie « Al-Mulk », titre de la sourate 67 ?",
             ["La Royauté / la Souveraineté", "La Lumière", "Le Voyage", "La Victoire"], 0,
             "« Béni soit Celui dans la main de qui est la Royauté (al-Mulk) » (67:1).",
             "Coran 67:1"),
        en=L("What does \"Al-Mulk\", the title of surah 67, mean?",
             ["The Sovereignty / the Kingdom", "The Light", "The Journey", "The Victory"], 0,
             "\"Blessed is He in whose hand is the Sovereignty (al-Mulk)\" (67:1).",
             "Qur'an 67:1"),
        ar=L("ما معنى «الملك» عنوان السورة السابعة والستين؟",
             ["السلطان والسيادة", "النور", "الرحلة", "النصر"], 0,
             "«تبارك الذي بيده الملك» (67:1).",
             "القرآن 67:1"))

    add("quran_060", "quran", "easy", "quran", Q, "114:1", False,
        fr=L("Quelle est la dernière sourate du Coran ?",
             ["An-Nâs", "Al-Falaq", "Al-Ikhlâs", "Al-Fâtiha"], 0,
             "An-Nâs (« Les Hommes »), sourate 114, clôt le Coran : « Dis : je cherche refuge auprès du Seigneur des hommes ».",
             "Coran 114:1"),
        en=L("What is the last surah of the Qur'an?",
             ["An-Nas", "Al-Falaq", "Al-Ikhlas", "Al-Fatiha"], 0,
             "An-Nas (\"Mankind\"), surah 114, closes the Qur'an: \"Say: I seek refuge in the Lord of mankind\".",
             "Qur'an 114:1"),
        ar=L("ما آخر سورة في القرآن؟",
             ["الناس", "الفلق", "الإخلاص", "الفاتحة"], 0,
             "سورة الناس (114) تختم القرآن: «قل أعوذ برب الناس».",
             "القرآن 114:1"))

    add("quran_061", "quran", "medium", "quran", Q, "113:1", False,
        fr=L("Comment commence la sourate Al-Falaq ?",
             ["« Dis : je cherche refuge auprès du Seigneur de l'aube »", "« Dis : Il est Allah, Unique »", "« Par le temps ! »", "« Louange à Allah »"], 0,
             "« Qul a'ûdhu bi-rabbi-l-falaq » (113:1) : Al-Falaq signifie l'aube naissante.",
             "Coran 113:1"),
        en=L("How does Surah Al-Falaq begin?",
             ["\"Say: I seek refuge in the Lord of the daybreak\"", "\"Say: He is Allah, One\"", "\"By time!\"", "\"Praise be to Allah\""], 0,
             "\"Qul a'udhu bi-rabbi-l-falaq\" (113:1): Al-Falaq means the daybreak.",
             "Qur'an 113:1"),
        ar=L("بماذا تبدأ سورة الفلق؟",
             ["«قل أعوذ برب الفلق»", "«قل هو الله أحد»", "«والعصر»", "«الحمد لله»"], 0,
             "«قل أعوذ برب الفلق» (113:1)، والفلق هو الصبح.",
             "القرآن 113:1"))

    add("quran_062", "quran", "medium", "quran", Q, "2:158", False,
        fr=L("Quelles deux collines le Coran cite-t-il parmi les « rites d'Allah » ?",
             ["As-Safâ et Al-Marwa", "Uhud et Thawr", "'Arafât et Minâ", "Hirâ' et Abû Qubays"], 0,
             "« As-Safâ et Al-Marwa sont vraiment parmi les rites d'Allah » (2:158) : on y fait le sa'y du pèlerinage.",
             "Coran 2:158"),
        en=L("Which two hills does the Qur'an name among the \"symbols of Allah\"?",
             ["As-Safa and Al-Marwa", "Uhud and Thawr", "'Arafat and Mina", "Hira' and Abu Qubays"], 0,
             "\"As-Safa and Al-Marwa are among the symbols of Allah\" (2:158): the sa'y of the pilgrimage is walked between them.",
             "Qur'an 2:158"),
        ar=L("ما الجبلان اللذان ذكرهما القرآن من «شعائر الله»؟",
             ["الصفا والمروة", "أحد وثور", "عرفات ومنى", "حراء وأبو قبيس"], 0,
             "«إن الصفا والمروة من شعائر الله» (2:158)، وبينهما يكون السعي في الحج.",
             "القرآن 2:158"))

    add("quran_063", "quran", "easy", "quran", Q, "19:16", False,
        fr=L("Quelle est la seule femme nommée par son prénom dans le Coran ?",
             ["Maryam", "Khadîja", "Âsiya", "Hâjar"], 0,
             "Maryam, mère de 'Îsâ, est nommée dans plusieurs sourates ; une sourate entière porte son nom.",
             "Coran 19:16"),
        en=L("Who is the only woman mentioned by name in the Qur'an?",
             ["Maryam", "Khadija", "Asiya", "Hajar"], 0,
             "Maryam, mother of 'Isa, is named in several surahs, and a whole surah bears her name.",
             "Qur'an 19:16"),
        ar=L("من المرأة الوحيدة التي ذُكرت باسمها في القرآن؟",
             ["مريم", "خديجة", "آسية", "هاجر"], 0,
             "مريم أم عيسى ذُكرت باسمها في سور عدة، وسُمّيت سورة كاملة باسمها.",
             "القرآن 19:16"))

    add("quran_064", "quran", "hard", "quran", Q, "33:37", False,
        fr=L("Quel est le seul compagnon du Prophète ﷺ nommé dans le Coran ?",
             ["Zayd ibn Hâritha", "Abû Bakr", "'Umar", "'Alî"], 0,
             "« Lorsque Zayd eut cessé toute relation avec elle… » (33:37) : Zayd, l'affranchi du Prophète ﷺ, est le seul compagnon cité par son nom.",
             "Coran 33:37"),
        en=L("Who is the only companion of the Prophet ﷺ named in the Qur'an?",
             ["Zayd ibn Haritha", "Abu Bakr", "'Umar", "'Ali"], 0,
             "\"When Zayd had ended his relationship with her…\" (33:37): Zayd, the Prophet's freed slave, is the only companion named.",
             "Qur'an 33:37"),
        ar=L("من الصحابي الوحيد الذي ذُكر باسمه في القرآن؟",
             ["زيد بن حارثة", "أبو بكر", "عمر", "علي"], 0,
             "«فلما قضى زيد منها وطرًا» (33:37)، وزيد مولى النبي ﷺ هو الصحابي الوحيد المذكور باسمه.",
             "القرآن 33:37"))

    add("quran_065", "quran", "hard", "quran", Q, "2:102", False,
        fr=L("Qui étaient Hârût et Mârût, cités dans la sourate Al-Baqara ?",
             ["Deux anges envoyés à Babylone", "Deux prophètes", "Deux rois d'Égypte", "Deux compagnons"], 0,
             "« …ce qui fut descendu sur les deux anges Hârût et Mârût à Babylone » (2:102) : ils avertissaient que la magie est une épreuve.",
             "Coran 2:102"),
        en=L("Who were Harut and Marut, mentioned in Surah Al-Baqara?",
             ["Two angels sent to Babylon", "Two prophets", "Two kings of Egypt", "Two companions"], 0,
             "\"…what was sent down to the two angels Harut and Marut in Babylon\" (2:102): they warned that magic was a trial.",
             "Qur'an 2:102"),
        ar=L("من هما هاروت وماروت المذكوران في سورة البقرة؟",
             ["ملكان أُنزلا ببابل", "نبيّان", "ملكان من ملوك مصر", "صحابيان"], 0,
             "«وما أُنزل على الملكين ببابل هاروت وماروت» (2:102)، وكانا يحذّران أن السحر فتنة.",
             "القرآن 2:102"))

    add("quran_066", "quran", "easy", "quran", Q, "49:13", False,
        fr=L("Selon le Coran, qui est le plus noble auprès d'Allah ?",
             ["Le plus pieux", "Le plus riche", "Le plus fort", "Le plus célèbre"], 0,
             "« Le plus noble d'entre vous auprès d'Allah est le plus pieux » (49:13).",
             "Coran 49:13"),
        en=L("According to the Qur'an, who is the most noble in the sight of Allah?",
             ["The most God-fearing", "The richest", "The strongest", "The most famous"], 0,
             "\"The most noble of you in the sight of Allah is the most God-fearing\" (49:13).",
             "Qur'an 49:13"),
        ar=L("بحسب القرآن، من أكرم الناس عند الله؟",
             ["أتقاهم", "أغناهم", "أقواهم", "أشهرهم"], 0,
             "«إن أكرمكم عند الله أتقاكم» (49:13).",
             "القرآن 49:13"))

    add("quran_067", "quran", "hard", "quran", Q, "56:1", False,
        fr=L("Que désigne « Al-Wâqi'a », titre de la sourate 56 ?",
             ["L'Événement inéluctable (le Jour de la Résurrection)", "La caravane", "La fourmi", "Le voyage nocturne"], 0,
             "« Quand l'Événement arrivera… » (56:1) : la sourate décrit les trois groupes du Jour dernier.",
             "Coran 56:1"),
        en=L("What does \"Al-Waqi'a\", the title of surah 56, refer to?",
             ["The inevitable Event (the Day of Resurrection)", "The caravan", "The ant", "The night journey"], 0,
             "\"When the Event befalls…\" (56:1): the surah describes the three groups of the Last Day.",
             "Qur'an 56:1"),
        ar=L("إلامَ يشير اسم «الواقعة» عنوان السورة السادسة والخمسين؟",
             ["إلى يوم القيامة الذي لا بد أن يقع", "إلى القافلة", "إلى النملة", "إلى الإسراء"], 0,
             "«إذا وقعت الواقعة» (56:1)، وتصف السورة أصناف الناس الثلاثة يوم القيامة.",
             "القرآن 56:1"))

    add("quran_068", "quran", "medium", "quran", Q, "68:1", False,
        fr=L("Par quel objet Allah jure-t-Il au début de la sourate Al-Qalam ?",
             ["Par la plume", "Par l'épée", "Par la balance", "Par la lampe"], 0,
             "« Nûn. Par la plume et ce qu'ils écrivent ! » (68:1).",
             "Coran 68:1"),
        en=L("By which object does Allah swear at the start of Surah Al-Qalam?",
             ["By the pen", "By the sword", "By the scale", "By the lamp"], 0,
             "\"Nun. By the pen and what they write!\" (68:1).",
             "Qur'an 68:1"),
        ar=L("بأي شيء أقسم الله في مطلع سورة القلم؟",
             ["بالقلم", "بالسيف", "بالميزان", "بالمصباح"], 0,
             "«ن والقلم وما يسطرون» (68:1).",
             "القرآن 68:1"))

    add("quran_069", "quran", "medium", "quran", Q, "89:1-2", False,
        fr=L("Par quoi s'ouvre la sourate Al-Fajr ?",
             ["Par le serment sur l'aube et dix nuits", "Par le serment sur le figuier", "Par un récit de Yûsuf", "Par la basmala seule"], 0,
             "« Par l'aube ! Et par les dix nuits ! » (89:1-2).",
             "Coran 89:1-2"),
        en=L("How does Surah Al-Fajr open?",
             ["With an oath by the dawn and ten nights", "With an oath by the fig", "With a story of Yusuf", "With the basmala alone"], 0,
             "\"By the dawn! And by the ten nights!\" (89:1-2).",
             "Qur'an 89:1-2"),
        ar=L("بماذا تُفتتح سورة الفجر؟",
             ["بالقسم بالفجر وليال عشر", "بالقسم بالتين", "بقصة يوسف", "بالبسملة وحدها"], 0,
             "«والفجر وليال عشر» (89:1-2).",
             "القرآن 89:1-2"))

    add("quran_070", "quran", "easy", "quran", Q, "91:1", False,
        fr=L("Par quel astre Allah jure-t-Il au début de la sourate Ash-Shams ?",
             ["Le soleil", "La lune seule", "Les étoiles", "Les planètes"], 0,
             "« Par le soleil et sa clarté ! » (91:1) ; Ash-Shams signifie « le soleil ».",
             "Coran 91:1"),
        en=L("By which heavenly body does Allah swear at the start of Surah Ash-Shams?",
             ["The sun", "The moon alone", "The stars", "The planets"], 0,
             "\"By the sun and its brightness!\" (91:1); Ash-Shams means \"the sun\".",
             "Qur'an 91:1"),
        ar=L("بأي جرم سماوي أقسم الله في مطلع سورة الشمس؟",
             ["الشمس", "القمر وحده", "النجوم", "الكواكب"], 0,
             "«والشمس وضحاها» (91:1).",
             "القرآن 91:1"))

    add("quran_071", "quran", "medium", "quran", Q, "76:1", False,
        fr=L("Quelle sourate s'ouvre par : « S'est-il écoulé pour l'homme un laps de temps où il n'était pas une chose mentionnable ? »",
             ["Al-Insân (sourate 76)", "Al-Kahf", "Al-Hajj", "Al-Fâtiha"], 0,
             "Al-Insân (« L'Homme »), aussi appelée Ad-Dahr, rappelle que l'homme n'était rien avant sa création (76:1).",
             "Coran 76:1"),
        en=L("Which surah opens: \"Has there come upon man a period of time when he was not a thing mentioned?\"",
             ["Al-Insan (surah 76)", "Al-Kahf", "Al-Hajj", "Al-Fatiha"], 0,
             "Al-Insan (\"Man\"), also called Ad-Dahr, recalls that man was nothing before his creation (76:1).",
             "Qur'an 76:1"),
        ar=L("أي سورة تُفتتح بقوله: «هل أتى على الإنسان حين من الدهر لم يكن شيئًا مذكورًا»؟",
             ["الإنسان (السورة 76)", "الكهف", "الحج", "الفاتحة"], 0,
             "سورة الإنسان، وتُسمّى أيضًا الدهر، تذكّر أن الإنسان لم يكن شيئًا قبل خلقه (76:1).",
             "القرآن 76:1"))

    add("quran_072", "quran", "easy", "quran", Q, "54:17", False,
        fr=L("Selon le Coran, à quoi Allah a-t-Il rendu le Coran facile ?",
             ["À la mémorisation et au rappel", "Au commerce", "À la traduction", "À l'oubli"], 0,
             "« Nous avons rendu le Coran facile pour la méditation. Y a-t-il quelqu'un pour réfléchir ? » (54:17), répété quatre fois dans la sourate.",
             "Coran 54:17"),
        en=L("According to the Qur'an, for what has Allah made the Qur'an easy?",
             ["For remembrance and memorisation", "For trade", "For translation", "For forgetting"], 0,
             "\"We have made the Qur'an easy to remember; is there anyone who will take heed?\" (54:17), repeated four times in the surah.",
             "Qur'an 54:17"),
        ar=L("بحسب القرآن، لماذا يسّر الله القرآن؟",
             ["للذكر والحفظ", "للتجارة", "للترجمة", "للنسيان"], 0,
             "«ولقد يسّرنا القرآن للذكر فهل من مدّكر» (54:17)، وتكررت أربع مرات في السورة.",
             "القرآن 54:17"))

    add("quran_073", "quran", "medium", "quran", Q, "54:1", False,
        fr=L("Quel signe la sourate Al-Qamar mentionne-t-elle dès son premier verset ?",
             ["La lune s'est fendue", "Le soleil s'est éteint", "La mer s'est ouverte", "La montagne a parlé"], 0,
             "« L'Heure approche et la lune s'est fendue » (54:1) : un signe montré aux Mecquois.",
             "Coran 54:1"),
        en=L("Which sign does Surah Al-Qamar mention in its very first verse?",
             ["The moon split", "The sun went out", "The sea opened", "The mountain spoke"], 0,
             "\"The Hour has drawn near and the moon has split\" (54:1): a sign shown to the Makkans.",
             "Qur'an 54:1"),
        ar=L("أي آية ذكرتها سورة القمر في أول آية منها؟",
             ["انشقاق القمر", "انطفاء الشمس", "انفلاق البحر", "كلام الجبل"], 0,
             "«اقتربت الساعة وانشق القمر» (54:1)، وهي آية أُريها أهل مكة.",
             "القرآن 54:1"))

    add("quran_074", "quran", "medium", "quran", Q, "25:32", False,
        fr=L("Pourquoi le Coran fut-il révélé progressivement plutôt qu'en une seule fois, selon lui-même ?",
             ["Pour raffermir le cœur du Prophète ﷺ", "Parce qu'il était trop long", "Pour le cacher aux ennemis", "À cause des voyages"], 0,
             "« Nous l'avons révélé ainsi pour raffermir ton cœur, et Nous l'avons récité avec soin » (25:32).",
             "Coran 25:32"),
        en=L("Why was the Qur'an revealed gradually rather than all at once, according to the Qur'an itself?",
             ["To strengthen the Prophet's ﷺ heart", "Because it was too long", "To hide it from enemies", "Because of journeys"], 0,
             "\"Thus, that We may strengthen your heart thereby, and We have recited it with careful recitation\" (25:32).",
             "Qur'an 25:32"),
        ar=L("لماذا نزل القرآن منجّمًا لا جملة واحدة، كما بيّن القرآن نفسه؟",
             ["ليثبّت الله به قلب النبي ﷺ", "لأنه كان طويلًا جدًا", "لإخفائه عن الأعداء", "بسبب الأسفار"], 0,
             "«كذلك لنثبّت به فؤادك ورتّلناه ترتيلًا» (25:32).",
             "القرآن 25:32"))

    add("quran_075", "quran", "easy", "hadithBukhari", B, "5017", False,
        fr=L("Quelles sourates le Prophète ﷺ récitait-il chaque soir dans ses mains avant de dormir, selon 'Â'isha ?",
             ["Al-Ikhlâs, Al-Falaq et An-Nâs", "Al-Fâtiha et Al-Baqara", "Yâ-Sîn et Al-Mulk", "Al-Kahf et Maryam"], 0,
             "Il soufflait dans ses mains en récitant les trois « Qul », puis se passait les mains sur le corps, trois fois.",
             "Sahîh al-Bukhârî, 5017"),
        en=L("Which surahs did the Prophet ﷺ recite into his hands each night before sleeping, according to 'A'isha?",
             ["Al-Ikhlas, Al-Falaq and An-Nas", "Al-Fatiha and Al-Baqara", "Ya-Sin and Al-Mulk", "Al-Kahf and Maryam"], 0,
             "He would blow into his hands reciting the three \"Qul\" surahs, then wipe them over his body, three times.",
             "Sahih al-Bukhari, 5017"),
        ar=L("أي سور كان النبي ﷺ يقرؤها في كفّيه كل ليلة قبل النوم كما روت عائشة؟",
             ["الإخلاص والفلق والناس", "الفاتحة والبقرة", "يس والملك", "الكهف ومريم"], 0,
             "كان ينفث في كفّيه ويقرأ المعوذات و«قل هو الله أحد»، ثم يمسح بهما جسده، ثلاث مرات.",
             "صحيح البخاري، 5017"))

    add("quran_076", "quran", "medium", "quran", Q, WT + " (sujud at-tilawa; e.g. 96:19)", False,
        fr=L("Comment appelle-t-on la prosternation que l'on fait en récitant certains versets du Coran ?",
             ["La prosternation de récitation (sujûd at-tilâwa)", "La prosternation d'oubli", "La prosternation de remerciement", "Le ruku'"], 0,
             "Le Coran contient des versets de prosternation, comme le dernier verset d'Al-'Alaq : « prosterne-toi et rapproche-toi » (96:19).",
             "Terminologie établie ; Coran 96:19"),
        en=L("What is the prostration made when reciting certain verses of the Qur'an called?",
             ["The prostration of recitation (sujud at-tilawa)", "The prostration of forgetfulness", "The prostration of thanks", "The ruku'"], 0,
             "The Qur'an contains prostration verses, such as the last verse of Al-'Alaq: \"prostrate and draw near\" (96:19).",
             "Established terminology; Qur'an 96:19"),
        ar=L("ماذا تُسمّى السجدة التي يسجدها القارئ عند تلاوة آيات معينة من القرآن؟",
             ["سجود التلاوة", "سجود السهو", "سجود الشكر", "الركوع"], 0,
             "في القرآن آيات سجدة، منها آخر آية في سورة العلق: «واسجد واقترب» (96:19).",
             "مصطلح مستقر؛ القرآن 96:19"))

    add("quran_077", "quran", "easy", "quran", Q, WT + " (tajwid)", False,
        fr=L("Comment appelle-t-on la science des règles de bonne prononciation du Coran ?",
             ["Le tajwîd", "Le tafsîr", "Le fiqh", "La sîra"], 0,
             "Le tajwîd enseigne à prononcer chaque lettre depuis son point d'articulation, avec ses caractéristiques.",
             "Terminologie établie des sciences du Coran"),
        en=L("What is the science of the rules for correctly pronouncing the Qur'an called?",
             ["Tajwid", "Tafsir", "Fiqh", "Sira"], 0,
             "Tajwid teaches how to pronounce each letter from its point of articulation, with its qualities.",
             "Established terminology of Qur'anic sciences"),
        ar=L("ماذا يُسمّى علم قواعد النطق الصحيح للقرآن؟",
             ["التجويد", "التفسير", "الفقه", "السيرة"], 0,
             "التجويد هو إخراج كل حرف من مخرجه مع إعطائه صفاته.",
             "مصطلح مستقر في علوم القرآن"))

    add("quran_078", "quran", "easy", "quran", Q, WT + " (hafiz)", False,
        fr=L("Comment appelle-t-on une personne qui a mémorisé tout le Coran ?",
             ["Un hâfiz", "Un imam", "Un muezzin", "Un mufti"], 0,
             "Hâfiz signifie « celui qui garde » : il porte le Coran entier dans sa mémoire.",
             "Terminologie établie"),
        en=L("What is a person who has memorised the whole Qur'an called?",
             ["A hafiz", "An imam", "A muezzin", "A mufti"], 0,
             "Hafiz means \"one who guards\": he carries the entire Qur'an in his memory.",
             "Established terminology"),
        ar=L("ماذا يُسمّى من حفظ القرآن كله؟",
             ["حافظ", "إمام", "مؤذّن", "مفتٍ"], 0,
             "الحافظ هو من حفظ القرآن كاملًا في صدره.",
             "مصطلح مستقر"))

    add("quran_079", "quran", "easy", "quran", Q, WT + " (mushaf)", False,
        fr=L("Comment appelle-t-on l'exemplaire écrit du Coran ?",
             ["Un mushaf", "Un hadith", "Un juz'", "Un minbar"], 0,
             "Le mushaf est le Coran réuni entre deux couvertures ; le juz' en est une des trente parties.",
             "Terminologie établie"),
        en=L("What is the written copy of the Qur'an called?",
             ["A mushaf", "A hadith", "A juz'", "A minbar"], 0,
             "The mushaf is the Qur'an gathered between two covers; a juz' is one of its thirty parts.",
             "Established terminology"),
        ar=L("ماذا تُسمّى النسخة المكتوبة من القرآن؟",
             ["مصحف", "حديث", "جزء", "منبر"], 0,
             "المصحف هو القرآن مجموعًا بين دفّتين، والجزء واحد من أجزائه الثلاثين.",
             "مصطلح مستقر"))

    add("quran_080", "quran", "hard", "quran", Q, "27:30", False,
        fr=L("Dans quelle sourate la basmala apparaît-elle deux fois ?",
             ["An-Naml", "Al-Fâtiha", "At-Tawba", "Al-Baqara"], 0,
             "Outre son ouverture, An-Naml cite la basmala au début de la lettre de Sulaymân à la reine de Saba' (27:30).",
             "Coran 27:30"),
        en=L("In which surah does the basmala appear twice?",
             ["An-Naml", "Al-Fatiha", "At-Tawba", "Al-Baqara"], 0,
             "Besides its opening, An-Naml quotes the basmala at the start of Sulayman's letter to the queen of Saba' (27:30).",
             "Qur'an 27:30"),
        ar=L("في أي سورة وردت البسملة مرتين؟",
             ["النمل", "الفاتحة", "التوبة", "البقرة"], 0,
             "إلى جانب افتتاحيتها، وردت البسملة في سورة النمل في مطلع كتاب سليمان إلى ملكة سبأ (27:30).",
             "القرآن 27:30"))
