"""Faith, worship and the names of Allah — part B (faith_071 … faith_150).

Articles of faith, acts of worship and the divine names, taken from the
Qur'an where the Qur'an states them, from the two Ṣaḥīḥs where a hadith
does, and from the `well-established` class of CONTENT_SOURCE_POLICY
§2bis for terminology and practices agreed across the schools. Nothing
here needs a madhhab to answer.
"""

WT = "well-established terminology"
WP = "well-established practice, agreed across the schools"


def register(add, L):
    Q = "Quran"
    C = "Creed"

    # -- The names of Allah ---------------------------------------------
    add("faith_071", "faith", "easy", "quran", Q, "59:23", False,
        fr=L("Que signifie le nom d'Allah « As-Salâm » ?",
             ["La Paix, exempt de tout défaut", "Le Créateur", "Le Pourvoyeur", "Le Puissant"], 0,
             "As-Salâm figure parmi les noms énumérés à la fin de la sourate Al-Hashr : Il est la Paix, exempt de toute imperfection.",
             "Coran — Sourate Al-Hashr, 59:23"),
        en=L("What does the name of Allah \"As-Salam\" mean?",
             ["The Peace, free of every defect", "The Creator", "The Provider", "The Mighty"], 0,
             "As-Salam is among the names listed at the end of Surah Al-Hashr: He is the Peace, free of all imperfection.",
             "Quran — Surah Al-Hashr, 59:23"),
        ar=L("ما معنى اسم الله «السلام»؟",
             ["السالم من كل نقص", "الخالق", "الرزّاق", "العزيز"], 0,
             "السلام من الأسماء المذكورة في خاتمة سورة الحشر، وهو السالم من كل عيب.",
             "القرآن — سورة الحشر، 59:23"))

    add("faith_072", "faith", "medium", "quran", Q, "59:22", False,
        fr=L("Quels attributs le verset 59:22 associe-t-il au nom d'Allah, juste après « nulle divinité à part Lui » ?",
             ["Le Connaisseur de l'invisible et du visible, le Tout Miséricordieux", "Le Roi et le Guerrier", "Le Riche et le Généreux", "Le Fort et le Rapide"], 0,
             "« C'est Lui Allah : nulle divinité autre que Lui, le Connaisseur de l'invisible tout comme du visible. C'est Lui le Tout Miséricordieux, le Très Miséricordieux. »",
             "Coran — Sourate Al-Hashr, 59:22"),
        en=L("Which attributes does verse 59:22 place beside the name of Allah, right after \"there is no deity but He\"?",
             ["Knower of the unseen and the witnessed, the Most Merciful", "The King and the Warrior", "The Rich and the Generous", "The Strong and the Swift"], 0,
             "\"He is Allah, other than whom there is no deity, Knower of the unseen and the witnessed. He is the Entirely Merciful, the Especially Merciful.\"",
             "Quran — Surah Al-Hashr, 59:22"),
        ar=L("أي أوصاف قرنتها الآية 59:22 باسم الله بعد «لا إله إلا هو»؟",
             ["عالم الغيب والشهادة، الرحمن الرحيم", "الملك والمقاتل", "الغني والكريم", "القوي والسريع"], 0,
             "«هو الله الذي لا إله إلا هو عالم الغيب والشهادة، هو الرحمن الرحيم».",
             "القرآن — سورة الحشر، 59:22"))

    add("faith_073", "faith", "hard", "quran", Q, "7:180", False,
        fr=L("Que le Coran ordonne-t-il de faire avec les plus beaux noms d'Allah ?",
             ["L'invoquer par eux", "Les compter seulement", "Les écrire sur les portes", "Les taire"], 0,
             "« C'est à Allah qu'appartiennent les noms les plus beaux : invoquez-Le par ces noms. »",
             "Coran — Sourate Al-Aʿrâf, 7:180"),
        en=L("What does the Quran command be done with the most beautiful names of Allah?",
             ["To call upon Him by them", "Only to count them", "To write them on doors", "To keep silent about them"], 0,
             "\"And to Allah belong the best names, so invoke Him by them.\"",
             "Quran — Surah Al-A'raf, 7:180"),
        ar=L("بماذا أمر القرآن في شأن أسماء الله الحسنى؟",
             ["أن يُدعى بها", "أن تُعدّ فقط", "أن تُكتب على الأبواب", "أن يُسكت عنها"], 0,
             "«ولله الأسماء الحسنى فادعوه بها».",
             "القرآن — سورة الأعراف، 7:180"))

    add("faith_074", "faith", "medium", "quran", Q, "20:8", False,
        fr=L("Comment la sourate Tâ-Hâ présente-t-elle les noms d'Allah ?",
             ["« Allah ! Point de divinité à part Lui ! À Lui les plus beaux noms »", "« Ses noms sont cachés »", "« Ses noms sont innombrables »", "« Ses noms sont neuf »"], 0,
             "« Allah ! Point de divinité que Lui ! À Lui appartiennent les plus beaux noms. »",
             "Coran — Sourate Tâ-Hâ, 20:8"),
        en=L("How does Surah Ta-Ha present the names of Allah?",
             ["\"Allah — there is no deity except Him. To Him belong the best names\"", "\"His names are hidden\"", "\"His names are countless\"", "\"His names are nine\""], 0,
             "\"Allah — there is no deity except Him. To Him belong the best names.\"",
             "Quran — Surah Ta-Ha, 20:8"),
        ar=L("كيف قدّمت سورة طه أسماء الله؟",
             ["«الله لا إله إلا هو له الأسماء الحسنى»", "«أسماؤه مخفية»", "«أسماؤه لا تُحصى»", "«أسماؤه تسعة»"], 0,
             "«الله لا إله إلا هو له الأسماء الحسنى».",
             "القرآن — سورة طه، 20:8"))

    add("faith_075", "faith", "hard", "quran", Q, "42:11", False,
        fr=L("Quelle formule le Coran emploie-t-il pour écarter toute ressemblance avec Allah ?",
             ["« Il n'y a rien qui Lui ressemble ; et c'est Lui l'Audient, le Clairvoyant »", "« Il est le plus grand des rois »", "« Il ressemble à la lumière »", "« Nul ne Le voit »"], 0,
             "« Il n'y a rien qui Lui ressemble ; et c'est Lui l'Audient, le Clairvoyant. »",
             "Coran — Sourate Ash-Shûrâ, 42:11"),
        en=L("Which formula does the Quran use to rule out any likeness to Allah?",
             ["\"There is nothing like unto Him, and He is the Hearing, the Seeing\"", "\"He is the greatest of kings\"", "\"He is like light\"", "\"None sees Him\""], 0,
             "\"There is nothing like unto Him, and He is the Hearing, the Seeing.\"",
             "Quran — Surah Ash-Shura, 42:11"),
        ar=L("بأي عبارة نفى القرآن المماثلة عن الله؟",
             ["«ليس كمثله شيء وهو السميع البصير»", "«هو أعظم الملوك»", "«هو كالنور»", "«لا يراه أحد»"], 0,
             "«ليس كمثله شيء وهو السميع البصير».",
             "القرآن — سورة الشورى، 42:11"))

    add("faith_076", "faith", "easy", "quran", Q, "2:255", False,
        fr=L("Que dit le Verset du Trône au sujet de la somnolence et du sommeil ?",
             ["Ni somnolence ni sommeil ne Le saisissent", "Il dort la nuit", "Il se repose le septième jour", "Il veille un jour sur deux"], 0,
             "« Ni somnolence ni sommeil ne Le saisissent. »",
             "Coran — Sourate Al-Baqara, 2:255"),
        en=L("What does the Throne Verse say about slumber and sleep?",
             ["Neither drowsiness nor sleep overtakes Him", "He sleeps at night", "He rests on the seventh day", "He watches every other day"], 0,
             "\"Neither drowsiness overtakes Him nor sleep.\"",
             "Quran — Surah Al-Baqarah, 2:255"),
        ar=L("ماذا قالت آية الكرسي في شأن السِّنة والنوم؟",
             ["لا تأخذه سِنة ولا نوم", "ينام ليلًا", "يستريح في اليوم السابع", "يسهر يومًا بعد يوم"], 0,
             "«لا تأخذه سِنة ولا نوم».",
             "القرآن — سورة البقرة، 2:255"))

    add("faith_077", "faith", "medium", "quran", Q, "6:59", False,
        fr=L("Que dit le Coran de la connaissance qu'Allah a de la feuille qui tombe ?",
             ["Nulle feuille ne tombe sans qu'Il ne le sache", "Il l'apprend ensuite", "Les anges L'en informent", "Cela n'est pas écrit"], 0,
             "« Il détient les clés de l'inconnaissable… nulle feuille ne tombe sans qu'Il ne le sache. »",
             "Coran — Sourate Al-Anʿâm, 6:59"),
        en=L("What does the Quran say of Allah's knowledge of a falling leaf?",
             ["Not a leaf falls but He knows it", "He learns of it afterwards", "The angels inform Him", "It is not written down"], 0,
             "\"And with Him are the keys of the unseen… not a leaf falls but that He knows it.\"",
             "Quran — Surah Al-An'am, 6:59"),
        ar=L("ماذا قال القرآن عن علم الله بالورقة الساقطة؟",
             ["ما تسقط من ورقة إلا يعلمها", "يعلمها بعد ذلك", "تخبره الملائكة", "لا تُكتب"], 0,
             "«وعنده مفاتح الغيب… وما تسقط من ورقة إلا يعلمها».",
             "القرآن — سورة الأنعام، 6:59"))

    add("faith_078", "faith", "hard", "quran", Q, "50:16", False,
        fr=L("De quoi Allah est-Il plus proche de l'homme, selon la sourate Qâf ?",
             ["De sa veine jugulaire", "De son ombre", "De sa voix", "De sa maison"], 0,
             "« Nous avons créé l'homme et Nous savons ce que son âme lui suggère ; Nous sommes plus près de lui que sa veine jugulaire. »",
             "Coran — Sourate Qâf, 50:16"),
        en=L("Than what is Allah nearer to a person, according to Surah Qaf?",
             ["Than his jugular vein", "Than his shadow", "Than his voice", "Than his house"], 0,
             "\"And We have already created man and know what his soul whispers to him, and We are closer to him than his jugular vein.\"",
             "Quran — Surah Qaf, 50:16"),
        ar=L("مِمّ الله أقرب إلى الإنسان بحسب سورة ق؟",
             ["من حبل الوريد", "من ظله", "من صوته", "من داره"], 0,
             "«ولقد خلقنا الإنسان ونعلم ما توسوس به نفسه، ونحن أقرب إليه من حبل الوريد».",
             "القرآن — سورة ق، 50:16"))

    # -- Angels, books, the unseen ---------------------------------------
    add("faith_079", "faith", "easy", "quran", Q, "66:6", False,
        fr=L("Comment le Coran décrit-il les anges chargés du Feu ?",
             ["Ils ne désobéissent pas à Allah et font ce qui leur est ordonné", "Ils sont plusieurs à hésiter", "Ils dorment", "Ils choisissent"], 0,
             "« … des anges rudes, durs, qui ne désobéissent jamais à Allah en ce qu'Il leur commande, et qui font strictement ce qu'on leur ordonne. »",
             "Coran — Sourate At-Tahrîm, 66:6"),
        en=L("How does the Quran describe the angels charged with the Fire?",
             ["They do not disobey Allah and do what they are commanded", "Some of them hesitate", "They sleep", "They choose"], 0,
             "\"…angels, harsh and severe, who do not disobey Allah in what He commands them but do what they are commanded.\"",
             "Quran — Surah At-Tahrim, 66:6"),
        ar=L("كيف وصف القرآن ملائكة النار؟",
             ["لا يعصون الله ما أمرهم ويفعلون ما يؤمرون", "منهم من يتردد", "ينامون", "يختارون"], 0,
             "«ملائكة غلاظ شداد لا يعصون الله ما أمرهم ويفعلون ما يؤمرون».",
             "القرآن — سورة التحريم، 66:6"))

    add("faith_080", "faith", "medium", "quran", Q, "21:26-27", False,
        fr=L("Comment le Coran décrit-il les anges vis-à-vis de la parole d'Allah ?",
             ["Ils ne devancent pas Sa parole et agissent sur Son ordre", "Ils discutent Ses ordres", "Ils décident seuls", "Ils se taisent toujours"], 0,
             "« Ce sont plutôt des serviteurs honorés : ils ne devancent pas Sa parole et agissent sur Son ordre. »",
             "Coran — Sourate Al-Anbiyâ, 21:26-27"),
        en=L("How does the Quran describe the angels in relation to Allah's word?",
             ["They do not precede Him in speech and act by His command", "They dispute His orders", "They decide on their own", "They are always silent"], 0,
             "\"Rather, they are honoured servants. They cannot precede Him in word, and they act by His command.\"",
             "Quran — Surah Al-Anbiya, 21:26-27"),
        ar=L("كيف وصف القرآن الملائكة في شأن قول الله؟",
             ["لا يسبقونه بالقول وهم بأمره يعملون", "يجادلون في أمره", "يقررون وحدهم", "يصمتون دائمًا"], 0,
             "«بل عباد مكرمون، لا يسبقونه بالقول وهم بأمره يعملون».",
             "القرآن — سورة الأنبياء، 21:26-27"))

    add("faith_081", "faith", "hard", "quran", Q, "2:97", False,
        fr=L("Quel ange le Coran nomme-t-il comme celui qui fit descendre la révélation sur le cœur du Prophète ﷺ ?",
             ["Jibrîl", "Mîkâ'îl", "Isrâfîl", "Mâlik"], 0,
             "« Dis : quiconque est ennemi de Jibrîl… c'est lui qui, par la permission d'Allah, l'a fait descendre sur ton cœur. »",
             "Coran — Sourate Al-Baqara, 2:97"),
        en=L("Which angel does the Quran name as the one who brought the revelation down upon the Prophet's ﷺ heart?",
             ["Jibril (Gabriel)", "Mika'il (Michael)", "Israfil", "Malik"], 0,
             "\"Say: whoever is an enemy to Jibril — it is he who has brought it down upon your heart by permission of Allah.\"",
             "Quran — Surah Al-Baqarah, 2:97"),
        ar=L("أي ملك سمّاه القرآن نازلًا بالوحي على قلب النبي ﷺ؟",
             ["جبريل", "ميكائيل", "إسرافيل", "مالك"], 0,
             "«قل من كان عدوًّا لجبريل فإنه نزّله على قلبك بإذن الله».",
             "القرآن — سورة البقرة، 2:97"))

    add("faith_082", "faith", "medium", "quran", Q, "2:98", False,
        fr=L("Quel autre ange est nommé aux côtés de Jibrîl dans la sourate Al-Baqara ?",
             ["Mîkâl", "Isrâfîl", "Ridwân", "Munkar"], 0,
             "« Quiconque est ennemi d'Allah, de Ses anges, de Ses messagers, de Jibrîl et de Mîkâl… »",
             "Coran — Sourate Al-Baqara, 2:98"),
        en=L("Which other angel is named alongside Jibril in Surah Al-Baqarah?",
             ["Mikal (Michael)", "Israfil", "Ridwan", "Munkar"], 0,
             "\"Whoever is an enemy to Allah and His angels and His messengers and Jibril and Mikal…\"",
             "Quran — Surah Al-Baqarah, 2:98"),
        ar=L("أي ملك آخر ذُكر مع جبريل في سورة البقرة؟",
             ["ميكال", "إسرافيل", "رضوان", "منكر"], 0,
             "«من كان عدوًّا لله وملائكته ورسله وجبريل وميكال».",
             "القرآن — سورة البقرة، 2:98"))

    add("faith_083", "faith", "easy", "quran", Q, "4:136", False,
        fr=L("Quels objets de foi le verset 4:136 énumère-t-il ?",
             ["Allah, Son Messager, le Livre révélé et les Livres antérieurs", "Le Livre seulement", "Les prophètes seulement", "Les anges seulement"], 0,
             "« Ô les croyants ! Croyez en Allah, en Son messager, au Livre qu'Il a fait descendre sur Son messager, et au Livre qu'Il a fait descendre avant. »",
             "Coran — Sourate An-Nisâ, 4:136"),
        en=L("Which objects of belief does verse 4:136 list?",
             ["Allah, His Messenger, the Book revealed, and the Books before", "The Book only", "The prophets only", "The angels only"], 0,
             "\"O you who have believed, believe in Allah and His Messenger and the Book that He sent down upon His Messenger and the Scripture which He sent down before.\"",
             "Quran — Surah An-Nisa, 4:136"),
        ar=L("أي أركان للإيمان عدّدتها الآية 4:136؟",
             ["الله ورسوله والكتاب المنزّل والكتب قبله", "الكتاب فقط", "الرسل فقط", "الملائكة فقط"], 0,
             "«يا أيها الذين آمنوا آمنوا بالله ورسوله والكتاب الذي نزّل على رسوله والكتاب الذي أنزل من قبل».",
             "القرآن — سورة النساء، 4:136"))

    add("faith_084", "faith", "hard", "quran", Q, "17:55", False,
        fr=L("Quel Livre le Coran mentionne-t-il comme donné à Dâwûd ?",
             ["Le Zabûr", "La Torah", "L'Évangile", "Les Feuillets d'Ibrâhîm"], 0,
             "« … et Nous avons donné le Zabûr à Dâwûd. »",
             "Coran — Sourate Al-Isrâ, 17:55"),
        en=L("Which Book does the Quran mention as given to Dawud?",
             ["The Zabur (Psalms)", "The Torah", "The Gospel", "The Scrolls of Ibrahim"], 0,
             "\"…and We gave to Dawud the Zabur.\"",
             "Quran — Surah Al-Isra, 17:55"),
        ar=L("أي كتاب ذكر القرآنُ أنه أُوتي داوود؟",
             ["الزبور", "التوراة", "الإنجيل", "صحف إبراهيم"], 0,
             "«وآتينا داوود زبورًا».",
             "القرآن — سورة الإسراء، 17:55"))

    add("faith_085", "faith", "medium", "quran", Q, "72:1", False,
        fr=L("Quelle sourate porte le nom des djinns, qui écoutèrent le Coran et y crurent ?",
             ["Al-Jinn", "Al-Insân", "An-Nâs", "Al-Furqân"], 0,
             "« Dis : il m'a été révélé qu'un groupe de djinns prêta l'oreille, puis dit : nous avons entendu une lecture merveilleuse. »",
             "Coran — Sourate Al-Jinn, 72:1"),
        en=L("Which surah is named after the jinn, who listened to the Quran and believed?",
             ["Al-Jinn", "Al-Insan", "An-Nas", "Al-Furqan"], 0,
             "\"Say: it has been revealed to me that a group of the jinn listened and said: we have heard an amazing recitation.\"",
             "Quran — Surah Al-Jinn, 72:1"),
        ar=L("أي سورة سُمّيت بالجن الذين استمعوا القرآن فآمنوا؟",
             ["الجن", "الإنسان", "الناس", "الفرقان"], 0,
             "«قل أوحي إليّ أنه استمع نفر من الجن فقالوا إنا سمعنا قرآنًا عجبًا».",
             "القرآن — سورة الجن، 72:1"))

    add("faith_086", "faith", "hard", "quran", Q, "51:56", False,
        fr=L("Pour quoi les djinns et les hommes ont-ils été créés, selon la sourate Adh-Dhâriyât ?",
             ["Pour qu'ils L'adorent", "Pour peupler la terre", "Pour bâtir", "Pour se disputer"], 0,
             "« Je n'ai créé les djinns et les hommes que pour qu'ils M'adorent. »",
             "Coran — Sourate Adh-Dhâriyât, 51:56"),
        en=L("For what were jinn and mankind created, according to Surah Adh-Dhariyat?",
             ["That they worship Him", "To fill the earth", "To build", "To quarrel"], 0,
             "\"And I did not create the jinn and mankind except to worship Me.\"",
             "Quran — Surah Adh-Dhariyat, 51:56"),
        ar=L("لماذا خُلق الجن والإنس بحسب سورة الذاريات؟",
             ["ليعبدوه", "ليعمروا الأرض", "ليبنوا", "ليتنازعوا"], 0,
             "«وما خلقت الجن والإنس إلا ليعبدون».",
             "القرآن — سورة الذاريات، 51:56"))

    add("faith_087", "faith", "easy", "quran", Q, "3:185", False,
        fr=L("Que dit le Coran au sujet de toute âme et de la mort ?",
             ["Toute âme goûtera la mort", "Certaines âmes ne meurent pas", "La mort est un doute", "La mort est un sommeil sans fin"], 0,
             "« Toute âme goûtera la mort. Mais c'est seulement au Jour de la Résurrection que vous recevrez votre entière rétribution. »",
             "Coran — Sourate Âl ʿImrân, 3:185"),
        en=L("What does the Quran say about every soul and death?",
             ["Every soul will taste death", "Some souls do not die", "Death is a doubt", "Death is endless sleep"], 0,
             "\"Every soul will taste death, and you will only be given your full compensation on the Day of Resurrection.\"",
             "Quran — Surah Al-'Imran, 3:185"),
        ar=L("ماذا قال القرآن في شأن كل نفس والموت؟",
             ["كل نفس ذائقة الموت", "بعض النفوس لا تموت", "الموت شك", "الموت نوم لا ينتهي"], 0,
             "«كل نفس ذائقة الموت، وإنما توفّون أجوركم يوم القيامة».",
             "القرآن — سورة آل عمران، 3:185"))

    add("faith_088", "faith", "medium", "quran", Q, "99:6", False,
        fr=L("Dans quel état les hommes sortiront-ils, selon la sourate Az-Zalzala, pour qu'on leur montre leurs œuvres ?",
             ["Par groupes séparés", "Tous ensemble en un seul rang", "Endormis", "Silencieux et invisibles"], 0,
             "« Ce jour-là, les gens sortiront par groupes séparés pour que leur soient montrées leurs œuvres. »",
             "Coran — Sourate Az-Zalzala, 99:6"),
        en=L("In what state will people come forth, according to Surah Az-Zalzalah, to be shown their deeds?",
             ["In scattered groups", "All together in one rank", "Asleep", "Silent and invisible"], 0,
             "\"That Day, the people will depart separated in groups to be shown their deeds.\"",
             "Quran — Surah Az-Zalzalah, 99:6"),
        ar=L("بأي حال يصدر الناس بحسب سورة الزلزلة ليُروا أعمالهم؟",
             ["أشتاتًا", "جميعًا في صف واحد", "نيامًا", "صامتين غير مرئيين"], 0,
             "«يومئذ يصدر الناس أشتاتًا ليُروا أعمالهم».",
             "القرآن — سورة الزلزلة، 99:6"))

    add("faith_089", "faith", "hard", "quran", Q, "18:49", False,
        fr=L("Comment la sourate Al-Kahf décrit-elle le registre des œuvres au Jour dernier ?",
             ["Il ne laisse rien, petit ou grand, sans le compter", "Il ne retient que le grand", "Il est effacé", "Il est écrit par les hommes"], 0,
             "« Ils diront : “Malheur à nous ! Qu'est-ce donc que ce livre qui ne laisse rien, ni petit ni grand, sans le compter ?” »",
             "Coran — Sourate Al-Kahf, 18:49"),
        en=L("How does Surah Al-Kahf describe the record of deeds on the Last Day?",
             ["It leaves nothing small or great without accounting for it", "It records only great deeds", "It is erased", "It is written by people"], 0,
             "\"They will say: 'Woe to us! What is this book that leaves nothing small or great except that it has enumerated it?'\"",
             "Quran — Surah Al-Kahf, 18:49"),
        ar=L("كيف وصفت سورة الكهف كتاب الأعمال يوم القيامة؟",
             ["لا يغادر صغيرة ولا كبيرة إلا أحصاها", "يحصي الكبائر فقط", "يُمحى", "يكتبه الناس"], 0,
             "«ويقولون يا ويلتنا مال هذا الكتاب لا يغادر صغيرة ولا كبيرة إلا أحصاها».",
             "القرآن — سورة الكهف، 18:49"))

    add("faith_090", "faith", "medium", "quran", Q, "36:65", False,
        fr=L("Que le Coran dit-il des membres du corps au Jour du Jugement ?",
             ["Les mains parleront et les pieds témoigneront", "Ils resteront muets", "Ils seront cachés", "Ils seront transformés"], 0,
             "« Ce jour-là, Nous scellerons leurs bouches, tandis que leurs mains Nous parleront et que leurs jambes témoigneront de ce qu'ils faisaient. »",
             "Coran — Sourate Yâ-Sîn, 36:65"),
        en=L("What does the Quran say of the limbs on the Day of Judgement?",
             ["The hands will speak and the feet will testify", "They will remain silent", "They will be hidden", "They will be transformed"], 0,
             "\"That Day, We will seal over their mouths, and their hands will speak to Us, and their feet will testify about what they used to earn.\"",
             "Quran — Surah Ya-Sin, 36:65"),
        ar=L("ماذا قال القرآن عن الجوارح يوم القيامة؟",
             ["تكلّم الأيدي وتشهد الأرجل", "تبقى صامتة", "تُخفى", "تُبدَّل"], 0,
             "«اليوم نختم على أفواههم وتكلّمنا أيديهم وتشهد أرجلهم بما كانوا يكسبون».",
             "القرآن — سورة يس، 36:65"))

    # -- Prayer and purification -----------------------------------------
    add("faith_091", "faith", "easy", "quran", Q, "4:103", False,
        fr=L("Comment le Coran qualifie-t-il la prière quant à son horaire ?",
             ["Une prescription à heures fixes", "Libre à toute heure", "Une fois par semaine", "Seulement la nuit"], 0,
             "« La prière demeure, pour les croyants, une prescription à des temps déterminés. »",
             "Coran — Sourate An-Nisâ, 4:103"),
        en=L("How does the Quran describe the prayer with regard to its timing?",
             ["A decree at fixed times", "Free at any hour", "Once a week", "Only at night"], 0,
             "\"Indeed, prayer has been decreed upon the believers a decree of specified times.\"",
             "Quran — Surah An-Nisa, 4:103"),
        ar=L("كيف وصف القرآن الصلاة من جهة وقتها؟",
             ["كتابًا موقوتًا", "في أي وقت", "مرة في الأسبوع", "ليلًا فقط"], 0,
             "«إن الصلاة كانت على المؤمنين كتابًا موقوتًا».",
             "القرآن — سورة النساء، 4:103"))

    add("faith_092", "faith", "medium", "quran", Q, "29:45", False,
        fr=L("De quoi la prière préserve-t-elle, selon la sourate Al-ʿAnkabût ?",
             ["De la turpitude et du blâmable", "De la faim", "De la maladie", "Du voyage"], 0,
             "« Accomplis la prière : la prière préserve de la turpitude et du blâmable. »",
             "Coran — Sourate Al-ʿAnkabût, 29:45"),
        en=L("From what does prayer restrain, according to Surah Al-'Ankabut?",
             ["From immorality and wrongdoing", "From hunger", "From illness", "From travel"], 0,
             "\"And establish prayer: indeed, prayer prohibits immorality and wrongdoing.\"",
             "Quran — Surah Al-'Ankabut, 29:45"),
        ar=L("مِمّ تنهى الصلاة بحسب سورة العنكبوت؟",
             ["عن الفحشاء والمنكر", "عن الجوع", "عن المرض", "عن السفر"], 0,
             "«وأقم الصلاة، إن الصلاة تنهى عن الفحشاء والمنكر».",
             "القرآن — سورة العنكبوت، 29:45"))

    add("faith_093", "faith", "hard", "quran", Q, "2:238", False,
        fr=L("Quelle prière le Coran désigne-t-il particulièrement comme « la prière médiane » ?",
             ["Elle est nommée sans être identifiée, dans l'ordre de veiller sur les prières", "La prière de l'aube seule", "La prière du soir seule", "La prière du vendredi"], 0,
             "« Soyez assidus aux prières, et surtout à la prière médiane, et tenez-vous debout devant Allah avec humilité. »",
             "Coran — Sourate Al-Baqara, 2:238"),
        en=L("Which prayer does the Quran single out as \"the middle prayer\"?",
             ["It is named without being identified, in the command to guard the prayers", "The dawn prayer only", "The evening prayer only", "The Friday prayer"], 0,
             "\"Maintain with care the prayers and the middle prayer, and stand before Allah devoutly obedient.\"",
             "Quran — Surah Al-Baqarah, 2:238"),
        ar=L("أي صلاة خصّها القرآن بالذكر بوصفها «الصلاة الوسطى»؟",
             ["ذُكرت وصفًا في الأمر بالمحافظة على الصلوات", "الفجر وحدها", "المغرب وحدها", "الجمعة"], 0,
             "«حافظوا على الصلوات والصلاة الوسطى وقوموا لله قانتين».",
             "القرآن — سورة البقرة، 2:238"))

    add("faith_094", "faith", "easy", "quran", Q, "20:14", False,
        fr=L("Pour quelle raison le Coran ordonne-t-il d'accomplir la prière, dans la sourate Tâ-Hâ ?",
             ["Pour se souvenir d'Allah", "Pour se reposer", "Pour se réunir", "Pour compter les heures"], 0,
             "« Je suis Allah : nulle divinité à part Moi. Adore-Moi donc et accomplis la prière pour te souvenir de Moi. »",
             "Coran — Sourate Tâ-Hâ, 20:14"),
        en=L("For what reason does the Quran command the prayer, in Surah Ta-Ha?",
             ["For the remembrance of Allah", "For rest", "For gathering", "For counting the hours"], 0,
             "\"Indeed, I am Allah. There is no deity except Me, so worship Me and establish prayer for My remembrance.\"",
             "Quran — Surah Ta-Ha, 20:14"),
        ar=L("لأي غاية أمر القرآن بالصلاة في سورة طه؟",
             ["لذكر الله", "للراحة", "للاجتماع", "لعدّ الساعات"], 0,
             "«إنني أنا الله لا إله إلا أنا فاعبدني وأقم الصلاة لذكري».",
             "القرآن — سورة طه، 20:14"))

    add("faith_095", "faith", "medium", "quran", Q, "23:1-2", False,
        fr=L("Quelle qualité de la prière ouvre la liste des croyants qui réussissent, dans Al-Mu'minûn ?",
             ["L'humilité (khushûʿ) dans la prière", "La longueur", "La rapidité", "Le nombre"], 0,
             "« Bienheureux sont certes les croyants, ceux qui sont humbles dans leur prière. »",
             "Coran — Sourate Al-Mu'minûn, 23:1-2"),
        en=L("Which quality of prayer opens the list of successful believers, in Al-Mu'minun?",
             ["Humility (khushu') in prayer", "Length", "Speed", "Number"], 0,
             "\"Certainly will the believers have succeeded: they who are during their prayer humbly submissive.\"",
             "Quran — Surah Al-Mu'minun, 23:1-2"),
        ar=L("أي صفة في الصلاة افتُتحت بها صفات المؤمنين المفلحين في سورة المؤمنون؟",
             ["الخشوع في الصلاة", "الطول", "السرعة", "العدد"], 0,
             "«قد أفلح المؤمنون، الذين هم في صلاتهم خاشعون».",
             "القرآن — سورة المؤمنون، 23:1-2"))

    add("faith_096", "faith", "hard", "quran", Q, "17:78", False,
        fr=L("Quelle prière la sourate Al-Isrâ décrit-elle comme « attestée » (mashhûda) ?",
             ["La lecture de l'aube", "La prière du soir", "La prière de midi", "La prière du vendredi"], 0,
             "« Accomplis la prière au déclin du soleil jusqu'à l'obscurité de la nuit, et la lecture à l'aube : la lecture à l'aube a des témoins. »",
             "Coran — Sourate Al-Isrâ, 17:78"),
        en=L("Which prayer does Surah Al-Isra describe as \"witnessed\" (mashhudah)?",
             ["The recitation at dawn", "The evening prayer", "The noon prayer", "The Friday prayer"], 0,
             "\"Establish prayer at the decline of the sun until the darkness of the night, and the recitation at dawn: indeed, the recitation at dawn is ever witnessed.\"",
             "Quran — Surah Al-Isra, 17:78"),
        ar=L("أي صلاة وصفتها سورة الإسراء بأنها «مشهودة»؟",
             ["قرآن الفجر", "المغرب", "الظهر", "الجمعة"], 0,
             "«أقم الصلاة لدلوك الشمس إلى غسق الليل وقرآن الفجر، إن قرآن الفجر كان مشهودًا».",
             "القرآن — سورة الإسراء، 17:78"))

    add("faith_097", "faith", "easy", "quran", Q, "2:153", False,
        fr=L("Quelles deux choses le Coran ordonne-t-il de chercher comme secours ?",
             ["La patience et la prière", "La force et la richesse", "Le voyage et le repos", "Le silence et la solitude"], 0,
             "« Ô les croyants ! Cherchez secours dans l'endurance et la prière : Allah est avec ceux qui sont endurants. »",
             "Coran — Sourate Al-Baqara, 2:153"),
        en=L("Which two things does the Quran command be sought as help?",
             ["Patience and prayer", "Strength and wealth", "Travel and rest", "Silence and solitude"], 0,
             "\"O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient.\"",
             "Quran — Surah Al-Baqarah, 2:153"),
        ar=L("بأي شيئين أمر القرآن أن يُستعان؟",
             ["الصبر والصلاة", "القوة والمال", "السفر والراحة", "الصمت والعزلة"], 0,
             "«يا أيها الذين آمنوا استعينوا بالصبر والصلاة، إن الله مع الصابرين».",
             "القرآن — سورة البقرة، 2:153"))

    add("faith_098", "faith", "medium", "creed", C, WP, False,
        fr=L("Combien de rakʿas comporte la prière obligatoire du Dhuhr ?",
             ["Quatre", "Deux", "Trois", "Cinq"], 0,
             "Le Dhuhr, le ʿAsr et le ʿIshâ comptent chacun quatre rakʿas obligatoires ; c'est un point sur lequel les écoles s'accordent.",
             "Pratique établie, accord des écoles"),
        en=L("How many rak'ahs does the obligatory Dhuhr prayer have?",
             ["Four", "Two", "Three", "Five"], 0,
             "Dhuhr, 'Asr and 'Isha each have four obligatory rak'ahs; the schools agree on this.",
             "Established practice, agreed across the schools"),
        ar=L("كم ركعة في صلاة الظهر المفروضة؟",
             ["أربع", "ركعتان", "ثلاث", "خمس"], 0,
             "الظهر والعصر والعشاء أربع ركعات لكل منها، وهو موضع اتفاق بين المذاهب.",
             "ممارسة ثابتة باتفاق المذاهب"))

    add("faith_099", "faith", "easy", "creed", C, WP, False,
        fr=L("Quelle est la dernière des cinq prières obligatoires du jour ?",
             ["Al-ʿIshâ", "Al-Fajr", "Al-Maghrib", "Al-ʿAsr"], 0,
             "L'ordre est : Fajr, Dhuhr, ʿAsr, Maghrib, ʿIshâ.",
             "Pratique établie, accord des écoles"),
        en=L("Which is the last of the five obligatory daily prayers?",
             ["Al-'Isha", "Al-Fajr", "Al-Maghrib", "Al-'Asr"], 0,
             "The order is: Fajr, Dhuhr, 'Asr, Maghrib, 'Isha.",
             "Established practice, agreed across the schools"),
        ar=L("ما آخر الصلوات الخمس المفروضة في اليوم؟",
             ["العشاء", "الفجر", "المغرب", "العصر"], 0,
             "ترتيبها: الفجر، الظهر، العصر، المغرب، العشاء.",
             "ممارسة ثابتة باتفاق المذاهب"))

    add("faith_100", "faith", "hard", "creed", C, WT, False,
        fr=L("Comment appelle-t-on la posture de prosternation dans la prière ?",
             ["Le sujûd", "Le rukûʿ", "Le qiyâm", "Le tashahhud"], 0,
             "Le qiyâm est la station debout, le rukûʿ l'inclinaison, le sujûd la prosternation, le tashahhud la position assise de témoignage.",
             "Terminologie établie"),
        en=L("What is the prostration position in the prayer called?",
             ["The sujud", "The ruku'", "The qiyam", "The tashahhud"], 0,
             "Qiyam is standing, ruku' is bowing, sujud is prostration, and tashahhud is the sitting of testimony.",
             "Established terminology"),
        ar=L("بماذا تُسمّى هيئة السجود في الصلاة؟",
             ["السجود", "الركوع", "القيام", "التشهد"], 0,
             "القيام الوقوف، والركوع الانحناء، والسجود وضع الجبهة، والتشهد الجلوس للشهادة.",
             "مصطلح ثابت"))

    # -- Fasting, zakat, hajj ---------------------------------------------
    add("faith_101", "faith", "easy", "quran", Q, "2:184", False,
        fr=L("Que prévoit le Coran pour le malade ou le voyageur durant Ramadan ?",
             ["Un nombre égal de jours à rattraper", "Rien du tout", "Une double obligation", "Un jeûne perpétuel"], 0,
             "« Quiconque d'entre vous est malade ou en voyage, qu'il jeûne un nombre égal d'autres jours. »",
             "Coran — Sourate Al-Baqara, 2:184"),
        en=L("What does the Quran provide for the sick or the traveller during Ramadan?",
             ["An equal number of days to make up", "Nothing at all", "A double obligation", "A perpetual fast"], 0,
             "\"So whoever among you is ill or on a journey, then an equal number of other days.\"",
             "Quran — Surah Al-Baqarah, 2:184"),
        ar=L("ما الذي شرعه القرآن للمريض والمسافر في رمضان؟",
             ["عدة من أيام أخر", "لا شيء", "مضاعفة الفرض", "صيام الدهر"], 0,
             "«فمن كان منكم مريضًا أو على سفر فعدة من أيام أخر».",
             "القرآن — سورة البقرة، 2:184"))

    add("faith_102", "faith", "medium", "quran", Q, "2:183", False,
        fr=L("Quel but le Coran donne-t-il au jeûne prescrit ?",
             ["Atteindre la piété (taqwâ)", "Perdre du poids", "Économiser", "Se reposer"], 0,
             "« Le jeûne vous a été prescrit comme il le fut à ceux qui vous ont précédés, afin que vous atteigniez la piété. »",
             "Coran — Sourate Al-Baqara, 2:183"),
        en=L("What purpose does the Quran give to the prescribed fast?",
             ["To attain God-consciousness (taqwa)", "To lose weight", "To save money", "To rest"], 0,
             "\"Fasting is prescribed for you as it was prescribed for those before you, that you may become righteous.\"",
             "Quran — Surah Al-Baqarah, 2:183"),
        ar=L("أي غاية جعلها القرآن للصيام المفروض؟",
             ["بلوغ التقوى", "إنقاص الوزن", "الادخار", "الراحة"], 0,
             "«كُتب عليكم الصيام كما كُتب على الذين من قبلكم لعلكم تتقون».",
             "القرآن — سورة البقرة، 2:183"))

    add("faith_103", "faith", "hard", "quran", Q, "2:186", False,
        fr=L("Que répond Allah, au milieu des versets du jeûne, à qui L'interroge sur Sa proximité ?",
             ["« Je suis proche : Je réponds à l'appel de celui qui M'invoque »", "« Attendez la nuit »", "« Demandez aux anges »", "« Cherchez au loin »"], 0,
             "« Quand Mes serviteurs t'interrogent sur Moi, alors Je suis tout proche : Je réponds à l'appel de celui qui Me prie quand il Me prie. »",
             "Coran — Sourate Al-Baqara, 2:186"),
        en=L("What does Allah answer, amid the verses on fasting, to those who ask about His nearness?",
             ["\"I am near: I respond to the call of the caller when he calls upon Me\"", "\"Wait for the night\"", "\"Ask the angels\"", "\"Seek far away\""], 0,
             "\"And when My servants ask you concerning Me, indeed I am near. I respond to the invocation of the supplicant when he calls upon Me.\"",
             "Quran — Surah Al-Baqarah, 2:186"),
        ar=L("بماذا أجاب الله في وسط آيات الصيام مَن سأل عن قربه؟",
             ["«فإني قريب أجيب دعوة الداعِ إذا دعان»", "«انتظروا الليل»", "«اسألوا الملائكة»", "«اطلبوا بعيدًا»"], 0,
             "«وإذا سألك عبادي عني فإني قريب، أجيب دعوة الداعِ إذا دعان».",
             "القرآن — سورة البقرة، 2:186"))

    add("faith_104", "faith", "medium", "quran", Q, "9:60", False,
        fr=L("Combien de catégories de bénéficiaires de la zakât le Coran énumère-t-il ?",
             ["Huit", "Trois", "Cinq", "Douze"], 0,
             "« Les aumônes ne sont destinées qu'aux pauvres, aux indigents, à ceux qui y travaillent, à ceux dont les cœurs sont à gagner, à l'affranchissement des captifs, aux endettés, dans le sentier d'Allah, et au voyageur en détresse. »",
             "Coran — Sourate At-Tawba, 9:60"),
        en=L("How many categories of zakat recipients does the Quran list?",
             ["Eight", "Three", "Five", "Twelve"], 0,
             "\"Zakat is only for the poor, the needy, those employed to collect it, those whose hearts are to be reconciled, for freeing captives, for those in debt, in the cause of Allah, and for the traveller.\"",
             "Quran — Surah At-Tawbah, 9:60"),
        ar=L("كم صنفًا من مصارف الزكاة عدّدها القرآن؟",
             ["ثمانية", "ثلاثة", "خمسة", "اثنا عشر"], 0,
             "«إنما الصدقات للفقراء والمساكين والعاملين عليها والمؤلفة قلوبهم وفي الرقاب والغارمين وفي سبيل الله وابن السبيل».",
             "القرآن — سورة التوبة، 9:60"))

    add("faith_105", "faith", "hard", "quran", Q, "9:103", False,
        fr=L("Quel effet le Coran attribue-t-il à la zakât prélevée sur les biens ?",
             ["Elle purifie et fait croître", "Elle appauvrit", "Elle est symbolique", "Elle remplace la prière"], 0,
             "« Prélève de leurs biens une aumône par laquelle tu les purifies et les bénis. »",
             "Coran — Sourate At-Tawba, 9:103"),
        en=L("What effect does the Quran attribute to the zakat taken from wealth?",
             ["It purifies and causes to grow", "It impoverishes", "It is symbolic", "It replaces the prayer"], 0,
             "\"Take from their wealth a charity by which you purify them and cause them increase.\"",
             "Quran — Surah At-Tawbah, 9:103"),
        ar=L("أي أثر نسبه القرآن للزكاة المأخوذة من الأموال؟",
             ["تطهّر وتزكّي", "تُفقر", "رمزية", "تُغني عن الصلاة"], 0,
             "«خذ من أموالهم صدقة تطهّرهم وتزكّيهم بها».",
             "القرآن — سورة التوبة، 9:103"))

    add("faith_106", "faith", "easy", "quran", Q, "2:110", False,
        fr=L("Quelles deux obligations le Coran associe-t-il très souvent l'une à l'autre ?",
             ["La prière et la zakât", "Le jeûne et le voyage", "Le pèlerinage et le commerce", "La lecture et l'écriture"], 0,
             "« Accomplissez la prière et acquittez la zakât ; tout ce que vous avancez de bien pour vous-mêmes, vous le retrouverez auprès d'Allah. »",
             "Coran — Sourate Al-Baqara, 2:110"),
        en=L("Which two obligations does the Quran most often pair together?",
             ["Prayer and zakat", "Fasting and travel", "Pilgrimage and trade", "Reading and writing"], 0,
             "\"And establish prayer and give zakat; whatever good you put forward for yourselves, you will find it with Allah.\"",
             "Quran — Surah Al-Baqarah, 2:110"),
        ar=L("أي فريضتين كثيرًا ما يقرن بينهما القرآن؟",
             ["الصلاة والزكاة", "الصيام والسفر", "الحج والتجارة", "القراءة والكتابة"], 0,
             "«وأقيموا الصلاة وآتوا الزكاة، وما تقدّموا لأنفسكم من خير تجدوه عند الله».",
             "القرآن — سورة البقرة، 2:110"))

    add("faith_107", "faith", "medium", "quran", Q, "22:37", False,
        fr=L("Que dit le Coran de ce qui parvient à Allah dans le sacrifice ?",
             ["Ni la chair ni le sang, mais la piété qui vient du croyant", "La chair seule", "Le sang seul", "Le nombre de bêtes"], 0,
             "« Ni leurs chairs ni leurs sangs n'atteignent Allah, mais ce qui L'atteint de votre part, c'est la piété. »",
             "Coran — Sourate Al-Hajj, 22:37"),
        en=L("What does the Quran say reaches Allah in the sacrifice?",
             ["Neither the flesh nor the blood, but the piety of the believer", "The flesh alone", "The blood alone", "The number of animals"], 0,
             "\"Their meat will not reach Allah, nor will their blood, but what reaches Him is piety from you.\"",
             "Quran — Surah Al-Hajj, 22:37"),
        ar=L("ماذا قال القرآن عمّا ينال الله من الأضاحي؟",
             ["لا لحومها ولا دماؤها بل التقوى منكم", "اللحوم وحدها", "الدماء وحدها", "عدد الذبائح"], 0,
             "«لن ينال الله لحومها ولا دماؤها ولكن يناله التقوى منكم».",
             "القرآن — سورة الحج، 22:37"))

    add("faith_108", "faith", "hard", "quran", Q, "2:197", False,
        fr=L("Quelle est la meilleure provision pour le pèlerinage, selon le Coran ?",
             ["La piété", "L'or", "Les vivres", "Les montures"], 0,
             "« Et prenez vos provisions ; mais vraiment la meilleure provision est la piété. »",
             "Coran — Sourate Al-Baqara, 2:197"),
        en=L("What is the best provision for the pilgrimage, according to the Quran?",
             ["God-consciousness (taqwa)", "Gold", "Food", "Mounts"], 0,
             "\"And take provisions, but indeed, the best provision is God-consciousness.\"",
             "Quran — Surah Al-Baqarah, 2:197"),
        ar=L("ما خير الزاد للحج بحسب القرآن؟",
             ["التقوى", "الذهب", "الطعام", "الركائب"], 0,
             "«وتزوّدوا فإن خير الزاد التقوى».",
             "القرآن — سورة البقرة، 2:197"))

    add("faith_109", "faith", "easy", "quran", Q, "22:29", False,
        fr=L("Quel rite le Coran mentionne-t-il autour de l'Ancienne Maison ?",
             ["La circumambulation (tawâf)", "La course dans le désert", "L'ascension d'une colline", "Le jeûne sur place"], 0,
             "« … et qu'ils fassent les circumambulations autour de l'Ancienne Maison. »",
             "Coran — Sourate Al-Hajj, 22:29"),
        en=L("Which rite does the Quran mention around the Ancient House?",
             ["Circumambulation (tawaf)", "Running in the desert", "Climbing a hill", "Fasting on the spot"], 0,
             "\"…and let them perform tawaf around the Ancient House.\"",
             "Quran — Surah Al-Hajj, 22:29"),
        ar=L("أي نسك ذكره القرآن حول البيت العتيق؟",
             ["الطواف", "الجري في الصحراء", "صعود تل", "الصيام هناك"], 0,
             "«وليطّوّفوا بالبيت العتيق».",
             "القرآن — سورة الحج، 22:29"))

    add("faith_110", "faith", "medium", "quran", Q, "2:198", False,
        fr=L("Où le Coran ordonne-t-il d'invoquer Allah, après avoir quitté ʿArafat ?",
             ["Auprès d'al-Mashʿar al-Harâm, à Muzdalifa", "Sur le mont Uhud", "À Qubâ", "À Tâ'if"], 0,
             "« Quand vous déferlez depuis ʿArafat, invoquez Allah auprès d'al-Mashʿar al-Harâm. »",
             "Coran — Sourate Al-Baqara, 2:198"),
        en=L("Where does the Quran command Allah be remembered, after leaving 'Arafat?",
             ["At al-Mash'ar al-Haram, in Muzdalifah", "On Mount Uhud", "At Quba", "At Ta'if"], 0,
             "\"But when you depart from 'Arafat, remember Allah at al-Mash'ar al-Haram.\"",
             "Quran — Surah Al-Baqarah, 2:198"),
        ar=L("أين أمر القرآن بذكر الله بعد الإفاضة من عرفات؟",
             ["عند المشعر الحرام بمزدلفة", "على أُحد", "بقباء", "بالطائف"], 0,
             "«فإذا أفضتم من عرفات فاذكروا الله عند المشعر الحرام».",
             "القرآن — سورة البقرة، 2:198"))

    # -- Repentance, remembrance, trust -----------------------------------
    add("faith_111", "faith", "easy", "quran", Q, "66:8", False,
        fr=L("Quelle sorte de repentir le Coran demande-t-il aux croyants ?",
             ["Un repentir sincère (tawba nasûh)", "Un repentir écrit", "Un repentir public", "Un repentir annuel"], 0,
             "« Ô les croyants ! Repentez-vous à Allah d'un repentir sincère. »",
             "Coran — Sourate At-Tahrîm, 66:8"),
        en=L("What kind of repentance does the Quran ask of the believers?",
             ["A sincere repentance (tawbah nasuh)", "A written repentance", "A public repentance", "A yearly repentance"], 0,
             "\"O you who have believed, repent to Allah with sincere repentance.\"",
             "Quran — Surah At-Tahrim, 66:8"),
        ar=L("أي توبة طلبها القرآن من المؤمنين؟",
             ["توبة نصوحًا", "توبة مكتوبة", "توبة علنية", "توبة سنوية"], 0,
             "«يا أيها الذين آمنوا توبوا إلى الله توبة نصوحًا».",
             "القرآن — سورة التحريم، 66:8"))

    add("faith_112", "faith", "hard", "quran", Q, "42:25", False,
        fr=L("Que dit la sourate Ash-Shûrâ de l'accueil du repentir ?",
             ["C'est Lui qui accepte le repentir de Ses serviteurs et efface les méfaits", "Le repentir n'est pas accepté", "Il faut un intermédiaire", "Il faut attendre un an"], 0,
             "« C'est Lui qui agrée le repentir de Ses serviteurs, pardonne les méfaits et sait ce que vous faites. »",
             "Coran — Sourate Ash-Shûrâ, 42:25"),
        en=L("What does Surah Ash-Shura say of the acceptance of repentance?",
             ["It is He who accepts repentance from His servants and pardons misdeeds", "Repentance is not accepted", "An intermediary is needed", "One must wait a year"], 0,
             "\"And it is He who accepts repentance from His servants and pardons misdeeds, and He knows what you do.\"",
             "Quran — Surah Ash-Shura, 42:25"),
        ar=L("ماذا قالت سورة الشورى في قبول التوبة؟",
             ["هو الذي يقبل التوبة عن عباده ويعفو عن السيئات", "لا تُقبل التوبة", "لا بد من وسيط", "لا بد من انتظار سنة"], 0,
             "«وهو الذي يقبل التوبة عن عباده ويعفو عن السيئات ويعلم ما تفعلون».",
             "القرآن — سورة الشورى، 42:25"))

    add("faith_113", "faith", "medium", "quran", Q, "3:135", False,
        fr=L("Que font ceux que le Coran loue, après avoir commis une faute ?",
             ["Ils se souviennent d'Allah et demandent pardon", "Ils s'enfuient", "Ils se taisent", "Ils accusent autrui"], 0,
             "« Et pour ceux qui, après avoir commis une turpitude ou fait du tort à eux-mêmes, se souviennent d'Allah et demandent pardon pour leurs péchés. »",
             "Coran — Sourate Âl ʿImrân, 3:135"),
        en=L("What do those praised by the Quran do after committing a wrong?",
             ["They remember Allah and ask forgiveness", "They flee", "They stay silent", "They blame others"], 0,
             "\"And those who, when they commit an immorality or wrong themselves, remember Allah and seek forgiveness for their sins.\"",
             "Quran — Surah Al-'Imran, 3:135"),
        ar=L("ماذا يفعل من أثنى عليهم القرآن بعد وقوع الذنب؟",
             ["ذكروا الله فاستغفروا لذنوبهم", "هربوا", "سكتوا", "اتهموا غيرهم"], 0,
             "«والذين إذا فعلوا فاحشة أو ظلموا أنفسهم ذكروا الله فاستغفروا لذنوبهم».",
             "القرآن — سورة آل عمران، 3:135"))

    add("faith_114", "faith", "easy", "quran", Q, "33:41-42", False,
        fr=L("À quelle fréquence le Coran ordonne-t-il d'évoquer Allah, dans la sourate Al-Ahzâb ?",
             ["Beaucoup, matin et soir", "Une fois par an", "Une fois par semaine", "Seulement en voyage"], 0,
             "« Ô les croyants ! Évoquez Allah d'une façon abondante, et glorifiez-Le à la pointe et au déclin du jour. »",
             "Coran — Sourate Al-Ahzâb, 33:41-42"),
        en=L("How often does the Quran command the remembrance of Allah, in Surah Al-Ahzab?",
             ["Much, morning and evening", "Once a year", "Once a week", "Only while travelling"], 0,
             "\"O you who have believed, remember Allah with much remembrance, and exalt Him morning and afternoon.\"",
             "Quran — Surah Al-Ahzab, 33:41-42"),
        ar=L("بأي قدر أمر القرآن بذكر الله في سورة الأحزاب؟",
             ["ذكرًا كثيرًا بكرة وأصيلًا", "مرة في السنة", "مرة في الأسبوع", "في السفر فقط"], 0,
             "«يا أيها الذين آمنوا اذكروا الله ذكرًا كثيرًا، وسبّحوه بكرة وأصيلًا».",
             "القرآن — سورة الأحزاب، 33:41-42"))

    add("faith_115", "faith", "hard", "quran", Q, "3:190-191", False,
        fr=L("Sur quoi méditent « les doués d'intelligence », selon la fin de la sourate Âl ʿImrân ?",
             ["La création des cieux et de la terre, en toute posture", "Les récoltes", "Les caravanes", "Les généalogies"], 0,
             "« Ceux qui évoquent Allah debout, assis et couchés sur leurs côtés, et méditent sur la création des cieux et de la terre. »",
             "Coran — Sourate Âl ʿImrân, 3:190-191"),
        en=L("On what do \"those of understanding\" reflect, at the end of Surah Al-'Imran?",
             ["The creation of the heavens and the earth, in every posture", "The harvests", "The caravans", "The genealogies"], 0,
             "\"Who remember Allah while standing, sitting, and lying on their sides, and reflect upon the creation of the heavens and the earth.\"",
             "Quran — Surah Al-'Imran, 3:190-191"),
        ar=L("فيمَ يتفكّر «أولو الألباب» في خاتمة سورة آل عمران؟",
             ["في خلق السماوات والأرض على كل حال", "في الزروع", "في القوافل", "في الأنساب"], 0,
             "«الذين يذكرون الله قيامًا وقعودًا وعلى جنوبهم ويتفكرون في خلق السماوات والأرض».",
             "القرآن — سورة آل عمران، 3:190-191"))

    add("faith_116", "faith", "medium", "quran", Q, "3:159", False,
        fr=L("Que le Coran ordonne-t-il de faire après avoir pris une résolution ?",
             ["Placer sa confiance en Allah", "Attendre un signe", "Demander à un devin", "Renoncer"], 0,
             "« Et quand tu as pris une décision, place ta confiance en Allah : Allah aime ceux qui Lui font confiance. »",
             "Coran — Sourate Âl ʿImrân, 3:159"),
        en=L("What does the Quran command be done once a decision is taken?",
             ["Place one's trust in Allah", "Wait for a sign", "Ask a soothsayer", "Give up"], 0,
             "\"And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely upon Him.\"",
             "Quran — Surah Al-'Imran, 3:159"),
        ar=L("بماذا أمر القرآن بعد عقد العزم؟",
             ["التوكل على الله", "انتظار علامة", "سؤال كاهن", "الترك"], 0,
             "«فإذا عزمت فتوكّل على الله، إن الله يحب المتوكلين».",
             "القرآن — سورة آل عمران، 3:159"))

    add("faith_117", "faith", "easy", "quran", Q, "94:7-8", False,
        fr=L("Vers qui la sourate Ash-Sharh oriente-t-elle le désir, une fois la tâche accomplie ?",
             ["Vers son Seigneur", "Vers le repos", "Vers la famille", "Vers les gens"], 0,
             "« Quand tu te libères, lève-toi ; et à ton Seigneur aspire. »",
             "Coran — Sourate Ash-Sharh, 94:7-8"),
        en=L("Toward whom does Surah Ash-Sharh direct one's longing, once the task is done?",
             ["Toward his Lord", "Toward rest", "Toward family", "Toward people"], 0,
             "\"So when you have finished, stand up, and to your Lord direct your longing.\"",
             "Quran — Surah Ash-Sharh, 94:7-8"),
        ar=L("إلى مَن وجّهت سورة الشرح الرغبة بعد الفراغ من العمل؟",
             ["إلى ربه", "إلى الراحة", "إلى الأهل", "إلى الناس"], 0,
             "«فإذا فرغت فانصب، وإلى ربك فارغب».",
             "القرآن — سورة الشرح، 94:7-8"))

    add("faith_118", "faith", "hard", "quran", Q, "57:20", False,
        fr=L("À quoi la sourate Al-Hadîd compare-t-elle la vie de ce monde ?",
             ["Une pluie dont la végétation émerveille, puis jaunit et devient débris", "Un long voyage", "Une montagne", "Un océan"], 0,
             "« Sachez que la vie présente n'est que jeu, amusement… comme une pluie dont la végétation qu'elle fait pousser plaît aux cultivateurs, puis elle jaunit et devient des débris. »",
             "Coran — Sourate Al-Hadîd, 57:20"),
        en=L("To what does Surah Al-Hadid compare the life of this world?",
             ["Rain whose growth delights, then yellows and turns to debris", "A long journey", "A mountain", "An ocean"], 0,
             "\"Know that the life of this world is but amusement… like the example of a rain whose resulting plant growth pleases the tillers; then it dries and you see it turned yellow, then it becomes debris.\"",
             "Quran — Surah Al-Hadid, 57:20"),
        ar=L("بماذا شبّهت سورة الحديد الحياة الدنيا؟",
             ["بغيث أعجب النبات ثم يهيج فيصير حطامًا", "برحلة طويلة", "بجبل", "بمحيط"], 0,
             "«اعلموا أنما الحياة الدنيا لعب ولهو… كمثل غيث أعجب الكفار نباته ثم يهيج فتراه مصفرًّا ثم يكون حطامًا».",
             "القرآن — سورة الحديد، 57:20"))

    add("faith_119", "faith", "medium", "quran", Q, "18:46", False,
        fr=L("Que le Coran déclare-t-il meilleur que les biens et les enfants, parure de ce monde ?",
             ["Les bonnes œuvres qui persistent", "L'or", "La renommée", "Les terres"], 0,
             "« Les biens et les enfants sont l'ornement de la vie de ce monde. Mais les bonnes œuvres qui persistent ont auprès de ton Seigneur une meilleure récompense. »",
             "Coran — Sourate Al-Kahf, 18:46"),
        en=L("What does the Quran declare better than wealth and children, the adornment of this world?",
             ["The enduring good deeds", "Gold", "Fame", "Land"], 0,
             "\"Wealth and children are the adornment of the life of this world, but the enduring good deeds are better with your Lord for reward.\"",
             "Quran — Surah Al-Kahf, 18:46"),
        ar=L("ما الذي جعله القرآن خيرًا من المال والبنين زينة الدنيا؟",
             ["الباقيات الصالحات", "الذهب", "الشهرة", "الأرض"], 0,
             "«المال والبنون زينة الحياة الدنيا، والباقيات الصالحات خير عند ربك ثوابًا».",
             "القرآن — سورة الكهف، 18:46"))

    add("faith_120", "faith", "hard", "quran", Q, "23:115", False,
        fr=L("Quelle question le Coran pose-t-il sur le but de la création de l'homme ?",
             ["« Pensiez-vous que Nous vous avions créés sans but ? »", "« Qui vous a nommés ? »", "« Où irez-vous ? »", "« Combien êtes-vous ? »"], 0,
             "« Pensiez-vous que Nous vous avions créés sans but et que vous ne seriez pas ramenés vers Nous ? »",
             "Coran — Sourate Al-Mu'minûn, 23:115"),
        en=L("What question does the Quran ask about the purpose of human creation?",
             ["\"Did you think We created you aimlessly?\"", "\"Who named you?\"", "\"Where will you go?\"", "\"How many are you?\""], 0,
             "\"Then did you think that We created you uselessly and that to Us you would not be returned?\"",
             "Quran — Surah Al-Mu'minun, 23:115"),
        ar=L("أي سؤال طرحه القرآن عن الغاية من خلق الإنسان؟",
             ["«أفحسبتم أنما خلقناكم عبثًا؟»", "«من سمّاكم؟»", "«إلى أين تذهبون؟»", "«كم أنتم؟»"], 0,
             "«أفحسبتم أنما خلقناكم عبثًا وأنكم إلينا لا تُرجعون».",
             "القرآن — سورة المؤمنون، 23:115"))

    add("faith_121", "faith", "easy", "quran", Q, "2:152", False,
        fr=L("Quelle promesse le Coran fait-il à qui se souvient d'Allah ?",
             ["« Souvenez-vous de Moi, Je Me souviendrai de vous »", "« Vous serez riches »", "« Vous vivrez longtemps »", "« Vous voyagerez »"], 0,
             "« Souvenez-vous de Moi donc : Je Me souviendrai de vous. Remerciez-Moi et ne soyez pas ingrats. »",
             "Coran — Sourate Al-Baqara, 2:152"),
        en=L("What promise does the Quran make to the one who remembers Allah?",
             ["\"Remember Me; I will remember you\"", "\"You will be rich\"", "\"You will live long\"", "\"You will travel\""], 0,
             "\"So remember Me; I will remember you. And be grateful to Me and do not deny Me.\"",
             "Quran — Surah Al-Baqarah, 2:152"),
        ar=L("أي وعد قطعه القرآن لمن ذكر الله؟",
             ["«فاذكروني أذكركم»", "«ستغتنون»", "«ستعمّرون»", "«ستسافرون»"], 0,
             "«فاذكروني أذكركم واشكروا لي ولا تكفرون».",
             "القرآن — سورة البقرة، 2:152"))

    add("faith_122", "faith", "medium", "quran", Q, "4:59", False,
        fr=L("À qui le Coran ordonne-t-il de renvoyer les litiges ?",
             ["À Allah et au Messager ﷺ", "Aux anciens", "Au marché", "Aux poètes"], 0,
             "« Puis, si vous vous disputez en quoi que ce soit, renvoyez-le à Allah et au Messager, si vous croyez en Allah et au Jour dernier. »",
             "Coran — Sourate An-Nisâ, 4:59"),
        en=L("To whom does the Quran command disputes be referred?",
             ["To Allah and the Messenger ﷺ", "To the elders", "To the market", "To the poets"], 0,
             "\"And if you disagree over anything, refer it to Allah and the Messenger, if you believe in Allah and the Last Day.\"",
             "Quran — Surah An-Nisa, 4:59"),
        ar=L("إلى مَن أمر القرآن بردّ التنازع؟",
             ["إلى الله والرسول ﷺ", "إلى الشيوخ", "إلى السوق", "إلى الشعراء"], 0,
             "«فإن تنازعتم في شيء فردّوه إلى الله والرسول إن كنتم تؤمنون بالله واليوم الآخر».",
             "القرآن — سورة النساء، 4:59"))

    add("faith_123", "faith", "hard", "quran", Q, "8:2", False,
        fr=L("Comment la sourate Al-Anfâl décrit-elle le cœur des croyants à l'évocation d'Allah ?",
             ["Leurs cœurs frémissent, et leur foi augmente à la récitation", "Ils s'endurcissent", "Ils s'endorment", "Ils oublient"], 0,
             "« Les vrais croyants sont ceux dont les cœurs frémissent quand on mentionne Allah, et dont la foi augmente quand on leur récite Ses versets. »",
             "Coran — Sourate Al-Anfâl, 8:2"),
        en=L("How does Surah Al-Anfal describe the believers' hearts at the mention of Allah?",
             ["Their hearts tremble, and their faith increases at the recitation", "They harden", "They fall asleep", "They forget"], 0,
             "\"The believers are only those who, when Allah is mentioned, their hearts become fearful, and when His verses are recited to them, it increases them in faith.\"",
             "Quran — Surah Al-Anfal, 8:2"),
        ar=L("كيف وصفت سورة الأنفال قلوب المؤمنين عند ذكر الله؟",
             ["وجلت قلوبهم وزادتهم الآيات إيمانًا", "قست", "نامت", "نسيت"], 0,
             "«إنما المؤمنون الذين إذا ذُكر الله وجلت قلوبهم وإذا تُليت عليهم آياته زادتهم إيمانًا».",
             "القرآن — سورة الأنفال، 8:2"))

    add("faith_124", "faith", "easy", "quran", Q, "6:162", False,
        fr=L("Que le Coran ordonne-t-il de dédier entièrement au Seigneur des mondes ?",
             ["La prière, les actes de dévotion, la vie et la mort", "Le commerce", "Les récoltes", "Les voyages"], 0,
             "« Dis : en vérité, ma prière, mes actes de dévotion, ma vie et ma mort appartiennent à Allah, Seigneur de l'univers. »",
             "Coran — Sourate Al-Anʿâm, 6:162"),
        en=L("What does the Quran command be dedicated entirely to the Lord of the worlds?",
             ["Prayer, acts of devotion, living and dying", "Trade", "Harvests", "Journeys"], 0,
             "\"Say: indeed, my prayer, my rites of sacrifice, my living and my dying are for Allah, Lord of the worlds.\"",
             "Quran — Surah Al-An'am, 6:162"),
        ar=L("ماذا أمر القرآن أن يُخلص كله لرب العالمين؟",
             ["الصلاة والنسك والمحيا والممات", "التجارة", "الزروع", "الأسفار"], 0,
             "«قل إن صلاتي ونسكي ومحياي ومماتي لله رب العالمين».",
             "القرآن — سورة الأنعام، 6:162"))

    add("faith_125", "faith", "hard", "quran", Q, "98:5", False,
        fr=L("Quelle condition la sourate Al-Bayyina met-elle à l'adoration ordonnée ?",
             ["Adorer Allah en Lui vouant un culte exclusif et sincère", "Adorer en public", "Adorer par écrit", "Adorer en groupe seulement"], 0,
             "« Il ne leur a été commandé que d'adorer Allah, en Lui vouant un culte exclusif, d'accomplir la prière et d'acquitter la zakât. »",
             "Coran — Sourate Al-Bayyina, 98:5"),
        en=L("Which condition does Surah Al-Bayyinah set on the worship commanded?",
             ["To worship Allah sincerely, devoting religion purely to Him", "To worship in public", "To worship in writing", "To worship only in groups"], 0,
             "\"And they were not commanded except to worship Allah, sincere to Him in religion, and to establish prayer and give zakat.\"",
             "Quran — Surah Al-Bayyinah, 98:5"),
        ar=L("أي شرط وضعته سورة البينة للعبادة المأمور بها؟",
             ["عبادة الله مخلصين له الدين", "العبادة علنًا", "العبادة كتابةً", "العبادة جماعةً فقط"], 0,
             "«وما أُمروا إلا ليعبدوا الله مخلصين له الدين حنفاء ويقيموا الصلاة ويؤتوا الزكاة».",
             "القرآن — سورة البينة، 98:5"))

    # -- Paradise, the Fire, and the creed --------------------------------
    add("faith_126", "faith", "easy", "quran", Q, "47:15", False,
        fr=L("Que le Coran décrit-il comme coulant dans les jardins promis aux pieux ?",
             ["Des ruisseaux", "Des routes", "Des ponts", "Des puits"], 0,
             "Le Coran décrit à maintes reprises les jardins « sous lesquels coulent les ruisseaux ».",
             "Coran — Sourate Muhammad, 47:15"),
        en=L("What does the Quran describe as flowing in the gardens promised to the God-fearing?",
             ["Rivers", "Roads", "Bridges", "Wells"], 0,
             "The Quran repeatedly describes the gardens \"beneath which rivers flow\".",
             "Quran — Surah Muhammad, 47:15"),
        ar=L("ماذا وصف القرآن جاريًا في جنات المتقين؟",
             ["الأنهار", "الطرق", "الجسور", "الآبار"], 0,
             "وصف القرآن مرارًا الجنات «تجري من تحتها الأنهار».",
             "القرآن — سورة محمد، 47:15"))

    add("faith_127", "faith", "hard", "quran", Q, "32:17", False,
        fr=L("Que dit le Coran de ce qui est caché aux croyants comme récompense ?",
             ["Nulle âme ne sait ce qui lui est réservé comme réjouissance pour les yeux", "Tout est décrit en détail", "Ce sont des richesses", "Ce sont des royaumes"], 0,
             "« Aucune âme ne sait ce qu'on a caché pour eux comme réjouissance pour les yeux, en récompense de ce qu'ils œuvraient. »",
             "Coran — Sourate As-Sajda, 32:17"),
        en=L("What does the Quran say of what is hidden from the believers as reward?",
             ["No soul knows what comfort for the eyes is kept for them", "Everything is described in detail", "It is riches", "It is kingdoms"], 0,
             "\"And no soul knows what has been hidden for them of comfort for eyes as reward for what they used to do.\"",
             "Quran — Surah As-Sajdah, 32:17"),
        ar=L("ماذا قال القرآن عمّا أُخفي للمؤمنين من الجزاء؟",
             ["لا تعلم نفس ما أُخفي لهم من قرة أعين", "وُصف كل شيء تفصيلًا", "هي أموال", "هي ممالك"], 0,
             "«فلا تعلم نفس ما أُخفي لهم من قرة أعين جزاءً بما كانوا يعملون».",
             "القرآن — سورة السجدة، 32:17"))

    add("faith_128", "faith", "medium", "quran", Q, "10:26", False,
        fr=L("Que le Coran promet-il à ceux qui font le bien, en plus de la meilleure récompense ?",
             ["Un surcroît (ziyâda)", "Un délai", "Un royaume", "Un livre"], 0,
             "« À ceux qui agissent en bien est réservée la meilleure récompense, et même davantage. »",
             "Coran — Sourate Yûnus, 10:26"),
        en=L("What does the Quran promise those who do good, beyond the best reward?",
             ["More besides (ziyadah)", "A delay", "A kingdom", "A book"], 0,
             "\"For those who have done good is the best reward and extra.\"",
             "Quran — Surah Yunus, 10:26"),
        ar=L("بماذا وعد القرآن المحسنين زيادةً على الحسنى؟",
             ["الزيادة", "التأجيل", "المُلك", "الكتاب"], 0,
             "«للذين أحسنوا الحسنى وزيادة».",
             "القرآن — سورة يونس، 10:26"))

    add("faith_129", "faith", "hard", "quran", Q, "39:73", False,
        fr=L("Comment le Coran décrit-il l'accueil des pieux à l'entrée du Paradis ?",
             ["« Paix sur vous ! Vous avez été bons : entrez donc pour y demeurer »", "En silence", "Après un long procès", "Un par un sans parole"], 0,
             "« Ses gardiens leur diront : “Salâm ʿalaykum ! Vous avez été bons : entrez donc, pour y demeurer éternellement.” »",
             "Coran — Sourate Az-Zumar, 39:73"),
        en=L("How does the Quran describe the welcome of the God-fearing at the gate of Paradise?",
             ["\"Peace be upon you; you have become pure, so enter to abide eternally\"", "In silence", "After a long trial", "One by one without a word"], 0,
             "\"Its keepers will say: 'Peace be upon you; you have become pure, so enter it to abide eternally.'\"",
             "Quran — Surah Az-Zumar, 39:73"),
        ar=L("كيف وصف القرآن استقبال المتقين عند باب الجنة؟",
             ["«سلام عليكم طبتم فادخلوها خالدين»", "بالصمت", "بعد محاكمة طويلة", "واحدًا واحدًا بلا كلام"], 0,
             "«وقال لهم خزنتها سلام عليكم طبتم فادخلوها خالدين».",
             "القرآن — سورة الزمر، 39:73"))

    add("faith_130", "faith", "easy", "quran", Q, "3:133", False,
        fr=L("Vers quoi le Coran ordonne-t-il de se hâter, dans la sourate Âl ʿImrân ?",
             ["Vers un pardon de son Seigneur et un Paradis large comme les cieux et la terre", "Vers le marché", "Vers le voyage", "Vers la richesse"], 0,
             "« Et concourez au pardon de votre Seigneur et à un Paradis large comme les cieux et la terre, préparé pour les pieux. »",
             "Coran — Sourate Âl ʿImrân, 3:133"),
        en=L("Toward what does the Quran command one hasten, in Surah Al-'Imran?",
             ["Toward forgiveness from the Lord and a Paradise as wide as the heavens and the earth", "Toward the market", "Toward travel", "Toward wealth"], 0,
             "\"And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth, prepared for the righteous.\"",
             "Quran — Surah Al-'Imran, 3:133"),
        ar=L("إلامَ أمر القرآن بالمسارعة في سورة آل عمران؟",
             ["إلى مغفرة من الرب وجنة عرضها السماوات والأرض", "إلى السوق", "إلى السفر", "إلى المال"], 0,
             "«وسارعوا إلى مغفرة من ربكم وجنة عرضها السماوات والأرض أُعدّت للمتقين».",
             "القرآن — سورة آل عمران، 3:133"))

    add("faith_131", "faith", "hard", "quran", Q, "66:6", False,
        fr=L("Quelle responsabilité le Coran confie-t-il au croyant envers sa famille ?",
             ["Les préserver, comme lui-même, d'un Feu", "Les enrichir", "Les instruire des langues", "Les faire voyager"], 0,
             "« Ô les croyants ! Préservez vos personnes et vos familles d'un Feu dont le combustible sera les gens et les pierres. »",
             "Coran — Sourate At-Tahrîm, 66:6"),
        en=L("What responsibility does the Quran place on the believer toward his family?",
             ["To protect them, and himself, from a Fire", "To make them rich", "To teach them languages", "To take them travelling"], 0,
             "\"O you who have believed, protect yourselves and your families from a Fire whose fuel is people and stones.\"",
             "Quran — Surah At-Tahrim, 66:6"),
        ar=L("أي مسؤولية حمّلها القرآن المؤمن تجاه أهله؟",
             ["أن يقيهم ونفسه نارًا", "أن يغنيهم", "أن يعلّمهم اللغات", "أن يسافر بهم"], 0,
             "«يا أيها الذين آمنوا قوا أنفسكم وأهليكم نارًا وقودها الناس والحجارة».",
             "القرآن — سورة التحريم، 66:6"))

    add("faith_132", "faith", "medium", "quran", Q, "2:177", False,
        fr=L("Comment le verset 2:177 définit-il la vraie piété (al-birr) ?",
             ["Croire en Allah, au Jour dernier, aux anges, au Livre et aux prophètes, et donner de son bien", "Se tourner vers l'orient ou l'occident", "Jeûner seulement", "Voyager"], 0,
             "« La bonté pieuse ne consiste pas à tourner vos visages vers le Levant ou le Couchant, mais à croire en Allah, au Jour dernier, aux anges, au Livre et aux prophètes. »",
             "Coran — Sourate Al-Baqara, 2:177"),
        en=L("How does verse 2:177 define true righteousness (al-birr)?",
             ["Belief in Allah, the Last Day, the angels, the Book and the prophets, and giving of one's wealth", "Turning one's face east or west", "Fasting only", "Travelling"], 0,
             "\"Righteousness is not that you turn your faces toward the east or the west, but righteous is one who believes in Allah, the Last Day, the angels, the Book and the prophets.\"",
             "Quran — Surah Al-Baqarah, 2:177"),
        ar=L("كيف عرّفت الآية 2:177 البِرّ؟",
             ["الإيمان بالله واليوم الآخر والملائكة والكتاب والنبيين وإيتاء المال", "توجيه الوجه شرقًا أو غربًا", "الصيام فقط", "السفر"], 0,
             "«ليس البرّ أن تولّوا وجوهكم قِبَل المشرق والمغرب، ولكن البرّ من آمن بالله واليوم الآخر والملائكة والكتاب والنبيين».",
             "القرآن — سورة البقرة، 2:177"))

    add("faith_133", "faith", "hard", "quran", Q, "9:105", False,
        fr=L("Qui verra les œuvres accomplies, selon la sourate At-Tawba ?",
             ["Allah, Son Messager ﷺ et les croyants", "Personne", "Les anges seulement", "Les rois"], 0,
             "« Et dis : œuvrez, car Allah va voir votre œuvre, de même que Son messager et les croyants. »",
             "Coran — Sourate At-Tawba, 9:105"),
        en=L("Who will see the deeds performed, according to Surah At-Tawbah?",
             ["Allah, His Messenger ﷺ and the believers", "No one", "The angels only", "The kings"], 0,
             "\"And say: work, for Allah will see your deeds, and His Messenger and the believers.\"",
             "Quran — Surah At-Tawbah, 9:105"),
        ar=L("من يرى الأعمال بحسب سورة التوبة؟",
             ["الله ورسوله ﷺ والمؤمنون", "لا أحد", "الملائكة فقط", "الملوك"], 0,
             "«وقل اعملوا فسيرى الله عملكم ورسوله والمؤمنون».",
             "القرآن — سورة التوبة، 9:105"))

    add("faith_134", "faith", "easy", "quran", Q, "112:4", False,
        fr=L("Par quelle affirmation se termine la sourate Al-Ikhlâs ?",
             ["« Et nul n'est égal à Lui »", "« Il est le plus grand »", "« Il est proche »", "« Il est le premier »"], 0,
             "« Et nul n'est égal à Lui. »",
             "Coran — Sourate Al-Ikhlâs, 112:4"),
        en=L("With which statement does Surah Al-Ikhlas end?",
             ["\"And there is none comparable to Him\"", "\"He is the greatest\"", "\"He is near\"", "\"He is the first\""], 0,
             "\"And there is none comparable to Him.\"",
             "Quran — Surah Al-Ikhlas, 112:4"),
        ar=L("بأي جملة خُتمت سورة الإخلاص؟",
             ["«ولم يكن له كفوًا أحد»", "«هو الأكبر»", "«هو قريب»", "«هو الأول»"], 0,
             "«ولم يكن له كفوًا أحد».",
             "القرآن — سورة الإخلاص، 112:4"))

    add("faith_135", "faith", "hard", "quran", Q, "57:3", False,
        fr=L("Quels quatre noms la sourate Al-Hadîd rassemble-t-elle dans un même verset ?",
             ["Le Premier, le Dernier, l'Apparent et le Caché", "Le Roi, le Saint, la Paix, le Fidèle", "Le Créateur, le Novateur, le Formateur, le Sage", "Le Vivant, le Subsistant, l'Audient, le Clairvoyant"], 0,
             "« C'est Lui le Premier et le Dernier, l'Apparent et le Caché, et Il est Omniscient. »",
             "Coran — Sourate Al-Hadîd, 57:3"),
        en=L("Which four names does Surah Al-Hadid gather in a single verse?",
             ["The First, the Last, the Manifest and the Hidden", "The King, the Holy, the Peace, the Faithful", "The Creator, the Originator, the Fashioner, the Wise", "The Living, the Sustainer, the Hearing, the Seeing"], 0,
             "\"He is the First and the Last, the Manifest and the Hidden, and He is Knowing of all things.\"",
             "Quran — Surah Al-Hadid, 57:3"),
        ar=L("أي أربعة أسماء جمعتها سورة الحديد في آية واحدة؟",
             ["الأول والآخر والظاهر والباطن", "الملك القدوس السلام المؤمن", "الخالق البارئ المصوّر الحكيم", "الحي القيوم السميع البصير"], 0,
             "«هو الأول والآخر والظاهر والباطن وهو بكل شيء عليم».",
             "القرآن — سورة الحديد، 57:3"))

    add("faith_136", "faith", "medium", "quran", Q, "59:23", False,
        fr=L("Quels noms la fin de la sourate Al-Hashr énumère-t-elle après « le Roi » ?",
             ["Le Saint, la Paix, le Rassurant, le Prédominant", "Le Créateur, le Formateur", "Le Pardonneur, le Miséricordieux", "L'Audient, le Clairvoyant"], 0,
             "« C'est Lui, Allah : le Souverain, le Pur, la Paix, le Rassurant, le Prédominant, le Tout Puissant, le Contraignant, l'Orgueilleux. »",
             "Coran — Sourate Al-Hashr, 59:23"),
        en=L("Which names does the end of Surah Al-Hashr list after \"the Sovereign\"?",
             ["The Pure, the Peace, the Bestower of Faith, the Overseer", "The Creator, the Fashioner", "The Forgiving, the Merciful", "The Hearing, the Seeing"], 0,
             "\"He is Allah, the Sovereign, the Pure, the Peace, the Bestower of Faith, the Overseer, the Exalted in Might.\"",
             "Quran — Surah Al-Hashr, 59:23"),
        ar=L("أي أسماء عدّدتها خاتمة سورة الحشر بعد «الملك»؟",
             ["القدوس السلام المؤمن المهيمن", "الخالق البارئ", "الغفور الرحيم", "السميع البصير"], 0,
             "«هو الله الذي لا إله إلا هو الملك القدوس السلام المؤمن المهيمن العزيز الجبار المتكبر».",
             "القرآن — سورة الحشر، 59:23"))

    add("faith_137", "faith", "easy", "creed", C, WT, False,
        fr=L("Comment appelle-t-on la formule « Il n'y a de divinité qu'Allah, Muhammad est Son Messager » ?",
             ["La shahâda (l'attestation de foi)", "La basmala", "La takbîra", "La tasmiya"], 0,
             "La shahâda est la première parole de l'islam et le premier de ses piliers.",
             "Terminologie établie"),
        en=L("What is the formula \"There is no deity but Allah, Muhammad is His Messenger\" called?",
             ["The shahadah (the testimony of faith)", "The basmalah", "The takbirah", "The tasmiyah"], 0,
             "The shahadah is the first word of Islam and the first of its pillars.",
             "Established terminology"),
        ar=L("بماذا تُسمّى عبارة «لا إله إلا الله محمد رسول الله»؟",
             ["الشهادة", "البسملة", "التكبيرة", "التسمية"], 0,
             "الشهادة أول كلمة الإسلام وأول أركانه.",
             "مصطلح ثابت"))

    add("faith_138", "faith", "medium", "creed", C, WT, False,
        fr=L("Comment appelle-t-on la formule « Allâhu akbar » ?",
             ["Le takbîr", "Le tahlîl", "Le tasbîh", "Le tahmîd"], 0,
             "Le takbîr est « Allâhu akbar », le tasbîh « subhân Allâh », le tahmîd « al-hamdu lillâh », le tahlîl « lâ ilâha illâ-llâh ».",
             "Terminologie établie"),
        en=L("What is the formula \"Allahu akbar\" called?",
             ["The takbir", "The tahlil", "The tasbih", "The tahmid"], 0,
             "Takbir is \"Allahu akbar\", tasbih is \"subhan Allah\", tahmid is \"al-hamdu lillah\", and tahlil is \"la ilaha illa-llah\".",
             "Established terminology"),
        ar=L("بماذا تُسمّى عبارة «الله أكبر»؟",
             ["التكبير", "التهليل", "التسبيح", "التحميد"], 0,
             "التكبير «الله أكبر»، والتسبيح «سبحان الله»، والتحميد «الحمد لله»، والتهليل «لا إله إلا الله».",
             "مصطلح ثابت"))

    add("faith_139", "faith", "hard", "creed", C, WT, False,
        fr=L("Comment appelle-t-on la formule « au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux » ?",
             ["La basmala", "La hamdala", "La hawqala", "L'istirjâʿ"], 0,
             "La basmala ouvre toutes les sourates sauf une ; la hawqala est « lâ hawla wa lâ quwwata illâ billâh ».",
             "Terminologie établie"),
        en=L("What is the formula \"In the name of Allah, the Most Merciful, the Especially Merciful\" called?",
             ["The basmalah", "The hamdalah", "The hawqalah", "The istirja'"], 0,
             "The basmalah opens every surah but one; the hawqalah is \"la hawla wa la quwwata illa billah\".",
             "Established terminology"),
        ar=L("بماذا تُسمّى عبارة «بسم الله الرحمن الرحيم»؟",
             ["البسملة", "الحمدلة", "الحوقلة", "الاسترجاع"], 0,
             "البسملة تفتتح كل السور إلا واحدة، والحوقلة «لا حول ولا قوة إلا بالله».",
             "مصطلح ثابت"))

    add("faith_140", "faith", "medium", "quran", Q, "2:156", False,
        fr=L("Quelle parole le Coran enseigne-t-il à dire lorsqu'un malheur frappe ?",
             ["« Nous sommes à Allah, et c'est à Lui que nous retournerons »", "« Pourquoi moi ? »", "« Cela passera »", "« C'est le destin des hommes »"], 0,
             "« Ceux qui, atteints d'un malheur, disent : “Certes nous sommes à Allah, et c'est à Lui que nous retournerons.” »",
             "Coran — Sourate Al-Baqara, 2:156"),
        en=L("Which words does the Quran teach be said when calamity strikes?",
             ["\"Indeed we belong to Allah, and to Him we will return\"", "\"Why me?\"", "\"It will pass\"", "\"It is the lot of men\""], 0,
             "\"Who, when disaster strikes them, say: 'Indeed we belong to Allah, and indeed to Him we will return.'\"",
             "Quran — Surah Al-Baqarah, 2:156"),
        ar=L("أي كلمة علّمها القرآن عند المصيبة؟",
             ["«إنا لله وإنا إليه راجعون»", "«لم أنا؟»", "«ستمضي»", "«هذا حال الناس»"], 0,
             "«الذين إذا أصابتهم مصيبة قالوا إنا لله وإنا إليه راجعون».",
             "القرآن — سورة البقرة، 2:156"))

    add("faith_141", "faith", "easy", "quran", Q, "18:23-24", False,
        fr=L("Que le Coran ordonne-t-il de dire en annonçant une action pour demain ?",
             ["« Si Allah le veut » (in shâ' Allâh)", "« C'est promis »", "« Sans faute »", "« Je le jure »"], 0,
             "« Et ne dis jamais “je ferai cela demain” sans ajouter : “si Allah le veut”. »",
             "Coran — Sourate Al-Kahf, 18:23-24"),
        en=L("What does the Quran command be said when announcing an action for tomorrow?",
             ["\"If Allah wills\" (in sha' Allah)", "\"It is promised\"", "\"Without fail\"", "\"I swear it\""], 0,
             "\"And never say of anything: 'Indeed, I will do that tomorrow', except when adding: 'If Allah wills'.\"",
             "Quran — Surah Al-Kahf, 18:23-24"),
        ar=L("بماذا أمر القرآن عند الإخبار عن فعل غدًا؟",
             ["«إن شاء الله»", "«وعد»", "«لا محالة»", "«أُقسم»"], 0,
             "«ولا تقولنّ لشيء إني فاعل ذلك غدًا، إلا أن يشاء الله».",
             "القرآن — سورة الكهف، 18:23-24"))

    add("faith_142", "faith", "hard", "quran", Q, "31:34", False,
        fr=L("Quelle connaissance le Coran réserve-t-il à Allah seul, à la fin de la sourate Luqmân ?",
             ["L'Heure, la pluie, ce qui est dans les matrices, ce que l'on gagnera demain et où l'on mourra", "Le nombre des étoiles", "Le nom des rois", "Le compte des jours"], 0,
             "« La connaissance de l'Heure est auprès d'Allah ; c'est Lui qui fait tomber la pluie et qui sait ce qu'il y a dans les matrices. Nul ne sait ce qu'il acquerra demain, ni en quelle terre il mourra. »",
             "Coran — Sourate Luqmân, 31:34"),
        en=L("Which knowledge does the Quran reserve to Allah alone, at the end of Surah Luqman?",
             ["The Hour, the rain, what is in the wombs, what one will earn tomorrow, and where one will die", "The number of the stars", "The names of kings", "The count of days"], 0,
             "\"Indeed, Allah has knowledge of the Hour and sends down the rain and knows what is in the wombs. And no soul knows what it will earn tomorrow, and no soul knows in what land it will die.\"",
             "Quran — Surah Luqman, 31:34"),
        ar=L("أي علم استأثر به الله في خاتمة سورة لقمان؟",
             ["الساعة والغيث وما في الأرحام وكسب الغد وأرض الموت", "عدد النجوم", "أسماء الملوك", "عدّ الأيام"], 0,
             "«إن الله عنده علم الساعة وينزّل الغيث ويعلم ما في الأرحام، وما تدري نفس ماذا تكسب غدًا وما تدري نفس بأي أرض تموت».",
             "القرآن — سورة لقمان، 31:34"))

    add("faith_143", "faith", "medium", "quran", Q, "7:34", False,
        fr=L("Que dit le Coran du terme fixé pour chaque communauté ?",
             ["Quand il vient, on ne le retarde ni ne l'avance d'une heure", "Il est modifiable", "Il est inconnu d'Allah", "Il dépend des rois"], 0,
             "« Pour chaque communauté il y a un terme : quand leur terme vient, ils ne peuvent le retarder d'une heure, ni l'avancer. »",
             "Coran — Sourate Al-Aʿrâf, 7:34"),
        en=L("What does the Quran say about the term fixed for every community?",
             ["When it comes, it is neither delayed nor advanced by an hour", "It can be changed", "It is unknown to Allah", "It depends on kings"], 0,
             "\"And for every nation is a term. So when their term has come, they will not remain behind an hour, nor will they precede it.\"",
             "Quran — Surah Al-A'raf, 7:34"),
        ar=L("ماذا قال القرآن عن أجل كل أمة؟",
             ["إذا جاء لا يُستأخر ساعة ولا يُستقدم", "قابل للتغيير", "لا يعلمه الله", "يتوقف على الملوك"], 0,
             "«ولكل أمة أجل، فإذا جاء أجلهم لا يستأخرون ساعة ولا يستقدمون».",
             "القرآن — سورة الأعراف، 7:34"))

    add("faith_144", "faith", "hard", "quran", Q, "16:97", False,
        fr=L("Quelle promesse le Coran fait-il à quiconque fait le bien, homme ou femme, en étant croyant ?",
             ["Une vie bonne, et une récompense selon le meilleur de ses œuvres", "La richesse", "Le pouvoir", "La célébrité"], 0,
             "« Quiconque, mâle ou femelle, fait une bonne œuvre tout en étant croyant, Nous lui ferons vivre une bonne vie. »",
             "Coran — Sourate An-Nahl, 16:97"),
        en=L("What does the Quran promise whoever does good, male or female, while believing?",
             ["A good life, and a reward by the best of their deeds", "Wealth", "Power", "Fame"], 0,
             "\"Whoever does righteousness, whether male or female, while being a believer — We will surely cause him to live a good life.\"",
             "Quran — Surah An-Nahl, 16:97"),
        ar=L("بماذا وعد القرآن من عمل صالحًا من ذكر أو أنثى وهو مؤمن؟",
             ["حياة طيبة وأجرًا بأحسن ما عملوا", "المال", "السلطان", "الشهرة"], 0,
             "«من عمل صالحًا من ذكر أو أنثى وهو مؤمن فلنحيينّه حياة طيبة».",
             "القرآن — سورة النحل، 16:97"))

    add("faith_145", "faith", "easy", "quran", Q, "49:14", False,
        fr=L("Quelle distinction le Coran établit-il entre « islam » et « foi » dans la sourate Al-Hujurât ?",
             ["Dire « nous nous sommes soumis » n'est pas encore que la foi entre dans les cœurs", "Ce sont deux mots identiques", "La foi précède toujours", "L'islam est réservé aux savants"], 0,
             "« Les Bédouins ont dit : “Nous avons la foi.” Dis : “Vous n'avez pas encore la foi. Dites plutôt : nous nous sommes soumis, car la foi n'a pas encore pénétré dans vos cœurs.” »",
             "Coran — Sourate Al-Hujurât, 49:14"),
        en=L("What distinction does the Quran draw between \"islam\" and \"faith\" in Surah Al-Hujurat?",
             ["Saying \"we have submitted\" is not yet faith entering the hearts", "They are the same word", "Faith always comes first", "Islam is only for scholars"], 0,
             "\"The bedouins say: 'We have believed.' Say: 'You have not believed; but say we have submitted, for faith has not yet entered your hearts.'\"",
             "Quran — Surah Al-Hujurat, 49:14"),
        ar=L("أي فرق قرّره القرآن بين «الإسلام» و«الإيمان» في سورة الحجرات؟",
             ["قول «أسلمنا» ليس بعدُ دخولَ الإيمان في القلوب", "هما لفظان مترادفان", "الإيمان أسبق دائمًا", "الإسلام للعلماء"], 0,
             "«قالت الأعراب آمنا، قل لم تؤمنوا ولكن قولوا أسلمنا ولمّا يدخل الإيمان في قلوبكم».",
             "القرآن — سورة الحجرات، 49:14"))

    add("faith_146", "faith", "hard", "quran", Q, "5:32", False,
        fr=L("Quelle règle la sourate Al-Mâ'ida énonce-t-elle sur la vie d'une seule personne ?",
             ["Qui tue une personne, c'est comme s'il tuait tous les hommes ; qui en sauve une, comme s'il les sauvait tous", "Chaque vie compte pour une", "Seuls les proches comptent", "Seul le nombre compte"], 0,
             "« Quiconque tuerait une personne non coupable d'un meurtre ou d'une corruption sur la terre, c'est comme s'il avait tué tous les hommes ; et quiconque lui fait don de la vie, c'est comme s'il faisait don de la vie à tous les hommes. »",
             "Coran — Sourate Al-Mâ'ida, 5:32"),
        en=L("Which rule does Surah Al-Ma'idah state about a single life?",
             ["Whoever kills one person, it is as if he killed all mankind; whoever saves one, as if he saved all", "Each life counts as one", "Only relatives count", "Only numbers count"], 0,
             "\"Whoever kills a soul, unless for a soul or for corruption in the land, it is as if he had slain mankind entirely; and whoever saves one, it is as if he had saved mankind entirely.\"",
             "Quran — Surah Al-Ma'idah, 5:32"),
        ar=L("أي قاعدة قرّرتها سورة المائدة في شأن النفس الواحدة؟",
             ["من قتل نفسًا فكأنما قتل الناس جميعًا، ومن أحياها فكأنما أحيا الناس جميعًا", "كل نفس بواحدة", "الأقارب فقط", "العدد وحده"], 0,
             "«من قتل نفسًا بغير نفس أو فساد في الأرض فكأنما قتل الناس جميعًا، ومن أحياها فكأنما أحيا الناس جميعًا».",
             "القرآن — سورة المائدة، 5:32"))

    add("faith_147", "faith", "easy", "quran", Q, "6:160", False,
        fr=L("Comment le Coran multiplie-t-il la récompense de la bonne action ?",
             ["Par dix", "Par deux", "Par cent", "Elle n'est pas multipliée"], 0,
             "« Quiconque viendra avec le bien aura dix fois autant ; et quiconque viendra avec le mal ne sera rétribué que par son équivalent. »",
             "Coran — Sourate Al-Anʿâm, 6:160"),
        en=L("By how much does the Quran multiply the reward of a good deed?",
             ["Tenfold", "Twofold", "A hundredfold", "It is not multiplied"], 0,
             "\"Whoever comes with a good deed will have ten times the like thereof; and whoever comes with an evil deed will not be recompensed except the like thereof.\"",
             "Quran — Surah Al-An'am, 6:160"),
        ar=L("بكم يضاعف القرآنُ جزاء الحسنة؟",
             ["بعشر أمثالها", "بمثلين", "بمائة", "لا تضاعف"], 0,
             "«من جاء بالحسنة فله عشر أمثالها، ومن جاء بالسيئة فلا يُجزى إلا مثلها».",
             "القرآن — سورة الأنعام، 6:160"))

    add("faith_148", "faith", "hard", "quran", Q, "35:15", False,
        fr=L("Comment la sourate Fâtir décrit-elle le rapport des hommes à Allah ?",
             ["Ce sont eux les pauvres, et Allah est le Riche, le Digne de louange", "Ils sont Ses associés", "Ils sont indépendants", "Ils sont Ses créanciers"], 0,
             "« Ô hommes ! Vous êtes les pauvres ayant besoin d'Allah, et c'est Allah le Riche, le Digne de louange. »",
             "Coran — Sourate Fâtir, 35:15"),
        en=L("How does Surah Fatir describe people's relation to Allah?",
             ["They are the poor in need of Him, and Allah is the Free of need, the Praiseworthy", "They are His partners", "They are independent", "They are His creditors"], 0,
             "\"O mankind, you are those in need of Allah, while Allah is the Free of need, the Praiseworthy.\"",
             "Quran — Surah Fatir, 35:15"),
        ar=L("كيف وصفت سورة فاطر حاجة الناس إلى الله؟",
             ["هم الفقراء إلى الله، والله الغني الحميد", "هم شركاؤه", "هم مستغنون", "هم دائنون له"], 0,
             "«يا أيها الناس أنتم الفقراء إلى الله، والله هو الغني الحميد».",
             "القرآن — سورة فاطر، 35:15"))

    add("faith_149", "faith", "easy", "quran", Q, "103:1-3", False,
        fr=L("Quelles quatre qualités sauvent de la perte, selon la sourate Al-ʿAsr ?",
             ["La foi, les bonnes œuvres, l'exhortation à la vérité et à l'endurance", "La richesse, la force, la beauté, la ruse", "Le silence, le sommeil, la retraite, le jeûne", "Le voyage, le commerce, l'écriture, la lecture"], 0,
             "« Par le Temps ! L'homme est certes en perdition, sauf ceux qui croient, accomplissent les bonnes œuvres, s'enjoignent mutuellement la vérité et s'enjoignent mutuellement l'endurance. »",
             "Coran — Sourate Al-ʿAsr, 103:1-3"),
        en=L("Which four qualities save from loss, according to Surah Al-'Asr?",
             ["Faith, righteous deeds, enjoining truth and enjoining patience", "Wealth, strength, beauty, cunning", "Silence, sleep, seclusion, fasting", "Travel, trade, writing, reading"], 0,
             "\"By time, man is in loss, except those who believe and do righteous deeds and advise each other to truth and advise each other to patience.\"",
             "Quran — Surah Al-'Asr, 103:1-3"),
        ar=L("أي أربع خصال تنجّي من الخسر بحسب سورة العصر؟",
             ["الإيمان والعمل الصالح والتواصي بالحق والتواصي بالصبر", "المال والقوة والجمال والحيلة", "الصمت والنوم والعزلة والصوم", "السفر والتجارة والكتابة والقراءة"], 0,
             "«والعصر، إن الإنسان لفي خسر، إلا الذين آمنوا وعملوا الصالحات وتواصوا بالحق وتواصوا بالصبر».",
             "القرآن — سورة العصر، 103:1-3"))

    add("faith_150", "faith", "hard", "quran", Q, "2:285", False,
        fr=L("En quoi les croyants déclarent-ils croire, dans l'avant-dernier verset de la sourate Al-Baqara ?",
             ["En Allah, Ses anges, Ses livres et Ses messagers", "En un seul livre", "En un seul ange", "En leurs ancêtres"], 0,
             "« Le Messager a cru en ce qu'on a fait descendre vers lui, et les croyants aussi : tous ont cru en Allah, en Ses anges, à Ses livres et en Ses messagers. »",
             "Coran — Sourate Al-Baqara, 2:285"),
        en=L("What do the believers declare belief in, in the penultimate verse of Surah Al-Baqarah?",
             ["In Allah, His angels, His books and His messengers", "In one book", "In one angel", "In their forefathers"], 0,
             "\"The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers.\"",
             "Quran — Surah Al-Baqarah, 2:285"),
        ar=L("بماذا أعلن المؤمنون الإيمان في الآية قبل الأخيرة من سورة البقرة؟",
             ["بالله وملائكته وكتبه ورسله", "بكتاب واحد", "بملك واحد", "بآبائهم"], 0,
             "«آمن الرسول بما أُنزل إليه من ربه والمؤمنون، كل آمن بالله وملائكته وكتبه ورسله».",
             "القرآن — سورة البقرة، 2:285"))
