"""Sīra — part A (sira_031 … sira_090).

Established, non-disputed facts of the Prophet's ﷺ life and companions:
Qur'anic references where the Qur'an states the fact, Ṣaḥīḥ al-Bukhārī /
Muslim where a hadith does, and the `well-established` class of
CONTENT_SOURCE_POLICY §2bis for mass-transmitted names, places and
sequences.
"""

WE = "well-established sira event, agreed across standard biographies"
WT = "well-established terminology"


def register(add, L):
    Q = "Quran"
    S = "Sira"
    B = "Sahih al-Bukhari"
    M = "Sahih Muslim"

    add("sira_031", "sira", "easy", "quran", Q, "106:1", False,
        fr=L("À quelle tribu appartenait le Prophète Muhammad ﷺ ?",
             ["Quraysh", "Les Aws", "Les Khazraj", "Thaqîf"], 0,
             "Une sourate entière porte le nom de sa tribu : Quraysh.",
             "Coran — Sourate Quraysh, 106:1"),
        en=L("To which tribe did the Prophet Muhammad ﷺ belong?",
             ["Quraysh", "The Aws", "The Khazraj", "Thaqif"], 0,
             "A whole surah bears the name of his tribe: Quraysh.",
             "Quran — Surah Quraysh, 106:1"),
        ar=L("إلى أي قبيلة ينتمي النبي محمد ﷺ؟",
             ["قريش", "الأوس", "الخزرج", "ثقيف"], 0,
             "سورة كاملة تحمل اسم قبيلته: قريش.",
             "القرآن — سورة قريش، 106:1"))

    add("sira_032", "sira", "medium", "sira", S, WE, False,
        fr=L("De quel clan de Quraysh le Prophète ﷺ était-il issu ?",
             ["Banû Hâshim", "Banû Umayya", "Banû Makhzûm", "Banû Tamîm"], 0,
             "Le Prophète ﷺ appartenait aux Banû Hâshim, le clan de son arrière-grand-père Hâshim.",
             "Sîra — fait établi"),
        en=L("From which clan of Quraysh did the Prophet ﷺ come?",
             ["Banu Hashim", "Banu Umayya", "Banu Makhzum", "Banu Tamim"], 0,
             "The Prophet ﷺ belonged to Banu Hashim, the clan of his great-grandfather Hashim.",
             "Sira — established fact"),
        ar=L("من أي بطن من قريش كان النبي ﷺ؟",
             ["بني هاشم", "بني أمية", "بني مخزوم", "بني تميم"], 0,
             "كان النبي ﷺ من بني هاشم، بطن جدّه الأعلى هاشم.",
             "السيرة — حقيقة ثابتة"))

    add("sira_033", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment s'appelait la nourrice qui allaita le Prophète ﷺ dans le désert ?",
             ["Halîma as-Sa'diyya", "Âmina", "Khadîja", "Fâtima"], 0,
             "Selon la coutume mecquoise, l'enfant fut confié à une nourrice bédouine : Halîma as-Sa'diyya.",
             "Sîra — fait établi"),
        en=L("What was the name of the wet nurse who nursed the Prophet ﷺ in the desert?",
             ["Halima as-Sa'diyya", "Amina", "Khadija", "Fatima"], 0,
             "Following Makkan custom, the infant was entrusted to a Bedouin wet nurse: Halima as-Sa'diyya.",
             "Sira — established fact"),
        ar=L("ما اسم المرضعة التي أرضعت النبي ﷺ في البادية؟",
             ["حليمة السعدية", "آمنة", "خديجة", "فاطمة"], 0,
             "على عادة أهل مكة، دُفع الرضيع إلى مرضعة من البادية: حليمة السعدية.",
             "السيرة — حقيقة ثابتة"))

    add("sira_034", "sira", "medium", "sira", S, WE, False,
        fr=L("Quel oncle du Prophète ﷺ, héros de Badr, tomba en martyr à Uhud ?",
             ["Hamza", "Abû Tâlib", "Al-'Abbâs", "Abû Lahab"], 0,
             "Hamza ibn 'Abd al-Muttalib combattit à Badr et fut tué à la bataille d'Uhud.",
             "Sîra — fait établi"),
        en=L("Which uncle of the Prophet ﷺ, a hero of Badr, fell as a martyr at Uhud?",
             ["Hamza", "Abu Talib", "Al-'Abbas", "Abu Lahab"], 0,
             "Hamza ibn 'Abd al-Muttalib fought at Badr and was killed at the battle of Uhud.",
             "Sira — established fact"),
        ar=L("أي عمٍّ للنبي ﷺ، من أبطال بدر، استُشهد في أُحد؟",
             ["حمزة", "أبو طالب", "العباس", "أبو لهب"], 0,
             "قاتل حمزة بن عبد المطلب في بدر واستُشهد في غزوة أُحد.",
             "السيرة — حقيقة ثابتة"))

    add("sira_035", "sira", "easy", "sira", S, WE, False,
        fr=L("Quel cousin du Prophète ﷺ, élevé dans sa maison, devint le quatrième calife ?",
             ["'Alî ibn Abî Tâlib", "Ja'far", "'Aqîl", "Al-'Abbâs"], 0,
             "'Alî, fils d'Abû Tâlib, grandit auprès du Prophète ﷺ et fut le quatrième calife bien guidé.",
             "Sîra — fait établi"),
        en=L("Which cousin of the Prophet ﷺ, raised in his home, became the fourth caliph?",
             ["'Ali ibn Abi Talib", "Ja'far", "'Aqil", "Al-'Abbas"], 0,
             "'Ali, son of Abu Talib, grew up with the Prophet ﷺ and was the fourth rightly guided caliph.",
             "Sira — established fact"),
        ar=L("أي ابن عمّ للنبي ﷺ نشأ في بيته وصار الخليفة الرابع؟",
             ["علي بن أبي طالب", "جعفر", "عقيل", "العباس"], 0,
             "نشأ علي بن أبي طالب في كنف النبي ﷺ وكان رابع الخلفاء الراشدين.",
             "السيرة — حقيقة ثابتة"))

    add("sira_036", "sira", "easy", "sira", S, WE, False,
        fr=L("Qui fut le premier calife après la mort du Prophète ﷺ ?",
             ["Abû Bakr", "'Umar", "'Uthmân", "'Alî"], 0,
             "Abû Bakr as-Siddîq fut choisi comme premier calife.",
             "Sîra — fait établi"),
        en=L("Who was the first caliph after the Prophet's ﷺ death?",
             ["Abu Bakr", "'Umar", "'Uthman", "'Ali"], 0,
             "Abu Bakr as-Siddiq was chosen as the first caliph.",
             "Sira — established fact"),
        ar=L("من كان الخليفة الأول بعد وفاة النبي ﷺ؟",
             ["أبو بكر", "عمر", "عثمان", "علي"], 0,
             "اختير أبو بكر الصدّيق خليفة أول.",
             "السيرة — حقيقة ثابتة"))

    add("sira_037", "sira", "easy", "sira", S, WT, False,
        fr=L("Quel surnom porte Abû Bakr, pour avoir cru le Prophète ﷺ sans hésiter ?",
             ["As-Siddîq (le Véridique)", "Al-Fârûq", "Dhun-Nûrayn", "Sayf Allah"], 0,
             "Abû Bakr est appelé as-Siddîq, celui qui confirme et croit la vérité.",
             "Sîra — terminologie établie"),
        en=L("What title does Abu Bakr carry, for believing the Prophet ﷺ without hesitation?",
             ["As-Siddiq (the Truthful)", "Al-Faruq", "Dhun-Nurayn", "Sayf Allah"], 0,
             "Abu Bakr is called as-Siddiq, the one who affirms and believes the truth.",
             "Sira — established terminology"),
        ar=L("ما لقب أبي بكر لتصديقه النبي ﷺ دون تردد؟",
             ["الصدّيق", "الفاروق", "ذو النورين", "سيف الله"], 0,
             "يُلقّب أبو بكر بالصدّيق، الذي يصدّق الحق ويؤمن به.",
             "السيرة — مصطلح ثابت"))

    add("sira_038", "sira", "medium", "sira", S, WT, False,
        fr=L("Quel surnom porte 'Umar ibn al-Khattâb ?",
             ["Al-Fârûq (celui qui distingue le vrai du faux)", "As-Siddîq", "Dhun-Nûrayn", "Al-Amîn"], 0,
             "'Umar est appelé al-Fârûq, celui qui sépare la vérité du mensonge.",
             "Sîra — terminologie établie"),
        en=L("What title does 'Umar ibn al-Khattab carry?",
             ["Al-Faruq (who distinguishes truth from falsehood)", "As-Siddiq", "Dhun-Nurayn", "Al-Amin"], 0,
             "'Umar is called al-Faruq, the one who separates truth from falsehood.",
             "Sira — established terminology"),
        ar=L("ما لقب عمر بن الخطاب؟",
             ["الفاروق", "الصدّيق", "ذو النورين", "الأمين"], 0,
             "يُلقّب عمر بالفاروق، الذي يفرّق بين الحق والباطل.",
             "السيرة — مصطلح ثابت"))

    add("sira_039", "sira", "hard", "sira", S, WE, False,
        fr=L("Pourquoi 'Uthmân ibn 'Affân est-il surnommé « Dhun-Nûrayn », l'homme aux deux lumières ?",
             ["Il épousa successivement deux filles du Prophète ﷺ", "Il portait deux lampes", "Il mémorisa le Coran deux fois", "Il fit deux hijras"], 0,
             "'Uthmân épousa Ruqayya, puis, après sa mort, Umm Kulthûm, toutes deux filles du Prophète ﷺ.",
             "Sîra — fait établi"),
        en=L("Why is 'Uthman ibn 'Affan called \"Dhun-Nurayn\", the possessor of two lights?",
             ["He married two daughters of the Prophet ﷺ, one after the other", "He carried two lamps", "He memorised the Quran twice", "He made two hijras"], 0,
             "'Uthman married Ruqayya and, after her death, Umm Kulthum, both daughters of the Prophet ﷺ.",
             "Sira — established fact"),
        ar=L("لماذا لُقّب عثمان بن عفان بـ«ذي النورين»؟",
             ["لأنه تزوج ابنتين للنبي ﷺ واحدة بعد الأخرى", "لأنه حمل مصباحين", "لأنه حفظ القرآن مرتين", "لأنه هاجر مرتين"], 0,
             "تزوج عثمان رقيّة، ثم بعد وفاتها أم كلثوم، وكلتاهما بنتا النبي ﷺ.",
             "السيرة — حقيقة ثابتة"))

    add("sira_040", "sira", "medium", "sira", S, WE, False,
        fr=L("Dans quel ordre les quatre califes bien guidés se sont-ils succédé ?",
             ["Abû Bakr, 'Umar, 'Uthmân, 'Alî", "'Alî, 'Umar, Abû Bakr, 'Uthmân", "'Umar, Abû Bakr, 'Alî, 'Uthmân", "Abû Bakr, 'Alî, 'Umar, 'Uthmân"], 0,
             "Abû Bakr, puis 'Umar, puis 'Uthmân, puis 'Alî.",
             "Sîra — fait établi"),
        en=L("In which order did the four rightly guided caliphs succeed one another?",
             ["Abu Bakr, 'Umar, 'Uthman, 'Ali", "'Ali, 'Umar, Abu Bakr, 'Uthman", "'Umar, Abu Bakr, 'Ali, 'Uthman", "Abu Bakr, 'Ali, 'Umar, 'Uthman"], 0,
             "Abu Bakr, then 'Umar, then 'Uthman, then 'Ali.",
             "Sira — established fact"),
        ar=L("ما ترتيب الخلفاء الراشدين الأربعة؟",
             ["أبو بكر، عمر، عثمان، علي", "علي، عمر، أبو بكر، عثمان", "عمر، أبو بكر، علي، عثمان", "أبو بكر، علي، عمر، عثمان"], 0,
             "أبو بكر ثم عمر ثم عثمان ثم علي.",
             "السيرة — حقيقة ثابتة"))

    add("sira_041", "sira", "easy", "sira", S, WE, False,
        fr=L("Qui fut la première personne à croire au message du Prophète ﷺ ?",
             ["Khadîja, son épouse", "Abû Bakr", "'Alî", "Bilâl"], 0,
             "Khadîja crut en lui dès la première révélation et le soutint.",
             "Sîra — fait établi"),
        en=L("Who was the first person to believe in the Prophet's ﷺ message?",
             ["Khadija, his wife", "Abu Bakr", "'Ali", "Bilal"], 0,
             "Khadija believed in him from the first revelation and supported him.",
             "Sira — established fact"),
        ar=L("من أول من آمن برسالة النبي ﷺ؟",
             ["خديجة زوجته", "أبو بكر", "علي", "بلال"], 0,
             "آمنت خديجة به منذ أول الوحي وآزرته.",
             "السيرة — حقيقة ثابتة"))

    add("sira_042", "sira", "medium", "sira", S, WE, False,
        fr=L("Qui racheta Bilâl pour le libérer des tortures de son maître ?",
             ["Abû Bakr", "'Umar", "Hamza", "'Uthmân"], 0,
             "Abû Bakr acheta Bilâl et l'affranchit.",
             "Sîra — fait établi"),
        en=L("Who bought Bilal to free him from his master's torture?",
             ["Abu Bakr", "'Umar", "Hamza", "'Uthman"], 0,
             "Abu Bakr bought Bilal and set him free.",
             "Sira — established fact"),
        ar=L("من اشترى بلالًا ليخلّصه من تعذيب سيده؟",
             ["أبو بكر", "عمر", "حمزة", "عثمان"], 0,
             "اشترى أبو بكر بلالًا وأعتقه.",
             "السيرة — حقيقة ثابتة"))

    add("sira_043", "sira", "hard", "sira", S, WE, False,
        fr=L("Qui fut la première martyre de l'islam, tuée à La Mecque pour sa foi ?",
             ["Sumayya, mère de 'Ammâr", "Asmâ", "Umm Salama", "Safiyya"], 0,
             "Sumayya bint Khayyât, mère de 'Ammâr ibn Yâsir, fut tuée par Abû Jahl.",
             "Sîra — fait établi"),
        en=L("Who was the first martyr of Islam, killed in Makkah for her faith?",
             ["Sumayya, mother of 'Ammar", "Asma", "Umm Salama", "Safiyya"], 0,
             "Sumayya bint Khayyat, mother of 'Ammar ibn Yasir, was killed by Abu Jahl.",
             "Sira — established fact"),
        ar=L("من أول شهيدة في الإسلام قُتلت في مكة بسبب إيمانها؟",
             ["سميّة أم عمّار", "أسماء", "أم سلمة", "صفية"], 0,
             "قُتلت سميّة بنت خيّاط، أم عمّار بن ياسر، على يد أبي جهل.",
             "السيرة — حقيقة ثابتة"))

    add("sira_044", "sira", "medium", "sira", S, WE, False,
        fr=L("Vers quel pays eut lieu la première émigration de musulmans persécutés à La Mecque ?",
             ["L'Abyssinie (Éthiopie)", "La Perse", "Le Yémen", "L'Égypte"], 0,
             "Les premiers émigrants partirent en Abyssinie, chez un roi juste.",
             "Sîra — fait établi"),
        en=L("To which land did the first emigration of Muslims persecuted in Makkah take place?",
             ["Abyssinia (Ethiopia)", "Persia", "Yemen", "Egypt"], 0,
             "The first emigrants went to Abyssinia, to a just king.",
             "Sira — established fact"),
        ar=L("إلى أي بلد كانت الهجرة الأولى للمسلمين المضطهدين في مكة؟",
             ["الحبشة", "فارس", "اليمن", "مصر"], 0,
             "هاجر المسلمون الأوائل إلى الحبشة عند ملك عادل.",
             "السيرة — حقيقة ثابتة"))

    add("sira_045", "sira", "medium", "hadithBukhari", B, "1245", False,
        fr=L("Comment s'appelait le roi d'Abyssinie qui protégea les musulmans, et pour qui le Prophète ﷺ fit la prière funéraire à distance ?",
             ["An-Najâshî (le Négus)", "Héraclius", "Chosroès", "Al-Muqawqis"], 0,
             "Le Prophète ﷺ annonça la mort du Négus le jour même et pria sur lui avec les compagnons.",
             "Sahîh al-Bukhârî, 1245"),
        en=L("What was the king of Abyssinia called, who protected the Muslims and for whom the Prophet ﷺ prayed the funeral prayer in absence?",
             ["An-Najashi (the Negus)", "Heraclius", "Chosroes", "Al-Muqawqis"], 0,
             "The Prophet ﷺ announced the Negus's death the day it happened and prayed over him with the companions.",
             "Sahih al-Bukhari, 1245"),
        ar=L("ما اسم ملك الحبشة الذي حمى المسلمين وصلّى عليه النبي ﷺ صلاة الغائب؟",
             ["النجاشي", "هرقل", "كسرى", "المقوقس"], 0,
             "نعى النبي ﷺ النجاشي يوم مات وصلّى عليه مع أصحابه.",
             "صحيح البخاري، 1245"))

    add("sira_046", "sira", "hard", "sira", S, WE, False,
        fr=L("Quel compagnon prit la parole devant le Négus pour expliquer l'islam ?",
             ["Ja'far ibn Abî Tâlib", "'Uthmân", "Bilâl", "Mus'ab ibn 'Umayr"], 0,
             "Ja'far exposa au roi ce que le Prophète ﷺ enseignait, et lui récita des versets de la sourate Maryam.",
             "Sîra — fait établi"),
        en=L("Which companion spoke before the Negus to explain Islam?",
             ["Ja'far ibn Abi Talib", "'Uthman", "Bilal", "Mus'ab ibn 'Umayr"], 0,
             "Ja'far explained to the king what the Prophet ﷺ taught, and recited verses of Surah Maryam to him.",
             "Sira — established fact"),
        ar=L("أي صحابي تكلّم أمام النجاشي ليبيّن له الإسلام؟",
             ["جعفر بن أبي طالب", "عثمان", "بلال", "مصعب بن عمير"], 0,
             "بيّن جعفر للملك ما جاء به النبي ﷺ وقرأ عليه من سورة مريم.",
             "السيرة — حقيقة ثابتة"))

    add("sira_047", "sira", "medium", "quran", Q, "111:1", False,
        fr=L("Quel oncle du Prophète ﷺ est condamné nommément dans le Coran ?",
             ["Abû Lahab", "Abû Tâlib", "Al-'Abbâs", "Hamza"], 0,
             "« Que périssent les deux mains d'Abû Lahab, et que lui-même périsse. »",
             "Coran — Sourate Al-Masad, 111:1"),
        en=L("Which uncle of the Prophet ﷺ is condemned by name in the Quran?",
             ["Abu Lahab", "Abu Talib", "Al-'Abbas", "Hamza"], 0,
             "\"May the hands of Abu Lahab perish, and may he perish.\"",
             "Quran — Surah Al-Masad, 111:1"),
        ar=L("أي عمّ للنبي ﷺ ذمّه القرآن باسمه؟",
             ["أبو لهب", "أبو طالب", "العباس", "حمزة"], 0,
             "﴿تبّت يدا أبي لهب وتبّ﴾.",
             "القرآن — سورة المسد، 111:1"))

    add("sira_048", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment appelle-t-on l'année où le Prophète ﷺ perdit son épouse Khadîja et son oncle Abû Tâlib ?",
             ["L'année de la tristesse", "L'année de l'éléphant", "L'année des délégations", "L'année de la famine"], 0,
             "Les deux soutiens du Prophète ﷺ moururent la même année, appelée « année de la tristesse ».",
             "Sîra — fait établi"),
        en=L("What is the year called in which the Prophet ﷺ lost his wife Khadija and his uncle Abu Talib?",
             ["The Year of Sorrow", "The Year of the Elephant", "The Year of Delegations", "The Year of Famine"], 0,
             "The Prophet's ﷺ two great supporters died in the same year, known as the Year of Sorrow.",
             "Sira — established fact"),
        ar=L("ماذا يُسمّى العام الذي فقد فيه النبي ﷺ زوجته خديجة وعمّه أبا طالب؟",
             ["عام الحزن", "عام الفيل", "عام الوفود", "عام المجاعة"], 0,
             "مات نصيرا النبي ﷺ في عام واحد سُمّي عام الحزن.",
             "السيرة — حقيقة ثابتة"))

    add("sira_049", "sira", "medium", "hadithBukhari", B, "3231", False,
        fr=L("Dans quelle ville le Prophète ﷺ fut-il chassé et blessé après y avoir appelé à l'islam, avant de refuser que l'ange des montagnes écrase ses habitants ?",
             ["At-Tâ'if", "Médine", "Khaybar", "Tabûk"], 0,
             "Repoussé à Tâ'if, il refusa de faire périr ses habitants, espérant que leurs descendants adoreraient Allah.",
             "Sahîh al-Bukhârî, 3231"),
        en=L("In which town was the Prophet ﷺ driven out and hurt after calling to Islam, before refusing to let the angel of the mountains crush its people?",
             ["At-Ta'if", "Madinah", "Khaybar", "Tabuk"], 0,
             "Rejected at Ta'if, he refused to destroy its people, hoping their descendants would worship Allah.",
             "Sahih al-Bukhari, 3231"),
        ar=L("في أي بلدة طُرد النبي ﷺ وأُوذي بعد دعوته، ثم أبى أن يُطبق ملك الجبال على أهلها؟",
             ["الطائف", "المدينة", "خيبر", "تبوك"], 0,
             "رُدّ في الطائف فأبى إهلاك أهلها رجاء أن يخرج من أصلابهم من يعبد الله.",
             "صحيح البخاري، 3231"))

    add("sira_050", "sira", "easy", "hadithBukhari", B, "349", False,
        fr=L("Lors du voyage nocturne et de l'ascension (Isrâ et Mi'râj), quelle obligation fut prescrite aux musulmans ?",
             ["Les cinq prières quotidiennes", "Le jeûne du Ramadan", "La zakât", "Le pèlerinage"], 0,
             "Les prières furent prescrites cette nuit-là, réduites de cinquante à cinq, avec la récompense de cinquante.",
             "Sahîh al-Bukhârî, 349"),
        en=L("During the Night Journey and Ascension (Isra and Mi'raj), which obligation was prescribed for Muslims?",
             ["The five daily prayers", "Fasting Ramadan", "Zakat", "The pilgrimage"], 0,
             "The prayers were prescribed that night, reduced from fifty to five, with the reward of fifty.",
             "Sahih al-Bukhari, 349"),
        ar=L("في ليلة الإسراء والمعراج، أي فريضة فُرضت على المسلمين؟",
             ["الصلوات الخمس", "صيام رمضان", "الزكاة", "الحج"], 0,
             "فُرضت الصلوات تلك الليلة، وخُفّفت من خمسين إلى خمس بأجر خمسين.",
             "صحيح البخاري، 349"))

    add("sira_051", "sira", "hard", "quran", Q, "53:14", False,
        fr=L("Quel arbre, à la limite extrême, le Prophète ﷺ vit-il lors de l'ascension selon la sourate An-Najm ?",
             ["Sidrat al-Muntahâ", "L'olivier béni", "Le palmier de Maryam", "L'arbre de Tûbâ"], 0,
             "« Près de Sidrat al-Muntahâ », le lotus de la limite.",
             "Coran — Sourate An-Najm, 53:14"),
        en=L("Which tree, at the farthest boundary, did the Prophet ﷺ see during the Ascension, according to Surah An-Najm?",
             ["Sidrat al-Muntaha", "The blessed olive tree", "Maryam's palm tree", "The tree of Tuba"], 0,
             "\"Near Sidrat al-Muntaha\", the lote tree of the utmost boundary.",
             "Quran — Surah An-Najm, 53:14"),
        ar=L("أي شجرة عند المنتهى رآها النبي ﷺ في المعراج بحسب سورة النجم؟",
             ["سدرة المنتهى", "شجرة الزيتون المباركة", "نخلة مريم", "شجرة طوبى"], 0,
             "﴿عند سدرة المنتهى﴾.",
             "القرآن — سورة النجم، 53:14"))

    add("sira_052", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment appelle-t-on les serments d'allégeance prêtés au Prophète ﷺ par des habitants de Yathrib, avant l'Hégire ?",
             ["Les pactes d'Al-'Aqaba", "Le pacte de Hudaybiyya", "Le serment de l'arbre", "Le pacte de Médine"], 0,
             "Des habitants de Yathrib prêtèrent serment au Prophète ﷺ à Al-'Aqaba, près de Minâ, avant l'Hégire.",
             "Sîra — fait établi"),
        en=L("What are the pledges of allegiance called that people of Yathrib gave the Prophet ﷺ before the Hijra?",
             ["The pledges of Al-'Aqaba", "The pact of Hudaybiyya", "The pledge of the tree", "The Constitution of Madinah"], 0,
             "People of Yathrib pledged allegiance to the Prophet ﷺ at Al-'Aqaba, near Mina, before the Hijra.",
             "Sira — established fact"),
        ar=L("ماذا تُسمّى البيعات التي بايع بها أهل يثرب النبي ﷺ قبل الهجرة؟",
             ["بيعة العقبة", "صلح الحديبية", "بيعة الشجرة", "وثيقة المدينة"], 0,
             "بايع نفر من أهل يثرب النبي ﷺ عند العقبة قرب منى قبل الهجرة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_053", "sira", "hard", "sira", S, WE, False,
        fr=L("Quel compagnon le Prophète ﷺ envoya-t-il à Yathrib, avant l'Hégire, pour enseigner l'islam ?",
             ["Mus'ab ibn 'Umayr", "Bilâl", "Abû Hurayra", "Khâlid ibn al-Walîd"], 0,
             "Mus'ab ibn 'Umayr fut le premier envoyé à Yathrib pour enseigner le Coran aux nouveaux musulmans.",
             "Sîra — fait établi"),
        en=L("Which companion did the Prophet ﷺ send to Yathrib, before the Hijra, to teach Islam?",
             ["Mus'ab ibn 'Umayr", "Bilal", "Abu Hurayra", "Khalid ibn al-Walid"], 0,
             "Mus'ab ibn 'Umayr was the first envoy to Yathrib, teaching the Quran to the new Muslims.",
             "Sira — established fact"),
        ar=L("أي صحابي بعثه النبي ﷺ إلى يثرب قبل الهجرة ليعلّم الناس الإسلام؟",
             ["مصعب بن عمير", "بلال", "أبو هريرة", "خالد بن الوليد"], 0,
             "كان مصعب بن عمير أول مبعوث إلى يثرب يعلّم المسلمين الجدد القرآن.",
             "السيرة — حقيقة ثابتة"))

    add("sira_054", "sira", "medium", "sira", S, WE, False,
        fr=L("Qui dormit dans le lit du Prophète ﷺ la nuit de son départ pour l'Hégire ?",
             ["'Alî ibn Abî Tâlib", "Abû Bakr", "Zayd ibn Hâritha", "Bilâl"], 0,
             "'Alî prit sa place dans le lit pour tromper ceux qui guettaient, et rendit ensuite les dépôts aux Mecquois.",
             "Sîra — fait établi"),
        en=L("Who slept in the Prophet's ﷺ bed on the night he left for the Hijra?",
             ["'Ali ibn Abi Talib", "Abu Bakr", "Zayd ibn Haritha", "Bilal"], 0,
             "'Ali took his place in the bed to mislead those watching, then returned the deposits to the Makkans.",
             "Sira — established fact"),
        ar=L("من نام في فراش النبي ﷺ ليلة خروجه مهاجرًا؟",
             ["علي بن أبي طالب", "أبو بكر", "زيد بن حارثة", "بلال"], 0,
             "نام علي في فراشه ليخفي خروجه، ثم ردّ الودائع إلى أهل مكة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_055", "sira", "medium", "sira", S, WE, False,
        fr=L("Dans quelle grotte le Prophète ﷺ et Abû Bakr se cachèrent-ils pendant l'Hégire ?",
             ["La grotte de Thawr", "La grotte de Hirâ", "La grotte d'Uhud", "La grotte de Tâ'if"], 0,
             "Ils se cachèrent trois jours dans la grotte de Thawr, au sud de La Mecque.",
             "Sîra — fait établi"),
        en=L("In which cave did the Prophet ﷺ and Abu Bakr hide during the Hijra?",
             ["The cave of Thawr", "The cave of Hira", "The cave of Uhud", "The cave of Ta'if"], 0,
             "They hid for three days in the cave of Thawr, south of Makkah.",
             "Sira — established fact"),
        ar=L("في أي غار اختبأ النبي ﷺ وأبو بكر أثناء الهجرة؟",
             ["غار ثور", "غار حراء", "غار أُحد", "غار الطائف"], 0,
             "اختبآ ثلاثة أيام في غار ثور جنوب مكة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_056", "sira", "hard", "hadithBukhari", B, "3905", False,
        fr=L("Quelle fille d'Abû Bakr apporta des provisions à la grotte et fut surnommée « celle aux deux ceintures » ?",
             ["Asmâ", "'Âisha", "Umm Kulthûm", "Umm Rûmân"], 0,
             "Asmâ déchira sa ceinture en deux pour attacher les provisions : d'où « Dhât an-Nitâqayn ».",
             "Sahîh al-Bukhârî, 3905"),
        en=L("Which daughter of Abu Bakr brought provisions to the cave and was nicknamed \"she of the two belts\"?",
             ["Asma", "'Aisha", "Umm Kulthum", "Umm Ruman"], 0,
             "Asma tore her belt in two to tie up the provisions: hence \"Dhat an-Nitaqayn\".",
             "Sahih al-Bukhari, 3905"),
        ar=L("أي بنات أبي بكر حملت الزاد إلى الغار ولُقّبت بـ«ذات النطاقين»؟",
             ["أسماء", "عائشة", "أم كلثوم", "أم رومان"], 0,
             "شقّت أسماء نطاقها نصفين لتربط الزاد، فسُمّيت ذات النطاقين.",
             "صحيح البخاري، 3905"))

    add("sira_057", "sira", "hard", "hadithBukhari", B, "3906", False,
        fr=L("Que se passa-t-il pour Surâqa, qui poursuivait le Prophète ﷺ pendant l'Hégire ?",
             ["Son cheval s'enfonça dans le sol, et il demanda la sauvegarde", "Il rattrapa le Prophète ﷺ", "Il se perdit dans le désert", "Il tomba malade"], 0,
             "Les pattes de son cheval s'enfoncèrent dans la terre ; Surâqa demanda grâce et repartit sans nuire.",
             "Sahîh al-Bukhârî, 3906"),
        en=L("What happened to Suraqa, who pursued the Prophet ﷺ during the Hijra?",
             ["His horse sank into the ground, and he asked for safety", "He caught up with the Prophet ﷺ", "He got lost in the desert", "He fell ill"], 0,
             "His horse's legs sank into the earth; Suraqa asked for safe conduct and left without harm.",
             "Sahih al-Bukhari, 3906"),
        ar=L("ماذا جرى لسراقة الذي طارد النبي ﷺ في الهجرة؟",
             ["ساخت قوائم فرسه في الأرض فطلب الأمان", "أدرك النبي ﷺ", "تاه في الصحراء", "مرض"], 0,
             "ساخت يدا فرسه في الأرض، فطلب سراقة الأمان ورجع دون أن يضرّ.",
             "صحيح البخاري، 3906"))

    add("sira_058", "sira", "easy", "quran", Q, "33:13", False,
        fr=L("Quel était l'ancien nom de Médine, cité dans le Coran ?",
             ["Yathrib", "Tayba", "Khaybar", "Bakka"], 0,
             "« Ô gens de Yathrib… », dit le Coran en rappelant la bataille des coalisés.",
             "Coran — Sourate Al-Ahzâb, 33:13"),
        en=L("What was the old name of Madinah, mentioned in the Quran?",
             ["Yathrib", "Tayba", "Khaybar", "Bakka"], 0,
             "\"O people of Yathrib…\", says the Quran, recalling the battle of the confederates.",
             "Quran — Surah Al-Ahzab, 33:13"),
        ar=L("ما الاسم القديم للمدينة المذكور في القرآن؟",
             ["يثرب", "طيبة", "خيبر", "بكّة"], 0,
             "﴿يا أهل يثرب…﴾ في سياق غزوة الأحزاب.",
             "القرآن — سورة الأحزاب، 33:13"))

    add("sira_059", "sira", "medium", "hadithBukhari", B, "2731", False,
        fr=L("Comment s'appelait la chamelle du Prophète ﷺ, qui s'agenouilla à Hudaybiyya ?",
             ["Al-Qaswâ", "Al-Burâq", "Ad-Duldul", "Al-'Adbâ"], 0,
             "À Hudaybiyya, Al-Qaswâ s'agenouilla ; le Prophète ﷺ dit : « Celui qui retint l'éléphant l'a retenue. »",
             "Sahîh al-Bukhârî, 2731"),
        en=L("What was the name of the Prophet's ﷺ she-camel, which knelt at Hudaybiyya?",
             ["Al-Qaswa", "Al-Buraq", "Ad-Duldul", "Al-'Adba"], 0,
             "At Hudaybiyya, Al-Qaswa knelt; the Prophet ﷺ said: \"The One who held back the elephant has held her back.\"",
             "Sahih al-Bukhari, 2731"),
        ar=L("ما اسم ناقة النبي ﷺ التي بركت في الحديبية؟",
             ["القصواء", "البراق", "الدُّلدُل", "العضباء"], 0,
             "بركت القصواء في الحديبية فقال ﷺ: «حبسها حابس الفيل».",
             "صحيح البخاري، 2731"))

    add("sira_060", "sira", "medium", "sira", S, WE, False,
        fr=L("Qu'établit le Prophète ﷺ entre les Muhâjirûn et les Ansâr à son arrivée à Médine ?",
             ["Une fraternité, deux par deux", "Un impôt", "Une armée", "Un marché"], 0,
             "Il fraternisa les émigrés et les auxiliaires, chaque Muhâjir ayant un frère parmi les Ansâr.",
             "Sîra — fait établi"),
        en=L("What did the Prophet ﷺ establish between the Muhajirun and the Ansar on arriving in Madinah?",
             ["Brotherhood, in pairs", "A tax", "An army", "A market"], 0,
             "He made the emigrants and the helpers brothers, each Muhajir paired with a brother from the Ansar.",
             "Sira — established fact"),
        ar=L("ماذا أقام النبي ﷺ بين المهاجرين والأنصار عند قدومه المدينة؟",
             ["المؤاخاة", "ضريبة", "جيشًا", "سوقًا"], 0,
             "آخى بين المهاجرين والأنصار، فكان لكل مهاجر أخ من الأنصار.",
             "السيرة — حقيقة ثابتة"))

    add("sira_061", "sira", "hard", "sira", S, WE, False,
        fr=L("Comment appelle-t-on le document par lequel le Prophète ﷺ organisa les relations entre les communautés de Médine ?",
             ["La Sahîfa (Constitution) de Médine", "Le traité de Hudaybiyya", "Le pacte de Tâ'if", "La charte de Quba"], 0,
             "La Sahîfa fixa les droits et devoirs des musulmans et des autres tribus de Médine.",
             "Sîra — fait établi"),
        en=L("What is the document called by which the Prophet ﷺ organised relations between the communities of Madinah?",
             ["The Sahifa (Constitution) of Madinah", "The treaty of Hudaybiyya", "The pact of Ta'if", "The charter of Quba"], 0,
             "The Sahifa set out the rights and duties of the Muslims and the other tribes of Madinah.",
             "Sira — established fact"),
        ar=L("ماذا تُسمّى الوثيقة التي نظّم بها النبي ﷺ العلاقات بين أهل المدينة؟",
             ["صحيفة (وثيقة) المدينة", "صلح الحديبية", "عهد الطائف", "ميثاق قباء"], 0,
             "حدّدت الصحيفة حقوق المسلمين وسائر قبائل المدينة وواجباتهم.",
             "السيرة — حقيقة ثابتة"))

    add("sira_062", "sira", "hard", "hadithBukhari", B, "6452", False,
        fr=L("Comment appelait-on les compagnons pauvres qui vivaient dans la mosquée du Prophète ﷺ ?",
             ["Ahl as-Suffa (les gens du banc)", "Les Muhâjirûn", "Les Ansâr", "Les Hawâriyyûn"], 0,
             "Abû Hurayra raconte qu'il était parmi les gens de la Suffa, nourris par le Prophète ﷺ.",
             "Sahîh al-Bukhârî, 6452"),
        en=L("What were the poor companions called who lived in the Prophet's ﷺ mosque?",
             ["Ahl as-Suffa (the people of the bench)", "The Muhajirun", "The Ansar", "The Hawariyyun"], 0,
             "Abu Hurayra relates that he was among the people of the Suffa, fed by the Prophet ﷺ.",
             "Sahih al-Bukhari, 6452"),
        ar=L("ماذا كان يُسمّى فقراء الصحابة الذين سكنوا مسجد النبي ﷺ؟",
             ["أهل الصُّفّة", "المهاجرون", "الأنصار", "الحواريون"], 0,
             "يروي أبو هريرة أنه كان من أهل الصُّفّة الذين يطعمهم النبي ﷺ.",
             "صحيح البخاري، 6452"))

    add("sira_063", "sira", "hard", "sira", S, WE, False,
        fr=L("Combien d'années après l'Hégire eut lieu la bataille de Badr ?",
             ["Deux", "Cinq", "Huit", "Dix"], 0,
             "Badr eut lieu en l'an 2 de l'Hégire, pendant le Ramadan.",
             "Sîra — fait établi"),
        en=L("How many years after the Hijra did the battle of Badr take place?",
             ["Two", "Five", "Eight", "Ten"], 0,
             "Badr was fought in 2 AH, during Ramadan.",
             "Sira — established fact"),
        ar=L("بعد كم سنة من الهجرة وقعت غزوة بدر؟",
             ["سنتين", "خمس", "ثمانٍ", "عشر"], 0,
             "وقعت بدر في السنة الثانية للهجرة في رمضان.",
             "السيرة — حقيقة ثابتة"))

    add("sira_064", "sira", "hard", "quran", Q, "8:9", False,
        fr=L("Combien d'anges Allah promit-Il d'envoyer en renfort aux croyants à Badr ?",
             ["Mille", "Cent", "Dix", "Cent mille"], 0,
             "« Je vous envoie en renfort mille anges, se suivant les uns les autres. »",
             "Coran — Sourate Al-Anfâl, 8:9"),
        en=L("How many angels did Allah promise to send as reinforcement to the believers at Badr?",
             ["A thousand", "A hundred", "Ten", "A hundred thousand"], 0,
             "\"I will reinforce you with a thousand angels, following one another.\"",
             "Quran — Surah Al-Anfal, 8:9"),
        ar=L("بكم ملَك وعد الله أن يمدّ المؤمنين في بدر؟",
             ["ألف", "مئة", "عشرة", "مئة ألف"], 0,
             "﴿أني ممدّكم بألف من الملائكة مردفين﴾.",
             "القرآن — سورة الأنفال، 8:9"))

    add("sira_065", "sira", "medium", "hadithBukhari", B, "3039", False,
        fr=L("À Uhud, quelle erreur des archers fit basculer la bataille ?",
             ["Ils quittèrent la colline malgré l'ordre du Prophète ﷺ", "Ils tirèrent trop tôt", "Ils s'endormirent", "Ils changèrent de camp"], 0,
             "Le Prophète ﷺ avait ordonné aux archers de ne pas bouger ; la plupart descendirent pour le butin, et la cavalerie ennemie les contourna.",
             "Sahîh al-Bukhârî, 3039"),
        en=L("At Uhud, which mistake by the archers turned the battle?",
             ["They left the hill despite the Prophet's ﷺ order", "They shot too early", "They fell asleep", "They switched sides"], 0,
             "The Prophet ﷺ had ordered the archers not to move; most came down for the spoils and the enemy cavalry went round them.",
             "Sahih al-Bukhari, 3039"),
        ar=L("في أُحد، ما الخطأ الذي وقع فيه الرماة فقلب المعركة؟",
             ["تركوا الجبل رغم أمر النبي ﷺ", "رموا مبكرًا", "ناموا", "انضموا إلى العدو"], 0,
             "أمرهم النبي ﷺ ألا يبرحوا، فنزل أكثرهم للغنيمة والتفّ عليهم خيل العدو.",
             "صحيح البخاري، 3039"))

    add("sira_066", "sira", "easy", "sira", S, WE, False,
        fr=L("Près de quelle ville se trouve le mont Uhud ?",
             ["Médine", "La Mecque", "Tâ'if", "Jérusalem"], 0,
             "Le mont Uhud est au nord de Médine ; la bataille eut lieu à son pied.",
             "Sîra — fait établi"),
        en=L("Near which city is Mount Uhud?",
             ["Madinah", "Makkah", "Ta'if", "Jerusalem"], 0,
             "Mount Uhud lies north of Madinah; the battle took place at its foot.",
             "Sira — established fact"),
        ar=L("قرب أي مدينة يقع جبل أُحد؟",
             ["المدينة", "مكة", "الطائف", "القدس"], 0,
             "يقع جبل أُحد شمال المدينة، وعند سفحه دارت المعركة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_067", "sira", "medium", "sira", S, WE, False,
        fr=L("Quel compagnon proposa de creuser une tranchée pour défendre Médine contre les coalisés ?",
             ["Salmân al-Fârisî", "Bilâl", "Abû Dharr", "Suhayb"], 0,
             "Salmân le Persan suggéra la tranchée, une tactique connue en Perse.",
             "Sîra — fait établi"),
        en=L("Which companion suggested digging a trench to defend Madinah against the confederates?",
             ["Salman al-Farisi", "Bilal", "Abu Dharr", "Suhayb"], 0,
             "Salman the Persian suggested the trench, a tactic known in Persia.",
             "Sira — established fact"),
        ar=L("أي صحابي أشار بحفر الخندق لحماية المدينة من الأحزاب؟",
             ["سلمان الفارسي", "بلال", "أبو ذر", "صهيب"], 0,
             "أشار سلمان الفارسي بحفر الخندق، وهو أسلوب معروف عند الفرس.",
             "السيرة — حقيقة ثابتة"))

    add("sira_068", "sira", "medium", "quran", Q, "33:9-10", False,
        fr=L("Sous quel autre nom la bataille de la Tranchée est-elle connue, d'après la sourate qui en parle ?",
             ["La bataille des Coalisés (Al-Ahzâb)", "La bataille de Badr", "La bataille de Hunayn", "La bataille de Mu'ta"], 0,
             "La sourate Al-Ahzâb évoque les armées coalisées venues assiéger Médine et le vent envoyé contre elles.",
             "Coran — Sourate Al-Ahzâb, 33:9-10"),
        en=L("By what other name is the battle of the Trench known, after the surah that speaks of it?",
             ["The battle of the Confederates (Al-Ahzab)", "The battle of Badr", "The battle of Hunayn", "The battle of Mu'ta"], 0,
             "Surah Al-Ahzab recalls the allied armies that besieged Madinah and the wind sent against them.",
             "Quran — Surah Al-Ahzab, 33:9-10"),
        ar=L("بأي اسم آخر تُعرف غزوة الخندق نسبة إلى السورة التي ذكرتها؟",
             ["غزوة الأحزاب", "غزوة بدر", "غزوة حنين", "غزوة مؤتة"], 0,
             "تذكر سورة الأحزاب الجيوش المتحالفة التي حاصرت المدينة والريح التي أُرسلت عليها.",
             "القرآن — سورة الأحزاب، 33:9-10"))

    add("sira_069", "sira", "medium", "quran", Q, "48:18", False,
        fr=L("Comment appelle-t-on le serment prêté sous un arbre à Hudaybiyya, dont Allah dit être satisfait ?",
             ["Bay'at ar-Ridwân", "Bay'at al-'Aqaba", "Bay'at an-Nisâ", "Bay'at al-Fath"], 0,
             "« Allah a été satisfait des croyants quand ils te prêtaient serment sous l'arbre. »",
             "Coran — Sourate Al-Fath, 48:18"),
        en=L("What is the pledge called that was given under a tree at Hudaybiyya, with which Allah says He was pleased?",
             ["Bay'at ar-Ridwan", "Bay'at al-'Aqaba", "Bay'at an-Nisa", "Bay'at al-Fath"], 0,
             "\"Allah was pleased with the believers when they pledged allegiance to you under the tree.\"",
             "Quran — Surah Al-Fath, 48:18"),
        ar=L("ماذا تُسمّى البيعة التي تمت تحت الشجرة في الحديبية ورضي الله عن أصحابها؟",
             ["بيعة الرضوان", "بيعة العقبة", "بيعة النساء", "بيعة الفتح"], 0,
             "﴿لقد رضي الله عن المؤمنين إذ يبايعونك تحت الشجرة﴾.",
             "القرآن — سورة الفتح، 48:18"))

    add("sira_070", "sira", "medium", "quran", Q, "48:1", False,
        fr=L("Quelle sourate s'ouvre par « Nous t'avons accordé une victoire éclatante », révélée après le traité de Hudaybiyya ?",
             ["Al-Fath", "An-Nasr", "Al-Anfâl", "At-Tawba"], 0,
             "« Nous t'avons accordé une victoire éclatante » : la sourate Al-Fath.",
             "Coran — Sourate Al-Fath, 48:1"),
        en=L("Which surah opens with \"We have given you a clear victory\", revealed after the treaty of Hudaybiyya?",
             ["Al-Fath", "An-Nasr", "Al-Anfal", "At-Tawba"], 0,
             "\"Indeed, We have given you a clear victory\": Surah Al-Fath.",
             "Quran — Surah Al-Fath, 48:1"),
        ar=L("أي سورة تبدأ بـ﴿إنا فتحنا لك فتحًا مبينًا﴾ ونزلت بعد صلح الحديبية؟",
             ["الفتح", "النصر", "الأنفال", "التوبة"], 0,
             "﴿إنا فتحنا لك فتحًا مبينًا﴾: سورة الفتح.",
             "القرآن — سورة الفتح، 48:1"))

    add("sira_071", "sira", "hard", "sira", S, WE, False,
        fr=L("En quelle année de l'Hégire fut conclu le traité de Hudaybiyya ?",
             ["L'an 6", "L'an 2", "L'an 8", "L'an 10"], 0,
             "Le traité de Hudaybiyya fut conclu en l'an 6 de l'Hégire, entre les musulmans et Quraysh.",
             "Sîra — fait établi"),
        en=L("In which year of the Hijra was the treaty of Hudaybiyya concluded?",
             ["6 AH", "2 AH", "8 AH", "10 AH"], 0,
             "The treaty of Hudaybiyya was concluded in 6 AH between the Muslims and Quraysh.",
             "Sira — established fact"),
        ar=L("في أي سنة هجرية عُقد صلح الحديبية؟",
             ["السنة السادسة", "السنة الثانية", "السنة الثامنة", "السنة العاشرة"], 0,
             "عُقد صلح الحديبية في السنة السادسة للهجرة بين المسلمين وقريش.",
             "السيرة — حقيقة ثابتة"))

    add("sira_072", "sira", "hard", "hadithBukhari", B, "7", False,
        fr=L("Quel empereur byzantin reçut la lettre du Prophète ﷺ l'invitant à l'islam et interrogea Abû Sufyân à son sujet ?",
             ["Héraclius", "Néron", "Constantin", "Justinien"], 0,
             "Héraclius interrogea Abû Sufyân sur le Prophète ﷺ après avoir reçu sa lettre.",
             "Sahîh al-Bukhârî, 7"),
        en=L("Which Byzantine emperor received the Prophet's ﷺ letter inviting him to Islam and questioned Abu Sufyan about him?",
             ["Heraclius", "Nero", "Constantine", "Justinian"], 0,
             "Heraclius questioned Abu Sufyan about the Prophet ﷺ after receiving his letter.",
             "Sahih al-Bukhari, 7"),
        ar=L("أي إمبراطور للروم تلقّى كتاب النبي ﷺ يدعوه إلى الإسلام وسأل أبا سفيان عنه؟",
             ["هرقل", "نيرون", "قسطنطين", "جستنيان"], 0,
             "سأل هرقل أبا سفيان عن النبي ﷺ بعد أن جاءه كتابه.",
             "صحيح البخاري، 7"))

    add("sira_073", "sira", "medium", "hadithBukhari", B, "3701", False,
        fr=L("À qui le Prophète ﷺ remit-il l'étendard à Khaybar, après avoir dit : « Demain je le donnerai à un homme qu'Allah et Son Messager aiment » ?",
             ["'Alî ibn Abî Tâlib", "Abû Bakr", "'Umar", "Sa'd ibn Abî Waqqâs"], 0,
             "Il appela 'Alî, qui souffrait des yeux ; il lui cracha dans les yeux, le guérit et lui remit l'étendard.",
             "Sahîh al-Bukhârî, 3701"),
        en=L("To whom did the Prophet ﷺ hand the banner at Khaybar, after saying: \"Tomorrow I will give it to a man whom Allah and His Messenger love\"?",
             ["'Ali ibn Abi Talib", "Abu Bakr", "'Umar", "Sa'd ibn Abi Waqqas"], 0,
             "He called 'Ali, who had sore eyes; he applied his saliva, cured him and gave him the banner.",
             "Sahih al-Bukhari, 3701"),
        ar=L("لمن دفع النبي ﷺ الراية في خيبر بعد قوله: «لأعطينّ الراية غدًا رجلًا يحبه الله ورسوله»؟",
             ["علي بن أبي طالب", "أبو بكر", "عمر", "سعد بن أبي وقاص"], 0,
             "دعا عليًا وكان يشتكي عينيه، فبصق فيهما فبرأ، ودفع إليه الراية.",
             "صحيح البخاري، 3701"))

    add("sira_074", "sira", "hard", "hadithBukhari", B, "4262", False,
        fr=L("Quels trois commandants tombèrent successivement à la bataille de Mu'ta ?",
             ["Zayd ibn Hâritha, Ja'far ibn Abî Tâlib et 'Abdullâh ibn Rawâha", "Hamza, Mus'ab et Sa'd", "Abû Bakr, 'Umar et 'Uthmân", "Bilâl, Salmân et Suhayb"], 0,
             "Le Prophète ﷺ annonça à Médine : « Zayd a pris l'étendard et est tombé, puis Ja'far, puis Ibn Rawâha… puis un sabre d'Allah l'a pris. »",
             "Sahîh al-Bukhârî, 4262"),
        en=L("Which three commanders fell one after another at the battle of Mu'ta?",
             ["Zayd ibn Haritha, Ja'far ibn Abi Talib and 'Abdullah ibn Rawaha", "Hamza, Mus'ab and Sa'd", "Abu Bakr, 'Umar and 'Uthman", "Bilal, Salman and Suhayb"], 0,
             "The Prophet ﷺ announced in Madinah: \"Zayd took the banner and fell, then Ja'far, then Ibn Rawaha… then a sword of Allah took it.\"",
             "Sahih al-Bukhari, 4262"),
        ar=L("أي ثلاثة قادة استُشهدوا على التوالي في غزوة مؤتة؟",
             ["زيد بن حارثة وجعفر بن أبي طالب وعبد الله بن رواحة", "حمزة ومصعب وسعد", "أبو بكر وعمر وعثمان", "بلال وسلمان وصهيب"], 0,
             "نعاهم النبي ﷺ في المدينة: «أخذ الراية زيد فأُصيب، ثم جعفر، ثم ابن رواحة… ثم أخذها سيف من سيوف الله».",
             "صحيح البخاري، 4262"))

    add("sira_075", "sira", "medium", "hadithBukhari", B, "4262", False,
        fr=L("Quel compagnon le Prophète ﷺ appela-t-il « un sabre parmi les sabres d'Allah » ?",
             ["Khâlid ibn al-Walîd", "'Alî", "Hamza", "Abû 'Ubayda"], 0,
             "À Mu'ta, « un sabre parmi les sabres d'Allah », Khâlid ibn al-Walîd, prit l'étendard et sauva l'armée.",
             "Sahîh al-Bukhârî, 4262"),
        en=L("Which companion did the Prophet ﷺ call \"a sword among the swords of Allah\"?",
             ["Khalid ibn al-Walid", "'Ali", "Hamza", "Abu 'Ubayda"], 0,
             "At Mu'ta, \"a sword among the swords of Allah\", Khalid ibn al-Walid, took the banner and saved the army.",
             "Sahih al-Bukhari, 4262"),
        ar=L("أي صحابي سمّاه النبي ﷺ «سيفًا من سيوف الله»؟",
             ["خالد بن الوليد", "علي", "حمزة", "أبو عبيدة"], 0,
             "في مؤتة أخذ الراية «سيف من سيوف الله» خالد بن الوليد فنجّى الجيش.",
             "صحيح البخاري، 4262"))

    add("sira_076", "sira", "medium", "hadithBukhari", B, "4287", False,
        fr=L("Que fit le Prophète ﷺ des idoles qui entouraient la Ka'ba, lors de la conquête de La Mecque ?",
             ["Il les renversa en récitant « La vérité est venue, le faux a disparu »", "Il les vendit", "Il les emporta à Médine", "Il les laissa en place"], 0,
             "Il frappait les idoles de son bâton en disant : « La vérité est venue et le faux a disparu. »",
             "Sahîh al-Bukhârî, 4287"),
        en=L("What did the Prophet ﷺ do with the idols around the Ka'ba at the conquest of Makkah?",
             ["He knocked them down reciting \"Truth has come and falsehood has vanished\"", "He sold them", "He took them to Madinah", "He left them in place"], 0,
             "He struck the idols with his stick saying: \"Truth has come and falsehood has vanished.\"",
             "Sahih al-Bukhari, 4287"),
        ar=L("ماذا فعل النبي ﷺ بالأصنام حول الكعبة يوم فتح مكة؟",
             ["طعنها قائلًا ﴿جاء الحق وزهق الباطل﴾", "باعها", "حملها إلى المدينة", "تركها مكانها"], 0,
             "كان يطعن الأصنام بعود في يده ويقول: ﴿جاء الحق وزهق الباطل﴾.",
             "صحيح البخاري، 4287"))

    add("sira_077", "sira", "easy", "sira", S, WE, False,
        fr=L("Qui lança l'appel à la prière du haut de la Ka'ba le jour de la conquête de La Mecque ?",
             ["Bilâl", "Abû Bakr", "'Alî", "'Umar"], 0,
             "Le Prophète ﷺ ordonna à Bilâl de monter sur la Ka'ba pour appeler à la prière.",
             "Sîra — fait établi"),
        en=L("Who gave the call to prayer from the top of the Ka'ba on the day Makkah was conquered?",
             ["Bilal", "Abu Bakr", "'Ali", "'Umar"], 0,
             "The Prophet ﷺ ordered Bilal to climb onto the Ka'ba and call to prayer.",
             "Sira — established fact"),
        ar=L("من أذّن فوق الكعبة يوم فتح مكة؟",
             ["بلال", "أبو بكر", "علي", "عمر"], 0,
             "أمر النبي ﷺ بلالًا أن يصعد على الكعبة فيؤذّن.",
             "السيرة — حقيقة ثابتة"))

    add("sira_078", "sira", "hard", "sira", S, WE, False,
        fr=L("Que dit le Prophète ﷺ aux Mecquois vaincus qui l'avaient persécuté, le jour de la conquête ?",
             ["« Allez, vous êtes libres »", "« Vous serez jugés demain »", "« Quittez la ville »", "« Payez une rançon »"], 0,
             "Il leur pardonna : « Allez, vous êtes libres. »",
             "Sîra — fait établi"),
        en=L("What did the Prophet ﷺ tell the defeated Makkans who had persecuted him, on the day of the conquest?",
             ["\"Go, you are free\"", "\"You will be judged tomorrow\"", "\"Leave the city\"", "\"Pay a ransom\""], 0,
             "He forgave them: \"Go, you are free.\"",
             "Sira — established fact"),
        ar=L("ماذا قال النبي ﷺ لأهل مكة الذين آذوه، يوم الفتح؟",
             ["«اذهبوا فأنتم الطلقاء»", "«ستُحاكمون غدًا»", "«اخرجوا من البلد»", "«ادفعوا الفدية»"], 0,
             "عفا عنهم وقال: «اذهبوا فأنتم الطلقاء».",
             "السيرة — حقيقة ثابتة"))

    add("sira_079", "sira", "hard", "quran", Q, "9:25", False,
        fr=L("Lors de quelle bataille, citée dans le Coran, les musulmans furent-ils d'abord surpris malgré leur grand nombre ?",
             ["Hunayn", "Badr", "Uhud", "Khaybar"], 0,
             "« Le jour de Hunayn, votre grand nombre vous plut mais ne vous servit à rien. »",
             "Coran — Sourate At-Tawba, 9:25"),
        en=L("At which battle, named in the Quran, were the Muslims at first caught off guard despite their large numbers?",
             ["Hunayn", "Badr", "Uhud", "Khaybar"], 0,
             "\"On the day of Hunayn, your great number pleased you, but it availed you nothing.\"",
             "Quran — Surah At-Tawba, 9:25"),
        ar=L("في أي غزوة ذكرها القرآن فوجئ المسلمون في البداية رغم كثرتهم؟",
             ["حنين", "بدر", "أُحد", "خيبر"], 0,
             "﴿ويوم حنين إذ أعجبتكم كثرتكم فلم تغنِ عنكم شيئًا﴾.",
             "القرآن — سورة التوبة، 9:25"))

    add("sira_080", "sira", "hard", "hadithBukhari", B, "4418", False,
        fr=L("Quel compagnon, resté en arrière lors de l'expédition de Tabûk, avoua sincèrement sa faute et fut pardonné par une révélation ?",
             ["Ka'b ibn Mâlik", "Abû Dharr", "Anas ibn Mâlik", "Abû Hurayra"], 0,
             "Ka'b ibn Mâlik dit la vérité, subit cinquante jours de mise à l'écart, puis Allah révéla son pardon (9:118).",
             "Sahîh al-Bukhârî, 4418"),
        en=L("Which companion, who stayed behind from the expedition to Tabuk, confessed honestly and was forgiven by a revelation?",
             ["Ka'b ibn Malik", "Abu Dharr", "Anas ibn Malik", "Abu Hurayra"], 0,
             "Ka'b ibn Malik told the truth, endured fifty days of being shunned, then Allah revealed his forgiveness (9:118).",
             "Sahih al-Bukhari, 4418"),
        ar=L("أي صحابي تخلّف عن غزوة تبوك فصدق في اعترافه ونزل الوحي بتوبته؟",
             ["كعب بن مالك", "أبو ذر", "أنس بن مالك", "أبو هريرة"], 0,
             "صدق كعب بن مالك، وهُجر خمسين يومًا، ثم أنزل الله توبته (9:118).",
             "صحيح البخاري، 4418"))

    add("sira_081", "sira", "medium", "sira", S, WE, False,
        fr=L("Comment appelle-t-on l'an 9 de l'Hégire, où de nombreuses tribus vinrent embrasser l'islam à Médine ?",
             ["L'année des délégations", "L'année de la tristesse", "L'année de l'éléphant", "L'année de la sécheresse"], 0,
             "Après la conquête de La Mecque, les délégations des tribus arabes affluèrent à Médine.",
             "Sîra — fait établi"),
        en=L("What is 9 AH called, when many tribes came to Madinah to embrace Islam?",
             ["The Year of Delegations", "The Year of Sorrow", "The Year of the Elephant", "The Year of Drought"], 0,
             "After the conquest of Makkah, delegations of Arab tribes streamed into Madinah.",
             "Sira — established fact"),
        ar=L("ماذا يُسمّى العام التاسع للهجرة الذي قدمت فيه القبائل إلى المدينة لتُسلم؟",
             ["عام الوفود", "عام الحزن", "عام الفيل", "عام القحط"], 0,
             "بعد فتح مكة توافدت وفود القبائل العربية على المدينة.",
             "السيرة — حقيقة ثابتة"))

    add("sira_082", "sira", "easy", "sira", S, WE, False,
        fr=L("Où le Prophète ﷺ prononça-t-il son sermon d'adieu ?",
             ["À Arafat", "À Médine", "Sur le mont Uhud", "À Tâ'if"], 0,
             "Le sermon d'adieu fut prononcé à Arafat, lors du pèlerinage d'adieu.",
             "Sîra — fait établi"),
        en=L("Where did the Prophet ﷺ deliver his Farewell Sermon?",
             ["At Arafat", "In Madinah", "On Mount Uhud", "At Ta'if"], 0,
             "The Farewell Sermon was delivered at Arafat, during the Farewell Pilgrimage.",
             "Sira — established fact"),
        ar=L("أين ألقى النبي ﷺ خطبة الوداع؟",
             ["في عرفات", "في المدينة", "على جبل أُحد", "في الطائف"], 0,
             "أُلقيت خطبة الوداع في عرفات خلال حجة الوداع.",
             "السيرة — حقيقة ثابتة"))

    add("sira_083", "sira", "medium", "quran", Q, "5:3", False,
        fr=L("Quel verset, révélé lors du pèlerinage d'adieu, annonce que la religion est parachevée ?",
             ["« Aujourd'hui, J'ai parachevé pour vous votre religion »", "« Lis, au nom de ton Seigneur »", "« Quand vient le secours d'Allah »", "« Dis : Il est Allah, Unique »"], 0,
             "« Aujourd'hui J'ai parachevé pour vous votre religion, et accompli sur vous Mon bienfait. »",
             "Coran — Sourate Al-Mâ'ida, 5:3"),
        en=L("Which verse, revealed during the Farewell Pilgrimage, announces that the religion is perfected?",
             ["\"This day I have perfected for you your religion\"", "\"Read, in the name of your Lord\"", "\"When the victory of Allah comes\"", "\"Say: He is Allah, One\""], 0,
             "\"This day I have perfected for you your religion and completed My favour upon you.\"",
             "Quran — Surah Al-Ma'ida, 5:3"),
        ar=L("أي آية نزلت في حجة الوداع تعلن كمال الدين؟",
             ["﴿اليوم أكملت لكم دينكم﴾", "﴿اقرأ باسم ربك﴾", "﴿إذا جاء نصر الله﴾", "﴿قل هو الله أحد﴾"], 0,
             "﴿اليوم أكملت لكم دينكم وأتممت عليكم نعمتي﴾.",
             "القرآن — سورة المائدة، 5:3"))

    add("sira_084", "sira", "easy", "sira", S, WE, False,
        fr=L("Dans quelle ville le Prophète ﷺ est-il mort et enterré ?",
             ["Médine", "La Mecque", "Jérusalem", "Tâ'if"], 0,
             "Il mourut à Médine, en l'an 11 de l'Hégire, et y fut enterré.",
             "Sîra — fait établi"),
        en=L("In which city did the Prophet ﷺ die and get buried?",
             ["Madinah", "Makkah", "Jerusalem", "Ta'if"], 0,
             "He died in Madinah in 11 AH and was buried there.",
             "Sira — established fact"),
        ar=L("في أي مدينة تُوفّي النبي ﷺ ودُفن؟",
             ["المدينة", "مكة", "القدس", "الطائف"], 0,
             "تُوفّي في المدينة سنة 11 للهجرة ودُفن فيها.",
             "السيرة — حقيقة ثابتة"))

    add("sira_085", "sira", "medium", "sira", S, WE, False,
        fr=L("Dans la chambre de quelle épouse le Prophète ﷺ fut-il enterré ?",
             ["'Âisha", "Khadîja", "Hafsa", "Umm Salama"], 0,
             "Il fut enterré là où il mourut, dans la chambre de 'Âisha, aujourd'hui dans la Mosquée du Prophète.",
             "Sîra — fait établi"),
        en=L("In which wife's room was the Prophet ﷺ buried?",
             ["'Aisha's", "Khadija's", "Hafsa's", "Umm Salama's"], 0,
             "He was buried where he died, in 'Aisha's room, now inside the Prophet's Mosque.",
             "Sira — established fact"),
        ar=L("في حجرة أي زوجة دُفن النبي ﷺ؟",
             ["عائشة", "خديجة", "حفصة", "أم سلمة"], 0,
             "دُفن حيث قُبض، في حجرة عائشة، وهي اليوم داخل المسجد النبوي.",
             "السيرة — حقيقة ثابتة"))

    add("sira_086", "sira", "hard", "hadithBukhari", B, "3667", False,
        fr=L("Qui déclara, à la mort du Prophète ﷺ : « Celui qui adorait Muhammad, Muhammad est mort ; celui qui adore Allah, Allah est Vivant » ?",
             ["Abû Bakr", "'Umar", "'Alî", "Bilâl"], 0,
             "Abû Bakr apaisa les compagnons et récita : « Muhammad n'est qu'un messager… » (3:144).",
             "Sahîh al-Bukhârî, 3667"),
        en=L("Who declared, at the Prophet's ﷺ death: \"Whoever worshipped Muhammad, Muhammad has died; whoever worships Allah, Allah is Ever-Living\"?",
             ["Abu Bakr", "'Umar", "'Ali", "Bilal"], 0,
             "Abu Bakr calmed the companions and recited: \"Muhammad is not but a messenger…\" (3:144).",
             "Sahih al-Bukhari, 3667"),
        ar=L("من قال عند وفاة النبي ﷺ: «من كان يعبد محمدًا فإن محمدًا قد مات، ومن كان يعبد الله فإن الله حي لا يموت»؟",
             ["أبو بكر", "عمر", "علي", "بلال"], 0,
             "ثبّت أبو بكر الصحابة وتلا: ﴿وما محمد إلا رسول…﴾ (3:144).",
             "صحيح البخاري، 3667"))

    add("sira_087", "sira", "easy", "sira", S, WE, False,
        fr=L("Comment s'appelaient les deux petits-fils du Prophète ﷺ, fils de Fâtima et 'Alî ?",
             ["Al-Hasan et Al-Husayn", "Ibrâhîm et Ismâ'îl", "Zayd et Usâma", "Ja'far et 'Aqîl"], 0,
             "Al-Hasan et Al-Husayn, que le Prophète ﷺ aimait tendrement.",
             "Sîra — fait établi"),
        en=L("What were the names of the Prophet's ﷺ two grandsons, the sons of Fatima and 'Ali?",
             ["Al-Hasan and Al-Husayn", "Ibrahim and Isma'il", "Zayd and Usama", "Ja'far and 'Aqil"], 0,
             "Al-Hasan and Al-Husayn, whom the Prophet ﷺ loved dearly.",
             "Sira — established fact"),
        ar=L("ما اسما حفيدَي النبي ﷺ ابنَي فاطمة وعلي؟",
             ["الحسن والحسين", "إبراهيم وإسماعيل", "زيد وأسامة", "جعفر وعقيل"], 0,
             "الحسن والحسين، وكان النبي ﷺ يحبهما حبًا شديدًا.",
             "السيرة — حقيقة ثابتة"))

    add("sira_088", "sira", "easy", "sira", S, WE, False,
        fr=L("Quelle épouse du Prophète ﷺ était la fille d'Abû Bakr ?",
             ["'Âisha", "Hafsa", "Zaynab", "Sawda"], 0,
             "'Âisha, fille d'Abû Bakr, transmit un très grand nombre de hadiths.",
             "Sîra — fait établi"),
        en=L("Which wife of the Prophet ﷺ was the daughter of Abu Bakr?",
             ["'Aisha", "Hafsa", "Zaynab", "Sawda"], 0,
             "'Aisha, daughter of Abu Bakr, transmitted a very large number of hadiths.",
             "Sira — established fact"),
        ar=L("أي زوجات النبي ﷺ كانت ابنة أبي بكر؟",
             ["عائشة", "حفصة", "زينب", "سودة"], 0,
             "عائشة بنت أبي بكر، وقد روت عددًا كبيرًا من الأحاديث.",
             "السيرة — حقيقة ثابتة"))

    add("sira_089", "sira", "medium", "sira", S, WE, False,
        fr=L("Quelle épouse du Prophète ﷺ était la fille de 'Umar ibn al-Khattâb ?",
             ["Hafsa", "'Âisha", "Umm Habîba", "Maymûna"], 0,
             "Hafsa bint 'Umar ; c'est chez elle que fut conservé le premier recueil du Coran.",
             "Sîra — fait établi"),
        en=L("Which wife of the Prophet ﷺ was the daughter of 'Umar ibn al-Khattab?",
             ["Hafsa", "'Aisha", "Umm Habiba", "Maymuna"], 0,
             "Hafsa bint 'Umar; the first collected copy of the Quran was kept with her.",
             "Sira — established fact"),
        ar=L("أي زوجات النبي ﷺ كانت ابنة عمر بن الخطاب؟",
             ["حفصة", "عائشة", "أم حبيبة", "ميمونة"], 0,
             "حفصة بنت عمر، وعندها حُفظت الصحف الأولى للقرآن.",
             "السيرة — حقيقة ثابتة"))

    add("sira_090", "sira", "medium", "sira", S, WE, False,
        fr=L("Quel compagnon a rapporté le plus grand nombre de hadiths du Prophète ﷺ ?",
             ["Abû Hurayra", "Anas ibn Mâlik", "'Abdullâh ibn 'Umar", "Jâbir"], 0,
             "Abû Hurayra, qui accompagna le Prophète ﷺ assidûment, est le compagnon ayant rapporté le plus de hadiths.",
             "Sîra — fait établi"),
        en=L("Which companion narrated the largest number of hadiths from the Prophet ﷺ?",
             ["Abu Hurayra", "Anas ibn Malik", "'Abdullah ibn 'Umar", "Jabir"], 0,
             "Abu Hurayra, who kept close company with the Prophet ﷺ, is the companion who narrated the most hadiths.",
             "Sira — established fact"),
        ar=L("أي صحابي روى أكبر عدد من الأحاديث عن النبي ﷺ؟",
             ["أبو هريرة", "أنس بن مالك", "عبد الله بن عمر", "جابر"], 0,
             "أبو هريرة الذي لازم النبي ﷺ هو أكثر الصحابة رواية للحديث.",
             "السيرة — حقيقة ثابتة"))
