// GENERATED by tool/art/bake_cross_board.py — do not edit by hand.
//
// The plate and this table come from one grid, so an index can never
// address a square the art does not have.

class SceneAnchor {
  const SceneAnchor(this.x, this.y);

  final double x;
  final double y;
}

/// The 52 circuit squares, in riding order.
const List<SceneAnchor> crossTrackAnchors = [
  SceneAnchor(0.0875, 0.4411),
  SceneAnchor(0.1464, 0.4411),
  SceneAnchor(0.2053, 0.4411),
  SceneAnchor(0.2643, 0.4411),
  SceneAnchor(0.3232, 0.4411),
  SceneAnchor(0.3821, 0.4411),
  SceneAnchor(0.4411, 0.3821),
  SceneAnchor(0.4411, 0.3232),
  SceneAnchor(0.4411, 0.2643),
  SceneAnchor(0.4411, 0.2053),
  SceneAnchor(0.4411, 0.1464),
  SceneAnchor(0.4411, 0.0875),
  SceneAnchor(0.5000, 0.0875),
  SceneAnchor(0.5589, 0.0875),
  SceneAnchor(0.5589, 0.1464),
  SceneAnchor(0.5589, 0.2053),
  SceneAnchor(0.5589, 0.2643),
  SceneAnchor(0.5589, 0.3232),
  SceneAnchor(0.5589, 0.3821),
  SceneAnchor(0.6179, 0.4411),
  SceneAnchor(0.6768, 0.4411),
  SceneAnchor(0.7357, 0.4411),
  SceneAnchor(0.7947, 0.4411),
  SceneAnchor(0.8536, 0.4411),
  SceneAnchor(0.9125, 0.4411),
  SceneAnchor(0.9125, 0.5000),
  SceneAnchor(0.9125, 0.5589),
  SceneAnchor(0.8536, 0.5589),
  SceneAnchor(0.7947, 0.5589),
  SceneAnchor(0.7357, 0.5589),
  SceneAnchor(0.6768, 0.5589),
  SceneAnchor(0.6179, 0.5589),
  SceneAnchor(0.5589, 0.6179),
  SceneAnchor(0.5589, 0.6768),
  SceneAnchor(0.5589, 0.7357),
  SceneAnchor(0.5589, 0.7947),
  SceneAnchor(0.5589, 0.8536),
  SceneAnchor(0.5589, 0.9125),
  SceneAnchor(0.5000, 0.9125),
  SceneAnchor(0.4411, 0.9125),
  SceneAnchor(0.4411, 0.8536),
  SceneAnchor(0.4411, 0.7947),
  SceneAnchor(0.4411, 0.7357),
  SceneAnchor(0.4411, 0.6768),
  SceneAnchor(0.4411, 0.6179),
  SceneAnchor(0.3821, 0.5589),
  SceneAnchor(0.3232, 0.5589),
  SceneAnchor(0.2643, 0.5589),
  SceneAnchor(0.2053, 0.5589),
  SceneAnchor(0.1464, 0.5589),
  SceneAnchor(0.0875, 0.5589),
  SceneAnchor(0.0875, 0.5000),
];

/// Each team's five-step escalier, outermost first.
const Map<int, List<SceneAnchor>> crossLaneAnchors = {
  0: [SceneAnchor(0.1464, 0.5000), SceneAnchor(0.2053, 0.5000), SceneAnchor(0.2643, 0.5000), SceneAnchor(0.3232, 0.5000), SceneAnchor(0.3821, 0.5000)],
  1: [SceneAnchor(0.5000, 0.1464), SceneAnchor(0.5000, 0.2053), SceneAnchor(0.5000, 0.2643), SceneAnchor(0.5000, 0.3232), SceneAnchor(0.5000, 0.3821)],
  2: [SceneAnchor(0.8536, 0.5000), SceneAnchor(0.7947, 0.5000), SceneAnchor(0.7357, 0.5000), SceneAnchor(0.6768, 0.5000), SceneAnchor(0.6179, 0.5000)],
  3: [SceneAnchor(0.5000, 0.8536), SceneAnchor(0.5000, 0.7947), SceneAnchor(0.5000, 0.7357), SceneAnchor(0.5000, 0.6768), SceneAnchor(0.5000, 0.6179)],
};

/// The four stable slots in each team's corner.
const Map<int, List<SceneAnchor>> crossCampAnchors = {
  0: [SceneAnchor(0.3214, 0.3214), SceneAnchor(0.3709, 0.3214), SceneAnchor(0.3214, 0.3709), SceneAnchor(0.3709, 0.3709)],
  1: [SceneAnchor(0.6291, 0.3214), SceneAnchor(0.6786, 0.3214), SceneAnchor(0.6291, 0.3709), SceneAnchor(0.6786, 0.3709)],
  2: [SceneAnchor(0.6291, 0.6291), SceneAnchor(0.6786, 0.6291), SceneAnchor(0.6291, 0.6786), SceneAnchor(0.6786, 0.6786)],
  3: [SceneAnchor(0.3214, 0.6291), SceneAnchor(0.3709, 0.6291), SceneAnchor(0.3214, 0.6786), SceneAnchor(0.3709, 0.6786)],
};

/// Mecca, at the centre.
const SceneAnchor crossCenterAnchor = SceneAnchor(0.5000, 0.5000);

/// The middle of each team's corner medallion. The place names are drawn
/// by Flutter from the localisations rather than baked into the plate, so
/// all twelve languages read their own.
const Map<int, SceneAnchor> crossCornerAnchors = {
  0: SceneAnchor(0.2047, 0.2047),
  1: SceneAnchor(0.7953, 0.2047),
  2: SceneAnchor(0.7953, 0.7953),
  3: SceneAnchor(0.2047, 0.7953),
};
