// GENERATED by tool/art/bake_cross_board.py — do not edit by hand.
//
// The plate and this table come from one grid, so an index can never
// address a square the art does not have.

class SceneAnchor {
  const SceneAnchor(this.x, this.y);

  final double x;
  final double y;
}

/// The 52 circuit squares, in riding order.
const List<SceneAnchor> crossTrackAnchors = [
  SceneAnchor(0.0576, 0.4368),
  SceneAnchor(0.1208, 0.4368),
  SceneAnchor(0.1840, 0.4368),
  SceneAnchor(0.2472, 0.4368),
  SceneAnchor(0.3104, 0.4368),
  SceneAnchor(0.3736, 0.4368),
  SceneAnchor(0.4368, 0.3736),
  SceneAnchor(0.4368, 0.3104),
  SceneAnchor(0.4368, 0.2472),
  SceneAnchor(0.4368, 0.1840),
  SceneAnchor(0.4368, 0.1208),
  SceneAnchor(0.4368, 0.0576),
  SceneAnchor(0.5000, 0.0576),
  SceneAnchor(0.5632, 0.0576),
  SceneAnchor(0.5632, 0.1208),
  SceneAnchor(0.5632, 0.1840),
  SceneAnchor(0.5632, 0.2472),
  SceneAnchor(0.5632, 0.3104),
  SceneAnchor(0.5632, 0.3736),
  SceneAnchor(0.6264, 0.4368),
  SceneAnchor(0.6896, 0.4368),
  SceneAnchor(0.7528, 0.4368),
  SceneAnchor(0.8160, 0.4368),
  SceneAnchor(0.8792, 0.4368),
  SceneAnchor(0.9424, 0.4368),
  SceneAnchor(0.9424, 0.5000),
  SceneAnchor(0.9424, 0.5632),
  SceneAnchor(0.8792, 0.5632),
  SceneAnchor(0.8160, 0.5632),
  SceneAnchor(0.7528, 0.5632),
  SceneAnchor(0.6896, 0.5632),
  SceneAnchor(0.6264, 0.5632),
  SceneAnchor(0.5632, 0.6264),
  SceneAnchor(0.5632, 0.6896),
  SceneAnchor(0.5632, 0.7528),
  SceneAnchor(0.5632, 0.8160),
  SceneAnchor(0.5632, 0.8792),
  SceneAnchor(0.5632, 0.9424),
  SceneAnchor(0.5000, 0.9424),
  SceneAnchor(0.4368, 0.9424),
  SceneAnchor(0.4368, 0.8792),
  SceneAnchor(0.4368, 0.8160),
  SceneAnchor(0.4368, 0.7528),
  SceneAnchor(0.4368, 0.6896),
  SceneAnchor(0.4368, 0.6264),
  SceneAnchor(0.3736, 0.5632),
  SceneAnchor(0.3104, 0.5632),
  SceneAnchor(0.2472, 0.5632),
  SceneAnchor(0.1840, 0.5632),
  SceneAnchor(0.1208, 0.5632),
  SceneAnchor(0.0576, 0.5632),
  SceneAnchor(0.0576, 0.5000),
];

/// Each team's five-step escalier, outermost first.
const Map<int, List<SceneAnchor>> crossLaneAnchors = {
  0: [SceneAnchor(0.1208, 0.5000), SceneAnchor(0.1840, 0.5000), SceneAnchor(0.2472, 0.5000), SceneAnchor(0.3104, 0.5000), SceneAnchor(0.3736, 0.5000)],
  1: [SceneAnchor(0.5000, 0.1208), SceneAnchor(0.5000, 0.1840), SceneAnchor(0.5000, 0.2472), SceneAnchor(0.5000, 0.3104), SceneAnchor(0.5000, 0.3736)],
  2: [SceneAnchor(0.8792, 0.5000), SceneAnchor(0.8160, 0.5000), SceneAnchor(0.7528, 0.5000), SceneAnchor(0.6896, 0.5000), SceneAnchor(0.6264, 0.5000)],
  3: [SceneAnchor(0.5000, 0.8792), SceneAnchor(0.5000, 0.8160), SceneAnchor(0.5000, 0.7528), SceneAnchor(0.5000, 0.6896), SceneAnchor(0.5000, 0.6264)],
};

/// The four stable slots in each team's corner.
const Map<int, List<SceneAnchor>> crossCampAnchors = {
  0: [SceneAnchor(0.3085, 0.3085), SceneAnchor(0.3616, 0.3085), SceneAnchor(0.3085, 0.3616), SceneAnchor(0.3616, 0.3616)],
  1: [SceneAnchor(0.6384, 0.3085), SceneAnchor(0.6915, 0.3085), SceneAnchor(0.6384, 0.3616), SceneAnchor(0.6915, 0.3616)],
  2: [SceneAnchor(0.6384, 0.6384), SceneAnchor(0.6915, 0.6384), SceneAnchor(0.6384, 0.6915), SceneAnchor(0.6915, 0.6915)],
  3: [SceneAnchor(0.3085, 0.6384), SceneAnchor(0.3616, 0.6384), SceneAnchor(0.3085, 0.6915), SceneAnchor(0.3616, 0.6915)],
};

/// Mecca, at the centre.
const SceneAnchor crossCenterAnchor = SceneAnchor(0.5000, 0.5000);

/// The middle of each team's corner medallion. The place names are drawn
/// by Flutter from the localisations rather than baked into the plate, so
/// all twelve languages read their own.
const Map<int, SceneAnchor> crossCornerAnchors = {
  0: SceneAnchor(0.1834, 0.1834),
  1: SceneAnchor(0.8166, 0.1834),
  2: SceneAnchor(0.8166, 0.8166),
  3: SceneAnchor(0.1834, 0.8166),
};
