// GENERATED by tool/art/bake_cross_board.py — do not edit by hand.
//
// The plate and this table come from one grid, so an index can never
// address a square the art does not have.

class SceneAnchor {
  const SceneAnchor(this.x, this.y);

  final double x;
  final double y;
}

/// The 52 circuit squares, in riding order.
const List<SceneAnchor> crossTrackAnchors = [
  SceneAnchor(0.0847, 0.4407),
  SceneAnchor(0.1440, 0.4407),
  SceneAnchor(0.2033, 0.4407),
  SceneAnchor(0.2627, 0.4407),
  SceneAnchor(0.3220, 0.4407),
  SceneAnchor(0.3813, 0.4407),
  SceneAnchor(0.4407, 0.3813),
  SceneAnchor(0.4407, 0.3220),
  SceneAnchor(0.4407, 0.2627),
  SceneAnchor(0.4407, 0.2033),
  SceneAnchor(0.4407, 0.1440),
  SceneAnchor(0.4407, 0.0847),
  SceneAnchor(0.5000, 0.0847),
  SceneAnchor(0.5593, 0.0847),
  SceneAnchor(0.5593, 0.1440),
  SceneAnchor(0.5593, 0.2033),
  SceneAnchor(0.5593, 0.2627),
  SceneAnchor(0.5593, 0.3220),
  SceneAnchor(0.5593, 0.3813),
  SceneAnchor(0.6187, 0.4407),
  SceneAnchor(0.6780, 0.4407),
  SceneAnchor(0.7373, 0.4407),
  SceneAnchor(0.7967, 0.4407),
  SceneAnchor(0.8560, 0.4407),
  SceneAnchor(0.9153, 0.4407),
  SceneAnchor(0.9153, 0.5000),
  SceneAnchor(0.9153, 0.5593),
  SceneAnchor(0.8560, 0.5593),
  SceneAnchor(0.7967, 0.5593),
  SceneAnchor(0.7373, 0.5593),
  SceneAnchor(0.6780, 0.5593),
  SceneAnchor(0.6187, 0.5593),
  SceneAnchor(0.5593, 0.6187),
  SceneAnchor(0.5593, 0.6780),
  SceneAnchor(0.5593, 0.7373),
  SceneAnchor(0.5593, 0.7967),
  SceneAnchor(0.5593, 0.8560),
  SceneAnchor(0.5593, 0.9153),
  SceneAnchor(0.5000, 0.9153),
  SceneAnchor(0.4407, 0.9153),
  SceneAnchor(0.4407, 0.8560),
  SceneAnchor(0.4407, 0.7967),
  SceneAnchor(0.4407, 0.7373),
  SceneAnchor(0.4407, 0.6780),
  SceneAnchor(0.4407, 0.6187),
  SceneAnchor(0.3813, 0.5593),
  SceneAnchor(0.3220, 0.5593),
  SceneAnchor(0.2627, 0.5593),
  SceneAnchor(0.2033, 0.5593),
  SceneAnchor(0.1440, 0.5593),
  SceneAnchor(0.0847, 0.5593),
  SceneAnchor(0.0847, 0.5000),
];

/// Each team's five-step escalier, outermost first.
const Map<int, List<SceneAnchor>> crossLaneAnchors = {
  0: [SceneAnchor(0.1440, 0.5000), SceneAnchor(0.2033, 0.5000), SceneAnchor(0.2627, 0.5000), SceneAnchor(0.3220, 0.5000), SceneAnchor(0.3813, 0.5000)],
  1: [SceneAnchor(0.5000, 0.1440), SceneAnchor(0.5000, 0.2033), SceneAnchor(0.5000, 0.2627), SceneAnchor(0.5000, 0.3220), SceneAnchor(0.5000, 0.3813)],
  2: [SceneAnchor(0.8560, 0.5000), SceneAnchor(0.7967, 0.5000), SceneAnchor(0.7373, 0.5000), SceneAnchor(0.6780, 0.5000), SceneAnchor(0.6187, 0.5000)],
  3: [SceneAnchor(0.5000, 0.8560), SceneAnchor(0.5000, 0.7967), SceneAnchor(0.5000, 0.7373), SceneAnchor(0.5000, 0.6780), SceneAnchor(0.5000, 0.6187)],
};

/// The four stable slots in each team's corner.
const Map<int, List<SceneAnchor>> crossCampAnchors = {
  0: [SceneAnchor(0.1580, 0.1580), SceneAnchor(0.3080, 0.1580), SceneAnchor(0.1580, 0.3080), SceneAnchor(0.3080, 0.3080)],
  1: [SceneAnchor(0.6920, 0.1580), SceneAnchor(0.8420, 0.1580), SceneAnchor(0.6920, 0.3080), SceneAnchor(0.8420, 0.3080)],
  2: [SceneAnchor(0.6920, 0.6920), SceneAnchor(0.8420, 0.6920), SceneAnchor(0.6920, 0.8420), SceneAnchor(0.8420, 0.8420)],
  3: [SceneAnchor(0.1580, 0.6920), SceneAnchor(0.3080, 0.6920), SceneAnchor(0.1580, 0.8420), SceneAnchor(0.3080, 0.8420)],
};

/// Mecca, at the centre.
const SceneAnchor crossCenterAnchor = SceneAnchor(0.5000, 0.5000);

/// The middle of each team's corner medallion, where its place is named.
/// The names are drawn by Flutter from the localisations rather than
/// baked into the plate, so all twelve languages read their own.
const Map<int, SceneAnchor> crossCornerAnchors = {
  0: SceneAnchor(0.2330, 0.2330),
  1: SceneAnchor(0.7670, 0.2330),
  2: SceneAnchor(0.7670, 0.7670),
  3: SceneAnchor(0.2330, 0.7670),
};
