// GENERATED by tool/art/bake_scene.py — do not edit by hand.
// Anchor positions are normalized to the baked scene image
// (assets/board/scene_oasis.webp); scale is the perspective depth
// factor for sprites standing at that anchor.

class SceneAnchor {
  const SceneAnchor(this.x, this.y, this.scale);

  final double x;
  final double y;
  final double scale;
}

const List<SceneAnchor> sceneTrackAnchors = [
  SceneAnchor(0.2052, 0.3747, 0.937),
  SceneAnchor(0.3009, 0.3472, 0.922),
  SceneAnchor(0.4167, 0.3389, 0.918),
  SceneAnchor(0.5350, 0.3384, 0.918),
  SceneAnchor(0.6529, 0.3421, 0.920),
  SceneAnchor(0.7604, 0.3609, 0.929),
  SceneAnchor(0.8306, 0.3991, 0.949),
  SceneAnchor(0.8607, 0.4444, 0.973),
  SceneAnchor(0.8700, 0.4917, 0.997),
  SceneAnchor(0.8722, 0.5386, 1.022),
  SceneAnchor(0.8706, 0.5859, 1.047),
  SceneAnchor(0.8538, 0.6329, 1.071),
  SceneAnchor(0.8038, 0.6748, 1.093),
  SceneAnchor(0.7063, 0.7023, 1.107),
  SceneAnchor(0.5864, 0.7106, 1.111),
  SceneAnchor(0.4636, 0.7110, 1.112),
  SceneAnchor(0.3414, 0.7074, 1.110),
  SceneAnchor(0.2308, 0.6885, 1.100),
  SceneAnchor(0.1609, 0.6504, 1.080),
  SceneAnchor(0.1334, 0.6050, 1.056),
  SceneAnchor(0.1275, 0.5578, 1.032),
  SceneAnchor(0.1289, 0.5108, 1.007),
  SceneAnchor(0.1339, 0.4636, 0.983),
  SceneAnchor(0.1539, 0.4166, 0.958),
];

const Map<int, List<SceneAnchor>> sceneLaneAnchors = {
  0: [SceneAnchor(0.2439, 0.4455, 0.973), SceneAnchor(0.2877, 0.4593, 0.980), SceneAnchor(0.3315, 0.4730, 0.987), SceneAnchor(0.3754, 0.4867, 0.994)],
  1: [SceneAnchor(0.6927, 0.4043, 0.952), SceneAnchor(0.6597, 0.4251, 0.962), SceneAnchor(0.6268, 0.4459, 0.973), SceneAnchor(0.5938, 0.4666, 0.984)],
  2: [SceneAnchor(0.7618, 0.6057, 1.056), SceneAnchor(0.7170, 0.5920, 1.049), SceneAnchor(0.6722, 0.5783, 1.042), SceneAnchor(0.6274, 0.5645, 1.035)],
  3: [SceneAnchor(0.3008, 0.6469, 1.078), SceneAnchor(0.3349, 0.6261, 1.067), SceneAnchor(0.3690, 0.6054, 1.056), SceneAnchor(0.4031, 0.5846, 1.045)],
};

const Map<int, List<SceneAnchor>> sceneCampAnchors = {
  0: [SceneAnchor(0.0892, 0.3012, 0.896), SceneAnchor(0.1762, 0.3012, 0.896), SceneAnchor(0.0892, 0.3297, 0.911), SceneAnchor(0.1762, 0.3297, 0.911)],
  1: [SceneAnchor(0.9108, 0.3012, 0.896), SceneAnchor(0.8238, 0.3012, 0.896), SceneAnchor(0.9108, 0.3297, 0.911), SceneAnchor(0.8238, 0.3297, 0.911)],
  2: [SceneAnchor(0.7112, 0.8671, 1.190), SceneAnchor(0.7955, 0.8732, 1.194), SceneAnchor(0.8797, 0.8671, 1.190), SceneAnchor(0.9640, 0.8732, 1.194)],
  3: [SceneAnchor(0.0360, 0.8671, 1.190), SceneAnchor(0.1203, 0.8732, 1.194), SceneAnchor(0.2045, 0.8671, 1.190), SceneAnchor(0.2888, 0.8732, 1.194)],
};

const SceneAnchor sceneCenterAnchor = SceneAnchor(0.5000, 0.5410, 1.000);
