// GENERATED by tool/art/board_from_ref.py — do not edit by hand.
// Anchors are normalized to the scene image built from the owner's
// board reference; scale is the perspective factor at that anchor.

class SceneAnchor {
  const SceneAnchor(this.x, this.y, this.scale);

  final double x;
  final double y;
  final double scale;
}

const List<SceneAnchor> sceneTrackAnchors = [
  SceneAnchor(0.3090, 0.2406, 0.908),
  SceneAnchor(0.4190, 0.2406, 0.908),
  SceneAnchor(0.5290, 0.2406, 0.908),
  SceneAnchor(0.6389, 0.2406, 0.908),
  SceneAnchor(0.7380, 0.2577, 0.916),
  SceneAnchor(0.8278, 0.2894, 0.930),
  SceneAnchor(0.9176, 0.3212, 0.945),
  SceneAnchor(0.9337, 0.3720, 0.967),
  SceneAnchor(0.9337, 0.4270, 0.992),
  SceneAnchor(0.9337, 0.4819, 1.017),
  SceneAnchor(0.8599, 0.5204, 1.034),
  SceneAnchor(0.7779, 0.5570, 1.051),
  SceneAnchor(0.6898, 0.5857, 1.064),
  SceneAnchor(0.5798, 0.5857, 1.064),
  SceneAnchor(0.4699, 0.5857, 1.064),
  SceneAnchor(0.3599, 0.5857, 1.064),
  SceneAnchor(0.2589, 0.5739, 1.058),
  SceneAnchor(0.1768, 0.5373, 1.042),
  SceneAnchor(0.0948, 0.5007, 1.025),
  SceneAnchor(0.0651, 0.4524, 1.004),
  SceneAnchor(0.0651, 0.3974, 0.979),
  SceneAnchor(0.0651, 0.3424, 0.954),
  SceneAnchor(0.1295, 0.3041, 0.937),
  SceneAnchor(0.2193, 0.2724, 0.923),
];

const Map<int, List<SceneAnchor>> sceneLaneAnchors = {
  0: [SceneAnchor(0.3542, 0.2900, 0.930), SceneAnchor(0.3959, 0.3108, 0.940), SceneAnchor(0.4375, 0.3316, 0.949), SceneAnchor(0.4780, 0.3519, 0.958)],
  1: [SceneAnchor(0.6969, 0.2864, 0.929), SceneAnchor(0.6553, 0.3072, 0.938), SceneAnchor(0.6136, 0.3281, 0.948), SceneAnchor(0.5720, 0.3483, 0.957)],
  2: [SceneAnchor(0.4994, 0.5363, 1.041), SceneAnchor(0.4994, 0.5065, 1.028), SceneAnchor(0.4994, 0.4768, 1.015), SceneAnchor(0.4994, 0.4494, 1.002)],
  3: [SceneAnchor(0.2829, 0.4399, 0.998), SceneAnchor(0.3233, 0.4262, 0.992), SceneAnchor(0.3638, 0.4131, 0.986), SceneAnchor(0.4042, 0.3995, 0.980)],
};

const Map<int, List<SceneAnchor>> sceneCampAnchors = {
  0: [SceneAnchor(0.0092, 0.2710, 0.848), SceneAnchor(0.0734, 0.2805, 0.852), SceneAnchor(-0.0003, 0.2995, 0.860), SceneAnchor(0.0639, 0.3090, 0.864)],
  1: [SceneAnchor(0.9420, 0.2591, 0.843), SceneAnchor(0.9872, 0.2733, 0.849), SceneAnchor(0.9325, 0.2864, 0.855), SceneAnchor(0.9777, 0.3007, 0.860)],
  2: [SceneAnchor(0.7112, 0.6101, 0.989), SceneAnchor(0.7731, 0.6184, 0.992), SceneAnchor(0.6446, 0.6184, 0.992), SceneAnchor(0.7064, 0.6279, 0.996)],
  3: [SceneAnchor(0.2924, 0.6101, 0.989), SceneAnchor(0.3542, 0.6184, 0.992), SceneAnchor(0.2257, 0.6184, 0.992), SceneAnchor(0.2876, 0.6279, 0.996)],
};

const SceneAnchor sceneCenterAnchor = SceneAnchor(0.4994, 0.4114, 1.000);
