// GENERATED by tool/art/board_from_ref.py — do not edit by hand.
// Anchors are normalized to the scene image built from the owner's
// board reference; scale is the perspective factor at that anchor.

class SceneAnchor {
  const SceneAnchor(this.x, this.y, this.scale);

  final double x;
  final double y;
  final double scale;
}

const List<SceneAnchor> sceneTrackAnchors = [
  SceneAnchor(0.2187, 0.2726, 0.923),
  SceneAnchor(0.3085, 0.2408, 0.908),
  SceneAnchor(0.4183, 0.2406, 0.908),
  SceneAnchor(0.5283, 0.2406, 0.908),
  SceneAnchor(0.6382, 0.2406, 0.908),
  SceneAnchor(0.7375, 0.2575, 0.916),
  SceneAnchor(0.8272, 0.2892, 0.930),
  SceneAnchor(0.9170, 0.3210, 0.944),
  SceneAnchor(0.9337, 0.3716, 0.967),
  SceneAnchor(0.9337, 0.4266, 0.992),
  SceneAnchor(0.9337, 0.4816, 1.017),
  SceneAnchor(0.8605, 0.5202, 1.034),
  SceneAnchor(0.7784, 0.5568, 1.051),
  SceneAnchor(0.6905, 0.5857, 1.064),
  SceneAnchor(0.5805, 0.5857, 1.064),
  SceneAnchor(0.4706, 0.5857, 1.064),
  SceneAnchor(0.3606, 0.5857, 1.064),
  SceneAnchor(0.2594, 0.5742, 1.058),
  SceneAnchor(0.1773, 0.5376, 1.042),
  SceneAnchor(0.0953, 0.5010, 1.025),
  SceneAnchor(0.0651, 0.4527, 1.004),
  SceneAnchor(0.0651, 0.3978, 0.979),
  SceneAnchor(0.0651, 0.3428, 0.954),
  SceneAnchor(0.1289, 0.3043, 0.937),
];

const Map<int, List<SceneAnchor>> sceneLaneAnchors = {
  0: [SceneAnchor(0.3542, 0.2900, 0.930), SceneAnchor(0.3959, 0.3108, 0.940), SceneAnchor(0.4375, 0.3316, 0.949), SceneAnchor(0.4780, 0.3519, 0.958)],
  1: [SceneAnchor(0.6969, 0.2864, 0.929), SceneAnchor(0.6553, 0.3072, 0.938), SceneAnchor(0.6136, 0.3281, 0.948), SceneAnchor(0.5720, 0.3483, 0.957)],
  2: [SceneAnchor(0.4994, 0.5363, 1.041), SceneAnchor(0.4994, 0.5065, 1.028), SceneAnchor(0.4994, 0.4768, 1.015), SceneAnchor(0.4994, 0.4494, 1.002)],
  3: [SceneAnchor(0.2829, 0.4399, 0.998), SceneAnchor(0.3233, 0.4262, 0.992), SceneAnchor(0.3638, 0.4131, 0.986), SceneAnchor(0.4042, 0.3995, 0.980)],
};

const Map<int, List<SceneAnchor>> sceneCampAnchors = {
  0: [SceneAnchor(0.0092, 0.2710, 0.848), SceneAnchor(0.0734, 0.2805, 0.852), SceneAnchor(-0.0003, 0.2995, 0.860), SceneAnchor(0.0639, 0.3090, 0.864)],
  1: [SceneAnchor(0.8230, 0.2626, 0.845), SceneAnchor(0.8683, 0.2769, 0.851), SceneAnchor(0.8159, 0.2900, 0.856), SceneAnchor(0.8611, 0.3043, 0.862)],
  2: [SceneAnchor(0.7398, 0.6196, 0.993), SceneAnchor(0.7969, 0.6279, 0.996), SceneAnchor(0.6826, 0.6279, 0.996), SceneAnchor(0.7398, 0.6362, 0.999)],
  3: [SceneAnchor(0.3423, 0.6124, 0.990), SceneAnchor(0.3995, 0.6208, 0.993), SceneAnchor(0.3328, 0.6279, 0.996), SceneAnchor(0.3899, 0.6362, 0.999)],
};

const SceneAnchor sceneCenterAnchor = SceneAnchor(0.4994, 0.4114, 1.000);
