"""English — details, beginner_3 (50 questions)."""

D = {
"sira_291": "Every standard account of the Qur'an's history, and the words of Zayd ibn Thabit recorded in Sahih al-Bukhari, tell that after many reciters were killed in the fighting at Yamama, 'Umar urged Abu Bakr to gather the Qur'an, and Abu Bakr gave the task to Zayd, who collected it from what was written down and from the memories of the reciters. The pages were kept with Abu Bakr, then with 'Umar. Allah had promised: \"Indeed, it is We who sent down the Reminder, and indeed We are its guardian\" (15:9). A Muslim sees in this care one of the ways that promise was kept.",

"sira_292": "Every standard biography records that the Prophet's ﷺ father 'Abdullah died before he was born, and that his mother Amina died while he was still a small boy, so his grandfather 'Abd al-Muttalib, a respected elder of Quraysh, took him into his care and kept him close. When the grandfather died, the boy passed to his uncle Abu Talib, who protected him for the rest of his life. The Qur'an recalls those years: \"Did He not find you an orphan and give you shelter?\" (93:6). A Muslim learns that Allah cared for His Prophet ﷺ through the love of his own family.",

"sira_293": "The verse comes in Surah Ad-Duha, where Allah swears by the morning brightness and the still night and tells His Prophet ﷺ: \"Your Lord has not forsaken you, nor does He hate you\" (93:3). Then He counts three favours: \"Did He not find you an orphan and give you shelter? And find you unaware and guide you? And find you poor and make you self-sufficient?\" (93:6-8). The surah ends by asking him to pass the kindness on: do not oppress the orphan, do not turn away the one who asks, and speak of your Lord's favour (93:9-11). A Muslim learns that remembering how Allah helped us should make us gentle with others.",

"sira_294": "The Qur'an speaks of Uhud in Surah Al 'Imran, right after naming Badr: \"Allah had already given you victory at Badr when you were few\" (3:123). Then it turns to the morning the Prophet ﷺ went out to set the believers in their positions for battle (3:121), at the mountain of Uhud outside Medina. Every standard biography tells that the archers left the hill they had been told to hold, the Muslims suffered heavily, the Prophet ﷺ himself was wounded, and his uncle Hamza was killed. The Qur'an adds that Allah forgave them (3:152). A Muslim learns that hardship after victory is also a test.",

"sira_295": "Surah Al-Ahzab, the Confederates, keeps the memory of this battle: \"O you who believe, remember the favour of Allah upon you when armies came to you and We sent upon them a wind and armies you did not see\" (33:9). The enemy tribes had joined together to attack Medina, and every standard biography records that the Muslims, with the Prophet ﷺ carrying earth beside them, dug a wide trench across the open side of the city so that the horsemen could not cross. The Qur'an describes the fear of those days, when \"hearts reached the throats\" (33:10). A Muslim learns that planning and hard work go together with trust in Allah's help.",

"sira_296": "'A'isha was the daughter of Abu Bakr as-Siddiq, the Prophet's ﷺ closest friend, who became the first caliph after him. The Qur'an speaks of her father as the Prophet's ﷺ companion in the cave during the emigration: \"the second of the two, when they were in the cave, when he said to his companion: do not grieve, indeed Allah is with us\" (9:40). Every standard biography records that the Prophet ﷺ died in 'A'isha's room and was buried there, and that she taught the companions and passed on a great number of his words. A Muslim learns her name as a mother of the believers and a teacher of the community.",

"sira_297": "The full verse reads: \"The Prophet is closer to the believers than their own selves, and his wives are their mothers\" (33:6). It stands near the beginning of Surah Al-Ahzab, after Allah has said that calling an adopted boy someone's son does not make him a true son (33:4-5); here, by contrast, Allah Himself gives the Prophet's ﷺ wives the title of mothers. Later in the same surah He says that no one may marry his wives after him (33:53). A Muslim honours Khadija, 'A'isha and the other wives of the Prophet ﷺ with the respect owed to a mother.",

"sira_298": "Every standard biography records that 'Ali was the son of Abu Talib, the uncle who raised the Prophet ﷺ, that he grew up in the Prophet's ﷺ own household, and that he accepted Islam as a boy, among the very first. On the night of the emigration he slept in the Prophet's ﷺ bed so that the watchers outside would think he was still there. In Medina he married Fatima, the Prophet's ﷺ daughter, and their sons al-Hasan and al-Husayn were the Prophet's ﷺ grandsons; years later 'Ali became the fourth caliph. A Muslim remembers him as the companion bound to the Prophet ﷺ by blood, by marriage and by faith.",

"sira_299": "Every standard biography records that when the Prophet ﷺ arrived in Medina after the emigration, one of the first things he did was to build a mosque, working beside his companions. From this mosque he led the five prayers, taught the Qur'an and received delegations, and when he died he was buried in the room of 'A'isha that opened onto it. Sahih al-Bukhari and Sahih Muslim record his words that a prayer in his mosque is better than a thousand prayers anywhere else, except al-Masjid al-Haram. A Muslim who visits Medina prays there and sends his greeting of peace to the Prophet ﷺ.",

"sira_300": "The Qur'an tells of the journey itself: \"Exalted is He who took His servant by night from al-Masjid al-Haram to al-Masjid al-Aqsa, whose surroundings We have blessed, to show him of Our signs\" (17:1). The account of the night journey in Sahih Muslim, in the words of Anas ibn Malik, gives the mount its name: the Prophet ﷺ said that al-Buraq was brought to him, a white animal larger than a donkey and smaller than a mule, which set its hoof down as far as its eye could see, and that he rode it to Bayt al-Maqdis. The name comes from the Arabic word for lightning. A Muslim learns that the night journey was a real journey, with a real mount, granted by Allah to His Prophet ﷺ.",

"faith_151": "Ibn 'Umar reports in Sahih al-Bukhari 8 that the Prophet ﷺ named the five: the testimony that there is no god but Allah and that Muhammad is the Messenger of Allah, establishing the prayer, giving the zakat, the pilgrimage, and fasting Ramadan. The Qur'an speaks of each of them: prayer and zakat together, \"establish prayer and give zakat\" (2:43); fasting, \"decreed upon you is fasting\" (2:183); and the pilgrimage owed to Allah by whoever can make the journey (3:97). The word pillar is used because a house cannot stand if one of its supports is missing. A Muslim learns the five as one whole, not as a list to choose from.",

"faith_152": "The shahada is spoken in Arabic: la ilaha illa Allah, Muhammadun rasul Allah. Its two halves are both in the Qur'an: \"So know that there is no god but Allah\" (47:19) and \"Muhammad is the Messenger of Allah\" (48:29). In Sahih al-Bukhari 8 the Prophet ﷺ names it first among the five pillars, and every Muslim repeats it in the sitting of every prayer, in the call to prayer, and as the words a person says to enter Islam. A Muslim learns that the whole religion begins with these two sentences: one Lord to worship, and one messenger to follow.",

"faith_153": "Every Muslim performs the same five: Fajr before sunrise, Dhuhr after midday, 'Asr in the afternoon, Maghrib just after sunset and 'Isha at night. The Qur'an says: \"Indeed, prayer has been decreed upon the believers at fixed times\" (4:103), and: \"Establish prayer from the decline of the sun until the darkness of the night, and the recitation of dawn\" (17:78). Sahih al-Bukhari and Sahih Muslim record, in the hadith of the night journey, that the prayers were first made fifty and then reduced to five, with the reward of fifty kept. A Muslim learns that the day is shaped around five meetings with his Lord.",

"faith_154": "The whole verse says: \"The month of Ramadan, in which the Qur'an was sent down as guidance for the people and clear proofs of guidance and the criterion. So whoever of you witnesses the month, let him fast it; and whoever is ill or on a journey, then an equal number of other days. Allah wants ease for you and does not want hardship for you\" (2:185). Two verses earlier fasting is made a duty, as it was for the nations before (2:183). The month is named because the Qur'an came down in it. A Muslim learns that Ramadan is the month of the Book as much as the month of fasting.",

"faith_155": "The word zakat means purification and growth, and the Qur'an joins it to prayer again and again: \"Establish prayer and give zakat\" (2:43). It also says who receives it: \"Charity is only for the poor and the needy and those who work on it\" and the other groups the verse names (9:60). The Prophet ﷺ was told: \"Take from their wealth a charity by which you purify them\" (9:103). In Sahih al-Bukhari 8 it is counted among the five pillars of Islam. A Muslim learns that giving a share of what he owns makes the rest clean, and that the poor have a right in his wealth.",

"faith_156": "The Qur'an makes the duty plain: \"And due to Allah from the people is a pilgrimage to the House, for whoever is able to find a way to it\" (3:97). It also tells how the call began, when Ibrahim was commanded: \"Proclaim to the people the pilgrimage; they will come to you on foot and on every lean camel, coming from every distant pass\" (22:27). Pilgrims wear simple white clothing, circle the Ka'ba, walk between Safa and Marwa, which the Qur'an counts among the symbols of Allah (2:158), and stand at 'Arafat (2:198). A Muslim who can travel makes the journey once in his life, answering Ibrahim's call.",

"faith_157": "The six are named by the Prophet ﷺ himself in the hadith of Jibril, reported by 'Umar in Sahih Muslim 8: when Jibril came in the form of a man and asked him about iman, he answered that it is to believe in Allah, His angels, His books, His messengers, the Last Day, and in destiny, its good and its bad. The Qur'an lists most of them in one verse: \"The Messenger has believed in what was sent down to him from his Lord, and so have the believers; all of them believe in Allah, His angels, His books and His messengers\" (2:285). A Muslim learns the six as the beliefs that stand behind the five pillars.",

"faith_158": "The surah has only four verses: \"Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, and there is none equal to Him\" (112:1-4). It is called Al-Ikhlas, sincerity, because it speaks of nothing but Allah alone. Sahih al-Bukhari records the Prophet ﷺ saying that this surah equals a third of the Qur'an. Every other verse of the Qur'an that speaks of Allah agrees with it: \"Your God is one God; there is no god but Him\" (2:163). A Muslim learns the surah by heart as a small child and recites it in prayer, and with it the whole of his belief about Allah.",

"faith_159": "The name appears in the very first line of the Qur'an, \"In the name of Allah, the Entirely Merciful, the Especially Merciful\" (1:1), and Allah uses it of Himself when He speaks to Musa: \"Indeed, I am Allah; there is no god but Me, so worship Me\" (20:14). The Qur'an also asks: \"Do you know of anyone who shares His name?\" (19:65), for no one else has ever been called Allah. All His other names are named as belonging to Him: \"To Allah belong the most beautiful names\" (7:180). A Muslim learns that Allah is not a title but a name, His own, in every language Muslims speak.",

"faith_160": "The Qur'an speaks of itself: \"This is the Book about which there is no doubt, a guidance for those mindful of Allah\" (2:2), and tells how it came: \"The Trustworthy Spirit brought it down upon your heart, in a clear Arabic tongue\" (26:193-195). Its name means the recitation, and the first word revealed of it was a command to read (96:1). It was sent down over the years of the Prophet's ﷺ mission, and Allah promised to guard it: \"Indeed, it is We who sent down the Reminder, and We are its guardian\" (15:9). A Muslim learns the Qur'an as the words of Allah, kept unchanged since they were revealed.",

"faith_161": "The verse continues: \"the first House established for mankind is the one at Bakka, blessed and a guidance for the worlds; in it are clear signs, the standing place of Ibrahim, and whoever enters it is safe\" (3:96-97). Bakka is Makka, and the Qur'an tells who raised the walls: \"When Ibrahim was raising the foundations of the House, with Isma'il: our Lord, accept it from us\" (2:127). Muslims everywhere turn towards it in prayer, as they were told: \"Turn your face towards al-Masjid al-Haram\" (2:144). A Muslim learns that the Ka'ba is not worshipped; it is the direction of worship and the House Ibrahim built for Allah alone.",

"faith_162": "'Umar ibn Abi Salama tells the story himself in Sahih al-Bukhari 5376: he was a boy living in the Prophet's ﷺ house, and at meals his hand wandered all over the dish, so the Prophet ﷺ said to him, \"Boy, say the name of Allah, eat with your right hand, and eat from what is nearest to you.\" He adds that this remained his way of eating ever after. The Qur'an tells the believers to \"eat of the good things We have provided you and be grateful to Allah\" (2:172). A Muslim learns table manners as a child from the Prophet's ﷺ own words: Allah's name first, the right hand, and the food in front of you.",

"faith_163": "The greeting is in Arabic, as-salamu 'alaykum, and it is what the angels say to the people of Paradise: \"Peace be upon you for what you patiently endured\" (13:24). The Qur'an tells the believers: \"When you enter houses, greet one another with a greeting from Allah, blessed and good\" (24:61). Sahih Muslim records the Prophet ﷺ saying that the believers will not enter Paradise until they believe, and will not believe until they love one another, and that spreading the salam among themselves is the way to that love. A Muslim learns that his greeting is a prayer for the other person's safety.",

"faith_164": "The Qur'an sets the rule for every greeting: \"When you are greeted with a greeting, greet with one better than it, or return it\" (4:86). So the reply to as-salamu 'alaykum is wa 'alaykum as-salam, and the better reply adds wa rahmatullahi wa barakatuh, and the mercy of Allah and His blessings. The verse ends: \"Indeed, Allah keeps account of everything\" (4:86), so even a greeting is counted. A Muslim learns to answer every salam he hears, and to add to it when he can.",

"faith_165": "The festival's name means the breaking of the fast, and it comes on the first day of the month after Ramadan, Shawwal. The Qur'an, after commanding the fast, says why the month ends in thanks: \"so that you complete the number and glorify Allah for having guided you, and that you may be grateful\" (2:185). On the morning of 'Id Muslims give a small charity of food to the poor before the prayer, then gather for the 'Id prayer and visit one another. Sahih al-Bukhari records the Prophet ﷺ saying that every people has its festival and that this is ours. A Muslim learns that the end of a hard month is met with gratitude and sharing.",

"faith_166": "The festival's name means the sacrifice, and it falls on the tenth day of Dhu al-Hijja, when the pilgrims at Mina offer their animals and Muslims everywhere do the same. It recalls Ibrahim, who was ready to sacrifice his son when Allah commanded it in a dream, until Allah called to him: \"O Ibrahim, you have fulfilled the vision,\" and \"We ransomed him with a great sacrifice\" (37:104-107). The Qur'an also says what the offering is for: \"Their meat will not reach Allah, nor their blood, but what reaches Him is your piety\" (22:37). A Muslim learns that the meat is shared with family and the poor, and that the real gift is obedience.",

"faith_167": "The Qur'an describes the angels with these words: \"They do not disobey Allah in what He commands them, and they do what they are commanded\" (66:6), and again: \"Those who are near Him are not too proud to worship Him, nor do they tire; they glorify Him night and day and never slacken\" (21:19-20). They are made by Allah and sent as His messengers, with wings, two, three and four (35:1). Jibril is the angel who brought the Qur'an down to the Prophet's ﷺ heart (2:97). A Muslim learns to believe in beings he cannot see, whose whole life is obedience to Allah.",

"faith_168": "The Qur'an calls it a garden because it is full of trees and water: \"gardens beneath which rivers flow\" (2:25) is its most frequent description. It is \"as wide as the heavens and the earth, prepared for the God-fearing\" (3:133), and those who enter hear: \"Enter it in peace, safe\" (15:46). Sahih al-Bukhari and Sahih Muslim record the Prophet ﷺ saying that Allah has prepared for His righteous servants what no eye has seen, no ear has heard, and no human heart has imagined. A Muslim learns to work for a home whose beauty is beyond anything in this world.",

"faith_169": "The Qur'an itself gives the steps: \"O you who believe, when you rise for prayer, wash your faces and your hands up to the elbows, wipe your heads, and wash your feet up to the ankles\" (5:6). The same verse says that Allah does not want to make things hard for you, but wants to purify you and complete His favour upon you. Sahih al-Bukhari records the Prophet ﷺ saying that the prayer of one who has lost his purity is not accepted until he performs wudu'. A Muslim learns that he comes to speak with his Lord clean, and that the water on his face and hands is the first part of the prayer.",

"faith_170": "The word rak'ah comes from ruku', the bowing, and the Qur'an calls the believers \"those who bow and those who prostrate\" (9:112) and commands: \"O you who believe, bow and prostrate and worship your Lord\" (22:77). One rak'ah runs in this order: standing with the recitation of al-Fatiha, bowing, standing again, prostrating, sitting, prostrating again. Every Muslim counts the prayers by their rak'ahs: Fajr has two, Maghrib three, and Dhuhr, 'Asr and 'Isha four each. A Muslim learns the rak'ah as the building block of the whole prayer, repeated the same way every day.",

"faith_171": "'Ubada ibn as-Samit reports in Sahih al-Bukhari that the Prophet ﷺ said there is no prayer for one who does not recite the Opening of the Book. The Prophet ﷺ also called it, in Sahih al-Bukhari, the \"seven of the oft-repeated\" spoken of in the Qur'an (15:87), and it is repeated at least seventeen times a day across the five prayers. Its seven verses praise Allah, Lord of the worlds, name Him Merciful and Master of the Day of Judgement, and then ask Him: \"You alone we worship and You alone we ask for help; guide us to the straight path\" (1:5-6). A Muslim learns al-Fatiha first of all the surahs, because without it the prayer cannot be made.",

"faith_172": "The Qur'an uses the word in its commands about food: \"O mankind, eat of what is on the earth, lawful and good\" (2:168), and: \"Eat of what Allah has provided you, lawful and good, and be grateful for the favour of Allah\" (16:114). It also describes the Prophet ﷺ as one who \"makes lawful for them the good things and forbids them the bad\" (7:157). Sahih al-Bukhari and Sahih Muslim record him saying that the halal is clear and the haram is clear. A Muslim learns that what Allah has allowed is wide and good, and that eating it with thanks is itself an act of worship.",

"faith_173": "The same root gives al-Masjid al-Haram, the sacred mosque, for haram first means what is set apart and not to be touched. The Qur'an tells the Prophet ﷺ: \"Say: my Lord has only forbidden shameful deeds, open and hidden, and sin, and wrongful oppression, and that you associate with Allah what He has sent no authority for, and that you say about Allah what you do not know\" (7:33). It also warns against calling things forbidden by one's own tongue: \"Do not say, about what your tongues falsely describe, this is lawful and this is unlawful\" (16:116). A Muslim learns that only Allah decides what is haram, and that the list is short beside all that He permits.",

"faith_174": "The verse reads in full: \"He has only forbidden you carrion, blood, the flesh of swine, and what has been offered to other than Allah; but whoever is forced by need, without desiring it or going too far, there is no sin on him; indeed Allah is Forgiving and Merciful\" (2:173). The verse before it opens with the wide permission: \"O you who believe, eat of the good things We have provided you and be grateful to Allah\" (2:172). The same four things are forbidden again in 5:3, 6:145 and 16:115. A Muslim learns that the rule is clear and small, and that Allah lifts it for someone who has nothing else to eat.",

"faith_175": "The verse gives a list and a reason: \"O you who believe, intoxicants, gambling, sacrificing at altars and divining arrows are only filth from the work of Satan, so avoid it that you may succeed\" (5:90). The next verse explains what wine does: Satan uses it and gambling \"to sow enmity and hatred among you and to keep you from the remembrance of Allah and from prayer; so will you not stop?\" (5:91). The Arabic word khamr covers every drink that clouds the mind, and Sahih Muslim records the Prophet ﷺ saying that every intoxicant is khamr and every intoxicant is forbidden. A Muslim learns that the mind is a trust, kept clear for remembering Allah.",

"faith_176": "Abu Hurayra reports in Sahih al-Bukhari 6224 the whole exchange: when one of you sneezes, let him say al-hamdu lillah; let his brother or companion answer yarhamuk Allah, may Allah have mercy on you; and let the one who sneezed reply yahdikum Allah wa yuslih balakum, may Allah guide you and set your affairs right. So a sneeze becomes three short prayers passed between two people. The words al-hamdu lillah are the same that open al-Fatiha: \"Praise be to Allah, Lord of the worlds\" (1:2). A Muslim learns to thank Allah even for the small relief of a sneeze, and to answer with a prayer for the one beside him.",

"faith_177": "The word salat is the Qur'an's own word, used every time prayer is commanded; Allah says to Musa: \"Establish the prayer for My remembrance\" (20:14). The Qur'an tells what it does for the one who prays: \"Indeed, the prayer keeps one away from shameful and wrong deeds, and the remembrance of Allah is greater\" (29:45), and it names it beside patience as the believer's help: \"Seek help through patience and prayer\" (2:45). The call to prayer itself uses the word: hayya 'ala as-salah, come to the prayer. A Muslim learns that as-salat is a fixed prayer with set words and movements, different from the free asking of du'a.",

"faith_178": "The Qur'an says the invitation comes from Allah Himself: \"Your Lord says: call upon Me, I will answer you\" (40:60), and: \"When My servants ask you about Me, indeed I am near; I answer the call of the caller when he calls on Me\" (2:186). The prophets prayed this way: Ibrahim asked, \"My Lord, make me one who establishes prayer, and of my descendants too\" (14:40), and Zakariyya called on his Lord in a low voice for a son (19:3-4). Du'a needs no set words, no set time and no set place, only a heart turned to Allah. A Muslim learns to speak to his Lord in his own language about his own needs, sure that he is heard.",

"faith_179": "Al-Fatiha opens: \"In the name of Allah, the Entirely Merciful, the Especially Merciful. Praise be to Allah, Lord of the worlds, the Entirely Merciful, the Especially Merciful, Master of the Day of Judgement\" (1:1-4). Hamd is praise given with love and thanks, and the second verse (1:2) gives it to Allah because He is Lord of every world there is. The same words open four other surahs, Al-An'am, Al-Kahf, Saba and Fatir, and the Qur'an says they are the last words of the people of Paradise: \"the end of their call is: praise be to Allah, Lord of the worlds\" (10:10). A Muslim says al-hamdu lillah after eating, after sneezing and when good news comes, and hears it in every rak'ah.",

"faith_180": "The root of the word gives salam, peace, and aslama, to hand oneself over. The Qur'an shows Ibrahim doing exactly that: \"When his Lord said to him: submit, he said: I have submitted to the Lord of the worlds\" (2:131). Allah names the religion with this word: \"Indeed, the religion with Allah is Islam\" (3:19), and during the Prophet's ﷺ pilgrimage the verse came down: \"This day I have perfected your religion for you, completed My favour upon you, and chosen Islam for you as religion\" (5:3). A Muslim learns that islam is not a name Muslims invented but the word Allah chose, meaning to give oneself to Him and find peace in it.",

"faith_181": "The Qur'an says who gave the name: \"It is He who named you Muslims, before and in this\" (22:78). Ibrahim and Isma'il prayed with the word while building the Ka'ba: \"Our Lord, make us both submitting to You, and of our descendants a nation submitting to You\" (2:128), and Ya'qub told his sons: \"Allah has chosen the religion for you, so do not die except as Muslims\" (2:132). The Qur'an says of Ibrahim that \"he was not a Jew nor a Christian, but he was upright, a Muslim\" (3:67). A Muslim learns that his name links him to every prophet who gave himself to Allah, long before the Prophet ﷺ was born.",

"faith_182": "The surah opens with praise and its reason: \"Praise be to Allah, who created the heavens and the earth and made the darkness and the light; yet those who disbelieve set up equals to their Lord\" (6:1). The next verse turns to the human being: \"It is He who created you from clay, then decreed a term\" (6:2). Elsewhere the Qur'an says that He created the heavens and the earth in six days and then rose over the Throne (7:54), and that He has no partner in His dominion (25:2). A Muslim learns to look at the sky, the earth, night and day, and to answer each one with the words that open Surah Al-An'am.",

"faith_183": "Abu Hurayra reports in Sahih al-Bukhari 2736 that the Prophet ﷺ said Allah has ninety-nine names, one hundred less one, and that whoever learns them all by heart will enter Paradise. The Qur'an is where the names are found: \"To Allah belong the most beautiful names, so call on Him by them\" (7:180), and one passage alone gathers many of them: the King, the Holy, the Peace, the Creator, the Maker, the Fashioner (59:23-24). Learning them is not counting but knowing whom one worships. A Muslim learns the names from the Qur'an and calls on Allah by the one that fits his need: the Forgiving when he has erred, the Provider when he is in want.",

"faith_184": "The verse names the angels \"noble and writing\" (82:11), and the verses around it complete the picture: \"Indeed, over you are keepers\" (82:10), \"they know whatever you do\" (82:12). They come in Surah Al-Infitar, just after Allah asks: \"O man, what has deceived you about your generous Lord?\" (82:6), and just before the surah says that the righteous will be in bliss and the wicked in the Fire (82:13-14). Surah Qaf tells where the two angels sit and how closely they listen: \"seated on the right and on the left; he utters no word without a watcher ready beside him\" (50:17-18). A Muslim learns that nothing he says or does is lost, and that his own record will be shown to him.",

"faith_185": "The surah is only five verses: \"Indeed, We sent it down on the Night of Decree. And what will make you know what the Night of Decree is? The Night of Decree is better than a thousand months. The angels and the Spirit come down in it, by permission of their Lord, with every matter. Peace it is, until the rising of dawn\" (97:1-5). The heart of the surah is its third verse (97:3), and what was sent down is the Qur'an, and Surah Al-Baqara places that sending in Ramadan (2:185), so the night is in that month. Sahih al-Bukhari records the Prophet ﷺ telling the believers to seek it in the odd nights of the last ten of Ramadan. A Muslim spends those nights in prayer, hoping to meet one night worth more than a thousand months.",

"faith_186": "The word comes from wahid, one, and means making Allah one: worshipping Him alone, with no partner. The Qur'an says every messenger was sent with this: \"We sent no messenger before you without revealing to him: there is no god but Me, so worship Me\" (21:25), and: \"We sent to every nation a messenger, saying: worship Allah and shun false gods\" (16:36). Its shortest statement is Surah Al-Ikhlas, \"Say: He is Allah, the One\" (112:1), and its daily statement is the first half of the shahada. A Muslim learns that tawhid is the one message Nuh, Ibrahim, Musa, 'Isa and Muhammad ﷺ all shared.",

"faith_187": "The word means making a partner, and the Qur'an treats it as the one wrong Allah says He does not forgive: \"Indeed, Allah does not forgive that partners be associated with Him, but forgives what is less than that for whom He wills\" (4:48). The wise man Luqman gave his son this as his first lesson: \"O my son, do not associate anything with Allah; indeed, association is a great injustice\" (31:13). The command is put simply elsewhere: \"Worship Allah and associate nothing with Him\" (4:36). A Muslim learns to keep every act of worship, prayer, du'a, sacrifice and trust, for Allah alone.",

"faith_188": "The Qur'an swears by that Day: \"I swear by the Day of Resurrection\" (75:1), and gives it other names too: the Day of Judgement, the Hour, the Day of Reckoning. It tells what happens: \"That Day people will come forward in separate groups to be shown their deeds. Whoever does an atom's weight of good will see it, and whoever does an atom's weight of evil will see it\" (99:6-8). The scales will be set up so that no soul is wronged in anything (21:47). Every Muslim names it in each rak'ah, when al-Fatiha calls Allah \"Master of the Day of Judgement\" (1:4). A Muslim learns to live as one who will be shown his deeds.",

"faith_189": "The verse says: \"Indeed, the number of months with Allah is twelve months, in the decree of Allah from the day He created the heavens and the earth; of them, four are sacred\" (9:36). The Muslim months follow the moon: the Qur'an says the crescents are \"measures of time for the people and for the pilgrimage\" (2:189), and that Allah made the moon's stages \"so that you may know the number of years and the reckoning\" (10:5). Ramadan is the ninth of the twelve, and Dhu al-Hijja, the month of the pilgrimage, is the last. A Muslim learns that his calendar is counted by the new moon, and that four of its months carry a special sanctity.",

"faith_190": "Every Muslim prays the same way: after bowing and standing straight again, he goes down to the ground, sits up, and goes down a second time before rising or sitting for the tashahhud. Sahih al-Bukhari records the Prophet ﷺ saying that he was commanded to prostrate on seven bones: the forehead with the nose, the two hands, the two knees and the toes of the two feet. The Qur'an closes Surah Al-'Alaq with the command: \"Prostrate and draw near\" (96:19), and Sahih Muslim records the Prophet ﷺ saying that a servant is nearest to his Lord when he is prostrating, so he should make much du'a there. A Muslim learns that the two prostrations are the closest moments of the prayer.",
}
