"""English — details, beginner_1 (50 questions)."""

D = {
"prophets_251": "The Qur'an itself gives the Prophet's ﷺ name: \"Muhammad is the Messenger of Allah\" (48:29), and again: \"Muhammad is not the father of any of your men, but the Messenger of Allah and the seal of the prophets\" (33:40). His name and lineage open every standard biography, and every Muslim says his name each day in the testimony of faith. A Muslim learns the name of the man who brought him the Qur'an, and honours it whenever it is spoken.",

"prophets_252": "These words close a long prayer Ibrahim makes near the end of Surah Ibrahim, after settling his family in a valley without crops beside the Sacred House (14:37). He says: \"Praise be to Allah, who has granted me in old age Isma'il and Ishaq. Indeed, my Lord is the Hearer of supplication\" (14:39), then asks that he and his descendants keep up the prayer (14:40). Both sons are named in one breath, as gifts received late in life. A Muslim learns to thank Allah for children as a gift, not as something owed.",

"prophets_253": "The verse answers a false claim recorded just before it. Surah An-Nisa' reports the boast of those who said they had killed the Messiah, 'Isa son of Maryam, and replies: \"They did not kill him, nor did they crucify him, but it was made to appear so to them\" (4:157). Then comes the truth: \"Rather, Allah raised him to Himself. And Allah is ever Mighty and Wise\" (4:158). A Muslim learns that 'Isa was not killed, that Allah protected His messenger, and that no scheme can defeat His plan.",

"prophets_254": "Surah Maryam tells her story: \"And mention in the Book Maryam, when she withdrew from her family to a place toward the east\" (19:16). Allah sent His Spirit to her in the form of a man; she sought refuge in the Most Merciful from him, and he said he was only a messenger of her Lord, come to give her a pure boy (19:17-19). When she asked how, since no man had touched her, he answered: \"Your Lord says: it is easy for Me\" (19:21). A Muslim learns that 'Isa was born by Allah's command alone, and honours Maryam as his mother.",

"prophets_255": "Before Adam was created, Allah told the angels: \"I am placing upon the earth a successor\" (2:30). Then \"He taught Adam the names, all of them\" (2:31), showed the angels that this new creature knew what they did not, and commanded them to prostrate to him (2:34). The Qur'an later addresses all people as \"children of Adam\" (7:26), and reminds them that Allah \"created you from one soul\" (4:1). A Muslim learns that every human being on earth descends from this one first man, honoured with knowledge by his Creator.",

"prophets_256": "Surah Al-Anbiya tells how young Ibrahim broke his people's idols, left the largest one standing, and told them to ask it if it could speak (21:58-63). Their answer was fire: \"Burn him and support your gods, if you are going to act\" (21:68). Allah then commanded: \"O fire, be coolness and peace upon Ibrahim\" (21:69), and the next verse says that they plotted against him, but Allah made them the greatest losers (21:70). A Muslim learns that fire burns only by Allah's permission, and that He protects whoever stands for the truth.",

"prophets_257": "Allah asked Musa this question in the sacred valley of Tuwa, where He first spoke to him (20:12-13): \"And what is that in your right hand, O Musa?\" (20:17). Musa answered: \"It is my staff; I lean on it, and I bring down leaves with it for my sheep\" (20:18). Allah said, \"Throw it down,\" and it became a snake moving swiftly; then He told him to take it and not fear, and it returned to its former state (20:19-21). A Muslim learns that Allah can turn an ordinary shepherd's stick into a sign for a prophet.",

"prophets_258": "Surah Yusuf opens with the boy telling his father: \"O my father, indeed I saw eleven stars and the sun and the moon; I saw them prostrating to me\" (12:4). His father Ya'qub told him not to tell his brothers, lest they plot against him, for Satan is a clear enemy to man (12:5). Long after, when his parents and brothers bowed before him in Egypt, Yusuf said: \"This is the explanation of my vision of before; my Lord has made it true\" (12:100). A Muslim learns that what Allah shows may take long years and hard trials before it comes true.",

"prophets_259": "Sulayman had looked over the birds and asked why the hoopoe was missing, threatening to punish it unless it brought a clear excuse (27:20-21). It came back with news: \"I have learned something you have not learned, and I have come to you from Saba' with sure news\" (27:22). It had found a woman ruling there with a great throne, and her people prostrating to the sun instead of Allah (27:23-24). Sulayman said he would test whether the bird had told the truth, and sent it back with a letter (27:27-28). A Muslim learns that a report is checked before it is acted on.",

"prophets_260": "The verse reads: \"And remember Our servant Ayyub, when he called to his Lord: Satan has touched me with hardship and pain\" (38:41). Allah answered him at once: \"Strike the ground with your foot; here is a cool spring to wash in and to drink\" (38:42), and gave him back his family and as many again with them (38:43). Then the Qur'an gives its judgement: \"Indeed, We found him patient. An excellent servant; he was ever turning back to Allah\" (38:44). A Muslim learns that patience does not mean silence before Allah: Ayyub endured, and he also asked.",

"prophets_261": "The verse compares two prophets: \"Indeed, the likeness of 'Isa before Allah is as the likeness of Adam. He created him from dust, then said to him, Be, and he was\" (3:59). It closes the account of Maryam and the birth of 'Isa in Surah Al 'Imran, and the next verse adds: \"The truth is from your Lord, so do not be among the doubters\" (3:60). Elsewhere the Qur'an says of all people: \"He created you from dust, and then you were human beings, spreading out\" (30:20). A Muslim learns that dust came alive by one word of Allah, so no one has reason for pride.",

"prophets_262": "The verse comes in a list of messengers: \"And messengers We have already told you about, and messengers We have not told you about. And Allah spoke to Musa with direct speech\" (4:164). Surah Ta-Ha records that speech in the sacred valley: \"Indeed, I am your Lord, so take off your sandals; you are in the sacred valley of Tuwa. And I have chosen you, so listen to what is revealed\" (20:12-13). Later Allah told him: \"I have chosen you above the people with My messages and My words\" (7:144). A Muslim learns that Musa received a special honour among the messengers.",

"prophets_263": "The Qur'an states this article of faith in one verse: \"Muhammad is not the father of any of your men, but the Messenger of Allah and the seal of the prophets\" (33:40). A seal is what closes a letter; nothing is added after it. He was also sent not to one town but to everyone: \"Say: O mankind, indeed I am the Messenger of Allah to you all\" (7:158). Every standard biography and every Muslim creed teaches this closing of prophethood. A Muslim learns that the guidance he needs was completed with this last prophet, and that no new prophet will come after him.",

"prophets_264": "The verse that gives the title is in Surah An-Nisa': \"And who is better in religion than one who submits his face to Allah, does good, and follows the way of Ibrahim, inclining to truth? And Allah took Ibrahim as an intimate friend\" (4:125). Surah Al-Baqarah then shows what Muslims say of him: \"We believe in Allah and what was revealed to us, and what was revealed to Ibrahim, Isma'il, Ishaq, Ya'qub and the Descendants\" (2:136). Ibrahim heads that line of prophets. A Muslim learns that closeness to Allah comes from submitting to Him and doing good, as Ibrahim did.",

"prophets_265": "The verse belongs to a speech Allah will make on the Day of Judgement, listing His favours: \"O 'Isa, son of Maryam, remember My favour upon you and your mother, when I supported you with the Pure Spirit, and you spoke to people in the cradle and in maturity\" (5:110). It goes on: he shaped a bird from clay and it became a bird by Allah's permission, he healed the blind from birth and the leper by His permission, and he brought forth the dead by His permission (5:110). A Muslim learns that 'Isa's miracles were real and were Allah's, worked through His servant.",

"prophets_266": "The verse reads: \"And We certainly gave Dawud bounty from Us: O mountains, repeat praises with him, and the birds too. And We made iron soft for him\" (34:10). The next verse tells him what to do with that iron: make full coats of mail, measure the links well, and do good, for Allah sees what he does (34:11). Surah Sad adds that the mountains glorified with him in the evening and after sunrise, and the birds gathered around him (38:18-19). A Muslim learns that praising Allah joins a person to the whole creation, which praises Him too.",

"prophets_267": "The king of Egypt had seen seven fat cows eaten by seven lean ones, and seven green ears of grain with others dry, and his court called it a jumble of dreams (12:43-44). The man freed from prison remembered Yusuf and went to him: \"Yusuf, O man of truth, explain to us\" (12:46). Yusuf answered: seven years of steady planting, leaving the grain in its ears; then seven hard years that would eat up what was stored; then a year of rain and plenty (12:47-49). A Muslim learns that knowledge from Allah is used to help people, even those who left him forgotten in prison.",

"prophets_268": "The brothers' words open the trouble: \"Yusuf and his brother are dearer to our father than we are, though we are a group. Indeed, our father is in clear error\" (12:8). Surah Yusuf names this father earlier, when he promises the boy that Allah will complete His favour \"upon you and upon the family of Ya'qub, as He completed it upon your two forefathers before, Ibrahim and Ishaq\" (12:6). When his sons brought him Yusuf's shirt with false blood, he answered: \"So beautiful patience\" (12:18). A Muslim learns from this father that patience, not anger, is the answer to a great loss.",

"prophets_269": "The verse is one of the favours Allah reminds the Children of Israel of: \"And when We parted the sea for you and saved you and drowned the people of Pharaoh while you were looking on\" (2:50). Surah Ash-Shu'ara tells the moment itself: with Pharaoh's army behind them, Musa's companions cried that they were caught, and he answered, \"No! Indeed, with me is my Lord; He will guide me\" (26:61-62). Then Allah commanded, \"Strike the sea with your staff,\" and it split, each side like a great mountain (26:63). A Muslim learns that when every way seems closed, Allah can open one.",

"prophets_270": "The practice comes from a verse of Surah Al-Ahzab: \"Indeed, Allah and His angels send blessings upon the Prophet. O you who believe, send blessings upon him and greet him with peace\" (33:56). So when a Muslim says salla-Llahu 'alayhi wa sallam, he is doing exactly what this verse asks: joining Allah and His angels in honouring the Prophet ﷺ. Muslims also send blessings on him in the sitting at the end of every prayer. A Muslim learns to answer the Prophet's ﷺ name with a prayer for him, in thanks for the guidance he brought.",

"prophets_271": "The surah named after him begins: \"Indeed, We sent Nuh to his people: warn your people before a painful punishment comes to them\" (71:1). He told them plainly: worship Allah, fear Him, and obey me (71:3). Then he complained to his Lord: \"My Lord, I called my people night and day, but my calling only made them run further away\" (71:5-6); they put their fingers in their ears and wrapped themselves in their garments (71:7). Surah Al-'Ankabut gives the length: a thousand years less fifty (29:14). A Muslim learns that a caller to Allah keeps going, and leaves the result to Allah.",

"prophets_272": "Surah Sad names the father and the son in one line: \"And to Dawud We gave Sulayman. What an excellent servant; indeed, he was ever turning back to Allah\" (38:30). Notice what is praised: not the throne he would have, but his character as a servant who kept returning to his Lord. Surah An-Naml says he inherited from Dawud and told the people: \"We have been taught the speech of birds, and we have been given of all things\" (27:16). A Muslim learns that the best praise of a king is that he was a good servant of Allah.",

"prophets_273": "The verse closes the story of Talut's army: \"So they defeated them by Allah's permission, and Dawud killed Jalut, and Allah gave him kingship and wisdom and taught him what He willed\" (2:251). Just before, the few who stayed firm had said: \"How many a small company has overcome a large company by Allah's permission; and Allah is with the patient\" (2:249), and they prayed for patience, firm feet and victory (2:250). Dawud, one of that small company, became a king and a prophet. A Muslim learns that victory comes from Allah to the patient, not from numbers.",

"prophets_274": "The Qur'an puts this belief in the mouth of every believer: \"The Messenger has believed in what was sent down to him from his Lord, and so have the believers. All of them believe in Allah, His angels, His books and His messengers: We make no distinction between any of His messengers\" (2:285). It also says that not all of them are named: \"messengers We have told you about, and messengers We have not told you about\" (40:78). A Muslim learns to honour the prophets he knows by name and those he does not, as one family sent by one Lord.",

"prophets_275": "The verse reads: \"Indeed, Allah chose Adam and Nuh and the family of Ibrahim and the family of 'Imran over the worlds, descendants one of another\" (3:33-34). The next verse shows why the family of 'Imran is named: the wife of 'Imran prayed, \"My Lord, I have dedicated to You what is in my womb\" (3:35), and the child was Maryam, mother of 'Isa (3:36). So the verse names the first man, the prophet of the flood, the father of many prophets and the family of the Messiah. A Muslim learns that Allah chooses whom He wills, and that the prophets come from one line.",

"prophets_276": "The name of the land is spoken by Yusuf himself when his family arrives: \"Enter Egypt, if Allah wills, safe and secure\" (12:99). He had asked the king, \"Appoint me over the storehouses of the land; I am a knowing guardian\" (12:55), and the Qur'an says: \"Thus We established Yusuf in the land\" (12:56). At the reunion he raised his parents on the throne and said that Allah had been good to him when He took him out of prison and brought them from the desert (12:100). A Muslim learns that the boy thrown into a well was raised by Allah to honour in a foreign land.",

"prophets_277": "Surah Al-Isra opens with this journey: \"Exalted is He who took His servant by night from the Sacred Mosque to the Farthest Mosque, whose surroundings We have blessed, to show him of Our signs\" (17:1). The Sacred Mosque is in Makkah, where the Prophet ﷺ lived, and the Farthest Mosque is Al-Aqsa. At the moment of his greatest honour the Qur'an calls him simply \"His servant\". The next verse turns to Musa and the Book he was given (17:2). A Muslim learns that Al-Aqsa is a blessed place tied to his Prophet ﷺ, and that the highest title of a man is servant of Allah.",

"prophets_278": "The verse reads: \"And We gave Musa the Book, and We sent messengers after him, following one another\" (2:87), and it goes on to name 'Isa, son of Maryam, given clear proofs and supported by the Pure Spirit. The Book given to Musa is named elsewhere: \"Indeed, We sent down the Torah, in which was guidance and light\" (5:44), and Surah Al 'Imran says Allah \"sent down the Torah and the Gospel before, as guidance for the people\" (3:3-4). A Muslim learns that the Torah was a true revelation from Allah to Musa, and that believing in the earlier books is part of his faith.",

"prophets_279": "The verse reads: \"And We sent, following in their footsteps, 'Isa son of Maryam, confirming the Torah that came before him; and We gave him the Gospel, in which was guidance and light\" (5:46). Two verses earlier the Torah is described with the same words, guidance and light (5:44), and two verses later Allah tells the Prophet ﷺ that the Qur'an was sent \"confirming the Scripture that came before it\" (5:48). Torah, Gospel and Qur'an are thus one chain from one Sender. A Muslim learns that 'Isa came with a true book, and believes in it as Allah revealed it.",

"prophets_280": "The verse is a long list of those Allah sent revelation to: \"We have revealed to you as We revealed to Nuh and the prophets after him; and We revealed to Ibrahim, Isma'il, Ishaq, Ya'qub and the Descendants, and 'Isa, Ayyub, Yunus, Harun and Sulayman; and to Dawud We gave the Zabur\" (4:163). Surah Al-Isra repeats the gift in the same words (17:55), and Surah Al-Anbiya quotes a line from it: \"the earth will be inherited by My righteous servants\" (21:105). A Muslim learns that Dawud was both a king and a prophet with a book named in the Qur'an.",

"prophets_281": "Ibrahim had prayed for a righteous child and was given good news of a forbearing boy (37:100-101). Then: \"When the boy was old enough to work with him, he said: O my son, I have seen in a dream that I sacrifice you, so see what you think. He said: O my father, do as you are commanded; you will find me, if Allah wills, among the patient\" (37:102). When both had submitted, Allah called: \"O Ibrahim, you have fulfilled the vision\" (37:103-105), and ransomed the boy with a great sacrifice (37:107). A Muslim learns from the son to say \"if Allah wills\", and that obedience to Allah is met with His mercy.",

"prophets_282": "The verse reads: \"And We inspired the mother of Musa: nurse him, and when you fear for him, cast him into the river, and do not fear and do not grieve. Indeed, We will return him to you and make him one of the messengers\" (28:7). Pharaoh was killing the sons of her people (28:4). Pharaoh's own family picked the baby up, and he refused every wet nurse until his sister led them to his mother, \"so We returned him to his mother, that her eye might be comforted and she would know that the promise of Allah is true\" (28:8-13). A Muslim learns that Allah keeps His promise, even through the house of an enemy.",

"prophets_283": "The Qur'an quotes the call itself: \"And he called out in the darkness: There is no god but You; glory be to You; indeed, I have been of the wrongdoers\" (21:87). The verse says he had gone off in anger, thinking Allah would not decree hardship upon him. The answer follows: \"So We responded to him and saved him from the distress. And thus do We save the believers\" (21:88). Surah As-Saffat tells that the fish swallowed Yunus, and that had he not been of those who glorify Allah, he would have stayed in its belly (37:142-144). A Muslim learns that this same prayer is a door of rescue for every believer in distress.",

"prophets_284": "His full name is Muhammad ibn 'Abdullah ibn 'Abd al-Muttalib ibn Hashim, of the tribe of Quraysh in Makkah; every standard biography opens with this line. All of them agree that 'Abdullah died before his son was born, so the Prophet ﷺ never knew his father. The Qur'an speaks to him of that childhood: \"Did He not find you an orphan and give you shelter?\" (93:6). His grandfather 'Abd al-Muttalib cared for him, then his uncle Abu Talib. A Muslim learns that the man Allah chose as His last messenger began life as an orphan, with Allah Himself as his protector.",

"prophets_285": "Amina bint Wahb was from Quraysh, the tribe of Makkah, and every standard biography records her as the mother of the Prophet ﷺ. All of them agree that she died while he was still a small boy, after his father had already died before his birth, so he grew up in the care of his grandfather 'Abd al-Muttalib and then of his uncle Abu Talib. The Qur'an reminds him of this: \"Did He not find you an orphan and give you shelter? And He found you lost and guided you\" (93:6-7). A Muslim learns that Allah watched over His Prophet ﷺ from the cradle, and honours the mother who bore him.",

"prophets_286": "Maryam brought her baby to her people, who accused her; she only pointed to the child, and they asked how they could speak to a baby in the cradle (19:27-29). Then he spoke: \"Indeed, I am the servant of Allah. He has given me the Book and made me a prophet, and made me blessed wherever I am, and enjoined on me prayer and zakat as long as I live, and to be good to my mother\" (19:30-32). The Qur'an then says: \"That is 'Isa, son of Maryam, the word of truth about which they dispute\" (19:34). A Muslim learns that 'Isa's first words called him Allah's servant, and takes that as the truth about him.",

"prophets_287": "The verse reads: \"And to 'Ad We sent their brother Hud. He said: O my people, worship Allah; you have no god other than Him. Will you not then fear Him?\" (7:65). The chiefs of his people called him a fool and a liar, and he answered that he was a messenger from the Lord of the worlds, giving them sincere advice (7:66-68). He reminded them that Allah had made them successors after the people of Nuh (7:69); they refused, so Allah saved Hud and those with him and destroyed the deniers (7:72). A Muslim learns that Hud brought the same call as every prophet: worship Allah alone.",

"prophets_288": "The verse reads: \"And to Thamud We sent their brother Salih. He said: O my people, worship Allah; you have no god other than Him. A clear proof has come to you from your Lord: this is the she-camel of Allah, a sign for you. So leave her to eat in Allah's land and do not touch her with harm, or a painful punishment will seize you\" (7:73). Thamud carved their homes in the mountains (7:74), yet they hamstrung the she-camel and defied their Lord's command, and an earthquake took them (7:77-78). A Muslim learns that a sign from Allah is to be respected, and that harming what He protects brings ruin.",

"prophets_289": "Musa had just been sent to Pharaoh and prayed: \"My Lord, expand my breast for me, ease my task, and loosen the knot from my tongue, that they may understand my speech\" (20:25-28). Then he asked for a helper: \"And appoint for me a helper from my family, Harun, my brother; strengthen me through him and let him share my task, so that we may glorify You much\" (20:29-33). Allah answered: \"You have been granted your request, O Musa\" (20:36), and later told them: \"Go, both of you, to Pharaoh\" (20:43). A Muslim learns that asking Allah for help, and for a good companion in a hard task, is part of a prophet's way.",

"prophets_290": "The verse reads: \"Muhammad is not the father of any of your men, but the Messenger of Allah and the seal of the prophets; and Allah has knowledge of all things\" (33:40). It comes after the account of Zayd (33:37), in a surah that had already said adopted sons are to be called by their real fathers' names (33:5). A seal closes a letter so that nothing more is added. A few verses later Allah calls him \"an illuminating lamp\" (33:46). A Muslim learns that prophethood was completed and closed with Muhammad ﷺ, and that his message is the last sent to mankind.",

"prophets_291": "The angels' words are: \"O Maryam, indeed Allah has chosen you and purified you and chosen you above the women of the worlds. O Maryam, be devout to your Lord, prostrate, and bow with those who bow\" (3:42-43). Earlier the surah shows why: whenever Zakariyya entered her prayer chamber he found provision with her and asked where it came from, and she answered, \"It is from Allah\" (3:37). Soon after, the angels bring her news of a son, the Messiah, 'Isa (3:45). A Muslim learns that Maryam was chosen for her devotion, and that being chosen called her to more worship, not less.",

"prophets_292": "The verse gives the whole prayer: \"And Ayyub, when he called to his Lord: Indeed, adversity has touched me, and You are the most merciful of the merciful\" (21:83). He did not list demands; he named his pain and named Allah's mercy. The reply came at once: \"So We responded to him and removed what afflicted him, and We gave him his family and the like of them with them, a mercy from Us and a reminder for the worshippers\" (21:84). The next verse counts Isma'il, Idris and Dhul-Kifl with him among the patient (21:85). A Muslim learns to bring his hurt to Allah in a few humble words.",

"prophets_293": "The verse reads: \"And He taught Adam the names, all of them; then He showed them to the angels and said: Tell Me the names of these, if you are truthful\" (2:31). The angels replied: \"Glory be to You! We have no knowledge except what You have taught us\" (2:32). Then Allah said, \"O Adam, tell them their names,\" and when he did, He reminded the angels that He knows the unseen of the heavens and the earth (2:33), and commanded them to prostrate to Adam (2:34). A Muslim learns that knowledge is a gift from Allah, and that it raised the first man in honour before the angels.",

"prophets_294": "The prayer reads: \"My Lord, forgive me, and grant me a kingdom such as no one after me will have. Indeed, You are the Giver\" (38:35). Notice that he asks for forgiveness first. Allah answered: \"So We subjected to him the wind, blowing gently by his command wherever he wished\" (38:36), and the devils, every builder and diver (38:37). Then He said: \"This is Our gift, so give or withhold without account\" (38:39), and promised him nearness to Him and a good return (38:40). A Muslim learns that Sulayman's unmatched power came as a gift after a prayer for forgiveness, joined to a promise of the Hereafter.",

"prophets_295": "The angels who came to Lut said: \"O Lut, we are messengers of your Lord; they will never reach you. So leave with your family in a part of the night, and let none of you look back, except your wife; what strikes them will strike her. Their appointed time is the morning\" (11:81). At dawn Allah turned the town upside down and rained on it stones of hard clay (11:82). Surah At-Tahrim explains her fate: the wives of Nuh and of Lut were under two righteous servants but betrayed them, and that did not help them before Allah (66:10). A Muslim learns that each person answers for his own faith.",

"prophets_296": "The verse reads: \"And when Ibrahim said to his father: Do you take idols as gods? Indeed, I see you and your people in clear error\" (6:74). The following verses tell how Allah showed him the kingdom of the heavens and the earth (6:75): he saw a star, then the moon, then the sun, and each time they set he said, \"I do not love things that set\" (6:76-78). Then he declared: \"I have turned my face to Him who created the heavens and the earth, inclining to truth\" (6:79). A Muslim learns that Ibrahim's warning began at home, and that only the Creator, who never sets, deserves worship.",

"prophets_297": "The word rasul runs through the Qur'an. It is the title in the testimony of faith: \"Muhammad is the Messenger of Allah\" (48:29). The Qur'an says that no people was left without one: \"And for every nation there is a messenger\" (10:47), and \"there is no nation but a warner passed among it\" (35:24). It also states what a messenger's task is: \"Upon the Messenger is only clear delivery\" (24:54); he does not invent the message, he carries it faithfully from Allah to people. A Muslim learns to see every messenger, from Nuh to Muhammad ﷺ, as a trusted carrier of one message: worship Allah alone.",

"prophets_298": "The two verses read: \"O Prophet, indeed We have sent you as a witness, a bringer of good news and a warner, and as one who calls to Allah by His permission, and an illuminating lamp\" (33:45-46). The next verse says what the good news is: \"Give the believers the good news that they will have from Allah great bounty\" (33:47). Surah Al-Baqarah explains the witness: the Muslim community was made a middle nation \"so that the Messenger may be a witness over you\" (2:143). A Muslim learns that his Prophet ﷺ watches over his community, brings it hope, warns it of danger and lights its way.",

"prophets_299": "The verse comes near the end of Surah Al-Anbiya, after a long line of prophets: \"And We have not sent you except as a mercy to the worlds\" (21:107). The next verse gives the heart of that mercy: \"Say: it is only revealed to me that your God is one God; so will you submit?\" (21:108). Surah At-Tawbah shows the mercy in his person: \"There has come to you a Messenger from among yourselves; what you suffer is hard on him; he is anxious for you, and to the believers he is kind and merciful\" (9:128). A Muslim learns that the Prophet ﷺ was sent for all the worlds, and tries to carry that same mercy to others.",

"prophets_300": "The verse reads: \"O descendants of those We carried with Nuh; indeed, he was a grateful servant\" (17:3). It addresses the Children of Israel, just after the Book given to Musa (17:2), and reminds them that their ancestors were saved on the Ark. Nuh's gratitude is shown in Surah Al-Mu'minun, where Allah tells him what to say once aboard: \"Praise be to Allah, who saved us from the wrongdoing people\" (23:28). After a lifetime of calling his people (29:14) and a flood that drowned the deniers, he answered with praise. A Muslim learns from Nuh that thanks to Allah is the right answer to rescue.",
}
