"""English — details, prophets_b (60 questions)."""

D = {
"prophets_091": "The verse opens the account of Dawud's favours in Surah Saba: \"And We certainly gave Dawud from Us bounty: O mountains, echo praises with him, and the birds. And We made iron pliable for him\" (34:10). The next verse tells him what the gift is for: \"Make full coats of mail and measure the links precisely, and work righteousness; indeed I see what you do\" (34:11). A Muslim learns that a skill is a favour from Allah, to be used for good and under His sight.",

"prophets_092": "Surah Al-Anbiya says: \"And We taught him the fashioning of coats of armour for you, to protect you in your battles. So will you be grateful?\" (21:80). It follows the verse in which the mountains and the birds glorify Allah with Dawud (21:79), and leads into the wind subjected to Sulayman (21:81). The armour is a gift to the people it protects as much as to Dawud, and the verse ends by asking them for thanks. A Muslim learns to see useful knowledge as a favour that calls for gratitude.",

"prophets_093": "The verse closes the story of Talut's army: \"So they defeated them by permission of Allah, and Dawud killed Jalut, and Allah gave him the kingship and wisdom and taught him from what He willed\" (2:251). Just before, the small company had prayed: \"Our Lord, pour upon us patience, plant firmly our feet and give us victory over the disbelieving people\" (2:250). The victory is credited to Allah's permission, and the young Dawud receives both rule and knowledge. A Muslim learns that success comes by Allah's leave, not by numbers.",

"prophets_094": "Talut said as he set out with the army: \"Allah will test you with a river: whoever drinks from it is not of me, except one who takes a handful with his hand. But they drank from it, except a few\" (2:249). He was the king the Children of Israel had asked for (2:247). The few who stayed firm said: \"How many a small company has overcome a large company by permission of Allah\" (2:249). A Muslim learns that a small act of obedience shows who will hold firm later.",

"prophets_095": "The verse reads: \"And We subjected the mountains to glorify Us along with Dawud, and the birds; and We were the doers\" (21:79). It follows the judgement of Dawud and Sulayman on the field (21:78). Surah Sad shows the same scene: the mountains glorifying with him in the evening and at sunrise, and the birds gathered, all turning to him (38:18-19). A Muslim learns that all creation praises Allah, and that a servant who praises Him joins a chorus far larger than himself.",

"prophets_096": "The verse reads: \"And to Sulayman We subjected the wind, blowing forcefully, running by his command towards the land We had blessed; and We know all things\" (21:81). Surah Saba gives its measure: \"its morning course was a month and its evening course was a month\" (34:12), and Surah Sad says the wind blew gently by his command wherever he directed (38:36). A Muslim learns that even a king's greatest power is a loan from Allah, given for a time and under His knowledge.",

"prophets_097": "Sulayman inspected the birds and asked: \"Why do I not see the hoopoe, or is he among the absent?\", promising to punish him unless he brought a clear excuse (27:20-21). The hoopoe returned and said: \"I have encompassed what you have not encompassed, and I bring you from Saba certain news\" (27:22). He reported a queen with a great throne, and a people prostrating to the sun (27:23-24). A Muslim learns that Sulayman listened to a small bird, because true news matters whoever carries it.",

"prophets_098": "The verse reads: \"When they came upon the valley of the ants, an ant said: O ants, enter your dwellings, lest Sulayman and his soldiers crush you while they do not perceive\" (27:18). Sulayman understood her: \"He smiled, laughing at her words, and said: My Lord, enable me to be grateful for Your favour upon me and upon my parents, and to do righteousness that pleases You\" (27:19). A Muslim learns that a moment of wonder at Allah's creation should turn at once into gratitude.",

"prophets_099": "Sulayman asked his assembly: \"Which of you will bring me her throne before they come to me in submission?\" (27:38). Then \"one who had knowledge of the Book said: I will bring it to you before your glance returns to you. When he saw it placed before him, he said: This is from the favour of my Lord, to test me whether I am grateful or ungrateful\" (27:40). A Muslim learns that a great gift is a test answered by thanks.",

"prophets_100": "The jinn worked for Sulayman by the permission of his Lord (34:12): \"They made for him what he willed of elevated chambers, statues, basins like reservoirs and fixed cauldrons. Work, O family of Dawud, in gratitude; and few of My servants are grateful\" (34:13). The same passage warns that any jinn who turned from Allah's command would taste the punishment of the Blaze (34:12). A Muslim learns that abundance is a call to gratitude, and that few answer it.",

"prophets_101": "The verse reads: \"When We decreed death for him, nothing showed them his death except a creature of the earth eating his staff. When he fell, it became clear to the jinn that had they known the unseen, they would not have remained in humiliating punishment\" (34:14). The jinn had been building and diving for him under his command (34:12-13), and they kept working while he stood. A Muslim learns that the unseen belongs to Allah alone, and that no one else, jinn or human, can see it.",

"prophets_102": "The prayer reads: \"He said: My Lord, forgive me and grant me a kingdom such as will not belong to anyone after me; indeed, You are the Bestower\" (38:35). The verse comes right after the Qur'an says that Sulayman was tried and then turned back to his Lord (38:34). Allah answered by subjecting the wind to him and the devils, builders and divers (38:36-37), and said: \"This is Our gift, so grant or withhold without account\" (38:39). A Muslim notices that Sulayman asked for forgiveness before anything else.",

"prophets_103": "Ayyub called to his Lord: \"Satan has touched me with hardship and torment\" (38:41). The answer came: \"Strike the ground with your foot; here is a cool spring to wash with and to drink\" (38:42). Allah then gave him back his family and their like with them, as a mercy and a reminder (38:43), and said: \"We found him patient; an excellent servant, ever turning back to Us\" (38:44). A Muslim learns that Ayyub turned to Allah alone in his illness, and that relief came through an act of obedience.",

"prophets_104": "The verse reads: \"And the man of the fish, when he went off in anger; then he called out in the darkness: There is no god but You, glory be to You, I have been among the wrongdoers\" (21:87). The next verse answers: \"So We responded to him and saved him from the distress; and thus do We save the believers\" (21:88). A Muslim learns this call for his own distress, because the Qur'an promises that this is how Allah saves the believers.",

"prophets_105": "Surah As-Saffat tells the story: Yunus fled to the laden ship, drew lots and lost, and the fish swallowed him while he was blameworthy (37:140-142). \"Had he not been of those who glorify Allah, he would have remained in its belly until the Day they are resurrected\" (37:143-144). \"We cast him onto the open shore while he was ill\" (37:145), \"and We caused to grow over him a gourd plant\" (37:146). A Muslim learns that Allah's care continues after forgiveness, down to the shade over a sick man's head.",

"prophets_106": "The verse reads: \"And We sent him to a hundred thousand or more, and they believed, so We gave them enjoyment for a time\" (37:147-148). It closes the story of Yunus (37:139-146). Surah Yunus recalls them: no town's faith benefited it when punishment came except the people of Yunus, from whom Allah removed the punishment of disgrace when they believed (10:98). A Muslim learns that a whole people can turn back to Allah together, and that His mercy meets them when they do.",

"prophets_107": "Zakariyya had asked how he could have a son in old age, and was told: \"It is easy for Me\" (19:8-9). He then asked for a sign: \"Your sign is that you will not speak to people for three nights, though sound\" (19:10). He then came out to his people and signalled to them to glorify Allah morning and evening (19:11). A Muslim learns that his sign was silence, and that even without speech he kept calling others to praise.",

"prophets_108": "The good news reads: \"O Zakariyya, We give you good tidings of a boy whose name will be Yahya; We have not given this name to anyone before\" (19:7). It answers the quiet prayer at the surah's opening, where Zakariyya said his bones had weakened and his head was white with age, and asked for an heir pleasing to Allah (19:3-6). Allah chose the name before the child was born. A Muslim learns that Allah answers a private prayer more completely than what was asked.",

"prophets_109": "The verse reads: \"O Yahya, take the Scripture with determination. And We gave him judgement while yet a boy\" (19:12). The following verses describe him: tenderness from Allah and purity, fear of Allah, dutiful to his parents, neither a tyrant nor disobedient, and \"peace be upon him the day he was born, the day he dies and the day he is raised alive\" (19:13-15). Wisdom in childhood came together with kindness to parents. A Muslim learns that true understanding shows in good character, whatever one's age.",

"prophets_110": "The verse reads: \"When the wife of 'Imran said: My Lord, I have vowed to You what is in my womb, consecrated to Your service, so accept it from me; You are the Hearing, the Knowing\" (3:35). When she gave birth she said: \"My Lord, I have delivered a female\", named her Maryam, and sought refuge with Allah for her and her offspring from Satan (3:36). A Muslim learns from this mother that a child can be offered to Allah before birth, and that Allah accepts.",

"prophets_111": "\"Her Lord accepted her with good acceptance and put her in the care of Zakariyya. Whenever Zakariyya entered upon her in the prayer chamber, he found with her provision. He said: O Maryam, where does this come from? She said: It is from Allah; Allah provides for whom He wills without account\" (3:37). The next verse says that Zakariyya then called on his Lord for a good offspring (3:38). A Muslim learns that seeing Allah's provision to another moved a prophet to ask, with hope, for his own.",

"prophets_112": "The verse reads: \"When the angels said: O Maryam, Allah has chosen you and purified you, and chosen you above the women of the worlds\" (3:42). The angels then told her what to do with that rank: \"O Maryam, be devoutly obedient to your Lord, prostrate and bow with those who bow\" (3:43). The Qur'an calls this news of the unseen revealed to the Prophet ﷺ (3:44). A Muslim learns that being chosen by Allah leads to more worship, not less.",

"prophets_113": "\"The pains of childbirth drove her to the trunk of a palm tree; she said: I wish I had died before this and been forgotten\" (19:23). A voice called from below her: \"Do not grieve; your Lord has placed beneath you a stream\" (19:24), \"and shake towards you the trunk of the palm tree: it will drop upon you fresh, ripe dates\" (19:25). A Muslim learns that Allah's provision often asks a small effort, and that comfort comes in the hardest hour.",

"prophets_114": "The verse reads: \"The Messiah, son of Maryam, was only a messenger; messengers had passed away before him. His mother was a woman of truth. They both used to eat food\" (5:75). It answers those in the same passage who said that Allah is the Messiah, or one of three (5:72-73). The same word of truth is given to Yusuf, addressed in prison as \"O Yusuf, man of truth\" (12:46). A Muslim learns to honour Maryam highly and to worship Allah alone.",

"prophets_115": "The angels said: \"O Maryam, Allah gives you good tidings of a word from Him, whose name is the Messiah, Isa son of Maryam, distinguished in this world and the Hereafter\" (3:45). When she asked how she could have a child untouched by any man, she was told: \"Thus Allah creates what He wills; when He decrees a matter, He only says to it, Be, and it is\" (3:47). A Muslim learns Isa's names and rank from the angels' own words.",

"prophets_116": "Isa told the Children of Israel: \"I have come to you with a sign from your Lord: I design for you from clay the form of a bird, then I breathe into it and it becomes a bird by Allah's permission; I give life to the dead by Allah's permission\" (3:49). Twice in one verse the words \"by Allah's permission\" appear, and Surah Al-Ma'ida repeats them (5:110). A Muslim learns that every miracle of a prophet is Allah's act, and that the prophet is His servant.",

"prophets_117": "The verse reads: \"When Isa sensed disbelief from them, he said: Who are my helpers for Allah? The disciples said: We are the helpers of Allah; we believe in Allah, and bear witness that we are Muslims\" (3:52). They asked to be written among the witnesses (3:53). Surah As-Saff calls the believers to be helpers of Allah as the disciples were when Isa asked them (61:14). A Muslim learns that answering a prophet's call means standing with him when others turn away.",

"prophets_118": "The disciples asked Isa whether his Lord could send down to them a table spread with food from heaven, and he answered: \"Fear Allah, if you are believers\" (5:112). Isa prayed: \"O Allah, our Lord, send down to us a table from heaven, to be a feast for the first of us and the last of us, and a sign from You\" (5:114). Allah promised to send it, warning whoever disbelieved after it (5:115). A Muslim learns that a sign given is a trust, not a spectacle.",

"prophets_119": "The verses answer a claim: \"And for their saying: We killed the Messiah, Isa son of Maryam, the messenger of Allah. They did not kill him, nor did they crucify him, but it was made to appear so to them. They certainly did not kill him. Rather, Allah raised him to Himself\" (4:157-158). The passage lists earlier wrongs of the same people, including a grave slander against Maryam (4:156). A Muslim learns to say of Isa's end what the Qur'an says: not killed, not crucified, raised by Allah.",

"prophets_120": "Isa said: \"O Children of Israel, I am the messenger of Allah to you, confirming the Torah that came before me and bringing good tidings of a messenger to come after me, whose name is Ahmad\" (61:6). The verse before records Musa asking his people why they harmed him though they knew he was Allah's messenger (61:5). Each messenger confirms the one before and announces the one after. A Muslim learns that Ahmad is a name of the Prophet ﷺ, announced by Isa long before his birth.",

"prophets_121": "Surah As-Saffat says: \"Ilyas was among the messengers. When he said to his people: Will you not fear Allah?\" (37:123-124), \"Do you call upon Ba'l and leave the best of creators, Allah, your Lord and the Lord of your first forefathers?\" (37:125-126). They denied him, and will be brought for judgement, except Allah's chosen servants (37:127-128). Allah left him a good name among later generations: \"Peace be upon Ilyasin\" (37:129-130). A Muslim learns that a prophet's whole argument is that only the Creator deserves to be called upon.",

"prophets_122": "The verse reads: \"And Isma'il, Idris and Dhul-Kifl: all were of the patient. We admitted them into Our mercy; they were among the righteous\" (21:85-86). Surah Al-Anbiya passes from one prophet to the next: just before come Ayyub, whose harm Allah removed (21:83-84), and just after comes Yunus calling out in the darkness (21:87). A Muslim learns that patience is the trait the Qur'an chooses to remember these three by, and that patience leads into Allah's mercy.",

"prophets_123": "The verse reads: \"And remember Isma'il, Al-Yasa' and Dhul-Kifl: all are among the outstanding\" (38:48). It follows the mention of Ibrahim, Ishaq and Ya'qub, men of strength and vision whom Allah chose for a special quality, the remembrance of the Hereafter (38:45-47). Al-Yasa' is named once more in Surah Al-An'am, alongside Isma'il, Yunus and Lut, among those Allah preferred over the worlds (6:86). The Qur'an gives him no story, only a rank. A Muslim learns to honour every prophet the Qur'an names, even without a story.",

"prophets_124": "The verse reads: \"Muhammad is not the father of any of your men, but he is the Messenger of Allah and the Seal of the Prophets; and Allah knows all things\" (33:40). It closes the passage about Zayd, whom the Prophet ﷺ had raised as a son (33:37), after the surah stated that adopted sons are not true sons (33:4-5). A seal comes last and closes what went before. A Muslim learns from this verse that no prophet comes after Muhammad ﷺ, and that his message is the last.",

"prophets_125": "The verse reads: \"And We have not sent you except as a mercy to the worlds\" (21:107). It stands near the end of Surah Al-Anbiya, which has recounted many prophets, and the next verse gives the heart of his message: \"Say: It is only revealed to me that your God is one God, so will you submit?\" (21:108). The mercy is not for one people or one time but for the worlds. A Muslim learns that following him ﷺ is meant to carry mercy to everyone his message reaches.",

"prophets_126": "The verse reads: \"Allah and His angels send blessings upon the Prophet. O you who believe, send blessings upon him and greet him with peace\" (33:56). It follows a description of the Prophet ﷺ as a witness, a bringer of good tidings, a warner, a caller to Allah and a shining lamp (33:45-46). The believers are asked to do on earth what Allah and His angels do above. A Muslim takes from it the habit of asking blessings on him whenever his name is mentioned.",

"prophets_127": "The verse reads: \"And indeed, you are of a great moral character\" (68:4). It comes at the opening of Surah Al-Qalam, after Allah swears by the pen and what they write that the Prophet ﷺ is not mad by the favour of his Lord, and that his reward is unending (68:1-3). Surah Al-Ahzab adds that in the Messenger of Allah is an excellent example for those who hope in Allah (33:21). A Muslim learns that the Prophet's ﷺ conduct is itself proof of his truth, and a model to follow.",

"prophets_128": "The verse reads: \"Muhammad is only a messenger; messengers have passed away before him. If he dies or is killed, will you turn back on your heels? Whoever turns back will not harm Allah, and Allah will reward the grateful\" (3:144). It belongs to the verses on the battle in which the believers were wounded (3:140). A Muslim learns that faith rests on Allah, who never dies, and that loving the Prophet ﷺ means holding to his message.",

"prophets_129": "The verse reads: \"When We took from the prophets their covenant, and from you, and from Nuh, Ibrahim, Musa and Isa son of Maryam; and We took from them a solemn covenant\" (33:7). Its purpose follows: \"that He may question the truthful about their truthfulness\" (33:8). Surah Ash-Shura names the same five: the religion enjoined on Nuh, Ibrahim, Musa and Isa is the one revealed to the Prophet ﷺ (42:13). A Muslim learns that these messengers carried one covenant and one religion.",

"prophets_130": "Abu Hurayra narrates in Sahih al-Bukhari 2262 that the Prophet ﷺ said Allah sent no prophet who had not tended sheep; asked whether he had too, he said he had tended them for the people of Makkah for a small payment. The Qur'an shows Musa in the same work: his staff beat down leaves for his sheep (20:18), and he watered the flocks of the two women of Madyan (28:23-24). A Muslim learns that the prophets earned their living with their hands, and that no honest work is beneath anyone.",

"prophets_131": "The hadith is narrated by Abu Hurayra in Sahih Muslim 2379: the Messenger of Allah ﷺ said that Zakariyya was a carpenter. The Qur'an shows the same prophet in the prayer chamber, caring for Maryam and asking where her provision came from (3:37), and calling on his Lord for a son in his old age (19:3-6). The hadith adds that between these moments he worked with wood for his bread. A Muslim learns that prophethood and a humble trade went together, and that working with the hands carries no shame.",

"prophets_132": "The hadith is narrated by Abu Hurayra in Sahih al-Bukhari 3442. The Prophet ﷺ said that in this world and the Hereafter he is the nearest of all people to Isa son of Maryam, that the prophets are brothers from one father, their mothers differ, and their religion is one. The Qur'an records Isa announcing a messenger after him named Ahmad (61:6), and it names no prophet between them. A Muslim learns to love Isa as the Prophet ﷺ loved him, and to see all the prophets as one family.",

"prophets_133": "Six surahs carry a prophet's name, as the list of surah names shows: Yunus (10), Hud (11), Yusuf (12), Ibrahim (14), Muhammad (47) and Nuh (71). Surah Yusuf tells his story and calls it the best of stories (12:3); Surah Nuh is given entirely to his call to his people; Surah Ibrahim holds his prayer for Makkah and his descendants (14:35-41); Surah Muhammad names him in its second verse (47:2). Surah Al-Anbiya is named for the prophets all together. A Muslim learns his way around the Qur'an by these names.",

"prophets_134": "The verse reads: \"Indeed, Ibrahim was forbearing, tender-hearted and ever-returning to Allah\" (11:75). When fear left Ibrahim and the good news reached him, he began to plead with Allah for the people of Lut (11:74), until he was told: \"O Ibrahim, leave this; the command of your Lord has come, and a punishment that cannot be turned back is coming to them\" (11:76). A Muslim learns that a tender heart pleads even for the astray, while bowing to Allah's decree.",

"prophets_135": "Shu'ayb said to the people of Madyan: \"O my people, worship Allah; you have no god other than Him. A clear proof has come to you from your Lord, so give full measure and weight, do not deprive people of their due, and do not spread corruption in the land after it has been set right\" (7:85). Surah Ash-Shu'ara records the same call to weigh with a straight balance (26:181-182). A Muslim learns that honesty in trade is part of worship, not separate from it.",

"prophets_136": "The verse reads: \"So the earthquake seized them, and they lay lifeless in their homes. Those who denied Shu'ayb were as if they had never lived there\" (7:91-92). The chiefs had threatened to expel him and the believers (7:88). Then Shu'ayb turned away: \"O my people, I conveyed to you the messages of my Lord and advised you; how could I grieve for a disbelieving people?\" (7:93). A Muslim learns that a warner who has delivered his message is clear of what follows.",

"prophets_137": "Guests came to Ibrahim with good news and greeted him with peace, and he brought a roasted calf (11:69). \"When he saw their hands not reaching for it, he found them strange and felt fear of them. They said: Do not fear; we have been sent to the people of Lut\" (11:70). His wife laughed, and was given the good news of Ishaq and, after Ishaq, of Ya'qub (11:71). A Muslim learns that the angels' errand held both mercy for one house and justice for another.",

"prophets_138": "The verse reads: \"My Lord, make me an establisher of prayer, and from my descendants; our Lord, and accept my supplication\" (14:40). It belongs to the long prayer Ibrahim made after settling his family by the sacred House: he asked for a secure city and protection from idols (14:35), and said he had placed his descendants in a valley without crops so that they might establish prayer (14:37). A Muslim learns to ask for prayer not only for himself but for his children after him.",

"prophets_139": "The verse reads: \"He raised his parents upon the throne, and they fell down before him in prostration. He said: O my father, this is the meaning of my vision of old; my Lord has made it true. He was good to me when He took me out of prison\" (12:100). The vision was the eleven stars, the sun and the moon that Yusuf had seen prostrating to him as a boy (12:4). A Muslim learns that Yusuf, at the height of his honour, gave the credit to Allah.",

"prophets_140": "The brothers said: \"Yusuf and his brother are more beloved to our father than we are, though we are a group; our father is clearly mistaken. Kill Yusuf or cast him out to some land, so that your father's face will be yours alone, and after that you can be righteous people\" (12:8-9). One of them said: \"Do not kill Yusuf, but throw him into the bottom of the well; some travellers will pick him up\" (12:10). A Muslim learns how envy talks itself into wrong by promising repentance later.",

"prophets_141": "The brothers came to their father at night weeping, saying a wolf had eaten Yusuf while they raced (12:16-17). \"They brought his shirt with false blood on it. He said: Rather, your souls have tempted you to something; so patience is most fitting, and Allah is the one whose help is sought\" (12:18). The shirt returns twice: torn from behind, proving Yusuf innocent (12:26-28), and laid over Ya'qub's face, restoring his sight (12:93, 12:96). A Muslim learns from Ya'qub to meet a lie with patience and seek Allah's help.",

"prophets_142": "\"We inspired the mother of Musa: when you fear for him, cast him into the river, and do not fear and do not grieve; We will return him to you and make him one of the messengers\" (28:7). Pharaoh's family picked him up (28:8). Allah made him refuse every wet nurse until his sister led them to his mother, \"so that she might know that the promise of Allah is true\" (28:12-13). A Muslim learns that Allah's promise is kept, even through a river and a palace.",

"prophets_143": "The verse reads: \"We inspired Musa: Strike the sea with your staff. So it parted, and each part was like a great mountain\" (26:63). Just before, when the two hosts saw each other, Musa's companions cried that they would be overtaken, and he answered: \"No; my Lord is with me, He will guide me\" (26:62). Allah then saved Musa and all who were with him and drowned the others (26:65-66). A Muslim learns that Musa's certainty came before the sea opened, not after.",

"prophets_144": "Musa had gone towards a fire and heard a call: take off your sandals, you are in the sacred valley of Tuwa, listen to what is revealed (20:11-13). What was revealed came at once: \"Indeed, I am Allah; there is no god but Me, so worship Me and establish prayer for My remembrance\" (20:14). The next verse tells him that the Hour is surely coming (20:15). A Muslim learns that Allah's first message to a prophet was His oneness, worship and prayer.",

"prophets_145": "The command reads: \"Go, both of you, to Pharaoh; he has transgressed. Speak to him with gentle speech, so that he may be reminded or fear\" (20:43-44). The two said they feared Pharaoh would hasten harm against them, and Allah answered: \"Do not fear; I am with you both, I hear and I see\" (20:45-46). Gentleness was commanded towards the man the Qur'an calls a transgressor. A Muslim learns that a firm message is to be delivered in a gentle voice.",

"prophets_146": "The verse reads: \"When Musa said to his young servant: I will not give up until I reach the junction of the two seas, even if I go on for ages\" (18:60). When they reached it they forgot their fish (18:61); when Musa later asked for their meal, the boy remembered it, and Musa said: \"That is what we were seeking\", and they turned back (18:62-64). There they found a servant given mercy and knowledge from Allah (18:65). A Muslim learns that seeking knowledge is worth a long, tiring journey.",

"prophets_147": "The servant holed the ship they boarded, and Musa asked: \"Have you holed it to drown its people?\" (18:71). Then he killed a boy (18:74). Then he repaired a falling wall, and Musa said he could have taken payment (18:77). The servant explained each act: a king was seizing every sound boat, the boy's parents were believers, and the wall hid a treasure for two orphans; \"I did not do it of my own accord\" (18:82). A Muslim learns that what looks like harm can hide Allah's mercy.",

"prophets_148": "Maryam brought the child to her people, who reproached her (19:27-28). She pointed to the baby, and they asked how they could speak to a child in the cradle (19:29). \"He said: I am the servant of Allah; He has given me the Scripture and made me a prophet\" (19:30). He went on: Allah had made him blessed wherever he was, enjoined on him prayer and zakat, and made him dutiful to his mother (19:31-32). A Muslim learns that Isa's first word about himself was \"servant\".",

"prophets_149": "Allah had forbidden Adam and his wife one tree, and Satan whispered to them (7:19-21). When they tasted it, their nakedness appeared, and their Lord asked: \"Did I not forbid you that tree and tell you that Satan is a clear enemy to you?\" (7:22). They answered: \"Our Lord, we have wronged ourselves; if You do not forgive us and have mercy on us, we will surely be among the losers\" (7:23). A Muslim learns the words to say after a mistake.",

"prophets_150": "The surah opens: \"We sent Nuh to his people: Warn your people before a painful punishment comes to them\" (71:1). Nuh told them he was a clear warner and called them to worship Allah, fear Him and obey him (71:2-3). He told his Lord that he had called them night and day and they only fled, putting their fingers in their ears (71:5-7). He promised them rain, wealth and children if they sought forgiveness (71:10-12). A Muslim learns that a warning is an act of mercy, given before punishment.",
}
