"""English — details, prophets_c_1 (50 questions)."""

D = {
"prophets_151": "The command is given in Surah Al-Baqarah: \"O Adam, dwell, you and your wife, in the Garden, and eat freely from it wherever you wish, but do not approach this tree, or you will be among the wrongdoers\" (2:35). It comes right after the angels prostrated to Adam and Iblis refused (2:34), and right before Satan made the two of them slip (2:36). A Muslim learns that obedience is proved at the single limit Allah sets, not in the abundance He permits.",

"prophets_152": "The verse reads: \"Then Adam received words from his Lord, and He accepted his repentance. Indeed, He is the Accepting of repentance, the Merciful\" (2:37). The verse before records the slip, and the verse after sends Adam down with the promise that whoever follows Allah's guidance will have no fear nor grief (2:38). Surah Al-A'raf records the prayer of Adam and his wife: \"Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy on us, we will be among the losers\" (7:23). A Muslim learns that the way back to Allah was opened for the very first human being.",

"prophets_153": "The verse reads: \"Indeed, the likeness of 'Isa before Allah is as the likeness of Adam: He created him from dust, then said to him 'Be', and he was\" (3:59). Surah Al-'Imran has just told of Maryam and the birth of 'Isa, and the next verse closes the argument: \"The truth is from your Lord, so do not be among the doubters\" (3:60). Adam had neither father nor mother, and nobody calls him divine. A Muslim takes from it that 'Isa is a created servant and messenger, and that a wonder in birth points to the Creator.",

"prophets_154": "Surah Maryam says: \"And mention in the Book Idris. Indeed, he was a man of truth, a prophet. And We raised him to a high station\" (19:56-57). He closes a series of prophets the surah tells the Prophet ﷺ to mention: Ibrahim (19:41), Musa (19:51), Isma'il (19:54), then Idris. The surah then gathers them all as those on whom Allah bestowed favour, who fell in prostration and weeping when His verses were recited (19:58). A Muslim learns that Idris is honoured for two things named together, truthfulness and prophethood.",

"prophets_155": "Nuh's words are in Surah Hud: \"Board it: in the name of Allah shall be its course and its anchorage. Indeed, my Lord is Forgiving and Merciful\" (11:41). The verse before has the oven gushing forth as the sign that the flood had begun, with the order to load a pair of every kind, his family and those who believed, \"and none had believed with him except a few\" (11:40). The next verse shows the ark carrying them through waves like mountains (11:42). A Muslim learns from Nuh to begin any journey with the name of Allah, trusting Him for both the setting out and the arrival.",

"prophets_156": "The prayer closes Surah Nuh: \"My Lord, do not leave upon the earth any inhabitant from among the disbelievers. If You leave them, they will mislead Your servants and beget none but wicked disbelievers\" (71:26-27). It comes after Nuh tells his Lord that he called his people night and day, and that his call only increased them in flight (71:5-6); the Qur'an counts his stay among them as a thousand years less fifty (29:14). His very next words ask forgiveness for himself, his parents, and every believing man and woman (71:28). A Muslim learns that Nuh asked this only after a lifetime of patient calling.",

"prophets_157": "The order is in Surah Al-Mu'minun: \"Construct the ship under Our eyes and Our inspiration, and when Our command comes and the oven overflows, take into it a pair of every kind, and your family, except those against whom the word has gone forth\" (23:27). Just before, his people had called him only a man like themselves, and he prayed: \"My Lord, help me, because they have denied me\" (23:26). Once aboard he was to say: \"Praise be to Allah, who saved us from the wrongdoing people\" (23:28). A Muslim learns that Allah's rescue came with exact instructions, and Nuh answered it with praise.",

"prophets_158": "Hud says to 'Ad in Surah Al-A'raf: \"Remember when He made you successors after the people of Nuh and increased you amply in stature. So remember the favours of Allah, that you may succeed\" (7:69). He had begun like every prophet, \"O my people, worship Allah; you have no god other than Him\" (7:65), and the chiefs answered that they saw him in foolishness and thought him a liar (7:66). The flood had cleared the earth, and 'Ad were given it and given strength. A Muslim learns that a people's strength is a favour to be remembered, and that remembering it is the road to success.",

"prophets_159": "Surah Al-Haqqah says: \"As for 'Ad, they were destroyed by a screaming, violent wind, which He imposed upon them for seven nights and eight days in succession, so you would see the people there lying fallen, as if they were hollow trunks of palm trees\" (69:6-7). The surah pairs them with Thamud, who \"were destroyed by the overpowering blast\" (69:5), and then asks: \"Do you see any remnant of them?\" (69:8). A Muslim learns that the wind that serves us daily is a soldier of Allah, and that no strength stands against Him.",

"prophets_160": "Hud asks in Surah Ash-Shu'ara: \"Do you build on every high place a monument, amusing yourselves, and take for yourselves fortresses, as if you would live forever? And when you seize, you seize as tyrants\" (26:128-130). He had opened with the call the surah gives every messenger, \"Will you not fear Allah?\" (26:124), and he goes on to name the One who provided them with cattle, children, gardens and springs (26:132-134). The reproach is against building for show and for a permanence no human has. A Muslim learns to use wealth for need and gratitude, remembering that the earth is not a permanent home.",

"prophets_161": "Salih says to Thamud in Surah Al-A'raf: \"Remember when He made you successors after 'Ad and settled you in the land: you take palaces from its plains and carve homes out of the mountains. So remember the favours of Allah, and do not go about the earth spreading corruption\" (7:74). Just before, he had shown them the she-camel of Allah as a sign, telling them not to touch her with harm (7:73). Their skill with stone was real, and the verse names it as a favour before it warns them. A Muslim learns that a people's craft comes from Allah, and the right answer is gratitude.",

"prophets_162": "Allah tells Salih in Surah Al-Qamar: \"We are sending the she-camel as a trial for them, so watch them and be patient. And inform them that the water is to be shared between them: each drinking turn is to be attended\" (54:27-28). Thamud had refused to follow \"one human being from among us\" and called Salih an insolent liar (54:24-25). The trial was simple, the camel's turn at the water and theirs, and they failed it: their companion hamstrung her (54:29). A Muslim learns that a sign from Allah is also a test of how one treats it.",

"prophets_163": "Surah Al-A'raf tells the end: \"So the earthquake seized them, and morning found them lying prone in their homes\" (7:78). The verse before gives the cause: they hamstrung the she-camel, scorned the command of their Lord and dared Salih, \"Bring us what you promise us, if you are one of the messengers\" (7:77). After the ruin Salih turned from them: \"I conveyed to you the message of my Lord and advised you sincerely, but you do not love sincere advisers\" (7:79). A Muslim learns that a punishment demanded in mockery can come, and that the prophet's advice was the true protection.",

"prophets_164": "Surah Ash-Shu'ara records: \"When their brother Lut said to them: Will you not fear Allah? I am a trustworthy messenger to you, so fear Allah and obey me. I ask you no reward for it; my reward is only from the Lord of the worlds\" (26:161-164). The surah gives the same opening words to Nuh, Hud, Salih and Shu'ayb, each called \"their brother\". Lut then names their wrong, going to males and leaving the mates Allah created for them (26:165-166), and they threaten to drive him out (26:167). A Muslim learns that Lut came to his people as a brother, with the call every messenger brought.",

"prophets_165": "The angels tell Lut in Surah Hud: \"We are messengers of your Lord; they will never reach you. So set out with your family in a part of the night, and let none of you look back, except your wife: she will be struck by what strikes them. Their appointed time is the morning\" (11:81). Lut had been distressed by his guests' arrival, calling it a hard day (11:77), and wished for a strong support against his people (11:80). At dawn the city was turned upside down and rained with stones of baked clay (11:82). A Muslim learns that obeying Allah's instructions without looking back was the way out.",

"prophets_166": "Surah Hud says: \"And to Madyan, their brother Shu'ayb. He said: O my people, worship Allah; you have no god other than Him. And do not give short measure and weight. I see you in prosperity, and I fear for you the punishment of an all-encompassing Day\" (11:84). He goes on: \"Give full measure and weight in justice, and do not deprive people of their due\" (11:85). Worship of Allah alone and honest scales stand in one breath. A Muslim learns that fair dealing in trade is part of faith, and that prosperity gained by cheating is a danger, not a blessing.",

"prophets_167": "Shu'ayb says in Surah Hud: \"I do not want to do, in your absence, what I forbid you. I only intend reform, as much as I am able. My success is only through Allah; in Him I trust, and to Him I turn\" (11:88). His people had just mocked him: \"Does your prayer command you that we should leave what our fathers worshipped?\" (11:87). He then warns them by the peoples of Nuh, Hud, Salih and Lut, and calls them to repent, for his Lord is Merciful and Loving (11:89-90). A Muslim learns that whoever calls to good must live by it first, and count on Allah for the result.",

"prophets_168": "Surah Al-Baqarah says: \"When Ibrahim was tried by his Lord with words and he fulfilled them, He said: I will make you a leader for the people. He said: And of my descendants? He said: My covenant does not reach the wrongdoers\" (2:124). The verses after show what that leadership meant: the House made a place of return and safety, and Ibrahim and Isma'il raising its foundations, praying \"Our Lord, accept from us\" (2:125-127). The answer sets a limit even on his own line. A Muslim learns that leadership in religion is given for obedience fulfilled, not inherited by blood.",

"prophets_169": "Surah Al-Baqarah tells it: \"When Ibrahim said: My Lord is the One who gives life and causes death, he said: I give life and cause death. Ibrahim said: Allah brings the sun from the east, so bring it from the west. So the one who disbelieved was confounded\" (2:258). The verse says the man argued \"because Allah had given him kingship\" and leaves him unnamed. It follows the words \"Allah is the ally of those who believe; He brings them out of darkness into light\" (2:257). A Muslim learns to answer a false claim with a clear proof that no power on earth can imitate.",

"prophets_170": "The command reads: \"Proclaim the pilgrimage to the people: they will come to you on foot and on every lean camel, coming from every distant pass\" (22:27). The verse before sets the scene: Allah settled Ibrahim at the site of the House with the order to associate nothing with Him and to purify the House for those who circle it, stand, bow and prostrate (22:26). The verse after gives the purpose: to witness benefits and mention the name of Allah on known days (22:28). A Muslim learns that the Hajj is an invitation first issued by Ibrahim at Allah's command, and every pilgrim today answers it.",

"prophets_171": "Surah Adh-Dhariyat tells it: \"When they entered upon him and said: Peace. He said: Peace, unfamiliar people. Then he slipped away to his family and brought a fat calf, and placed it before them and said: Will you not eat?\" (51:24-27). When their hands did not reach for it he grew afraid; they said, \"Do not fear\", and gave him the good news of a boy of knowledge (51:28). His wife came forward and said she was a barren old woman (51:29). A Muslim learns hospitality from Ibrahim: return the greeting, go quietly, bring the best, set it close, and invite gently.",

"prophets_172": "Surah Al-Mumtahanah says: \"There has been for you an excellent example in Ibrahim and those with him, when they said to their people: We are clear of you and of what you worship besides Allah. We reject you, and enmity and hatred have appeared between us and you forever, until you believe in Allah alone\" (60:4). The same verse ends with their prayer: \"Our Lord, in You we trust, to You we turn, and to You is the final return\" (60:4). The surah repeats that this is an example for whoever hopes in Allah and the Last Day (60:6). A Muslim learns that loyalty belongs first to Allah.",

"prophets_173": "The prayer opens: \"My Lord, make this city secure, and keep me and my sons away from worshipping idols. My Lord, they have led many of the people astray\" (14:35-36). Ibrahim goes on to say that he has settled some of his offspring in a valley without cultivation near Allah's sacred House, and asks that hearts incline toward them and that they be provided with fruits (14:37). The same prayer asks that he and his descendants be establishers of prayer (14:40). A Muslim learns from Ibrahim what to ask for one's children before food or comfort: that they worship Allah alone.",

"prophets_174": "Surah As-Saffat records: \"He said: I am going to my Lord; He will guide me. My Lord, grant me one of the righteous. So We gave him good tidings of a forbearing boy\" (37:99-101). The words come right after his people, beaten in argument over the idols he had broken, tried to burn him: \"they plotted against him, but We made them the lowest\" (37:97-98). The verses after tell of the dream in which he saw himself sacrificing that very son (37:102). A Muslim learns that leaving one's people for Allah's sake is a journey toward guidance, and its first fruit was a righteous son.",

"prophets_175": "Surah Maryam says: \"Mention in the Book Isma'il. He was true to his promise, and he was a messenger and a prophet. He used to command his family to prayer and zakat, and he was pleasing to his Lord\" (19:54-55). He appears in the surah's series of prophets, after Musa and Harun (19:51-53) and before Idris (19:56), the ones who fell in prostration and weeping when Allah's verses were recited (19:58). Two things are singled out: keeping his word, and teaching his own household first. A Muslim learns that prayer and zakat begin at home.",

"prophets_176": "Ya'qub says in Surah Yusuf: \"O my son, do not relate your vision to your brothers, or they will plot against you. Indeed, Satan is a clear enemy to man\" (12:5). Yusuf had just told him: \"O my father, I saw eleven stars and the sun and the moon; I saw them prostrating to me\" (12:4). Ya'qub adds that his Lord will choose him and complete His favour on him as on Ibrahim and Ishaq (12:6). At the end of the surah Yusuf's family bows before him and he recalls this vision (12:100). A Muslim learns to guard a blessing from envy and trust Allah to bring it about.",

"prophets_177": "Surah Yusuf records: \"A witness from her family testified: if his shirt is torn from the front, she has told the truth and he is a liar; but if his shirt is torn from the back, she has lied and he is one of the truthful\" (12:26-27). Yusuf had fled to the door, she had torn his shirt from behind, and at the door they met her husband (12:25). The next verse settles it: \"When he saw his shirt torn from the back, he said: This is one of your women's schemes\" (12:28). A Muslim learns that Allah brought Yusuf's innocence to light by a plain sign, and that truth leaves its mark on the evidence.",

"prophets_178": "Surah Yusuf tells it: \"She sent for them and prepared a banquet, gave each of them a knife, and said: Come out before them. When they saw him, they were struck with awe and cut their hands, and said: Allah forbid! This is no human; this is none but a noble angel\" (12:31). The women of the city had been saying that the governor's wife was pursuing her servant (12:30). She then declared he would be imprisoned if he refused her (12:32), and Yusuf prayed: \"My Lord, prison is dearer to me than what they call me to\" (12:33). A Muslim learns that Yusuf chose a prison cell over disobeying Allah.",

"prophets_179": "Yusuf says: \"O my two companions of the prison, are separate lords better, or Allah, the One, the Prevailing? You worship besides Him nothing but names that you and your fathers have invented, for which Allah has sent down no authority. Judgement belongs to Allah alone; He has commanded that you worship none but Him\" (12:39-40). Two young men had asked him to interpret their dreams, seeing him as a doer of good (12:36). He first told them he had followed the religion of his fathers Ibrahim, Ishaq and Ya'qub (12:38). A Muslim learns to put the call to Allah's oneness before every other service.",

"prophets_180": "Surah Yusuf records: \"The king said: Bring him to me; I will take him for myself. And when he had spoken with him, he said: Today you are, with us, established and trusted\" (12:54). Yusuf had refused to leave prison until the matter of the women who cut their hands was cleared (12:50), and the governor's wife confessed: \"It was I who tried to seduce him, and he is of the truthful\" (12:51). He answered the king's offer with a request: \"Set me over the storehouses of the land\" (12:55). A Muslim learns that Yusuf's rank came after his honour was cleared, and he used it to take on a duty.",

"prophets_181": "Surah Yusuf says: \"He began with their bags before his brother's bag, then he brought it out of his brother's bag. Thus did We plan for Yusuf; he could not have taken his brother under the king's law unless Allah willed. We raise in degrees whom We will, and above every possessor of knowledge is one more knowing\" (12:76). Yusuf had placed the drinking cup in his brother's saddlebag (12:70), and when accused the brothers themselves named the penalty of their own law: the one in whose bag it was found would be held (12:75). A Muslim learns that Allah arranges events beyond human sight, and that above every knower is Allah.",

"prophets_182": "Yusuf's words are in Surah Yusuf: \"No blame on you today. Allah will forgive you, and He is the most merciful of the merciful\" (12:92). The brothers had come in hardship asking for charity (12:88), and he asked whether they remembered what they did to Yusuf and his brother in their ignorance (12:89). To their question he answered: \"I am Yusuf, and this is my brother. Allah has been gracious to us\" (12:90), and they admitted: \"Allah has preferred you over us, and we were sinners\" (12:91). A Muslim learns that forgiving those who wronged us, when we hold power over them, is the way of the prophets.",

"prophets_183": "Ya'qub says in Surah Yusuf: \"O my sons, go and search for Yusuf and his brother, and do not despair of relief from Allah. None despairs of relief from Allah except the disbelieving people\" (12:87). By then his eyes had turned white from grief (12:84), and his sons had told him he would not stop remembering Yusuf until he wasted away (12:85). He answered: \"I only complain of my anguish and my grief to Allah\" (12:86). After years of loss, he still sends them to search. A Muslim learns that grief is brought to Allah, and that hope in His relief is part of faith itself.",

"prophets_184": "The prayer reads: \"My Lord, You have given me something of sovereignty and taught me the interpretation of events. Creator of the heavens and the earth, You are my protector in this world and the Hereafter. Cause me to die as a Muslim and join me with the righteous\" (12:101). Yusuf says it at the height of his story: his parents have come to Egypt, he has raised them on the throne, and his family has bowed before him (12:99-100). He has just credited Allah for taking him out of prison (12:100). A Muslim learns from Yusuf to ask for a good ending above every worldly gain, at the moment of greatest honour.",

"prophets_185": "Surah Sad says: \"Remember Our servant Ayyub, when he called to his Lord: Satan has touched me with hardship and suffering\" (38:41). Surah Al-Anbiya gives his call in the words: \"Adversity has touched me, and You are the most merciful of the merciful\" (21:83). The answer came at once: \"Strike with your foot; here is a cool spring for washing and drinking\" (38:42), and the surah closes his story: \"We found him patient. An excellent servant; he was ever turning back to Allah\" (38:44). A Muslim learns from Ayyub how to complain to Allah alone, without a word against Him.",

"prophets_186": "Surah Sad says: \"We gave him his family and the like of them with them, as a mercy from Us and a reminder for people of understanding\" (38:43). The verse before records the spring that healed him (38:42), and the verse after Allah's testimony: \"We found him patient. An excellent servant\" (38:44). Surah Al-Anbiya says the same: \"We answered him and removed the harm that was on him, and We gave him his family and the like of them with them\" (21:84). What was lost was not merely returned; it was doubled. A Muslim learns that Allah's relief after patience comes larger than the loss.",

"prophets_187": "Surah As-Saffat says: \"Had he not been of those who glorify Allah, he would have remained in its belly until the Day they are raised\" (37:143-144). The surah tells the story in a few verses: Yunus ran away to the laden ship, drew lots and lost, and the fish swallowed him while he was blameworthy (37:140-142); then Allah cast him onto the bare shore, sick (37:145). Surah Al-Anbiya gives the words he called out in the darkness: \"There is no god but You; glory be to You; I have been among the wrongdoers\" (21:87). A Muslim learns that glorifying Allah in easy times carries a servant through the hardest ones.",

"prophets_188": "Surah Yunus says: \"If only there had been a city that believed and whose faith benefited it, other than the people of Yunus. When they believed, We removed from them the punishment of disgrace in the life of this world, and We let them enjoy for a time\" (10:98). The verses before speak of people who will not believe until they see the painful punishment (10:96-97). Surah As-Saffat gives their number: a hundred thousand or more, \"and they believed\" (37:147-148). A Muslim learns that repentance before the punishment arrives is accepted, and that a whole city was spared by it.",

"prophets_189": "Surah Al-Qalam says: \"Be patient for the judgement of your Lord, and do not be like the companion of the fish, when he called out while he was choked with grief. Had a favour from his Lord not reached him, he would have been cast on the bare shore, blamed. But his Lord chose him and made him one of the righteous\" (68:48-50). The surah is addressed to the Prophet ﷺ, whom his people were calling mad (68:2, 68:51), and tells him to wait for Allah's decision rather than hurry away from them. A Muslim learns that Allah's favour restored Yunus to honour, and that patience is asked of the one who calls to Him.",

"prophets_190": "Surah As-Saffat says: \"Ilyas was one of the messengers, when he said to his people: Will you not fear Allah? Do you call upon Ba'l and forsake the best of creators, Allah, your Lord and the Lord of your forefathers?\" (37:123-126). His people denied him (37:127); then Allah left him a greeting among later generations, \"Peace be upon Ilyas\" (37:129-130), and counted him among His believing servants (37:132). In Surah Al-An'am he is listed with Zakariyya, Yahya and 'Isa among the righteous (6:85). A Muslim learns that Ilyas called to worship of the Creator alone, and that the peace sent on him is recited until today.",

"prophets_191": "Surah Al-Anbiya says: \"And Isma'il and Idris and Dhul-Kifl: all were of the patient. And We admitted them into Our mercy; they were among the righteous\" (21:85-86). They are named right after Ayyub, whose patience in affliction has just been told (21:83-84), and right before Yunus calling out from the darkness (21:87). Dhul-Kifl is named once more in Surah Sad, again beside Isma'il: \"Remember Isma'il and Al-Yasa' and Dhul-Kifl; all are among the best\" (38:48). The Qur'an tells no story of him; it gives his name, his patience and his place among the righteous. A Muslim learns that patience alone earned a prophet a place in Allah's mercy.",

"prophets_192": "Surah Al-Baqarah says: \"When We parted the sea for you and saved you and drowned the people of Pharaoh while you were watching\" (2:50). It belongs to a passage that begins \"O Children of Israel, remember My favour which I bestowed upon you\" (2:40), and the verse before recalls how Pharaoh's people slaughtered their sons (2:49). Surah Ash-Shu'ara shows the moment itself: \"Strike the sea with your staff. And it parted, and each part was like a great mountain\" (26:63). A Muslim learns that Allah saves and judges in a single act, and that His favours are to be remembered.",

"prophets_193": "Musa says in Surah Al-Qasas: \"My brother Harun is more eloquent than me in speech, so send him with me as a helper to confirm me; I fear that they will deny me\" (28:34). Just before, he had confessed another fear: \"My Lord, I killed one of them, and I fear they will kill me\" (28:33). Allah answered both: \"We will strengthen your arm through your brother and give you both authority, so they will not reach you\" (28:35). In Surah Ta-Ha the same request comes with \"untie the knot from my tongue\" (20:27). A Muslim learns that asking for a helper is no weakness, and that Allah granted Harun prophethood in answer to his brother's prayer.",

"prophets_194": "Allah says to Musa and Harun in Surah Ta-Ha: \"Speak to him with gentle words, so that he may take heed or fear\" (20:44), right after \"Go, both of you, to Pharaoh; he has transgressed\" (20:43). The two answered: \"Our Lord, we fear that he will hasten against us or transgress\", and were told: \"Do not fear; I am with you both, I hear and I see\" (20:45-46). Their message was to send the Children of Israel with them and stop tormenting them (20:47). Pharaoh was the man who slaughtered their sons, and the order was still to speak gently. A Muslim learns that gentleness in calling to Allah is commanded even toward the hardest hearer.",

"prophets_195": "Surah Ghafir says: \"A believing man from Pharaoh's family, who concealed his faith, said: Would you kill a man because he says: My Lord is Allah, when he has brought you clear proofs from your Lord? If he is a liar, his lie is upon him; but if he is truthful, some of what he promises you will strike you\" (40:28). He speaks right after Pharaoh announces: \"Let me kill Musa, and let him call upon his Lord\" (40:26). He warns his people by the fate of the peoples of Nuh, 'Ad and Thamud (40:31), and the surah ends his story: \"So Allah protected him from the evils they plotted\" (40:45). A Muslim learns that one believer speaking truth before a tyrant is remembered by Allah.",

"prophets_196": "Surah Ta-Ha says: \"Harun had told them before: O my people, you are only being tested by it. Your Lord is the Most Merciful, so follow me and obey my command\" (20:90). The Samiri had made them a calf, a body that lowed, and they said, \"This is your god and the god of Musa\" (20:88); they answered Harun that they would stay devoted to it until Musa returned (20:91). When Musa seized him, Harun said: \"I feared you would say: You divided the Children of Israel\" (20:94). A Muslim learns that a trial can come dressed as a wonder, and that following Allah's messenger is the way through it.",

"prophets_197": "Surah Al-Qasas says: \"The wife of Pharaoh said: A comfort of the eye for me and for you; do not kill him. He may be of use to us, or we may take him as a son. And they did not perceive\" (28:9). The verses before tell how Musa's mother was inspired to cast him into the river, with the promise that he would be returned to her (28:7), and how Pharaoh's household picked him up to become, without their knowing, an enemy and a grief to them (28:8). In Surah At-Tahrim the same woman prays: \"My Lord, build for me a house near You in Paradise\" (66:11). A Muslim learns that a believing heart lived and spoke inside Pharaoh's own palace.",

"prophets_198": "Surah Al-Kahf records: \"Musa said to him: May I follow you, on condition that you teach me some of the right guidance you have been taught?\" (18:66). The man is described only as \"a servant from among Our servants, to whom We had given mercy from Us and taught knowledge from Us\" (18:65). He replied: \"You will never be able to bear with me\" (18:67), and Musa promised: \"You will find me, if Allah wills, patient, and I will not disobey you in anything\" (18:69). Musa, the prophet who spoke with Allah, asks like a pupil. A Muslim learns the manners of seeking knowledge: ask permission, promise patience, and put oneself under the teacher.",

"prophets_199": "Surah Al-A'raf says: \"When Musa returned to his people, angry and grieved, he said: How evil is what you did in my place after me! Were you impatient for the command of your Lord? He threw down the tablets and seized his brother by the head, dragging him toward him\" (7:150). Harun answered: \"Son of my mother, the people overpowered me and nearly killed me\" (7:150), and Musa prayed: \"My Lord, forgive me and my brother, and admit us into Your mercy\" (7:151). When his anger subsided he took up the tablets again (7:154). A Muslim learns that anger for Allah's sake is real even in a prophet, and that it ends in a prayer of forgiveness.",

"prophets_200": "Surah An-Nazi'at says: \"Go to Pharaoh; he has transgressed. And say: Would you be willing to purify yourself, and that I guide you to your Lord, so that you may fear Him?\" (79:17-19). The surah has just recalled Musa's call in the sacred valley of Tuwa (79:15-16). The rest is told in a few verses: Musa showed him the greatest sign, but Pharaoh denied, gathered his people and proclaimed \"I am your most exalted lord\" (79:20-24), so Allah seized him as an example, \"and in that is a lesson for whoever fears\" (79:25-26). A Muslim learns that even a tyrant was first offered purification and guidance, and that refusing it was his own doing.",
}
