"""English — details, sira_b (60 questions)."""

D = {
"sira_091": "Anas ibn Malik reports in Sahih al-Bukhari 6038 that in ten years of service the Prophet ﷺ never said \"uff\" to him, never asked of something done \"why did you do it?\", nor of something left undone \"why did you not do it?\". \"Uff\" is the smallest sound of impatience, the very word the Qur'an forbids a child to say to ageing parents (17:23). A Muslim takes from it how to treat those who help at home: with patience, without small reproaches.",

"sira_092": "Ibn 'Abbas narrates the moment in Sahih al-Bukhari 75: the Prophet ﷺ pressed him to his chest and said, \"O Allah, teach him the Book.\" The Book is the Qur'an, sent down \"as clarification for all things and as guidance and mercy and good tidings for the Muslims\" (16:89). Ibn 'Abbas was a boy, and the prayer came with an embrace. A Muslim learns to join affection with prayer for a child, and to ask Allah first for understanding of the Qur'an.",

"sira_093": "Ibn 'Abbas relates in Sahih al-Bukhari 1395 the instructions the Prophet ﷺ gave Mu'adh ibn Jabal: he was going to a people of the Book and should first call them to testify that there is no god but Allah and that Muhammad is His Messenger. If they accepted, he should teach them the five daily prayers Allah had made a duty; then, that a charity was due from their rich to their poor. A Muslim learns that the call begins with Allah's oneness and moves step by step.",

"sira_094": "Anas reports in Sahih al-Bukhari 3744 that the Prophet ﷺ said every nation has a trustworthy one, and that the trustworthy one of this nation is Abu 'Ubayda ibn al-Jarrah. Amin was the title Makkah had given the Prophet ﷺ before his mission, and here he gives it to a companion publicly. The Qur'an counts among the successful \"those who are to their trusts and their promises attentive\" (23:8). A Muslim takes from it that being trusted is a rank, one a leader honours in public.",

"sira_095": "Zayd ibn Thabit tells it in Sahih al-Bukhari 4986. After losses among the reciters at al-Yamama, 'Umar urged Abu Bakr to gather the Qur'an before more was lost, and Abu Bakr, unwilling at first to do what the Prophet ﷺ had not done, agreed. He told Zayd he was a wise young man who had written the revelation. Zayd said moving a mountain would have been lighter, and gathered the Qur'an from parchments, palm stalks and the memories of men. A Muslim learns how carefully his Book was preserved.",

"sira_096": "Anas ibn Malik relates in Sahih al-Bukhari 4987 how the official copies came about. Hudhayfa, alarmed by differences in recitation among Muslims of Syria and Iraq, asked 'Uthman to save the community before it differed over its Book as earlier communities had. 'Uthman borrowed from Hafsa the sheets gathered under Abu Bakr, had Zayd ibn Thabit and three men of Quraysh copy them, and sent a copy to every province. A Muslim learns that the unity of the Qur'an's text was guarded by the companions themselves.",

"sira_097": "Every biography records that Salman was born in Persia and left his home in search of the true religion, serving Christian monks before being sold as a slave and carried to Yathrib. There, after the Hijra, he watched the Prophet ﷺ for the signs he expected, embraced Islam, and gained his freedom. At the siege of Madinah it was Salman who proposed the trench. A Muslim learns that truth is worth a long journey, and that Islam made Persian, Arab and Abyssinian one family.",

"sira_098": "The biographies agree that Suhayb was born an Arab, taken captive as a child and raised among the Byzantines, and came to Makkah, where he gained his freedom and embraced Islam. When he set out for Madinah, Quraysh pursued him, and he bought his way through by handing over all the wealth he had earned. The Prophet ﷺ greeted him saying that Suhayb's trade had been profitable. A Muslim learns that a believer counts faith and the Prophet's ﷺ company as worth more than all he owns.",

"sira_099": "Al-Masjid an-Nabawi is the mosque the Prophet ﷺ founded on arriving in Madinah; every biography records that he built it with his companions from mud brick and palm trunks, carrying bricks himself. His wives' rooms opened onto it, the poor of the Suffa sheltered in it, and there he taught, judged and led the prayer for ten years. He was buried in 'Aisha's room beside it, within the mosque today. A Muslim sees in it the heart of the first community, where prayer and daily life were one.",

"sira_100": "The name stands in four verses: \"Muhammad is not but a messenger; messengers have passed on before him\" (3:144); \"Muhammad is not the father of any one of your men, but the Messenger of Allah and the Seal of the Prophets\" (33:40); belief \"in what has been sent down upon Muhammad\" (47:2); and \"Muhammad is the Messenger of Allah\" (48:29). In 61:6 'Isa announces a messenger \"whose name is Ahmad\". A Muslim learns to find his Prophet ﷺ named in the Book he recites.",

"sira_101": "The verse reads: \"There has certainly been for you in the Messenger of Allah an excellent example for anyone whose hope is in Allah and the Last Day and who remembers Allah often\" (33:21). It belongs to the siege of Madinah in Surah al-Ahzab, when the enemy came \"from above you and from below you\" (33:10), and the believers, seeing the armies, said this was what Allah had promised (33:22). A Muslim takes from it that following the Prophet ﷺ means copying his conduct, especially in hardship.",

"sira_102": "Every biography records that the Prophet's ﷺ first child by Khadija was a son, al-Qasim, born before the revelation, and that by Arab custom the father was thereafter called Abu al-Qasim. The boy died while still small, as did the other son born to Khadija, 'Abdullah, yet the kunya stayed with the Prophet ﷺ all his life. A kunya in Arab usage marks honour and closeness. A Muslim learns that behind this familiar title stands a father who buried his children and bore it with patience.",

"sira_103": "The biographies agree that Ibrahim was born in Madinah to Mariya and nursed in a home the Prophet ﷺ often visited. The child died as an infant, and the Prophet ﷺ held him as he was dying and wept. That day the sun was eclipsed, and people said it was for Ibrahim; the Prophet ﷺ told them the sun and moon are two signs of Allah, not eclipsed for anyone's death. A Muslim learns that tears are allowed, and that nature's signs are tied to no man.",

"sira_104": "All the biographies record that Khadija was a merchant, and that having heard of the honesty of Muhammad ﷺ she sent him with her caravan to Syria with her servant Maysara, who came back praising him. The trade prospered, and she sent word proposing marriage. When the first revelation came she was the first to believe and calmed him, saying Allah would never disgrace a man who kept ties of kinship and helped the weak. A Muslim learns that his mission began in a marriage built on trust.",

"sira_105": "Every biography records the rebuilding of the Ka'ba. When the walls reached the height of the Black Stone, each clan claimed to set it, and the dispute neared bloodshed until they agreed that the first man through the gate would decide. It was Muhammad ﷺ, and they accepted al-Amin's judgement. He spread his cloak, laid the Stone on it, had a chief of each clan lift an edge, and set it himself. A Muslim learns that a fair solution giving everyone a share ends a quarrel.",

"sira_106": "The biographies agree that the Prophet ﷺ was forty when the revelation began, and that he had taken to withdrawing to the cave of Hira to worship alone. The Qur'an names the month: \"the month of Ramadan in which the Qur'an was sent down\" (2:185). Jibril came to him there with \"Read in the name of your Lord who created\" (96:1). Forty is the age the Qur'an describes as full maturity (46:15). A Muslim learns that the mission began in solitude and reflection.",

"sira_107": "Sahih al-Bukhari 3 describes Waraqa ibn Nawfal as Khadija's cousin, a Christian before Islam who wrote from the Gospel in Hebrew. Khadija said, \"Listen to your nephew,\" and after hearing of Hira Waraqa said this was the Namus Allah had sent down to Musa, and wished he were young for the day his people would drive him out. Asked if they would, Waraqa answered that no man had ever brought what he brought without meeting hostility. A Muslim learns that a man of the earlier Scriptures recognised his mission.",

"sira_108": "Ibn 'Abbas relates in Sahih al-Bukhari 4770 that when \"And warn your closest kindred\" (26:214) was revealed, the Prophet ﷺ climbed as-Safa and called the clans of Quraysh. He asked whether they would believe him if he said horsemen were about to attack, and they said they had known only truth from him. He said he warned them of a severe punishment. Abu Lahab wished him ruin, and \"May the hands of Abu Lahab be ruined\" (111:1) came down. A Muslim learns that his message rested on proven honesty.",

"sira_109": "Every account of the caliphate of 'Umar records that, when dated records made a fixed calendar necessary, he gathered the companions to decide from which event the years should be counted. They chose the Hijra over the Prophet's ﷺ birth or death, and made the year begin with Muharram. The Qur'an had already fixed the months: \"Indeed, the number of months with Allah is twelve months in the register of Allah\" (9:36). A Muslim learns that his calendar counts from the founding of the community.",

"sira_110": "All the biographies agree that the Prophet ﷺ entered Madinah in Rabi' al-Awwal and died in the same month of the eleventh year, ten years apart. Into them fall the great events: Badr in the second year, Uhud in the third, the siege of Madinah in the fifth, Hudaybiyya in the sixth, the conquest of Makkah in the eighth and the Farewell Pilgrimage in the tenth. The Qur'an calls the city by its old name, Yathrib (33:13). A Muslim learns that a whole community was built in one decade.",

"sira_111": "The biographies agree that from the first revelation to the Hijra the Prophet ﷺ preached in Makkah for thirteen years: three calling people quietly, the rest in public, through the emigration to Abyssinia, the boycott of his clan, the deaths of Khadija and Abu Talib and the pledges of 'Aqaba. The Qur'an describes its revelation as \"a Qur'an which We have separated, that you might recite it to the people over a prolonged period\" (17:106). A Muslim learns that the Qur'an's teaching was given in years of patience.",

"sira_112": "Al-Bara' reports in Sahih al-Bukhari 3212 that the Prophet ﷺ said to Hassan, \"Satirise them, and Jibril is with you.\" Hassan ibn Thabit was a poet of the Ansar, and the poets of Quraysh were attacking the Prophet ﷺ in verse. The Qur'an condemns poets followed by the misguided but excepts \"those who believe and do righteous deeds and remember Allah often and defend themselves after they were wronged\" (26:227). A Muslim learns that a gift for words is honoured when placed in the service of truth.",

"sira_113": "Abu Musa al-Ash'ari narrates in Sahih al-Bukhari 5048 that the Prophet ﷺ said to him, \"O Abu Musa, you have been given one of the flutes of the family of Dawud.\" The Qur'an tells that Allah gave Dawud the Zabur (4:163) and made the mountains and the birds join him in praise (21:79), the model of a praising voice. Abu Musa was reciting the Qur'an when the Prophet ﷺ heard him. A Muslim learns that a beautiful recitation is a gift the Prophet ﷺ admired.",

"sira_114": "'Abdullah ibn 'Amr reports in Sahih al-Bukhari 3758 that he heard the Prophet ﷺ say, \"Take the Qur'an from four,\" beginning with 'Abdullah ibn Mas'ud, then Salim the freed slave of Abu Hudhayfa, Mu'adh ibn Jabal and Ubayy ibn Ka'b. Ibn Mas'ud and Salim were emigrants from Makkah, Mu'adh and Ubayy were of the Ansar, so the Qur'an's teachers came from both halves of the community. A Muslim learns that the Qur'an was passed on by named teachers the Prophet ﷺ trusted, in a chain reaching back to him.",

"sira_115": "Sahih al-Bukhari 4073 records that on the day of Uhud the Prophet's ﷺ face was wounded and a front tooth was broken. The Qur'an speaks of that day, when the Muslims fled \"while the Messenger was calling you from behind\" (3:153), and consoles the wounded: \"If a wound should touch you, there has already touched the opposing people a wound similar to it\" (3:140). He stayed on the field with his companions. A Muslim learns that the Prophet ﷺ shared his community's pain in his own body.",

"sira_116": "'Ali reports in Sahih al-Bukhari 4055 that he never heard the Prophet ﷺ say to anyone \"may my father and mother be sacrificed for you\" except to Sa'd ibn Abi Waqqas, on the day of Uhud, when he told him to shoot. Sa'd was firing arrows to keep the enemy from the Prophet ﷺ. Among Arabs, offering one's parents as ransom was the strongest expression of love. A Muslim learns that courage in defending the Prophet ﷺ earned words he gave to no one else.",

"sira_117": "The biographies agree that the Muslims marched to meet a Quraysh caravan under Abu Sufyan returning from Syria, but that he turned along the coast and sent to Makkah for help, so an army came out instead. The Qur'an recalls it: \"And when Allah promised you one of the two groups, that it would be yours, and you wished that the unarmed one would be yours\" (8:7). The battle followed at Badr. A Muslim learns that what Allah chose was harder than what they wanted, and greater.",

"sira_118": "All the biographies record that Abu Sufyan, the leader of Quraysh, went out to spy on the army approaching Makkah, was brought to the Prophet ﷺ by his uncle al-'Abbas, and embraced Islam on the night before the entry. The Prophet ﷺ then honoured him by proclaiming that whoever entered the house of Abu Sufyan was safe, as was anyone who shut his door or entered the mosque. A Muslim learns that the Prophet ﷺ met his oldest enemy with safety and honour.",

"sira_119": "Ibn 'Abbas tells it in Sahih al-Bukhari 3364. Ibrahim left Hajar and Isma'il in the valley; when she asked whether Allah had commanded this and he said yes, she answered that He would not neglect them. The water ran out, the child cried with thirst, and she saw an angel dig with his heel until water gushed. She built a basin, and the Prophet ﷺ said that had she left it, Zamzam would have flowed freely. A Muslim learns that Zamzam was given to a mother who trusted Allah.",

"sira_120": "Anas reports in Sahih al-Bukhari 5872 that the Prophet ﷺ had a ring of silver made, engraved \"Muhammad Rasul Allah\", in the story of his letters: when he decided to write to rulers, he was told that a letter without a seal would not be read. Anas adds that the ring's whiteness still stood before his eyes. The three words are the second half of the testimony of faith. A Muslim learns that the Prophet ﷺ used the means of his time to make his message received.",

"sira_121": "'Aisha reports in Sahih al-Bukhari 5431 that the Messenger of Allah ﷺ loved sweet things and honey. Her short sentence shows him taking pleasure in good food without excess. The Qur'an speaks of honey as a healing: from the bees \"there emerges from their bellies a drink, varying in colours, in which there is healing for people\" (16:69). His taste was for something the Qur'an names among Allah's signs. A Muslim learns that enjoying lawful food with gratitude is part of the Prophet's ﷺ way.",

"sira_122": "Abu Qatada reports in Sahih Muslim 1162 that the Prophet ﷺ was asked about fasting on Monday and answered that it was the day he was born and the day revelation came down to him. The same hadith records that fasting the day of 'Arafa expiates the year before and the year after, and 'Ashura the year before. Birth and mission fall on the same weekday, and he honoured it not with a feast but with a fast. A Muslim learns that gratitude for a blessing is shown by worship.",

"sira_123": "As-Sa'ib ibn Yazid relates in Sahih al-Bukhari 3541 that as a boy he was taken by his aunt to the Prophet ﷺ; the Prophet ﷺ stroked his head, prayed for blessing and made ablution, and the boy drank from the water. Then he stood behind him and saw the seal of prophethood between his shoulders, like the button of a tent. The Qur'an calls him \"the Seal of the Prophets\" (33:40). A Muslim learns that even children who met the Prophet ﷺ remembered him closely.",

"sira_124": "Sahl ibn Sa'd relates in Sahih al-Bukhari 917 that the Prophet ﷺ asked a woman to have her carpenter slave make him something of wood to sit on when addressing the people, made from the tamarisk of al-Ghaba. Once it stood in the mosque, the Prophet ﷺ prayed on it, stepped down backwards to prostrate at its foot, then told the people he had done this so they would learn his prayer. A Muslim learns that the Prophet ﷺ showed the prayer as well as describing it.",

"sira_125": "Every biography records that the Aws and the Khazraj had fought each other for generations, and that men of the Khazraj met the Prophet ﷺ at Makkah, accepted his call, and returned with men of the Aws to pledge allegiance at 'Aqaba. The Qur'an reminds them: \"Remember the favour of Allah upon you when you were enemies and He brought your hearts together and you became, by His favour, brothers\" (3:103). A Muslim learns that faith turned old enemies into one people.",

"sira_126": "The verse reads: \"The Prophet is more worthy of the believers than themselves, and his wives are their mothers\" (33:6). Surah al-Ahzab addresses them directly, \"O wives of the Prophet, you are not like any other women\" (33:32), and forbids the believers ever to marry them after him, calling that \"in the sight of Allah an enormity\" (33:53). A Muslim learns to speak of Khadija and 'Aisha as his mothers, and to receive what they passed on from the Prophet's ﷺ home as a mother's teaching.",

"sira_127": "All the biographies agree that the Prophet ﷺ left Makkah with Abu Bakr in the year corresponding to 622, hid three days in the cave of Thawr while Quraysh searched, and reached Madinah. The Qur'an recalls the cave: \"when those who disbelieved had driven him out as one of two, when they were in the cave and he said to his companion, 'Do not grieve; indeed Allah is with us'\" (9:40). A Muslim learns that his calendar began with a journey made in trust.",

"sira_128": "Anas tells it in Sahih al-Bukhari 2048. When 'Abd ar-Rahman ibn 'Awf arrived, the Prophet ﷺ made him the brother of Sa'd ibn ar-Rabi', who offered him half his property. 'Abd ar-Rahman asked only to be shown the market, and traded at a profit. Later he came with a trace of yellow perfume, having married for gold the weight of a date-stone, and the Prophet ﷺ told him to give a wedding feast, even with one sheep. A Muslim learns to accept help without living on it.",

"sira_129": "Ubayy ibn Ka'b relates in Sahih Muslim 810 that the Prophet ﷺ asked him, \"O Abu al-Mundhir, do you know which verse of the Book of Allah is the greatest?\" Ubayy answered with the Throne Verse, \"Allah, there is no god but He, the Ever-Living, the Sustainer of existence\" (2:255), which goes on to say that His Kursi extends over the heavens and the earth. The Prophet ﷺ struck his chest and said, \"May knowledge delight you, Abu al-Mundhir.\" A Muslim learns to know this verse and its place.",

"sira_130": "Every biography records that when the Prophet ﷺ entered Madinah the Ansar begged him to lodge with them, and he told them to let his she-camel go, for she was under command. She walked on until she knelt at a drying-place belonging to two orphan boys of Banu an-Najjar. Though they offered it as a gift, he insisted on paying, and there the mosque was built. A Muslim learns that the Prophet ﷺ favoured no clan and paid a fair price even to orphans who wished to give.",

"sira_131": "The biographies record three sons: al-Qasim and 'Abdullah, both born to Khadija, and Ibrahim, born in Madinah to Mariya; each died in early childhood. His four daughters, Zaynab, Ruqayya, Umm Kulthum and Fatima, grew up. The Qur'an states the outcome: \"Muhammad is not the father of any one of your men, but the Messenger of Allah and the Seal of the Prophets\" (33:40). A Muslim learns that the Prophet ﷺ knew the grief of burying children, and that his message was carried on without a son.",

"sira_132": "All the biographies agree that Zayd ibn Haritha was taken captive as a boy, was given by Khadija to the Prophet ﷺ, and that when his father came for him, Zayd chose to stay. The Prophet ﷺ freed and adopted him; he was called Zayd ibn Muhammad until the Qur'an ended such naming: \"Call them by the names of their fathers\" (33:5). He is the only companion named in the Qur'an (33:37) and fell commanding at Mu'ta. A Muslim learns what love between master and freed man can be.",

"sira_133": "Ibn 'Umar reports in Sahih al-Bukhari 4469 that the Prophet ﷺ sent out a force under Usama ibn Zayd, and when people criticised his command he said that those who criticised Usama had criticised his father's command before him; that his father had been worthy and among the dearest to him; and that this one was among the dearest to him after him. Usama was very young, and his father had commanded at Mu'ta. A Muslim learns that leadership is given for merit rather than age.",

"sira_134": "Every biography records that Zamzam had been filled in long before, and that 'Abd al-Muttalib was shown its place in a dream and dug it out with his only son, al-Harith; he then held the office of watering the pilgrims. They also record his vow to sacrifice a son if Allah gave him ten, and that when the lot fell on 'Abdullah, the future father of the Prophet ﷺ, he was ransomed with a hundred camels. A Muslim learns that the Prophet's ﷺ grandfather served the pilgrims.",

"sira_135": "All the biographies put the Muslims at Badr at a little over three hundred men, facing a Quraysh army of close to a thousand. The Qur'an records the imbalance: \"Allah had already given you victory at Badr while you were few\" (3:123), and promises help from heaven: \"Is it not sufficient for you that your Lord should reinforce you with three thousand angels sent down?\" (3:124). Those who were at Badr were honoured all their lives. A Muslim learns that victory is not decided by numbers.",

"sira_136": "Every biography records that the Prophet ﷺ was born in Makkah in Rabi' al-Awwal in the Year of the Elephant, the year Abraha marched with an elephant to destroy the Ka'ba. The Qur'an recalls it: \"Have you not considered how your Lord dealt with the companions of the elephant?\" (105:1). His father 'Abdullah had died before his birth, his mother was Amina, and he was nursed by Halima. A Muslim learns that Allah protected the House in the very year its last Prophet ﷺ was born.",

"sira_137": "The biographies agree that the Prophet ﷺ reached Madinah in Rabi' al-Awwal and halted first at Quba, where he founded a mosque, and that he entered the city on a Friday, praying the first Friday prayer on the way. The Qur'an speaks of Quba as \"a mosque founded on righteousness from the first day\" (9:108). Every household of the Ansar wished to host him. A Muslim learns that the first thing the Prophet ﷺ built in his new home, before any house of his own, was a place of prayer.",

"sira_138": "Every biography records that Quraysh wrote a document binding themselves not to trade or intermarry with Banu Hashim and Banu al-Muttalib until they handed over Muhammad ﷺ, and hung it inside the Ka'ba. Abu Talib withdrew with the whole clan into his valley outside Makkah, where they suffered hunger for about three years. It ended when men of Quraysh ashamed of it had the document torn up, and it was found eaten away except for the name of Allah. A Muslim learns that patience outlasted the pact.",

"sira_139": "All the biographies agree that after the first revelation the Prophet ﷺ spoke of his message only to those closest to him, and that the first to believe were Khadija, Abu Bakr, 'Ali and Zayd ibn Haritha. For about three years the believers met quietly in the house of al-Arqam. Then the Qur'an commanded, \"Then declare what you are commanded\" (15:94), and \"And warn your closest kindred\" (26:214). A Muslim learns that the call grew step by step, from a trusted circle to the whole city.",

"sira_140": "Ibn 'Abbas relates in Sahih al-Bukhari 3364 that when the water was gone and Isma'il cried with thirst, Hajar climbed as-Safa to look for anyone, came down, and in the valley lifted her garment and ran like a person in distress, then climbed al-Marwa. She did this seven times, and the Prophet ﷺ said that this is why pilgrims go between them. The Qur'an says: \"Indeed, as-Safa and al-Marwa are among the symbols of Allah\" (2:158). A Muslim learns that every pilgrim's sa'y retraces a mother's search.",

"sira_141": "Abu Bakra relates in Sahih al-Bukhari 2704 that he saw the Prophet ﷺ on the minbar with al-Hasan beside him, saying, \"This son of mine is a sayyid, and it may be that Allah will reconcile through him two great groups of Muslims.\" Al-Hasan was the son of 'Ali and Fatima, and the words were said before the whole congregation. The Qur'an makes peace between believers the duty of all (49:10). A Muslim learns that the Prophet ﷺ prized peace among Muslims above rule.",

"sira_142": "Every biography records that Fatima was the youngest of the Prophet's ﷺ daughters, that she married 'Ali in Madinah, and that from that marriage came al-Hasan and al-Husayn, the grandsons he carried and played with. They also record his words that Fatima was a part of him, and that she was the only one of his children to outlive him, dying about six months after him. A Muslim learns that the Prophet's ﷺ family life was one of tenderness, and that his descendants come through a daughter.",

"sira_143": "All the biographies agree that Zaynab was married to her cousin Abu al-'As ibn ar-Rabi' and stayed with him in Makkah after the Hijra. When he was captured at Badr, she sent as ransom a necklace Khadija had given her; the Prophet ﷺ recognised it, was moved, and returned it and released her husband on condition that Zaynab join her father. She emigrated to Madinah, and Abu al-'As later embraced Islam. A Muslim learns how the Prophet ﷺ loved his daughter and honoured Khadija's memory.",

"sira_144": "Every biography records that Bilal ibn Rabah was a slave in Makkah tortured by his master for embracing Islam, who kept repeating \"Ahad, Ahad\" until Abu Bakr bought and freed him. In Madinah the Prophet ﷺ chose him to give the call to prayer, and on the day Makkah was conquered Bilal climbed onto the roof of the Ka'ba and called the adhan from there. A Muslim learns that the former slave rose to call the community to prayer, and that rank is measured by faith.",

"sira_145": "Sahih al-Bukhari 3661 records the Prophet's ﷺ words that had he taken a bosom friend among men it would have been Abu Bakr, his brother and companion. The Qur'an reserves the word khalil for the bond between Ibrahim and his Lord, \"And Allah took Ibrahim as a khalil\" (4:125), and recalls Abu Bakr as \"the second of two, when they were in the cave\" (9:40). A Muslim learns that no one ranked closer to the Prophet ﷺ than Abu Bakr, and that the heart's deepest bond is kept for Allah.",

"sira_146": "Every biography records that as Ibrahim had declared Makkah a sanctuary, the Prophet ﷺ declared Madinah a sanctuary between its two tracts of black stone, and prayed for its blessing. The Qur'an calls Makkah \"a secure sanctuary\" (28:57) and names Madinah by its old name, Yathrib (33:13); the Prophet ﷺ called it Taybah. Makkah holds the Ka'ba, Madinah his mosque and grave, and together they are al-Haramayn. A Muslim learns to revere both: where the Qur'an began and where the community was built.",

"sira_147": "All the biographies agree that after the Hijra the Prophet ﷺ made the pilgrimage once, in the tenth year, and that it was called the Farewell Pilgrimage because he died months later. At 'Arafat he addressed the people, reminding them that their lives and property were sacred, and there the verse came down: \"This day I have perfected for you your religion and completed My favour upon you\" (5:3). A Muslim learns that the Hajj he performs today follows the one Hajj the Prophet ﷺ led.",

"sira_148": "Anas relates in Sahih al-Bukhari 3149 that walking with the Prophet ﷺ, who wore a cloak with a rough border, a Bedouin seized it and pulled so hard that it marked the Prophet's ﷺ shoulder. The man said, \"O Muhammad, order for me some of the wealth of Allah.\" The Prophet ﷺ turned, laughed, and ordered him a gift. The Qur'an says: \"And indeed, you are of a great moral character\" (68:4). A Muslim learns that the Prophet ﷺ answered rudeness with a smile and generosity.",

"sira_149": "The Qur'an opens Surah al-Isra with the journey: \"Exalted is He who took His Servant by night from al-Masjid al-Haram to al-Masjid al-Aqsa, whose surroundings We have blessed, to show him of Our signs\" (17:1). Every biography records that the Prophet ﷺ was carried that night from Makkah to Jerusalem and raised through the heavens, where the five prayers were prescribed. Quraysh mocked him, and Abu Bakr believed him at once. A Muslim learns that Jerusalem is bound to his prayer from the start.",

"sira_150": "All the biographies agree that the Prophet ﷺ died at sixty-three: forty before the revelation, thirteen in Makkah, ten in Madinah. He died in Rabi' al-Awwal in the room of 'Aisha. Abu Bakr steadied the community by reciting, \"Muhammad is not but a messenger; messengers have passed on before him. So if he was to die or be killed, would you turn back on your heels?\" (3:144). A Muslim learns that his love for the Prophet ﷺ rests on worship of Allah, who does not die.",
}
