"""English — details, sira_b (60 questions)."""

D = {
"sira_091": "Anas ibn Malik reports in Sahih al-Bukhari 6038 that he served the Prophet ﷺ for ten years, and that in all that time the Prophet ﷺ never said \"uff\" to him, never asked about something he had done \"why did you do it?\", nor about something left undone \"why did you not do it?\". \"Uff\" is the smallest sound of impatience, the very word the Qur'an forbids a child to say to ageing parents (17:23). Anas was a boy through those years, in a household where mistakes were possible every day. A Muslim takes from it how to treat those who help at home: with patience, and without the small reproaches that wound.",

"sira_092": "Ibn 'Abbas himself narrates the moment in Sahih al-Bukhari 75: the Prophet ﷺ pressed him to his chest and said, \"O Allah, teach him the Book.\" The Book is the Qur'an, which describes itself as sent down \"as clarification for all things and as guidance and mercy and good tidings for the Muslims\" (16:89). Ibn 'Abbas was still a boy, the son of the Prophet's ﷺ uncle al-'Abbas, and the prayer was made for him with an embrace rather than a lesson. A Muslim learns to join affection with prayer for a child, and to ask Allah for understanding of the Qur'an before any other knowledge.",

"sira_093": "Ibn 'Abbas relates in Sahih al-Bukhari 1395 the instructions the Prophet ﷺ gave Mu'adh ibn Jabal when he sent him to Yemen. He told him that he was going to a people of the Book and should first call them to testify that there is no god but Allah and that Muhammad is His Messenger. If they accepted that, he should teach them that Allah had made five prayers a duty on them in every day and night; and if they accepted that, that Allah had made a charity a duty on their wealth, taken from their rich and given to their poor. A Muslim learns that the call begins with the oneness of Allah and moves one step at a time.",

"sira_094": "Anas ibn Malik reports the words in Sahih al-Bukhari 3744: the Prophet ﷺ said that every nation has a trustworthy one, and that the trustworthy one of this nation is Abu 'Ubayda ibn al-Jarrah. The word amin was the title Makkah had given the Prophet ﷺ himself before his mission, and here he gives it to a companion before the whole community. The Qur'an counts among the successful believers \"those who are to their trusts and their promises attentive\" (23:8). A Muslim takes from it that being trusted is a rank in itself, and one that a leader names and honours in public.",

"sira_095": "Zayd ibn Thabit tells the story himself in Sahih al-Bukhari 4986. After heavy losses among the reciters at al-Yamama, 'Umar urged Abu Bakr to have the Qur'an gathered before more of it was lost with them; Abu Bakr at first hesitated to do what the Prophet ﷺ had not done, then his heart opened to it. He told Zayd that he was a wise young man, above suspicion, who had written the revelation for the Messenger of Allah, and charged him with the search. Zayd said that moving a mountain would have been lighter for him, and gathered the Qur'an from parchments, flat stones, palm stalks and the memories of men. A Muslim learns how carefully the text he reads today was preserved.",

"sira_096": "Anas ibn Malik relates in Sahih al-Bukhari 4987 how the official copies came about. Hudhayfa ibn al-Yaman, returning from campaigns where Muslims of Syria and Iraq had disagreed over recitation, asked 'Uthman to save the community before it differed over its Book as earlier communities had. 'Uthman borrowed from Hafsa the sheets gathered under Abu Bakr and had Zayd ibn Thabit and three men of Quraysh copy them, instructing that any difference be written in the tongue of Quraysh, in which the Qur'an was revealed. He returned the sheets to Hafsa and sent a copy to every province. A Muslim learns that the unity of the Qur'an's text was guarded by the companions themselves.",

"sira_097": "Every standard biography records that Salman was born in Persia and left his home and its fire-worship in search of the true religion, serving Christian monks in the lands of Syria before being sold as a slave and carried to Yathrib. There, after the Hijra, he watched the Prophet ﷺ for the signs he had been told to look for, embraced Islam, and gained his freedom with the Prophet's ﷺ help. At the siege of Madinah it was Salman who proposed digging the trench that stopped the Confederates. A Muslim takes from his story that truth is worth a long journey, and that Islam gathered Persian, Arab and Abyssinian into one family.",

"sira_098": "The biographies agree that Suhayb was born an Arab, was taken captive as a child and raised among the Byzantines, then came to Makkah where he gained his freedom and embraced Islam in the earliest years of the call. When he set out for Madinah, men of Quraysh pursued him, and he bought his way through by handing over all the wealth he had earned in Makkah. The Prophet ﷺ greeted him on arrival with the words that Suhayb's trade had been profitable. A Muslim takes from it that a believer counts faith and the company of the Prophet ﷺ as worth more than everything he owns.",

"sira_099": "Al-Masjid an-Nabawi is the mosque the Prophet ﷺ founded on arriving in Madinah, and every biography records that he built it with his companions from mud brick, with trunks of palm for pillars and palm fronds for a roof, carrying the bricks with his own hands. His wives' rooms opened onto it, the poor companions of the Suffa lived in its shelter, and he taught, judged, received delegations and led the prayer there for the ten years of Madinah. When he died he was buried in 'Aisha's room beside it, and his grave lies within the mosque today. A Muslim sees in it the heart of the first community, where prayer and daily life were one.",

"sira_100": "The name Muhammad stands in four verses. \"Muhammad is not but a messenger; messengers have passed on before him\" (3:144), revealed about Uhud; \"Muhammad is not the father of any one of your men, but the Messenger of Allah and the Seal of the Prophets\" (33:40); the believers are those who believe \"in what has been sent down upon Muhammad, and it is the truth from their Lord\" (47:2); and \"Muhammad is the Messenger of Allah, and those with him are firm against the disbelievers, merciful among themselves\" (48:29). In 61:6 'Isa announces a messenger to come after him \"whose name is Ahmad\". A Muslim learns to find his Prophet ﷺ named in the Book he recites.",

"sira_101": "The full verse reads: \"There has certainly been for you in the Messenger of Allah an excellent example for anyone whose hope is in Allah and the Last Day and who remembers Allah often\" (33:21). It stands in Surah al-Ahzab among the verses on the siege of Madinah by the Confederates, when the enemy came \"from above you and from below you\" and hearts reached the throats (33:10), and the next verse recalls how the believers, seeing the armies, said this was what Allah and His Messenger had promised them (33:22). The example is his steadiness in the hardest hour. A Muslim takes from it that following the Prophet ﷺ means copying his conduct, especially under pressure.",

"sira_102": "Every biography records that the Prophet's ﷺ first child by Khadija was a son, al-Qasim, born in Makkah before the revelation, and that by Arab custom the father was thereafter addressed as Abu al-Qasim, the father of al-Qasim. The boy died while still small, as did the other son born to Khadija, 'Abdullah, yet the kunya stayed with the Prophet ﷺ all his life, and companions and even strangers called him by it. A kunya in Arab usage is a mark of honour and closeness rather than a bare name. A Muslim learns that behind this familiar title stands a father who buried his children and bore it with patience.",

"sira_103": "The biographies agree that Ibrahim was born in Madinah to Mariya, the Copt, in the last years of the Prophet's ﷺ life, and that he was given to a wet-nurse whom the Prophet ﷺ visited to hold his son. He died before he was two, and when the Prophet ﷺ held him as he was dying his eyes filled with tears. On the day of his death the sun was eclipsed, and people said it was for Ibrahim; the Prophet ﷺ told them that the sun and the moon are two signs of Allah that are not eclipsed for anyone's death or life. A Muslim learns that tears are allowed, that words must stay within what pleases Allah, and that nature's signs are not tied to any man.",

"sira_104": "All the biographies record that Khadija bint Khuwaylid was a merchant of Quraysh who hired men to trade with her goods, and that having heard of the honesty of Muhammad ﷺ she sent him with her caravan to Syria in the company of her servant Maysara, who returned full of praise for him. The trade prospered, and she sent word proposing marriage; he was about twenty-five. She bore him all his children except Ibrahim, and when the first revelation came she was the first to believe and the one who calmed him, saying that Allah would never disgrace a man who kept ties of kinship and helped the weak. A Muslim learns that his mission began in a marriage built on trust.",

"sira_105": "Every biography records this event from the rebuilding of the Ka'ba by Quraysh before the revelation. When the walls reached the height of the Black Stone, each clan claimed the honour of setting it in place, and the dispute came near to bloodshed until they agreed that the first man to enter through the gate would decide. It was Muhammad ﷺ, and they cried out that al-Amin, the trustworthy, had come and that they accepted his judgement. He spread his cloak, laid the Stone on it, had a chief of each clan take an edge, and when they had lifted it together he set it with his own hand. A Muslim learns that a fair solution which gives everyone a share ends a quarrel.",

"sira_106": "The biographies agree that the Prophet ﷺ was forty when the revelation began, and that he had taken to withdrawing to the cave of Hira on a mountain outside Makkah to worship alone. The Qur'an itself names the month: \"the month of Ramadan in which the Qur'an was sent down\" (2:185). The angel Jibril came to him there with the first verses, \"Read in the name of your Lord who created\" (96:1), and he returned home trembling to Khadija. Forty is the age the Qur'an describes as full maturity, when a person turns to Allah in gratitude (46:15). A Muslim learns that the mission began not in a crowd but in solitude and reflection.",

"sira_107": "Sahih al-Bukhari 3 describes Waraqa ibn Nawfal as Khadija's cousin, a man who had become a Christian before Islam and used to write from the Gospel in Hebrew, and who was by then old and blind. Khadija said to him, \"Listen to your nephew,\" and after hearing what had happened at Hira Waraqa said that this was the Namus, the angel Allah had sent down to Musa, and wished he were young and strong for the day the Prophet's ﷺ people would drive him out. When the Prophet ﷺ asked whether they would really expel him, Waraqa answered that no man had ever brought what he brought without meeting hostility. A Muslim learns that the truth of his mission was recognised at once by one who knew the earlier Scriptures.",

"sira_108": "Ibn 'Abbas relates in Sahih al-Bukhari 4770 that when \"And warn your closest kindred\" (26:214) was revealed, the Prophet ﷺ climbed as-Safa and called the clans of Quraysh by name until they gathered. He asked whether they would believe him if he told them horsemen were in the valley about to attack, and they answered that they had never known anything from him but truth. He said he was then a warner to them before a severe punishment. Abu Lahab replied that he wished him ruin for gathering them for this, and the surah \"May the hands of Abu Lahab be ruined\" (111:1) came down about him. A Muslim learns that his message rested on a lifetime of proven honesty.",

"sira_109": "Every account of the caliphate of 'Umar ibn al-Khattab records that, when dated letters and records made a fixed calendar necessary, he gathered the companions to decide from which event the years should be counted. They chose the Hijra, the emigration to Madinah, over the Prophet's ﷺ birth or death, and the year was made to begin with the month of Muharram. The Qur'an had already fixed the number of months: \"Indeed, the number of months with Allah is twelve months in the register of Allah\" (9:36). A Muslim learns that his calendar counts from the founding of the community rather than from a birthday.",

"sira_110": "All the biographies agree that the Prophet ﷺ entered Madinah in the month of Rabi' al-Awwal and died in the same month of the eleventh year after the Hijra, so that his life there lasted ten years. Into those years fall the events the Qur'an itself recounts: Badr in the second year, Uhud in the third, the siege of the Confederates in the fifth, the treaty of Hudaybiyya in the sixth, the conquest of Makkah in the eighth and the Farewell Pilgrimage in the tenth. The Qur'an calls Madinah by its old name Yathrib (33:13) and the city became his home and resting place. A Muslim learns that a whole community was built in one decade.",

"sira_111": "The biographies agree that from the first revelation at the age of forty to the Hijra the Prophet ﷺ preached in Makkah for thirteen years: three of them calling people quietly, the rest in public under growing hostility, through the emigration of believers to Abyssinia, the boycott of his clan, the deaths of Khadija and Abu Talib, the Night Journey and the pledges of 'Aqaba. The Qur'an describes its own revelation as spread over this long span, \"a Qur'an which We have separated, that you might recite it to the people over a prolonged period\" (17:106). A Muslim learns that most of the Qur'an's teaching on faith was given during these years of patience.",

"sira_112": "Al-Bara' ibn 'Azib reports in Sahih al-Bukhari 3212 that the Prophet ﷺ said to Hassan, \"Satirise them, and Jibril is with you.\" Hassan ibn Thabit was a poet of the Ansar, and the poets of Quraysh were attacking the Prophet ﷺ in verse, the weapon Arabs feared most. The Qur'an condemns poets followed by the misguided but excepts \"those who believe and do righteous deeds and remember Allah often and defend themselves after they were wronged\" (26:227). A Muslim learns that a talent for words is honoured when it is placed in the service of the truth, and that the answer to slander was given with the help of an angel.",

"sira_113": "Abu Musa al-Ash'ari himself narrates in Sahih al-Bukhari 5048 that the Prophet ﷺ said to him, \"O Abu Musa, you have been given one of the flutes of the family of Dawud.\" The Qur'an tells that Allah gave Dawud the Zabur (4:163) and made the mountains and the birds join him in praise (21:79), so that a voice like his is the highest praise for recitation. Abu Musa was reciting the Qur'an when the Prophet ﷺ heard him. A Muslim learns that making the recitation of the Qur'an beautiful is a gift the Prophet ﷺ himself admired, and that the voice is meant to serve the words.",

"sira_114": "'Abdullah ibn 'Amr reports in Sahih al-Bukhari 3758 that he heard the Prophet ﷺ say, \"Take the Qur'an from four,\" and that he began with 'Abdullah ibn Mas'ud, then named Salim the freed slave of Abu Hudhayfa, Mu'adh ibn Jabal and Ubayy ibn Ka'b. Two of them, Ibn Mas'ud and Salim, were emigrants from Makkah, and two, Mu'adh and Ubayy, were of the Ansar, so that the Qur'an's teachers were drawn from both halves of the community. A Muslim learns that the Qur'an was passed on by named teachers whom the Prophet ﷺ himself trusted, and that the science of its reading has a chain reaching back to him.",

"sira_115": "Sahih al-Bukhari 4073 records that on the day of Uhud the Prophet's ﷺ face was wounded and one of his front teeth was broken. The Qur'an speaks of that day in Surah Al 'Imran, when the archers left their post and the Muslims retreated \"while the Messenger was calling you from behind\" (3:153), and it consoles the wounded: \"If a wound should touch you, there has already touched the opposing people a wound similar to it\" (3:140). He stayed on the field, bleeding, and did not abandon his companions. A Muslim learns that the Prophet ﷺ shared the pain of his community in his own body, and that defeat was turned into a lesson.",

"sira_116": "'Ali ibn Abi Talib reports in Sahih al-Bukhari 4055 that he never heard the Prophet ﷺ say to anyone \"may my father and mother be sacrificed for you\" except to Sa'd ibn Abi Waqqas, on the day of Uhud, when he told him to shoot. Sa'd was firing arrows to keep the enemy from the Prophet ﷺ at the moment the Muslim lines had broken. Among Arabs, to offer one's parents as ransom was the strongest expression of love and gratitude a man could utter. A Muslim learns that courage in defending the Prophet ﷺ earned words he gave to no one else, and that praise given rightly is remembered for centuries.",

"sira_117": "Every biography records that in the second year after the Hijra the Muslims marched out to meet a rich Quraysh caravan under Abu Sufyan coming back from Syria, but that he changed his route along the coast and sent to Makkah for help, so that an army under Abu Jahl came out instead. The Qur'an recalls the moment: \"And when Allah promised you one of the two groups, that it would be yours, and you wished that the unarmed one would be yours\" (8:7). The battle that followed at the wells of Badr became \"the day of the Criterion\" (8:41). A Muslim learns that what Allah chose for them was harder than what they wanted, and greater.",

"sira_118": "All the biographies record that Abu Sufyan, who had led Quraysh against the Muslims at Uhud and at the Trench, came out to spy on the army approaching Makkah in the eighth year, was brought to the Prophet ﷺ by his uncle al-'Abbas, and embraced Islam on the night before the entry. The Prophet ﷺ then honoured him by proclaiming that whoever entered the house of Abu Sufyan would be safe, as would anyone who shut his door or entered the mosque. The conquest passed without a battle in the city. A Muslim learns that the Prophet ﷺ met his oldest enemy with safety and honour, and that no one is too far gone to return.",

"sira_119": "Ibn 'Abbas tells the story in Sahih al-Bukhari 3364. Ibrahim left Hajar and the infant Isma'il by the site of the House with a bag of dates and a skin of water; when she asked whether Allah had commanded this and he said yes, she answered that then He would not neglect them. The water ran out, the child cried with thirst, and after her search she heard a voice and saw an angel digging with his heel until water gushed out. She built a basin round it with her hands and scooped water into her skin, and the Prophet ﷺ said that had she left it, Zamzam would have been a flowing spring. A Muslim learns that Zamzam was given to a mother who trusted Allah.",

"sira_120": "Anas ibn Malik reports in Sahih al-Bukhari 5872 that the Prophet ﷺ had a ring of silver made and engraved with \"Muhammad Rasul Allah\", and the same account places it in the story of his letters: when he decided to write to rulers, he was told that a letter without a seal would not be read. Anas adds that the ring was in his hand and that its whiteness still stood before his eyes. The three words are the second half of the testimony of faith, and the seal carried them to kings beyond Arabia. A Muslim learns that the Prophet ﷺ used the ordinary means of his time to make sure his message would be received.",

"sira_121": "'Aisha reports in Sahih al-Bukhari 5431 that the Messenger of Allah ﷺ loved sweet things and honey. She knew his table better than anyone, and her short sentence shows him taking pleasure in good food without excess. The Qur'an speaks of honey as a healing: from the bees \"there emerges from their bellies a drink, varying in colours, in which there is healing for people\" (16:69). His taste for it was a taste for something the Qur'an names among Allah's signs. A Muslim learns that enjoying lawful food with gratitude is part of the Prophet's ﷺ way, and that the simplest details of his life were kept.",

"sira_122": "Abu Qatada reports in Sahih Muslim 1162 that the Prophet ﷺ was asked about fasting on Monday and answered that it was the day on which he was born and the day on which revelation came down to him. The same hadith records his words on other fasts: that fasting the day of 'Arafa expiates the year before and the year after, and 'Ashura the year before. Birth and mission thus fall on the same weekday, and he honoured it not with a feast but with a fast. A Muslim learns that gratitude for a blessing is shown by worship, and that the Monday fast is a way of thanking Allah for the Prophet's ﷺ coming.",

"sira_123": "As-Sa'ib ibn Yazid relates in Sahih al-Bukhari 3541 that as a boy he was taken by his aunt to the Prophet ﷺ because he was ill; the Prophet ﷺ stroked his head, prayed for blessing on him, and made ablution, and the boy drank from the water. Then he stood behind him and looked at the seal of prophethood between his shoulders, which he compared to the button of a tent. The Qur'an calls him \"the Seal of the Prophets\" (33:40), the last of them. A Muslim learns that even the children who met the Prophet ﷺ remembered him closely and lovingly, and that his companions passed on what they saw with their own eyes.",

"sira_124": "Sahl ibn Sa'd relates in Sahih al-Bukhari 917 that the Prophet ﷺ sent word to a woman to have her carpenter slave make him something of wood to sit on when he spoke to the people, and that the man made it from the tamarisk of al-Ghaba, a wooded place near Madinah. When it was set in the mosque, the Prophet ﷺ prayed on it, bowed on it, stepped down backwards to prostrate at its foot and climbed back up, then told the people that he had done this so that they could follow him and learn his prayer. A Muslim learns that the minbar served both preaching and teaching, and that the Prophet ﷺ showed the prayer as much as he described it.",

"sira_125": "Every biography records that the Aws and the Khazraj, the two Arab tribes of Yathrib, had fought each other for generations before Islam, and that men of the Khazraj first met the Prophet ﷺ at Makkah during the pilgrimage, accepted his call, and returned the next years with men of the Aws to pledge allegiance at 'Aqaba. The Qur'an reminds them of it: \"Remember the favour of Allah upon you when you were enemies and He brought your hearts together and you became, by His favour, brothers\" (3:103). Because they sheltered the emigrants, the Qur'an praises them as those who \"give preference over themselves, even though they are in privation\" (59:9). A Muslim learns that faith turned old enemies into one people.",

"sira_126": "The verse reads: \"The Prophet is more worthy of the believers than themselves, and his wives are their mothers\" (33:6). Surah al-Ahzab addresses the wives of the Prophet ﷺ directly, telling them, \"O wives of the Prophet, you are not like any other women\" (33:32), and forbids the believers ever to marry them after him, calling that \"in the sight of Allah an enormity\" (33:53). The title places every believer in the position of a child towards them, owing respect and care. A Muslim learns to speak of Khadija, 'Aisha and the others as his mothers, and to receive the many teachings they passed on from the Prophet's ﷺ home as a mother's teaching.",

"sira_127": "All the biographies agree that the Prophet ﷺ left Makkah with Abu Bakr in the year corresponding to 622, hid three days in the cave of Thawr while Quraysh searched for them, and reached Madinah by the coastal route. The Qur'an recalls the cave: \"when those who disbelieved had driven him out as one of two, when they were in the cave and he said to his companion, 'Do not grieve; indeed Allah is with us'\" (9:40). Under 'Umar this year was chosen as the first of the Muslim calendar, so that Hijri dates count from it. A Muslim learns that the calendar he uses began with a journey made in trust.",

"sira_128": "Anas ibn Malik tells the story in Sahih al-Bukhari 2048. When 'Abd ar-Rahman ibn 'Awf arrived in Madinah, the Prophet ﷺ made him the brother of Sa'd ibn ar-Rabi' of the Ansar, who offered to share his property with him in halves. 'Abd ar-Rahman blessed him and asked only to be shown the market, where he traded and soon made a profit. Some time later he came to the Prophet ﷺ with a trace of yellow perfume on him and said he had married a woman of the Ansar, giving her gold the weight of a date-stone; the Prophet ﷺ told him to hold a wedding feast, even with one sheep. A Muslim learns to accept help without living on it, and to earn with his own hands.",

"sira_129": "Ubayy ibn Ka'b relates in Sahih Muslim 810 that the Prophet ﷺ asked him, \"O Abu al-Mundhir, do you know which verse of the Book of Allah with you is the greatest?\" Ubayy first said that Allah and His Messenger know best, and when asked again answered with the Throne Verse, \"Allah, there is no god but He, the Ever-Living, the Sustainer of existence\" (2:255). The Prophet ﷺ struck him on the chest and said, \"May knowledge delight you, Abu al-Mundhir.\" The verse goes on to say that neither drowsiness nor sleep overtakes Him and that His Kursi extends over the heavens and the earth. A Muslim learns to know this verse and its place, and to love knowledge as the Prophet ﷺ loved it in Ubayy.",

"sira_130": "Every biography records that when the Prophet ﷺ entered Madinah each clan of the Ansar took hold of his she-camel's reins and begged him to lodge with them, and that he told them to let her go, for she was under command. She walked on until she knelt at a place used for drying dates, which belonged to two orphan boys of Banu an-Najjar. Though they and their guardians offered it as a gift, he insisted on paying for it, and there the mosque was built, with rooms beside it for his household. A Muslim learns that the Prophet ﷺ avoided favouring one clan over another and paid a fair price even to orphans who wanted to give.",

"sira_131": "The biographies record three sons: al-Qasim, from whom the Prophet ﷺ took his kunya, and 'Abdullah, both born to Khadija in Makkah, and Ibrahim, born in Madinah to Mariya, and that each of them died in early childhood. His four daughters, Zaynab, Ruqayya, Umm Kulthum and Fatima, lived to marry. The Qur'an states the outcome plainly: \"Muhammad is not the father of any one of your men, but the Messenger of Allah and the Seal of the Prophets\" (33:40). A Muslim learns that the Prophet ﷺ knew the grief of burying children, and that his line and his message were carried on without a son.",

"sira_132": "All the biographies agree that Zayd ibn Haritha was taken captive as a boy and sold, came into Khadija's possession and was given by her to the Prophet ﷺ, and that when his father and uncle came to Makkah to ransom him, Zayd chose to stay with the Prophet ﷺ rather than return home. The Prophet ﷺ freed him and adopted him, so that for years he was called Zayd ibn Muhammad, until the Qur'an ended the naming of adopted sons after their adopters: \"Call them by the names of their fathers\" (33:5). He is the only companion named in the Qur'an (33:37) and fell commanding the army at Mu'ta. A Muslim learns what love between a master and a freed man can be.",

"sira_133": "Ibn 'Umar reports in Sahih al-Bukhari 4469 that the Prophet ﷺ sent out a force under Usama ibn Zayd, and that when people criticised his command he rose and said that those who criticised Usama's command had criticised his father's command before him; that his father had been worthy of command and among the dearest of people to him; and that this one was among the dearest of people to him after him. Usama was very young, and his father Zayd had commanded at Mu'ta. A Muslim learns that leadership is given for merit and trust rather than age, and that the Prophet ﷺ defended his choice openly before the people.",

"sira_134": "Every biography records that the well of Zamzam had been filled in and lost long before, and that 'Abd al-Muttalib, chief of Banu Hashim, was shown its place in a dream and dug it out with his only son at the time, al-Harith, despite the objections of Quraysh. He then held the office of giving water to the pilgrims from it. The biographies also record his vow, made while he had few sons, to sacrifice one if Allah gave him ten, and that when the lot fell on 'Abdullah, the future father of the Prophet ﷺ, he was ransomed with a hundred camels. A Muslim learns that the Prophet's ﷺ grandfather served the pilgrims of the House, and that Zamzam still flows for them.",

"sira_135": "All the biographies put the Muslims at Badr at a little over three hundred men, with two horses and seventy camels between them, facing a Quraysh army of close to a thousand. The Qur'an itself records the imbalance: \"Allah had already given you victory at Badr while you were few\" (3:123), and tells that the Prophet ﷺ promised the believers help from heaven, \"Is it not sufficient for you that your Lord should reinforce you with three thousand angels sent down?\" (3:124). Those who were at Badr were honoured among the companions for the rest of their lives. A Muslim learns that victory is not decided by numbers, and that a small band standing firm can be given what a great army is denied.",

"sira_136": "Every biography records that the Prophet ﷺ was born in Makkah in the month of Rabi' al-Awwal in the Year of the Elephant, the year in which Abraha marched from Yemen with an elephant to destroy the Ka'ba and was turned back. The Qur'an recalls that year: \"Have you not considered how your Lord dealt with the companions of the elephant?\" (105:1). His father 'Abdullah had died before his birth, his mother was Amina, and he was nursed in the desert by Halima of Banu Sa'd. A Muslim learns that Allah protected the House in the very year its last Prophet ﷺ was born, and that he began life as an orphan.",

"sira_137": "The biographies agree that the Prophet ﷺ reached the outskirts of Madinah in Rabi' al-Awwal and halted first at Quba, where he founded a mosque, and that he entered the city itself on a Friday, praying the first Friday prayer on the way among Banu Salim. The Qur'an speaks of Quba as \"a mosque founded on righteousness from the first day\" (9:108), which is more worthy to stand in. The Ansar came out to meet him, and every household wished to be his host. A Muslim learns that the first thing the Prophet ﷺ built in his new home, before any house of his own, was a place of prayer.",

"sira_138": "Every biography records that Quraysh, unable to stop the call, wrote a document binding themselves not to trade or intermarry with Banu Hashim and Banu al-Muttalib until they handed over Muhammad ﷺ, and hung it inside the Ka'ba. Abu Talib withdrew with the whole clan, believers and unbelievers alike, into his valley outside Makkah, where they suffered hunger for about three years. The boycott ended when a few men of Quraysh who were ashamed of it demanded the document be torn up, and it was found eaten away except for the name of Allah. A Muslim learns that the Prophet's ﷺ own clan stood by him through hardship, and that patience outlasted the pact.",

"sira_139": "All the biographies agree that after the first revelation the Prophet ﷺ spoke of his message only to those closest to him, and that the first to believe were Khadija, Abu Bakr, 'Ali and Zayd ibn Haritha, followed by others whom Abu Bakr brought. For about three years the believers met quietly, gathering in the house of al-Arqam near as-Safa to learn what was being revealed. Then the Qur'an commanded, \"Then declare what you are commanded and turn away from the polytheists\" (15:94), and \"And warn your closest kindred\" (26:214). A Muslim learns that the call grew step by step, from a small trusted circle to the whole city.",

"sira_140": "Ibn 'Abbas relates in Sahih al-Bukhari 3364 that when the water Ibrahim had left was gone and the child Isma'il was writhing with thirst, Hajar climbed as-Safa, the nearest hill, to look for anyone, then came down, and when she reached the bottom of the valley she lifted her garment and ran like a person in distress until she had crossed it, then climbed al-Marwa and looked again. She did this seven times, and the Prophet ﷺ said that this is why people go between the two hills. The Qur'an confirms it: \"Indeed, as-Safa and al-Marwa are among the symbols of Allah\" (2:158). A Muslim learns that every pilgrim's sa'y retraces a mother's search for her child.",

"sira_141": "Abu Bakra relates in Sahih al-Bukhari 2704 that he saw the Prophet ﷺ on the minbar with al-Hasan beside him, looking now at the people and now at the boy, and saying, \"This son of mine is a sayyid, and it may be that Allah will reconcile through him two great groups of Muslims.\" Al-Hasan was the son of 'Ali and Fatima, the Prophet's ﷺ grandson, and the words were said before the whole congregation. The Qur'an says that making peace between believers is the duty of all of them (49:10). A Muslim learns that the Prophet ﷺ prized peace among Muslims above rule, and that a child was praised in the mosque for what he would one day do.",

"sira_142": "Every biography records that Fatima was the youngest of the Prophet's ﷺ daughters, born to Khadija in Makkah, that she married 'Ali ibn Abi Talib in Madinah, and that from that marriage came al-Hasan and al-Husayn, the two grandsons the Prophet ﷺ carried and played with. The biographies also record his words that Fatima was a part of him, and that she was the only one of his children to outlive him, dying about six months after him. A Muslim learns that the Prophet's ﷺ family life was one of tenderness, and that his descendants come through a daughter who lived simply.",

"sira_143": "All the biographies agree that Zaynab, the eldest of the Prophet's ﷺ daughters, was married before the revelation to her cousin Abu al-'As ibn ar-Rabi', and that she stayed with him in Makkah after the Hijra. When Abu al-'As was captured at Badr, she sent as his ransom a necklace Khadija had given her on her wedding day; the Prophet ﷺ recognised it, was moved, and with the companions' agreement returned it and released her husband on condition that he let Zaynab join her father. She emigrated to Madinah, and Abu al-'As later embraced Islam and rejoined her. A Muslim learns how the Prophet ﷺ loved his daughter and honoured his own marriage's memory.",

"sira_144": "Every biography records that Bilal ibn Rabah, an Abyssinian by origin, was a slave in Makkah who was tortured under the noon sun by his master for embracing Islam, and who kept repeating \"Ahad, Ahad\", one, one, until Abu Bakr bought and freed him. In Madinah, when the call to prayer was instituted, the Prophet ﷺ chose him to give it, and on the day Makkah was conquered Bilal climbed onto the roof of the Ka'ba and called the adhan from there. A Muslim learns that in Islam the former slave rose to the honour of calling the community to prayer, and that rank is measured by faith rather than by birth.",

"sira_145": "The hadith stands in Sahih al-Bukhari 3661, in the chapter on the Prophet's ﷺ words that if he had taken a bosom friend from among men he would have taken Abu Bakr, adding that Abu Bakr was nonetheless his brother and companion. The Qur'an reserves the word khalil for the bond between Ibrahim and his Lord: \"And Allah took Ibrahim as a khalil\" (4:125), and it names Abu Bakr's companionship without naming him, \"the second of two, when they were in the cave\" (9:40). The Prophet ﷺ kept the deepest intimacy of the heart for Allah alone. A Muslim learns that no one ranked closer to the Prophet ﷺ than Abu Bakr, and that Allah stands above every friendship.",

"sira_146": "Every biography records that as Ibrahim had declared Makkah a sanctuary, the Prophet ﷺ declared Madinah a sanctuary between its two tracts of black stone, and prayed that Allah bless it as He had blessed Makkah. The Qur'an calls Makkah \"a secure sanctuary\" (28:57) and names Madinah by its old name, Yathrib (33:13); the Prophet ﷺ called it Taybah, the good. Makkah holds the Ka'ba and Madinah his mosque and grave, and the two together are al-Haramayn, the two sanctuaries. A Muslim learns to hold both cities in reverence: the one where the Qur'an began and the one where the community was built.",

"sira_147": "All the biographies agree that after the Hijra the Prophet ﷺ made the pilgrimage once, in the tenth year, with a great crowd of Muslims following him, and that it was called the Farewell Pilgrimage because he died months later. At 'Arafat he addressed the people from his camel, reminding them that their lives and property were sacred to one another, and the verse came down there: \"This day I have perfected for you your religion and completed My favour upon you\" (5:3). Every act of his pilgrimage was watched and recorded by those present. A Muslim learns that the rites of Hajj he performs today follow the one Hajj the Prophet ﷺ led.",

"sira_148": "Anas ibn Malik relates in Sahih al-Bukhari 3149 that he was walking with the Prophet ﷺ, who wore a cloak from Najran with a thick border, when a Bedouin seized it and pulled so hard that Anas saw the mark of the border on the Prophet's ﷺ shoulder. The man said, \"O Muhammad, order for me some of the wealth of Allah that is with you.\" The Prophet ﷺ turned, laughed, and had something given to him. The Qur'an describes him: \"And indeed, you are of a great moral character\" (68:4). A Muslim learns that the Prophet ﷺ answered rudeness with a smile and generosity, and that public wealth was there for the needy who asked.",

"sira_149": "The Qur'an opens Surah al-Isra with the journey: \"Exalted is He who took His Servant by night from al-Masjid al-Haram to al-Masjid al-Aqsa, whose surroundings We have blessed, to show him of Our signs\" (17:1). Every biography records that the Prophet ﷺ was carried that night from Makkah to Jerusalem, led the prophets in prayer there, and was then raised through the heavens, where the five daily prayers were prescribed. When he told Quraysh in the morning they mocked him, and Abu Bakr believed him at once, earning the name as-Siddiq. A Muslim learns that Jerusalem is bound to his prayer from the start, and that faith like Abu Bakr's does not wait for proof.",

"sira_150": "All the biographies agree that the Prophet ﷺ died at sixty-three: forty years before the revelation, thirteen in Makkah and ten in Madinah. He died in Rabi' al-Awwal of the eleventh year, in the room of 'Aisha, and was buried where he died. Abu Bakr steadied the stunned community by reciting: \"Muhammad is not but a messenger; messengers have passed on before him. So if he was to die or be killed, would you turn back on your heels?\" (3:144), and the companions felt as if they were hearing the verse for the first time. A Muslim learns that his love for the Prophet ﷺ rests on the worship of Allah, who does not die.",
}
