"""English — details, sira_b (60 questions)."""

D = {
"sira_091": "Anas ibn Malik reports in Sahih al-Bukhari 6038 that in ten years of service the Prophet ﷺ never said \"uff\" to him, never asked of something done \"why did you do it?\", nor of something left undone \"why did you not do it?\". \"Uff\" is the smallest sound of impatience, the very word the Qur'an forbids a child to say to ageing parents (17:23). Anas was a boy in a household where mistakes were possible daily. A Muslim takes from it how to treat those who help at home: with patience, without small reproaches.",

"sira_092": "Ibn 'Abbas himself narrates the moment in Sahih al-Bukhari 75: the Prophet ﷺ pressed him to his chest and said, \"O Allah, teach him the Book.\" The Book is the Qur'an, sent down \"as clarification for all things and as guidance and mercy and good tidings for the Muslims\" (16:89). Ibn 'Abbas was still a boy, son of the Prophet's ﷺ uncle al-'Abbas, and the prayer came with an embrace rather than a lesson. A Muslim learns to join affection with prayer for a child, and to ask Allah first for understanding of the Qur'an.",

"sira_093": "Ibn 'Abbas relates in Sahih al-Bukhari 1395 the instructions the Prophet ﷺ gave Mu'adh ibn Jabal for Yemen. He was going to a people of the Book and should first call them to testify that there is no god but Allah and that Muhammad is His Messenger. If they accepted, he should teach them that Allah had made five prayers a duty in every day and night; if they accepted that, that Allah had made a charity due on their wealth, taken from their rich and given to their poor. A Muslim learns that the call begins with Allah's oneness and moves one step at a time.",

"sira_094": "Anas ibn Malik reports in Sahih al-Bukhari 3744 that the Prophet ﷺ said every nation has a trustworthy one, and that the trustworthy one of this nation is Abu 'Ubayda ibn al-Jarrah. Amin was the title Makkah had given the Prophet ﷺ himself before his mission, and here he gives it to a companion before the whole community. The Qur'an counts among the successful believers \"those who are to their trusts and their promises attentive\" (23:8). A Muslim takes from it that being trusted is a rank in itself, one a leader names and honours in public.",

"sira_095": "Zayd ibn Thabit tells the story in Sahih al-Bukhari 4986. After heavy losses among the reciters at al-Yamama, 'Umar urged Abu Bakr to gather the Qur'an before more was lost; Abu Bakr hesitated to do what the Prophet ﷺ had not done, then his heart opened to it. He told Zayd that he was a wise young man, above suspicion, who had written the revelation for the Messenger of Allah. Zayd said moving a mountain would have been lighter, and gathered the Qur'an from parchments, stones, palm stalks and the memories of men. A Muslim learns how carefully his Book was preserved.",

"sira_096": "Anas ibn Malik relates in Sahih al-Bukhari 4987 how the official copies came about. Hudhayfa ibn al-Yaman, back from campaigns where Muslims of Syria and Iraq had disagreed over recitation, asked 'Uthman to save the community before it differed over its Book as earlier communities had. 'Uthman borrowed from Hafsa the sheets gathered under Abu Bakr, had Zayd ibn Thabit and three men of Quraysh copy them in the tongue of Quraysh, returned the sheets, and sent a copy to every province. A Muslim learns that the unity of the Qur'an's text was guarded by the companions themselves.",

"sira_097": "Every standard biography records that Salman was born in Persia and left his home and its fire-worship in search of the true religion, serving Christian monks in Syria before being sold as a slave and carried to Yathrib. There, after the Hijra, he watched the Prophet ﷺ for the signs he had been told of, embraced Islam, and gained his freedom with the Prophet's ﷺ help. At the siege of Madinah it was Salman who proposed the trench. A Muslim takes from his story that truth is worth a long journey, and that Islam made Persian, Arab and Abyssinian one family.",

"sira_098": "The biographies agree that Suhayb was born an Arab, taken captive as a child and raised among the Byzantines, then came to Makkah, where he gained his freedom and embraced Islam in the first years of the call. When he set out for Madinah, men of Quraysh pursued him, and he bought his way through by handing over all the wealth he had earned in Makkah. The Prophet ﷺ greeted him with the words that Suhayb's trade had been profitable. A Muslim learns that a believer counts faith and the Prophet's ﷺ company as worth more than all he owns.",

"sira_099": "Al-Masjid an-Nabawi is the mosque the Prophet ﷺ founded on arriving in Madinah, and every biography records that he built it with his companions from mud brick, palm trunks and palm fronds, carrying bricks with his own hands. His wives' rooms opened onto it, the poor companions of the Suffa sheltered in it, and there he taught, judged, received delegations and led the prayer for ten years. He was buried in 'Aisha's room beside it, and his grave lies within the mosque today. A Muslim sees in it the heart of the first community, where prayer and daily life were one.",

"sira_100": "The name stands in four verses: \"Muhammad is not but a messenger; messengers have passed on before him\" (3:144), revealed about Uhud; \"Muhammad is not the father of any one of your men, but the Messenger of Allah and the Seal of the Prophets\" (33:40); belief \"in what has been sent down upon Muhammad, and it is the truth from their Lord\" (47:2); and \"Muhammad is the Messenger of Allah, and those with him are firm against the disbelievers, merciful among themselves\" (48:29). In 61:6 'Isa announces a messenger \"whose name is Ahmad\". A Muslim learns to find his Prophet ﷺ named in the Book he recites.",

"sira_101": "The full verse reads: \"There has certainly been for you in the Messenger of Allah an excellent example for anyone whose hope is in Allah and the Last Day and who remembers Allah often\" (33:21). It stands in Surah al-Ahzab among the verses on the siege of Madinah, when the enemy came \"from above you and from below you\" and hearts reached the throats (33:10); the next verse recalls the believers saying this was what Allah and His Messenger had promised (33:22). A Muslim takes from it that following the Prophet ﷺ means copying his conduct, above all under pressure.",

"sira_102": "Every biography records that the Prophet's ﷺ first child by Khadija was a son, al-Qasim, born in Makkah before the revelation, and that by Arab custom the father was thereafter called Abu al-Qasim. The boy died while still small, as did the other son born to Khadija, 'Abdullah, yet the kunya stayed with the Prophet ﷺ all his life, and companions and strangers alike addressed him by it. A kunya in Arab usage marks honour and closeness. A Muslim learns that behind this familiar title stands a father who buried his children and bore it with patience.",

"sira_103": "The biographies agree that Ibrahim was born in Madinah to Mariya the Copt in the last years of the Prophet's ﷺ life, and that he visited the wet-nurse's home to hold his son. The child died before he was two, and the Prophet ﷺ held him as he was dying with tears in his eyes. That day the sun was eclipsed, and people said it was for Ibrahim; the Prophet ﷺ told them the sun and moon are two signs of Allah, not eclipsed for anyone's death or life. A Muslim learns that tears are allowed, and that nature's signs are tied to no man.",

"sira_104": "All the biographies record that Khadija bint Khuwaylid was a merchant of Quraysh who hired men to trade with her goods, and that having heard of the honesty of Muhammad ﷺ she sent him with her caravan to Syria alongside her servant Maysara, who returned full of praise for him. The trade prospered, and she sent word proposing marriage. She bore all his children except Ibrahim, and when the first revelation came she was the first to believe and calmed him, saying Allah would never disgrace a man who kept ties of kinship and helped the weak. A Muslim learns that his mission began in a marriage built on trust.",

"sira_105": "Every biography records the event from the rebuilding of the Ka'ba by Quraysh before the revelation. When the walls reached the height of the Black Stone, each clan claimed the honour of setting it, and the dispute neared bloodshed until they agreed that the first man through the gate would decide. It was Muhammad ﷺ, and they cried that al-Amin had come and they accepted his judgement. He spread his cloak, laid the Stone on it, had a chief of each clan lift an edge, and set it with his own hand. A Muslim learns that a fair solution giving everyone a share ends a quarrel.",

"sira_106": "The biographies agree that the Prophet ﷺ was forty when the revelation began, and that he had taken to withdrawing to the cave of Hira, on a mountain outside Makkah, to worship alone. The Qur'an names the month: \"the month of Ramadan in which the Qur'an was sent down\" (2:185). Jibril came to him there with \"Read in the name of your Lord who created\" (96:1), and he returned trembling to Khadija. Forty is the age the Qur'an describes as full maturity, when a person turns to Allah in gratitude (46:15). A Muslim learns that the mission began in solitude and reflection.",

"sira_107": "Sahih al-Bukhari 3 describes Waraqa ibn Nawfal as Khadija's cousin, a Christian before Islam who used to write from the Gospel in Hebrew, by then old and blind. Khadija said, \"Listen to your nephew,\" and after hearing of Hira Waraqa said this was the Namus Allah had sent down to Musa, and wished he were young for the day the Prophet's ﷺ people would drive him out. Asked whether they really would, Waraqa answered that no man had ever brought what he brought without meeting hostility. A Muslim learns that one who knew the earlier Scriptures recognised his mission at once.",

"sira_108": "Ibn 'Abbas relates in Sahih al-Bukhari 4770 that when \"And warn your closest kindred\" (26:214) was revealed, the Prophet ﷺ climbed as-Safa and called the clans of Quraysh by name until they gathered. He asked whether they would believe him if he said horsemen in the valley were about to attack, and they answered they had never known anything from him but truth. He said he was a warner before a severe punishment. Abu Lahab wished him ruin for it, and \"May the hands of Abu Lahab be ruined\" (111:1) came down. A Muslim learns that his message rested on a lifetime of proven honesty.",

"sira_109": "Every account of the caliphate of 'Umar ibn al-Khattab records that, when dated letters and records made a fixed calendar necessary, he gathered the companions to decide from which event the years should be counted. They chose the Hijra, the emigration to Madinah, over the Prophet's ﷺ birth or death, and made the year begin with Muharram. The Qur'an had already fixed the months: \"Indeed, the number of months with Allah is twelve months in the register of Allah\" (9:36). A Muslim learns that his calendar counts from the founding of the community rather than from a birthday.",

"sira_110": "All the biographies agree that the Prophet ﷺ entered Madinah in Rabi' al-Awwal and died in the same month of the eleventh year, so that his life there lasted ten years. Into them fall the events the Qur'an recounts: Badr in the second year, Uhud in the third, the siege of the Confederates in the fifth, Hudaybiyya in the sixth, the conquest of Makkah in the eighth and the Farewell Pilgrimage in the tenth. The Qur'an calls the city by its old name, Yathrib (33:13). A Muslim learns that a whole community was built in one decade.",

"sira_111": "The biographies agree that from the first revelation at forty to the Hijra the Prophet ﷺ preached in Makkah for thirteen years: three calling people quietly, the rest in public under growing hostility, through the emigration to Abyssinia, the boycott of his clan, the deaths of Khadija and Abu Talib, the Night Journey and the pledges of 'Aqaba. The Qur'an describes its revelation as spread over a long span, \"a Qur'an which We have separated, that you might recite it to the people over a prolonged period\" (17:106). A Muslim learns that the Qur'an's teaching on faith was given in years of patience.",

"sira_112": "Al-Bara' ibn 'Azib reports in Sahih al-Bukhari 3212 that the Prophet ﷺ said to Hassan, \"Satirise them, and Jibril is with you.\" Hassan ibn Thabit was a poet of the Ansar, and the poets of Quraysh were attacking the Prophet ﷺ in verse, the weapon Arabs feared most. The Qur'an condemns poets followed by the misguided but excepts \"those who believe and do righteous deeds and remember Allah often and defend themselves after they were wronged\" (26:227). A Muslim learns that a gift for words is honoured when placed in the service of truth.",

"sira_113": "Abu Musa al-Ash'ari himself narrates in Sahih al-Bukhari 5048 that the Prophet ﷺ said to him, \"O Abu Musa, you have been given one of the flutes of the family of Dawud.\" The Qur'an tells that Allah gave Dawud the Zabur (4:163) and made the mountains and the birds join him in praise (21:79), so a voice like his is the highest praise for recitation. Abu Musa was reciting the Qur'an when the Prophet ﷺ heard him. A Muslim learns that a beautiful recitation is a gift the Prophet ﷺ admired, and that the voice serves the words.",

"sira_114": "'Abdullah ibn 'Amr reports in Sahih al-Bukhari 3758 that he heard the Prophet ﷺ say, \"Take the Qur'an from four,\" beginning with 'Abdullah ibn Mas'ud, then Salim the freed slave of Abu Hudhayfa, Mu'adh ibn Jabal and Ubayy ibn Ka'b. Ibn Mas'ud and Salim were emigrants from Makkah, Mu'adh and Ubayy were of the Ansar, so the Qur'an's teachers came from both halves of the community. A Muslim learns that the Qur'an was passed on by named teachers the Prophet ﷺ trusted, in a chain reaching back to him.",

"sira_115": "Sahih al-Bukhari 4073 records that on the day of Uhud the Prophet's ﷺ face was wounded and one of his front teeth was broken. The Qur'an speaks of that day in Surah Al 'Imran, when the archers left their post and the Muslims fled \"while the Messenger was calling you from behind\" (3:153), and consoles the wounded: \"If a wound should touch you, there has already touched the opposing people a wound similar to it\" (3:140). He stayed on the field, bleeding, with his companions. A Muslim learns that the Prophet ﷺ shared his community's pain in his own body.",

"sira_116": "'Ali ibn Abi Talib reports in Sahih al-Bukhari 4055 that he never heard the Prophet ﷺ say to anyone \"may my father and mother be sacrificed for you\" except to Sa'd ibn Abi Waqqas, on the day of Uhud, when he told him to shoot. Sa'd was firing arrows to keep the enemy from the Prophet ﷺ when the Muslim lines had broken. Among Arabs, offering one's parents as ransom was the strongest expression of love a man could utter. A Muslim learns that courage in defending the Prophet ﷺ earned words he gave to no one else.",

"sira_117": "Every biography records that in the second year after the Hijra the Muslims marched to meet a rich Quraysh caravan under Abu Sufyan returning from Syria, but that he turned along the coast and sent to Makkah for help, so an army under Abu Jahl came out instead. The Qur'an recalls it: \"And when Allah promised you one of the two groups, that it would be yours, and you wished that the unarmed one would be yours\" (8:7). The battle at the wells of Badr became \"the day of the Criterion\" (8:41). A Muslim learns that what Allah chose was harder than what they wanted, and greater.",

"sira_118": "All the biographies record that Abu Sufyan, who had led Quraysh against the Muslims at Uhud and at the Trench, went out to spy on the army approaching Makkah in the eighth year, was brought to the Prophet ﷺ by his uncle al-'Abbas, and embraced Islam on the night before the entry. The Prophet ﷺ then honoured him by proclaiming that whoever entered the house of Abu Sufyan was safe, as was anyone who shut his door or entered the mosque. A Muslim learns that the Prophet ﷺ met his oldest enemy with safety and honour, and that no one is too far gone to return.",

"sira_119": "Ibn 'Abbas tells the story in Sahih al-Bukhari 3364. Ibrahim left Hajar and the infant Isma'il by the site of the House with dates and a skin of water; when she asked whether Allah had commanded this and he said yes, she answered that He would not neglect them. The water ran out, the child cried with thirst, and after her search she heard a voice and saw an angel dig with his heel until water gushed. She built a basin round it with her hands, and the Prophet ﷺ said that had she left it, Zamzam would have been a flowing spring. A Muslim learns that Zamzam was given to a mother who trusted Allah.",

"sira_120": "Anas ibn Malik reports in Sahih al-Bukhari 5872 that the Prophet ﷺ had a ring of silver made, engraved \"Muhammad Rasul Allah\", and the account places it in the story of his letters: when he decided to write to rulers, he was told that a letter without a seal would not be read. Anas adds that the ring's whiteness in his hand still stood before his eyes. The three words are the second half of the testimony of faith, carried to kings beyond Arabia. A Muslim learns that the Prophet ﷺ used the ordinary means of his time to make sure his message was received.",

"sira_121": "'Aisha reports in Sahih al-Bukhari 5431 that the Messenger of Allah ﷺ loved sweet things and honey. She knew his table better than anyone, and her short sentence shows him taking pleasure in good food without excess. The Qur'an speaks of honey as a healing: from the bees \"there emerges from their bellies a drink, varying in colours, in which there is healing for people\" (16:69). His taste was for something the Qur'an names among Allah's signs. A Muslim learns that enjoying lawful food with gratitude is part of the Prophet's ﷺ way.",

"sira_122": "Abu Qatada reports in Sahih Muslim 1162 that the Prophet ﷺ was asked about fasting on Monday and answered that it was the day he was born and the day revelation came down to him. The same hadith records that fasting the day of 'Arafa expiates the year before and the year after, and 'Ashura the year before. Birth and mission fall on the same weekday, and he honoured it not with a feast but with a fast. A Muslim learns that gratitude for a blessing is shown by worship, and that the Monday fast thanks Allah for the Prophet's ﷺ coming.",

"sira_123": "As-Sa'ib ibn Yazid relates in Sahih al-Bukhari 3541 that as a boy he was taken by his aunt to the Prophet ﷺ because he was ill; the Prophet ﷺ stroked his head, prayed for blessing on him and made ablution, and the boy drank from the water. Then he stood behind him and saw the seal of prophethood between his shoulders, which he compared to the button of a tent. The Qur'an calls him \"the Seal of the Prophets\" (33:40), the last of them. A Muslim learns that even children who met the Prophet ﷺ remembered him closely and lovingly.",

"sira_124": "Sahl ibn Sa'd relates in Sahih al-Bukhari 917 that the Prophet ﷺ sent word to a woman to have her carpenter slave make him something of wood to sit on when he spoke to the people, and that the man made it from the tamarisk of al-Ghaba. When it was set in the mosque, the Prophet ﷺ prayed on it, bowed on it, stepped down backwards to prostrate at its foot and climbed back, then told the people he had done this so they could follow him and learn his prayer. A Muslim learns that the Prophet ﷺ showed the prayer as much as he described it.",

"sira_125": "Every biography records that the Aws and the Khazraj, the Arab tribes of Yathrib, had fought each other for generations, and that men of the Khazraj first met the Prophet ﷺ at Makkah during the pilgrimage, accepted his call, and returned with men of the Aws to pledge allegiance at 'Aqaba. The Qur'an reminds them: \"Remember the favour of Allah upon you when you were enemies and He brought your hearts together and you became, by His favour, brothers\" (3:103), and praises them as those who \"give preference over themselves, even though they are in privation\" (59:9). A Muslim learns that faith turned old enemies into one people.",

"sira_126": "The verse reads: \"The Prophet is more worthy of the believers than themselves, and his wives are their mothers\" (33:6). Surah al-Ahzab addresses them directly, \"O wives of the Prophet, you are not like any other women\" (33:32), and forbids the believers ever to marry them after him, calling that \"in the sight of Allah an enormity\" (33:53). The title places every believer in the position of a child towards them, owing respect and care. A Muslim learns to speak of Khadija, 'Aisha and the others as his mothers, and to receive what they passed on from the Prophet's ﷺ home as a mother's teaching.",

"sira_127": "All the biographies agree that the Prophet ﷺ left Makkah with Abu Bakr in the year corresponding to 622, hid three days in the cave of Thawr while Quraysh searched, and reached Madinah by the coastal route. The Qur'an recalls the cave: \"when those who disbelieved had driven him out as one of two, when they were in the cave and he said to his companion, 'Do not grieve; indeed Allah is with us'\" (9:40). Under 'Umar this year was made the first of the Muslim calendar. A Muslim learns that the calendar he uses began with a journey made in trust.",

"sira_128": "Anas ibn Malik tells the story in Sahih al-Bukhari 2048. When 'Abd ar-Rahman ibn 'Awf arrived in Madinah, the Prophet ﷺ made him the brother of Sa'd ibn ar-Rabi' of the Ansar, who offered him half his property. 'Abd ar-Rahman blessed him, asked only to be shown the market, and traded at a profit. Later he came to the Prophet ﷺ with a trace of yellow perfume, having married a woman of the Ansar for gold the weight of a date-stone; the Prophet ﷺ told him to give a wedding feast, even with one sheep. A Muslim learns to accept help without living on it.",

"sira_129": "Ubayy ibn Ka'b relates in Sahih Muslim 810 that the Prophet ﷺ asked him, \"O Abu al-Mundhir, do you know which verse of the Book of Allah with you is the greatest?\" Ubayy first said Allah and His Messenger know best, then answered with the Throne Verse, \"Allah, there is no god but He, the Ever-Living, the Sustainer of existence\" (2:255), which goes on to say that neither drowsiness nor sleep overtakes Him and that His Kursi extends over the heavens and the earth. The Prophet ﷺ struck his chest and said, \"May knowledge delight you, Abu al-Mundhir.\" A Muslim learns to know this verse and to love knowledge as Ubayy did.",

"sira_130": "Every biography records that when the Prophet ﷺ entered Madinah each clan of the Ansar took his she-camel's reins and begged him to lodge with them, and that he told them to let her go, for she was under command. She walked on until she knelt at a drying-place for dates belonging to two orphan boys of Banu an-Najjar. Though they offered it as a gift, he insisted on paying, and there the mosque was built, with rooms beside it for his household. A Muslim learns that the Prophet ﷺ favoured no clan over another and paid a fair price even to orphans who wished to give.",

"sira_131": "The biographies record three sons: al-Qasim, from whom the Prophet ﷺ took his kunya, and 'Abdullah, both born to Khadija in Makkah, and Ibrahim, born in Madinah to Mariya; each died in early childhood. His four daughters, Zaynab, Ruqayya, Umm Kulthum and Fatima, lived to marry. The Qur'an states the outcome plainly: \"Muhammad is not the father of any one of your men, but the Messenger of Allah and the Seal of the Prophets\" (33:40). A Muslim learns that the Prophet ﷺ knew the grief of burying children, and that his message was carried on without a son.",

"sira_132": "All the biographies agree that Zayd ibn Haritha was taken captive as a boy and sold, came into Khadija's possession and was given by her to the Prophet ﷺ, and that when his father and uncle came to ransom him, Zayd chose to stay. The Prophet ﷺ freed and adopted him, so that he was called Zayd ibn Muhammad until the Qur'an ended such naming: \"Call them by the names of their fathers\" (33:5). He is the only companion named in the Qur'an (33:37) and fell commanding the army at Mu'ta. A Muslim learns what love between a master and a freed man can be.",

"sira_133": "Ibn 'Umar reports in Sahih al-Bukhari 4469 that the Prophet ﷺ sent out a force under Usama ibn Zayd, and that when people criticised his command he rose and said that those who criticised Usama had criticised his father's command before him; that his father had been worthy of it and among the dearest of people to him; and that this one was among the dearest to him after him. Usama was very young, and his father Zayd had commanded at Mu'ta. A Muslim learns that leadership is given for merit rather than age, and that the Prophet ﷺ defended his choice openly.",

"sira_134": "Every biography records that Zamzam had been filled in and lost long before, and that 'Abd al-Muttalib, chief of Banu Hashim, was shown its place in a dream and dug it out with his only son at the time, al-Harith, despite the objections of Quraysh; he then held the office of watering the pilgrims from it. The biographies also record his vow to sacrifice a son if Allah gave him ten, and that when the lot fell on 'Abdullah, the future father of the Prophet ﷺ, he was ransomed with a hundred camels. A Muslim learns that the Prophet's ﷺ grandfather served the pilgrims of the House.",

"sira_135": "All the biographies put the Muslims at Badr at a little over three hundred men, with two horses between them, facing a Quraysh army of close to a thousand. The Qur'an records the imbalance: \"Allah had already given you victory at Badr while you were few\" (3:123), and tells that the Prophet ﷺ promised the believers help from heaven, \"Is it not sufficient for you that your Lord should reinforce you with three thousand angels sent down?\" (3:124). Those who were at Badr were honoured for the rest of their lives. A Muslim learns that victory is not decided by numbers.",

"sira_136": "Every biography records that the Prophet ﷺ was born in Makkah in Rabi' al-Awwal in the Year of the Elephant, the year Abraha marched from Yemen with an elephant to destroy the Ka'ba and was turned back. The Qur'an recalls it: \"Have you not considered how your Lord dealt with the companions of the elephant?\" (105:1). His father 'Abdullah had died before his birth, his mother was Amina, and he was nursed in the desert by Halima of Banu Sa'd. A Muslim learns that Allah protected the House in the very year its last Prophet ﷺ was born, an orphan.",

"sira_137": "The biographies agree that the Prophet ﷺ reached the outskirts of Madinah in Rabi' al-Awwal and halted first at Quba, where he founded a mosque, and that he entered the city on a Friday, praying the first Friday prayer on the way among Banu Salim. The Qur'an speaks of Quba as \"a mosque founded on righteousness from the first day\" (9:108), more worthy to stand in. The Ansar came out to meet him, and every household wished to host him. A Muslim learns that the first thing the Prophet ﷺ built in his new home, before any house of his own, was a place of prayer.",

"sira_138": "Every biography records that Quraysh, unable to stop the call, wrote a document binding themselves not to trade or intermarry with Banu Hashim and Banu al-Muttalib until they handed over Muhammad ﷺ, and hung it inside the Ka'ba. Abu Talib withdrew with the whole clan, believers and unbelievers alike, into his valley outside Makkah, where they suffered hunger for about three years. It ended when men of Quraysh ashamed of it had the document torn up, and it was found eaten away except for the name of Allah. A Muslim learns that the Prophet's ﷺ clan stood by him, and patience outlasted the pact.",

"sira_139": "All the biographies agree that after the first revelation the Prophet ﷺ spoke of his message only to those closest to him, and that the first to believe were Khadija, Abu Bakr, 'Ali and Zayd ibn Haritha, followed by others whom Abu Bakr brought. For about three years the believers met quietly in the house of al-Arqam near as-Safa to learn what was revealed. Then the Qur'an commanded, \"Then declare what you are commanded and turn away from the polytheists\" (15:94), and \"And warn your closest kindred\" (26:214). A Muslim learns that the call grew step by step, from a trusted circle to the whole city.",

"sira_140": "Ibn 'Abbas relates in Sahih al-Bukhari 3364 that when the water was gone and Isma'il writhed with thirst, Hajar climbed as-Safa, the nearest hill, to look for anyone, came down, and at the bottom of the valley lifted her garment and ran like a person in distress until she had crossed it, then climbed al-Marwa and looked again. She did this seven times, and the Prophet ﷺ said that this is why people go between the two hills. The Qur'an confirms it: \"Indeed, as-Safa and al-Marwa are among the symbols of Allah\" (2:158). A Muslim learns that every pilgrim's sa'y retraces a mother's search.",

"sira_141": "Abu Bakra relates in Sahih al-Bukhari 2704 that he saw the Prophet ﷺ on the minbar with al-Hasan beside him, looking now at the people and now at the boy, and saying, \"This son of mine is a sayyid, and it may be that Allah will reconcile through him two great groups of Muslims.\" Al-Hasan was the son of 'Ali and Fatima, and the words were said before the whole congregation. The Qur'an makes peace between believers the duty of all (49:10). A Muslim learns that the Prophet ﷺ prized peace among Muslims above rule, and praised a child for what he would one day do.",

"sira_142": "Every biography records that Fatima was the youngest of the Prophet's ﷺ daughters, born to Khadija in Makkah, that she married 'Ali ibn Abi Talib in Madinah, and that from that marriage came al-Hasan and al-Husayn, the grandsons the Prophet ﷺ carried and played with. The biographies also record his words that Fatima was a part of him, and that she was the only one of his children to outlive him, dying about six months after him. A Muslim learns that the Prophet's ﷺ family life was one of tenderness, and that his descendants come through a daughter who lived simply.",

"sira_143": "All the biographies agree that Zaynab, the eldest daughter, was married before the revelation to her cousin Abu al-'As ibn ar-Rabi' and stayed with him in Makkah after the Hijra. When he was captured at Badr, she sent as ransom a necklace Khadija had given her on her wedding day; the Prophet ﷺ recognised it, was moved, and with the companions' agreement returned it and released her husband on condition that he let Zaynab join her father. She emigrated to Madinah, and Abu al-'As later embraced Islam and rejoined her. A Muslim learns how the Prophet ﷺ loved his daughter and honoured Khadija's memory.",

"sira_144": "Every biography records that Bilal ibn Rabah, Abyssinian by origin, was a slave in Makkah tortured under the noon sun by his master for embracing Islam, who kept repeating \"Ahad, Ahad\", one, one, until Abu Bakr bought and freed him. In Madinah, when the call to prayer was instituted, the Prophet ﷺ chose him to give it, and on the day Makkah was conquered Bilal climbed onto the roof of the Ka'ba and called the adhan from there. A Muslim learns that the former slave rose to call the community to prayer, and that rank is measured by faith, not birth.",

"sira_145": "The hadith stands in Sahih al-Bukhari 3661, in the chapter on the Prophet's ﷺ words that had he taken a bosom friend from among men he would have taken Abu Bakr, who was nonetheless his brother and companion. The Qur'an reserves the word khalil for the bond between Ibrahim and his Lord, \"And Allah took Ibrahim as a khalil\" (4:125), and it recalls Abu Bakr's companionship without naming him, \"the second of two, when they were in the cave\" (9:40). A Muslim learns that no one ranked closer to the Prophet ﷺ than Abu Bakr, and that the deepest intimacy of the heart is kept for Allah alone.",

"sira_146": "Every biography records that as Ibrahim had declared Makkah a sanctuary, the Prophet ﷺ declared Madinah a sanctuary between its two tracts of black stone, and prayed that Allah bless it as He had blessed Makkah. The Qur'an calls Makkah \"a secure sanctuary\" (28:57) and names Madinah by its old name, Yathrib (33:13); the Prophet ﷺ called it Taybah, the good. Makkah holds the Ka'ba, Madinah his mosque and grave, and together they are al-Haramayn. A Muslim learns to revere both: the city where the Qur'an began and the one where the community was built.",

"sira_147": "All the biographies agree that after the Hijra the Prophet ﷺ made the pilgrimage once, in the tenth year, with a great crowd of Muslims following him, and that it was called the Farewell Pilgrimage because he died months later. At 'Arafat he addressed the people from his camel, reminding them that their lives and property were sacred to one another, and there the verse came down: \"This day I have perfected for you your religion and completed My favour upon you\" (5:3). Every act of it was watched and recorded. A Muslim learns that the Hajj he performs today follows the one Hajj the Prophet ﷺ led.",

"sira_148": "Anas ibn Malik relates in Sahih al-Bukhari 3149 that he was walking with the Prophet ﷺ, who wore a cloak from Najran with a thick border, when a Bedouin seized it and pulled so hard that Anas saw the mark of the border on the Prophet's ﷺ shoulder. The man said, \"O Muhammad, order for me some of the wealth of Allah that is with you.\" The Prophet ﷺ turned, laughed, and had something given to him. The Qur'an describes him: \"And indeed, you are of a great moral character\" (68:4). A Muslim learns that the Prophet ﷺ answered rudeness with a smile and generosity.",

"sira_149": "The Qur'an opens Surah al-Isra with the journey: \"Exalted is He who took His Servant by night from al-Masjid al-Haram to al-Masjid al-Aqsa, whose surroundings We have blessed, to show him of Our signs\" (17:1). Every biography records that the Prophet ﷺ was carried that night from Makkah to Jerusalem, led the prophets in prayer there, and was raised through the heavens, where the five daily prayers were prescribed. Quraysh mocked him in the morning, and Abu Bakr believed him at once, earning the name as-Siddiq. A Muslim learns that Jerusalem is bound to his prayer from the start.",

"sira_150": "All the biographies agree that the Prophet ﷺ died at sixty-three: forty years before the revelation, thirteen in Makkah and ten in Madinah. He died in Rabi' al-Awwal of the eleventh year, in the room of 'Aisha, and was buried where he died. Abu Bakr steadied the stunned community by reciting, \"Muhammad is not but a messenger; messengers have passed on before him. So if he was to die or be killed, would you turn back on your heels?\" (3:144), and the companions felt they were hearing the verse for the first time. A Muslim learns that his love for the Prophet ﷺ rests on worship of Allah, who does not die.",
}
