"""English — details, sira_a (60 questions)."""

D = {
"sira_031": "The surah opens: \"For the accustomed security of Quraysh, their security in the caravan of winter and summer\" (106:1-2), then calls on the tribe: \"So let them worship the Lord of this House, who has fed them against hunger and made them safe from fear\" (106:3-4). Quraysh lived beside the Ka'ba and traded in two yearly journeys, and the Qur'an reminds them that both come from Allah. A Muslim learns that the Prophet ﷺ was sent first to his own tribe, and that honour carries a duty to worship.",

"sira_032": "Every standard biography records the lineage as Muhammad, son of 'Abdullah, son of 'Abd al-Muttalib, son of Hashim, and the clan takes its name from Hashim. Banu Hashim was one of the clans of Quraysh settled around the Ka'ba, and its head, Abu Talib, sheltered his nephew through the Makkan years. When Quraysh boycotted the Muslims, all of Banu Hashim were shut out with him. A Muslim learns that the Prophet ﷺ grew up inside a clan that protected him before it believed him.",

"sira_033": "Halima came from Banu Sa'd, and every standard biography tells how she arrived in Makkah with the women of her tribe seeking infants to nurse, took the orphan whose father had died, and carried him to the desert, where Makkan families sent their children for clean air and pure Arabic. The biographies record that her household's flocks increased while he was with them, and that she kept him beyond the usual term before returning him to his mother Amina. A Muslim learns that the Prophet's ﷺ first years were spent simply, among ordinary people.",

"sira_034": "Hamza was the son of 'Abd al-Muttalib and so the Prophet's ﷺ uncle, though close to him in age; the biographies record that both were nursed by the same woman, Thuwayba. He accepted Islam in Makkah after standing up to Abu Jahl, who had insulted his nephew, and at Badr he fought in the single combat that opened the battle. At Uhud he was killed by Wahshi, an Abyssinian slave who later accepted Islam and told the story himself. A Muslim remembers Hamza as a man who defended the Prophet ﷺ before believing and gave his life after believing.",

"sira_035": "The biographies record that Abu Talib had many children and little means, so the Prophet ﷺ took his young cousin 'Ali into his own home to ease his uncle's burden. 'Ali was a boy when revelation came and accepted Islam among the very first; he married Fatima, slept in the Prophet's ﷺ bed on the night of the Hijra and carried the banner at Khaybar. After 'Uthman he received the pledge of allegiance in Madinah. A Muslim learns that for 'Ali, closeness to the Prophet ﷺ was a matter of upbringing and of faith together.",

"sira_036": "Every standard biography records that on the day the Prophet ﷺ died, the companions gathered at the meeting-place of Banu Sa'ida in Madinah and gave Abu Bakr the pledge of allegiance, 'Umar being the first to take his hand. During his final illness the Prophet ﷺ had ordered Abu Bakr to lead the prayer in his place, which the companions took as a sign of his standing. The Qur'an speaks of him, unnamed, as the second of two in the cave (9:40). A Muslim learns that leadership after the Prophet ﷺ went to the man closest to him in faith and in trial.",

"sira_037": "The biographies link the title to the morning after the Night Journey, when the Prophet ﷺ told the Makkans he had travelled to Jerusalem and back in one night. Quraysh ran to Abu Bakr expecting him to doubt, and he answered that if the Prophet ﷺ had said it, it was true, since he already believed him about news from heaven every morning and evening. The Qur'an speaks of him as the second of two in the cave, told not to grieve (9:40). A Muslim learns that believing the Prophet ﷺ without hesitation is itself a mark of honour.",

"sira_038": "The biographies record that when 'Umar accepted Islam in Makkah, the Muslims, who had prayed in hiding, went out and prayed openly at the Ka'ba, and that from this came his title: through him truth was set apart from falsehood in the open. Sahih al-Bukhari records the companions saying that they had been strong since 'Umar embraced Islam. He later became the second caliph, named by Abu Bakr before his death. A Muslim learns that courage in showing the truth openly is a gift others draw strength from.",

"sira_039": "The biographies record that 'Uthman emigrated with Ruqayya to Abyssinia during the persecution in Makkah, and later to Madinah. When the Muslims marched to Badr she was ill, and the Prophet ﷺ told him to stay and care for her; she died while the army was away, and the Prophet ﷺ still counted him among the men of Badr. He then married her sister Umm Kulthum, who also died in his lifetime. A Muslim learns that 'Uthman's honour came from his closeness to the Prophet's ﷺ household.",

"sira_040": "Every standard biography records how each caliph came to lead. Abu Bakr received the pledge of allegiance on the day the Prophet ﷺ died, and before his own death named 'Umar to follow him; 'Umar, mortally wounded, entrusted the choice to a council of six companions, who chose 'Uthman; after 'Uthman was killed in Madinah, its people gave their pledge to 'Ali. The four are called rightly guided because they governed by the Qur'an and the Prophet's ﷺ example. A Muslim learns their order as the first chapter of the community's history after its Prophet ﷺ.",

"sira_041": "Every standard biography records that when the Prophet ﷺ came home trembling from the cave of Hira after the first revelation, Khadija covered him and said that Allah would never disgrace him, because he kept ties with his kin, carried the burdens of the weak, gave to the poor and honoured guests. She then took him to her cousin Waraqa ibn Nawfal, who knew the earlier scriptures and told him that this was the angel who had come to Musa. A Muslim learns that the first to say yes to the message was the one who knew the Messenger ﷺ best.",

"sira_042": "The biographies record that Bilal was an Abyssinian slave in Makkah whose master, Umayya ibn Khalaf, laid him on the burning sand at midday with a heavy rock on his chest to make him renounce his faith, and that Bilal answered only \"Ahad, Ahad\", One, One. Abu Bakr, who had wealth from trade, paid the master his price and freed him for the sake of Allah. Bilal later became the Prophet's ﷺ caller to prayer in Madinah. A Muslim learns that Abu Bakr spent his money to free the oppressed.",

"sira_043": "The biographies record that Yasir, his wife Sumayya and their son 'Ammar were among the weak of Makkah with no clan to protect them, and that Abu Jahl and others tortured the family in the heat to make them abandon Islam. The Prophet ﷺ passed by them and said: \"Patience, family of Yasir, your appointed meeting is Paradise.\" Abu Jahl killed Sumayya with a spear; he himself fell at Badr, while 'Ammar lived on as a companion. A Muslim learns that the first martyr of Islam was a woman who chose her faith over her life.",

"sira_044": "Every standard biography records that when the persecution in Makkah became unbearable, the Prophet ﷺ told his companions that in Abyssinia there was a king under whom no one was wronged, and sent them to seek refuge with him. They crossed the Red Sea in two groups; among them were 'Uthman and his wife Ruqayya, the Prophet's ﷺ daughter. Quraysh sent envoys with gifts asking the king to hand the Muslims back, and he refused. A Muslim learns that seeking safety in a just land, even one not yet Muslim, was the Prophet's ﷺ own counsel.",

"sira_045": "The hadith is narrated by Abu Hurayra and recorded in Sahih al-Bukhari 1245: the Messenger of Allah ﷺ announced the death of the Negus on the very day he died, went out with the companions to the place of prayer, arranged them in rows and said four takbirs. No news had reached Madinah from Abyssinia, so the announcement was itself a sign of prophethood. The Negus had sheltered the Muslims who fled Makkah and refused to surrender them to Quraysh. A Muslim learns that the Prophet ﷺ honoured the king who protected the weak.",

"sira_046": "The biographies preserve the scene as told by Umm Salama, one of the emigrants. Ja'far, 'Ali's elder brother, told the king that his people had lived in ignorance, worshipping idols and wronging the weak, until Allah sent them a messenger who called them to worship Allah alone, speak the truth, keep ties of kinship and protect their neighbours. When the king asked to hear the revelation, Ja'far recited from Surah Maryam, the Negus wept, and he refused to hand the Muslims over. A Muslim learns that Islam was first explained abroad in plain words and verses of the Qur'an.",

"sira_047": "The surah reads: \"May the hands of Abu Lahab be ruined, and ruined is he. His wealth will not avail him, nor what he gained. He will burn in a Fire of flame, and his wife, the carrier of firewood, upon her neck a rope of twisted fibre\" (111:1-5). Sahih al-Bukhari records the occasion: when the Prophet ﷺ climbed the hill of Safa and called Quraysh to warn them, his uncle Abu Lahab answered that he hoped he would perish, and the surah came down. A Muslim learns that kinship with the Prophet ﷺ was no protection for a man who fought his message.",

"sira_048": "Every standard biography records that Abu Talib and Khadija died within a short span in the tenth year of the mission. Abu Talib, though he never entered Islam, had used his standing as head of Banu Hashim to keep Quraysh from harming his nephew; the Qur'an speaks of him when it says that the Prophet ﷺ cannot guide whom he loves (28:56). With both gone, Quraysh treated him more harshly, and he went to Ta'if to seek support. A Muslim learns that even the Prophet ﷺ grieved, and that grief is no failing of faith.",

"sira_049": "The hadith is narrated by 'Aisha and recorded in Sahih al-Bukhari 3231. She asked the Prophet ﷺ whether any day had been harder for him than Uhud, and he answered that the hardest was when he presented himself to the chiefs of Ta'if and was refused, then walked away in grief until a cloud shaded him and Jibril called with the angel of the mountains, who offered to crush the people between the two mountains of Makkah. The Prophet ﷺ replied that he hoped Allah would bring out of their descendants people who worship Him alone. A Muslim learns to answer cruelty with hope.",

"sira_050": "The hadith is narrated by Anas from Abu Dharr and recorded in Sahih al-Bukhari 349: Jibril washed his chest with Zamzam water, filled it from a golden tray of wisdom and faith, and took him up through the heavens, where he met Adam, Idris, Musa, 'Isa and Ibrahim. There Allah made fifty prayers a day obligatory; Musa told him his community could not bear it, and he returned again and again until they were five, counted as fifty in reward. A Muslim learns that the daily prayer was given in the highest place and lightened out of mercy.",

"sira_051": "Surah An-Najm describes the vision: \"And he certainly saw him in another descent\" (53:13), \"near the Lote Tree of the Utmost Boundary\" (53:14), \"near which is the Garden of Refuge, when there covered the Lote Tree that which covered it. The sight did not swerve, nor did it exceed\" (53:15-17). The surah opens by swearing by the star that the Prophet ﷺ has not gone astray and speaks only what is revealed to him (53:1-4). A Muslim learns that what the Prophet ﷺ reported of the Ascension is confirmed by the Qur'an itself.",

"sira_052": "Every standard biography records two pledges, given in successive pilgrimage seasons at the pass of Al-'Aqaba, where the Prophet ﷺ met the men of Yathrib by night, away from Quraysh. At the first, twelve men pledged, as Sahih al-Bukhari records from 'Ubada ibn as-Samit, not to associate anything with Allah, not to steal, not to commit adultery and not to kill their children. At the second, more than seventy men and two women pledged to defend him as they defended their own families. A Muslim learns that the community of Madinah began with a promise given quietly in the dark.",

"sira_053": "The biographies record that after the first pledge at Al-'Aqaba the people of Yathrib asked for a teacher, and the Prophet ﷺ sent Mus'ab ibn 'Umayr, a young man of Quraysh who had left a life of ease for Islam. He lodged with As'ad ibn Zurara, recited the Qur'an to whoever would listen, and through him the chiefs Sa'd ibn Mu'adh and Usayd ibn Hudayr entered Islam. He was killed at Uhud carrying the banner, with only a cloak for a shroud. A Muslim learns that the faith reached Madinah through one patient teacher.",

"sira_054": "Every standard biography records that the clans of Quraysh agreed to send a young man from each to strike the Prophet ﷺ together; the Qur'an recalls it: \"when those who disbelieved plotted against you to confine you or kill you or drive you out; they plan, and Allah plans\" (8:30). The Prophet ﷺ told 'Ali to lie in his bed under his green cloak and left unseen, charging 'Ali to return the goods that Makkans had left in his safekeeping. A Muslim learns that the Prophet ﷺ kept his trusts even to those who plotted his death.",

"sira_055": "Thawr lies south of Makkah while Madinah lies north; the two men went the opposite way first to throw off the search. The Qur'an speaks of this moment: \"the second of two, when they were in the cave, when he said to his companion, 'Do not grieve, indeed Allah is with us'\" (9:40). Sahih al-Bukhari records Abu Bakr's fear that a searcher looking under his feet would see them, and the Prophet's ﷺ answer asking what he thought of two whose third was Allah. A Muslim learns that trust in Allah stays calm even in danger.",

"sira_056": "The long account of the Hijra narrated by 'Aisha in Sahih al-Bukhari 3905 tells how the two men hid in the cave of Thawr for three nights, how Abu Bakr's son 'Abdullah brought news each evening, and how 'Amir ibn Fuhayra brought sheep for milk. Asma prepared the provisions, and finding nothing to tie the food bag, cut her waist-belt in two and used one half; from that she was named Dhat an-Nitaqayn. A Muslim learns that the Hijra succeeded through the quiet service of a whole family.",

"sira_057": "Suraqa ibn Malik tells the story himself in Sahih al-Bukhari 3906. When a man mentioned seeing riders on the coast, Suraqa, hoping for the reward Quraysh had offered, rode after them; as he drew close, his horse's forelegs sank into the ground up to the knees. He called out for safety, and the Prophet ﷺ had 'Amir ibn Fuhayra write him a guarantee on a piece of leather. A Muslim learns that Allah protected His Messenger ﷺ on the open road as He had in the cave.",

"sira_058": "The verse records the hypocrites during the siege of Madinah: \"And when a faction of them said, 'O people of Yathrib, there is no place for you here, so return', and a party of them asked permission of the Prophet, saying, 'Our houses are exposed', while they were not exposed; they wanted only to flee\" (33:13). Sahih al-Bukhari records the Prophet ﷺ saying that people called it Yathrib but it was Madinah. A Muslim learns that the old name survives in the Qur'an in the mouths of those who wished to abandon the city.",

"sira_059": "The long hadith of Hudaybiyya in Sahih al-Bukhari 2731 tells that the Prophet ﷺ set out with more than a thousand companions to perform 'umra, and that at the pass near Makkah Al-Qaswa knelt and would not rise. The people said she had become stubborn, and the Prophet ﷺ answered that stubbornness was not her nature, but that the One who had held back the elephant from Makkah had held her back. He then swore to grant Quraysh any request that honoured the sanctity of Allah's House. A Muslim learns that the Prophet ﷺ read Allah's will even in the halting of his camel.",

"sira_060": "Every standard biography records that soon after arriving in Madinah the Prophet ﷺ gathered the emigrants and the helpers in the house of Anas ibn Malik and joined them as brothers two by two. The Qur'an praises the Ansar for this: \"those who settled in the home and in faith before them love those who emigrated to them, and find no need in their breasts for what the emigrants were given, and give them preference over themselves even though they are in need\" (59:9). Sahih al-Bukhari records that Sa'd ibn ar-Rabi' offered his brother 'Abd ar-Rahman ibn 'Awf half his wealth. A Muslim learns that brotherhood in faith was made real by sharing.",

"sira_061": "Every standard biography preserves the text of the document the Prophet ﷺ drew up on arriving in Madinah. It declares that the believers of Quraysh and of Yathrib, and whoever joins them, are one community apart from all other people; that the Jewish tribes who enter the pact are a community alongside the believers, the Jews having their religion and the Muslims theirs; that Yathrib is inviolable and will be defended together; and that any dispute is referred to Allah and to Muhammad ﷺ. A Muslim learns that the first Muslim city was founded on written obligations shared with its non-Muslim neighbours.",

"sira_062": "Sahih al-Bukhari 6452 records Abu Hurayra's account of his hunger: he would tie a stone to his belly, and once sat on the road hoping to be fed; Abu Bakr and 'Umar passed by without noticing. Then the Prophet ﷺ came, smiled and took him home, where a cup of milk had been sent as a gift. He told Abu Hurayra to call the people of the Suffa, the guests of Islam with no family or wealth, and to serve each until all had drunk their fill, then drank what remained himself. A Muslim learns that the poorest companions were the Prophet's ﷺ own guests.",

"sira_063": "Every standard biography places the battle in Ramadan of the second year after the Hijra, when the Prophet ﷺ set out with a little over three hundred men to intercept a Quraysh caravan and instead met an army of about a thousand from Makkah. The Qur'an calls that day the day of the criterion, the day the two armies met (8:41), and reminds the believers: \"Allah had already given you victory at Badr when you were few\" (3:123). A Muslim learns that Badr was the first proof that the small community in Madinah would survive.",

"sira_064": "The verse belongs to the account of Badr in Surah Al-Anfal: \"When you asked help of your Lord, and He answered you, 'Indeed, I will reinforce you with a thousand of the angels, following one another'\" (8:9). The next verse explains their purpose: \"Allah made it only as good tidings and so that your hearts would be assured; victory is only from Allah\" (8:10). The surah then recalls the drowsiness that calmed the believers and the rain that steadied their feet (8:11). A Muslim learns that help from Allah may come unseen, and that it is Allah, not numbers, who gives victory.",

"sira_065": "The hadith is narrated by al-Bara' ibn 'Azib in Sahih al-Bukhari 3039. The Prophet ﷺ placed 'Abdullah ibn Jubayr over fifty archers and told them not to leave their position, whether they saw the Muslims defeated or victorious, until he sent for them. When Quraysh broke and their women fled up the hillside, the archers said the spoils were there for the taking; Ibn Jubayr reminded them of the order, but they went down anyway, and their faces were then turned about. A Muslim learns that obeying the Prophet's ﷺ command mattered more than any gain of the moment.",

"sira_066": "Every standard biography places Mount Uhud a short ride north of Madinah, so that the Muslims marched out from the city and camped with the mountain at their backs. The Qur'an speaks of that morning: \"when you left your household to post the believers at their stations for the battle\" (3:121). Sahih al-Bukhari records the Prophet ﷺ saying that it is a mountain that loves us and we love it, and Hamza and the other martyrs were buried at its foot. A Muslim learns that a mountain of Madinah is remembered with affection because of who died beneath it.",

"sira_067": "Every standard biography records Salman's long journey: born in Persia, he left his father's fire-worship, served Christian monks in several towns, was told that a prophet would appear in a land of date palms, and reached Madinah as a slave, where the Prophet ﷺ helped him buy his freedom. When the confederates marched on Madinah, Salman proposed digging a trench across the open side of the city, a defence he had seen in Persia, and the Prophet ﷺ carried earth alongside the companions. A Muslim learns that good counsel is welcome whatever land it comes from.",

"sira_068": "The surah recalls the siege: \"O you who believe, remember the favour of Allah upon you when armies came to you and We sent upon them a wind and armies you did not see\" (33:9), \"when they came at you from above you and from below you, and when eyes shifted and hearts reached the throats\" (33:10). The believers, seeing the confederates, said this was what Allah and His Messenger had promised them (33:22), and Allah turned the disbelievers back having gained nothing (33:25). A Muslim learns that the siege was broken by a wind and by faith, not by a sword.",

"sira_069": "The verse reads: \"Certainly Allah was pleased with the believers when they pledged allegiance to you under the tree, and He knew what was in their hearts, so He sent down tranquillity upon them and rewarded them with an imminent conquest\" (48:18). Sahih al-Bukhari records the occasion: the Prophet ﷺ had sent 'Uthman into Makkah as his envoy, and when word came that he had been killed, the Prophet ﷺ called the companions to pledge themselves to him under a tree at Hudaybiyya. A Muslim learns that Allah Himself recorded His approval of those who stood by His Messenger ﷺ.",

"sira_070": "The surah begins: \"Indeed, We have given you a clear conquest, that Allah may forgive you what preceded of your sin and what will follow\" (48:1-2). Sahih al-Bukhari records that it came down on the road back from Hudaybiyya, and that the Prophet ﷺ said a surah had been revealed to him dearer than everything on which the sun rises. The companions had felt the treaty as a setback; the revelation named it a conquest. A Muslim learns that Allah's judgement of an event may be the reverse of what it looks like on the day.",

"sira_071": "Every standard biography places the treaty in Dhul-Qa'da of the sixth year after the Hijra, when the Prophet ﷺ had come to perform 'umra and Quraysh barred the way. Sahih al-Bukhari preserves its terms: the Muslims would return that year and come back the next for three days; there would be no fighting for ten years; and anyone who came from Quraysh to the Prophet ﷺ without permission would be sent back. The next year the Prophet ﷺ performed the 'umra as agreed. A Muslim learns that a hard peace, kept faithfully, opened the way to Makkah.",

"sira_072": "Sahih al-Bukhari 7 records, from Ibn 'Abbas, how Heraclius summoned Abu Sufyan and the Makkan traders in Syria and questioned him about the man claiming prophethood: his lineage, who followed him, whether he had ever lied or broken a pact, and what he commanded. Abu Sufyan, still an enemy, answered truthfully, and Heraclius concluded that if this was so, the man would one day rule the ground beneath his feet. The letter, then read out, quoted the call to the People of the Scripture to a common word (3:64). A Muslim learns that even an enemy's honest testimony bore witness to the Prophet ﷺ.",

"sira_073": "The hadith is narrated by Sahl ibn Sa'd in Sahih al-Bukhari 3701. The companions spent the night wondering who would receive the banner, and in the morning each hoped for it, but the Prophet ﷺ asked for 'Ali, who was suffering from his eyes; he applied his saliva, prayed for him, and 'Ali was healed as if nothing had troubled him. Handing him the banner, he told him to advance calmly and invite the people to Islam first, for Allah to guide one man through him was better than red camels. A Muslim learns that the aim of the banner was guidance before conquest.",

"sira_074": "The hadith is narrated by Anas in Sahih al-Bukhari 4262. Before any messenger had arrived from the battlefield, the Prophet ﷺ told the people in Madinah that Zayd had taken the banner and been struck down, then Ja'far, then Ibn Rawaha, his eyes flowing with tears as he spoke, until a sword among the swords of Allah took it and Allah granted them victory. Zayd ibn Haritha is the only companion named in the Qur'an (33:37). A Muslim learns that the Prophet ﷺ wept for his companions and honoured them in the order they fell.",

"sira_075": "The words come from the hadith of Anas in Sahih al-Bukhari 4262, in which the Prophet ﷺ said that the banner was then taken by a sword among the swords of Allah, through whom Allah gave the Muslims victory. Every standard biography identifies him as Khalid ibn al-Walid, who had led the Quraysh cavalry against the Muslims at Uhud and accepted Islam after the treaty of Hudaybiyya; at Mu'ta he drew the army back to safety. A Muslim learns that a title given by the Prophet ﷺ can outlast a man's earlier enmity.",

"sira_076": "The hadith is narrated by Ibn Mas'ud in Sahih al-Bukhari 4287: when the Prophet ﷺ entered Makkah on the day of the conquest, there were three hundred and sixty idols around the Ka'ba, and he went among them striking them with a stick and reciting: \"Truth has come and falsehood has vanished; indeed falsehood is ever bound to vanish\" (17:81), together with a verse of Surah Saba (34:49). The first verse had been revealed years earlier in Makkah, while the idols still stood. A Muslim learns that the House built for the worship of Allah alone was cleared in the words of the Qur'an itself.",

"sira_077": "Every standard biography records that on the day Makkah was conquered, after the idols had been cleared from the Ka'ba, the Prophet ﷺ ordered Bilal to climb onto its roof and give the call to prayer, and the voice of the former slave rang out over the city where he had once been tortured for saying that Allah is One. Bilal had been the Prophet's ﷺ caller to prayer since the adhan was instituted in Madinah, as Sahih al-Bukhari records. A Muslim learns that in Islam, standing comes from faith and not from birth.",

"sira_078": "Every standard biography records that on the day of the conquest the Prophet ﷺ stood at the door of the Ka'ba before the assembled Quraysh, who had fought him for years, and asked them what they thought he would do with them. They answered that he was a noble brother and the son of a noble brother. He replied with the words of Yusuf to his brothers: \"No blame upon you today; Allah will forgive you\" (12:92), and then told them to go, for they were free. A Muslim learns that the greatest victory of the Prophet ﷺ was sealed with forgiveness.",

"sira_079": "The verses read: \"...and on the day of Hunayn, when your great number pleased you, but it availed you nothing, and the earth, vast as it is, was straitened for you; then you turned back, fleeing. Then Allah sent down His tranquillity upon His Messenger and upon the believers, and sent down soldiers you did not see\" (9:25-26). Every standard biography places the battle soon after the conquest of Makkah, against Hawazin and Thaqif; the Prophet ﷺ held his ground on his mule until the companions rallied. A Muslim learns that reliance on numbers is a weakness, and reliance on Allah a strength.",

"sira_080": "Ka'b tells his own story in Sahih al-Bukhari 4418. He kept putting off his departure for Tabuk until the army was gone. When the Prophet ﷺ returned, the hypocrites came with excuses and oaths and were let go, but Ka'b said he had no excuse at all; the Prophet ﷺ answered that this man had spoken the truth, and ordered the Muslims not to speak to him. On the fiftieth morning the verse came down: \"And upon the three who were left behind\" (9:118). A Muslim learns that a hard truth told to the Prophet ﷺ was better than any easy lie.",

"sira_081": "Every standard biography records that once Makkah had entered Islam, the tribes of Arabia sent delegations to Madinah to declare their Islam before the Prophet ﷺ; among them came Thaqif of Ta'if, the town that had driven him out. The Qur'an speaks of this season: \"When the victory of Allah has come and the conquest, and you see the people entering the religion of Allah in multitudes, then glorify your Lord with praise and ask His forgiveness\" (110:1-3). A Muslim learns that the answer to a flood of new believers was praise and humility.",

"sira_082": "Every standard biography records that during his only pilgrimage the Prophet ﷺ addressed the pilgrims at Arafat, telling them that their blood and property were as sacred to one another as that day, that month and that city, and that he was leaving among them the Book of Allah, which whoever held fast to would never go astray. When they affirmed that he had conveyed the message, he called on Allah to bear witness, three times. The verse announcing the perfection of the religion was revealed at Arafat that same day (5:3). A Muslim learns that the Prophet's ﷺ last public words were about the sanctity of life and the keeping of the Qur'an.",

"sira_083": "The full passage reads: \"This day those who disbelieve have despaired of your religion. This day I have perfected for you your religion and completed My favour upon you, and I have approved for you Islam as religion\" (5:3). Sahih al-Bukhari records that a Jewish man said to 'Umar that had this verse come to the Jews they would have made that day a festival, and 'Umar replied that it came down while the Prophet ﷺ stood at Arafat on a Friday. A Muslim learns that the religion was declared complete during the Farewell Pilgrimage, with nothing left to be added.",

"sira_084": "Every standard biography records that after the Farewell Pilgrimage the Prophet ﷺ returned to Madinah, fell ill some months later in the eleventh year after the Hijra, and died on a Monday in the room of his wife 'Aisha beside his mosque. Sahih al-Bukhari records that his last words were a prayer for the highest companionship. He was buried in the room where he died, and Abu Bakr and 'Umar were later laid beside him. A Muslim learns that the city that welcomed the Prophet ﷺ in the Hijra is the city that keeps his grave.",

"sira_085": "Sahih al-Bukhari records 'Aisha's account of the last day: the Prophet ﷺ died resting against her chest, and she counted it a favour from Allah that it happened in her house and on her day. He was buried in that room, and every standard biography records that Abu Bakr and then 'Umar were buried beside him. When the mosque was later enlarged the room was enclosed within it, so his grave now lies inside the Prophet's Mosque. A Muslim learns that the Prophet ﷺ died in a small room among his family, with nothing of a king's ceremony.",

"sira_086": "The hadith is narrated by 'Aisha and recorded in Sahih al-Bukhari 3667. Abu Bakr came in, uncovered the Prophet's ﷺ face, kissed him and wept. He then went out to the mosque, where 'Umar was telling the people that the Prophet ﷺ had not died, told him to sit, spoke the words the question quotes, and recited: \"Muhammad is not but a messenger; messengers have passed on before him. If he dies or is killed, will you turn back on your heels?\" (3:144). A Muslim learns that grief for the Prophet ﷺ is right, but that worship belongs to Allah alone.",

"sira_087": "Every standard biography records that al-Hasan and al-Husayn were born in Madinah to Fatima, the Prophet's ﷺ daughter, and 'Ali, and that their grandfather carried them on his shoulders, sat them on his lap and let them climb on his back. Sahih al-Bukhari records him saying of al-Hasan, \"O Allah, I love him, so love him, and love whoever loves him,\" and calling the two of them his two sweet-scented flowers of this world. A Muslim learns that the Prophet ﷺ showed his tenderness for children openly and asked others to love them.",

"sira_088": "Every standard biography records that the Prophet ﷺ married 'Aisha, daughter of his closest companion Abu Bakr, after the death of Khadija, and that she lived with him in the room beside the mosque where he later died. Sahih al-Bukhari records that when he was asked whom he loved most, he answered 'Aisha, and when asked among men, her father. After his death she lived on for many years in Madinah, and companions and their students came to her to learn. A Muslim learns that much of what is known of the Prophet's ﷺ home life comes from the wife who remembered it.",

"sira_089": "Every standard biography records that Hafsa's first husband died after Badr, and that her father 'Umar offered her in marriage to Abu Bakr and to 'Uthman, who both declined, before the Prophet ﷺ himself asked for her. Sahih al-Bukhari records that after 'Umar's death the sheets on which the Qur'an had been collected in Abu Bakr's time were kept with Hafsa, and that 'Uthman borrowed them to make the copies he sent to the cities, returning them to her afterwards. A Muslim learns that the text of the Qur'an passed through the keeping of a wife of the Prophet ﷺ.",

"sira_090": "Every standard biography records that Abu Hurayra came to the Prophet ﷺ in the year of Khaybar, lived among the poor of the Suffa and stayed constantly at his side. Sahih al-Bukhari records his own explanation: the Muhajirun were busy in the markets and the Ansar with their land, while he followed the Prophet ﷺ on an empty stomach; and when he complained of forgetting, the Prophet ﷺ had him spread out his cloak and hold it to his chest, after which he forgot nothing. A Muslim learns that the largest store of hadith was kept by a man who chose company over trade.",
}
