"""English — details, virtues_c (50 questions)."""

D = {
"virtues_051": "The verse is the last of the counsels Luqman gives his son in Surah Luqman: \"And be moderate in your pace and lower your voice; indeed, the most disagreeable of sounds is the voice of donkeys\" (31:19). Just before, he told him not to turn his cheek away from people in contempt nor walk the earth exultantly, \"for Allah does not like every self-deluded boaster\" (31:18). His advice moves from faith in Allah alone (31:13) down to the small habits of walking and speaking. A Muslim learns that a quiet voice and a measured step are part of good character, not a matter of taste.",

"virtues_052": "Luqman's counsel to his son in Surah Luqman closes with a verdict on the whole set: \"Indeed, that is of the matters requiring determination\" (31:17). The verse just before has told the boy that even a deed the weight of a mustard seed, hidden in a rock or in the heavens or the earth, Allah will bring forth (31:16). Prayer, enjoining right, forbidding wrong and patience are thus set on the ground of that knowledge: nothing done is lost. A Muslim learns that prayer comes first, that caring for the good of others follows it, and that patience keeps both going.",

"virtues_053": "The verse describes the people for whom Paradise is prepared: the one before it calls the believers to \"hasten to forgiveness from your Lord and a garden as wide as the heavens and the earth, prepared for the righteous\" (3:133), and 3:134 then names them by their deeds. The next verse adds a fourth trait: when they wrong themselves, they remember Allah, ask forgiveness for their sins, and do not knowingly persist (3:135). Generosity, swallowed anger, pardon and repentance are put side by side as one character. A Muslim learns that holding back anger and forgiving people are good deeds that Allah loves.",

"virtues_054": "The verse ends with two names of Allah: \"Kind speech and forgiveness are better than charity followed by injury. And Allah is Free of need and Forbearing\" (2:263). It sits in a passage of Surah Al-Baqarah on spending: the verse before promises the reward of those who give and then do not follow their gift with reminders or hurt (2:262), and the verse after tells the believers not to void their charities with reminders and injury, like one who gives to be seen by people (2:264). A Muslim learns that a gift is measured by the way it is given, and that a gentle refusal is worth more than a wounding gift.",

"virtues_055": "The verse goes on to say what secret charity does for the giver: \"and He will remove from you some of your misdeeds. And Allah, with what you do, is Acquainted\" (2:271). The verse before has said that whatever a person spends or vows, Allah knows it (2:270), and the verse after adds that whatever good is spent is for the giver's own soul and will be repaid in full (2:272). Open giving is called good; hidden giving to the poor is called better and is joined to the wiping away of sins. A Muslim learns to give without an audience, trusting the One who sees.",

"virtues_056": "The verse opens with what should be given before it names what should not: \"O you who have believed, spend from the good things you have earned and from what We have brought out of the earth for you\" (2:267), and it closes with \"And know that Allah is Free of need and Praiseworthy\". The next verse names the fear that makes a person give the worst: \"Shaytan threatens you with poverty and orders you to immorality, but Allah promises you forgiveness from Him and bounty\" (2:268). A Muslim learns to give from what is good in his hands, and to answer the fear of poverty with trust in Allah's promise.",

"virtues_057": "The verse continues: \"And whatever you spend, indeed Allah is Knowing of it\" (3:92). It comes right after a verse about those who die in disbelief, from whom an earth full of gold would not be accepted as ransom (3:91): gold offered too late buys nothing, while a loved thing given now for Allah's sake reaches righteousness itself. Surah Al-Baqarah counts giving wealth, despite love for it, to relatives, orphans and the needy among the marks of the truly righteous (2:177). A Muslim learns that giving what costs him nothing is not yet the giving the Qur'an praises.",

"virtues_058": "The image belongs to a run of counsels in Surah Al-Isra. Two verses earlier the believer is told to give the relative, the poor and the traveller their due and not to squander, \"for the squanderers are brothers of the devils\" (17:27); the verse just before says that if one has nothing to give, one should at least speak a gentle word (17:28). Then come the hand chained to the neck, the hand flung wide open, and the end of both: sitting \"blamed and destitute\" (17:29). A Muslim learns that generosity has two edges to avoid, meanness and waste, and that the middle is where dignity stays.",

"virtues_059": "The verse is one line in the portrait of \"the servants of the Most Merciful\" at the end of Surah Al-Furqan. The portrait opens with their walk and their speech: they \"walk upon the earth humbly, and when the ignorant address them, they say words of peace\" (25:63); it goes on to their nights spent prostrating and standing (25:64). Then their spending is described (25:67), and the verse after turns to what they never do: call on another god, take a life unjustly, or commit unlawful intercourse (25:68). A Muslim learns that how he handles money belongs to the same portrait as how he prays and how he speaks.",

"virtues_060": "The verse ends with its reason: \"That is best for you, that you may be reminded\" (24:27). It opens a short passage of Surah An-Nur on the home: the next verse says that if no one is found inside, one does not enter until permission is given, and that if one is told to go back, one goes back, \"it is purer for you\" (24:28); the verse after excuses entering uninhabited buildings where one has some business (24:29). A Muslim learns that a home is a protected space, and that asking leave and greeting at the threshold are part of entering it rightly.",

"virtues_061": "The explanation gives the second half of the verse; the first half deals with a house where no one answers: \"And if you do not find anyone in them, do not enter until permission has been given to you\" (24:28). Then comes the order to leave when asked, and the verse closes, \"And Allah is Knowing of what you do\". The verse before has set the rule for every house that is not one's own: no entering before asking leave and greeting its people (24:27). A refusal at the door is a right of the household, not a slight. A Muslim learns to leave without offence when he is not received.",

"virtues_062": "The verse stands in Surah Al-Hujurat, a surah of manners for the community of believers, after verses on lowering one's voice before the Prophet ﷺ (49:2-5) and before the command to make peace between fighting believers (49:9). The verse after it reminds the believers that the Messenger of Allah is among them and that, if he followed their wishes in many matters, they would fall into hardship (49:7). The reasoning of 49:6 is stated in the verse itself: a report accepted unchecked can harm innocent people, and regret comes too late. A Muslim learns to pause before a rumour and to weigh the one who brings it.",

"virtues_063": "The verse goes on to give backbiting a picture: \"Would one of you like to eat the flesh of his dead brother? You would detest it. And fear Allah; indeed, Allah is Accepting of repentance and Merciful\" (49:12). The verse before has forbidden mocking others, insulting one another and calling people by offensive nicknames (49:11), and the verse after says that Allah made peoples and tribes so that they may know one another (49:13). Suspicion, spying and backbiting are set out as three steps of one path, each feeding the next. A Muslim learns to guard the honour of an absent brother as he would guard his body.",

"virtues_064": "The verse fills in what the explanation's ellipsis leaves out: if one of the two groups wrongs the other, the believers side against the wrongdoer \"until it returns to the command of Allah\", and only then is peace made \"between them in justice\" (49:9). The verse after gives the reason the whole community is concerned: \"The believers are but brothers, so make peace between your brothers, and fear Allah that you may receive mercy\" (49:10). Reconciliation is thus not silence about wrong but a settlement that sets it right. A Muslim learns that a quarrel between believers is every believer's business, and that peace must be just to last.",

"virtues_065": "The verse opens with a command that frames the one quoted: \"O you who have believed, be steadfast for Allah, witnesses in justice\" (5:8), and it closes with \"And fear Allah; indeed, Allah is Acquainted with what you do\". Earlier in the same surah the believers are told not to let their hatred of a people who had barred them from the Sacred Mosque drive them to transgress (5:2), so the warning against hatred is given twice in Surah Al-Ma'idah. To be fair to an enemy is described as the nearer road to fearing Allah. A Muslim learns that dislike of a person, however strong, never excuses treating him unjustly.",

"virtues_066": "The verse continues past the names it lists: \"Whether one is rich or poor, Allah is more worthy of both. So do not follow desire, lest you swerve from justice. And if you distort your testimony or refuse to give it, then indeed Allah is ever Acquainted with what you do\" (4:135). Three pulls on a witness are named in turn: love of self and family, awe or pity before wealth and poverty, and plain desire. Surah Al-Ma'idah gives the mirror of this verse, where the pull is hatred rather than love (5:8). A Muslim learns that truthful witness is owed to Allah first, and that neither kinship nor sympathy may bend it.",

"virtues_067": "The verse closes with praise of its own instruction: \"Excellent is that which Allah instructs you. Indeed, Allah is ever Hearing and Seeing\" (4:58). The verse after turns to the other side of the relationship, telling the believers to obey Allah, the Messenger and those in authority among them (4:59): trusts are to be returned and judgement made justly by those who hold responsibility, and obedience is owed by those under it. Surah Al-Mu'minun counts keeping trusts among the marks of the believers who succeed (23:8). A Muslim learns that whatever is placed in his hands, an object, a secret or an office, must reach the one it belongs to.",

"virtues_068": "The verse begins with the worship of Allah alone and ends with a warning: \"Indeed, Allah does not like those who are self-deluding and boastful\" (4:36). The next verse describes them: those who are stingy, who tell others to be stingy, and who hide what Allah has given them of His bounty (4:37). So the long list of people owed kindness is fenced on one side by tawhid and on the other by the vice that breaks kindness, arrogance joined to meanness. Surah Al-Isra gives the same order, worship of Allah alone followed at once by goodness to parents (17:23). A Muslim learns that good treatment widens in circles, from home outward to the stranger on the road.",

"virtues_069": "The verse ends with a phrase the explanation leaves off: \"if you only knew\" (2:280). It follows the verses that forbid usury and tell the believers to give up what remains of it, taking back only their capital, \"so you do no wrong, nor are you wronged\" (2:279); and it is followed by a call to fear the Day on which every soul will be paid in full for what it earned (2:281). The creditor is told, in one breath, that his right is real and that his mercy is better than his right. A Muslim learns to treat a struggling debtor with patience, and to see forgiving a debt as a gift stored with Allah.",

"virtues_070": "The verse goes on to say how the writing is done: a scribe writes \"in justice\", the one who owes the debt dictates and fears Allah, and two witnesses are called (2:282). It tells the believers not to grow weary of writing a debt down, \"whether small or large, to its term\", and gives the reason: \"that is more just in the sight of Allah, stronger as evidence and more likely to prevent doubt between you\" (2:282). The verse after allows a pledge in hand when no scribe is found on a journey (2:283). A Muslim learns that clear records protect both sides and are part of fearing Allah in dealings, not a sign of distrust.",

"virtues_071": "The verse ends on two words the explanation omits: \"while you know\" (2:188), so the wrong it describes is one done knowingly. It stands right after the verses of Surah Al-Baqarah on the fast of Ramadan, which close with \"these are the limits of Allah, so do not approach them\" (2:187), and before a verse on the new moons as markers of time and of the pilgrimage (2:189). Surah An-Nisa repeats the prohibition and gives the lawful way in its place: trade by mutual consent (4:29). A Muslim learns that wealth taken by fraud or by paying off a judge is not his, however legal the paperwork looks.",

"virtues_072": "The verse ends with a judgement the explanation leaves out: \"Indeed, that is ever a great sin\" (4:2). Surah An-Nisa returns to the matter a few verses later, telling guardians to test orphans until they reach the age of marriage and, once sound judgement is seen in them, to hand over their property, neither wasting it nor hurrying to spend it before they grow up (4:6). Then it gives the harshest image: those who devour the wealth of orphans unjustly \"are only consuming fire into their bellies\" (4:10). A Muslim learns that an orphan's property is a trust to be kept whole and returned, not a resource for its keeper.",

"virtues_073": "The command comes among the counsels of Surah Al-Isra, right after the order not to touch an orphan's property except in the best way and to fulfil every commitment, \"for the commitment will be asked about\" (17:34), and right before the warning not to follow what one has no knowledge of (17:36). Surah Al-Mutaffifin shows the fault the verse guards against: people who take full measure when they buy but give less when they sell (83:1-3), and it asks whether they do not think they will be raised for a tremendous Day (83:4-5). Honest scales are \"best and fairest in result\" (17:35). A Muslim learns that exactness in giving others their due is a form of worship, not merely good business.",

"virtues_074": "The verse follows the command to give full measure and weigh justly (17:35) and precedes the warning against walking the earth in pride (17:37), so it stands between honesty in trade and humility in bearing. It counts three faculties, hearing, sight and heart, and says of each that it will be questioned (17:36): what a person listens to, looks at and believes are all his responsibility. The passage closes with the words \"all that, its evil is ever hateful to your Lord\" (17:38). A Muslim learns not to repeat what he has not verified and not to accuse on a guess, since his ears, eyes and heart will answer for it.",

"virtues_075": "The verse turns pride into a matter of plain size: a man who struts cannot split the ground under him nor grow as tall as the mountains around him (17:37), and the passage then closes, \"All that, its evil is ever hateful to your Lord\" (17:38). Luqman gives his son the same counsel in Surah Luqman: do not walk the earth exultantly, \"indeed, Allah does not like every self-deluded boaster\" (31:18); and \"the servants of the Most Merciful\" are first described as those who \"walk upon the earth humbly\" (25:63). A Muslim learns to carry himself modestly, because his own body shows him how small he is.",

"virtues_076": "The promise ends with its third gift: \"And whoever obeys Allah and His Messenger has certainly attained a great attainment\" (33:70-71). The two verses come just after the believers are told not to be like those who hurt Musa, whom Allah then cleared of what they said (33:69), and just before the verse on the Trust that the heavens, the earth and the mountains declined to bear and man took up (33:72). Upright speech is thus placed between the harm of slander and the weight of responsibility. A Muslim learns that choosing straight, true words is a door through which his other deeds are set right and his sins forgiven.",

"virtues_077": "The command is given to Musa and his brother Harun as they are sent to Pharaoh: \"Go, both of you, to Pharaoh; indeed, he has transgressed\" (20:43), and then the instruction to use gentle words, \"that he may be reminded or fear\" (20:44). The two answer that they are afraid he will act hastily against them or overstep, and Allah replies: \"Fear not. Indeed, I am with you both; I hear and I see\" (20:46). Gentle speech is asked of them at the very moment they feel most threatened, so that the listener has a chance to remember. A Muslim learns that softness in words is a strategy of truth, not a sign of weakness.",

"virtues_078": "The verse joins three things in one person: a call to Allah, a righteous life, and open belonging to Islam (41:33). The verses that follow show how such a caller behaves when he is opposed: \"Repel evil with what is better, and the one between whom and you there is enmity will become as though he were a devoted friend\" (41:34), and the surah adds that this is granted only to the patient, to \"one having a great portion\" (41:35). The best speech is thus not only what is said but the conduct that carries it. A Muslim learns that inviting others to Allah is done as much by good character as by words.",

"virtues_079": "The verse is the third of a list that opens Surah Al-Mu'minun: \"Certainly will the believers have succeeded: those who are humbly submissive in their prayer\" (23:1-2), \"and those who turn away from idle talk\" (23:3). The list continues with paying zakat (23:4), guarding chastity (23:5), keeping trusts and covenants (23:8) and guarding the prayers (23:9), and ends with the promise that these will inherit Firdaws forever (23:10-11). Turning from laghw is set between humility in prayer and generosity with wealth, as one of the traits that earn Paradise. A Muslim learns to spend his tongue and his time on what has weight.",

"virtues_080": "The verse (23:8) belongs to the list of traits that opens Surah Al-Mu'minun, after humility in prayer (23:2), turning from idle talk (23:3), paying zakat (23:4) and guarding chastity (23:5), and just before guarding the prayers (23:9); the list ends with the inheritance of Firdaws (23:10-11). The same words, \"those who are attentive to their trusts and their covenant\", appear again in Surah Al-Ma'arij, in a second list of those who will be honoured in gardens (70:32). Surah An-Nisa gives the command behind the trait: render trusts to those they are due (4:58). A Muslim learns that a promise given and a thing entrusted are debts of faith.",

"virtues_081": "The verse closes with words the explanation omits: \"Indeed, He does not like wrongdoers\" (42:40). It stands in a passage of Surah Ash-Shura that first describes believers who defend themselves when tyranny strikes them (42:39), then allows a like-for-like response, then says that whoever takes his due after being wronged bears no blame (42:41). Having granted the right, the passage ends: \"And whoever is patient and forgives, indeed that is of the matters requiring determination\" (42:43). Retaliation is thus permitted and limited, while pardon is rewarded by Allah Himself. A Muslim learns that he may answer a wrong in measure, and that letting it go is the higher road.",

"virtues_082": "The verse begins with the people it addresses: \"And let not those of virtue and wealth among you swear not to give to their relatives, the needy and the emigrants in the cause of Allah\" (24:22). It comes at the close of the passage of Surah An-Nur on the slander that the Qur'an calls a falsehood and \"a great lie\", and whose spreaders it warns of punishment (24:11-16). People with means are asked not to swear off the charity they used to give, and the argument is turned on themselves: their own hope of forgiveness. A Muslim learns to measure his pardon of others by the pardon he asks of Allah.",

"virtues_083": "The verse is addressed to the Prophet ﷺ near the end of Surah Al-A'raf, after verses about those who are called upon besides Allah and can neither help nor hear (7:197-198). Its third counsel, turning away from the ignorant (7:199), is followed at once by what to do when the provocation comes from within: \"And if an evil suggestion comes to you from Shaytan, then seek refuge in Allah; indeed, He is Hearing and Knowing\" (7:200). The next verse says that the God-fearing, when a touch from Shaytan reaches them, remember and at once see clearly (7:201). A Muslim learns to accept what people manage to give, to keep urging the good, and not to quarrel with foolishness.",

"virtues_084": "The verse opens with a sentence the explanation leaves out: \"You will surely be tested in your wealth and in yourselves\" (3:186), and it names two sources of hurtful words, those given the Scripture before and those who associate others with Allah. It follows the verse that says every soul will taste death and that the life of this world is only the enjoyment of delusion (3:185). Trial in property, trial in one's person and trial by other people's tongues are announced together, and one answer is given for all three. A Muslim learns to expect insult when he holds to his faith, and to meet it with patience rather than with an answer in kind.",

"virtues_085": "The verse closes the passage of Surah Ash-Shura on responding to wrong. The passage first affirms that believers defend themselves when tyranny strikes them (42:39), sets the limit of an evil returned only with its like, and promises that whoever pardons and reconciles has his reward with Allah (42:40); it adds that one who takes his due after being wronged is not to blame (42:41). Then comes 42:43, which places patience and forgiveness above what is merely allowed. The same phrase describes Luqman's counsel of patience to his son (31:17) and the patience asked of believers who hear abuse (3:186). A Muslim learns that forgiving is not weakness but the harder, resolute choice.",

"virtues_086": "The verse after tells who the humbly submissive are: \"those who are certain that they will meet their Lord and that they will return to Him\" (2:46). The command of 2:45 is addressed, in this early part of Surah Al-Baqarah, to the Children of Israel, just after they are asked how they can order others to righteousness while forgetting themselves though they recite the Scripture (2:44). The same pairing is given later to the believers: \"O you who have believed, seek help through patience and prayer; indeed, Allah is with the patient\" (2:153). A Muslim learns that what makes prayer light is certainty of the meeting with his Lord.",

"virtues_087": "The verse begins with the hard thing it is talking about: \"Fighting has been prescribed for you while it is hateful to you\" (2:216). The verse does not pretend the burden is pleasant; it only says that the believers' dislike is not the measure of what is good for them, and ends by contrasting Allah's knowledge with their own. Surah An-Nisa applies the same reasoning to a marriage one has come to dislike, in which Allah may place much good (4:19). A Muslim learns to accept what Allah has decreed or commanded without assuming that what feels heavy is harmful, and to trust the One who knows the outcome.",

"virtues_088": "The promise continues beyond the two gifts named: \"And whoever relies upon Allah, then He is sufficient for him. Indeed, Allah will accomplish His purpose; Allah has set for everything a measure\" (65:2-3). The words come in the middle of the rulings of Surah At-Talaq on divorce and the waiting period, a time of strain in a household, and the surah repeats the pattern: whoever fears Allah, He makes his affair easy (65:4), removes his misdeeds and enlarges his reward (65:5). The way out is thus promised precisely where the door seems shut. A Muslim learns to hold to taqwa and trust in hard passages, because that is where relief is promised.",

"virtues_089": "The verse gives its reason before the command: \"And We have enjoined upon man care for his parents; his mother carried him in weakness upon weakness, and his weaning is in two years\" (31:14). It is set inside Luqman's counsels to his son, right after his warning that associating anything with Allah is a great wrong (31:13), and the next verse fixes the limit: if parents press their child to associate with Allah what he has no knowledge of, he does not obey them, yet keeps their company in this world with kindness (31:15). A Muslim learns that thankfulness to Allah and thankfulness to parents are spoken in one breath because the second is part of the first.",

"virtues_090": "The verse opens with the duty and closes with the reckoning: \"And We have enjoined upon man goodness to parents\" and, after the limit, \"To Me is your return, and I will inform you of what you used to do\" (29:8). Surah Luqman states the same limit and adds how the child still treats such parents: he does not obey them in this, but accompanies them in this world with kindness (31:15). In Surah Al-'Ankabut the verse stands between two promises to those who believe and do righteous deeds (29:7, 29:9). A Muslim learns that a parent's authority is real and wide, and that it ends only where Allah's right begins.",

"virtues_091": "The prayer is placed in a man's mouth at a set moment of life: when he reaches full strength and forty years, the verse says, he says it (46:15), and it ends with words the explanation leaves out: \"Indeed, I have repented to You, and indeed, I am of the Muslims\". Before the prayer the verse recalls the mother who carried him with hardship and bore him with hardship, thirty months of pregnancy and weaning. The next verse answers: from such people the best of their deeds is accepted and their misdeeds overlooked (46:16). A Muslim learns a prayer that binds three generations: thanks for his parents, uprightness for himself, and righteousness for his children.",

"virtues_092": "This prayer is the last trait in the portrait of \"the servants of the Most Merciful\" in Surah Al-Furqan, and the next verses give their reward: \"Those will be awarded the highest chamber for what they patiently endured, and they will be received there with greeting and peace\" (25:75). Just before the prayer, the servants are described as those who, when reminded of their Lord's verses, do not fall over them deaf and blind (25:73); their asking for good families follows their own attentiveness to revelation (25:74). The prayer asks for the family to become a model others follow in taqwa. A Muslim learns to pray for his household and to want it to be righteous, not merely happy.",

"virtues_093": "The verse follows the gravest sins the servants of the Most Merciful avoid, associating another god with Allah, killing unjustly and unlawful intercourse (25:68), and the promise that for those who repent, believe and do good, Allah replaces their evil deeds with good ones (25:70). Then two smaller things are named: they do not bear false witness, and when they pass by what is idle, they pass on with dignity (25:72). The next verse adds that when their Lord's signs are recited to them, they do not fall upon them deaf and blind (25:73). A Muslim learns to walk past what does not deserve his attention without contempt and without joining in.",

"virtues_094": "The verse goes on to a second courtesy and a promise: \"And when you are told to rise, then rise; Allah will raise those who have believed among you and those who were given knowledge by degrees. And Allah is Acquainted with what you do\" (58:11). The verses before it deal with private talk in a gathering, telling the believers not to confer in secret about sin and enmity but about righteousness and taqwa (58:9). Making room is answered by Allah making room, and standing when asked is answered by Allah raising in rank. A Muslim learns that small acts of courtesy in a gathering are noticed by Allah and rewarded in kind.",

"virtues_095": "The command comes at the end of an account of forgiveness in Surah At-Tawbah: Allah turned in mercy to the Prophet ﷺ and to those who followed him in the hour of hardship (9:117), and to three men who had been left behind, until the earth, for all its breadth, closed in on them and they knew there was no refuge from Allah except in Him (9:118). The next verse then tells the believers to fear Allah and be with the truthful (9:119). Surah Al-Ma'idah names the day on which this quality pays: \"This is the Day when the truthful will benefit from their truthfulness\" (5:119). A Muslim learns to choose his company by honesty, and to tell the truth even when a lie would be easier.",

"virtues_096": "The verse continues with what the Prophet ﷺ is not to do: let his eyes pass beyond these people \"desiring the adornment of the worldly life\", or obey one \"whose heart We have made heedless of Our remembrance, who follows his desire and whose affair is ever in neglect\" (18:28). The verse after leaves each person his choice: \"The truth is from your Lord, so whoever wills, let him believe, and whoever wills, let him disbelieve\" (18:29). Surah Al-An'am gives the Prophet ﷺ the same instruction, not to drive away those who call on their Lord morning and evening seeking His face (6:52). A Muslim learns to seek out those who remember Allah and to stay with them, whatever their rank.",

"virtues_097": "The command comes at the end of the second verse of Surah Al-Ma'idah, just after the believers are told not to let hatred of a people who once barred them from the Sacred Mosque push them into transgression, and just before its closing warning: \"And fear Allah; indeed, Allah is severe in penalty\" (5:2). The verse opens with respect for the rites of Allah and for the pilgrims heading to the Sacred House, so cooperation is asked of people who have just been reminded of an old grievance. Helping one another takes its value from what it serves. A Muslim learns to ask, before joining any effort, whether it is righteousness or wrong that he is helping to build.",

"virtues_098": "The verse gives the reason its oaths bind: \"while you have made Allah a witness over you. Indeed, Allah knows what you do\" (16:91). It follows the verse in which Allah commands justice, good conduct and giving to relatives, and forbids immorality, wrong and oppression (16:90), and it is followed by a picture of the oath-breaker: a woman who unravels her yarn after it was firmly spun, using oaths as a means of deceit between people (16:92). A confirmed oath is thus something made strong and then torn apart by the one who breaks it. A Muslim learns that a promise sworn with Allah's name is kept because Allah was called to witness it.",

"virtues_099": "The hadith is narrated by Anas ibn Malik and recorded in Sahih al-Bukhari 13, in the Book of Faith, under a chapter heading which states that loving for one's brother what one loves for oneself is part of faith. Its wording is a denial: the Prophet ﷺ did not say such a man has more faith, but that faith is not complete without this. The Qur'an gives the ground of the brotherhood the hadith assumes, \"the believers are but brothers\" (49:10), and praises the Ansar who gave preference to others over themselves even when in need (59:9). A Muslim learns to test his own faith by a simple question: does he want for others the good he wants for himself?",

"virtues_100": "The verse ends with a condition and a promise: \"And whoever does that seeking the approval of Allah, We are going to give him a great reward\" (4:114). It comes in a passage of Surah An-Nisa about people who hide from others but not from Allah, who is with them when they spend the night in talk He does not accept (4:108), and it turns their secret talk into a test: whispering is worthless except when it serves charity, kindness or peace between people. Surah Al-Mujadilah gives the believers the same rule for their own private talk: not sin and enmity, but righteousness and taqwa (58:9). A Muslim learns to ask what a private conversation is for, and to make sure it is for people's good.",
}
